### ISSUE TITLE
Test insert into a table with row filter for connector that support missing columns on insert  

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#10007]
We should use `MockConnector` to simulate connector that support missing columns on insert  and test if row filtering is properly handled if columns are missing during the insert but used in row filters.

Related to: #10006 and #10005

**Comment by tangjiangling** [comment]
@kokosing Is anyone fixing this, if not I'd like to try it.

**Comment by kokosing** [comment]
There is a PR already in flight: https://github.com/trinodb/trino/pull/10412

**Comment by tangjiangling** [comment]
Got it.

**Comment by kokosing** [comment]
Closed via https://github.com/trinodb/trino/pull/10581
