### ISSUE TITLE
Request: non-shaded jdbc-client jar.

### ISSUE THREAD

**Issue by kazuki-ma** [trinodb/trino#10043]
We want using `trino-jdbc` with `trino-client`.

It's ideal that execute query manually by `trino-client` and polling query status.
And finally got Result as [TrinoResultSet](https://github.com/trinodb/trino/blob/master/client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java#L49).

This use case example is a little hackly, but anyway I think it's good idea that providing non-shaded version jar for users who use both `trino-jdbc` and `trino-client` in same JVM.

**Comment by kazuki-ma** [comment]
It can be done by reverting this change. https://github.com/trinodb/trino/commit/20b9ecc2a7c33ae46d06eda67c1a7f003d1652cf#diff-abbafaa99c782dae61a776be596447a957e78257c663195c441958c56bd7909eL155 (add `<shadedClassifierName>standalone</shadedClassifierName>` etc).

`hive-jdbc` uses this way. They provides non-shaded version without classifier and shaded version with `standalone`.
https://repo1.maven.org/maven2/org/apache/hive/hive-jdbc/3.1.2/#:~:text=hive-jdbc-3.1.2-standalone.jar

How do you think?

**Comment by ebyhr** [comment]
I'm not sure why you need to use trino-client module for such use case. How about using `TrinoStatement.setProgressMonitor()` method for polling query status in trino-jdbc module?

**Comment by kazuki-ma** [comment]
Aha, thank you for your response.

Actually, I'm considering refactor of query frontend.

> Yanagishima is an open-source Web application for Trino, Hive and Spark.
> https://github.com/yanagishima/yanagishima

Current implementation polling query status by `trino-client` based on query id.
(We need to check query status only by query id, without sharing `Statement` instance. Because query status polling is occurred on another HTTP request)

That's a reason we want to use `trino-client` directly.


But as you mentioned, instead of submitting query by `StatementClient(trino-client)` first and try to create `ResultSet (trino-jdbc)` later, there is a way that executing the Query in `trino-jdbc` first and polling query status via `trino-client`.

**Comment by kazuki-ma** [comment]
FYI: I was originally trying to improve the fact that hive and trino have completely different code paths in our usage. hive uses a JDBC ResultSet, but trino (Presto) uses `StatementClient#currentData`. I wanted to convert this to a ResultSet.

**Comment by findepi** [comment]
Does https://github.com/trinodb/trino/pull/22098 help?
if not, please reopen
