### ISSUE TITLE
Elastic Connector - SQL search

### ISSUE THREAD

**Issue by pixie79** [trinodb/trino#10068]
Hi,

How do i issue a search via Trino to elastic. I can do simple queries ok but for example, in Kibana UI I may just search for the term "bread" and see if it is matched in any of the documents.

How would I do that and then return the results as a table. I have seen I can do the push down queries using base32 but that will be too technical for uses.

Thanks

Mark

**Comment by ebyhr** [comment]
Hi, please post questions in the Community Slack. We manage bug or enhancement request in GitHub issue.
https://trino.io/slack.html
