### ISSUE TITLE
PrestoS3FileSystem#rename does not preserve SSE properties

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#101]
Extracted from: https://github.com/prestodb/presto/issues/9916

`PrestoS3FileSystem#rename` should preserve SSE properties while copying files. Problematic line is: `PrestoS3FileSystem.java:407: s3.copyObject`. According to S3 Javadoc:
```
     * By default, all object metadata for the source object except
     * <b>server-side-encryption</b>, <b>storage-class</b> and
     * <b>website-redirect-location</b> are copied to the new destination
     * object, unless new object metadata in the specified
     * {@link CopyObjectRequest} is provided.
```

On the other hand, maybe `PrestoS3FileSystem#rename` should throw `UnsupportedOperationException`? It seems that it shouldn't be used at all because for S3 there should be no temporary objects when inserting into table (see: `HiveWriteUtils#isS3FileSystem`).

**Comment by hashhar** [comment]
Actually nevermind, new FS doesn't have this code path at all so no problem and legacy is going away.
