### ISSUE TITLE
Trino have duplicated data to query pinot while pinot have duplication data between realtime and offline table

### ISSUE THREAD

**Issue by ellieshen** [trinodb/trino#10125]
It looks Trino can't distinguish realtime and offline table with duplication data in pinot, which caused count double data from pinot. however via native Pinot, this will not appear.

**Comment by elonazoulay** [comment]
Pinot does connect to the broker to get the time boundary, can you paste an example query?

**Comment by ellieshen** [comment]
shared in query example in slack

**Comment by ebyhr** [comment]
Relates to https://trinodb.slack.com/archives/CGB0QHWSW/p1638293252062100
