### ISSUE TITLE
Bad link, YouTube page for Community show on SuperSet

### ISSUE THREAD

**Issue by Ordinant** [trinodb/trino#10138]
YouTube page for the Trino Community broadcast "12: Trino gets super visual with Apache Superset"
https://www.youtube.com/watch?v=0NHUs-TERtk

Open **Show More** to see all of the description. In that description, the **Show Notes** link is broken and leads to a 404. 

The problem is that the YT redirect adds `%E2%80%8B` to the end of the redirected URL. This doesn't happen on other YT Community pages I tried.

**Comment by bitsondatadev** [comment]
Fixed! Thanks @Ordinant !
