### ISSUE TITLE
Query failure event is not fired when exception thrown from resourceGroupManager

### ISSUE THREAD

**Issue by puchengy** [trinodb/trino#10144]
It seems that we should fire a failure event when exception is thrown from https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/dispatcher/DispatchManager.java#L214 currently this event is missing. 

@dain can you comment on this? thanks.

**Comment by findepi** [comment]
@puchengy would you be able to write a regression test for this?

@losipiuk might help you find existing tests

**Comment by dain** [comment]
The `catch(Throwable throwable)` block below is supposed to be firing the correct events.  Take a look here: https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/dispatcher/DispatchManager.java#L232

**Comment by puchengy** [comment]
@dain Are you suggesting we should re-throw the Throwable at https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/dispatcher/DispatchManager.java#L218 so that the event can be fired in the outer catch block?

If this is the case, then there will be two query create event fired. One from `createDispatchQuery` and one from the catch block.

**Comment by puchengy** [comment]
@losipiuk Could you help me find the existing tests? thank you.

**Comment by dain** [comment]
Is the problem that dispatchQuery.fail(e) is not firing the completed event?

**Comment by losipiuk** [comment]
> @losipiuk Could you help me find the existing tests? thank you.

PTAL at `TestEventListenerBasic` and `TestEventListenerWithSplits`

**Comment by dain** [comment]
Ya, I think we need a reproduction.  The code will call `dispatchQuery.fail(e)` if any exception is thrown, and at this point `dispatchQuery` will be an instance of `LocalDispatchQuery`.  `LocalDispatchQuery` constructor adds a listener to the query state machine that fires a completed event when the query is failed during startup.  It is possible there is a bug here, but it is not obvious.

**Comment by puchengy** [comment]
@dain @losipiuk @findepi I found that this is not reproducible in the latest trino version, so we are all good. Sorry for the inconvenience.
