### ISSUE TITLE
Queries to the Phoenix connector can use up all of the TrinoServer's heap memory

### ISSUE THREAD

**Issue by lhofhansl** [trinodb/trino#10143]
Phoenix has the notion of guidepost, equal width stats, in order to gauge how to parallelize a query.

For Trino this means that Phoenix will parallelize queries even for a single split when the Phoenix plan suggests to use the RoundRobinIterator.
What's makes this more interesting is that each Phoenix query segment (Scan) will prefetch some data (2MB worth of rows by default, with all overhead it could 3-5mb on the heap).

The effect: I loaded a decent amount of data (about 800gb uncompressed, about 150bg compressed) onto a very small (single node, because I wanted to do some debugging) Phoenix and Trino cluster. This is a simple count(*) query, and since Phoenix does not support aggregate pushdown all rows are actually loaded by the TrinoServer. What happened is that TrinoServer quickly ran out of heap.

When I looked at the heapdump I noticed for each split Phoenix created many thousands of scans per split, and each scan started pre-fetching. In effect the TrinoServer now had many thousands of scans open, each of which started fetching, filling the heap with millions of HBase Result objects and their associated byte[]. 10000's of scans using some 3-5mb of heap adds up quickly.

One could argue that this is a contrived case where we use an aggregate that cannot be pushed with a lot of data on a very small custer.

Possible solutions:
1. Do nothing and assume that this is not a common case. This is not entirely unreasonable. The default guidepost width in 300mb, which I had lowered to 10MB and then 100MB. Even at 300mb, this would create ~2700 scans for my dataset, and use up 8-12gb of heap without even starting executing the split.
2. Never allow Phoenix to parallelize inside a Split (i.e. always use a ConcatIterator instead of the RoundRobinIterator), and leave all parallelize to Trino. Small queries might be slower now, since we're losing out of the pre-fetching.
3. Put in some logic that allows the RoundRobinIterator for a Split when we have less than N scans. N should be low, like 10 or so, definitely < 100. So small queries would still be fast.
4. Make this configurable with a boolean enable/disable intra-split-parallelism (default off!)
5. Make it configurable with the maximum parallelism should be (i.e. 3. above but configurable, default 10). Not that we can tell the RoundRobinIterators how many scans to prefetch, so it always all or nothing.

I'd lean towards 2. or 3. and not introduce more config options.

It's also not at all clear how to isolate this into test.

**Comment by hashhar** [comment]
Is it possible/easy to quantify whether there is actually a real-world non-negligible performance difference between 2 and 3?

If not, then I'd opt for the simpler approach that is 2. If there are gains to be had from 3 I think we should consider it.

**Comment by lhofhansl** [comment]
For small datasets located on a single (or a few) HBase server only, adding parallelism and prefetching does help.

An HBase region is typically 10-20GB in size (Trino will use a split per region), for small queries we probably want more than a single handler working on it. When the query is large enough so that multiple regions pre HBase regionserver are engaged there is less or no need for it. It's all about making effective use of the HBase servers and resources.

It's quite hard to quantify exactly as it depends on: available handlers on the HBase servers (and associate CPU resources), network, and IO latency.

Maybe we could limit the splits * scans product...? Many splits means fewer scans. Even that depends on the size of the HBase cluster and the number of clients (i.e. TrinoServers)

Sorry... No definite answer. Maybe 2. is the best choice. As we do not really worry about peanut data sizes much :)

**Comment by lhofhansl** [comment]
@vincentpoon In case you have an opinion.

**Comment by lhofhansl** [comment]
Did some more tests, and at least in my scenario I see no improvements using the RoundRobinResultIterator (tried with a small local dataset on a single node). Of course with local data there's no network latency.

**Comment by vincentpoon** [comment]
@lhofhansl  Sounds like #2 is the way to go then.
Question on that though - Would it not help even larger queries to have some level parallelism on a larger region?

I'm wondering if it makes sense to continue generating the scans, but separate out the scans into more Trino splits, and thereby allow Trino to better manage overall resource consumption via split scheduling.
i.e. instead of having 10 splits each with 1000 scans, have something like 1000 splits each with 10 scans.

**Comment by lhofhansl** [comment]
@vincentpoon Agreed. There's more that could be done. Currently this follows the MapReduce model for one split per region (as you know of course, just stating for completeness.)

Not sure I want to change that. In a nicely balanced system each region server would host about 100 regions, we will probably get enough parallelism that way.

I do like the idea of more splits, though. That way Trino handles it. Currently Phoenix will generate a scan per guideposts. I've pushing Phoenix to change that, but eventually gave up. We can't have an Inputsplit per scan, that'd be overkill. Maybe we combine a few of them with a ConcatResultIterator, and then an InputSplit for each group... That could actually work.

Lemme noodle this a bit more. Can't put too much time in it, as it is technically not something I'm working on at work.

**Comment by vincentpoon** [comment]
Btw, wrt your side comment on count(*) - aggregate pushdown is supported now in Trino - we just need to implement it into the Phoenix connector (`PhoenixMetadata#applyAggregation()`).

**Comment by lhofhansl** [comment]
Yep. Was thinking about that too. I just did that for a connector for internal JDBC based database.

The extra bit different from the JDBC framework for Phoenix will be to do it two-phase, for the split and then for the query - would not be a simple query rewrite.
I.e. sum the per-split count, for avg collect split sum and count and to a final avg calculation, etc.
