### ISSUE TITLE
Improve documentation regarding insert overwrite behavior for hive

### ISSUE THREAD

**Issue by aakashnand** [trinodb/trino#10160]
This issue is for improving the documentation for `insert overwrite`. Currently, it is documented under `migrating from hive` but I think it makes more sense to add this frequently asked property under `hive connector` documentation. 

Recently during one of the conversations over slack, it was found that the documentation for `insert overwrite` does not make it explicit whether it works for Hive Transactional Table or not. 

> Insert overwrite operation is not supported by Trino when the table is stored on S3, encrypted HDFS or an external location.

Also, the current documentation says that it does not work when the table is stored in an external location, however, I found out that it is not correct, the `insert overwrite` works for the table which uses external location when the location is HDFS.

https://trino.io/docs/current/appendix/from-hive.html#overwriting-data-on-insert

@mosabua Let me know if you agree with the suggestions. I would like to take this issue.

Slack Ref Link: https://trinodb.slack.com/archives/CFLB9AMBN/p1638451676102600?thread_ts=1638436475.100300&cid=CFLB9AMBN

**Comment by mosabua** [comment]
Sounds good ... go ahead and create a PR and give it the docs label .. then we can review and get it merged.
