### ISSUE TITLE
health check for provisioning of trino process

### ISSUE THREAD

**Issue by youngjinkim0706** [trinodb/trino#10227]
I try to figure out whether Trino cluster is ready for executing query.
I use **/v1/queue api** for checking readiness. 
/v1/queue API occurs java exception unless trino cluster is ready for handling query.
Therefore, I suspect system readiness when the exception returned.

I think it is not a "graceful" technique to judge readiness of the cluster.
I was wondering there is any API or method for checking readiness of handling query in current Trino version.

Thanks in advance : )

**Comment by raunaqmorarka** [comment]
You can run `SELECT COUNT(*) FROM system.runtime.nodes` and check if that is above some minimum threshold number of nodes.

**Comment by youngjinkim0706** [comment]
Actually, I want to avoid to request query because of query queuing.
I think if I request the query, then it will be queued. 
I didn't read source code of API deeply, but I guess the queue API directly ask to run.Queue thread, not request query.

**Comment by hashhar** [comment]
/v1/info is the one you should use. It handles everything correctly and won't return a healthy response unless the server has started up completely and is ready to serve queries or requests.

If you want to instead enforce the presence of minimum number of workers you can set `query-manager.required-workers`.

**Comment by hashhar** [comment]
@youngjinkim0706 The resource group mechanism allows you to limit the number of queued queries that are allowed. You can configure a resource group which allows 0 queued queries and route all queries to it. https://trino.io/docs/current/admin/resource-groups.html

**Comment by hashhar** [comment]
BTW the entire point of the queuing mechanism within Trino is that you don't need to make these decisions - the server will queue any queries it cannot serve (as defined by the resource group configuration), and then continue with them once the queue depth is reduced.

**Comment by youngjinkim0706** [comment]
@hashhar  Thank you for your answer!!
