### ISSUE TITLE
Is there support for Delta Lake?

### ISSUE THREAD

**Issue by cemsbr** [trinodb/trino#10259]
Delta Lake provides connector to Presto ([source code](https://github.com/delta-io/connectors), [doc](https://docs.delta.io/latest/presto-integration.html)), not Trino. Besides, Delta Lake is not listed in [Trino documentation](https://trino.io/docs/current/connector.html). I could only find paid support from [Starburst](https://www.starburst.io/platform/connectors/delta-lake/).

Is there support for Delta Lake or does the Presto connector work with Trino?

**Comment by tmnd1991** [comment]
I think it’s going to be there very soon  #10300
