### ISSUE TITLE
Ensure full query retries work with JDBC connectors based on base-jdbc

### ISSUE THREAD

**Issue by joshthoward** [trinodb/trino#10254]
To ensure that full query retries (#9361) will work without failed retry attempts leaving around garbage, we need to ensure that transactions are atomic in JDBC based connectors. This issue is similar to #10252.

**Comment by hashhar** [comment]
What do you mean by transactions? Are you referring to the transaction (BEGIN/COMMIT/ROLLBACK) that Trino provides? Or are you more generally referring to any operation that the engine performs (e.g. CREATE TABLE, CTAS, INSERT etc?).

**Comment by findepi** [comment]
@hashhar i fixed the title.
