### ISSUE TITLE
Ensure query retries work with Hive connector

### ISSUE THREAD

**Issue by joshthoward** [trinodb/trino#10252]
To ensure that full query retries (#9361) will work without failed retry attempts leaving around garbage, we need to ensure that transactions are atomic in the Hive Connector.

**Comment by losipiuk** [comment]
Closed with https://github.com/trinodb/trino/pull/10064

**Comment by losipiuk** [comment]
I have just noticed that it is still possible that we leave "extra" files in the target table directory on insert. It is technically possible that a strangling task, whose work should not be committed, writes the file to target table directory **after** the commit routine of query already completes, and cleanup of extra-files already happened. No idea how we can handle that (if we can at all for non-transactional connector like Hive). 

@arhimondr @findepi  comments? Do we care? Can we care?

**Comment by findepi** [comment]
How (un)likely such a timing is possible?
Sounds like it can absolutely happen in real world scenarios, right?

**Comment by arhimondr** [comment]
There are 2 different ways of handling this problem (that I know of).

1. Write to a temporary directory. Move committed files to destination on commit. Unfortunately this approach doesn't play well with S3 where move operation is expensive.
2. Have deterministic file names. Each task produces fixed number of files with fixed names. Unfortunately with our implementation of thread level parallelism this implementation is challenging. 

We had this discussion with @findepi , @dain and @electrum . From what I remember the conclusion was that we are not going to try to handle this scenario in Hive (at least for now).

**Comment by findepi** [comment]
> We had this discussion with @findepi , @dain and @electrum . From what I remember the conclusion was that we are not going to try to handle this scenario in Hive (at least for now).

I guess you're referring to a kickstarting meeting we had in October? 
I don't remember the conclusions and didn't take notes.

Anyway, if the problem is not really possible in practice, we don't need to solve it.
If the problem is possible in practice, not solving it leaves us with silent correctness problem, right?

**Comment by losipiuk** [comment]
> Anyway, if the problem is not really possible in practice, we don't need to solve it. If the problem is possible in practice, not solving it leaves us with silent correctness problem, right?

I think it is possible - but not probable. It feels like it needs some kind of network split-brain scenario. Where a node can cleanly talk to S3/HDFS endpoint and complete the task correctly, while coordinator cannot reach the node to kill the task. 
It looks like with full-query retries it should not happen - or the chance is very slim (I do not see a scenario). But for task-level retires it is more reasonable to think that it is an actual problem - just a rare one.

On the other hand with non-transactional connectors like Hive, if you write directly to table directory you can get unexpected results even without any retries mechanism. Maybe not duplicate rows - but it is easy to get a partial insert visible in the table for a failed query. Just kill coordinator.
