### ISSUE TITLE
when trino connecting to hive metastore，It's always connect in the same order

### ISSUE THREAD

**Issue by lurnagao-dahua** [trinodb/trino#10305]
Hi, i have a quesion.

when trino connecting to hive metastore，It's always connect in the same order

    public ThriftMetastoreClient createMetastoreClient(Optional<String> delegationToken)
            throws TException
    {
        Comparator<Backoff> comparator = Comparator.comparingLong(Backoff::getBackoffDuration)
                .thenComparingLong(Backoff::getLastFailureTimestamp);
        List<Backoff> backoffsSorted = backoffs.stream()
                .sorted(comparator)
                .collect(toImmutableList());

        TException lastException = null;
        for (Backoff backoff : backoffsSorted) {
            try {
                return getClient(backoff.getAddress(), backoff, delegationToken);
            }
            catch (TException e) {
                lastException = e;
            }
        }

        List<HostAndPort> addresses = backoffsSorted.stream().map(Backoff::getAddress).collect(toImmutableList());
        throw new TException("Failed connecting to Hive metastore: " + addresses, lastException);
    }

and the getClient is:

    private ThriftMetastoreClient getClient(HostAndPort address, Backoff backoff, Optional<String> delegationToken)
            throws TException
    {
        ThriftMetastoreClient client = new FailureAwareThriftMetastoreClient(clientFactory.create(address, delegationToken), new Callback()
        {
            @Override
            public void success()
            {
                backoff.success();
            }

            @Override
            public void failed(TException e)
            {
                backoff.fail();
            }
        });
        if (!isNullOrEmpty(metastoreUsername)) {
            client.setUGI(metastoreUsername);
        }
        return client;
    }

and the backoff.fail() is :

    synchronized void fail()
    {
        lastFailureTimestamp = OptionalLong.of(ticker.read());
        backoffDuration = min(backoffDuration * 2, MAX_BACKOFF);
    }

when create metastore client, it will connect to metastore service sort by lastFailureTimestamp from small to big.

if one metastore service is down, then `clientFactory.create ` function will throw TException and not going to `Callback `function. so It's always connect in the same order.

Appreciate for help!

**Comment by findepi** [comment]
cc @losipiuk

**Comment by lurnagao** [comment]
I configured two  hive metastore service and tried to shut down a hive metastore service. then debug trino server, I found it was always first connected to a service which was down.

**Comment by nwdsslzwf** [comment]
I have the same question, and I hope someone can answer it.Appreciate for help!
