### ISSUE TITLE
How to get table Comment with 'show '

### ISSUE THREAD

**Issue by dawsongzhao** [trinodb/trino#10318]
I can list table name using 'show tables from hive.bda',But I can't get table comment.Is there any way to get table it by trino?
![image](https://user-images.githubusercontent.com/7078308/146305144-41d13e0e-6093-4786-91fb-eac0e3857f62.png)

**Comment by ebyhr** [comment]
There is a hidden `table_comment` column in `information_schema.tables`.

**Comment by dawsongzhao** [comment]
> There is a hidden `table_comment` column in `information_schema.tables`.

Thanks for your reply,but how to use hidden `table_comment` column.

**Comment by hashhar** [comment]
You can select the hidden column. Hidden just means that it isn't part of `DESCRIBE` output.

`SELECT *, table_comment FROM information_schema.tables` should work.

@ebyhr Any context why the column is hidden though?

**Comment by ebyhr** [comment]
@hashhar Here is the context: https://github.com/trinodb/trino/pull/192
