### ISSUE TITLE
High and Critical CVE findings in v367

### ISSUE THREAD

**Issue by 589290** [trinodb/trino#10316]
I've run **trino-server** and **trino-cli** through Twistlock and Anchore vulnerability scans.

The results show several HIGH and CRITICAL CVE's in the current release ~ v367.

The results of my scan with a list of CVEs and their severity are here:
https://pastebin.com/raw/dwTwAYjj

My image build process is here:
https://repo1.dso.mil/dsop/opensource/trino/trino/-/raw/hardening/Dockerfile

<img width="1472" alt="Screen Shot 2021-12-29 at 3 22 05 PM" src="https://user-images.githubusercontent.com/69643994/147704379-a05626f0-685d-42c1-b054-e2d6d3dbdb12.png">

**Comment by ebyhr** [comment]
Let me close this issue because version 367 is very old and we don't update past released modules.
