### ISSUE TITLE
Broadcast join query is getting stuck when broadcast table is not small

### ISSUE THREAD

**Issue by arhimondr** [trinodb/trino#10333]
```
SELECT
"i_item_desc"
, "w_warehouse_name"
, "d1"."d_week_seq"
, "sum"((CASE WHEN ("p_promo_sk" IS NULL) THEN 1 ELSE 0 END)) "no_promo"
, "sum"((CASE WHEN ("p_promo_sk" IS NOT NULL) THEN 1 ELSE 0 END)) "promo"
, "count"(*) "total_cnt"
FROM
((((((((((hive.tpcds_sf1000_orc_part.catalog_sales
INNER JOIN hive.tpcds_sf1000_orc_part.inventory ON ("cs_item_sk" = "inv_item_sk"))
INNER JOIN hive.tpcds_sf1000_orc_part.warehouse ON ("w_warehouse_sk" = "inv_warehouse_sk"))
INNER JOIN hive.tpcds_sf1000_orc_part.item ON ("i_item_sk" = "cs_item_sk"))
INNER JOIN hive.tpcds_sf1000_orc_part.customer_demographics ON ("cs_bill_cdemo_sk" = "cd_demo_sk"))
INNER JOIN hive.tpcds_sf1000_orc_part.household_demographics ON ("cs_bill_hdemo_sk" = "hd_demo_sk"))
INNER JOIN hive.tpcds_sf1000_orc_part.date_dim d1 ON ("cs_sold_date_sk" = "d1"."d_date_sk"))
INNER JOIN hive.tpcds_sf1000_orc_part.date_dim d2 ON ("inv_date_sk" = "d2"."d_date_sk"))
INNER JOIN hive.tpcds_sf1000_orc_part.date_dim d3 ON ("cs_ship_date_sk" = "d3"."d_date_sk"))
LEFT JOIN hive.tpcds_sf1000_orc_part.promotion ON ("cs_promo_sk" = "p_promo_sk"))
LEFT JOIN hive.tpcds_sf1000_orc_part.catalog_returns ON ("cr_item_sk" = "cs_item_sk")
AND ("cr_order_number" = "cs_order_number"))
WHERE ("d1"."d_week_seq" = "d2"."d_week_seq")
AND ("inv_quantity_on_hand" < "cs_quantity")
AND ("d3"."d_date" > ("d1"."d_date" + INTERVAL  '5' DAY))
AND ("hd_buy_potential" = '>10000')
AND ("d1"."d_year" = 1999)
AND ("cd_marital_status" = 'D')
GROUP BY "i_item_desc", "w_warehouse_name", "d1"."d_week_seq"
ORDER BY "total_cnt" DESC, "i_item_desc" ASC, "w_warehouse_name" ASC, "d1"."d_week_seq" ASC
LIMIT 100
```

**Comment by arhimondr** [comment]
Introduced by https://github.com/trinodb/trino/pull/9361

**Comment by findepi** [comment]
> Introduced by #9361

is the problem with retries disabled or enabled?

cc @losipiuk

**Comment by arhimondr** [comment]
@findepi Unfortunately with retries disabled as well. Looks like a regression introduced as part of the scheduler refactor.

**Comment by arhimondr** [comment]
The issue is specific to broadcast join. 

When the broadcast table is larger than the total size of the broadcast buffers on all the nodes (`sink.max-broadcast-buffer-size` multiplied by the number of nodes running a stage producing the build side of a join) and the number of splits for the probe side is higher than the total number of splits that can be assigned simultaneously ((`node-scheduler.max-pending-splits-per-task` + `node-scheduler.max-unacknowledged-splits-per-task`) multiplied by the total number of nodes in the cluster) a broadcast join can get stuck. 

The `BroadcastOutputBuffer` would wait for a `noMoreOutputBuffers` signal before it could start discarding the data that has already been sent to all the destination tasks. If the signal is lost the `BroadcastOutputBuffer` cannot discard the data as it expects more consuming tasks to be added. At the same time on the probe processing is waiting for the build side to become fully available and the split assignment cannot make further progress. Scheduler has a special handling for such scenario: https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/execution/scheduler/SourcePartitionedScheduler.java#L427. 

The propagation of this signal got broken during refactoring done in #9361

**Comment by findepi** [comment]
`sink.max-broadcast-buffer-size` defaults to 200 MB, so with a small 10 node cluster, the bug can occur for 2 GB broadcast table. We may end up in such broadcast join e.g. when stats are not accurate, and CBO decides to broadcast thinking the table is smaller.

**Comment by sopel39** [comment]
We can also hit buffer limit if the data is highly skewed (e.g. jdbc connector with single split). That was the initiall motivation for bigger buffer. Essentially we never want to overutilize broadcast buffer because we want it to be flushing instead. This way cluster could start more probe tasks.
