### ISSUE TITLE
Grant create privilege

### ISSUE THREAD

**Issue by Yikf** [trinodb/trino#10330]
I saw that we add create privilege in #10206 , That is a little curious.

- Any semantics with `grant create`
- Missing document explanation in [grant.rst](https://github.com/trinodb/trino/blame/master/docs/src/main/sphinx/sql/grant.rst#L20)

**Comment by yikf** [comment]
cc @dain @kokosing @findepi

**Comment by findepi** [comment]
This was discussed in https://github.com/trinodb/trino/pull/10206#issuecomment-989794507
The last message on the topic -- https://github.com/trinodb/trino/pull/10206#issuecomment-990838912 -- remind me that this wasn't clarified and we didn't reach a visible consensus.
