### ISSUE TITLE
Coordinator-only queries fail to transition from STARTING to RUNNING

### ISSUE THREAD

**Issue by sunningCGo** [trinodb/trino#10359]
In Trino 366, queries that run only on the coordinator fail to transition from the `STARTING` state to the `RUNNING` state.

**Comment by kokosing** [comment]
Is this a regression? What caused this issue?

**Comment by sunningCGo** [comment]
Yes. In Trino 366, due to changes in the class `SqlQueryScheduler`, queries that run only on the coordinator (such as `REFRESH MATERIALIZED VIEW`) no longer transition from `STARTING` to `RUNNING`. If one queries `system.runtime.queries` table, one can see that such queries remain in the `STARTING` state even though they are actually running.
