### ISSUE TITLE
Improve RowBlock performance

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#10354]
TODO:

- [ ] Do not use/serialize RowBlock#fieldBlockOffset when not needed
- [ ] Reuse SingleRowBlockWriter when writing to RowBlockBuilder
- [ ] Do not serialize serialize RowBlock field when it's all null

**Comment by WinkerDu** [comment]
@sopel39 Is this tasks list still available to take a ticket?

**Comment by sopel39** [comment]
This was completed by @radek-starburst
