### ISSUE TITLE
Explain (TYPE IO)  will throw Exception when table is hive partition table which is empty

### ISSUE THREAD

**Issue by hqbhoho** [trinodb/trino#10398]
common_20211203001_raw,common_20210902002_raw are hive partition table,but common_20211203001_raw is empty.
![image](https://user-images.githubusercontent.com/37388552/147242293-8bc55f42-c0ed-4e2b-9097-48c25b670443.png)
![image](https://user-images.githubusercontent.com/37388552/147242544-40fc303d-951a-4787-b10d-1c0463aaea0a.png)
this logical is also  different
![image](https://user-images.githubusercontent.com/37388552/147242812-65deef91-195b-4444-8648-0530cabeed4f.png)

**Comment by Emor-nj** [comment]
Hi @findepi , I would like to work on this. Could you please assign me?

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/12349
