### ISSUE TITLE
Postgres tables created with declarative partitioning option are not accessible

### ISSUE THREAD

**Issue by guyco33** [trinodb/trino#10400]
Since `364`, Postgres tables created with the [declarative partitioning](https://www.postgresql.org/docs/10/ddl-partitioning.html#DDL-PARTITIONING-DECLARATIVE) option (10+) are not accessible.

Postgres 10+
```
CREATE TABLE test_part_tbl (
    id         int not null,
    logdate    date not null,
    payload    varchar
) PARTITION BY RANGE (logdate)
```

Trino `363`
```
SHOW TABLES FROM postgres.public LIKE 'test_part_tbl'
('test_part_tbl',)
```

Trino `354+`
```
SHOW TABLES FROM postgres.public LIKE 'test_part_tbl'
no result
```

I guess it's somehow related to [bumping](https://github.com/trinodb/trino/commit/037122740f5cfe97597d997c48001aee923c375f#diff-47c6891b0e753037156b0787b8716ce022c31b136122f8fcafb460754376ff87) JDBC driver from `42.2.10` to `42.2.14`  

Tests for declarative partitioning cannot be done until Postgres docker will bump from 9.6 to 10+

The following [test](https://github.com/guyco33/trino/commit/90d5fd3c5a65bd704450df74a9d58b3ff1982c32) pass in `363` and fails in `364+`

**Comment by guyco33** [comment]
@hashhar

**Comment by findepi** [comment]
> Tests for declarative partitioning cannot be done until Postgres docker will bump from 9.6 to 10+

We should test with both: oldest and newest supported PostgreSQL version.
See `BaseElasticsearchConnectorTest` (perhaps this should use `BaseConnectorSmokeTest` instead.)

**Comment by guyco33** [comment]
`10.x` is the oldest supported version, so splitting tests is not relevant for partitioned tables.
