### ISSUE TITLE
How to re-use trino cluster for multi users

### ISSUE THREAD

**Issue by youngjinkim0706** [trinodb/trino#10414]
Hi, 
I try to reuse an exist Trino cluster with different aws s3 key pairs.
In current implementation, Trino set aws s3 key pair once during initialize, so  different key pair cannot be used for the exist cluster.
I would like to know there is other way to reuse cluster without additional implementation.

Thank you for reply in advanced : )

**Comment by hashhar** [comment]
See https://trino.io/docs/current/connector/hive-s3.html#s3-security-mapping

**Comment by hashhar** [comment]
If you have more complicated rules you'd like to implement see https://trino.io/docs/current/connector/hive-s3.html#custom-s3-credentials-provider

**Comment by hashhar** [comment]
Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there.
