### ISSUE TITLE
node.environment: may not be null

### ISSUE THREAD

**Issue by JeevansSP** [trinodb/trino#10454]
when I try bin/launcher run
I get this error 
**Invalid configuration property node.environment: may not be null (for class io.airlift.node.NodeConfig.environment)**
my node.environment is set to "test" so I don't see what is the issue.

```
bin/launcher run
OpenJDK 64-Bit Server VM warning: Option UseBiasedLocking was deprecated in version 15.0 and will likely be removed in a future release.
Jan 04, 2022 10:35:00 AM io.airlift.log.Logger info
INFO: Java version: 16.0.1
2022-01-04T10:35:00.653Z	INFO	main	io.airlift.log.Logging	Logging to stderr
2022-01-04T10:35:00.655Z	INFO	main	Bootstrap	Loading configuration
2022-01-04T10:35:00.944Z	INFO	main	Bootstrap	Initializing logging
2022-01-04T10:35:03.608Z	ERROR	main	io.trino.server.Server	Configuration is invalid
==========

Errors:

1) Invalid configuration property node.environment: may not be null (for class io.airlift.node.NodeConfig.environment)
```

and this is my node.properties 

```
node.environment=production
node.id=ffffffff-ffff-ffff-ffff-ffffffffffff
node.data-dir=/home/accidf/Desktop/Trino/data
```

**another thing worth mentioning, if I rename node.environment such that it contains invalid characters ('-' and uppercase letters) I still get the same error.**

**Comment by JeevansSP** [comment]
@ebyhr please help

**Comment by JeevansSP** [comment]
jvm.config 
```
-server
-Xmx16G
-XX:-UseBiasedLocking
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+ExplicitGCInvokesConcurrent
-XX:+ExitOnOutOfMemoryError
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-XX:ReservedCodeCacheSize=512M
-XX:PerMethodRecompilationCutoff=10000
-XX:PerBytecodeRecompilationCutoff=10000
-Djdk.attach.allowAttachSelf=true
-Djdk.nio.maxCachedBufferSize=2000000
```

config.properties
```
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
query.max-memory=5GB
query.max-memory-per-node=1GB
query.max-total-memory-per-node=2GB
discovery.uri=http://20.85.245.16:22
```

sqlserver.properties
```
connector.name=sqlserver
connection-url=jdbc:sqlserver://;servername=idfrgdemo.database.windows.net;database=IDFRGDW
connection-user=*********
connection-password=******
```
ive masked the confidential info

**Comment by JeevansSP** [comment]
@ebyhr i have posted all the files

**Comment by martint** [comment]
Where is your `node.properties` file located relative to `config.properties`? Is it also in the `etc/` directory?

**Comment by JeevansSP** [comment]
> Where is your `node.properties` file located relative to `config.properties`? Is it also in the `etc/` directory?

node.properties and config.properties are in the same directory in etc/

**Comment by JeevansSP** [comment]
> Where is your `node.properties` file located relative to `config.properties`? Is it also in the `etc/` directory?
```
etc
|-->node.properties
|-->jvm.config
|-->config.propoerties
|-->catalog
       |-->sqlserver.properties
```

**Comment by ebyhr** [comment]
Both `bin` and `etc` directories exist in the same directory?

**Comment by JeevansSP** [comment]
> Both `bin` and `etc` directories exist in the same directory?

yes bin and etc are folders in trino-server-367 along with other folders and trino-server-367 and data folders are inside a folder called Trino

**Comment by JeevansSP** [comment]
i restarted the system and now after bin/launcher start
it says 
started as 2303

**Comment by ebyhr** [comment]
Do you mean `bin/launcher start` works, but `bin/launcher run` doesn't work?

**Comment by JeevansSP** [comment]
> Do you mean `bin/launcher start` works, but `bin/launcher run` doesn't work?

actually no , after bin/launcher start when i check bin/launcher status it says not running

**Comment by JeevansSP** [comment]
> Do you mean `bin/launcher start` works, but `bin/launcher run` doesn't work?

bin/launcher run still gives the same error

**Comment by JeevansSP** [comment]
may it be because i have java 16 installed?

**Comment by ebyhr** [comment]
I don't think the version relates to the issue, but I would recommend using Java 11.
https://trino.io/docs/current/installation/deployment.html#java-runtime-environment

**Comment by JeevansSP** [comment]
do you know why i might be getting this error? or what does it even mean?

**Comment by ebyhr** [comment]
Can you join the community Slack so that we can talk interactively? https://trino.io/slack.html

**Comment by JeevansSP** [comment]
> Can you join the community Slack so that we can talk interactively? https://trino.io/slack.html

ok

**Comment by ebyhr** [comment]
As we talked in Slack, the `node.proporties` file name was wrong. It was `node.porperties` in your environment.

**Comment by JeevansSP** [comment]
i had misnamed node.properties as node.propoerties, fixed it and it works now
