### ISSUE TITLE
docs-checks fails due to OutOfMemoryError

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#10467]
```
Terminating due to java.lang.OutOfMemoryError: Java heap space
.github/bin/retry: retrying [./mvnw install -B --strict-checksums -V -T C1 -DskipTests -P ci -am -pl :trino-docs] timed out
Error: Process completed with exit code 1.
```
https://github.com/trinodb/trino/runs/4709585911

**Comment by hashhar** [comment]
Let's use the `MAVEN_INSTALL_OPTS` defined in docs.yml. It limits Xmx to 2G. I'm guessing that currently no Xmx is set and hence JVM tries to grow heap (instead of GCing) and fails?
