### ISSUE TITLE
view failure

### ISSUE THREAD

**Issue by ramkumar-jeganathan** [trinodb/trino#10527]
Trying to pass date dynamically to a view.

create function var1() returns VARCHAR(256) DETERMINISTIC NO SQL return @var1;

create view date_test as select * from ( select notes, create_date from table1 where create_date FROM_UNIXTIME(var1()) and FROM_UNIXTIME(1741013691) ) x) y

select dt.* from (select @var1:=1641013691) p , date_test dt;

Error:
Query 20220110_204851_00123_zhtpu failed: line 1:27: mismatched input '@'. Expecting: '*', 'ALL', 'DISTINCT', <expression>

Any suggestions.

**Comment by ebyhr** [comment]
Please use `"` for quoting column names likes `"@var1" = 1641013691`. 

Please feel free to continue in the community Slack if necessary. https://trino.io/slack.html
