### ISSUE TITLE
Support writing timestamp and datetime types in ClickHouse connector

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#10538]

**Comment by zhicwu** [comment]
Hi @ebyhr, `Date32` and `DateTime64` support date range from 1925-01-01 to 2283-11-11. Does it make sense to add an option for the default behavior?

Below items might be a bit off the topic but I think it would be nice if you can consider as well.
1. change `jdbcTypeName.equals("DateTime")` to `jdbcTypeName.startsWith("DateTime")` to support both DateTime32 and DateTime64. Similarly for Date and Date32.
2. `Types.TIMESTAMP_WITH_TIMEZONE` should be added as well. It's mapped to `OffsetDateTime` in JDBC driver.
3. Timezone. You might want to set connection property `use_server_time_zone` to `false`, and `use_time_zone` to preferred timezone, if you want to make the conversion transparent to users.

**Comment by ebyhr** [comment]
@zhicwu It makes sense. Do you want to send the PRs? By the way, there is another issue for `DateTime64` support.  https://github.com/trinodb/trino/issues/10537

**Comment by zhicwu** [comment]
Thanks @ebyhr. Sorry I need to focus on completing TCP/Native support for ClickHouse JDBC driver first, and then I should be able to spend more time to learn trino and contribute a few pull requests. Meanwhile, if it's not annoying, I'll comment on issue/pull request related to ClickHouse from time to time to share my thoughts and hopefully they can be of use :p

**Comment by ebyhr** [comment]
@zhicwu It's not annoying at all. We are welcome your comments. It's very helpful.

**Comment by ebyhr** [comment]
Supported creating tables with Trino `timestamp(0)` as ClickHouse `datetime` in #10751. Let's continue https://github.com/trinodb/trino/issues/10538#issuecomment-1020668450 in #10537
