### ISSUE TITLE
Add docs for supported security systems in Iceberg connector

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#10548]
Follow up to https://github.com/trinodb/trino/pull/10493

@kokosing who could help here?

**Comment by kokosing** [comment]
`iceberg.security` supports values:
 - ALLOW_ALL,
 - READ_ONLY,
 - SYSTEM - this means that connector do not control anything but relies on system level access control
 - FILE,

They all work like in https://trino.io/docs/current/connector/hive-security.html

**Comment by mosabua** [comment]
Done. Thanks!
