### ISSUE TITLE
JDK8 regression similar to #1169 with http2 enabled proxy. Slow exit

### ISSUE THREAD

**Issue by brokenjacobs** [trinodb/trino#10551]
Similar to #1169 but for java8 clients using the trino-jdbc driver. This PR appears to have caused the issue:
https://github.com/trinodb/trino/pull/5915

trino-jdbc 354 doesn't have this problem but trino-jdbc >= 355 does. 

It appears that this code wasn't unnecessary on jre <=11. We are testing on 1.8.0_281 and seeing this issue.

We are seeing shutdown times of 5 minutes (basically the okhttp connection timeout) from command line/console applications after the last query finishes. The application hangs for five minutes and two threads are active for OKHttp.

**Comment by brokenjacobs** [comment]
Would it be possible to implement a protocols parameter similar to:
https://github.com/prestodb/presto/pull/15955
?

**Comment by findepi** [comment]
> This PR appears to have caused the issue: #5915

#5915 wasn't merged, but #6002 was

i merged #6002 but only because @electrum said in https://github.com/trinodb/trino/pull/5915#issuecomment-726238592 this is the thing to do.
cc @PennyAndWang @electrum 

> Would it be possible to implement a protocols parameter similar to:
> prestodb/presto#15955

I am no expert in this area. I would defer to @electrum to determine the best way forward.

**Comment by brokenjacobs** [comment]
It seems that the issue that was previously observed on JDK11+ where if using a HTTP2 enabled proxy, exiting a command line application would result in a 5 minute delay, is now occurring in newer JDK8 builds after this change. Chasing after jdk8 support seems to be time consuming, hence my question of offering an option to disable http2 negotiation, similar to what prestodb has done.

**Comment by brokenjacobs** [comment]
We migrated to a different environment where this is no longer relevant to us and given no interest in pulling in the change from presto, closed.
