### ISSUE TITLE
Document scheduling policy configuration

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#10554]
property: `query.execution-policy`
session property: `execution_policy`
values: `phased`, `legacy-phased` or `all-at-once`
default as of 368: phased
old default: all-at-once

document in property reference: https://trino.io/docs/current/admin/properties-query-management.html

Could you run with this @rosewms ?

**Comment by rosewms** [comment]
@mosabua do you know what "type" is it or is there someone else I should follow up with?

**Comment by sopel39** [comment]
Fixed via https://github.com/trinodb/trino/pull/10715
