### ISSUE TITLE
Implement ALTER SCHEMA ... RENAME for ClickHouse

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#10558]
ClickHouse supports renaming schemas using `RENAME DATABASE` command.

It's only supported for databases created using the `ATOMIC` engine - see https://clickhouse.com/docs/en/sql-reference/statements/rename/

Atomic engine has been available since `v20.4.2.9-stable` (see https://github.com/ClickHouse/ClickHouse/commit/7928f2eaa187e4abc6c96d2c3651a0b52077835d) and has become the default since `v20.10.2.20-stable` (see https://github.com/ClickHouse/ClickHouse/commit/06d7b6cbef68cfca16460271976ee5f2aa0f35d6).

It was not implemented in https://github.com/trinodb/trino/pull/8939 to keep the PR small and scope simple.
Also it's an open question if we want to allow `ALTER SCHEMA ... RENAME` unconditionally and let ClickHouse throw the proper errors or if we want to check within the connector whether the schema being renamed is an `ATOMIC` database or not.

See various TODOs linking to this issue in the code.

**Comment by tangjiangling** [comment]
@hashhar I'd to try this.

**Comment by hashhar** [comment]
@tangjiangling Feel free to pick this up once https://github.com/trinodb/trino/pull/8939 gets merged (should be done by tomorrow).

I'll assign once merged.

**Comment by tangjiangling** [comment]
@hashhar Understood.
