### ISSUE TITLE
Double round() return incorrect result

### ISSUE THREAD

**Issue by xiaoDjun** [trinodb/trino#10607]
Double round in io.trino.operator.scalar.MathFunctions#round(double num, long decimals) gives incorrect result when the round decimal ends with 5 and decimal scale is more than 2, for example:
```
presto> select round(cast(4.145 as double), 2);
 _col0
-------
  4.14
presto> select round(cast(4.185 as double), 2);
 _col0
-------
  4.18
```
the expected result of round(cast(4.145 as double), 2) should be 4.15, but 4.14 is given.

**Comment by findepi** [comment]
The result is correct.
4.145 cast to double is approximately equal to 4.144999999999999573674358543939888477325439453125, so smaller than the actual 4.145 number.
