### ISSUE TITLE
What makes sense for ALTER VIEW SET AUTHORIZATION?

### ISSUE THREAD

**Issue by ksobolew** [trinodb/trino#10610]
This issue is meant to start a discussion about the future of the feature from the title. Or at least some aspects of it.

Recently, `ALTER VIEW SET AUTHORIZATION` on views with `SECURITY DEFINER` was disabled because of insufficient security checks. In terms of re-enabling it with better checks, there are some questions.

There are two kinds of target principals: `USER` and `ROLE`. For several reasons they are fundamentally different and have to be handled separately.

* `ROLE`: An attempt to re-enable it is in trinodb/trino#10567. The problem with this is that no connector supports role ownership (at least not yet), so it's not very useful[^1]. But it's the easier one, because the logic behind it - it should be equivalent, in terms of privileges, to `DROP`ping and `CREATE`'ing the view anew - is easier to implement (and to figure out, in the first place). For example, we can reuse the check whether the user can `SET` the target role.
* `USER`: It would seem that this is the primary use case for this feature, if only because it is actually supported by the connectors. But its usefulness is not clear (e.g. there's a trend to prefer role ownership), and neither is how to actually implement checks for it.

So this leaves us with the following questions:

* Is the aforementioned PR for `ROLE` doing the right thing? (Yes, this is redundant, because we can discuss it in the PR.)
* Do we want to re-enable it for `USER` at all?
* If so, how do we implement it?

And the meta-question:

* Is the feature worth all the effort?

To clarify the above, I can imagine two possibilities. One is that this feature does not have compelling use cases. On the other hand, it was added for a reason, one of which is inability to create a view with an owner other than the current user. And thus the other possibility: maybe there are other ways to cover the use cases, like providing a way to give an owner in `CREATE VIEW` (see also #10593, where one of the possibilities is enhancing `SHOW CREATE` to output `CREATE VIEW` with an owner clause).

[^1]: Some recent changes may change that. For example, there's an API (not implemented anywhere yet) to track ownership in system metadata (44c7be033ebd418af47269f762cf566e143a604a), so we no longer have to rely on the connectors to do it for us.

**Comment by ksobolew** [comment]
> If so, how do we implement it [`SET AUTHORIZATION USER`]?

In offline discussions there were two possibilities raised:

* Add another check to `AccessControl`
* Use the same logic as for `ROLE`, re-using different checks, like whether the user can impersonate the target user

The first one is unconvincing, because there already is `checkCanSetViewAuthorization`, and it was implemented badly. This is too sensitive to leave it to implementations of access controls to get right every time. The checks need to be independent of a particular access control used.

The second one was rejected, although I don't remember why. Perhaps we should revisit it.

**Comment by ksobolew** [comment]
@kokosing is this issue resolved?

**Comment by kokosing** [comment]
Yes. It is solved by pushing the responsibility to access control implementation to make sure it is secured operation.
