### ISSUE TITLE
TO_TIMESTAMP on Oracle DATE type generates inefficient plan in case of indexed column 

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#10626]
`LongWriteFunction` was changed to handle old dates issue in https://github.com/trinodb/trino/commit/77cfd97ffb159ec33a68938684a0b7ccc91b58f5. However, using `TO_TIMESTAMP` instead of `Statement.setObject(index, oracle.sql.TIMESTAMP)` decreased the performance when the column type is date.

**Comment by findepi** [comment]
Why `TO_TIMESTAMP` decreases performance? 
the bound value is a constant expression after all.
Does oracle has a special handing for `col > ?` vs `col > expr(?)`?

**Comment by bonuhov** [comment]
The problem is described [here](https://trinodb.slack.com/archives/CGB0QHWSW/p1642138785156200)

**Comment by ebyhr** [comment]
@findepi  It's type matching rather than expression. This issue will be fixed if we use `"TO_DATE(?, 'SYYYY-MM-DD HH24:MI:SS')"` as a bind expression. I will send the PR.
