### ISSUE TITLE
Implement Iceberg routine for removing orphaned files

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#10623]
Implement analogous of `remove_orphan_files` as described in https://iceberg.apache.org/#spark-procedures/.

**Comment by losipiuk** [comment]
cc: @findepi @jackye1995

**Comment by findepi** [comment]
This is sometimes called "vacuum".

**Comment by MichaelTiemannOSC** [comment]
So what is the remaining distance between the  PR covering #10622 merged into Trino 371 and this enhancement?
