### ISSUE TITLE
Fix flaky GitHub Actions milestone job

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#10652]

**Comment by nineinchnick** [comment]
@ebyhr do you remember what this is about?

**Comment by ebyhr** [comment]
@nineinchnick The milestone job rarely fail as https://github.com/trinodb/trino/actions/workflows/milestone.yml?query=is%3Afailure

**Comment by nineinchnick** [comment]
I was hoping you might have an idea about the root cause. I think I've seen this error a few times:
```
Unhandled error: HttpError: Validation Failed: {"resource":"Milestone","code":"already_exists","field":"title"}
```
Maybe we can change the action to handle the `already exist` error and try to get the milestone again.

**Comment by ebyhr** [comment]
@nineinchnick I couldn't find the root cause when I was debugging the issue in January. Adding retry logic looks good to me.
