### ISSUE TITLE
Add file-based and PAM authentication

### ISSUE THREAD

**Issue by bb786112** [trinodb/trino#1065]
Hi,

Can we add a new File & PAM based auth in Presto by default? Many user does not want to work with LDAP option already available in Presto.

Thanks
Bharat

**Comment by stagraqubole** [comment]
This would be of interest: https://github.com/prestosql/presto/pull/797

**Comment by hashhar** [comment]
File based auth is here https://trino.io/docs/current/security/password-file.html.

No plans for PAM.
