### ISSUE TITLE
Switch SingleStore (memsql) JDBC driver from MariaDB to official driver

### ISSUE THREAD

**Issue by jhlodin** [trinodb/trino#10669]
See memsql plugin: https://github.com/trinodb/trino/blob/8e9da982f95a531b52a72c9cda39d96b00d126ce/plugin/trino-memsql/pom.xml#L72

Currently we package the [MariaDB JDBC driver](https://mariadb.com/kb/en/about-mariadb-connector-j) to connect to SingleStore, but there is now an official [SingleStore JDBC driver](https://docs.singlestore.com/managed-service/en/developer-resources/connect-with-application-development-tools/connect-with-java-jdbc/the-singlestore-jdbc-driver.html).

@findepi @ebyhr Any insight as to why we use the MariaDB driver or otherwise if this is something worth doing?

**Comment by ebyhr** [comment]
The reason is there was no the dedicated JDBC driver when we introduced the connector. It worth switching the driver.

**Comment by leveyja** [comment]
TestMemSqlTypeMapping.testUnsignedTypes() is failing with the SingleStore driver. I'll investigate and see if we need a code change to support it (or if the driver needs a fix itself). Thanks for mentioning it @ebyhr ! 👍

**Comment by leveyja** [comment]
There is a bug in the field decoding in v1.0.0 and v.1.0.1 of the new SingleStore driver.
`0.1.0-preview` release of SingleStore doesn't have the issue. I'm investigating how to file a bug or submit a fix to their repo: https://github.com/memsql/S2-JDBC-Connector/releases - but until then this looks like a blocker for switching (and slightly worrying).

**Comment by ebyhr** [comment]
@leveyja You can handle the byte overflow by fixing `MemSqlClient.getUnsignedMapping()`. The `typeHandle.getJdbcTypeName()` contains precisions after the upgrade likes `tinyint(3) unsigned`

**Comment by leveyja** [comment]
Thank you! I was in `MemSqlClient` trying to determine how/why it worked in 0.1.0-preview versus 1.0.0/1.0.1.
That's exactly the issue - name is now "TINTINT(3) UNSIGNED", not "TINYINT UNSIGNED".
Should be straight-forward (ish) to fix 👍
