### ISSUE TITLE
Error is reported when maven packge

### ISSUE THREAD

**Issue by xianjuntang** [trinodb/trino#10676]
latest edition trino。Failed to execute goal org.skife.maven:really-executable-jar-maven-plugin:1.0.5:really-executable-jar (default) on project trino-cli: FAILURE!

**Comment by ebyhr** [comment]
Could you share the result of `./mvnw -version`?

**Comment by ebyhr** [comment]
Let me close as we can't reproduce the issue and there's no response for a while. Feel free to continue at https://trino.io/slack.html if you want to talk interactively.
