### ISSUE TITLE
Investigate cache correctness with respect to invalidation in raptor-legacy

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#10688]
For example, in `io.trino.plugin.raptor.legacy.storage.ShardRecoveryManager.MissingShardsQueue#queuedMissingShards` cache, the `invalidate` may be called while `load` didn't complete yet (if the `future` completes quickly, or synchronously), and the entry will be left in the cache.

Follows https://github.com/trinodb/trino/issues/10512

**Comment by ebyhr** [comment]
Closing as we removed Raptor connector.

**Comment by findepi** [comment]
the best solution
