### ISSUE TITLE
Investigate cache correctness with respect to invalidation in OAuth2TokenExchange

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#10685]
`OAuth2TokenExchange#cache` is a `LoadingCache` and `invalidate(key)` is called on it.
Thus it suffers from problems described nicely by @kokosing here: https://github.com/trinodb/trino/issues/10512

Needs investigation whether this is a problem or not.

It currently cannot use `EvictableLoadingCache`, as it currently doesn't support removal notifications.

**Comment by findepi** [comment]
cc @s2lomon @lukasz-walkiewicz

**Comment by kokosing** [comment]
Fixed by #10712
