### ISSUE TITLE
Deprecate and remove grouped execution

### ISSUE THREAD

**Issue by arhimondr** [trinodb/trino#10698]
https://github.com/trinodb/trino/issues/9101 will provide similar capabilities. It doesn't seem necessary to support both.

**Comment by findepi** [comment]
cc @losipiuk 

> #9101 will provide similar capabilities.

grouped execution triggers "proactively"
will https://github.com/trinodb/trino/issues/9101, "Support Failure Recovery", trigger its equivalent of grouped execution only after a failure, or proactively too?

**Comment by raunaqmorarka** [comment]
Already implemented by https://github.com/trinodb/trino/pull/12916
