### ISSUE TITLE
Unable to query Avro data on hdfs

### ISSUE THREAD

**Issue by tejaswibm** [trinodb/trino#10718]
## Issue
Querying Avro data stored on HDFS (Azure Blob in my case), returns no records. The query execution on UI shows that its complete, but resultset is empty

## Environment
```
Apache Hive 2.3.5
Trino v368
```

## Description
Azure Event Hubs capture data on azure blob in avro format. This data has the below schema 
```
{
  "type" : "record",
  "name" : "EventData",
  "namespace" : "Microsoft.ServiceBus.Messaging",
  "fields" : [ {
    "name" : "SequenceNumber",
    "type" : "long"
  }, {
    "name" : "Offset",
    "type" : "string"
  }, {
    "name" : "EnqueuedTimeUtc",
    "type" : "string"
  }, {
    "name" : "SystemProperties",
    "type" : {
      "type" : "map",
      "values" : [ "long", "double", "string", "bytes" ]
    }
  }, {
    "name" : "Properties",
    "type" : {
      "type" : "map",
      "values" : [ "long", "double", "string", "bytes", "null" ]
    }
  }, {
    "name" : "Body",
    "type" : [ "null", "string" ]
  } ]
}
```
Here, `Body` field has the actual data that is published to Azure Event Hub.

I created an external table on hive (mysql metastore) with below DDL statement -
```
CREATE EXTERNAL TABLE `test_avro`(
  `sequencenumber` bigint COMMENT '',
  `offset` string COMMENT '',
  `enqueuedtimeutc` string COMMENT '',
  `systemproperties` map<string,uniontype<bigint,double,string,binary>> COMMENT '',
  `properties` map<string,uniontype<bigint,double,string,binary>> COMMENT '',
  `body` string COMMENT '')
PARTITIONED BY (
  `process_date` date,
  `hour` string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.serde2.avro.AvroSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.avro.AvroContainerInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.avro.AvroContainerOutputFormat'
LOCATION
  'AZURE_BLOB_LOCATION(HDFS Compliant)'
TBLPROPERTIES (
  'avro.schema.url'='AZURE_BLOB_LOCATION/schema.avsc');
```

Partition registration -
`ALTER TABLE test_avro ADD IF NOT EXISTS PARTITION (process_date='2022-01-17', hour='05') LOCATION 'AZURE_BLOB_LOCATION/2022-01-17/05';`

Ran `select count(*) from test_avro` and the count is 0. Also tried `select * from test_avro limit 5` , result set is empty.

Attaching [sample avro](https://github.com/trinodb/trino/files/7911615/sample.txt) file for reference (renames as txt since avro files are not allowed)

## Expected result
Query on avro files should return the required result.

(For more context see https://trinodb.slack.com/archives/CGB0QHWSW/p1642406599054800?thread_ts=1642057624.138200&cid=CGB0QHWSW)

**Comment by hashhar** [comment]
For a partitioned table you need to register the partitions too before they can be queried.

Can you share the output of `SELECT * FROM "test_avro$partitions"`?
If there are no rows in that output either use `system.register_partition` or `system.sync_partition_metadata` procedure to get the partitions registered - see docs at https://trino.io/docs/current/connector/hive.html#procedures.

Once those partitions are added I believe your query should return results.

**Comment by tejaswibm** [comment]
@hashhar - Thanks for your reply. Yes I have registered partition before querying. I did not add it in the original post. Updating the main post.

**Comment by tejaswibm** [comment]
This issue is resolved now. It was a miss from our end in the hive configuration of trino. We missed adding - `hive.recursive-directories=true` to scan subdirectories. Setting this to `true` and we are able to read avro data. Thanks for the help from the community !
