### ISSUE TITLE
Writing to S3 sometimes results in corrupted files

### ISSUE THREAD

**Issue by sshkvar** [trinodb/trino#10710]
Hi we have migrated to Trino 367 and faced issue with create table as select in iceberg (Potentially all connectors which uses **TrinoS3FileSystem** affected)

We are doing CTAS in iceberg from other table (~482013195 records). 
After when we try to query created table
```sql 
select count(uuid) from iceberg.schema.just_created_table
```
 
we got exception

```
Query 20220119_153450_24112_cjit2 failed: Error reading from s3a://.../94a0afda-26d1-497d-9d48-362c5b36e363.parquet at position 27214944
```

After some investigation we found that because of some reasons we have multiple versions of parquet files, this is strange because each parquet file has uuid in name and we just created this table.
you can find screenshot in [this thread in slack](https://trinodb.slack.com/archives/CJ6UC075E/p1642662931013400?thread_ts=1642607192.009500&cid=CJ6UC075E) 

Additional retries of table creation shoved us that first version of parquet file always has the same size: 16 MB which is equal to [s3MultipartMinFileSize](https://github.com/dain/trino/blob/7ccedcdb156f834ea4076b83d603d1716ff902b3/plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/HiveS3Config.java#L62).

After it we checked all changes in `io.trino.plugin.hive.s3` package and found this one https://github.com/trinodb/trino/commit/73837347a4666476f26dbdc62f55386360902bbf.
We have reverted this change and it helped. We didn't have corrupted parquets in iceberg tables anymore.

Important note: issue is accidental, sometimes table created without issue.

**Comment by hashhar** [comment]
cc: @findepi @losipiuk

**Comment by findepi** [comment]
> Additional retries of table creation shoved us that first version of parquet file always has the same size: 16 MB which is equal to s3MultipartMinFileSize.

this is very suspicious

> After it we checked all changes in `io.trino.plugin.hive.s3` package and found this one [7383734](https://github.com/trinodb/trino/commit/73837347a4666476f26dbdc62f55386360902bbf).

Sounds like https://github.com/trinodb/trino/pull/9715 is related then
cc @joshthoward @electrum 

> We have reverted this change and it helped. We didn't have corrupted parquets in iceberg tables anymore.

good to hear that.

that also means you were testing with two builds, ie local modifications
did you also try with `hive.s3.streaming.enabled` off?

**Comment by losipiuk** [comment]
If revert helps I vote for reverting as initial fix and then rework original improvement

**Comment by findepi** [comment]
No longer considered a release blocker, as https://github.com/trinodb/trino/pull/10716 merged.
thank you @linzebing @losipiuk

**Comment by findepi** [comment]
@sshkvar can you please confirm the current master no longer exhibits the problem? 
@linzebing any chance this is testable? or there is nothing tbd in this issue?

**Comment by sbernauer** [comment]
We had the same problem with corrupt parquet and ORC files. In our case the CTAS in iceberg failed with `org.apache.iceberg.parquet.ParquetIO$ParquetInputFile@2700c43b is not a Parquet file. Expected magic number at tail, but found [49, -21, -31, 15]`
The current master with reverted https://github.com/trinodb/trino/commit/73837347a4666476f26dbdc62f55386360902bbf fixed the issue for us :+1: 
Thanks @sshkvar for bringing this up!

**Comment by sshkvar** [comment]
> @sshkvar can you please confirm the current master no longer exhibits the problem?

@findepi current master works without issue for us

**Comment by losipiuk** [comment]
@sshkvar I reworked the commit which caused the problem and it should be fine now. The new PR is https://github.com/trinodb/trino/pull/10729. Would that be ok for you to test it out?

**Comment by sshkvar** [comment]
> @sshkvar I reworked the commit which caused the problem and it should be fine now. The new PR is #10729. Would that be ok for you to test it out?

@losipiuk looks like reworked fix also working for us, I will continue testing and let you know in case of any issue

**Comment by losipiuk** [comment]
> > @sshkvar I reworked the commit which caused the problem and it should be fine now. The new PR is #10729. Would that be ok for you to test it out?
> 
> @losipiuk looks like reworked fix also working for us, I will continue testing and let you know in case of any issue

Thanks @sshkvar. Very much appreciate your help here.
