### ISSUE TITLE
CREATE VIEW does not validate if SELECT access to base table has GRANT OPTION

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#10727]
Reproduction (on `HiveQureryRunner` with `hive.security=sql-standard`)

As admin:
```
$ trino-cli  --user admin
trino:tiny> set role admin in hive;
SET ROLE
trino:tiny> create schema hive.default;
CREATE SCHEMA
trino:tiny> use hive.default;
USE
trino:default> create table nation as select * from tpch.tiny.nation;
CREATE TABLE: 25 rows
trino:default> create role r1 in hive;
CREATE ROLE
trino:default> grant select on nation to role r1;
GRANT
trino:default> grant r1 to user u1 in hive;
GRANT ROLE
```

Then as user `u1`:
```
trino:tiny> use hive.default;
USE
trino:default> set role r1 in hive;
SET ROLE
trino:default> create view v as select * from nation;
CREATE VIEW
```

In the above example `CREATE VIEW` should fail as SELECT grant on `nation` does not have `GRANT OPTION`. So any other user that would be using that view will get an access denied.

**Comment by kokosing** [comment]
From https://github.com/trinodb/trino/blob/e6c62cddde177ef3da4ed1dcecfdf4efb5194087/core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java#L3472 we don't create view access control if `owner = session user`. 

I am not sure if it is a desired behavior.

**Comment by electrum** [comment]
This is expected behavior. We allow users to create views for their own use. It is a feature. 

Note that a user with grant option could create a view and later have the grant option revoked, which is why we check for grant option when the view is queried.
