### ISSUE TITLE
Document DB backed resource group manager

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#10742]
Related to  https://github.com/trinodb/trino/pull/9812

I am not aware of any docs. Here is all we got https://trino.io/docs/current/admin/resource-groups.html

Maybe @posulliv can provide some info since he created the linked PR...

**Comment by posulliv** [comment]
@mosabua yep, will do. I will work on getting this documented next week.

**Comment by mosabua** [comment]
Awesome @posulliv !
