### ISSUE TITLE
Bigquery connector: no caching for case insensitive names

### ISSUE THREAD

**Issue by grantatspothero** [trinodb/trino#10740]
When `bigquery.case-insensitive-name-matching` is enabled, there is currently no caching of the mappings from case insensitive names to remote case sensitive names:
(see here for details: https://github.com/trinodb/trino/issues/10697)

This is a problem because when listing schemas/tables through trino `.toRemoteDataset/.toRemoteTable` are called once per schema/table respectively, resulting in a listing query for each respective schema/table.

https://github.com/trinodb/trino/blob/master/plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java#L128
https://github.com/trinodb/trino/blob/master/plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java#L176-L179

This is likely the root cause of slow metadata listing in this issue: https://github.com/trinodb/trino/issues/4580

**Comment by grantatspothero** [comment]
Started down the path of implementing *just* a case insensitive metadata cache here: https://github.com/trinodb/trino/compare/master...grantatspothero:gn/bigQueryClientCacheFixes?expand=1

But a better solution would build the general metadata cache as described here: https://github.com/trinodb/trino/issues/10741

And then use that to implement the case insensitive mapping cache.

**Comment by ebyhr** [comment]
> This is likely the root cause of slow metadata listing in this issue: #4580

The issue was reported (Jul 26, 2020) before adding `bigquery.case-insensitive-name-matching` (Mar 5, 2021) and I could reproduce the issue without the flag.
