### ISSUE TITLE
Add more information about the split in PhoenixSplit getInfo()

### ISSUE THREAD

**Issue by ranganathg** [trinodb/trino#10757]
In the Phoenix Connector logs - we see below which doesn't give much information about the Phoenix Split. Looking at other connectors, it looks to make things better to add more information here like the regionServer location etc to make it easy to discover phoenix server side things.

DEBUG	<TaskId>	io.trino.execution.executor.TaskExecutor	Split <TaskId>-3 io.trino.plugin.phoenix.**PhoenixSplit@48b4b96a**

**Comment by findepi** [comment]
Could you please make a PR?

**Comment by rameshbabu-sfdc** [comment]
Hi Could some one add me as contributor for this. I would like to work on the changes.

**Comment by ebyhr** [comment]
@rameshbabu-sfdc Hi, please feel free to send PR. Also, you need to submit CLA
https://github.com/trinodb/trino/blob/master/.github/CONTRIBUTING.md

**Comment by rameshbabu-sfdc** [comment]
Submitted PR for the same. Can some one review and approve
https://github.com/trinodb/trino/pull/12741
@ebyhr @ranganathg
