### ISSUE TITLE
Trino Windows Build

### ISSUE THREAD

**Issue by dipsitevikas** [trinodb/trino#10769]
Is it not possible to build Trino on windows ? As I see mac OS and Linux only in build requirements ?

**Comment by dipsitevikas** [comment]
Cc: @sauliusvl @martint

**Comment by ebyhr** [comment]
Closing as duplicate of #2272. Please feel free to join our community Slack https://trino.io/slack.html

**Comment by mosabua** [comment]
You can probably build Trino with WSL2. Its worth trying
