### ISSUE TITLE
Extend test coverage for S3 streaming upload

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#10797]
## Extra testing

#10710 showed that we are lacking test coverage for S3 streaming upload. 
We should write testcases which upload files of multiple sizes with S3 streaming enabled (default currently). Specifically
* file of size less than 16MB (multipart size)
* file of size greater than 16MB but less than 32MB (it was a trigger for #10751 
* file of size greater thatn 32MB

For tests which talk to real S3 endpoint on AWS we should extend `AbstractTestHiveFileSystemS3` (this test is run for `master` and for PRs originated from trinodb/trino).

`AbstractTestHiveFileSystemS3` is a low-level test in which we directly create PageSink etc. To have more blackbox coverage we can also write an integration test which uses MiniIO based QueryRunner and consumes SQL statements to trigger writing.
For that `BaseTestHiveOnDataLake` can be extended.

## Extra guards in TrinoS3FileSystem

Additionally it would be nice to add extra guards to `TrinoS3FileSystem` filesystem which ensure that `close()` would not call `finishUpload` if file upload is alredy considered completed; when code path which [uploads small files without multipart mechanism](https://github.com/trinodb/trino/blob/1b110c51792fa11759285e2e89d77033e2a4363b/plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java#L1578-L1597) 
 is executed. Having such guard would prevent #10710 from happening.

cc: @linzebing @findepi @joshthoward

**Comment by linzebing** [comment]
Closed via https://github.com/trinodb/trino/pull/11678
