### ISSUE TITLE
Migrate trinodb/trino-maven-plugin from Travis to GitHub Actions

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#10849]
Need to migrate [trino-maven-plugin](https://github.com/trinodb/trino-maven-plugin) to use GitHub actions instead of Travis CI. See https://github.com/trinodb/trino/issues/6859 for some guidance.

**Comment by ebyhr** [comment]
Closing as https://github.com/trinodb/trino-maven-plugin/pull/20
