### ISSUE TITLE
Migrate trinodb/tpcds from Travis to GitHub Actions

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#10850]
Need to migrate [tpcds](https://github.com/trinodb/tpcds) to use GitHub actions instead of Travis CI. See https://github.com/trinodb/trino/issues/6859 for some guidance.

**Comment by hectorhuol** [comment]
Hi @hashhar, is this issue still open for contribution? I would like to work on it.

**Comment by hashhar** [comment]
Fixed in https://github.com/trinodb/tpcds/pull/1
