### ISSUE TITLE
Migrate trinodb/tpch from Travis to GitHub Actions

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#10851]
Need to migrate [tpch](https://github.com/trinodb/tpch) to use GitHub actions instead of Travis CI. See https://github.com/trinodb/trino/issues/6859 for some guidance.

**Comment by winio94** [comment]
@hashhar can I work on this?

**Comment by winio94** [comment]
@hashhar here is PR with the changes - https://github.com/trinodb/tpch/pull/26
