### ISSUE TITLE
Support "tagged" queries

### ISSUE THREAD

**Issue by abrisan** [trinodb/trino#10853]
Hello trino-ers 🥇 

We own some trino client applications that pass through OAuth credentials to trino for authentication and authorization. Our setup additionally has an [event listener](https://trino.io/docs/current/admin/event-listeners-http.html) set up, which pipes metadata through an [ingestion service](https://github.com/bloomberg/datalake-query-ingester) in order to allow us to monitor and analyse usage of our trino clusters.

One thing we have noticed is that due to us passing the OAuth credentials to trino, the queries are executed as the user who is logged in, rather than a generic role account. This is advantageous for numerous reasons, such as permissioning and usage metering, however it makes it very difficult to estimate usage trends across applications, as we have no way of knowing, for a user, which application they were using when a query was made in their name. Unfortunately, we operate a large number of client applications, and it is not always possible to perform the metering on the application side.

As such, we would like to offer a contribution to support "tagged" queries. Clients would then be able to pass in a simple list of strings that would act as tags, and this information would then be included in the Event Listener SPI, allowing all implementations to consume it.

This would likely require additional changes to both the `jdbc` driver and the `Python` connection library.

We would like to raise the following questions with the community:

1. Would there be a more general interest in such a feature?
2. Would it be advisable to make the list of "allowable" tags a configuration option in a trino cluster?

Thanks and once again we ❤️ Trino!

**Comment by martint** [comment]
Tags are already supported by the client protocol (see X-Trino-Client-Tags in https://trino.io/docs/current/develop/client-protocol.html) and throughout the system (resource groups, event listener, etc). 

It’s possible they are not yet supported in the jdbc and python clients, though.

**Comment by abrisan** [comment]
Thanks, this is exactly what we needed. Closing.

**Comment by hashhar** [comment]
Follow-up for Python client tag support in https://github.com/trinodb/trino-python-client/pull/154. Thanks @abrisan
