### ISSUE TITLE
NPE when accessing a table with no properties using Hive Glue metastore

### ISSUE THREAD

**Issue by bind-cannon** [trinodb/trino#10864]
In the class
https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/tr[…]ive/metastore/glue/DefaultGlueMetastoreTableFilterProvider.java

line 52 starts with table.getParameters(). This returns null if there are no table parameters resulting in a Null Pointer Exception. This was causing all our users to get errors when trying to list the tables in the associated database. As a work around, we added a single dummy property.

**Comment by findepi** [comment]
@bind-cannon thanks for your issue. Do you want to check the link? it 404s for me.

**Comment by samnaden-bind** [comment]
@findepi I think this is the link David was after:
https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DefaultGlueMetastoreTableFilterProvider.java

**Comment by findepi** [comment]
The fix would be simpler, wonder whether it's testable?
