### ISSUE TITLE
Add SqlDataTypeTest to Cassandra connector

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#10860]
The current test `TestCassandraConnectorTest` has some issues:
* Unrelated types in a table
  * It reduces maintainability when we want to add test cases to a type
* The definition and data are managed in the different class
  * We need to look for the different class when we want to check the expected values
* Less coverage in a type
  * Should test min, max, null
  * Should test DST, julian->gregorian

It would be nice to introduce type mapping tests.

**Comment by tangjiangling** [comment]
I'd like to try, please assign it to me. :)

**Comment by tangjiangling** [comment]
Sorry for the delay. I have a few questions about the above description:

> Unrelated types in a table

This is saying that some of the fields in the test table contain fields that are not related to the current field, do I understand this correctly?

> The definition and data are managed in the different class

Does this mean that we'd better write the table definition in the same test method as the data? Like this [one example](https://github.com/trinodb/trino/blob/master/plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java#L110-L134).

> Less coverage in a type

Does this mean that some field types are not covered by the test and I need to look at the code as well as the documentation to find out exactly which types?

> It would be nice to introduce type mapping tests.

Can I refer to [this example](https://github.com/trinodb/trino/blob/master/plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java)?

**Comment by ebyhr** [comment]
> This is saying that some of the fields in the test table contain fields that are not related to the current field, do I understand this correctly?

Yes.

> Does this mean that we'd better write the table definition in the same test method as the data? Like this [one example](https://github.com/trinodb/trino/blob/master/plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java#L110-L134).

Yes, but the right example is `TestClickHouseTypeMapping.java`. You don't need to refer to other test classes. 

> Does this mean that some field types are not covered by the test and I need to look at the code as well as the documentation to find out exactly which types?

No, it meant the tested values are limited. We should add edge cases (min, max, null and so on)

> Can I refer to [this example](https://github.com/trinodb/trino/blob/master/plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java)?

Yes
