### ISSUE TITLE
Cap Hive split size by max number of rows

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#10884]
Smaller splits sizes are beneficial for unpartitioned benchmarks as they improve CPU utilization.
We can generate Hive splits that do not exceed given estimated row number based on hive table or partition stats.

**Comment by findepi** [comment]
How would that differ from lowering `hive.max-initial-split-size`?

cc @alexjo2144

**Comment by sopel39** [comment]
> How would that differ from lowering hive.max-initial-split-size?

To be benchmarked. Maybe it's a better idea.

**Comment by sopel39** [comment]
Still size is only loosely coupled with number of rows, so depending on query, you might still end up with bad parallelism

**Comment by Praveen2112** [comment]
What if the stats are not available, do we fall back to size based mechanism ?

**Comment by sopel39** [comment]
> What if the stats are not available, do we fall back to size based mechanism ?

yes

**Comment by sopel39** [comment]
This does not improve perf
