### ISSUE TITLE
Insert into bucketed, unpartioned Hive table not allowed

### ISSUE THREAD

**Issue by springjd** [trinodb/trino#1088]
Up through 316 when inserting into a Hive table that is bucketed, but not partitioned, e.g.

```create table hive.default.test_table(
 user_id bigint, 
firstname varchar, 
lastname varchar, 
city varchar ) 
with ( 
bucketed_by = ARRAY['user_id'] ,
bucket_count=25);

insert into table hive.default.test_table (
11,
'Juan',
'Carlos',
'Madrid');
```
Presto give the error:
`Query 20190705_191449_00002_f53b3 failed: Cannot insert into bucketed unpartitioned Hive table`

Inserting into a partitioned, bucketed table works as expected.

**Comment by raunaqmorarka** [comment]
Fixed by https://github.com/trinodb/trino/issues/1088
