### ISSUE TITLE
Support Iceberg's All_Entries Metadata table

### ISSUE THREAD

**Issue by osscm** [trinodb/trino#10882]
Spark supports iceberg's All_* metadata tables. This issue is to add the `All_Entries` metadata table. 
We can create separate issues for different tables.

reference: https://github.com/apache/iceberg/blob/e146d812f251f1ee5b54edd7dc696034c5ff75f4/core/src/main/java/org/apache/iceberg/MetadataTableUtils.java#L71

Also wondering if we can also think of reusing `Metadata table` classes that Iceberg has like: [AllEntries](https://github.com/apache/iceberg/blob/5505321af663befa89095ed6643b2de9be481788/core/src/main/java/org/apache/iceberg/AllEntriesTable.java#L110) instead of doing it doing it in the Trino APIs.

**Comment by osscm** [comment]
cc @findepi @RussellSpitzer

**Comment by findepi** [comment]
This probably would map to `$all_manifest_entries`.

@osscm what would be the use-case?

**Comment by osscm** [comment]
@findepi 
`All_Entries` exposes all the entries of Manifest file, including the valid and deleted data files in the table manifests.
`All_Datafiles` exposes valid data files in the table manifests.

**Comment by ebyhr** [comment]
Closing as #24543
