### ISSUE TITLE
Table and column names mapping in Mongo

### ISSUE THREAD

**Issue by filippocozzini** [trinodb/trino#10890]
Hi there!
I have searched for a whole day for the solution but I could not find it, I believe this function does not exist. 
It would be interesting to be able to map the name of the table and fields of the source database and to have a different name on Trino.
I saw that the only connector that gives this possibility is the one for MySQL.

Thanks!

**Comment by ebyhr** [comment]
I couldn't understand this feature. Could you describe more details?

**Comment by filippocozzini** [comment]
Ok sorry, my english is not perfect, so i try to explain better!

When i have a collection (table) on MongoDB called "users" that contains a document with 3 fields:

- name
- email
- password

I need that on Trino, it's possible to change (map) collection and fields names as follow: 
Table: users --> users_base
Fields:
- name --> first_name
- email --> contact
- password --> secret

In this way i can execute a query on trino like this: `SELECT first_name, contact FROM users_base`
It's this possibile? Thank in advance!

**Comment by ebyhr** [comment]
It's not possible in MongoDB connector. What's the motivation?

**Comment by filippocozzini** [comment]
I need to expose some of my tables to some users, but I need to mask the tables and fields of my db. Are there any solutions?

**Comment by ebyhr** [comment]
You can prepare views in MongoDB side and hide the original identifiers. 
https://www.percona.com/blog/2019/07/05/hiding-fields-in-mongodb-views-custom-roles/. 

Please feel free to ask in the community Slack for more details. 
https://trino.io/slack.html
