### ISSUE TITLE
MongoDB: column allow false return access denied on select *

### ISSUE THREAD

**Issue by filippocozzini** [trinodb/trino#10891]
Hi! 
I'm trying to run a query similar to this: 
`SELECT * FROM users` where the "password" column has set allow: false in the file system access control as follow:

```
{
  "catalog": "mongo",
  "schema": "test",
  "table": "users",
  "privileges": ["SELECT"],
  "columns": [
    {
      "name": "password",
      "allow": false
    }
  ]
},
```

Trino return this error `Access Denied: Cannot select from table mongo.test.users` and the only way not to return error is to set hidden: true on _schema table in MongoDB as follow:

```
name: password
type: varchar
hidden: true
```
 
 Is this a bug? Thanks in advance!

**Comment by findepi** [comment]
I think you're looking for https://github.com/trinodb/trino/pull/7893, https://github.com/trinodb/trino/pull/8752

**Comment by filippocozzini** [comment]
Thank you so much!
