### ISSUE TITLE
SymlinkTextInputFormat defaults to input format as SEQUENCEFILE 

### ISSUE THREAD

**Issue by benrifkind** [trinodb/trino#10910]
It seems like Trino treats Hive tables stored as s3 symlinks as if the actual files have the SEQUENCEFILE input format. This is an issue when the files are stored as TEXTFILE and I am not sure how to toggle between them. Just a note that it seems like the expectation in Hive is that the symlinks are stored as TEXTFILE
https://hive.apache.org/javadocs/r2.1.1/api/org/apache/hadoop/hive/ql/io/SymlinkTextInputFormat.html#:~:text=Symlink%20file%20is%20a%20text,data%20should%20be%20in%20TextInputFormat.
> Symlink file is a text file which contains a list of filename / dirname. This input method reads symlink files from specified job input paths and takes the files / directories specified in those symlink files as actual map-reduce input. The target input data should be in TextInputFormat.
------
Here is a minimal working example (replace <bucket> with your bucket of choice).
This is the create table statement in Hive.
```
CREATE EXTERNAL TABLE `bi_temp.foo`( `id` string )
ROW FORMAT SERDE
  'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='\t') 
STORED AS INPUTFORMAT 'org.apache.hadoop.hive.ql.io.SymlinkTextInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 's3://<bucket>/benrifkind/bi_temp/foo';
```

And then uploading data to the symlinks from my local command line
```
$> echo "1\n2\n3\n" > '/tmp/1.txt'
$> aws s3 cp /tmp/1.txt s3://<bucket>/benrifkind/symlink/foo/1.txt

$> echo 's3://<bucket>/benrifkind/symlink/foo/1.txt' > /tmp/symlink.txt
$> aws s3 cp /tmp/symlink.txt s3://<bucket>/benrifkind/bi_temp/foo/symlink.txt
```

From Trino
```
select * from bi_temp.foo;
Query 20220202_170239_00899_imsit failed: Error opening Hive split s3://<bucket>/benrifkind/symlink/foo/1.txt (offset=0, length=7) using org.apache.hadoop.hive.ql.io.SymlinkTextInputFormat: s3://<bucket>/benrifkind/symlink/foo/1.txt not a SequenceFile
```

Note that this works in Presto
```
select * from bi_temp.foo;
 id
----
 1
 2
 3
```
----
I believe the issue comes from this line 
https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java#L329-L332
![image](https://user-images.githubusercontent.com/8431062/152202260-7af1dfae-a805-4fcb-998d-7d78932d2d1d.png)

The point is that both SEQUENCEFILE and TEXTFILE share the `LazySimpleSerDe` serde. And the `SEQUENCEFILE` comes first in the list of values so it is matched.
https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveStorageFormat.java#L85-L99
![image](https://user-images.githubusercontent.com/8431062/152202824-67380e2e-9543-4699-aae8-274b11abf9ba.png)

I switched that enum so that  `TEXTFILE` comes before `SEQUENCEFILE` and the query succeeds.

I think this is the commit that caused this change in behavior: https://github.com/trinodb/trino/commit/61d33ccb250a657b5d2da1898833099cb76d9ae5
And the actual change
![image](https://user-images.githubusercontent.com/8431062/152205575-5c842efa-7c88-43e5-81fd-6bcc9bbf0937.png)

https://github.com/trinodb/trino/commit/61d33ccb250a657b5d2da1898833099cb76d9ae5#diff-a1393fbeff5a07f525676cb2eeab441fe2ae6da1f5b7af0a75f508e3614c5572R308-R315

**Comment by benrifkind** [comment]
This is a workaround. Use the `OpenCSVSerde`.
```
CREATE EXTERNAL TABLE `bi_temp.foo`( `id` string )
ROW FORMAT SERDE
  'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ('field.delim'='\t') 
STORED AS INPUTFORMAT 'org.apache.hadoop.hive.ql.io.SymlinkTextInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 's3://<bucket>/benrifkind/bi_temp/foo';
```

**Comment by findepi** [comment]
> I think this is the commit that caused this change in behavior: [61d33cc](https://github.com/trinodb/trino/commit/61d33ccb250a657b5d2da1898833099cb76d9ae5)

https://github.com/trinodb/trino/pull/6213; cc @sopel39

**Comment by sopel39** [comment]
It seems that `io.trino.plugin.hive.util.HiveUtil#getDeserializerClassName` is not enough distinction to recognize target file format. We either:
1. try to use some other field, e.g: `serialization.format` to recognize target format
2. Fallback to text for `LazySimpleSerDe` in case of symlink.

@benrifkind what's the advantage of using `LazySimpleSerDe` instead of `OpenCSVSerde` directly?

**Comment by benrifkind** [comment]
@sopel39 I don't know too much about serde's so I don't know about an advantage. I did not know about `OpenCSVSerde` when I created the issue. `LazySimpleSerDe` was just the serde of some table schemas we had. Which makes sense because it seems like `LazySimpleSerDe` is the default if no serde is specified. My current understanding is that since the Hive documentation I linked above states the expected file format for a symlink is `TextInputFormat` it makes sense for the default serde (`LazySimpleSerDe`) for a symlink to return the target format `TextInputFormat`.

Example that no specified serde gets `LazySimpleSerDe`
```
hive> CREATE EXTERNAL TABLE `bi_temp.foo`( `id` string )
    > STORED AS INPUTFORMAT 'org.apache.hadoop.hive.ql.io.SymlinkTextInputFormat'
    > OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
    > LOCATION 's3://<bucket>/bi_temp/foo';

hive> show create table bi_temp.foo;
OK
CREATE EXTERNAL TABLE `bi_temp.foo`(
  `id` string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.SymlinkTextInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://<bucket>/bi_temp/foo'
TBLPROPERTIES (
  'transient_lastDdlTime'='1644252722')
```

**Comment by sopel39** [comment]
@willmostly Can you add your input? I recall there were users relying on non-text format recognition.

Even before my change we didn't always use textformat
```
                // Symlink targets are assumed to be TEXTFILE unless serde indicates otherwise.
                inputFormatClass = TextInputFormat.class;
                if (isDeserializerClass(schema, AvroSerDe.class)) {
                    inputFormatClass = AvroContainerInputFormat.class;
                }
```

Hence I think `Fallback to text for LazySimpleSerDe in case of symlink.` is more sensible solution.

**Comment by willmostly** [comment]
Regarding the utility of non-text support -
The capability for reading Parquet data with `SymlinkTextInputFormat` is used to integrate with Databricks Delta ([details](https://docs.databricks.com/delta/presto-integration.html)). Snowflake and Redshift Spectrum now also support the same non-standard use of Parquet+Symlink. I'm also aware of one large user who manages compactions through custom ETL + symlink with Parquet. I have never seen it used with Sequence Files though, for what thats worth.

@sopel39 is correct - we made some changes to make Symlink perform better in some cases, but the ability to read non-text formats including Parquet and Avro were not introduced by our changes. 

I agree that `LazySimpleSerDe` is the correct default, as @benrifkind and @electrum point out this follows the docs and is the common Serde for delimited data.

**Comment by sopel39** [comment]
My fix proposal is in https://github.com/trinodb/trino/pull/11003
