### ISSUE TITLE
Metrics for time spent in components of coordinator such as split sourcing

### ISSUE THREAD

**Issue by lgo** [trinodb/trino#10971]
While recently working optimizing a series of Trino queries for latency, I had a challenging time measuring the work/delay incurred from split sourcing. The Iceberg tables involved consist of 10k+ files, upwards to 100k-200k files for some, as the datasets involved are >100TB.

In particular, I'm working with an Iceberg table and simple queries such as `select * from foo where [...]`. These queries just involve the coordinator sourcing splits for Iceberg table, scheduling split scans, and a collection stage task.

A non-trivial portion of the queries appear to be elapsed during `IcebergSplitManager#getSplits`. It has been difficult to measure the direct impact of this on queries, how much it increases with more files it (e.g. is it linear and 2x files doubles latency). I haven't looked at whether I can approximate this from timestamps of the query and first tasks, but that would going to be my next step.

From the Trino slack, findepi reasonably highlighted split sourcing will happen in parallel throughout the lifecycle of a query so this isn't just a "time taken to source in the beginning".

Anything from individual split source timestamps and durations, to measurements of the blocking coordinator split source, to log lines, would really help in a situation like this.

**Comment by findepi** [comment]
In the web ui there is a timeline view. I think it's supposed to help you with what you're up to.

**Comment by lgo** [comment]
Right, so in an example like the below, that would be the time prior to split creation.
<img width="1329" alt="Screen Shot 2022-02-08 at 06 33 35" src="https://user-images.githubusercontent.com/1161183/153008296-5c574e85-854d-4e33-aad0-be7d36172ca6.png">

While looking at that I dug into the JSON query stats of the `select * from iceberg.table where col = ... limit 1` query and dissected some interesting tidbits. Note, this query just has an an output stage with one substage for the scanning tasks.

Extracted from this `jq`
```sh
cat query_stats.json | jq '
  {
    createTime: .queryStats.createTime,
    executionStartTime: .queryStats.executionStartTime,
    endTime: .queryStats.endTime,
    elapsedTime: .queryStats.elapsedTime,
    queuedTime: .queryStats.queuedTime,
    resourceWaitingTime: .queryStats.resourceWaitingTime,
    dispatchingTime: .queryStats.dispatchingTime,
    executionTime: .queryStats.executionTime,
    analysisTime: .queryStats.analysisTime,
    planningTime: .queryStats.planningTime,
    finishingTime: .queryStats.finishingTime,

    taskPipelineStartTimes: [.outputStage.subStages[0].tasks[] | .stats.pipelines[0].firstStartTime],
  }'
```

One example was
```json
{
  "createTime": "2022-02-08T14:46:39.724Z",
  "executionStartTime": "2022-02-08T14:46:40.171Z",
  "endTime": "2022-02-08T14:46:43.289Z",
  "elapsedTime": "3.57s",
  "queuedTime": "117.04us",
  "resourceWaitingTime": "447.71ms",
  "dispatchingTime": "44.76us",
  "executionTime": "3.12s",
  "analysisTime": "447.65ms",
  "planningTime": "332.31ms",
  "finishingTime": "103.40us",
  "taskPipelineStartTimes": [
    "2022-02-08T14:46:42.382Z",
    "2022-02-08T14:46:42.380Z",
    "2022-02-08T14:46:42.385Z",
    "2022-02-08T14:46:42.383Z",
    "2022-02-08T14:46:42.383Z",
    "2022-02-08T14:46:42.383Z",
    "2022-02-08T14:46:42.383Z",
    "2022-02-08T14:46:42.384Z",
    "2022-02-08T14:46:42.384Z",
    "2022-02-08T14:46:42.384Z",
    "2022-02-08T14:46:42.384Z",
    "2022-02-08T14:46:42.384Z",
    "2022-02-08T14:46:42.384Z",
    "2022-02-08T14:46:42.385Z",
    "2022-02-08T14:46:42.385Z",
    "2022-02-08T14:46:42.385Z",
    "2022-02-08T14:46:42.382Z"
  ]
}
```

There's a difference of 2.211s between the execution start time and the first tasks starting. I'm going on plenty of assumptions, which are likely wrong (please correct me!):
- Difference of `createTime` and `executionStartTime` is `resourceWaitingTime`
- `executionTime` includes `analysisTime`, `planningTime`, the pipeline executions, among other things. Initially I assumed execution time excluded analysis and planning time but it looks like it does? Tthat might be a helpful to clarify on the UI with a tooltip.

Excluding the analysis and planning time from the pre-task execution time (2.211s-447.65ms-332.31ms) leaves 1.431s, which I'd guess is mostly the Iceberg source time prior to tasks starting?

**Comment by raunaqmorarka** [comment]
We have a `getSplitDistribution` histogram metric in StageStats which can be found for each stage in the queryinfo json
```
"stageStats" : {
        "getSplitDistribution" : {
          "count" : 1.0,
          "total" : 2.5246131E7,
          "p01" : 2.5246131E7,
          "p05" : 2.5246131E7,
          "p10" : 2.5246131E7,
          "p25" : 2.5246131E7,
          "p50" : 2.5246131E7,
          "p75" : 2.5246131E7,
          "p90" : 2.5246131E7,
          "p95" : 2.5246131E7,
          "p99" : 2.5246131E7,
          "min" : 2.5246131E7,
          "max" : 2.5246131E7,
          "avg" : 2.5246131E7
        },
```
This should record only the time spent by the scheduler waiting for splits from the connector splits source.
It's not easy to find but it is available.
cc: @Dith3r @sopel39
