### ISSUE TITLE
Adding total or system peak memory usage at StatementStats

### ISSUE THREAD

**Issue by miniway** [trinodb/trino#10990]
From https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/server/protocol/Query.java#L745

Trino is returning only `peakUserMemoryReservation` to client and hiding `peakNonRevocableMemoryReservation` or `peakTotalMemoryReservation` intentionally. 

But by the `StatementStats` there's no way to get total or system peak memory usage and might not get full sense of memory usages as memory limitations are applied to both user and system memories. 

So would it be reasonable to add  `peakNonRevocableMemoryReservation` or  `peakTotalMemoryReservation` on the `StatementStats`? If so, I'll send a PR for this.

**Comment by Praveen2112** [comment]
We have recently removed the distinction between system and user memory - (https://github.com/trinodb/trino/pull/10574) so we don't track -` peakNonRevocableMemoryReservation` but I guess we could track ` peakTotalMemoryReservation`

cc: @findepi

**Comment by miniway** [comment]
It sounds great!

**Comment by findepi** [comment]
@miniway is there anything else TBD here?

**Comment by miniway** [comment]
the combined memory usage looks good. I’m closing it
