### ISSUE TITLE
Finished queries continue using memory pool on worker

### ISSUE THREAD

**Issue by sshkvar** [trinodb/trino#11030]
Hi, after update to Trino 367 we found that finished queries doesn't release memory pool on workers.

As a result we have a lot of queries which actually finished but still exists in workers memory pool.
On the chart below you can find amount of such queries and see how these amount grown after cluster restart

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/3986221/153827297-b2215cfa-70bd-4e72-b1dc-d704722909ce.png">

As you can see we have 12000 queries which actually finished but using memory pool on workers.
Les't see example of one worker 
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/3986221/153829554-eaf1dd85-3cfe-46a6-87d4-5f719ebae2a9.png">

On this worker we have 166 running queries, but 98 of them already finished but still using memory pool.
For example 20220210_093944_48617_446ev 
When I try to click on this query on open in new tab I see query not found

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/3986221/153829359-b10c20c5-a91a-4493-abcf-ca68f5adb1b1.png">

**Comment by losipiuk** [comment]
@sshkvar thanks for the report.
Can you provide some more information about the queries you are running.
* what connectors do you use
* can you quote example problematic query?
* Is the problem always reproducable for query of a given shape or is it non-deterministic?

**Comment by davseitsev** [comment]
Small update. All stuck queries have reservation only in `ExchangeOperator`:
```
  "queryMemoryAllocations": {
    "20220216_125714_10727_uzgkx": [
      {
        "tag": "ExchangeOperator",
        "allocation": 13218
      }
    ],
....
```
Amount of reserved memory is pretty small, up to a few megabytes.

**Comment by losipiuk** [comment]
@arhimondr is this manifestation of https://github.com/trinodb/trino/pull/10950? Or different thing?

**Comment by losipiuk** [comment]
And @sshkvar what Trino version did you use before 367?

**Comment by sshkvar** [comment]
No, we are not using retries. As I know it disabled by default

**Comment by losipiuk** [comment]
> No, we are not using retries. As I know it disabled by default

Yeah. 

Tricky - did you maybe have a chance to take a look into logs? Any errors/stacktraces logged?

**Comment by sshkvar** [comment]
> Tricky - did you maybe have a chance to take a look into logs? Any errors/stacktraces logged?

we didn't find any errors

> @sshkvar Do you know if the queries you see holding memory reservations finished successfully or failed?

queries finished successfully

**Comment by arhimondr** [comment]
@sshkvar Do your queries contain `LIMIT` operation? 

We've found a race condition that may result in memory not being release properly: https://github.com/trinodb/trino/pull/11088. But that shouldn't happen unless you have a `LIMIT` operation after exchange. For example a `LIMIT` after `JOIN`.

**Comment by arhimondr** [comment]
We should also improve our integration tests to verify that memory pools are empty upon completion: https://github.com/trinodb/trino/issues/11093

**Comment by losipiuk** [comment]
Should be fixed by https://github.com/trinodb/trino/pull/11088
