### ISSUE TITLE
int column in parquet not properly read by Presto

### ISSUE THREAD

**Issue by prabakarankrishnan** [trinodb/trino#1103]
In parquet file

optional int96 in_time;
optional int96 out_time;

But in Presto it is showing like below if column data type declare as varchar.
              id                | in_time  | out_time 

------------------------------------------+----------+----------

 d_1234.1986_-11.1233 | ^@b<EF><BF><BD><EF><BF><BD>dA^@^@t<EF><BF><BD>%^@ | ^@<EF><BF><BD>

**Comment by findepi** [comment]
@prabakarankrishnan how did you define the table? I.e. what's the output of `SHOW CREATE TABLE your_table`?

**Comment by tooptoop4** [comment]
protip: dont define int as varchar

**Comment by tooptoop4** [comment]
u there @prabakarankrishnan

**Comment by raunaqmorarka** [comment]
For data stored as INT96, the column type in the table DDL should be a timestamp.
