### ISSUE TITLE
Does Trino support custom udtf functions

### ISSUE THREAD

**Issue by yy598162719** [trinodb/trino#11112]
I am using hive and want to migrate sql to trino, hive has our custom udtf function。
What should I do when I encounter this problem? thanks

**Comment by ebyhr** [comment]
Please take look at https://trino.io/docs/current/develop/functions.html

You can continue in https://github.com/trinodb/trino/discussions or https://trino.io/slack.html if you have further questions.

**Comment by findepi** [comment]
This is tracked in #1839
