### ISSUE TITLE
Add CREATE TABLE with column comment test

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#11162]
https://github.com/trinodb/trino/pull/11143#discussion_r812788763

**Comment by findinpath** [comment]
@ebyhr I find the test  https://github.com/trinodb/trino/blob/c53ee94fd7ef5c6b259bf9ffa1a53cad8ea5e944/plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java#L915-L930 quite appropriate for this issue.

I think that we can keep this test as it is because it tests a different functionality of interacting with column comments than the one tested in `io.trino.testing.BaseConnectorTest#testCommentColumn`  which is testing `COMMENT ON COLUMN` functionality.

**Comment by ebyhr** [comment]
@findinpath I agree with leaving the test. It would be better to rename the method in my opinion though. 
e.g. `testAddColumnWithComment()`

**Comment by ebyhr** [comment]
Closed as #12574
