### ISSUE TITLE
Using qualified property key instead of identifiers is possible?

### ISSUE THREAD

**Issue by fengguangyuan** [trinodb/trino#11177]
Now we could `CREATE ... TABLE WITH PROPERTIES, or  ALTER TABLE ... SET PROPERTIES` on few connectors, for example:
```
CREATE TABLE tbl (id BIGINT) WITH ("property.qualified"='true', identifierProperty='true')
```
Here `property.qualified` must be surrounded by double quotation marks, otherwise failures come. The root cause is the grammar defined in SqlBase.g4:
```
properties
    : '(' propertyAssignments ')'
    ;

propertyAssignments
    : property (',' property)*
    ;
// actual
property
    : identifier EQ propertyValue
    ;
// expected
qualifiedName
    : identifier ('.' identifier)*
    ;
```

So, would it be easier to use `qualified name` as the property instead of identifiers? Thus the above sql can be simplified as
```
CREATE TABLE tbl (id BIGINT) WITH (property.qualified='true', identifierProperty='true')
```

**Comment by dain** [comment]
Table properties in Trino are typed identifier and not a generic bag of string to string values like hive.  This mean the key is an identifier and the value is a realy typed value.  So the above in trino would look like:
```
WITH (some_actual_name=true, a_decimal_property=42.42)
```

**Comment by findepi** [comment]
Closing as answered.
