### ISSUE TITLE
Normalize OR expressions referencing the same symbol as IN

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#1118]
For example:
```
symbol = 'foo' OR symbol = 'bar'
```
should be rewritten to:
```
symbol IN ('foo', 'bar')
```
IN expressions are easier for planner to deal with. For example, they will be inlined in `PredicatePushdown`.

**Comment by martint** [comment]
@Praveen2112 is looking into this

**Comment by hashhar** [comment]
Fixed by https://github.com/trinodb/trino/pull/17635.
