### ISSUE TITLE
Add support for changing Iceberg table properties

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#11190]
Syntax for changing Iceberg table properties

```
ALTER TABLE an-iceberg-table SET PROPERTIES a-property-name = 'a-value'
```

### Implementation tips

Implement the method `io.trino.spi.connector.ConnectorMetadata#setTableProperties`  in `io.trino.plugin.iceberg.IcebergMetadata`.

Use `org.apache.iceberg.BaseTable#updateProperties` for updating table properties.

### Test tips

Add a integration test in `io.trino.plugin.iceberg.BaseIcebergConnectorTest` for testing the functionality. Use https://trino.io/docs/current/connector/iceberg.html#properties-table for reading the properties of the Iceberg table.

Add a product test to the class `io.trino.tests.product.iceberg.TestIcebergSparkCompatibility` for checking the compatibility with Spark on updating table properties.

**Comment by puchengy** [comment]
This is very useful, thanks!

**Comment by findepi** [comment]
> Use `org.apache.iceberg.BaseTable#updateProperties` for updating table properties.

`ALTER TABLE  SET PROPERTIES` should change Trino Iceberg table properties (IcebergTableProperties).
It's not supposed to be a pass-thru for Iceberg properties.


From Trino Iceberg table properties (IcebergTableProperties) perspective, we want to allow changing of `partitioning` field.


cc @electrum @phd3 @ebyhr @alexjo2144

**Comment by osscm** [comment]
@findepi thanks for the detail!
As you mentioned that until a property is not part of the `IcebergTableProperties` we should not allow setting/adding random properties. So, this issue, if needed, can only tackle the updates to the partitioning field.

There was another https://github.com/trinodb/trino/pull/10480#issuecomment-1013542450 which seems to be looking for setting new properties to the icebergTable (pass-through)
And it was discussed in this [thread](https://trinodb.slack.com/archives/CJ6UC075E/p1645621806119119).

@findinpath If I understood correctly, this issue was to allow the random properties can be set to the underlying iceberg table as pass-through only?

**Comment by findinpath** [comment]
@osscm the scenario which I had in mind revolved around changing custom / random properties. 

@findepi what would be the appropriate syntax in your opinion for changing custom table properties?

**Comment by findepi** [comment]
Same as in Hive -- i.e. to be figured out; https://github.com/trinodb/trino/issues/954#issuecomment-1054078225

**Comment by Aashishthakur10** [comment]
@findepi @findinpath I was looking for a good first issue but don't have any background in Iceberg. It also looks like there are things that have to be figured out here. Is it still a good first issue that I can take up? For some background on this if you guys have any recommendations I'd be happy to go through them first!

**Comment by findinpath** [comment]
I'm removing the `good first issue` label because it is not clear yet how to expose this functionality.

**Comment by Aashishthakur10** [comment]
Makes sense, thanks!

**Comment by osscm** [comment]
@findepi is it ok to take the approach of adding `extra_properties` as you mentioned in the hive https://github.com/trinodb/trino/issues/954#issuecomment-1054078225 related issue.
This can allow users for set the pass-through properties?

I believe we are waiting for final decision on this hive's PR https://github.com/trinodb/trino/pull/9475 as well?

do we need to take more blessings to go ahead, please guide, thanks.

@Aashishthakur10, Sorry missed your comment. Actually, I was working on it, but as @findinpath mentioned it was not clear, so didnt make any progress.

we also discussed in this thread: https://trinodb.slack.com/archives/CJ6UC075E/p1645767604315919?thread_ts=1645621806.119119&cid=CJ6UC075E

**Comment by Aashishthakur10** [comment]
No worries @osscm, that makes sense. Thanks for letting me know!

**Comment by findepi** [comment]
@findinpath let's close this ticket, it's too generic.
let's have a dedicated ticket to allow changing table format version, i.e. allow upgrading tables from v1 to v2: https://github.com/trinodb/trino/issues/12138

cc @alexjo2144 @ebyhr @homar

**Comment by findinpath** [comment]
> let's have a dedicated ticket to allow changing table format version, i.e. allow upgrading tables from v1 to v2: https://github.com/trinodb/trino/issues/12138
The implementation details for #12138 would fit then the https://github.com/trinodb/trino/issues/11190#issue-1150064963 comment.

@findepi I'm fine with closing this ticket. However there seems to be an actual need for being able to set arbitrary table properties in Hive / Iceberg / Delta? via Trino. Should we continue the discussion on https://github.com/trinodb/trino/issues/954 ?

**Comment by findepi** [comment]
https://github.com/trinodb/trino/issues/954 remains desirable.
Yes, we _may_ need to have something similar for Iceberg too, but this issue didn't sound to me like "#954 but for Iceberg".

**Comment by C-h-e-r-r-y** [comment]
@findinpath 

Could you please clarify why did you close this ticket? I understand that there is a `prehook` with alter table - but as I understand it will be called every time the model executed. Looks like creating a table with properties more appropriate solution, no?

**Comment by findinpath** [comment]
@C-h-e-r-r-y  pls follow the issue https://github.com/trinodb/trino/issues/17427
This is the agreed syntax on setting/changing non-canonical Iceberg table properties.
