### ISSUE TITLE
ALTER TABLE RENAME implicitly changes table schemata

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#11281]
```
$ bin/trino-cli --catalog hive --schema default
trino:default> CREATE SCHEMA s;
CREATE SCHEMA

trino:default> CREATE TABLE s.t(a bigint);
CREATE TABLE

trino:default> ALTER TABLE s.t RENAME TO u;
RENAME TABLE

trino:default> SELECT * FROM s.u;
Query 20220302_124504_00048_5zguy failed: line 1:15: Table 'hive.s.u' does not exist
io.trino.spi.TrinoException: line 1:15: Table 'hive.s.u' does not exist

trino:default> SELECT * FROM default.u;
 a
---
(0 rows)
```

### Expected

`ALTER TABLE [catalog.]schema.table RENAME TO unqalified_name` changes table name only, but doesn't change schema.

Relates to https://github.com/trinodb/trino/issues/11202

**Comment by findepi** [comment]
cc @martint @electrum @losipiuk @hashhar @findinpath @ebyhr

**Comment by losipiuk** [comment]
> ALTER TABLE [catalog.]schema.table RENAME TO unqalified_name changes table name only, but doesn't change schema.

feels natural. Is that what others do (from what I see there is no info about that in spec (thanks @kasiafi))

**Comment by findinpath** [comment]
```
trino> use tpch.sf1;
USE
trino:sf1> ALTER TABLE hive.default.table1 RENAME to table1new;
```

In this use case the `table1new` would correspond then to `tpch.sf1.table1new`. Obviously the rename operation will fail.

When taking into account table redirections, say we are in `hive.default` context and we want to rename an Iceberg unqualified table.

```
trino:default> ALTER TABLE icebergtable RENAME to icebergtable_new;
```

The new table qualified object name would be currently `hive.default.icebergtable_new` , which again would lead to a failed rename operation.

Therefore, in the context of table renames,  the engine should rather use the source table as landmark in extrapolating the qualified object name for the target table.

**Comment by findepi** [comment]
@findinpath let's not complicate things with redirections. Redirections-related review is why i created this issue, but the issue covers general case, with redirections disabled (or "non-existing").
Let's focus on this, and this only here, as I don't believe existence of redirections feature should **impact** what decision we make for general, well-defined case.

**Comment by Riddle4045** [comment]
@findepi, can I take on this bug?

**Comment by findinpath** [comment]
@Riddle4045 there is already a PR for this issue: https://github.com/trinodb/trino/pull/11282
