### ISSUE TITLE
Persist the Trino query ID into the Iceberg snapshot

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#11292]
Same as in Spark where `spark.app.id` is persisted into the Iceberg snapshot and points to the identifier of the query performed with Spark, it would be beneficial for debug purposes to write the Trino query ID in the snapshot when performing DML operations.

### Implementation tips

Trino query ID: `io.trino.spi.connector.ConnectorSession#getQueryId`

Note that `io.trino.plugin.iceberg.TrinoHiveCatalog#PRESTO_QUERY_ID_NAME` is already used for a similar purpose in creating views within the Hive metastore.

**Comment by kbendick** [comment]
I can submit a patch for this @findinpath
