### ISSUE TITLE
When the query fails, but the task status is still returned to running

### ISSUE THREAD

**Issue by huangxiaopingRD** [trinodb/trino#11293]
When there is a problem with Presto cluster, we go to check it and find the following logs. 
![image](https://user-images.githubusercontent.com/35296098/156515637-11355b47-0c0f-4cd8-a245-bcd488ecfe2b.png)

We found that the query failed, but the URL related to the task showed that it was running until it was cleared and finally failed. As shown in the URL and picture below.
http://xxxxx:8080/v1/task/20220303_031401_04484_b5gjq.3.26
![image](https://user-images.githubusercontent.com/35296098/156515728-94ca7fe5-05c5-4f1e-8302-b84dfd612d4c.png)

And accessing task information or status through a nonexistent task ID is also in operation. The reason is that no matter what task related request, a new task ID will be created through guava LoadingCache. Why not check the validity of task ID after the first request ？

**Comment by findepi** [comment]
cc @losipiuk @arhimondr

**Comment by arhimondr** [comment]
I think it was easier to implement this way as  `TaskStatusFetcher`/ `TaskInfoFetcher` starts pulling task tasks status asynchronously even before the `TaskUpdateRequest` is issued. It should be possible to change that if needed, but might not be trivial. @huangxiaopingRD Could you please elaborate on what practical problem does this approach create?

**Comment by huangxiaopingRD** [comment]
> 

Thanks the reply. There was no actual impact, only confusion in the process of troubleshooting.
