### ISSUE TITLE
Athena Partition Projection for Trino

### ISSUE THREAD

**Issue by jimhooker2002** [trinodb/trino#11305]
Feature request (unless this already exists in Trino and I've just not found it?) not a bug.  

This feature of Athena is incredibly useful as it frees you up from having to manage partitions in a metadata store such as Glue / Hive.

https://docs.aws.amazon.com/athena/latest/ug/partition-projection.html

No need to add or delete the partitions.  This is a real boon in terms of scaling -- reduced lookups to the metadata store and reduced chance of running into problems adding too many partitions to a table in any associated metadata store.

**Comment by findepi** [comment]
It's being worked on by @aczajkowski in https://github.com/trinodb/trino/pull/10767

**Comment by jimhooker2002** [comment]
Brilliant, thank you and sorry for the dup ticket -- couldn't find it in the search.  I'll resolve now.

**Comment by findepi** [comment]
Let's keep the issue open for now. Will get closed when the PR is merged.
