### ISSUE TITLE
Error: Password hashing algorithm cannot be determined

### ISSUE THREAD

**Issue by ndrluis** [trinodb/trino#11314]
Hello, I'm trying to use the Password authentication with bcrypt and I'm receiving this error (io.trino.spi.TrinoException: Error in password file line 1: Password hashing algorithm cannot be determined).

password.db
```
test:$2a$10$Qs90g6Q0gMIflGUg4MF7..C1VuTAIVQsXTJjL62oARkMBPzeJHzfG
admin:$2a$10$pqoKtt08Po/97j87vst/cOMhsmsfUglvbQ88.go2Lb1A5mOCqmn/O
```

password.properties
```
password-authenticator.name=file
file.password-file=/etc/trino/auth/password.db
```

**Comment by losipiuk** [comment]
From what I see Trino requires `bcrypt` version 2Y (encrypted password should start with `$2y$`). But I do not really have context why that was a choice. @electrum do you happen to know?

**Comment by hashhar** [comment]
BSD bcrypt which came first used `$2a` but had bugs when dealing with non-ASCII values.

`$2y` is the fixed implementation AFAIK.

**Comment by ndrluis** [comment]
Hello, I changed to the 2y prefixed password and the problem was solved.
