### ISSUE TITLE
Fix calculation of page retained size for pages involving VariableWidthBlockEncoding blocks

### ISSUE THREAD

**Issue by linzebing** [trinodb/trino#11315]
In `VariableWidthBlockEncoding`, when reading a block, we don't allocate a new Slice but instead return a view https://github.com/trinodb/trino/blob/master/core/trino-spi/src/main/java/io/trino/spi/block/VariableWidthBlockEncoding.java#L70-L71

This is inconsistent with other encodings and makes such blocks return augmented retained sizes. Ideally, we should create a new Slice, but get rid of the extra copy here  https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/execution/buffer/PagesSerde.java#L224-L228. Also in ExchangeSourceReader we will be able to return a view too.

**Comment by findepi** [comment]
cc @sopel39

**Comment by sopel39** [comment]
That's my old PR (closed) where I wanted to fix the issue: https://github.com/prestodb/presto/pull/10634. IIRC I've never benchmarked it

**Comment by linzebing** [comment]
https://github.com/trinodb/trino/pull/11235 resolves this
