### ISSUE TITLE
More Delta Lake integration test coverage

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#11325]
Tests to be enabled

- [x] TestDeltaLakeAnalyze -- hadoop container sometimes fails during the test (e.g. testAnalyzeWithFilesModifiedAfter)
  - #11922
- [x] TestDeltaLakeAdlsConnectorSmokeTest -- removeTestData cleanup fails 
  - #11898
- [ ] Enable parallel tests in pom.xml

**Comment by findepi** [comment]
cc @jirassimok @alexjo2144

**Comment by findinpath** [comment]
_Enable parallel tests in pom.xml_ has been already handled via https://github.com/trinodb/trino/pull/12192
