### ISSUE TITLE
Document ANSI compliant trim function

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#11347]
Relates to #11236

**Comment by Ordinant** [comment]
Does the new `trim` syntax also apply to `rtrim` and `ltrim`?

**Comment by ebyhr** [comment]
@Ordinant rtrim and ltim don't have changes itself, but the new trim function can trim leading & following characters now.

**Comment by Ordinant** [comment]
So perhaps an eventual deprecation of `rtrim` and `ltrim`?

**Comment by ebyhr** [comment]
@Ordinant I don't think so. Many databases have those functions and there's no reason to delete them.

**Comment by ebyhr** [comment]
Closing as #11913
