### ISSUE TITLE
Deny CREATE TABLE with comment if the connector doesn't support storing comments

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#11348]
```sql
trino> CREATE TABLE postgresql.tpch.test (c1 int) COMMENT 'foo';
CREATE TABLE

trino> SHOW CREATE TABLE postgresql.tpch.test;
            Create Table
-------------------------------------
 CREATE TABLE postgresql.tpch.test (
    c1 integer
 )
(1 row)
```

**Comment by kyo-tom** [comment]
How do we judge whether a connector supports storing comments, now there are hive、iceberg and kudu which is support supports storing comments

**Comment by hashhar** [comment]
@kyo-tom We can start by adding a test in `BaseConnectorTest` for example that creates table with comment then asserts that show create table (+ some info schema views) preserve the comment.

For the connectors where this test fails we'd need to disable creating tables with comments.

**Comment by kyo-tom** [comment]
@hashhar that is a way we could judge whether a connector support storing comments. In my option, can we add a default function named ``setTableComment`` in ``ConnectorMetadata`` and return a exception in connector which is unsupport to store comments and to store comment in connector which is support to store comment.

**Comment by hashhar** [comment]
Yes. See some other methods like setSchemaAuthroization or createSchema for example of how existing features which aren't supported by all connectors are handled.

**Comment by kyo-tom** [comment]
@ebyhr @hashhar can I assign this issue to me

**Comment by findepi** [comment]
When we were adding table comments, we should have added a new ConnectorCapabilities. But now it's too late. We just need to fix the existing connectors to ignore table comments.

(i am assuming ignoring unsupported table comments wasn't deliberate choice; i didn't find any discussion on the topic in the old PR that added that functionality (https://github.com/prestodb/presto/pull/7722))

**Comment by kyo-tom** [comment]
@findepi So you mean we don't need to deny CREATE TABLE with comment if the connector doesn't support storing comments.

**Comment by findepi** [comment]
I think we should deny it. I am just saying this is now connector's responsibility to do so.

**Comment by kyo-tom** [comment]
Because different connectors have different methods of adding table comment when creating tables, sometimes these two operations are coupled. So it is difficult to abstract a single method to add table comment when creating tables.

can we provide a method in the ``ConnectorMetadata`` to declare whether the connector supports adding table comments for connector adding table or modifying table comments.
