### ISSUE TITLE
Problem with Slack

### ISSUE THREAD

**Issue by mardenbpasinato** [trinodb/trino#11355]
Hi,

I've just tried to access Trino Slack using the link in https://trino.io/slack.html, but it seems to invalid.
Is there any other invitation link?

**Comment by findepi** [comment]
PR: https://github.com/trinodb/trino.io/pull/281

thanks for reporting this.

**Comment by findepi** [comment]
@mardenbpasinato thanks for letting us know. Can you please try again now?
let me know if it works.

**Comment by mardenbpasinato** [comment]
@findepi It worked! Thanks a lot
