### ISSUE TITLE
Why does the resource-groups configuration in the cluster not take effect

### ISSUE THREAD

**Issue by xsk123456** [trinodb/trino#11364]
rules.json  configuration 
{
  "rootGroups": [
    {
      "name": "global",
      "softMemoryLimit": "10%",
      "hardConcurrencyLimit": 100,
      "maxQueued": 1000,
      "schedulingPolicy": "weighted",
      "jmxExport": true,
      "subGroups": [
                        {
          "name": "hive",
          "softMemoryLimit": "100%",
          "hardConcurrencyLimit": 45,
          "maxQueued": 100,
          "schedulingWeight": 1,
          "jmxExport": true,
          "subGroups": [
            {
              "name": "hh_xx2_001",
              "softMemoryLimit": "1%",
              "hardConcurrencyLimit": 5,
              "maxQueued": 1
            },
               {
              "name": "hadoop",
              "softMemoryLimit": "10%",
              "hardConcurrencyLimit": 5,
              "maxQueued": 100
            },
               {
              "name": "hh_xx2_002",
              "softMemoryLimit": "100%",
              "hardConcurrencyLimit": 5,
              "maxQueued": 100
            },
               {
              "name": "hh_xx2_003",
              "softMemoryLimit": "50%",
              "hardConcurrencyLimit": 5,
              "maxQueued": 100
            }
          ]
        }
      ]
    }
  ],
  "selectors": [ 
    {
      "group": "global.hive"
    }
  ]
}
The softmemorylimit of subgroups is not valid！
I want to be able to specified as an absolute value or as a percentage of the cluster’s memory.

**Comment by wikke** [comment]
similar problem to me.

```
  {
    "rootGroups": [
      {
        "name": "global",
        "maxQueued": 100,
        "softMemoryLimit": "100%",
        "hardConcurrencyLimit": 4,
        "schedulingPolicy": "weighted_fair",
        "subGroups": [
          {
            "name": "dam",
            "maxQueued": 100,
            "softMemoryLimit": "4GB",
            "hardConcurrencyLimit": 2,
            "schedulingWeight": 2
          },
          {
            "name": "default",
            "maxQueued": 100,
            "softMemoryLimit": "100%",
            "hardConcurrencyLimit": 8,
            "schedulingWeight": 8
          }
       ]
     }
    ],
    "selectors": [
     {
       "user": "dam",
       "group": "global.dam"
     },
     {
       "group": "global.default"
     }
    ]
  }
```

I want `dam` user with `global.dam` resource group take no more than `4GB` memory, but query exceeded, reaching 13GB!!!

![image2022-9-14_18-8-57](https://user-images.githubusercontent.com/1450849/190133519-93d59b08-8e9b-4f61-b1c4-3beeda550e71.png)

**Comment by endlesscyl** [comment]
> similar problem to me.
> 
> ```
>   {
>     "rootGroups": [
>       {
>         "name": "global",
>         "maxQueued": 100,
>         "softMemoryLimit": "100%",
>         "hardConcurrencyLimit": 4,
>         "schedulingPolicy": "weighted_fair",
>         "subGroups": [
>           {
>             "name": "dam",
>             "maxQueued": 100,
>             "softMemoryLimit": "4GB",
>             "hardConcurrencyLimit": 2,
>             "schedulingWeight": 2
>           },
>           {
>             "name": "default",
>             "maxQueued": 100,
>             "softMemoryLimit": "100%",
>             "hardConcurrencyLimit": 8,
>             "schedulingWeight": 8
>           }
>        ]
>      }
>     ],
>     "selectors": [
>      {
>        "user": "dam",
>        "group": "global.dam"
>      },
>      {
>        "group": "global.default"
>      }
>     ]
>   }
> ```
> 
> I want `dam` user with `global.dam` resource group take no more than `4GB` memory, but query exceeded, reaching 13GB!!!
> 
> ![image2022-9-14_18-8-57](https://user-images.githubusercontent.com/1450849/190133519-93d59b08-8e9b-4f61-b1c4-3beeda550e71.png)



------------------------------------------
I have the same problem, have you solved it?

**Comment by jack-o-hara** [comment]
I'm also seeing this issue where `softMemoryLimit` is not respected with the same setup as @endlesscyl

**Comment by hashhar** [comment]
Resource groups in either Trino or Presto are only admission control tools. They don't control resource usage once query starts running. The limits only apply to next queries - not already executing ones.

For already executing ones the limits are via `query_max_memory` session property for example - which you can apply to specific resource groups using the Session Property Manager.
