### ISSUE TITLE
Fix style in Kudu documentation

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#11380]
<img width="814" alt="Screen Shot 2022-03-09 at 9 58 36" src="https://user-images.githubusercontent.com/6237050/157351832-06feebb3-2490-4100-af5e-68903aa48e89.png">

- `-` becomes `・` : We can fix by using two hyphen  `--`
- `1(1,2)`: It looks little awkward

**Comment by dchvn** [comment]
For `・`, should we keep the dash `-` by using `\-`, or we change it to the hyphen `--`? 
For `1(1,2)`: I think we can use cross-reference instead.
@ebyhr  WDYT?
