### ISSUE TITLE
Set query client timeout (Like Presto's query.client.timeout)

### ISSUE THREAD

**Issue by LucasMMota** [trinodb/trino#11413]
I was trying to set a time limit to queries that have connections lost with the client.
Do we have some property like Presto's `query.client.timeout`?
(Actually, I tried to set it, but since it didn't work I'm afraid we don't have it set yet in Trino).

> https://github.com/prestodb/presto/blob/master/presto-main/etc/config.properties#L26

**Comment by hashhar** [comment]
It exists and works - default is 5 seconds. see https://github.com/trinodb/trino/blob/99ef4ec162b3b099762e4d6727ee3db641e1445c/core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java#L238

Feel free to re-open in case you run into some errors.
Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there.

**Comment by leveyja** [comment]
Just to clarify - the default is 5 minutes
```
clientTimeout = new Duration(5, TimeUnit.MINUTES);
```
The minimum is 5 seconds.
```
    @MinDuration("5s")
    @NotNull
    public Duration getClientTimeout()
```

**Comment by DeveloperZJQ** [comment]
I also encountered the same problem. Is `task.client.timeout` the config.properties configured on the worker node
