### ISSUE TITLE
Improve JDBC connector type mapping docs

### ISSUE THREAD

**Issue by tangjiangling** [trinodb/trino#11448]
Now we are trying to explain in a big table what is the type mapping relationship between Trino and different connectors, which will cause a problem for users: **is this mapping relationship for both read and write operations?**

So we should explain in the type mapping document what the type mapping relationship is for Trino read operations and what the type mapping is for Trino write operations, and I think the [MySQL type mapping document](https://trino.io/docs/current/connector/mysql.html#type-mapping) is a good example to refer to.

The following is a list of **JDBC connectors** that require improved type mapping documentation:

- [x] ClickHouse - #13578
- [x] Druid - #13776
- [x] SingleStore(MemSQL) - #13801
- [x] MySQL - #13577
- [x] MariaDB - #13656
- [x] Oracle - #13659
- [x] Phoenix4/5 - #13547
- [x] PostgresSQL - #13118
- [x] ~~Redshift~~ - #13832
- [x] SQL Server - #11564

**Edited**: Since Redshift still has no type mapping tests, no type mapping documentation will be added for now (see https://github.com/trinodb/trino/pull/13832#issuecomment-1282942980).

**Comment by tangjiangling** [comment]
And I also observed that there are some JDBC connectors that do not have type mapping tests (e.g. Druid, Redshift), which is also **needed** to be added.

**Comment by tangjiangling** [comment]
cc @ebyhr @hashhar  For the **non-JDBC connector**, I don't have much context, so I didn't list it, but I personally think it's also necessary to have type mapping documentation as well as tests.

**Comment by ebyhr** [comment]
@tangjiangling Yes, it would be nice if we can improve other connectors' documentation as well.

**Comment by mosabua** [comment]
Just for reference .. @jhlodin is working on this across all connectors. We might also have a generic section where we explain more.

**Comment by tlblessing** [comment]
Oracle PR https://github.com/trinodb/trino/pull/13659

**Comment by tangjiangling** [comment]
@tlblessing Added to the list, thanks for your contribution.

**Comment by tangjiangling** [comment]
Close this issue and thank you all for making this happen.

Since Redshift still has no type mapping tests, no type mapping documentation will be added for now (see https://github.com/trinodb/trino/pull/13832#issuecomment-1282942980).

**Comment by hashhar** [comment]
Thanks a lot @tangjiangling for kicking this off and seeing it to completion.
