### ISSUE TITLE
Release fails when building RPM

### ISSUE THREAD

**Issue by martint** [trinodb/trino#11531]
The release process is failing when building the trino-server-rpm module:

```
 [ERROR] Failed to execute goal org.basepom.maven:duplicate-finder-maven-plugin:1.5.0:check (default) on project trino-server-rpm: Found duplicate classes/resources! -> [Help 1]
```

Logs here: https://gist.github.com/martint/266cc4146d61d2511669e244bcd87160

**Comment by martint** [comment]
Possible causes:

https://github.com/trinodb/trino/pull/11387
https://github.com/trinodb/trino/pull/11495

**Comment by martint** [comment]
I was able to bypass the issue by not using the maven wrapper. So one of those two changes is almost definitely the problem. cc @hashhar @ssheikin @wendigo

**Comment by wendigo** [comment]
Does it matter if we merge https://github.com/trinodb/trino/pull/11521?

**Comment by ssheikin** [comment]
@martint what maven version do you have installed locally? According to @hashhar it has to be one below `3.8.5`.

**Comment by martint** [comment]
I'm using 3.8.4 (without the maven wrapper)

**Comment by martint** [comment]
> Does it matter if we merge https://github.com/trinodb/trino/pull/11521?

That would help, but it doesn't rule out any other issues. If its a bug in maven, it could affect other parts of the build.

**Comment by findepi** [comment]
did rpm build work in recent releases?

**Comment by nineinchnick** [comment]
I'll close this, please reopen if this is still happening.
