### ISSUE TITLE
Example connector in https

### ISSUE THREAD

**Issue by DwijadasDey** [trinodb/trino#11542]
I need a clarification about example-http connector. Does it work with https ? Although the [release note](https://trino.io/docs/current/release/release-0.54.html) does not mention about metadata uri in https.
e.g. 

```
connector.name=example-http
metadata-uri=https://domain-name/example-metadata.json

```
Thanks

**Comment by ebyhr** [comment]
It would work with https. 

```properties
connector.name=example-http
metadata-uri=https://raw.githubusercontent.com/trinodb/trino/master/plugin/trino-example-http/src/test/resources/example-data/example-metadata.json
```

```
trino> SELECT * FROM  http.example.numbers;
  text  | value
--------+-------
 ten    |    10
 eleven |    11
 twelve |    12
 one    |     1
 two    |     2
 three  |     3
(6 rows)
```

Please feel free to reopen or continue the community Slack if you want.
https://trino.io/slack.html
