### ISSUE TITLE
ClickHouse: case-sensitive table name causes an error

### ISSUE THREAD

**Issue by d9k** [trinodb/trino#11541]
The query

```
SELECT * FROM my_clickhouse_db.my_schema."MyTable";
```

causes an error:

```
Code: 60. DB::Exception: Received from js-clickhouse.infra-js-test.svc.cluster.local:9000. DB::Exception: Table my_schema.mytable doesn't exist. (UNKNOWN_TABLE)
```

Looks like query preprocess always converts table names to the lowercase.

Trino version 373.

**Comment by ebyhr** [comment]
Did you enable `case-insensitive-name-matching` configuration property?

**Comment by ebyhr** [comment]
Let me close as answered. Please feel free to reopen or ask in the community. 
https://trino.io/slack.html
