### ISSUE TITLE
Support impersonation for the all get calls (show commands ) of the Metastore API

### ISSUE THREAD

**Issue by osscm** [trinodb/trino#11577]
Currently, show operations like 

``` 
show tables;
show schemas
```
are not impersonated.

There could be use-cases where Trino clusters talk to a metastore that also allows users to set ACLs on entities like tables. And it is kind of confusing for users to see tables they don't have access to in show tables but not be able to query from them.
Metastore is considered as the source of truth for these ACLs so its kind of redundant to have Table rules on Trino side as well.
The same applies to the views as well.

Also, if users were to leverage storage-based authorization in Hive metastore server - [Storage based hive authorization](https://cwiki.apache.org/confluence/display/Hive/Storage+Based+Authorization+in+the+Metastore+Server), the current model won't work for operations like show tables (where read access to the database is checked based on the identity) for Hive plugin out of the box. 

There are the methods of  [ThriftHiveMetastore](https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java) needs to be impersonated:

```
getAllDatabases() 
getDatabase(String databaseName) 
getAllTables(String databaseName)
getTablesWithParameter(String databaseName, String parameterKey, String parameterValue): 
getAllViews(String databaseName)
getConfigValue(String name)
```

**Comment by osscm** [comment]
cc @kokosing @hashhar @vgankidi

**Comment by vgankidi** [comment]
Context here - https://trinodb.slack.com/archives/CJ6UC075E/p1647234370147859

**Comment by osscm** [comment]
taken care by this PR: https://github.com/trinodb/trino/pull/12002
