### ISSUE TITLE
Enable auto-purge default value property

### ISSUE THREAD

**Issue by sravanip09** [trinodb/trino#11575]
Currently end users are encountering the failures when they run the 'DROP table_name' command, even though the table gets dropped but the error message is leading to confusion.

trino:> drop table withacid;
Query failed: The following metastore delete operations failed: drop table withacid
io.trino.spi.TrinoException: The following metastore delete operations failed: drop table withacid

This is happening as auto_purge is not set to true, , which can be done when creating the table. Instead of having end users do it every time a table is created, Enable auto purge default value as catalog property. This adds a new config option to Trino, to set auto_purge flags's  default value to true without having to specify it in a create table statement.

**Comment by ebyhr** [comment]
> This adds a new config option to Trino

Hive connector already supports `auto_purge` table property. What connector are you going to fix? 
https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveTableProperties.java#L71

**Comment by sravanip09** [comment]
yes it is related to above PR. Updating the Hive connector.For the existing auto_purge flag, enabling the auto purge default value as a catalog property. this if not set is by default false follows default behavior. If required
provides admin to override at a centralized location by setting the default value at connector level. Eliminates the need to set it for each and every table creation. but users can still explicitly override set auto_purge itself during table creation.
worked closely with posulliv on this solution & implemented in employer specific trino, planning to open source the changes now.

**Comment by ebyhr** [comment]
Closing as #11749
