### ISSUE TITLE
Is there any way to dynamically load kafka catalog without restarting trino?

### ISSUE THREAD

**Issue by FernandoDorado** [trinodb/trino#11655]
Hello to all, 

I would be interested to see if it is possible to add topics to a kafka catalog without having to change the kafka.properties file and restart my trino counter. Is there any way to do this?

Best regards, 
Fernando

**Comment by hashhar** [comment]
Other than using the Confluent table description supplier - no. If you use file based table description supplier then it's static and cannot be reloaded at runtime.
