### ISSUE TITLE
Trino worker nodes fail to start when config.properties contain web ui specific properties 

### ISSUE THREAD

**Issue by thereisnospoon** [trinodb/trino#11689]
Hi,

I've been trying to provision a Trino cluster on top of AWS EMR. One thing I wanted to configure is to disable auth on Web UI by setting `web-ui.authentication.type` to `fixed` in `config.properties` file as per https://trino.io/docs/current/admin/properties-web-interface.html.

The problem is that when setting `web-ui.authentication.type` property for both master and  worker nodes, the worker nodes cannot start. I'm getting the following errors:
```
2022-03-28T10:52:08.031Z	ERROR	main	io.trino.server.Server	Configuration is invalid
==========

Errors:

1) Configuration property 'web-ui.authentication.type' was not used
2) Configuration property 'web-ui.user' was not used
```

The easy solution would be removing the `web-ui` properties from `config.properties` on workers, but it looks like it's not easily done on managed cloud environments like Amazon EMR or Google Dataproc.

Wouldn't it make more sense to just ignore `web-ui` properties in case a node acts as a worker?

**Comment by whutpencil** [comment]
What's your trino version?

**Comment by thereisnospoon** [comment]
I've tested this version 360

**Comment by dain** [comment]
Workers don't run the UI so these configuration properties are not allowed.
