### ISSUE TITLE
quoted_identifiers_ignore_case - Snowflake session parameters

### ISSUE THREAD

**Issue by kkovachki** [trinodb/trino#11726]
Please, can you review - quoted_identifiers_ignore_case parameter in Snowflake, this is very important to avoid mix of uppercase and lowercase in the same dataset but using trino or snowflake data source.
Also, will be very useful if we can pass any parameters which is supported on Snowflake as session based via Trino

**Comment by ebyhr** [comment]
@kkovachki We don't have Snowflake connector in this repository. Could you share the link to the plugin?

**Comment by kkovachki** [comment]
We are using Starburst with trino driver - https://docs.starburst.io/latest/connector/starburst-snowflake.html
the idea is to be able to pass special session based parameters to the Snowflake database in order to control one or other feature

**Comment by findepi** [comment]
@kkovachki if you have a support contract with Starburst, their representative might be the best person to help.,
Otherwise let's move the conversation to the `#starburst` channel on the Trino slack.
