### ISSUE TITLE
Query Logger

### ISSUE THREAD

**Issue by HiLany** [trinodb/trino#11733]
Does the community plan to implement the QueryLogger feature?

eg：Persistent query indicator information to the database...

**Comment by ebyhr** [comment]
Did you confirm https://trino.io/docs/current/develop/event-listener.html?

**Comment by HiLany** [comment]
yes, i think it is the basis for implementing the QueryLogger function.

**Comment by ebyhr** [comment]
You may want to take a look at #11645

**Comment by arhimondr** [comment]
@HiLany I'm working on a simple version here: https://github.com/trinodb/trino/pull/11645. It can log information from `QueryCompletedEvent` into a `MySQL` table. The current version is very basic. It doesn't support schema evolution and logs everything into a single table.
