### ISSUE TITLE
Implement ResultSet#getBinaryStream

### ISSUE THREAD

**Issue by yittg** [trinodb/trino#11748]
Shall we implement `ResultSet#getBinaryStream` by building a `ByteArrayInputStream` instead of throwing an exception?

WDYT @findepi?

https://github.com/trinodb/trino/blob/9c3961712ca813dbac303a239ac98921d5e27489/client/trino-jdbc/src/main/java/io/trino/jdbc/AbstractTrinoResultSet.java#L460-L464

**Comment by findepi** [comment]
Good idea.
