### ISSUE TITLE
Add `add_files` procedure  in Iceberg connector

### ISSUE THREAD

**Issue by erikerlandson** [trinodb/trino#11744]
like so:
https://github.com/RussellSpitzer/iceberg/blob/a4279fc5842046043f2afdc90f2428243958574d/spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java#L80

**Comment by osscm** [comment]
+1

**Comment by erikerlandson** [comment]
One of the use cases I had in mind for this was that the files I want to add are sitting on some s3 bucket.  So in this use case,there needs to be a way to supply `add_files` with s3 credentials, as parameters.

**Comment by alexjo2144** [comment]
Similarly to the Hive connector's `allow-register-partition-procedure` this should be disabled by default and opted in using a catalog property. The idea being that it should only be turned on if file system location based access control is in place.

**Comment by blopezpi** [comment]
Any updates on this? It will be great to have this procedure for importing a bunch of data directly avoiding any insert command.

**Comment by anandsakhare** [comment]
+1

**Comment by ebyhr** [comment]
@martint Could you review the syntax of this procedure? The procedure name in Spark is `add_files`. The detailed information is documented at https://iceberg.apache.org/docs/latest/spark-procedures/#add_files

**Comment by MichaelTiemannOSC** [comment]
Awesome works.  Can't wait to try it out in 461!
