### ISSUE TITLE
Timeout in maven-checks (17) job

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#11747]
https://github.com/trinodb/trino/runs/5780079718

**Comment by findepi** [comment]
cc @nineinchnick

**Comment by nineinchnick** [comment]
Avg duration for this job in last 30 days was 28 minutes. I'll see what could have changed to increase this recently.

https://nineinchnick.github.io/trino-cicd/reports/ci-cd/#job-duration-in-last-30-days

**Comment by nineinchnick** [comment]
It might be timing out because of retries:
```
Warning: ][warning][gc,alloc] mvn-builder-io.trino:trino-iceberg:trino-plugin:376-SNAPSHOT: Retried waiting for GCLocker too often allocating 292607 words
Terminating due to java.lang.OutOfMemoryError: Java heap space
```

**Comment by hashhar** [comment]
The OOM seems new and unexpected and only happens on JDK 17 it seems?

**Comment by MiguelWeezardo** [comment]
For ease-of-use I would recommend [JProfiler](https://www.ej-technologies.com/products/jprofiler/overview.html) or [YourKit](https://www.yourkit.com/java/profiler/features/) but if you need to stick to the command line you can use `jcmd <pid> GC.heap_dump <file-path>` or add `-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=<file-or-dir-path>` to the java call which runs Maven.
