### ISSUE TITLE
Add support to enable user defined custom plan optimizer

### ISSUE THREAD

**Issue by ariforu** [trinodb/trino#11765]
As a Trino admin I want to be able to influence Trino's logical plan. I currently want to be able to do the following things: 

- Before executing Trino's internal query optimization on customer query, we want to have an opportunity to conditionally rewrite/modify the original query based on configured/installed custom optimizer. 
- This feature should allow user to inject one or more custom optimizer user wanted to register before any other default trino optimizer. 
- User should be able to register the custom optimizer classes packaged in respective jars by placing them into trino plugins classpath. 
- There should a property flag ( like `optimizer.custom-optimizer.allow`) to enable custom optimizer support with disabled being the default behavior for backward compatibility reason. 
- Optimizer classes to be injected should be specified in a new property using comma separated fully qualified class names like `optimizer.custom-optimizer.list=io.trino.sql.planner.SampleCustomPlanOptimizer1,io.trino.sql.planner.SampleCustomPlanOptimizer2`, where `SampleCustomPlanOptimizer1` and `SampleCustomPlanOptimizer2` are the optimizer classes to be placed in the beginning of the plan optimizers chain in the order of their appearance. 

Possible Usages: 
- We can use it for purpose based row access control by transparently adding a join or filter.
- Perform optimization that are not by default provided by trino. 
- This will allow us to inject organization specific security/privacy/policy enforcement and/or query optimization instructions by modifying the original query dynamically and transparently

**Comment by findepi** [comment]
Let me close this issue as it duplicates https://github.com/trinodb/trino/issues/18 ("allow connectors to provide optimizer rules").

See also explanation https://github.com/trinodb/trino/pull/11767#issuecomment-1090083153
