### ISSUE TITLE
Memory leak in queryContexts of SqlTaskManager

### ISSUE THREAD

**Issue by JackieTien97** [trinodb/trino#11761]
It seems that there is no places to remove the entry from `queryContexts`.
<img width="1916" alt="image" src="https://user-images.githubusercontent.com/16079446/161376715-f1b4062d-f7e5-49f3-ad15-79cc44d82373.png">

Even though using `CacheBuilder.newBuilder().weakValues()` which can let gc help us to free the value memory, but the key will get no chance to be removed.

I don't whether it is right or you guys may remove it in any other places, please tell me.

**Comment by JackieTien97** [comment]
And I'm also confused that why not remove corresponding entry in `queryContexts` whille removing `tasks` Map in `removeOldTasks` method.

**Comment by findepi** [comment]
thanks for asking!

> It seems that there is no places to remove the entry from `queryContexts`.

as you noticed, it's weak-values cache

> Even though using CacheBuilder.newBuilder().weakValues() which can let gc help us to free the value memory, but the key will get no chance to be removed.

per `com.google.common.cache.CacheBuilder#weakValues`

> Entries with values that have been garbage collected may be counted in Cache.size, but will never be visible to read or write operations; such entries are cleaned up as part of the routine maintenance described in the class javadoc.

**Comment by JackieTien97** [comment]
Thanks for you response @findepi , but I'm still confused that why not remove corresponding entry in `queryContexts` whille removing `tasks` Map in `removeOldTasks` method.
