### ISSUE TITLE
Failed to enable hive cache

### ISSUE THREAD

**Issue by njalan** [trinodb/trino#11795]
Below is my configuration on trino 375 and only one node for testing:
hive.cache.enabled=true
hive.cache.location=/data/hive-cache
hive.metastore.uri=thrift://xxx:9083
hive.s3.aws-access-key=xxx
hive.s3.aws-secret-key=xxx
hive.s3.endpoint=http://xxxxx
hive.s3.path-style-access=true
hive.s3.ssl.enabled=false

Cache folder is already created locally but there is no data exists in this cache directory.
Is there anything wrong with my configuration?

**Comment by 0xc0deface** [comment]
I would also like to know, as I am struggling to get a cache working.

**Comment by raunaqmorarka** [comment]
This particular implementation of caching has been removed, please upgrade to a new release and use the new caching implementation https://trino.io/docs/current/object-storage/file-system-cache.html
