### ISSUE TITLE
Elasticserch date field with format shouldn't be ignored with custom format

### ISSUE THREAD

**Issue by ysn2233** [trinodb/trino#11823]
The elasticsearch connector ignores date fields with custom format, which I think it is unneccessary. Date format information of fields can be got easily from elasticsearch metadata. So we can decode date value according to those formats metadata.

**Comment by ysn2233** [comment]
The elasticsearch connector now pulling datetype field as a normalized doc_filed instead of its original value from JSON source. So I think we don't need to ignore date field with format.

**Comment by martint** [comment]
Related: https://github.com/trinodb/trino/pull/8896

**Comment by ysn2233** [comment]
In current Implementation, elasticsearch connector fetches timestamp field by "docvalue_fields" which will return a fixed format.
Do you think we should support mutliple trino tiemstamp data type by creating Table definition files like Kafka connector or only one timestamp format like "TIMESTAMP_TZ_MILLIS"?

**Comment by ebyhr** [comment]
Closing as duplicate of #3395
