### ISSUE TITLE
Iceberg Catalog returns getTablesWithParameter for GlueHiveMetastore is not implemented for all queries 

### ISSUE THREAD

**Issue by TFiroozian** [trinodb/trino#11831]
I'm running trino on EMR and I have added the iceberg connector for the trino.

These are the configuration under the iceberg.properties

```
connector.name=iceberg
iceberg.file-format=PARQUET
hive.metastore = glue
hive.metastore.glue.region = us-east-1
hive.metastore.glue.endpoint-url = https://glue.us-east-1.amazonaws.com
```

To reproduce the error: 

> trino-cli --catalog iceberg
trino> use iceberg_poc ;
USE
trino:iceberg_poc> show tables;
Query 20220406_174310_00013_m5ibj failed: getTablesWithParameter for GlueHiveMetastore is not implemented
trino:iceberg_poc> select * from test_table;
Query 20220406_174511_00016_m5ibj failed: Internal error ( which logs the same error in the log file )

**Versions**
- EMR 6.5 
- Trino 360

**Comment by findepi** [comment]
Real Iceberg Glue support was added in https://github.com/trinodb/trino/pull/10845, so Trino 374.
Please upgrade.

**Comment by findepi** [comment]
(If you need Trino as a kind of managed service and don't want to wait for EMR's to update to 374, you can try things out sooner with Starburst Galaxy; disclaimer: i'm from Starburst)
