### ISSUE TITLE
Create an temp table with "every minutes in a day"

### ISSUE THREAD

**Issue by dionysus1016** [trinodb/trino#11862]
I am tring to count rows by minutes and set the count to 0 if there is no rows in related mintue range, I am not sure I can achieve this without creating a temp table with all minutes value there and join the temp table with source table. e.g. 

SELECT minute_value, minute_count
      FROM (
       VALUES
        (timestamp  '2012-10-31 01:00', 0),
        (timestamp  '2012-10-31 01:01', 0),
        (timestamp  '2012-10-31 01:02', 0),
        (timestamp  '2012-10-31 01:03', 0)
        .....
        .....
    ) AS all_minute (minute_value, minute_count)

Question s are:
1.  Can I acheive "count rows by minutes and set the count to 0 if there is no rows in related mintue range" without creating the temp table and join with it?
2. If I have to create the temp table, is there a way to automaitc genreate the table without hardcode the time?

Thanks!

**Comment by findepi** [comment]
> Can I acheive "count rows by minutes and set the count to 0 if there is no rows in related mintue range" without creating the temp table and join with it?

I don't think you can

> 2\. If I have to create the temp table, is there a way to automaitc genreate the table without hardcode the time?

```sql
SELECT * FROM UNNEST(sequence(TIMESTAMP '2012-10-31', TIMESTAMP '2012-10-31 23:59:59', INTERVAL '1' MINUTE));
```

**Comment by dionysus1016** [comment]
Thanks!
