### ISSUE TITLE
Support for JDBC catalog in Iceberg connector

### ISSUE THREAD

**Issue by meetsitaram** [trinodb/trino#11883]
Add support for JDBC iceberg catalog similar to the glue catalog added in https://github.com/trinodb/trino/pull/10845. 

Creating this issue for awareness and reaching out to check if anyone else is working on it. I am planning to create a pull request for the same.

**Comment by hashhar** [comment]
See https://github.com/trinodb/trino/pull/11772

**Comment by ebyhr** [comment]
@meetsitaram There is already issue and PR (#9968 & #11772). Let me close as duplicate.
