### ISSUE TITLE
Fix Iceberg entry in release note 376

### ISSUE THREAD

**Issue by KarlManong** [trinodb/trino#11890]
<img width="648" alt="image" src="https://user-images.githubusercontent.com/2627662/162554176-e3c746b0-7831-4444-9914-386a94d558a3.png">

It should be placed in Iceberg Connector

**Comment by ebyhr** [comment]
@KarlManong Good catch. Could you send a PR?

**Comment by KarlManong** [comment]
> @KarlManong Good catch. Could you send a PR?

@ebyhr Sorry, I have submitted the cla, but it didn't affect.
