### ISSUE TITLE
Make AbstractTestHive's "assertExpectedPartitions" check all partitions are present.

### ISSUE THREAD

**Issue by damnMeddlingKid** [trinodb/trino#11904]
While working on a change to the hive connector I noticed that the method "assertExpectedPartitions" only checks if the expected partitions are in the actual partitions. But if the actual partitions contain more partitions than expected the check will still pass.  see https://github.com/trinodb/trino/blob/910501b979b3661df0c9e2628d5ac0a9e1c23931/plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java#L1282

I'm not sure if this is expected behaviour but i've made sure that the tests in TestHive do not depend on it

- If it is expected behaviour then I propose renaming this method to "assertContainsPartitions"
- If it's not expected we can make this method correct by adding an additional assertion at the end to check that the size of both expected and actual lists are the same. 

Let me know what you think and i can PR the changes.

**Comment by hashhar** [comment]
cc: @findepi

**Comment by findepi** [comment]
@damnMeddlingKid good catch!
i don't think it's desired, but let's check.
note that `AbstractTestHive` is run for many eg S3 and Azure file systems, so it requires github secrets to be fully exercised. If you make a PR from a fork, CI won't test AbstractTestHive fully.
This is why i allowed myself to take a stab at the proposed improvements: https://github.com/trinodb/trino/pull/11925
