### ISSUE TITLE
Reduce returns incorrect result for decimals

### ISSUE THREAD

**Issue by mndoping1** [trinodb/trino#11942]
Using as reduce operation to perform a sum on an array:

select REDUCE(CAST(TRANSFORM(ARRAY[3.3,decimal '2.1', decimal '3.25'],x->COALESCE(x,decimal '0')) AS ARRAY(decimal)),decimal '0',(s, x) -> s + x,s -> s);

result: 8

expected result: 8.65

Can we investigate why this isn't returning the expected result?

**Comment by martint** [comment]
That's because `decimal` in `CAST(... AS ARRAY(decimal))` is equivalent to `decimal(38, 0)`.
