### ISSUE TITLE
Improve Trino UI to display Tardigrade related information

### ISSUE THREAD

**Issue by arhimondr** [trinodb/trino#11959]
Some ideas:

* [x] Total / Completed / Failed number of tasks per stage
* [ ] Display number of retries for each "logical" task. 
* [ ] Group attempts of a single "logical" task together
* [x] Group tasks from a single stage together
* [ ] Display wasted CPU / Wall time 
  * [x] on query
  * [x]  stage 
  * [ ] "logical" task level
* [ ] Display amount of time spent waiting for input
* [ ] Display input / output throughput for 
  * [ ] a single task 
  * [ ] stage 
  * [ ] query
  * [ ] cluster
* [x] Display memory estimate / reservation / peak reservation per task

**Comment by arhimondr** [comment]
CC: @losipiuk @linzebing @joshthoward

**Comment by losipiuk** [comment]
Partly completed by https://github.com/trinodb/trino/pull/12099

**Comment by arhimondr** [comment]
The changes from https://github.com/trinodb/trino/pull/12099 seem to be good enough. Closing the issue for now. If there's anything else specific to be added a new issue can be opened.
