### ISSUE TITLE
Could not create connection to mysql8

### ISSUE THREAD

**Issue by xihuishawpy** [trinodb/trino#11971]
trino version : 376 

I want to connect mysql8 

etc/catalog/mysql.properties : 
      connector.name=mysql
      connection-url=jdbc:mysql://ip:3307
      connection-user=root
      connection-password=xxx

but , **Trino: [67108864] Query failed (#20220415_064619_00322_efs2k): Could not create connection to database server.** 
![image](https://user-images.githubusercontent.com/25117244/163534294-89641384-4eb8-427c-86ca-c21a893aabe0.png)

how to fix it ? thanks

**Comment by ebyhr** [comment]
Please make sure the connection url, credential & network between Trino nodes and MySQL. You can continue in the community Slack if you want. 

https://trino.io/slack.html > `#troubleshooting` channel

**Comment by mjh568412187** [comment]
I encountered the same error, the version of trino is 403 Trino link mysql8 is ok, trino link mysql5.7 the error is as follows

Query 20221207_084828_00007_ejswm failed: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
