### ISSUE TITLE
Security issue Arbitrary code execution detected 

### ISSUE THREAD

**Issue by sreekesh93** [trinodb/trino#11993]
Introduced through
pyyaml@5.3.1 and myst-parser@0.12.10
pillow@7.0.0

Fixed in
pyyaml@5.4
pillow@9.0.0

**Comment by findepi** [comment]
The server tarball includes a launcher.py (provided by airbase), but the script has no dependencies beyond Python standard library.

While we can upgrade dependencies in supporting libraries (here: docs), we don't need to keep this "security bug" open.
