### ISSUE TITLE
Add tests for SelectedPortWaitStrategy and move it to trino-testing

### ISSUE THREAD

**Issue by homar** [trinodb/trino#12041]
See [SelectedPortWaitStrategy](https://github.com/trinodb/trino/blob/025b22a06ba864b9c37d2e58f69c45902502956e/testing/trino-testing-containers/src/main/java/io/trino/testing/containers/wait/strategy/SelectedPortWaitStrategy.java#L35)

**Comment by ebyhr** [comment]
The class was already moved to testing module. I think this issue is duplicate of #12010 now.

**Comment by homar** [comment]
Duplicate
