### ISSUE TITLE
SPI backward compatibility check should support final removal

### ISSUE THREAD

**Issue by lukasz-stec** [trinodb/trino#12053]
Currently `io.trino.spi.TestSpiBackwardCompatibility#testSpiSingleVersionBackwardCompatibility` fails if `final` modifier was removed from a method.

**Comment by lukasz-stec** [comment]
I can but I'm not sure how to fix it properly without big changes (given that currently, the method signatures are put into String).
A quick fix is to ignore the `final` keyword altogether, but that makes **adding** `final` keyword pass, which may be not a backward compatible change.
Is that acceptable?

**Comment by findepi** [comment]
or maybe we depart from comparing Strings for SPI compatibility test.
cc @kokosing and @trinodb/maintainers for ideas

**Comment by kokosing** [comment]
How about as simple as https://github.com/trinodb/trino/pull/12062?

**Comment by lukasz-stec** [comment]
> How about as simple as #12062?

this allows adding `final` on a method or class, which may break backward compatibility.
I do like the simplicity though.

**Comment by sopel39** [comment]
@kokosing should we close it now that you have merged https://github.com/trinodb/trino/pull/12062?
