### ISSUE TITLE
TestHiveTransactionalTable > testOrcColumnTypeChange(0: true) is flaky

### ISSUE THREAD

**Issue by arhimondr** [trinodb/trino#12063]
https://github.com/trinodb/trino/pull/12037/checks?check_run_id=6103132944

**Comment by findepi** [comment]
> https://github.com/trinodb/trino/pull/12037/checks?check_run_id=6103132944

Thanks for the link.

However, when i tried to browse the logs to get the full stacktrace, i got this

<img width="844" alt="image" src="https://user-images.githubusercontent.com/144328/194557498-92757305-f9f4-41e1-b1d2-14e893fcb87b.png">


so we have the message only

```
[onTrino] Expected row count to be <2>, but was <4>; rows=[[111, Katy, 57, CA], [222, Joe, 72, WA], [111, Katy, 57, CA], [222, Joe, 72, WA]]
```

as such, it looks like potentially same as https://github.com/trinodb/trino/issues/14519
