### ISSUE TITLE
Trino 377 deprecated ldap.ssl-trust-certificate

### ISSUE THREAD

**Issue by brokenjacobs** [trinodb/trino#12087]
I get a deprecation warning and failure to start about a ldap property:
`ldap.ssl-trust-certificate`
```
1) Error: Defunct property 'ldap.ssl-trust-certificate' (class [class LdapConfig]) cannot be configured.

2) Error: Configuration property 'ldap.ssl-trust-certificate' was not used

2 errors

======================
Full classname legend:
======================
LdapConfig: "io.trino.plugin.password.ldap.LdapConfig"
========================
End of classname legend:
========================
```
This was on an upgrade from 0.374 -> 0.377. So somewhere in the past few updates this property has been deprecated? I didn't see anything in the release notes.

**Comment by brokenjacobs** [comment]
I'm guessing it was this pr?
https://github.com/trinodb/trino/pull/11070

It changes it do a defunctconfig.

**Comment by ebyhr** [comment]
> I didn't see anything in the release notes.

Release note version 376 has the entry. https://trino.io/docs/current/release/release-376.html#security

> I'm guessing it was this pr? https://github.com/trinodb/trino/pull/11070

Correct.

**Comment by brokenjacobs** [comment]
Adding support for two way ldap auth is in the release notes. This config parameter is for using a private CA. Adding mTLS is not the same as deprecation of support for private CA’s. Also at a minimum this is a doc bug, as the property is still in the documentation.

**Comment by brokenjacobs** [comment]
@ebyhr This is still a bug and should not have been closed.

**Comment by electrum** [comment]
The documentation has been updated for the new property `ldap.ssl.truststore.path`. I believe the rename of this property was unintentional, which is why the documentation and release notes did not reflect it. Our apologies.
