### ISSUE TITLE
Hot loading data sources

### ISSUE THREAD

**Issue by xhsky** [trinodb/trino#12132]
Are there plans for a data source hot reload feature?

**Comment by ebyhr** [comment]
@xhsky Could you share more details about your requirement?

**Comment by xhsky** [comment]
Now if  add or modify the configuration of a data source,  need to restart the entire trino cluster. 
Is there a way to do this without rebooting

**Comment by ebyhr** [comment]
@xhsky It's not possible at this time. Let's continue in #2110
