### ISSUE TITLE
Glue tests are failing on master

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#12147]
Below tests are consistently failing in master
* TestHiveGlueMetastore.testDisallowQueryingOfIcebergTables
* TestHiveGlueMetastore.testHideDeltaLakeTables
* TestDeltaLakeGlueMetastore.testHideNonDeltaLakeTable

Relates to #12130

**Comment by ebyhr** [comment]
cc: @erichwang @dain @findepi

**Comment by erichwang** [comment]
Does anyone know why these tests didn't run for the https://github.com/trinodb/trino/pull/12130 PR?

**Comment by ebyhr** [comment]
@erichwang PR from forked branch doesn't trigger the tests due to missing secrets.
* https://github.com/trinodb/trino/blob/master/.github/workflows/ci.yml#L207-L215
* https://github.com/trinodb/trino/blob/master/.github/workflows/ci.yml#L488-L496

Maintainers should send another PR within a `trinodb` repo like #12126 (actual PR) & #12141 (test PR)
