### ISSUE TITLE
Support time travel in Delta Lake connector

### ISSUE THREAD

**Issue by ericlgoodman** [trinodb/trino#12156]
Hello,

Opening this issue to discuss plans for adding time travel support for Delta Lake. This would ideally support timestamps:

```sql
SELECT count(*) FROM my_table FOR SYSTEM_TIME AS OF "2019-01-01"
```

or with versions

```sql
SELECT count(*) FROM my_table FOR SYSTEM_VERSION AS OF 5238
```

**Comment by tooptoop4** [comment]
@ericlgoodman this is not fixed?
