### ISSUE TITLE
Make StorageDescriptor optional for Managed Delta Lake tables

### ISSUE THREAD

**Issue by alexjo2144** [trinodb/trino#12180]
The StorageDescriport is used to get the path to all Delta Lake tables, via a serde parameter https://github.com/trinodb/trino/blob/master/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/HiveMetastoreBackedDeltaLakeMetastore.java#L189

This should be required for External tables, but for Managed tables the location can be derived from the Schema's location similarly to https://github.com/trinodb/trino/blob/master/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java#L592

**Comment by findepi** [comment]
@alexjo2144 
What's the use-case scenario for this, i.e. under what circumstances a user would benefit from such change?

cc @homar @erichwang

**Comment by alexjo2144** [comment]
This was related to Eric's work on https://github.com/trinodb/trino/pull/12130

I remember him mentioning a case where the storage descriptor wasn't set on a Glue table, maybe a table created by Flink? Regardless this just seemed like a resilience improvement, since for managed tables we have all the information we need to derive the location.

**Comment by findepi** [comment]
@alexjo2144 while we can add support for theoretically possible, or manually crafted, situations, it's not the best way of spending our complexity budget. I would want us to focus on real-life and common scenarios. If this change is beneficial for a real-life scenario, we should identify it and code-level document (or test).

> maybe a table created by Flink?

it may be. it would be a good real-life scenario.

**Comment by homar** [comment]
@findepi @alexjo2144 so what is the next step ?
