### ISSUE TITLE
Unexpected result using NOT IN clause while subset contains null

### ISSUE THREAD

**Issue by fancy27** [trinodb/trino#12186]
query:

```sql
select count(1)
from (
  select 1 as id
  union all
  select 2 as id
) t
where id not in (
  select null as id
)
```

expect: 2
actual: 0

**Comment by findepi** [comment]
This is correct. The `IN` semantics is based on equality.
`1 = null` is `null` in SQL (read "null" as "unknown", that's what it stands for in SQL "theory")
`NOT (1 = null)` is `NOT (null)`, is `null`.

and `WHERE null` filters out rows, i.e. `WHERE` allows only rows for which the condition evaluates to `true` (and not `false`, and not `null`).

**Comment by fancy27** [comment]
@findepi I am puzzled by the following queries
```sql
select count(1)
from (
  select 1 as id
  union all
  select 2 as id
) t
where id in (
  select null as id
  union all
  select 1 as id
)
```
returns 1

However,
```sql
select count(1)
from (
  select 1 as id
  union all
  select 2 as id
) t
where id not in (
  select null as id
  union all
  select 1 as id
)
```
returns 0

Could you analyze it?

**Comment by findepi** [comment]
This is correct.
