### ISSUE TITLE
JDBC Connection to a large table should have a fetch cap ?

### ISSUE THREAD

**Issue by dohr-michael** [trinodb/trino#12254]
Hello,

We are working currently with Trino as database on top of our Datalake.
But we have a a real problem with performance when we are trying to fetch a large table we notice a limitation with the fetch of data.
It's looks like we have a limitation to 16 MB / s.

My Test Case : 
```java
public class Main {
    public static void main(String[] args) {
        long start = System.currentTimeMillis();
        final Properties props = new Properties();
        props.setProperty("user", args[0]);
        props.setProperty("password", args[1]);
        final String trinoUrl = "jdbc:trino://xxx.xxx.xxx:443/xxx?SSL=true";

        try (
                final Connection con = DriverManager.getConnection(trinoUrl, props);
                final Statement stmt = con.createStatement();
        ) {
            final ResultSet rs = stmt.executeQuery("SELECT * FROM contrat_metrics.prime_contrats_history LIMIT 10000000");

            int counter = 0;
            long batchStart = System.currentTimeMillis();
            while (rs.next()) {
                counter++;
                if (counter % 100000 == 0) {
                    System.out.println(" - current count " + counter + " and took " + (System.currentTimeMillis() - batchStart) + "ms");
                    batchStart = System.currentTimeMillis();
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        System.out.println("Results extracted in " + (System.currentTimeMillis() - start));
        System.exit(0);
    }
}
```
Result : 
```
 - current count 100000 and took 1186ms
...
 - current count 10000000 and took 743ms
Results extracted in 86826
```

Data Source : 
- Hive from parquet file in local MinIO (S3)

Server Configuration : 
- Version 379
- Run in Kubernetes
- 6 Worker, 1 Master, 
- Query Max Memory : 36GB
- change of exchange.max-response-size don't change the result of the test.

Do you have any idea to ingress this limitation ?

I can send you the result from the query plan.

Regards,

Michael

**Comment by findepi** [comment]
The Trino protocol is JSON-based, and so is highly inefficient for transporting large amounts of data.

https://github.com/trinodb/trino/issues/3042 is the issue tracking the improvement (no-one is currently working on this) and will give you some further pointers to wiki and slack.
