### ISSUE TITLE
Remove -XX:+UnlockDiagnosticVMOptions and -XX:+UseAESCTRIntrinsics from jvm.config.

### ISSUE THREAD

**Issue by radek-starburst** [trinodb/trino#12253]
We enabled `-XX:+UnlockDiagnosticVMOptions` and `-XX:+UseAESCTRIntrinsics` to use a backport introduced by https://github.com/openjdk/jdk11u-dev/pull/410. 
This PR backports a significant performance improvment of `AES CTR/GCM` for `ARM64` architecture. 
After upgrading Java version to at least 18 we should remove these options. 
For more reference see https://github.com/trinodb/trino/pull/12251/commits/5d6bbc2190bce02502ec6bf0cfbaa8626a8b2f7b

**Comment by sopel39** [comment]
> After upgrading Java version to at least 17 we should remove these options.

Why java 17? I think it's on by default in 18. Also, it might happen that they just enable it by default in 11 (in July). Then we can remove this options too

**Comment by Pluies** [comment]
@radek-starburst I see `-XX:+UseAESCTRIntrinsics` was removed in https://github.com/trinodb/trino/pull/19553/commits/ac5b182a06dc09df446123409bc6344148936cab , this issue can probably be closed?

**Comment by radek-starburst** [comment]
Yes
