### ISSUE TITLE
Add checks for target table.view,mv during view/table rename

### ISSUE THREAD

**Issue by lukasz-stec** [trinodb/trino#12337]
Add checks, similar to in RenameMaterializedViewTask, that the target table or view or materialized view does not exist in the RenameTableTask and RenameViewTask

**Comment by findepi** [comment]
cc @findinpath @ilfrin

**Comment by zhaoyim** [comment]
I want to work on this issue, assign to me for first issue to fix. Thanks!

**Comment by findinpath** [comment]
Feel free to reach out for support and do sign the CLA if this is your first PR.

**Comment by zhaoyim** [comment]
Thanks! I already sign the CLA, any questions I will ask in the slack. Thanks again!

**Comment by zhaoyim** [comment]
already submit a PR: Add checks for rename table and view #12402

**Comment by zhaoyim** [comment]
@findinpath Could help review? Thanks!
