### ISSUE TITLE
Support Kerberos authentication for Kudu Connector

### ISSUE THREAD

**Issue by dukeshiny** [trinodb/trino#1237]
When I use presto to connect kudu tables,I can show tables and describe kudu table's structure,But I can not select data from kudu table,there is error as following:
Query 20190802_074604_00006_2g8pc failed: org.apache.kudu.client.NonRecoverableException: Couldn't find a valid master in (192.168.1.1:7051,192.168.1.2:7051,192.168.1.3:7051). Exceptions received: [org.apache.kudu.client.NonRecoverableException: server requires authentication, but client does not have Kerberos credentials (tgt). Authentication tokens were not used because no token is available, org.apache.kudu.client.NonRecoverableException: server requires authentication, but client does not have Kerberos credentials (tgt). Authentication tokens were not used because no token is available, org.apache.kudu.client.NonRecoverableException: server requires authentication, but client does not have Kerberos credentials (tgt). Authentication tokens were not used because no token is available]

Anyone has occured this problem?

**Comment by kokosing** [comment]
It is not yet supported.

**Comment by electrum** [comment]
The Kudu connector does not support Kerberos authentication. Someone will need to add it.

**Comment by dukeshiny** [comment]
Thank you .I see .But now I can't use presto to connect kudu without Kerberos authentication yet.Here is the error:
![image](https://user-images.githubusercontent.com/21135052/62470624-6c05aa00-b7cd-11e9-9838-9d8dbb4f5fb3.png)
How can I solve this problem?

**Comment by dukeshiny** [comment]
> The Kudu connector does not support Kerberos authentication. Someone will need to add it.

Could you help me look at it?Here is the kudu.properties:
connector.name=kudu
kudu.client.master-addresses=192.168.1.1:7051,192.168.1.2:7051,192.168.1.3:7051
[root@cdh215 catalog]#

**Comment by liyubin117** [comment]
I have resolved the problem, please see at https://github.com/prestosql/presto/pull/3549
