### ISSUE TITLE
Allow row filter to use an inaccessible column

### ISSUE THREAD

**Issue by weiatwork** [trinodb/trino#12390]
For columns that are referenced in row filters or column masks, even if they are not defined as "selectable" by the policy, there should be valid use cases where the columns are only involved in the predicate condition evaluation.

Here are two respective file-based policy examples. They both fail with Access Denied error for the query below currently. But if we add something like `checkCanUseColumnsImplicitly`, they can be supported. @martint @kokosing 

Query
```
select orderkey from orders
```

Row filter
```
{
    "tables": [
        {
            "catalog": "hive",
            "schema": "tpch",
            "table": "orders",
            "privileges": ["SELECT"],
            "filter": "orderstatus = 'F'",
            "columns": [
                {
                    "name": "orderstatus",
                    "allow": false
                }
            ]
        }
    ]
}
```

Column mask
```
{
    "tables": [
        {
            "catalog": "hive",
            "schema": "tpch",
            "table": "orders",
            "privileges": ["SELECT"],
            "columns": [
                {
                    "name": "orderkey",
                    "mask": "if (orderstatus = 'F', orderkey)"
                },
                {
                    "name": "orderstatus",
                    "allow": false
                }
            ]
        }
    ]
}
```

**Comment by findepi** [comment]
cc @kokosing @dain @lukasz-walkiewicz

**Comment by weiatwork** [comment]
Thanks @kokosing for pointing that out. I assume `mask_environment` and `filter_environment` are specific to the file-based access control. For something like Apache Ranger to achieve the same, they might have to follow the similar implementation? It may be more flexible if we have the concept that "allows inaccessible columns to be used in row filters or column masks only" without requiring a superuser as a delegate

**Comment by martint** [comment]
Column masks and row filters behave like dynamic views that get evaluated using the permissions of a user provided by the mask or filter definition. That should be sufficient to achieve what you're describing, as @kokosing explained above. 

It doesn't make a lot of sense to allow row filters and masks to bypass security settings. It introduces a security hole where someone who can define a row filter or mask for a table can bypass security and extract information from another protected table.

E.g., 

Let's say you have table `t` and `secret`. A user has access to read from `t` and to add column masks and filters for it. However, they don't have access to read from `secret`. If the user wanted to check whether `secret` contains a row with `id = 1`, all they'd need to do is define a row filter for `t` that looks like:

```
EXISTS (SELECT * FROM secret WHERE id = 1)
```

Using masks, it would be even more trivial to extract sensitive information, by defining a mask for a column in `t` using a scalar subquery like this:

```
(SELECT secret_value FROM secret WHERE id = 1)
```

**Comment by weiatwork** [comment]
Thanks @kokosing and @martint. I agree this can be an issue if the expression references columns in a different table, although allowing implicit column access in a single table use case might be fine (please correct me if wrong).
