### ISSUE TITLE
Error running command: No ObjectCodec defined for the generator, can only serialize simple wrapper types (type passed java.util.HashMap)

### ISSUE THREAD

**Issue by StalkerOne** [trinodb/trino#12427]
When i use prometheus connector to query time series data, it occur some errors:

--------------------------------- output -----------------------------
trino:default> select labels['cluster'] as cluster, labels['env'] as environment from container_memory_cache where labels['env'] = 'pro' limit 2;

Query 20220517_045907_00085_iptcs, FAILED, 1 node
Splits: 86 total, 0 done (0.00%)
5.41 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20220517_045907_00085_iptcs failed: Key not present in map: env

trino:default> select labels['cluster'] as cluster, labels['env'] as environment from container_memory_cache where labels['env'] = 'pro' limit 2;

Query 20220517_045915_00086_iptcs, FAILED, 1 node
Splits: 86 total, 0 done (0.00%)
6.91 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20220517_045915_00086_iptcs failed: Key not present in map: env

trino:default> select labels['cluster'] as cluster, labels['env'] as environment from container_memory_cache where labels['env'] = 'pro' limit 2;
    cluster     | environment 
----------------+-------------
 zto-pro-bd-cpu | pro         
 zto-pro-bd-cpu | pro         
(2 rows)

Query 20220517_045923_00087_iptcs, FINISHED, 1 node
Splits: 86 total, 66 done (76.74%)
7.49 [12.1K rows, 34.3MB] [1.62K rows/s, 4.58MB/s]

-------------------------------------------------------------

The same SQL query Prometheus can check the results and report errors in a moment. I don't understance the sql explain planning

**Comment by ebyhr** [comment]
Try `element_at ` function. https://trino.io/docs/current/functions/map.html?highlight=element_at
