### ISSUE TITLE
Iceberg's create table to support `sort_order` property

### ISSUE THREAD

**Issue by osscm** [trinodb/trino#12447]
Iceberg spec supports `sort_order` (https://iceberg.apache.org/spec/#table-metadata-fields) and Spark is supporting it while creating, altering, and writing data.
This issue is to support `sort_order` as a property while creating an Iceberg table like `sorted_by` in the hive tables. (https://trino.io/docs/current/connector/hive.html#table-properties)

CREATE TABLE syntax 

```
CREATE TABLE iceberg.testdb.customer_orders (
    order_id BIINT,
    order_date DATE,
    account_number BIGINT,
    customer VARCHAR,
    state VARCHAR,
    country VARCHAR)
WITH (partitioning = ARRAY['month(order_date)', 'bucket(account_number, 10)', 'country'],
	  sort_order = ARRAY['customer','country DESC'])
	  
CREATE TABLE iceberg.testdb.customer_orders (
    order_id BIINT,
    order_date DATE,
    account_number BIGINT,
    customer VARCHAR,
    state VARCHAR,
    country VARCHAR)
WITH (partitioning = ARRAY['month(order_date)', 'bucket(account_number, 10)', 'country'],
	  sort_order = ARRAY['customer DESC','country ASC'])
```

**Comment by findepi** [comment]
Defining this as a table property makes sense.
The important part is syntax for `sort_order` elements.
It should be field/transform (like in `partitioning`) followed by optional DESC/ASC and optional NULLS FIRST/LAST.

There is a small caveat around NaN ordering. I think the Iceberg spec has a problem around that.
I posted https://github.com/apache/iceberg/pull/2891 but it was never rejected nor accepted, so it's unclear whether the spec is considered correct or not.

**Comment by findepi** [comment]
Also, should this be `sort_order`, `file_sort_order` (to emphasize it's sorting local to a file), or `sorted_by` (as in Hive) ?

cc @electrum @phd3 @alexjo2144 @trinodb/maintainers

**Comment by osscm** [comment]
thanks, @findepi 
I didn't find that the transform function being used in the given examples: https://iceberg.apache.org/docs/latest/spark-ddl/#alter-table--write-ordered-by 
thought in the [SortOrderParser](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/SortOrderParser.java#L160-L180): it's parsing the transform from the metadata JSON.

>Also, should this be sort_order, file_sort_order (to emphasize it's sorting local to a file), or sorted_by (as in Hive)?

just a thought `sorted_by` looks good for Trino consistency but `sort_order` looks good to keep it similar to how Iceberg refers to it internally.

**Comment by osscm** [comment]
cc @RussellSpitzer

**Comment by RussellSpitzer** [comment]
Currently in Spark we don't have any way to specify transform in our API and we just use WRITE ... ORDERED/SORTED BY. I don't think it's critical to allow passing a sort transform at the moment

**Comment by findepi** [comment]
> I didn't find that the transform function being used in the given examples: https://iceberg.apache.org/docs/latest/spark-ddl/#alter-table--write-ordered-by

Iceberg API allows to specify expression-based sort order. See eg test code
https://github.com/apache/iceberg/blob/78cc15aedbfd2d2c2fb499737952252ea200d772/core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java#L884-L887


> Currently in Spark we don't have any way to specify transform in our API and we just use WRITE ... ORDERED/SORTED BY.

@RussellSpitzer seems like the Iceberg Spark `ORDERED BY` also allows specifying expressions/transforms

https://github.com/apache/iceberg/blob/9691737c8aded99eb4650570d3d8a44181c8bbc6/spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRequiredDistributionAndOrdering.java#L120

**Comment by alexjo2144** [comment]
If the sort property is set does data have to be sorted when being inserted, or is it optional?

**Comment by RussellSpitzer** [comment]
@findepi That's cool, I didn't know that would work at all

@alexjo2144 No, we currently do not require this, we even have an extra set of parameters allowing the user to decide what Spark algorithm to use for sorting (or not use). For example, a user can choose to not sort data in a particular write.

**Comment by osscm** [comment]
@findepi or @alexjo2144 can you please assign this to me. thanks

**Comment by findepi** [comment]
Looks reasonable.

Note that `<column>` should be either column name without quotes, or with quotes (delimited).
see https://github.com/trinodb/trino/pull/12227

**Comment by osscm** [comment]
@findepi thanks

I had got working code/test-cases for create table with sorted_by in local, but didn't know about https://github.com/trinodb/trino/pull/12227 
As this is still under review and not sure when will get in, do you want me to still consider the quotes requirement for the `sorted_by` PR as well or we can add the quotes requirement changes after this?

**Comment by ebyhr** [comment]
Closing as #14891
