### ISSUE TITLE
Iceberg reports unknown nulls_fraction for added column

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#12461]
```sql
CREATE TABLE t(one bigint);
INSERT INTO t VALUES 42;
ALTER TABLE t ADD COLUMN two bigint;
INSERT INTO t VALUES (42, 100);
SHOW STATS FOR t;
```

```
 column_name | data_size | distinct_values_count | nulls_fraction | row_count | low_value | high_value
-------------+-----------+-----------------------+----------------+-----------+-----------+------------
 one         |      NULL |                  NULL |            0.0 |      NULL | 42        | 42
 two         |      NULL |                  NULL |           NULL |      NULL | NULL      | NULL
 NULL        |      NULL |                  NULL |           NULL |       2.0 | NULL      | NULL
```

**Comment by findepi** [comment]
Seems that `TableStatisticsMaker` doesn't differentiate between "column not in a file" and "no file-level stats provided for given column".

Not sure about importance though. Newly added columns are less frequently used as join conditions.

cc @alexjo2144

**Comment by r9liucc** [comment]
@alexjo2144 Hi ! Could we just use [Table Metadata](https://iceberg.apache.org/spec/#table-metadata) to determine the current schema? So all statistics could be base on the current schema.

**Comment by alexjo2144** [comment]
The problem is that these two cases look exactly the same, from a stats perspective:

```
CREATE TABLE table_one (a int, b int, c int);
ALTER TABLE table_one SET TBLPROPERTIES (write.metadata.metrics.column.c='none');
INSERT INTO table_one VALUES (1, 2, 3);
ALTER TABLE table_one SET TBLPROPERTIES (write.metadata.metrics.column.c='full');
INSERT INTO table_one VALUES (4, 5, 6);
```

and

```
CREATE TABLE table_two (a int, b int);
INSERT INTO table_two VALUES (1, 2);
ALTER TABLE table_two ADD COLUMN c INT;
INSERT INTO table_two VALUES (4, 5, 6);
```
Column `c` is in the current schema and is missing from the first data-file. Problem is, in one case c was expected to exist but is disabled, and in the other case it was not in the table schema at the time. Without opening the data-file itself, there isn't a way to tell the two apart.

**Comment by r9liucc** [comment]
@alexjo2144 Thanks for the answer. I will take a look at the table properties.
