### ISSUE TITLE
Accumulo connector allows creating views in a schema where it doesn't exist

### ISSUE THREAD

**Issue by Emor-nj** [trinodb/trino#12475]
The similar issue with [https://github.com/trinodb/trino/issues/10857](url)  and [https://github.com/trinodb/trino/issues/11110]()

> trino> CREATE VIEW accumulo .schema_not_found.test AS SELECT 1 AS c1;
CREATE VIEW

**Comment by ebyhr** [comment]
We can fix by adding the below code to `createView` & `createOrReplaceView` in `AccumuloClient`
```java
        if (!tableManager.namespaceExists(viewName.getSchemaName())) {
            throw new SchemaNotFoundException(viewName.getSchemaName());
        }
```
