### ISSUE TITLE
Presize new page to exeact expect size in MultiChannelGroupByHash#startNewPage

### ISSUE THREAD

**Issue by lukasz-stec** [trinodb/trino#12484]
Follow up after https://github.com/trinodb/trino/pull/12336

For fixed width type you can assume here that there will be OUTPUT_PAGE_SIZE positions (type check on instaceof FixedWidthType.
For variable length type, (instanceof VariableWidthType) you can assume OUTPUT_PAGE_SIZE positions, but can also assume some skew via io.trino.spi.block.BlockUtil#calculateBlockResetBytes. You can then use io.trino.spi.type.Type#createBlockBuilder(io.trino.spi.block.BlockBuilderStatus, int, int) to construct builder of right size.

This should save memory compared to existing code. I wouldn't be surprised to see aggregation mem usage drop by 10-20%

I think we can extend io.trino.spi.PageBuilder#reset to accept expectedEntries.

https://github.com/trinodb/trino/pull/12072/files#r861792201

**Comment by lukasz-stec** [comment]
cc @sopel39 @skrzypo987

**Comment by skrzypo987** [comment]
Isn't this a one-liner after https://github.com/trinodb/trino/pull/12336 lands?

**Comment by lukasz-stec** [comment]
> Isn't this a one-liner after #12336 lands?

@skrzypo987 No, the issue is that `VariableWIdthBlockBuilder` needs to be reset/recreated with a similar (currently 25% higher) `expectedBytes`. So we either do something as I did in  https://github.com/trinodb/trino/pull/12512 or we need to expose 

```
VariableWidthBlockBuilder.getCurrentSizeInBytes()
{
  return getOffset(positions) - getOffset(0)
}
```

**Comment by skrzypo987** [comment]
ok, I got you.
Still this does not seem too complicated.
