### ISSUE TITLE
Show Iceberg location and format_version in `SHOW CREATE MATERIALIZED VIEW`

### ISSUE THREAD

**Issue by polaris6** [trinodb/trino#12504]
Currently, we can set four properties when we use `CREATE MATERIALIZED VIEW` in Iceberg connector, but `SHOW CREATE MATERIALIZED VIEW` only shows `format` and `partitioning`, I will submit a PR to add `format_version` and `location`.

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/29967142/169678027-c8f2a68b-816a-4943-908d-4fe8a39b931e.png">

**Comment by polaris6** [comment]
cc: @findepi @alexjo2144 
Do you think it is necessary to add the format_version and location property in `SHOW CREATE MATERIALIZED VIEW`?

**Comment by alexjo2144** [comment]
Yep, that makes sense to me

**Comment by alexjo2144** [comment]
Actually, @raunaqmorarka should you be able to set the location for a MV?

**Comment by raunaqmorarka** [comment]
> should you be able to set the location for a MV?

yes, that seems reasonable
