### ISSUE TITLE
Cannot drop Iceberg materialized view after storage table externally dropped

### ISSUE THREAD

**Issue by polaris6** [trinodb/trino#12503]
I created an Iceberg table named `table_1`(with hive metastore), then I created materialized view based on this table. At this point `SHOW TABLES` will show three tables:
```
 materialized_view_1                 
 st_1fe045821b714dbe92b3ee9b4ca16f2a 
 table_1
```
I dropped the storage table first and then dropped the materialized view, the exception is thrown that the storage table not found. 

Although the correct operation is not to drop the storage table first, but if the storage table is dropped, I think that dropping the materialized view should not throw an exception(now I can't drop this materialized view through Trino, it becomes dirty data).

Full screenshot:
Trino client:
![image](https://user-images.githubusercontent.com/29967142/169676193-abaee60b-7de4-4117-b455-02e2b23fe58b.png)

**Comment by findepi** [comment]
cc @lukasz-stec @sopel39

**Comment by zhaoyim** [comment]
Could I assign this issue to me ? and try to fix? Thanks!

**Comment by polaris6** [comment]
done @zhaoyim 
You can discuss with @lukasz-stec @sopel39 first, I'm not sure if users should be allowed to drop storage table.

**Comment by polaris6** [comment]
@lukasz-stec 
> I think it should not even be in the result of show tables (maybe that is the fix here)

I also considered this solution, but I saw that @findepi has replied before, in addition to `show tables` through hive client also shows the storage table.
https://github.com/trinodb/trino/pull/10745#discussion_r793589518

**Comment by raunaqmorarka** [comment]
We don't have a good way to prevent the dropping of storage table right now ("st_" prefix in the name is too broad and listing MVs to see if current table is a storage table would be too brute force). We could start adding some unique property to the storage table as an identifier and detect that during the DROP to stop it from being dropped directly.
Always hiding the storage tables in SHOW TABLES wouldn't be good, you might want to be aware about existence of storage tables as they take up resources in HMS and filesystem somewhere. Also, any other system which works with HMS would show these tables.
Setting up access controls is a less intrusive way of hiding the storage tables. Currently it would probably require matching for "st_" table name pattern, I'm not sure if this is ideal. We could make it easier to setup access controls by making the schema under which the storage table is created a catalog config, then access controls to deny direct access can be setup on that schema.

**Comment by zhaoyim** [comment]
@polaris6  Thanks! I will read the comments and code first.

**Comment by zhaoyim** [comment]
> 

@raunaqmorarka Will you mean leverage the Catalog-level access control files to reject the drop the storage table? In this way seems we did NOT need do any code changes,  maybe need update the DOC?

**Comment by findepi** [comment]
> Setting up access controls is a less intrusive way of hiding the storage tables. Currently it would probably require matching for "st_" table name pattern, I'm not sure if this is ideal.

Not an option. First of all, naming pattern is just a convention, not a reserved prefix.

Also, it doesn't solve the actual problem. the storage table can be dropped using other application or direct metastore API (eg Glue's).

**Comment by findepi** [comment]
> I think it should not even be in the result of `show tables` 

I don't think it's obvious, but @lukasz-stec  we can have separate issue about this

> (maybe that is the fix here)

it's not, per above: the storage table can be dropped using other application or direct metastore API (eg Glue's).

**Comment by lukasz-stec** [comment]
> I don't think it's obvious, but @lukasz-stec we can have separate issue about this

@findepi Not that I'm a big side on this discussion but I think it would be good to clear this up so I created https://github.com/trinodb/trino/issues/12559 as you suggested

**Comment by raunaqmorarka** [comment]
@findepi Given we don't have a perfect way of preventing drop of the storage table, would it make sense to move forward with fixing the issue here by simply logging the missing storage table and allowing the user to drop the MV instead of failing the query ?
Also, maybe as a separate issue, would it make sense to allow the schema of the storage table to be a configurable MV property ? Using the "st_%" table name pattern is definitely too broad. This would help in at least making it easier to setup rules to deny direct access to storage table through Ranger or other means. There may still be loopholes from other systems, but admins can setup their environment to block direct access through other means (e.g. direct access to metastore or access through engines can also be curtailed).

**Comment by findepi** [comment]
> Given we don't have a perfect way of preventing drop of the storage table, would it make sense to move forward with fixing the issue here by simply logging the missing storage table and allowing the user to drop the MV instead of failing the query ?

That's what we should do, yes.

> Also, maybe as a separate issue, would it make sense to allow the schema of the storage table to be a configurable MV property ? 

Yes, this should be possible. This would allow to easily segregate storage tables from other, more directly useful stuff user wants to interact with.

@raunaqmorarka please file an issue for this.

**Comment by raunaqmorarka** [comment]
Create https://github.com/trinodb/trino/pull/12591 for adding the ability to configure storage schema for iceberg MVs.

**Comment by zhaoyim** [comment]
@raunaqmorarka  logging following WARN message is OK? Thanks! I did some changes now can drop the MV successfully with following message.  
```
2022-06-09T18:53:38.715+0800	WARN	dispatcher-query-0	io.trino.plugin.iceberg.catalog.hms.TrinoHiveCatalog	Failed to drop storage table 'st_660bd374956f42b9bf1966571d699d40' for materialized view 'i12503.materialized_view_1'
io.trino.spi.connector.TableNotFoundException: Table 'i12503.st_660bd374956f42b9bf1966571d699d40' not found
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.dropTable(ThriftHiveMetastore.java:1113)
	at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.dropTable(BridgingHiveMetastore.java:211)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.dropTable(CachingHiveMetastore.java:485)
	at io.trino.plugin.iceberg.catalog.hms.TrinoHiveCatalog.dropMaterializedView(TrinoHiveCatalog.java:503)
	at io.trino.plugin.iceberg.IcebergMetadata.dropMaterializedView(IcebergMetadata.java:1705)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.dropMaterializedView(ClassLoaderSafeConnectorMetadata.java:920)
	at io.trino.metadata.MetadataManager.dropMaterializedView(MetadataManager.java:1263)
	at io.trino.execution.DropMaterializedViewTask.execute(DropMaterializedViewTask.java:85)
	at io.trino.execution.DropMaterializedViewTask.execute(DropMaterializedViewTask.java:35)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:243)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_381____20220609_105304_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findepi** [comment]
After https://github.com/trinodb/trino/pull/18853 this shouldn't be a problem (except for Materialized Views created prior 433).
