### ISSUE TITLE
Kerberos Authentication support in multiple connectors/plugin

### ISSUE THREAD

**Issue by vjain143** [trinodb/trino#12509]
Connectors/Plugins not supporting kerberos Authentication, 
For example mysql not support Kerberos Pluggable Authentication,
https://dev.mysql.com/doc/refman/8.0/en/kerberos-pluggable-authentication.html

Do we have any plan to have this in future releases or how to contribute?

**Comment by hashhar** [comment]
No explicit plans. If you are interested please feel free to send a pull request.

The pull request must however come with tests to demonstrate the functionality is working. See other connectors which already support Kerberos in Trino to see how the tests can look like.
