### ISSUE TITLE
Enable encryption in TestS3FileSystemExchangeManager

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#12524]
Currently we are testing S3 based exchange with encryption disabled on Trino.
It does not match typical production deployment model.

https://github.com/trinodb/trino/blob/583b20e92571c07fb2bffe6143a6148c4e854bef/plugin/trino-exchange/src/test/java/io/trino/plugin/exchange/containers/MinioStorage.java#L90-L91

**Comment by findepi** [comment]
> ` // TODO: enable exchange encryption after https is supported for Trino MinIO`

what does encryption have to do with https?
if we have internal pre-shared secret, we could do client-side encryption, even with query-specific key.

**Comment by losipiuk** [comment]
IDK to be honest. Possibly //TODO comment does not make sense. Yet I expect the `.put("exchange.encryption-enabled", "false") ` is there for a reason.
@linzebing can you please comment?

**Comment by losipiuk** [comment]
N/A - encryption is enabled by default no in engine
