### ISSUE TITLE
Does trino support iceberg table version 2?

### ISSUE THREAD

**Issue by johndb2016** [trinodb/trino#12529]
i wanna use trino to query iceberg table, but i am not sure about whether iceberg conncector supports iceberg version 2 table. 
Any help will be appreciated~

**Comment by johndb2016** [comment]
@findepi But the "Trino 381 Documentation" tells that "It supports Apache Iceberg table spec version 1." Is that doc outdated? By the way , which version of trino supports iceberg version 2 table?

**Comment by findepi** [comment]
thanks for noticing. see #12451
