### ISSUE TITLE
[Doc] elasticsearch.host properties should support multi hosts need to update in doc

### ISSUE THREAD

**Issue by zhaoyim** [trinodb/trino#12528]
Related with issue [Allow multiple hosts for elasticsearch connector (elasticsearch.host property)](https://github.com/trinodb/trino/issues/11889)

**Comment by colebow** [comment]
@zhaoyim Do you plan on handling this, or would you like someone else to try to tackle it?

**Comment by zhaoyim** [comment]
@colebow Please go ahead if you want to work on this issue. Thanks!
