### ISSUE TITLE
Add licenses to pom files and scripts

### ISSUE THREAD

**Issue by Yikf** [trinodb/trino#12546]
Currently, There is no licenses added in some POM files and scripts. Do we need to add these information? @findepi

**Comment by Yikf** [comment]
If it is necessary to add, I will file a PR.

**Comment by findepi** [comment]
I am not aware of such a need, but IANAL.

**Comment by martint** [comment]
It isn’t strictly required. It’s more of a recommendation and convention that makes it easier to tell what license applies to a file if it happens to be copied or present in a third party archive.
