### ISSUE TITLE
Materialized View storage table is visible in show tables

### ISSUE THREAD

**Issue by lukasz-stec** [trinodb/trino#12559]
Currently iceberg MV storage table is visible in `show tables` output.
The question is should it be there?

Pros:
- It takes up resources so it's good for users to see it directly
- user can see it anyway using some other HMS client
- it's already there

Cons:
- user can drop it from trino, making MV invalid
- it's an implementation detail that the user may not expect to be a valid object e.g. this may break the user naming convention for tables, or break automation based on the table list.
- the user has to worry about restricting access to this table
- some users may start to depend on the existence of this table, which will break them if the implementation changes (e.g. the storage table definition is kept in a separate metastore)

Some context is in https://github.com/trinodb/trino/issues/12503 and https://github.com/trinodb/trino/pull/10745#discussion_r793589518.

@findepi @raunaqmorarka I know you have strong opinions, so please share them.

**Comment by zhaoyim** [comment]
I have a question, There is Materialized View, why we need to operate the storage table directly? If we want to access storage table directly, but seems the storage table naming is unreadable.

**Comment by findepi** [comment]
> * the user has to worry about restricting access to this table

If they use Trino only, that would solve the access problem. 
If they use Trino and, say, Spark, they still need to configure access.

> user can see it anyway using some other HMS client

Some other client, or some other app (like EMR, Spark, etc.)
I don't think Trino should provide less information to the users than other applications. I feel strongly about this.

> user can drop it from trino, making MV invalid

System administrator can configure access control rules and then SHOW TABLES won't show storage tables.

cc @losipiuk @sopel39 @martint @electrum @alexjo2144

**Comment by lukasz-stec** [comment]
> I don't think Trino should provide less information to the users than other applications. I feel strongly about this.

Maybe we should not store storage table metadata in the HMS then?

**Comment by sopel39** [comment]
Ideally, storage tables are is special, restricted schemas not accessible directly to normal users

**Comment by martint** [comment]
There some reasons why we modeled storage tables as visible tables. @anjalinorwood, do you remember?

**Comment by anjalinorwood** [comment]
The pros that @lukasz-stec pointed out are some of the reasons. We also [envisioned ](https://docs.google.com/document/d/10jPGw3t-Tu8OgWo5oC9d-O8d1PVdnAbEhyfvnJA0T8U/edit#) enhancing `create materialized view` syntax to associate materialized views with pre-existing table/data and hence the choice to show the storage table with `show tables` command.
[ STORED AS [ EXISTING ] table_name [ COMMENT storage_table_comment ] ]

We also discussed storing storage tables in a different (configurable) schema from the materialized view by setting the table property. That would be a way to hide storage tables from users. 

> There some reasons why we modeled storage tables as visible tables. @anjalinorwood, do you remember?

**Comment by raunaqmorarka** [comment]
> We also discussed storing storage tables in a different (configurable) schema from the materialized view by setting the table property. That would be another way to hide storage tables from users.

https://github.com/trinodb/trino/pull/12591 addresses that

**Comment by mosabua** [comment]
Pinging this issue here since a decision would help with either working towards merging #10745 or clearly documenting and maybe improving output from show tables somehow.

**Comment by findepi** [comment]
> towards merging #10745 or

that PR talks about two things

_add "STORAGE TABLE" and "MATERIALIZED VIEW" type in information_schema.tables_

we definitely won't add "STORAGE TABLE" in information_schema.tables, so let me close this issue

**Comment by mosabua** [comment]
Thank you @findepi
