### ISSUE TITLE
Show table functions in `SHOW FUNCTIONS`

### ISSUE THREAD

**Issue by kasiafi** [trinodb/trino#12550]
It should be added in `ShowQueriesRewrite#visitShowFunctions`.

**Comment by mosabua** [comment]
From a users perspective this should somehow allow you to see what connector these functions are supported.

Separate issue .. maybe we can enhance SHOW FUNCTION to allow it to return a specific type of functions only .. currently you can only use LIKE with the name ..

**Comment by findepi** [comment]
> From a users perspective this should somehow allow you to see what connector these functions are supported.

A PTF is currently provided by a catalog.

Thus, `my_postgres1.system.query` is a _different_ function than `my_postgres2.system.query`  or `my_mysql.system.query`   and `SHOW FUNCTIONS` should return all of them.

**Comment by mosabua** [comment]
Oh ... thanks for clarifying @findepi  .. that makes it even more important to somehow improve SHOW FUNCTIONS to narrow down what is returned.

**Comment by sajjoseph** [comment]
@ebyhr - any thoughts around how you will list out functions available in specific catalogs in ```SHOW FUNCTIONS``` output?
In other words, how do we differentiate built-in functions vs catalog/connector specific functions?

**Comment by findepi** [comment]
> In other words, how do we differentiate built-in functions vs catalog/connector specific functions?

We do not. built-in functions are now registered in a predefined catalog as well
