### ISSUE TITLE
TLS certificate verification is disabled by python through 'verify': False

### ISSUE THREAD

**Issue by njalan** [trinodb/trino#12562]
I have enabled https and also integrated with ldaps.
http-server.authentication.type is password.
While using Dbeaver to connect presto https port it requires truststore file.
But when use python configure below parameters it doesn't need ssl verification. 
**'protocol': 'https','requests_kwargs': {'verify': False}**
How can enforce the server TLS certificate verification ?  I am using presto 340

**Comment by findepi** [comment]
You may want to open an issue in https://github.com/trinodb/trino-python-client instead.
