### ISSUE TITLE
Drop of Iceberg table deletes data of other tables when location shared

### ISSUE THREAD

**Issue by mdesmet** [trinodb/trino#12568]
This scenario is a typical `dbt` workflow.

An existing table is swapped with the new version of the table using` ALTER table RENAME to` statements.

```
 @Test
    public void testRenameTableBackToOriginalName()
    {
        String tableName = "test_rename_table_" + randomTableSuffix();
        String tmpName = "test_rename_table_tmp_" + randomTableSuffix();
        String backupName = "test_rename_table_backup_" + randomTableSuffix();
        try {
            assertUpdate("CREATE TABLE " + tmpName + " AS SELECT 1 as a", 1);
            assertUpdate("ALTER TABLE " + tmpName + " RENAME TO " + tableName);
            assertUpdate("CREATE TABLE " + tmpName + " AS SELECT 1 as a", 1);
            assertUpdate("ALTER TABLE " + tableName + " RENAME TO " + backupName);
            assertUpdate("ALTER TABLE " + tmpName + " RENAME TO " + tableName);
            assertUpdate("DROP TABLE IF EXISTS " + backupName);
            // errors on Failed to open input stream for file: /tmp/TrinoTest16473875710927576859/iceberg_data/tpch/test_rename_table_tmp_1v8injgko4/metadata/00000-745e9fc4-da2a-4097-af6a-b83f78ba5511.metadata.json
            assertUpdate("ALTER TABLE " + tableName + " RENAME TO " + backupName);
        }
        finally {
            assertUpdate("DROP TABLE IF EXISTS " + tableName);
            assertUpdate("DROP TABLE IF EXISTS " + backupName);
            assertUpdate("DROP TABLE IF EXISTS " + tmpName);
        }
    }
```

What we see is that the statement ` assertUpdate("DROP TABLE IF EXISTS " + backupName);` deletes the whole directory which may contain data of other tables.

**Comment by mdesmet** [comment]
As a workaround setting `iceberg.unique-table-location=true` avoids the issue.

**Comment by findepi** [comment]
> What we see is that the statement ` assertUpdate("DROP TABLE IF EXISTS " + backupName);` deletes the whole directory which may contain data of other tables.

We do NOT want to support a use-case where a storage location is shared between multiple tables.
Can you file an issue describing which statement erroneously allowed such situation?

**Comment by findepi** [comment]
cc @electrum @phd3 @alexjo2144

**Comment by mdesmet** [comment]
The statements are provided in the above test case. Note that we use the implicit locations and through renaming we come to this state.

Shouldn't we block this, as it creates the risk of data corruption?

**Comment by mdesmet** [comment]
IMHO the code doesn't match the description:

`assertFalse(fileSystem.exists(tableLocation), "The directory corresponding to the dropped Iceberg table should not be removed because it may be shared with other tables");`

Nevertheless we drop the directory:

`deleteTableDirectory(session, schemaTableName, hdfsEnvironment, new Path(table.location()));`

**Comment by mdesmet** [comment]
Maybe the resolution would be to throw an exception on the second `CREATE TABLE` statement that we can't create on a non-empty path and even suggest to set `iceberg.unique-table-location=true`.

```
assertUpdate("CREATE TABLE " + tmpName + " AS SELECT 1 as a", 1);
assertUpdate("ALTER TABLE " + tmpName + " RENAME TO " + tableName);
assertUpdate("CREATE TABLE " + tmpName + " AS SELECT 1 as a", 1);
```

**Comment by findepi** [comment]
> The statements are provided in the above test case. 

i know. My ask is to distill only those which matter 

> Maybe the resolution would be to throw an exception on the second `CREATE TABLE` statement that we can't create on a non-empty path

I think the same. 
That's why i asked for a new issue -- the problem is with CREATE, not DROP.

**Comment by mdesmet** [comment]
Created https://github.com/trinodb/trino/issues/12573
