### ISSUE TITLE
Iceberg `CREATE TABLE` statement allows to create a table on a location already used by another Iceberg table

### ISSUE THREAD

**Issue by mdesmet** [trinodb/trino#12573]
On Iceberg with default settings following statements result in a location being shared by two tables.

```
CREATE TABLE T1 AS SELECT 1 as a;
ALTER TABLE T1 RENAME TO T2;
CREATE TABLE T1 AS SELECT 1 as a;
```

If later on one of these tables is dropped, it will result in data and metadata loss on the other table as the location is shared.

```
DROP TABLE t1;
SELECT * FROM t2;
```

Results in following exception:

```
13:33:35  FAILED  [SELECT - 0 rows, 91.531 secs]  [Code: 65536, SQL State: ]  Query failed (#20220527_113335_00012_44zsa): Failed to read file: HdfsInputFile{delegate=s3a://datalake/t1/metadata/00000-ac141ee9-369f-4b5b-996d-b88ef979445a.metadata.json, identity=ConnectorIdentity{user='admin', groups=[], principal=admin, enabledSystemroles=[], extraCredentials=[]}}  
select * from t2;
```

We should prevent the user from getting into this situation by throwing an exception on table creation on a non-empty path and suggesting setting `iceberg.unique-table-location=true`.

We should also document this config `iceberg.unique-table-location=true`.

**Comment by mdesmet** [comment]
I still think the delete of the table directory could be problematic. What if the user created two tables on Spark sharing the same location.

`deleteTableDirectory(session, schemaTableName, hdfsEnvironment, new Path(table.location()));`

Can't we run instead the delete orphan files procedure?

**Comment by mdesmet** [comment]
Adding the check for non-empty path on table creation also makes the create table like tests fail. Related to https://github.com/trinodb/trino/pull/11265 as we shouldn't clone the location property.

**Comment by mdesmet** [comment]
I tested this scenario on Spark using following test cases:

```
    @Test(groups = {ICEBERG, PROFILE_SPECIFIC_TESTS}, dataProvider = "specVersions")
    public void testCreateTableWithSameLocationWorksOnSpark(int specVersion)
    {
        String dataPath = "hdfs://hadoop-master:9000/user/hive/warehouse/test_create_table_same_location/obj-data";
        String tableSameLocation1 = "test_same_location_spark_1";
        String tableSameLocation2 = "test_same_location_spark_2";

        onSpark().executeQuery(format("CREATE TABLE %s (_integer INTEGER ) USING ICEBERG LOCATION '%s' TBLPROPERTIES('format-version' = %s)",
                sparkTableName(tableSameLocation1), dataPath, specVersion));
        onSpark().executeQuery(format("CREATE TABLE %s (_integer INTEGER ) USING ICEBERG LOCATION '%s' TBLPROPERTIES('format-version' = %s)",
                sparkTableName(tableSameLocation2), dataPath, specVersion));

        onSpark().executeQuery(format("DROP TABLE IF EXISTS %s", sparkTableName(tableSameLocation1)));

        assertThat(onTrino().executeQuery(format("SELECT * FROM %s", trinoTableName(tableSameLocation2)))).hasNoRows();
        
        onSpark().executeQuery(format("DROP TABLE %s", sparkTableName(tableSameLocation2)));
    }

    @Test(groups = {ICEBERG, PROFILE_SPECIFIC_TESTS}, dataProvider = "specVersions")
    public void testCreateTableWithSameLocationFailsOnTrino(int specVersion)
    {
        String dataPath = "hdfs://hadoop-master:9000/user/hive/warehouse/test_create_table_same_location/obj-data";
        String tableSameLocation1 = "test_same_location_trino_1";
        String tableSameLocation2 = "test_same_location_trino_2";

        onSpark().executeQuery(format("CREATE TABLE %s (_integer INTEGER ) USING ICEBERG LOCATION '%s' TBLPROPERTIES('format-version' = %s)",
                sparkTableName(tableSameLocation1), dataPath, specVersion));
        onSpark().executeQuery(format("CREATE TABLE %s (_integer INTEGER ) USING ICEBERG LOCATION '%s' TBLPROPERTIES('format-version' = %s)",
                sparkTableName(tableSameLocation2), dataPath, specVersion));

        onTrino().executeQuery(format("DROP TABLE %s", trinoTableName(tableSameLocation1)));

        assertQueryFailure(() -> onTrino().executeQuery(format("SELECT * FROM %s", trinoTableName(tableSameLocation2))))
                .hasMessageMatching(".*Failed to open input stream for file.*");

    }
```

conclusions:

* Spark supports creating tables on shared locations
* Spark supports deletes on shared locations
* Trino breaks when dropping one table on a shared location

**Comment by findepi** [comment]
> * Spark supports creating tables on shared locations

I am aware.



> * Trino breaks when dropping one table on a shared location

Correct.
Other things, like `remove_orphan_files` also break on shared locations (for both Trino and Spark).

BTW in Iceberg, certain behaviors seem to be "up to Catalog implementation", for good and bad, so one Spark Iceberg Catalog implementation will manifest different DROP behavior than other. See eg
https://github.com/apache/iceberg/blob/17c0ff7f698bced6f03711819073b26bb8bb3e09/spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java#L251-L257

Again, shared table locations is deployment/configuration/use-case scenario which we deliberately DO NOT want to support.

**Comment by mdesmet** [comment]
> Again, shared table locations is deployment/configuration/use-case scenario which we deliberately DO NOT want to support.

I fully support this statement, within the scope of this issue we can add the check for non-empty path on `CREATE TABLE` statements. That will fix this issue within the Trino ecosystem. I will post a PR for that soon.

> Other things, like remove_orphan_files also break on shared locations (for both Trino and Spark).

I also found out  the same. I'm just a little worried that our `DROP TABLE` statements can result into data loss as we don't/can't guarantee that someone created tables on the same path using Spark or other means but that falls rather in the scope of #12568. IMHO if an operation can result in data loss we should chose the safer option as a default and require an explicit opt-in.
