### ISSUE TITLE
Delta Lake tables having delta.columnMapping.mode='name' or 'id' option return incorrect result

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#12592]
The below test would fail at Trino SELECT though Delta returns correct result. 
```java
    @Test(groups = {DELTA_LAKE_DATABRICKS, DELTA_LAKE_OSS, PROFILE_SPECIFIC_TESTS})
    public void testColumnMappingModeNameCompatibility()
    {
        String tableName = "test_dl_column_mapping_mode_name_" + randomTableSuffix();

        onDelta().executeQuery("" +
                "CREATE TABLE default." + tableName +
                " (a_number INT, a_string STRING)" +
                " USING delta " +
                " LOCATION 's3://" + bucketName + "/databricks-compatibility-test-" + tableName + "'" +
                " TBLPROPERTIES (" +
                " 'delta.columnMapping.mode' = 'name'," +
                " 'delta.minReaderVersion' = '2'," +
                " 'delta.minWriterVersion' = '5')");

        try {
            onDelta().executeQuery("INSERT INTO default." + tableName + " VALUES (1,'ala'), (2, 'kota')");

            List<Row> expectedRows = ImmutableList.of(
                    row(1, "ala"),
                    row(2, "kota"));

            assertThat(onDelta().executeQuery("SELECT * FROM default." + tableName))
                    .containsOnly(expectedRows);
            assertThat(onTrino().executeQuery("SELECT * FROM delta.default." + tableName))
                    .containsOnly(expectedRows);

        }
        finally {
            onDelta().executeQuery("DROP TABLE default." + tableName);
        }
    }

java.lang.AssertionError: Could not find rows:
[1, ala]
[2, kota]

actual rows:
[null, null]
[null, null]
```

Tested on Spark 3.2.1 and Delta Lake 1.2.1.

**Comment by findepi** [comment]
We don't support `delta.columnMapping.mode`. I think it's a new Delta feature, isn't it?
Adding support for it is a feature-add.

cc @alexjo2144 @claudiusli

**Comment by ebyhr** [comment]
I believe it's a bug until we disallow accessing such tables.

**Comment by findepi** [comment]
I agree that we should have such a check... or maybe a check based on `delta.minReaderVersion`, but i don't know where reader version requirements are documented cc @vkorukanti @dennyglee

**Comment by vkorukanti** [comment]
@findepi: reader and writer version requirements are [here](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#requirements-for-readers) and [here](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#writer-version-requirements). 

Column mapping is a new feature which is supported from reader version 2 and writer version 5.

**Comment by alexjo2144** [comment]
We should probably have Issues to track the new features in writer versions 3+ as well

**Comment by ebyhr** [comment]
We disallowed reading `name` & `id` option in #12621 and added support for `name` in #12675.
Let's file a new issue for `id` when necessary.
