### ISSUE TITLE
Do not merge partitions aggressively for table writer stages with use_preferred_write_partitioning enabled

### ISSUE THREAD

**Issue by arhimondr** [trinodb/trino#12616]
By default a single task is limited to writing 100 Hive partitions: https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java#L103

Merging happens here: https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/execution/scheduler/StageTaskSourceFactory.java#L572

Merging partitions too aggressively may cause a single task to try to write more than 100 partitions.

**Comment by findepi** [comment]
cc @losipiuk @sopel39 @radek-starburst
