### ISSUE TITLE
Add some columns in Iceberg `$snapshots` and `$manifests` table

### ISSUE THREAD

**Issue by polaris6** [trinodb/trino#12652]
- [ ] Add [sequence_number](https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/Snapshot.java#L43) and [schema_id](https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/Snapshot.java#L193) columns in Iceberg `$snapshots` table.
- [x] Add [added_rows_count](https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/ManifestFile.java#L50) and [deleted_rows_count](https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/ManifestFile.java#L54), etc columns in Iceberg `$manifests` table.

**Comment by polaris6** [comment]
This change may not be needed, it can be done after https://github.com/trinodb/trino/issues/12649, and the [code](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/SnapshotsTable.java) of iceberg needs to be updated.

**Comment by osscm** [comment]
hi @polaris6 
yeah, I'm doing https://github.com/trinodb/trino/issues/12649 this. (still can't assign issues myself :( ).

Wondering the use of these 2 new columns specially for the snapshots table? 

Spark's [manifests table](https://github.com/apache/iceberg/blob/128d5a161fda076118a7cab1d95ab5064400e08a/core/src/main/java/org/apache/iceberg/ManifestsTable.java#L32) has not added these proposed columns yet.
Is there any discussion around this?

and proposed columns for [snapshots](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/SnapshotsTable.java#L30) are also not being added yet.

**Comment by ebyhr** [comment]
> Add added_rows_count and deleted_rows_count, etc columns in Iceberg $manifests table.

They were added in #10809
