### ISSUE TITLE
Presto Iceberg should support `snapshot hive table as iceberg` as a connector procedure

### ISSUE THREAD

**Issue by Parth-Brahmbhatt** [trinodb/trino#1267]
To make it easier for users to experiment with their existing hive tables, presto should support a iceberg-connector specific procedure which will create the iceberg metadata layout on top of existing hive data files without modifying the hive table in any way.

**Comment by electrum** [comment]
Is there any code in the Iceberg library to handle this?

**Comment by ebyhr** [comment]
Let's continue in #13196 though the objective is a little different.
