### ISSUE TITLE
Deletion is not working as expected on Hive Acid tables

### ISSUE THREAD

**Issue by vinay-kl** [trinodb/trino#12731]
Hi Team,

> Found an issue (v384) with HIVE ACID table today, DELETION is not working on either partitioned or non partitioned table post 1.5 million **row__ids**

```
trino> create table dev_1.delete_issue_test1 with (transactional=true, partitioned_by = ARRAY['d']) as select * from dev_1.delete_trino_data;
CREATE TABLE: 6140935 rows

trino> select count(1) from dev_1.delete_issue_test1 where d is not null;
  _col0  
---------
 6140935

trino> delete from dev_1.delete_issue_test1 where d = '20211003';
DELETE: 6140935 rows

trino> select count(1) from dev_1.delete_issue_test1 where d is not null;
  _col0  
---------
 0

trino> insert into dev_1.delete_issue_test1 select * from dev_1.delete_trino_data;
INSERT: 6140935 rows

trino> select count(1) from dev_1.delete_issue_test1 where d is not null;
  _col0  
---------
 6140935

trino> delete from dev_1.delete_issue_test1 where d = '20211003';
DELETE: 0 rows

trino> select count(1) from dev_1.delete_issue_test1 where d is not null;
  _col0  
---------
 6140935
```

> Slack Link : https://trinodb.slack.com/archives/CGB0QHWSW/p1654618573035539

PFA the CSV for reproducing the bug

[187147706282983994744b51e4e-78eb-41fb-8a9a-404f20dde427.zip](https://github.com/trinodb/trino/files/8859382/187147706282983994744b51e4e-78eb-41fb-8a9a-404f20dde427.zip)

**Comment by vinay-kl** [comment]
steps for reproducing

```
trino> create table dev_1.delete_trino_test_stg1 as SELECT a, b, 20220101 as d FROM UNNEST(SEQUENCE(1, 9001), SEQUENCE(1, 9001)) AS t(a, b);
CREATE TABLE: 9001 rows

trino> create table dev_1.delete_trino_test_stg2 as SELECT a, b, 20220101 as d FROM UNNEST(SEQUENCE(1, 100), SEQUENCE(1, 100)) AS t(a, b);
CREATE TABLE: 100 rows

trino> create table dev_1.delete_trino_test_new with (transactional=true, partitioned_by=ARRAY['d']) as (select stg1.a as a, stg1.b as b, stg1.d as d from dev_1.delete_trino_test_stg1 stg1, dev_1.delete_trino_test_stg2 stg2 where stg1.d=stg2.d);
CREATE TABLE: 900100 rows

trino> select count(1) from dev_1.delete_trino_test_new where d is not null;
 _col0  
--------
 900100 

trino> delete from dev_1.delete_trino_test_new where d = 20220101;
DELETE: 900100 rows

trino> select count(1) from dev_1.delete_trino_test_new where d is not null;
 _col0  
--------
 0 

trino> insert into dev_1.delete_trino_test_new select stg1.a as a, stg1.b as b, stg1.d as d from dev_1.delete_trino_test_stg1 stg1, dev_1.delete_trino_test_stg2 stg2 where stg1.d=stg2.d;
INSERT: 900100 rows

trino> select count(1) from dev_1.delete_trino_test_new where d is not null;
 _col0  
--------
 900100 

trino> delete from dev_1.delete_trino_test_new where d = 20220101;
DELETE: 0 rows

trino> select count(1) from dev_1.delete_trino_test_new where d is not null;
 _col0  
--------
 900100 
```

**Comment by vinay-kl** [comment]
@findepi @djsstarburst @electrum, can you please help here?

**Comment by djsstarburst** [comment]
That's correct, @vinay-kl.  How delete and update work got redone in 404-SNAPSHOT.

**Comment by vinay-kl** [comment]
got it, thanks @djsstarburst. Any ETA on when `v405` would be released?

**Comment by kokosing** [comment]
@djsstarburst are you going to contribute this test to Trino?

**Comment by hashhar** [comment]
@djsstarburst AFAIK we still allow to opt to use the older implementation so the correctness bug still exists in current versions of Trino - just with a non-default configuration.

**Comment by findepi** [comment]
> @djsstarburst are you going to contribute this test to Trino?

Good idea, especially that this was a data size-dependent correctness issue.
(Is it possible to run such a test stably on the CI?)

> AFAIK we still allow to opt to use the older implementation so the correctness bug still exists in current versions of Trino - just with a non-default configuration.

@hashhar good point
I think we should now disable the legacy mode for ACID tables, as part of this issue resolution.

**Comment by djsstarburst** [comment]
> @djsstarburst are you going to contribute this test to Trino?

[Here is a Trino PR with the new test](https://github.com/trinodb/trino/pull/15475).

> I think we should now disable the legacy mode for ACID tables, as part of this issue resolution.

I'll work with @electrum to do this.
