### ISSUE TITLE
Document Iceberg time travel

### ISSUE THREAD

**Issue by colebow** [trinodb/trino#12745]
We should document how to use Iceberg time travel, as it was implemented in #10258 
cc @findepi

**Comment by findepi** [comment]
FWIW The syntax and engine-side was added in https://github.com/trinodb/trino/pull/8773

**Comment by mosabua** [comment]
@colebow you can work with @findinpath and @claudiusli on that..

**Comment by tnatssb** [comment]
Any progress on this?

**Comment by findinpath** [comment]
@colebow  CPTAL at #10515 ?
