### ISSUE TITLE
Deprecate assumeLiteralNamesInMetadataCallsForNonConformingClients from JDBC driver

### ISSUE THREAD

**Issue by hovaesco** [trinodb/trino#12761]
https://github.com/trinodb/trino/pull/12672 introduced a new parameter `assumeLiteralUnderscoreInMetadataCallsForNonConformingClients` that solves a bug in Tableau while loading a table metadata by not escaping a wildcard character. 

Old parameter `assumeLiteralNamesInMetadataCallsForNonConformingClients` was originally introduced to fix it in Tableau but it can be replaced now by the new one. 

The plan is to announce the deprecation of the new parameter in Slack, ask community about potential usage of this parameter in other clients and coordinate the next steps.

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/13090
