### ISSUE TITLE
Create view on cassandra connector

### ISSUE THREAD

**Issue by brijsaini03** [trinodb/trino#12791]
Hi Guys,
I am using trino(383).
I need to perform this operation with Cassandra and Mongo connectors.  When I am running query to create view. It is showing error -
`This connector does not support creating view`.

Since it is mentioned here - https://trino.io/docs/current/language/sql-support.html#sql-globally-available 

Just wanted to know if this feature is not yet supported in this version.

**Comment by ebyhr** [comment]
Both connector don't support views and also the page doesn't contain `CREATE VIEW`.
