### ISSUE TITLE
Iceberg: `DELETE` erases table history

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#12843]
```
trino:default> create table testdelete(x integer);
CREATE TABLE
trino:default> insert into testdelete values (1), (2), (3);
INSERT: 3 rows

Query 20220614_152504_00013_gv7tm, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
1.22 [0 rows, 0B] [0 rows/s, 0B/s]

trino:default> insert into testdelete values (4), (5), (6);
INSERT: 3 rows

Query 20220614_152515_00014_gv7tm, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0.98 [0 rows, 0B] [0 rows/s, 0B/s]

trino:default> delete from testdelete where x < 5;
DELETE: 4 rows

Query 20220614_152551_00015_gv7tm, FINISHED, 1 node
Splits: 11 total, 11 done (100.00%)
1.85 [6 rows, 500B] [3 rows/s, 271B/s]

trino:default> select * from "testdelete$snapshots";
             committed_at              |     snapshot_id     |      parent_id      | operation |                              >
---------------------------------------+---------------------+---------------------+-----------+------------------------------>
 2022-06-14 21:08:11.577 Europe/Vienna | 1386882508859864681 |                NULL | append    | hdfs://hadoop-master:9000/use>
 2022-06-14 21:08:25.195 Europe/Vienna | 4461048881573015820 | 1386882508859864681 | append    | hdfs://hadoop-master:9000/use>
 2022-06-14 21:08:35.949 Europe/Vienna | 8379972341036083093 | 4461048881573015820 | append    | hdfs://hadoop-master:9000/use>
 2022-06-14 21:09:11.847 Europe/Vienna |  256546177688590785 | 8379972341036083093 | overwrite | hdfs://hadoop-master:9000/use>
 2022-06-14 21:09:12.006 Europe/Vienna | 4511418255003595023 |  256546177688590785 | delete    | hdfs://hadoop-master:9000/use>
(5 rows)

Query 20220614_152604_00016_gv7tm, FINISHED, 1 node
Splits: 9 total, 9 done (100.00%)
0.26 [5 rows, 2.61KB] [19 rows/s, 9.99KB/s]

trino:default> select * from "testdelete$history";
            made_current_at            |     snapshot_id     |     parent_id      | is_current_ancestor 
---------------------------------------+---------------------+--------------------+---------------------
 2022-06-14 21:09:12.006 Europe/Vienna | 4511418255003595023 | 256546177688590785 | true                
(1 row)
```

The `DELETE` statement is creating two table snapshots:

https://github.com/trinodb/trino/blob/2a466edc37e26047d8cbc7f98023aa62452e782c/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java#L1569

https://github.com/trinodb/trino/blob/2a466edc37e26047d8cbc7f98023aa62452e782c/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java#L1598

This is probably not needed.

As can be seen in the snippet above, the history of the table is corrupted after executing the `DELETE` statement.

Also a CTAS statement based on a version of the source table is failing due to this reason.

**Comment by alexjo2144** [comment]
Looks like a bug in the case where some files are fully deleted and some require row level deletes. I'll take a look

**Comment by alexjo2144** [comment]
So, the fact that there are two snapshots is intentional. If a file can be removed fully by the delete operation it is deleted by the `delete` operation, if it requires a row level delete it is included in the `overwrite` operation.

I'm not sure why this messes up the history table though.

**Comment by findepi** [comment]
> it is deleted by the delete operation, if it requires a row level delete it is included in the overwrite operation.

they should happen in a single transaction, so I would hope for this to be a single table snapshot.
the intermediate snapshot isn't correct state of a table, so i would prefer for it to be squashed.

@danielcweeks is it possible?

> As can be seen in the snippet above, the history of the table is corrupted after executing the `DELETE` statement.

What you mean by corrupted?

**Comment by alexjo2144** [comment]
> they should happen in a single transaction

Yeah, they are both included in one transaction

Here's a code reference: https://github.com/trinodb/trino/blame/1be4a8cdd9806b23dd0dd466e5390bcf8cff7885/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java#L1598

**Comment by findepi** [comment]
> Here's my repro, the history table after the delete doesn't have any of the prior snapshots:

I noticed that, but thanks for calling this out explicitly.

**Comment by kbendick** [comment]
I have noticed this as well when working on https://github.com/trinodb/trino/pull/11298 (that two snapshots are generated during a DELETE).

**Comment by alexjo2144** [comment]
One thing I realized today, if it matters. It's just the table's `$history` table that gets corrupted. You can still time travel back to previous snapshots, you just can't see the available snapshots in the history table.

**Comment by alexjo2144** [comment]
https://github.com/apache/iceberg/issues/5442

**Comment by findepi** [comment]
If the old snapshots do exist, why can't we show them in `$history`?
