### ISSUE TITLE
run developmentServer failed with java.lang.NoClassDefFoundError: com/google/inject/Module

### ISSUE THREAD

**Issue by samyScott** [trinodb/trino#12889]
JDK version : 11.0.12
Trino version : latest

**the failed message is** 
2022-06-17T16:01:25.805+0800	INFO	startup-3	io.trino.server.PluginManager	Installing io.trino.plugin.hive.HivePlugin
2022-06-17T16:01:25.806+0800	INFO	startup-3	io.trino.server.PluginManager	-- Loading plugin ../../plugin/trino-tpch/pom.xml --
2022-06-17T16:01:25.808+0800	ERROR	main	io.trino.server.Server	com/google/inject/Module
java.lang.NoClassDefFoundError: com/google/inject/Module

when run the command "mvn clean install -DskipTests" is successful, but run the test  DevelopmentServer failed, please tell me how I can solve the solution

**Comment by ebyhr** [comment]
Could you confirm below setting?
* JDK path on your CLI
* JDK path of `DevelopmentServer` application setting on IntelliJ

**Comment by ebyhr** [comment]
Could you share screenshots?

**Comment by samyScott** [comment]
OKOK，thanks！
this is  the error
<img width="1440" alt="截屏2022-06-17 下午10 07 08" src="https://user-images.githubusercontent.com/38185636/174327064-736b107b-5838-4618-a337-a19892316b3d.png">
and this is the JDK intercalate 
<img width="1440" alt="截屏2022-06-17 下午10 24 10 1" src="https://user-images.githubusercontent.com/38185636/174327520-5db43b51-8591-4cbd-9b6e-5f90303c8268.png">
<img width="1440" alt="截屏2022-06-17 下午10 24 49" src="https://user-images.githubusercontent.com/38185636/174327551-40d686bd-7fff-4f9e-969d-ed300f2500a7.png">
<img width="1440" alt="截屏2022-06-17 下午10 25 13" src="https://user-images.githubusercontent.com/38185636/174327592-6672f5bd-1271-4305-8233-0ce872898242.png">

**Comment by ebyhr** [comment]
Thanks, please also share the screenshot of
* JDK path on your shell (where you executed `./mvnw` command)
* JDK path of DevelopmentServer application setting on IntelliJ
* Result of `./mvnw -v`

**Comment by samyScott** [comment]
the problem has been solved，when run the command "mvnw clean install -DskipTests", and then running the DevelopmentServer is successful, so maybe the reason is the maven version is not compatible, my local maven version is 3.6.3.
