### ISSUE TITLE
Trino CLI - Not able to create a Table in S3 - Query failed checking path s3a://xxx

### ISSUE THREAD

**Issue by alexcpn** [trinodb/trino#12886]
### Discussed in https://github.com/trinodb/trino/discussions/12877

<div type='discussions-op-text'>

<sup>Originally posted by **alexcpn** June 16, 2022</sup>
I have the following Kubernetes setup
```
Using TrinoCLI -- TrinoServer -- Hive Metastore Standalone - Postgres 
                               (Trino Workers)                                             - S3
 ```                                                       

I am able to create the Schema successfully in S3

```
trino:default> CREATE SCHEMA hive.test4 WITH (location ='s3a://test/test4');
CREATE SCHEMA
```
![image](https://user-images.githubusercontent.com/1157251/174038322-eda41bf3-4252-44ad-b0b6-52d6b9f05697.png)

(note the [warehouse](https://github.com/alexcpn/presto_in_kubernetes/blob/main/hive/metastore-cfg.yaml#L53-L54) folder I created manually as I was getting an error without it)

Trying to create a SCHEMA with this location, I am getting the error `Failed to check path: s3a://test/test4/orders`

```
CREATE SCHEMA hive.tpcds WITH (location = 's3a://test/warehouse/tpcds/');
CREATE SCHEMA
trino:default> CREATE TABLE tpcds.store_sales AS SELECT * FROM tpcds.tiny.store_sales;
Query 20220616_105922_00029_pekif failed: Failed checking path: s3a://test/warehouse/tpcds/store_sales
```
I did one more test

```
create schema test;
USE test;
CREATE TABLE store  AS SELECT * FROM tpcds.tiny.store_sales;
Query 20220617_055218_00032_d7buj failed: Failed checking path: s3a://test/warehouse/test.db/store
```
I see that it has created  a folder named `test.db` in S3; So it is creating the Schema;but not abe to create the Table

![image](https://user-images.githubusercontent.com/1157251/174234519-f1738d01-f016-4ca4-b9b2-7a56b48b1798.png)

All configurations are in https://github.com/alexcpn/presto_in_kubernetes

The latest image is used - trinodb/trino:386

In Hive configuration I gave `metastore.warehouse.dir` as `s3a://test/warehouse`

Code is checking if the path to Table exist even without creating the table

**Comment by AlakmarShafin** [comment]
im having same issue but im using azure adls gen2 storage, please can you tell what configurations i have to do??
