### ISSUE TITLE
trinodb/trino:latest support Geometry?

### ISSUE THREAD

**Issue by Wangdamao01** [trinodb/trino#12885]
Does the latest image support Geometry? How should the PostgreSQL Connector, pg.properties configuration file be configured

**Comment by ebyhr** [comment]
Do you mean `PostGis` support? Could you share more details?

**Comment by Wangdamao01** [comment]
> We use PostgresQL to store spatial data. We want to ask whether Trino supports querying PostGIS Geometry Columns. https://github.com/trinodb/trino/pull/9951 is available on the solution of the mentioned, this article container mirror deployment Settings take effect

**Comment by ebyhr** [comment]
The type isn't yet supported. Hope this Slack thread helps you https://trinodb.slack.com/archives/CFLB9AMBN/p1624544478194000

Let me close this issue now. There're existing issue #5580 and PR #9951.
