### ISSUE TITLE
Partitioning does not show up in $properties in Iceberg

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#12891]
Partitioning is set with `CREATE TABLE WITH` as a property.

Partitioning can be changed with `ALTER TABLE SET PROPERTIES`.

You can see the value with `SHOW CREATE TABLE`.

I would expect that `SELECT * FROM mytable$properties` also returns the partitioning property and currently set value. 

We ran into this not working in the Trino Community Broadcast fyi.. 

https://youtu.be/oG-HSB3tCY8?t=5293

**Comment by mosabua** [comment]
The other question to test in this context is what happens after a properties value change .. I would expect that SHOW CREATE TABLE shows the new/current value .. even though that feels kinda weird since that is not how the table was created...

**Comment by findepi** [comment]
> I would expect that SHOW CREATE TABLE shows the new/current value

yes, this is the expected behavior.

**Comment by ebyhr** [comment]
The `$properties` table is for providing [Iceberg properties](https://iceberg.apache.org/spec/#:~:text=1000-,properties,-JSON%20object%3A%20%7B) (not Trino table properties). I suppose we don't want to expose the partition definition via the system table.

**Comment by mosabua** [comment]
well.. thats certainly confusing .. after all .. when you create table in trino you use the trino table properties .. including partitioning .. so what is there a clear distinction between a trino table property and the underlying iceberg properties?

**Comment by ebyhr** [comment]
It's little hard to draw a boundary because the connector basically maps Iceberg properties to Trino properties. Let's continue in #11538
