### ISSUE TITLE
Deduplicate `PrintingLogConsumer` classes

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#12947]
The Trino codebase has (at the time of this writing) three `PrintingLogConsumer` classes:

- io.trino.plugin.deltalake.util.PrintingLogConsumer (logs information)
- io.trino.testing.kafka.PrintingLogConsumer (writes to a file)
- io.trino.tests.product.launcher.testcontainers.PrintingLogConsumer (writes to a file)

The `PrintingLogConsumer` classes from `trino-testing-kafka` and `trino-product-tests-launcher` projects are purely duplicated.

Bring the classes to a common place (e.g. : `trino-testing-containers` ) and try to come up with a code structure that makes code reuse between the log & file write functionality.

**Comment by martint** [comment]
Duplicated code is not necessarily a bad thing, especially if the alternative is to create an artificial dependency on a common component.
