### ISSUE TITLE
JDBC connection without password

### ISSUE THREAD

**Issue by miton18** [trinodb/trino#12954]
I'm trying to use Trino with [Pulsar](https://pulsar.apache.org/docs/sql-overview) with its Docker image.
Because we use it as test containers, there is no `Auth` neither `TLS` configured.

Using curl, I have to set a BasicAuth `username` else, I get a "Error: User must be set"
With curl and a `username`, everything is fine <3

Using JDBC, I try to set a `username`, but the driver does not use it if there is no `password` filled.
When I try to set a `password`, I have an error message telling me I have to setup TLS if I want to use `user`/`password` 
There is no TLS set on this image.

I think the issue come from here https://github.com/trinodb/trino/blob/master/client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoDriverUri.java#L269

Is there any reason to not allow `username` without `password` ?

Additionally, the **tempto** bug seems to be fixed
https://github.com/trinodb/tempto/pull/99

**Comment by ebyhr** [comment]
Thanks for sharing connection string. Please share the code using it.

**Comment by miton18** [comment]
Will be a bit hard without pasting hundred of classes, but this is the code with build the JDBC config
```
override protected def config: HikariConfig = {
    val cfg: HikariConfig = new HikariConfig()
    cfg.setDriverClassName("io.trino.jdbc.TrinoDriver")
    // cfg.addDataSourceProperty("SSL", "false")
    cfg.setJdbcUrl("jdbc:trino://localhost:49193/pulsar?user=test")
    cfg.setConnectionTimeout(10000)
    cfg.setInitializationFailTimeout(10000)
    // val properties: Properties = new Properties();
    // properties.setProperty("SSL", "true")
    
    // cfg.setDataSourceProperties(properties)
    // err: [Error: User must be set]
    // cfg.setUsername("test")
    // cfg.addDataSourceProperty("sessionUser", "myuser")
    // cfg.setPassword("empty")
    // TODO: AccessToken Biscuit ?

    cfg.setConnectionTestQuery("SELECT * FROM system.runtime.nodes")
    // cfg.setLeakDetectionThreshold(30 * 1000)
    // cfg.setMaximumPoolSize(configuration.maximumPoolSize)
    // cfg.setConnectionTimeout(TimeUnit.SECONDS.toMillis(configuration.connectionTimeout))
    // cfg.setMinimumIdle(configuration.minimumIdle)
    // cfg.setIdleTimeout(TimeUnit.SECONDS.toMillis(configuration.idleTimeout))
    // cfg.setAutoCommit(false)

    cfg
  }
```

**Comment by ebyhr** [comment]
The below code works without any issues. 
```java
        HikariConfig cfg = new HikariConfig();
        cfg.setDriverClassName("io.trino.jdbc.TrinoDriver");
        cfg.setJdbcUrl("jdbc:trino://localhost:8080/tpch?user=test");

        try (Connection connection = new HikariDataSource(cfg).getConnection();
             Statement statement = connection.createStatement()) {
            ResultSet resultSet = statement.executeQuery("SELECT current_user");
            resultSet.next();
            System.out.println(resultSet.getString(1));
        }
```

**Comment by ebyhr** [comment]
Could you share your Trino config files? You can mask confidential info.

**Comment by miton18** [comment]
The issue seems to come from the version used by Pulsar image (Presto v332). Sorry for the noise
