### ISSUE TITLE
Help option for launcher has misaligned output

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#12970]
Found this while working on the book:

<img width="872" alt="Screen Shot 2022-06-23 at 22 47 38" src="https://user-images.githubusercontent.com/145658/175470754-88b517f1-6a1a-4232-823c-78c75730a339.png">

We should fix this up if possible. I think the code for this might be in airbase ... Maybe @nineinchnick @MiguelWeezardo or @colebow could take a peak .. might be an easy fix.

The left columns just needs to be three spaces wider ;-)

**Comment by nineinchnick** [comment]
Why? If argparse is used to print this from the python stdlib it might not be configurable.

**Comment by mosabua** [comment]
It just looks bad and is not properly aligned .. but if nothing can be done to improve readability .. we can close this. I just dont know enough about how this works at this stage.

**Comment by hashhar** [comment]
argparse prints each column by constraining them to a particular column width. If the line would get wider then it clips it to newline - nothing can be done about it without "hacking" `max_help_position` in `argparse.HelpFormatter` (which is stdlib, not our code).

**Comment by mosabua** [comment]
What a shame ... one more reason why I am not a Pythonista
