### ISSUE TITLE
Querying Iceberg ORC unpartitioned table with many files cause node errors

### ISSUE THREAD

**Issue by alexjo2144** [trinodb/trino#12984]
Reported by @przemekak 

Run on version 385.

When doing a simple Iceberg query on unpartitioned data, like:
```sql
select count(*) from iceberg.iceberg_tpch_sf1000_history_orc.lineitem WHERE shipdate < CAST('1992-11-01' AS DATE)
```
It causes error:

```
io.trino.spi.TrinoTransportException: Encountered too many errors talking to a worker node. 
The node may have crashed or be under too much load. 
This is probably a transient issue, so please retry your query in a few minutes. 
(updating task http://10.2.1.70:8080/v1/task/20220620_124557_00000_rbgzj.1.0.0 - 20 failures, 
failure duration 304.73s, total failed request time 205.42s)
```

Table was created using `hive.target-max-file-size=10MB`

and contains: Total number of objects 43,178. Total size 157.2 GB

The same query works quite fast for partitioned data, and on both partitioned and un-partitioned Parquet data.

**Comment by homar** [comment]
I assume @przemekak ran into this on a specific cluster. Is it possible to access it somehow?
