### ISSUE TITLE
Delta Lake Glue support for `ALTER TABLE RENAME TO`

### ISSUE THREAD

**Issue by alexjo2144** [trinodb/trino#12985]
Could be implemented similarly to how the Iceberg Glue catalog does it: https://github.com/trinodb/trino/blob/b4507ddad6e3b4c1cb472dbafb20e5a20b192cf6/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java#L335-L364

**Comment by findepi** [comment]
@pettyjamesm what's the timeline for Glue API to support renaming tables in a more fault-tolerant manner?

**Comment by homar** [comment]
@alexjo2144 @findepi should this work for both managed and external tables or only for external tables?

**Comment by findepi** [comment]
Let's do both.
