### ISSUE TITLE
"No tests executed" Exception while executing product test on Mac

### ISSUE THREAD

**Issue by chen-ni** [trinodb/trino#12991]
I'm following [this guide](https://github.com/trinodb/trino/blob/6b34a29b4c74275adfceafc86872a808e90bd3c0/testing/trino-product-tests/README.md#running-the-product-tests) to run product tests on my Mac using Docker.

After the environment is set up, I copied and executed [the command to run a single test](https://github.com/trinodb/trino/blob/6b34a29b4c74275adfceafc86872a808e90bd3c0/testing/trino-product-tests/README.md#running-a-single-test):
```
testing/bin/ptl test run \
            --environment multinode \
            -- -t io.trino.tests.functions.operators.Comparison.testLessThanOrEqualOperatorExists
```

Then I got this error:
```
tests               | java.lang.IllegalStateException: No tests executed
tests               |   at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
tests               |   at io.trino.tempto.internal.listeners.ProgressLoggingListener.onFinish(ProgressLoggingListener.java:105)
tests               |   at org.testng.TestRunner.fireEvent(TestRunner.java:1213)
tests               |   at org.testng.TestRunner.afterRun(TestRunner.java:1001)
tests               |   at org.testng.TestRunner.run(TestRunner.java:614)
tests               |   at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
tests               |   at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
tests               |   at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
tests               |   at org.testng.SuiteRunner.run(SuiteRunner.java:289)
tests               |   at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
tests               |   at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
tests               |   at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
tests               |   at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
tests               |   at org.testng.TestNG.runSuites(TestNG.java:1133)
tests               |   at org.testng.TestNG.run(TestNG.java:1104)
tests               |   at io.trino.tempto.runner.TemptoRunner.run(TemptoRunner.java:91)
tests               |   at io.trino.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:64)
tests               |   at io.trino.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:52)
tests               |   at io.trino.tests.product.TemptoProductTestRunner.main(TemptoProductTestRunner.java:27)
tests               | 
tests               | ===============================================
tests               | tempto-tests
tests               | Total tests run: 0, Failures: 0, Skips: 0
tests               | ===============================================
tests               | 
tests               | (exited)

```

Which makes me very confused because:

- The error message is not very informative. I scrolled up but didn't find any other error messages;
- It's not mentioned in the [known issues section](https://github.com/trinodb/trino/blob/6b34a29b4c74275adfceafc86872a808e90bd3c0/testing/trino-product-tests/README.md#known-issues).

I think it would be better to:

- Either show a more precise error message to the developer;
- Or we can add the solution to the known issues section.

By the way, it would be great if someone could help me solve it in the first place. Thanks!

**Comment by findepi** [comment]
The class name is `TestComparison` not `Comparison`

**Comment by Rramu91** [comment]
@findepi I face the same issue and the error is not so informative.

 testing/bin/ptl test run --environment multinode --config config-default -- -t io.trino.tests.functions.operators.TestComparison.testLessThanOrEqualOperatorExists

tests               | java.lang.IllegalStateException: No tests executed
tests               | 	at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
tests               | 	at io.trino.tempto.internal.listeners.ProgressLoggingListener.onFinish(ProgressLoggingListener.java:105)
tests               | 	at org.testng.TestRunner.fireEvent(TestRunner.java:1213)
tests               | 	at org.testng.TestRunner.afterRun(TestRunner.java:1001)
tests               | 	at org.testng.TestRunner.run(TestRunner.java:614)
tests               | 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
tests               | 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
tests               | 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
tests               | 	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
tests               | 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
tests               | 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
tests               | 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
tests               | 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
tests               | 	at org.testng.TestNG.runSuites(TestNG.java:1133)
tests               | 	at org.testng.TestNG.run(TestNG.java:1104)
tests               | 	at io.trino.tempto.runner.TemptoRunner.run(TemptoRunner.java:91)
tests               | 	at io.trino.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:64)
tests               | 	at io.trino.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:52)
tests               | 	at io.trino.tests.product.TemptoProductTestRunner.main(TemptoProductTestRunner.java:27)
tests               | 2023-05-12 12:27:45 INFO: ManageTestResources.onFinish: running checks

**Comment by findepi** [comment]
use unqualified class name

```
testing/bin/ptl test run --environment multinode --config config-default -- -t TestComparison.testLessThanOrEqualOperatorExists
```
