### ISSUE TITLE
Trino CLI reports data with wrong units

### ISSUE THREAD

**Issue by metadaddy** [trinodb/trino#13054]
Using the Trino CLI to query CSV data via the Hive connector, I noticed that the CLI is reporting the amount of data transferred incorrectly. Querying a 72.8 MB CSV file, the CLI reported that it had transferred only 69.4 MB of data.

It seems that the discrepancy arises from the fact that macOS, correctly, reports file sizes in kilobytes, megabytes, gigabytes, etc, based on powers of 1,000, with the abbreviations KB, MB, GB, while the Trino CLI is reporting the number of kibibytes, mebibytes, gibibytes etc, based on powers of 1,024. but using the KB/MB/GB abbreviations rather than the correct KiB/MiB/GiB. The math confirms this - (69.4 * 1,024 * 1,024) / (1,000 * 1,000) = 72.8.

See [this wikipedia page](https://en.wikipedia.org/wiki/Megabyte) for an explanation of the correct terms to use.

The Trino CLI should either use the KiB/MiB/GiB abbreviations or, preferably, report the number of kilobytes/megabytes/gigabytes correctly.

**Comment by nineinchnick** [comment]
I noticed this when working on https://github.com/trinodb/trino/pull/11160 and also reported https://github.com/airlift/units/issues/26. But maybe the code in cli is different and changing this wouldn't be considered a breaking change?

**Comment by metadaddy** [comment]
@nineinchnick I'm preparing a PR specifically in the CLI - since the output is reported to the user, rather than written to logs, so the blast radius should be smaller.

**Comment by nineinchnick** [comment]
@dain wdyt?

**Comment by metadaddy** [comment]
Thanks, @mosabua - I'm submitting a PR. As far as using Trino - stay tuned...
