### ISSUE TITLE
Remove deprecated query pass-through mechanism for Elasticsearch connector

### ISSUE THREAD

**Issue by kasiafi** [trinodb/trino#13050]
To be removed: https://trino.io/docs/current/connector/elasticsearch.html?highlight=elasticsearch#pass-through-queries

The pass-through mechanism was deprecated in https://github.com/trinodb/trino/pull/12324 in favor of the `raw_query` table function.

**Comment by Nian007** [comment]
I would like to pick this up.

**Comment by kasiafi** [comment]
@Nian007 there's already a PR open addressing this issue (https://github.com/trinodb/trino/pull/13390). It was blocked with some preconditions, but might be ready to proceed now.
