### ISSUE TITLE
Add support for creating MongoDB views

### ISSUE THREAD

**Issue by mingfang** [trinodb/trino#13061]
This is needed for our dbt view models

**Comment by mingfang** [comment]
MongoDB views.
My setup is dbt-trino -> trino -> mongodb.
When I set my dbt model materialization to view
```
{{ config(materialized='view') }}
```
I am getting this error
```
TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="This connector does not support creating views", query_id=20220701_135107_00295_xhv6z)
```

**Comment by mingfang** [comment]
do you think this is a `dbt-trino` bug?

**Comment by ebyhr** [comment]
I don't think so. Requesting a Trino view in `dbt-trino` looks natural. 

Let me close this issue. It would be better to create such views in MongoDB side instead of the connector in my opinion.
