### ISSUE TITLE
Implement session logout and redirection to login Oauth server

### ISSUE THREAD

**Issue by anilkumar000** [trinodb/trino#13060]
Hi Team,
## Could be taken up as further enhancement of oauth logout impl.

In our scenerio, After logging out from Trino it just gives a html page as [here ](https://github.com/mat3e/trino/commit/53739bb1b8e42507a2cdc93d8c34bac460e9fc52) and if i refresh the browser in logout enpoint, it goes `/authorise` enpoint of adfs server and uses the token in cookie to login back again without asking for user credentials. So Would we be able to get a configuration to provide logout url so that the api will be called with logged in user's token param and  the oauth server's session also will be logged out.

Kindly look into it as this might be keen to have feature on security aspect.

Auth server : Microsoft ADFS
Configurations used:
```
http-server.authentication.type=OAUTH2,CERTIFICATE
web-ui.authentication.type=oauth2
http-server.https.enabled=true
http-server.https.port=8443	
http-server.https.keystore.path=/<path>/cert.pem
http-server.authentication.allow-insecure-over-http=true
http-server.process-forwarded=true
internal-communication.shared-secret=<secret>
http-server.authentication.oauth2.issuer=<base-url-of-auth-server>
http-server.authentication.oauth2.client-id=<CLIENT_ID>
http-server.authentication.oauth2.client-secret=<CLIENT_SECRET>
http-server.authentication.oauth2.access-token-issuer=<access_token_issuer_url>
http-server.authentication.oauth2.scopes=openid
http-server.authentication.oauth2.additional-audiences=microsoft:identityserver:<client_id>
http-server.authentication.oauth2.oidc.use-userinfo-endpoint=false
http-server.authentication.oauth2.principal-field=unique_name
```

**Comment by Praveen2112** [comment]
cc: @s2lomon @lukasz-walkiewicz

**Comment by rohank07** [comment]
Encountering similar issue. Clicking logout button and configuring logout URL on azure does not clear user's session. I am still able to login back in without credentials.

**Comment by masayyed** [comment]
I am also facing same issue. Raised question on Slack with video. 
https://trinodb.slack.com/archives/CP1MUNEUX/p1689172574881279

**Comment by mano1233** [comment]
Hey is there any further development?

**Comment by Praveen2112** [comment]
@anilkumar000 / @mano1233 / @masayyed Can you check by applying the linked PR ?

**Comment by masayyed** [comment]
> @anilkumar000 / @mano1233 / @masayyed Can you check by applying the linked PR ?

@Praveen2112 It is working fine for me. Thanks.

**Comment by urstrulykumar** [comment]
When and what SEP version is this fix available?
hmrc uk has also reported the similar issue about SEP logout doesnt' logs out the keycloak oauth2 issue. 
Auth Server : Keycloak
