### ISSUE TITLE
Iceberg scanning with Delete Files is extremely/unusably slow

### ISSUE THREAD

**Issue by lhofhansl** [trinodb/trino#13092]
See https://github.com/trinodb/trino/blob/bbf4e86807f4556a237b8cad19dbbfa565e6f381/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java#L173

Looks harmless enough. But DeleteFilter will re-open and re-read the split's delete files for each page:
See: https://github.com/apache/iceberg/blob/c8b97c91ac04a2ee5ee8f746dcc4619a9c8d5ffe/data/src/main/java/org/apache/iceberg/data/DeleteFilter.java#L216

With large delete files this easily leads to a query for a table of 6 million of which 3 million were deleted taking hours to finish.
But even just deleting 5 rows, slows down scanning dramatically. In the profiler I see that all the time is spent in opening and reopening the delete files.

It's not recoverable from within Trino as OPTIMIZE is equally slow.

Unfortunately Iceberg's DeleteFilter, which we are using here, has no other API to use, so we'd either have to do this ourselves, or do some batching in IcebergPageSource, or using (much) bigger page sizes.

**Comment by raunaqmorarka** [comment]
fyi @alexjo2144

**Comment by alexjo2144** [comment]
Maybe there is some filtering on the delete files we are not performing?

Do you have any data on how the same query performs on Spark?

**Comment by lhofhansl** [comment]
In my case there is only one delete file and only one data file - kinda the worst case.
So as we scan the data is page-chunks, the delete file is re-read for each page.

Lemme try to run this in Spark... Need to set that up first.

**Comment by lhofhansl** [comment]
OK. Spark does not have this issue.
In the case where 3m rows were deleted Spark returns the correct result after 12s, whereas Trino never completes (throughout 1 row/s).

**Comment by lhofhansl** [comment]
Please have a look at the linked PR when you get a chance.
