### ISSUE TITLE
Cannot delete Hive partitions when WHERE clause has a sub-query 

### ISSUE THREAD

**Issue by lxynov** [trinodb/trino#1310]
Consider a table `tbl` with a partition column `date`. Query `DELETE FROM hive.u_xinlin.tbl WHERE date IN ('2019-08-16');` works but query `DELETE FROM hive.u_xinlin.tbl WHERE date IN (SELECT '2019-08-16');` doesn't work.

Example queries:
```SQL
presto> CREATE TABLE hive.u_xinlin.tbl (id int, date varchar) WITH (format = 'orc', partitioned_by = array['date']);
CREATE TABLE


presto> DELETE FROM hive.u_xinlin.tbl WHERE date IN ('2019-08-16');
DELETE: 0 rows

Query 20190816_190556_00014_4r9e2, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0:01 [0 rows, 0B] [0 rows/s, 0B/s]


presto> DELETE FROM hive.u_xinlin.tbl WHERE date IN (SELECT '2019-08-16');
Query 20190816_190623_00017_4r9e2 failed: This connector only supports delete where one or more partitions are deleted entirely

```

**Comment by Praveen2112** [comment]
I think multi step execution might help here, the sub query will be evaluated and its result will be passed to the coordinator and based on its result we might to a metadata delete. @findepi Your insights ?

**Comment by electrum** [comment]
This is a constant, so it doesn’t require multi step execution. We just need to optimize it so that these two queries have the same plan (I’m surprised they don’t today).

**Comment by Praveen2112** [comment]
For the above query yes we don't need it. But for a generic sub query we might need multi step execution.

**Comment by martint** [comment]
> [...] We just need to optimize it so that these two queries have the same plan (I’m surprised they don’t today).

We don't have many optimizations that constant-fold plan expressions yet. For this case, it's a little more complicated, too, as this is modeled as a semijoin and it ends up with a non-trivial plan involving several operators.

**Comment by esemeniuc** [comment]
Is there a workaround? I'm also experiencing this issue

**Comment by findepi** [comment]
Should have been fixed by @djsstarburst 's https://github.com/trinodb/trino/pull/13926.

Please file a new issue if it is not the case.
