### ISSUE TITLE
Flaky TestDeltaLakeCreateTableStatistics.testMultiFileTable

### ISSUE THREAD

**Issue by raunaqmorarka** [trinodb/trino#13107]
```
io.trino.plugin.deltalake.TestDeltaLakeCreateTableStatistics.testMultiFileTable  Time elapsed: 1.888 s  <<< FAILURE!
java.lang.AssertionError: 
Expecting:
 <1>
to be greater than:
 <1> 
	at io.trino.plugin.deltalake.AbstractTestDeltaLakeCreateTableStatistics.testMultiFileTable(AbstractTestDeltaLakeCreateTableStatistics.java:459)
```
https://github.com/trinodb/trino/runs/7215925256?check_suite_focus=true

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/7736267790

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/7948765971

**Comment by tangjiangling** [comment]
https://github.com/trinodb/trino/runs/8058855336?check_suite_focus=true

**Comment by sopel39** [comment]
https://github.com/trinodb/trino/runs/8203817257?check_suite_focus=true
https://github.com/trinodb/trino/pull/12798
