### ISSUE TITLE
Unable to query Hive views with Trino in AWS EMR & Glue Data Catalog

### ISSUE THREAD

**Issue by Oliver-GSN** [trinodb/trino#13117]
I have tried different versions of both on EMR using Glue Data Catalog as the metastore (presto: 0.245.1-amzn-0, 338, 343. Trino: 360, 378).

The error I receive for Presto is
`java.sql.SQLException: Query failed (#20220624_160314_00014_4kmba): Table 'schema.table' not found at com.facebook.presto.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1841)`

For Trino, I receive `Hive views are not supported`

For Trino, I couldn't use the [legacy or experimental](https://trino.io/docs/current/connector/hive.html#hive-views) solution to read views in any of the versions I used. When I tried to include this configuration the trino-server would not start and returned a failed connection error. I tried to use `SET SESSION hive_views_legacy_translation = true;` and it returned `Session property 'hive_views_legacy_translation' does not exist`

The views I have been trying to query are supported by the legacy and experimental implementation, they aren't defined using HQL syntax but ANSI SQL. In fact, I can take any of the views' create view statement, remove the ` from it and use that to create the view using Presto.

Is there a known incompatibility between Trino and AWS? Maybe with the Data Catalog or EMR?

**Comment by martint** [comment]
> For Trino, I couldn't use the [legacy or experimental](https://trino.io/docs/current/connector/hive.html#hive-views) solution to read views in any of the versions I used. When I tried to include this configuration the trino-server would not start and returned a failed connection error. I tried to use SET SESSION hive_views_legacy_translation = true; and it returned Session property 'hive_views_legacy_translation' does not exist

Which versions produced those errors? Those options have been supported in Trino since at least version 348. The properties have been renamed in 380, though: https://trino.io/docs/current/release/release-380.html#hive-connector

> The views I have been trying to query are supported by the legacy and experimental implementation, they aren't defined using HQL syntax but ANSI SQL.

How did you create those views in the first place? Can you show some examples?

**Comment by Oliver-GSN** [comment]
Trino version 338, 343, 367, and 378. Those are the versions I have tested
This is what I get in version 378, just as the other versions
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/81991489/177874841-d5071f23-fec2-4d71-915b-d1c6efca8f0e.png">

The views are migrated from a Hive Metastore instance to the Glue Data Catalog.
This is the create table statement template of the views I'm trying to query

```
CREATE VIEW `schema`.`view` AS
select
	`table`.`col1`,
	`table`.`col2`,
	`table`.`col3`
from
	`schema`.`table`
where
	`table`.`datetime` = '20220623'
```

**Comment by ebyhr** [comment]
@Oliver-GSN Did you specify `--catalog` option in CLI? What happens if you prepend catalog name? 
```sql
SET SESSION hive.hive_views_legacy_translation = true;
```

**Comment by Oliver-GSN** [comment]
The `hive.views-execution.enabled` configuration worked. Thank you, guys.
I added this configuration as a Software Setting in EMR cluster creation. I'll append the configuration just in case someone add this issue.

```
[
	{
		"classification": "trino-connector-hive",
		"properties": {
			"hive.metastore.glue.datacatalog.enabled": "true",
			"hive.views-execution.enabled": "true"
		}
	}
]
```
