### ISSUE TITLE
Question: how to use Trino Docker image to query files on s3 or local files?

### ISSUE THREAD

**Issue by alexey-milovidov** [trinodb/trino#13134]
I've read that it requires Hive Metastore.
But looks like the Hive "catalog" is not included in the image.
Should I install Hive Metastore manually?
If I should - is there a step-by-step instruction (from zero to query my .parquet file in my public s3 bucket)?
Also, I've read that local files only support querying access logs, not any other data formats (which sounds strange).

**Comment by ebyhr** [comment]
@bitsondatadev's repository has Hive connector introduction including metastore. 
https://github.com/bitsondatadev/trino-getting-started/tree/main/hive/trino-minio

You can use Slack and GitHub discussion when asking a question. I would recommend Slack if you want to talk interactively. 
* https://trino.io/slack.html
* https://github.com/trinodb/trino/discussions
