### ISSUE TITLE
Incorrect line number in SQL error message

### ISSUE THREAD

**Issue by debashis1982** [trinodb/trino#13146]
We are using trino-jdbc `v363` to query hive and one thing we have noticed is that for a multi line SQL query the line number displayed in case of a missing object error is not correct. For example in a query like 
```
select 
* 
from 
abc
limit 10
```
the error is
```
SQL [select * from abc limit 10 ]; Query failed (#20220708_173907_00380_m8xtf): line 3:3: Table 'hive.default.abc' does not exist
```
`hive-jdbc` driver on the other hand displays the line number correctly as `FAILED: SemanticException [Error 10001]: Line 4:0 Table not found 'abc'` There could be other scenarios where this is happening that I am not aware of. Interestingly though if it is a syntax error the line number displayed is correct. For example if I misspell `from`:
```
select 
* 
fro
abc
limit 10
```
The error shows the correct line number
```
SQL [select * fro abc limit 10 ]; Query failed (#20220708_174349_00393_m8xtf): line 3:1: mismatched input 'fro'. Expecting: ',', 'EXCEPT', 'FETCH', 'FROM', 'GROUP', 'HAVING', 'INTERSECT', 'LIMIT', 'OFFSET', 'ORDER', 'UNION', 'WHERE', 'WINDOW', <EOF>
```
trino CLI on the other hand displays the correct line numbe
![image (1)](https://user-images.githubusercontent.com/11267855/178349843-ba568803-3d3e-4dc3-b041-0b85d336f40b.png)
r

**Comment by ebyhr** [comment]
@debashis1982 I can't reproduce the issue on 363 & upstream. I suspect the Java code doesn't contain `\n` correctly. Could you please share your Java code?

**Comment by debashis1982** [comment]
@ebyhr We use jOOQ(https://www.jooq.org/) library to execute queries and fetch results. Here is a main program that shows the output having incorrect line number
<img width="1088" alt="Screen Shot 2022-07-12 at 9 10 51 AM" src="https://user-images.githubusercontent.com/11267855/178510482-a39d67ce-238b-4e79-aef5-54b1db788090.png">

When I do not use JOOQ and just use java.sql.Statement to execute query I get the correct line number
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/11267855/178511620-d826051d-454a-4903-ae7c-1690e1f0bdf8.png">
This does not happen if I use `hive-jdbc` driver instead of `trino-jdbc` driver

**Comment by ebyhr** [comment]
@debashis1982 I would recommend asking JOOQ. The query was changed in their library.
