### ISSUE TITLE
Create table as ... with no data is not copying comment

### ISSUE THREAD

**Issue by indra-cloudwall** [trinodb/trino#13163]

**Comment by indra-cloudwall** [comment]
actually comment is also not copied with all create table as ... commands, not limited to "no data"

**Comment by ebyhr** [comment]
We can inherit source table's comment if the query uses single table, but it doesn't work in case of multiple source tables.

**Comment by indra-cloudwall** [comment]
Sorry if it was not clear, I meant each columns' comments was not copied even if it is single table

**Comment by findepi** [comment]
`CREATE TABLE t AS <subquery> [WITH NO DATA]` can be used to create a table from a query results.
Query results do not include table/column comments, nullability information, etc.
The additional WITH NO DATA clause makes the statement do _less_ (just schema, no data), it won't make the statement to copy more (eg column comments).

See `LIKE` clause in `CREATE TABLE` https://trino.io/docs/current/sql/create-table.html as an alternative.

**Comment by bachng2017** [comment]
it looks like that CTL also does not copy the original comment. Did I miss something ?

**Comment by findepi** [comment]
@bachng2017 that's a separate issue.
