### ISSUE TITLE
Cannot connect to discovery server for refresh (trino/general)

### ISSUE THREAD

**Issue by fujiqiu** [trinodb/trino#13177]
When I start the worker node to connect to the coordinator it tells me that the discovery service cannot be connected
<img width="712" alt="image" src="https://user-images.githubusercontent.com/30720738/178976671-17edc683-3692-449b-be0f-9277cb065437.png">

<img width="702" alt="image" src="https://user-images.githubusercontent.com/30720738/178976803-1394fd38-9fbb-49f0-9247-a5e26c9618e4.png">

coordinator:
<img width="807" alt="image" src="https://user-images.githubusercontent.com/30720738/178977069-ffbef38a-6886-4d3a-97dd-bed42bc7ecb5.png">
worker:
<img width="807" alt="image" src="https://user-images.githubusercontent.com/30720738/178977213-ac22b692-fa29-4fbc-a08f-bf6d1b497b6e.png">

**Comment by naveenp2708** [comment]
@fujiqiu  How this issue resolved, i am getting the same error
