### ISSUE TITLE
How to implement runtime data anonymization in Trino?

### ISSUE THREAD

**Issue by AlvinWo** [trinodb/trino#13173]
I'm thinking about implementing runtime data anonymization in Trino.

step 1. after the analyzer finishes its work, we get the analysis object and call an internal data governance service to check whether the columns are PII(personally identifiable information) related
step 2. when the query planner generates its initial query plan, we would like to write a new optimizer to modify the query plan, adding additional joins, or replace the PII columns with anonymization expressions or function calls.

I'm wondering does this solution make sense? How to modify the query plan in the step 2? We'll add new expressions and function calls in the query plan but the new functions may not be resolved by the analyzer.

**Comment by Praveen2112** [comment]
Hi !! Trino allows us to configure a column masking for a specific column i.e a column could be translated into a function calls or anonymization expressions or can be referred from an additional joins. We need to implement the following method `getColumnMasks` (we could pass the translation as a `String`  as a part of `expression` in `ViewExpression`) in  `SystemAccessControl` (for all catalogs) or `ConnectorAccessControl` (for a specific connector). The engine will perform the parsing and the necessary query plan changes.

Let us know if this satisfies your requirements or do we need further functionalities to it.


Feel free to join our [Slack community](https://trino.io/slack.html) and we can discuss it further in #dev channel

**Comment by AlvinWo** [comment]
Will try correlated queries.
