### ISSUE TITLE
Split expression ST from IR

### ISSUE THREAD

**Issue by martint** [trinodb/trino#13184]
Currently, the IR is a hybrid of dedicated PlanNodes and syntax tree expressions to represent operations over scalar values. Using the SQL syntax tree has a number of downsides:
* Excessive syntactic sugar that the optimizer needs to understand
* Lack of typing information or other annotations needed during optimization
* Inability to represent literal/constant values of types that are not defined in the SQL language

The goal of this issue is to complete the split between AST and IR to have the flexibility to evolve both independently based on the separate needs of the parser/analyzer vs planner/optimizer/execution engine.

The high level approach to do it involves:
* Replicating the AST expression hierarchy in a separate IR-specific package
* Update all imports in the planner/optimizer/execution engine to reference the new IR package
* Write a translation layer from AST expressions -> IR expressions (this needs to be done in the TranslationMap class and related machinery)

Some things to consider:
* The ExpressionInterpreter is currently used during analysis and during optimization. We're going to need to separate or fork the implementation -- at least in the short term.
* Same for ExpressionAnalyzer -- the optimizer needs information about expression types. Currently, the only way to obtain them is to re-analyze the expressions during the optimization process. We may need to fork that logic in the short term until we are able to embed typing information in IR expression nodes.
* Some tests currently "cheat" and rely on being able to evaluate expressions constructed directly by parsing SQL syntax. They will need to be adjusted to either 1) construct IR expressions directly, or 2) translate from SQL syntax to IR expressions.

Related slack channel: https://trinodb.slack.com/archives/C03QZMP8ERW/p1658331800778459

# Tasks

* https://github.com/trinodb/trino/pull/13967
* https://github.com/trinodb/trino/pull/14041
* https://github.com/trinodb/trino/pull/13977
* https://github.com/trinodb/trino/pull/14415
* https://github.com/trinodb/trino/pull/14388
* https://github.com/trinodb/trino/pull/14082
* https://github.com/trinodb/trino/pull/13690
* https://github.com/trinodb/trino/pull/13961
* https://github.com/trinodb/trino/pull/20525
* https://github.com/trinodb/trino/pull/20528
* https://github.com/trinodb/trino/pull/20568
* https://github.com/trinodb/trino/pull/20561
* https://github.com/trinodb/trino/pull/20562
* https://github.com/trinodb/trino/pull/20994
* https://github.com/trinodb/trino/pull/20979
* https://github.com/trinodb/trino/pull/20924
* https://github.com/trinodb/trino/pull/20910
* https://github.com/trinodb/trino/pull/20875
* https://github.com/trinodb/trino/pull/20853
* https://github.com/trinodb/trino/pull/20774
* https://github.com/trinodb/trino/pull/20674
* https://github.com/trinodb/trino/pull/20667
* https://github.com/trinodb/trino/pull/20650
* https://github.com/trinodb/trino/pull/20620
* https://github.com/trinodb/trino/pull/20568
* https://github.com/trinodb/trino/pull/21018
* https://github.com/trinodb/trino/pull/21037
* https://github.com/trinodb/trino/pull/21042

**Comment by martint** [comment]
cc @SongChujun

**Comment by SongChujun** [comment]
related to #18

**Comment by findepi** [comment]
cc @kasiafi @sopel39 @losipiuk
