### ISSUE TITLE
Is there a plan for vectorization excution？

### ISSUE THREAD

**Issue by a516072575** [trinodb/trino#13186]
Does Trino community have a vectorization implementation plan? 
Based on c++ or Java vector API

**Comment by raunaqmorarka** [comment]
We plan to update the build to Java 17 in the near future. After that we will be able to use Java vector APIs.
Feel free to continue this discussion on community slack https://trino.io/slack.html

**Comment by hackeryang** [comment]
The vectorization roadmap:  https://github.com/trinodb/trino/issues/14237
