### ISSUE TITLE
[Multi-Versioned Docs] Add Version Dropdown to Trino Docs

### ISSUE THREAD

**Issue by kevinjqliu** [trinodb/trino#13205]
### Problem
I want to see the documentation for older versions of Trino, not just the latest.

[Trino docs](https://trino.io/docs/current/#) defaults to the latest release. 
Given the speed of Trino releases, I am most often not running on the latest version and I’m not sure if the feature I want to use is available in my version.
There is the "[release notes](https://trino.io/docs/current/release.html)" section to see when the new feature was released. But, I have to parse through the release diffs.

### Ask
It would be great to have a way to “time travel” on documentation. I would like to view the v358 version of the documentation.

As part of researching this, it seems like the v358 docs are available in the production website. (https://trino.io/docs/358/).
So adding a version dropdown to navigate the older version docs should help with this use-case.

### Example
Iceberg docs (https://iceberg.apache.org/) make available older versions.
<img width="1494" alt="Screen Shot 2022-07-17 at 10 52 03 AM" src="https://user-images.githubusercontent.com/9057843/179418420-9d349d19-3b67-4b49-a22d-8725d19a49eb.png">

**Comment by findepi** [comment]
I think @mosabua added a version switcher in Starburst docs https://docs.starburst.io/latest/ so will best know what it takes to add one in Trino docs.

**Comment by mosabua** [comment]
Our framework for the docs easily supports this. However there are a few issues with this approach:

* there are way too many releases 
* we have no criteria on which old release should be in the selector, we do not classify releases as different quality or so
* Trino does NOT support any old releases, any fixes or improvements are always only available with new releases, hence only the latest release is used as base for the next release
* documentation for a release does NOT completely reflect the status and features of a release, we do not always document everything we ship in time

As such I suggest NOT to add a version drop down. 

We could add some information on a page somewhere that explains that all docs are available at the version path but I am not even sure we should do that. For reference the gh pages source repo for all docs is at https://github.com/trinodb/docs.trino.io
