### ISSUE TITLE
How to pass "password" file in Official Helm Chart

### ISSUE THREAD

**Issue by ashishjullia** [trinodb/trino#13202]
Hi all, 

I'm trying to use the "[Trino Official Helm Chart](https://github.com/trinodb/charts/tree/main/charts/trino)", I've it all set up and working properly in a k8s cluster with "HTTPS" and "PASSWORD" based authentication "on".

The only thing I can't figure out is, how to pass a "password.db" file instead of "passing a string" as "username:hashed-bcrypt-password-string".

If someone has figured this out, please help me.

**Comment by ashishjullia** [comment]
Closed.

As it seems like the official chart only supports values/configs to be passed via ConfiMap (which is indeed a good approach but sometimes things need more flexibility that can be achieved via volumes)

**Comment by m-ocean-it** [comment]
@ashishjullia Hi there! But you _were_ able to configure authentication by passing a string, right? Because I'm not even past that. Looking for a simple example of how to do it.

I've tried hashing a password with [bcrypt](https://github.com/pyca/bcrypt) and adding the resulting string to the `values.yaml` file like so:

```yaml
server:
  config:
    authenticationType: PASSWORD
auth:
  passwordAuth: "<username>:<hash>"
```

But it din't work: the containers kept crashing.

I guess, I should look into that `htpasswd` thing.

**Comment by ashishjullia** [comment]
@m-ocean-it 

Yes, mine is configured with the following:

```bash
auth: 
  passwordAuth: "user1:<pass-hash-string>\n
                "user2:<pass-hash-string>"
```

**Comment by m-ocean-it** [comment]
Yep, turns out it's described in the [docs](https://trino.io/docs/current/security/password-file.html#creating-a-password-file).

Here's the command to use:
```bash
htpasswd -B -C 10 password.db username
```
Then, the content of `password.db` can be examined with `cat password.db`.

Also, to install `htpasswd` on Ubuntu:
```bash
sudo apt install apache2-utils
```

**Comment by ashishjullia** [comment]
Cool @m-ocean-it

**Comment by m-ocean-it** [comment]
But, still, the container now throws this error:
```
Shared secret (internal-communication.shared-secret) is required when authentication is enabled
```

**Comment by ashishjullia** [comment]
For that you've to pass the following:
```bash
 workers: 2
  node:
    environment: production
    dataDir: /data/trino
    pluginDir: /usr/lib/trino/plugin
  log:
    trino:
      level: INFO
  config:
    path: /etc/trino
    http:
      port: 80
    https:
      enabled: false
      port: 8443
      keystore:
        path: ""
    authenticationType: "PASSWORD"
    query:
      maxMemory: "4GB"
      maxMemoryPerNode: "1GB"
    memory:
      heapHeadroomPerNode: "1GB"
  exchangeManager:
    name: "filesystem"
    baseDir: "/tmp/trino-local-file-system-exchange-manager"
  workerExtraConfig: "internal-communication.shared-secret=<secret>"
  coordinatorExtraConfig: "internal-communication.shared-secret=<secret>"
  ```
  
  Under^ `workerExtraConfig` and `coordinatorExtraConfig` (use the same secret for both). For testing, pass any "string value", you configuration will work fine.

**Comment by m-ocean-it** [comment]
Thank you very much! The weird thing, though, happened: despite not throwing any errors, Trino still allows me to connect without any creds. Neither the query engine, nor the GUI, are protected. In other words, nothing's changed.

Perhaps, it has to do with Ingress. I configured it to accept traffic on port 443 and route it Trino. Perhaps, I should expose Trino at the node level.

**Comment by ashishjullia** [comment]
@m-ocean-it because in order to use the password authentication you need to set up the ssl either on the trino level or at the ingress/lb level.

I believe it's mentioned in their docs.

+ as far as I can remember even if it allows you to connect without the password login even if you've configured it in the values.yml file, you won't be able to view any catalogs configured.

So, to use the password level authentication, you've to setup ssl^ and only then you can see catalogs and work on that.

**Comment by m-ocean-it** [comment]
Yeah... TLS is configured at the Ingress level. Alright, we'll see. Thanks anyway!

**Comment by m-ocean-it** [comment]
Opened an [issue](https://github.com/trinodb/trino/issues/15528#issue-1511138895)
