### ISSUE TITLE
Wrong exception handling in MySQL table statistics for MySQL version 5.7

### ISSUE THREAD

**Issue by geo-aoe** [trinodb/trino#13258]
At this line the contains needs to either be removed or changed to case insensitive: https://github.com/trinodb/trino/blob/master/plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java#L924
On my system with MySQL 5.7 this is the exception message: `java.sql.SQLSyntaxErrorException: Unknown table 'column_statistics' in information_schema [statement:"SELECT 1 FROM INFORMATION_SCHEMA.COLUMN_STATISTICS WHERE 0=1", arguments:{positional:{}, named:{}, finder:[]}]` which doesn't match the searched string `Unknown table 'COLUMN_STATISTICS'` because table name is upper case.

**Comment by findepi** [comment]
cc @hashhar @wendigo

**Comment by ebyhr** [comment]
@geo-aoe Does #13323 fix the failure in your environment? Could you share the details about your MySQL cluster (e.g. distribution)? We may want to add new test environment.
