### ISSUE TITLE
Make engine use concrete Block type depending on Column/Symbol type

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#13267]
- [ ] introduce block adaptation in table scan operator
- [ ] Make Iceberg return `Int128ArrayBlock` for UUID type.

**Comment by sopel39** [comment]
cc @lukasz-stec

**Comment by sopel39** [comment]
In this case UUID will also affect long decimal type.

We could also adapt block to proper type before processing. Should be easy loop with `io.trino.spi.block.Block#writeBytesTo`

**Comment by electrum** [comment]
If we want to make the block type a requirement, we could simply start enforcing. If UUID for Iceberg is the only offending type, we can fix that easily, worst case by adding some specific code in the ORC library for it (which we have avoided but unfortunately it has already snuck in).

**Comment by lukasz-stec** [comment]
I want to start working on this.
The first question is. Do we do block adaptation or do we fail if the block type does not match the preferred type (block type validation)?
I see @electrum prefers the latter. @martint @sopel39 what's your take on this?

I'll add that validation is easier to implement, but not by much.
