### ISSUE TITLE
Query returns potentially incorrect results

### ISSUE THREAD

**Issue by arhimondr** [trinodb/trino#13269]
Query:  https://gist.github.com/arhimondr/bc27b0a81fa0aa979fce4094a424264c

Expected results: https://gist.github.com/arhimondr/a4f55cae4038ed138bb44a6116f3b65d
Actual results: https://gist.github.com/arhimondr/55f939f25fb29126bfc4879f0b0a4102

Query was run on `tpcds.tiny` schema in `HiveQueryRunner`.

The expected results were computed with an older version of Trino (likely 378)

**Comment by arhimondr** [comment]
Diff: 
![image (1)](https://user-images.githubusercontent.com/5570988/180077832-061e2d13-8164-4e3e-a027-3e502dc725e8.png)

**Comment by arhimondr** [comment]
Could've potentially been introduced by https://github.com/trinodb/trino/pull/12548. The query returns results as expected with this PR reverted.

**Comment by sopel39** [comment]
will have fix for this EOD

**Comment by findepi** [comment]
from screenshot

> results_on_agg_optimization

seems like there is a change suspected for causing this. @arhimondr do you have a PR link?

**Comment by arhimondr** [comment]
@findepi There is a chance it might be caused by https://github.com/trinodb/trino/pull/12548. The results changes with the optimization on and off. I had a chance to discuss it with @sopel39 offline, he is currently looking.

**Comment by sopel39** [comment]
Fix https://github.com/trinodb/trino/pull/13290
