### ISSUE TITLE
Document incorrect results caution about Alluxio

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#13270]
`TestHiveAlluxioMetastore.testGetPartitionsWithFilter` always fails by incorrect results (#13252). We should document the behavior or (and) disable the integration by default and prepare a flag as @findepi mentioned in  https://github.com/trinodb/trino/pull/13252#discussion_r925752626

Also, the Alluxio metastore integration seems not to be maintained well in the connector. If we don't recommend using it, it would be better to mention about that in [this page](https://trino.io/docs/current/connector/hive-alluxio.html)

**Comment by findepi** [comment]
The test results suggest use of Alluxio integration may result in incorrect query results.
Since the integration with Alluxio is effectively unmaintained, and seems unused, I think we should remove it.

cc @apc999 @kokosing

**Comment by colebow** [comment]
Is it worth documenting in the meantime, or should I just wait for it to be removed?

**Comment by findepi** [comment]
@colebow  please go ahead

**Comment by electrum** [comment]
Closing since Alluxio metastore is no more.
