### ISSUE TITLE
Queries return different results when run over identical partitioned and non partitioned datasets

### ISSUE THREAD

**Issue by arhimondr** [trinodb/trino#13296]
[tpcds/etl/q15](https://github.com/trinodb/trino-verifier-queries/blob/main/src/main/resources/queries/tpcds/etl/q15.sql),[tpcds/etl/q32](https://github.com/trinodb/trino-verifier-queries/blob/main/src/main/resources/queries/tpcds/etl/q32.sql),[tpcds/etl/q48](https://github.com/trinodb/trino-verifier-queries/blob/main/src/main/resources/queries/tpcds/etl/q48.sql),[tpcds/etl/q62](https://github.com/trinodb/trino-verifier-queries/blob/main/src/main/resources/queries/tpcds/etl/q62.sql),[tpcds/etl/q92](https://github.com/trinodb/trino-verifier-queries/blob/main/src/main/resources/queries/tpcds/etl/q92.sql) return different results when run over a non partitioned and a partitioned TPC-DS dataset. 

Partitioning scheme is as following:

- `catalog_returns` on `cr_returned_date_sk`
- `catalog_sales` on `cs_sold_date_sk`
- `store_returns` on `sr_returned_date_sk`
- `store_sales` on `ss_sold_date_sk`
- `web_returns` on `wr_returned_date_sk`
- `web_sales` on `ws_sold_date_sk`

Tested on sf100 and sf10000 schemas.

**Comment by sopel39** [comment]
@arhimondr do you know when it started happening?

**Comment by arhimondr** [comment]
@sopel39 It seems like quite a while. I precomputed the expected results a couple of months back and realized only now that results are different for partitioned and non partitioned data sets. I haven't tried with fault tolerant execution disabled though. There's a small chance it might be fault tolerant execution specific.

**Comment by sopel39** [comment]
@przemekak is it something we've seen also?

**Comment by arhimondr** [comment]
@sopel39 That's the first thing I checked. The TPC-DS tables don't contain DOUBLE columns on their own. It is possible to get results processed as DOUBLE when certain functions return double on, say, integer inputs (e.g.: `avg`). However the queries mentioned (e.g.: [tpcds/etl/q15](https://github.com/trinodb/trino-verifier-queries/blob/main/src/main/resources/queries/tpcds/etl/q15.sql)) does not invoke any functions. 

I'm planning to spend more time on it today to get to the bottom of it.

**Comment by arhimondr** [comment]
False alarm. Partitioned and non partitioned tables have different column order (partitioning column comes last in partitioned tables). Queries mentioned are sensitive to column order.
