### ISSUE TITLE
User credentials are not validated when creating connection in JDBC driver

### ISSUE THREAD

**Issue by debashis1982** [trinodb/trino#13341]
We are using Trino V363 JDBC driver to connect to Hive and it looks like it lets you create a SQL connection even if the user credentials (userId and password) are invalid.

Code
```
Class.forName("io.trino.jdbc.TrinoDriver");
            String userName = "invalid_user";
            String password = "invalid_password";
            Connection connection = DriverManager.getConnection(jdbc, userName, password);
            System.out.println("connection is valid:"+connection.isValid(5));
```
Output
```
connection is valid:true
```

**Comment by ebyhr** [comment]
Currently, `TrinoConnection.isValid` verifies only whether it's closed or not. We may want to execute a query (e.g. `SELECT 1`) to check the connection. 

https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/Connection.html#isValid(int)
> Returns true if the connection has not been closed and is still valid. The driver shall submit a query on the connection or use some other mechanism that positively verifies the connection is still valid when this method is called.
The query submitted by the driver to validate the connection shall be executed in the context of the current transaction.

**Comment by ebyhr** [comment]
@debashis1982 I sent #13359

**Comment by nineinchnick** [comment]
Duplicates #8542
