### ISSUE TITLE
Support `DATABASE` as an alias for `SCHEMA`

### ISSUE THREAD

**Issue by osscm** [trinodb/trino#13363]
Spark and Hive support `SCHEMA` as an alias for `DATABASE`

Spark: https://docs.databricks.com/spark/latest/spark-sql/language-manual/sql-ref-syntax-ddl-create-database.html
Hive: https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-Create/Drop/AlterDatabase

In Trino also we can support `DATABASE` as an alias. This will bring parity between Trino and Spark.
Especially for the Iceberg and Hive table format for which Spark is typically used for Ingestion/ETL/Long running ad-hoc queries, and Trino is used for fast and ad-hoc querying.

So, for those use-cases, users can use the `DATABASE` at both places.
Hive Thrift APIs also support `database`.

Though RDBMS like Oracle and DB2 treats `database` and `schema` differently. 
IMO, it's mainly because `database` is treated as an object that manages physical and logical structures (https://docs.oracle.com/cd/B19306_01/server.102/b14220/intro.htm#:~:text=Database%20Application%20Development-,Oracle%20Database%20Architecture,the%20problems%20of%20information%20management.)

I believe adding ALIAS will be backward compatible and depending on the use-cases, allow users to use the keyword (like for Spark+Iceberg/Hive+Trino user can use `database`)

**Comment by osscm** [comment]
cc @vgankidi @RussellSpitzer

**Comment by osscm** [comment]
cc @findepi @martint @alexjo2144 @findinpath @ebyhr

We believe can help the community.
Appreciate it, if you can please provide your input? 

We are happy to contribute, thanks a lot!

**Comment by martint** [comment]
It is not a goal of Trino to have parity with Spark or Hive. There are already many incompatibilities between the Hive/Spark dialects vs Trino's, so adding an alias for SCHEMA is not going to have any material impact without also tackling all the other differences, which we don't have any plans to do. 

Also, we try to stay as close to the ANSI/ISO SQL specification, and only deviate when there's no other choice -- using DATABASE as an alias for SCHEMA is not part of the SQL specification. There's not a very strong argument for making an exception in this case.
