### ISSUE TITLE
Flaky TestSpilledJoinQueries.testJoinWithScalarSubqueryInOnClause running for 46.33m.

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#1337]
https://api.travis-ci.com/v3/job/226568366/log.txt

**Comment by kokosing** [comment]
`count++`

```
2019-08-19T11:56:31.297-0500 WARNING No test started or completed in 5.00m. Running tests:
	io.prestosql.tests.TestDistributedSpilledQueries::testLateralJoin running for 33.73m
	io.prestosql.tests.TestDistributedSpilledQueries running for 45.47m.
```

The case here is that there is no event recorded that test finished, there is no thread running the test and testng does not end.

**Comment by s2lomon** [comment]
Another occurrence of same behaviour:

`2019-08-23T08:52:42.303-0500 WARNING No test started or completed in 5.00m. Running tests:
	io.prestosql.tests.TestDistributedSpilledQueries running for 45.01m
	io.prestosql.tests.TestDistributedSpilledQueries::testTopN running for 21.24m.`

**Comment by findepi** [comment]
It hasn't been observed for a while. Please reopen with a new link & output transcript if you see this again.

**Comment by sopel39** [comment]
This is actual bug in join spill.

**Comment by sopel39** [comment]
Redundant to: https://github.com/trinodb/trino/issues/7454
