### ISSUE TITLE
[JWT] `requiredAudience` validation fails if `aud` claim contains multiple audiences

### ISSUE THREAD

**Issue by rstyp** [trinodb/trino#13442]
Currently, JWT `aud` claim is validated as below in `io.jsonwebtoken.impl.DefaultJwtParser`:

`
if (!expectedClaimValue.equals(actualClaimValue))
`

As `requiredAudience` is set as String, this equals comparison fails if `aud` claim contains multiple audiences in JWT token.

`
  "aud": ["trino", "oauth2_client_id"]
`

**Comment by osscm** [comment]
cc @alexjo2144 @findinpath

**Comment by findinpath** [comment]
@lukasz-walkiewicz @s2lomon

**Comment by lukasz-walkiewicz** [comment]
That's right, JWT authentication supports only single-value audience claims. @rstyp Would you be interested in contributing support for multi-value audience claims?

**Comment by rstyp** [comment]
@lukasz-walkiewicz Thanks for checking. Sure, I can work on `support for mutil-value audience claims`.
