### ISSUE TITLE
Unable to get query details

### ISSUE THREAD

**Issue by njalan** [trinodb/trino#13444]
My version is presto sql 340 and below is my config :
coordinator=true
http-server.authentication.type=PASSWORD
node-scheduler.include-coordinator=false
http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=xx.jks
http-server.https.keystore.key=xxxx
http-server.http.port=8084
query.max-stage-count=400
query.stage-count-warning-threshold=400
query.max-memory=80GB
query.max-memory-per-node=5GB
query.max-total-memory-per-node=6GB
task.max-drivers-per-task=16
discovery-server.enabled=true
exchange.http-client.request-timeout=120s
query.max-run-time=300s
scheduler.http-client.max-requests-queued-per-destination=4096
task.max-worker-threads=30
query.max-history=200
query.min-expire-age=30m
discovery.uri=http://xxxxxx8084

When I try to get query details and I got Query not found

By the way I have deployed event listener.

**Comment by ebyhr** [comment]
What happens if you deploy without the event listener?

**Comment by njalan** [comment]
In my testing environment it is working fine without the event listener

**Comment by ebyhr** [comment]
What event listener are you using? Implemented by yourself?

**Comment by njalan** [comment]
Yes, just the statistics and write into mysql

**Comment by ebyhr** [comment]
Can you provide the code and stacktrace? Otherwise, it's hard to debug the issue.

**Comment by njalan** [comment]
When I deployed  event listener in testing environment and it is also able to get query statistics on web ui

**Comment by njalan** [comment]
@ebyhr  I deployed exact the same jar on the testing environment and it is working fine. Do you know what can be the issues on the production

**Comment by njalan** [comment]
I got the reason Because the use can only see his own query details and not able to see others

**Comment by ebyhr** [comment]
By the way, you can ask questions in GitHub discussions https://github.com/trinodb/trino/discussions or community Slack https://trino.io/slack.html from next time.

**Comment by njalan** [comment]
I added in slack but no response.
