### ISSUE TITLE
SHOW CREATE TABLE and SHOW COLUMNS return invalid type when column/field name is a reserved keyword

### ISSUE THREAD

**Issue by Vayu** [trinodb/trino#13483]
If name of a columns or a field is a reserved keyword, Trino should quote it when printing type in `SHOW COLUMNS FROM table`, but it does not. It also does not do it for column names in `SHOW CREATE TABLE`.

E.g.
```
CREATE TABLE test_type (
    x1 ROW("exists" BOOLEAN),
    "exists" VARCHAR
 )
```

`> SHOW CREATE TABLE test_type;`
```
CREATE TABLE test_type (
    x1 ROW("exists" boolean),
    exists varchar
 )
```
Note missing quotes on the column name. Running this create table statement will result in an error `line 3:5: mismatched input 'exists'. Expecting: 'LIKE', <identifier>`

`> SHOW COLUMNS FROM test_type;`
```
 Column |        Type         | Extra | Comment
--------+---------------------+-------+---------
 x1     | row(exists boolean) |       |
 exists | varchar             |       |
(2 rows)
```
Note missing quotes on the column name and field name.

**Comment by findepi** [comment]
`SHOW COLUMNS` doesn't promise that you can pick what you get there and paste back into SQL.
Let's focus this issue on `SHOW CREATE TABLE` which is expected to produce valid SQL.
@Vayu can you please adjust the title accordingly? If you also want SHOW COLUMNS changed, I'd create two separate issues.

**Comment by Vayu** [comment]
@findepi what's the benefit of fixing one and not the other? Presumably they both could use the same code and both are used for different kinds of introspection.

Other things that are impacted are `SELECT data_type FROM iceberg.information_schema.columns WHERE table_name = 'test_type' AND column_name = 'x1'` (which is probably the same code as SHOW COLUMNS). And `TYPEOF(x1)` (using Row.getDisplayName).

Arguably, textual representations of types returned by the engine should always be valid SQL types.
