### ISSUE TITLE
ORC UUID value endianness

### ISSUE THREAD

**Issue by lukasz-stec** [trinodb/trino#13480]
Currently, trino stores `UUID` columns in `orc` in the `binary` format. 
The values are written and read using native byte order on a given machine, which means if the file is written on a big-endian machine and read on a little-endian machine the data will be corrupted.

More details in this conversation https://github.com/trinodb/trino/pull/13454#discussion_r936435327

**Comment by martint** [comment]
Trino does not work on big-endian machines, so this might not be an issue in practice.

**Comment by lukasz-stec** [comment]
theoretically, trino could read data created by some other means on a big-endian machine.
In practice, there are no big-endian contemporary machines so that won't happen soon.

**Comment by findepi** [comment]
> trino could read data created by some other means on a big-endian machine.

That would be other means' responsibility to write a valid ORC file, with UUID values in the right byte order.

I don't think there is anything TBD here. Should I close the issue?

**Comment by lukasz-stec** [comment]
> That would be other means' responsibility to write a valid ORC file, with UUID values in the right byte order.
There is no "right" byte order as ORC does not support UUID directly.

If we assume that trino only works on little-endian machines, we can close this issue.

**Comment by martint** [comment]
> There is no "right" byte order as ORC does not support UUID directly.

There should be one defined, otherwise, data containing UUIDs is not be portable. Then, whichever way we go, the code needs to make sure it writes it according to that encoding. Machine endianness doesn't play a part.

**Comment by martint** [comment]
According to the UUID RFC (https://datatracker.ietf.org/doc/html/rfc4122), values are supposed to be written in "network byte order" (i.e., big endian)

**Comment by electrum** [comment]
This whole conversation is completely off track. This is about UUID in Iceberg ORC files, so the only thing that matters [the Iceberg specification for UUID values](https://iceberg.apache.org/spec/#appendix-b-32-bit-hash-requirements):

> UUIDs are encoded using big endian. The test UUID for the example above is: `f79c3e09-677c-4bbd-a479-3f349cb785e7`. This UUID encoded as a byte array is: `F7 9C 3E 09 67 7C 4B BD A4 79 3F 34 9C B7 85 E7

Also, Trino only runs on little endian machines. Trino will [refuse to start](https://github.com/trinodb/trino/blob/71e11c35cb9342db67bc4bf60b00575224148c62/core/trino-main/src/main/java/io/trino/server/TrinoSystemRequirements.java#L65) if not little endian and [so will Slice](https://github.com/airlift/slice/blob/db02631a74de268be1dbe02d65352c5fa3d8ef13/src/main/java/io/airlift/slice/JvmUtils.java#L38).
