### ISSUE TITLE
Trino don't support String data type IN query 

### ISSUE THREAD

**Issue by sumit-gupta-sgt** [trinodb/trino#13492]
I see some issue  If the column type of pinot table is integer and SQL (select * from tablename where colname in ('1', '2') limit 10) puts this column in the condition as a string, there will be an error in trino. But pinot works normally.

I see same issue with other catalog like Kudu and TiDB too.

**Comment by martint** [comment]
If the type of `colname` is `integer`, then you need to do `... WHERE colname IN (1, 2)`. There's no implicit cast between `integer` and character types.

**Comment by sumit-gupta-sgt** [comment]
@martint if you do direct query on data source, they support implicit cast, Trino has any plan to support ?
