### ISSUE TITLE
`TimestampWithTimeZoneType#getObjectValue` should respect session timezone

### ISSUE THREAD

**Issue by yittg** [trinodb/trino#13491]
Given `Type#getObjectValue` gets an object representation of the type value in the block position. And the value is returned to the user.

Shall we  should respect the session timezone for `TimestampWithTimeZoneType#getObjectValue`?

Currently it uses the timezone extracted from the block.

WDYT @findepi @ebyhr ?

**Comment by dain** [comment]
I'm not sure what you mean.  The TimestampWithTimeZoneType is an exact UTC instance in a specific timezone, so every value can have a different time zone.  This is defined in the SQL spec.  So, if we were to use the session time zone, what would we do with that zone?

**Comment by yittg** [comment]
Thanks @dain for your explanation. I think you are right.

Share my case here:
Write a ts with time zone field into iceberg, and get the corresponding UTC ts while reading no matter which time zone i set via `SET TIME ZONE`.
The time zone associating with the data is lost from writing to reading. 

I guess it's the connector or file format implementation issue instead of the `TimestampWithTimeZoneType#getObjectValue`.

**Comment by martint** [comment]
See related discussion: https://github.com/trinodb/trino/issues/13157

**Comment by findepi** [comment]
Closing as answered (by https://github.com/trinodb/trino/issues/13157)
