### ISSUE TITLE
Trino should allow password authentication (LDAP) in insecure HTTP

### ISSUE THREAD

**Issue by vqcuong** [trinodb/trino#13512]
I'm using trino to serve our data analytical queries. The problem I got is that I must setup seft-signed TLS before setup authentication using LDAP. For me, I want to setup LDAP authentication to enable decentralization and restriction to end users better.
I'm currently run trino cluster on k8s environment and I want to use ingress for expose domain for trino instead of setup local seft-signed certification hardly.
In this case, I think we should allow trino use authentication without TLS. I think many companies don't public their internal services like trino to the internet so they can use http communication without any potential. If any want to enable https they can add them later by using k8s ingress or nginx later.

**Comment by Praveen2112** [comment]
Hi !! Would the steps mentioned [here](https://trino.io/docs/current/security/tls.html#use-a-load-balancer-to-terminate-tls-https) helps you ? Short summary if we add this config property `http-server.process-forwarded=true` then we should be allowing password authentication for insecure HTTP provided they are forwarded.

**Comment by vqcuong** [comment]
Hi @Praveen2112 thank you so much.
