### ISSUE TITLE
Document experimental annotation in SPI developer guide

### ISSUE THREAD

**Issue by colebow** [trinodb/trino#13520]
Docs for #13302

**Comment by mosabua** [comment]
Check with @nineinchnick and maybe help review his developer guide PRs

**Comment by colebow** [comment]
Probably not necessary, the javadoc does all it needs to. I thought we wanted plugins to also use @Experimental but the point is that it's used for SPI features, not plugin features, and we probably don't need to try to educate plugin developers to use it
