### ISSUE TITLE
Flaky `TestIcebergParquetConnectorTest.testReadMetadataWithRelationsConcurrentModifications`

### ISSUE THREAD

**Issue by Praveen2112** [trinodb/trino#13556]
This test fails with timeout. 

https://github.com/trinodb/trino/runs/7725557488?check_suite_focus=true

**Comment by ebyhr** [comment]
`TestIcebergOrcConnectorTest.testReadMetadataWithRelationsConcurrentModifications` also failed https://github.com/trinodb/trino/runs/7760222236

**Comment by nineinchnick** [comment]
Saw this in https://github.com/trinodb/trino/runs/7763461397?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/7773115785?check_suite_focus=true

**Comment by sopel39** [comment]
https://github.com/trinodb/trino/runs/7811310998?check_suite_focus=true

**Comment by sopel39** [comment]
https://github.com/trinodb/trino/pull/13650
