### ISSUE TITLE
Flaky `TestHiveAlluxioMetastore`

### ISSUE THREAD

**Issue by Praveen2112** [trinodb/trino#13557]
`TestHiveAlluxioMetastore` requires an alluxio and hadoop setup (defined by `docker-compose`) and we are unable to start the environment as hadoop port (50070) is already used by a different resource. 

Additional details : https://github.com/trinodb/trino/runs/7724855779

**Comment by findepi** [comment]
Can we perhaps remove the Alluxio integration?

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/7747794646?check_suite_focus=true

**Comment by findepi** [comment]
🎉 , this is fixed. https://github.com/trinodb/trino/pull/18195
