### ISSUE TITLE
Distinguish creation of new table and registering existing table operations in Delta Lake connector

### ISSUE THREAD

**Issue by aksakalli** [trinodb/trino#13568]
I am using the [Delta Lake connector](https://trino.io/docs/current/connector/delta-lake.html) for reading existing delta tables in s3 exclusively. When I run a create table statement, I expect to already have an existing transaction log for the given location before creating the table. I have to check everytime manually if the transaction log exists in order to avoid creating an erroneous transection logs in the path for `dummy bigint`. I think it's need to have an explicit property for creating delta table from existing logs that makes the `CREATE TABLE` statement fail in case there is no existing transaction log.

From the documentation:

> If the specified location does not already contain a Delta table, the connector automatically writes the initial transaction log entries and registers the table in the metastore. 

I don't want Trino to silently create a transaction log if I intent to create a table from existing logs.

**Comment by alexjo2144** [comment]
We could add a `register_table` procedure that would do this

**Comment by krvikash** [comment]
Started working on this.
