### ISSUE TITLE
Parquet allocates large byte array when reading column chunk

### ISSUE THREAD

**Issue by luohao** [trinodb/trino#1357]
Parquet reader reads the whole column chunk in one byte[] and slice them into pages. The column chunk can be very large and creates tons of humongous objects. G1 can't handle these humongous objects and eventually result in hight GC overhead.

cc: @zhenxiao

**Comment by zhenxiao** [comment]
nice catch. Let me take a look

**Comment by tooptoop4** [comment]
gentle ping

**Comment by raunaqmorarka** [comment]
Fixed by https://github.com/trinodb/trino/pull/15374
