### ISSUE TITLE
Union query may blocked after remove grouped execution

### ISSUE THREAD

**Issue by ans76** [trinodb/trino#13652]
grouped execution been removed since #12916, perform union query may blocked. set `node-scheduler.max-splits-per-node=10` and `node-scheduler.max-pending-splits-per-task=1` can easily reproduce the query stuck. also query can run success if we make `NodeScheduler#canAssignSplitToDistributionNode` always return true. test on both 388 and 392

```
hive.test_ds.tbl  [partitioned by event bucket by id]

WITH test_data AS
  (SELECT id,tag
   FROM
     (SELECT
        id,tag
      FROM hive.test_ds.tbl WHERE event = 'e1'
      UNION ALL
      SELECT 
        id,tag
      FROM hive.test_ds.tbl WHERE event = 'e2')
   GROUP BY 1,
            2)
SELECT COUNT(1) FROM test_data
```

**Comment by ans76** [comment]
@sopel39

**Comment by sopel39** [comment]
cc @skrzypo987

**Comment by sopel39** [comment]
I cannot reproduce unfortunatelly
