### ISSUE TITLE
[JVM] Allocation stalls with ZGC

### ISSUE THREAD

**Issue by jpohanka** [trinodb/trino#13660]
**Trino version**: 392

## Description

We have been using the default G1GC garbage collector for our trino clusters in our production environment. However, as the usage of our clusters increased in both concurrency and processed data,
we started to experience higher number of coordinator crashes due to memory issues.

In finding a solution for this problem, we decided to switch to ZGC, which promised better performance in higher-concurrency use cases. Initially, ZGC proved to be more stable in cases of usage spikes (frequent case in our deployments). However, soon we observed that after a longer usage under mild (but constant) concurrency load, the cluster performance decreased dramatically, up to the point, where we had to do periodic restarts in order to maintain our performance SLAs.

Upon checking the node logs, we found that when using ZGC, periods of **allocation stalls** are created, causing the performance degradation of our Trino clusters. The following is an example log generated by ZGC:

```
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.654s][info][gc] Allocation Stall (Query-20220812_072359_15696_jcf6c-481) 315.305ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.654s][info][gc] Allocation Stall (dispatch-executor-1) 288.598ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.654s][info][gc] Allocation Stall (Query-20220812_072359_15693_jcf6c-495) 608.775ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.654s][info][gc] Allocation Stall (task-management-0) 763.730ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.654s][info][gc] Allocation Stall (http-worker-347) 508.772ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.654s][info][gc] Allocation Stall (dispatcher-query-28) 610.574ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.654s][info][gc] Allocation Stall (execution-query-purger) 741.826ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.654s][info][gc] Allocation Stall (Query-20220812_072359_15691_jcf6c-657) 917.566ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.654s][info][gc] Allocation Stall (Query-20220812_072359_15694_jcf6c-670) 505.529ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.655s][info][gc] Allocation Stall (http-worker-412) 609.176ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.655s][info][gc] Allocation Stall (task-management-3) 417.047ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.655s][info][gc] Allocation Stall (Query-20220812_072359_15695_jcf6c-548) 500.958ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.656s][info][gc] Allocation Stall (http-worker-149) 382.338ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.656s][info][gc] Allocation Stall (http-worker-324) 382.046ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.655s][info][gc] Allocation Stall (http-worker-579) 808.813ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.656s][info][gc] Allocation Stall (query-management-0) 321.597ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.655s][info][gc] Allocation Stall (http-worker-782) 859.915ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.655s][info][gc] Allocation Stall (drain-state-query-manager) 765.133ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.654s][info][gc] Allocation Stall (Query-20220812_072359_15692_jcf6c-676) 701.954ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.656s][info][gc] Allocation Stall (query-management-1) 321.554ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.655s][info][gc] Allocation Stall (Announcer-3) 703.846ms
trino_test_trino-coordinator.1.76bikgr3bu48@jp    | [1282.685s][info][gc] GC(384) Garbage Collection (Allocation Stall) 2612M(85%)->2292M(75%)
```

## Issue reproduction

For reproducing the issue, we provide in this [repository](https://github.com/datasapiens/reproducible-examples/tree/main/github_issues/trinodb/zgc_allocation_stalls) the following:

- an example Trino Docker swarm deployment
- an example `locustfile`, that will send simple query requests (we use TPC-DS SF1 for local testing) to the example local Trino deployment

To reproduce the issue, first deploy the example Docker swarm deployment by running the following command:

```
source deploy.sh
```

Next, initiate the Locust load test by running the following command:

```
locust
```

In the Locust UI, set the number of users to 20 and the spawn rate to 1.

A similar behavior of gradual performance decrease should occur within few minutes of load testing.

In our example deployment, we use the following JVM configuration:

```
-server
-verbose:gc
-Xlog:gc
-Xmx3G
-XX:+UseZGC
-XX:InitialRAMPercentage=80
-XX:MaxRAMPercentage=80
-XX:G1HeapRegionSize=32M
-XX:+ExplicitGCInvokesConcurrent
-XX:+ExitOnOutOfMemoryError
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-XX:ReservedCodeCacheSize=512M
-XX:PerMethodRecompilationCutoff=10000
-XX:PerBytecodeRecompilationCutoff=10000
-Djdk.attach.allowAttachSelf=true
-Djdk.nio.maxCachedBufferSize=2000000
-XX:+UnlockDiagnosticVMOptions
-XX:+UseAESCTRIntrinsics
```

This configuration is the default Trino configuration with the exception of the choice of the garbage collector, where we use ZGC.

The following are the output plots from Locust, showing the performance degradation via gradual decrease in query throughput and increase in query latency:

![locust_test_output_01](https://user-images.githubusercontent.com/17990081/184433128-c66cbea2-b21b-424f-bbc8-b8ce5f814a2b.png)

In the load test, that produced these results, we used 20 concurrent workers and a spawn rate of 1.

Has anybody experienced similar behavior with ZGC or other garbage collectors ?

**Comment by dain** [comment]
My guess is you have an actual memory leak, and are legitimately running out of memory. In collectors like ZGC that spread collections out with allocations, the system just slows down as you run out of memory.  I've also hear that these kinds of garbage collectors need much larger free memory for managing the GC itself, so I'd try decreasing the memory allocated to Trino queryies.

**Comment by dain** [comment]
Actually `-Xmx3G` is your problem... You are trying to run on a machine that is way to small.  Trino was not designed to run on cell phones.  Also ZGC was designed for very large heaps 512GB+.  At 3GB you could likely use any GC.

**Comment by jpohanka** [comment]
@dain Thank you for the feedback. Sorry for the confusion with the `-Xmx3G` , this configuration is only for the reproducible example to be run locally. In our production environment, we use instances with a memory size of 128 GB and 144 GB. And the allocation stalls happen there as well.

I will try to investigate further and look for a way to enable usage for heaps smaller than 512GB.

**Comment by hashhar** [comment]
IMO ZGC is not likely to be useful for Trino. Trino is not an "interactive" low-latency web service. The thing which Trino benefits from is more throughput instead of low latency. I experimented with ZGC and G1 for almost 6 months in the past and the conclusion was that for heaps smaller than 256GB it did not help at all and we actually saw decreased performance (in terms of number of queries finished per unit time).

Also as a test you should see how much performance ZGC eats up compared to something like the Parallel collector. You'll be surprised.

Is there a specific reason why you want to use ZGC?

**Comment by electrum** [comment]
Thanks for providing a reproducible example. If you run the same test on G1, do you see consistent response times over a long time period (an hour or more)? Does it reproduce on ZGC if you use a larger heap such as 8GB or 16GB?

**Comment by electrum** [comment]
According to [this](https://bugs.openjdk.org/browse/JMC-6203):

> If we see ZGC allocation stalls, that mean that the allocation rate is higher than what ZGC can keep up with, and you’re running out of available heap space; ZGC has slowed down the application threads.

Some potential causes:

* Not enough heap for the workload. ZGC might have more overhead and require more headroom.
* Memory leak in Trino. Running the same workload with G1 should prove or disprove this.
* Not enough GC threads. You can try setting `-XX:ConcGCThreads=<number>`.

**Comment by b-slim** [comment]
I wonder at what scale the G1GC fails, We run Trino at a very large scale (IMO at least), and we see a very stable coordinator with a QPS of 30 and above and a worker pool of 500 nodes.

This is the JVM opts we are using maybe it will help.
```
-server
-Xmx200G
-Xms200G
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+UseGCOverheadLimit
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-agentpath:/export/apps/trino/latest/resources/libjvmkill-f30c886-JDK-11_0_8-msft.so
-verbose:gc
-XX:HeapDumpPath=/grid/a/tmp/trino/
-Djava.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
-Xlog:gc*,age*:var/log/gc-%t.log:time,level,tags:filecount=5,filesize=2147483648
-XX:+ExitOnOutOfMemoryError
-XX:ErrorFile=var/log/java_error.log
-XX:MaxGCPauseMillis=500
-XX:-UseBiasedLocking
-XX:ReservedCodeCacheSize=512M
-Djdk.nio.maxCachedBufferSize=2097152
-XX:PerMethodRecompilationCutoff=10000
-XX:PerBytecodeRecompilationCutoff=10000
-Dlog.output-file=/export/apps/trino/data/var/log/server.log
-Dnode.data-dir=/export/apps/trino/data
-Dnode.id=9c7c0c3b-d3ff-5ac0-6546-c4833c641683
-Dnode.environment=ltx1_holdem04
-Dlog.enable-console=false
```

**Comment by findepi** [comment]
Previously ZGC wasn't recommended and wasn't as good as G1.
This could have changed in recent JDK releases. Trino now requires Java 22.
Let's close this old issue and have a new one if relevant.
