### ISSUE TITLE
Iceberg batch file operations for expire_snapshots and remove_orphan_files

### ISSUE THREAD

**Issue by erichwang** [trinodb/trino#13692]
In the current Iceberg connector, file deletions are done serially one at a time. From my testing with Iceberg-S3/Glue, this nets to around 2 files deleted per second. The last time I had to run an expire_snapshot over about 2 months worth of data, it took around 24 hours to complete the query, which is way too long -- and this is just maintenance for a single table. This is especially important as we start to bring in more real-time workloads which by definition need to create more smaller files. Another downside of long query times for expire_snapshots is that it dramatically increases probability that the query will fail or be cancelled and create orphaned files that need to be cleaned up.

Under the covers, we are using the single delete API, but S3 actually supports batch deletes up to 1000 at a time, so in theory we could do this 1000x faster, and make these calls pretty much negligible to consider.

**Comment by erichwang** [comment]
Alternatively, we should see if we can parallelize this more.

**Comment by findinpath** [comment]
Probably related https://github.com/trinodb/trino/pull/13974

**Comment by findepi** [comment]
`remove_orphan_files` being fixed in https://github.com/trinodb/trino/pull/14383
while `expire_snapshots` in https://github.com/trinodb/trino/pull/14434

**Comment by homar** [comment]
`expire_snapshot` is merged ;)

**Comment by homar** [comment]
and I see `remove_orphan_files` is merged as well so I think we can close this one

**Comment by alexjo2144** [comment]
I think this is the last one we need: https://github.com/trinodb/trino/pull/14908

**Comment by erichwang** [comment]
Awesome! Thanks, I am so excited to get to try this
