### ISSUE TITLE
Add comment columns to information_schema.tables

### ISSUE THREAD

**Issue by hovaesco** [trinodb/trino#13705]
Currently, there is no way to get comments from `tables` ~and `columns`~ tables from information_schema. For instance, Snowflake exposes these comment columns in respective tables in information_schema. It would be very useful for integrations like dbt which requires it to fully support persisting docs functionality.

**Comment by hashhar** [comment]
cc: @martint 

We do expose this under `system.jdbc.tables` it seems. Not sure why there is a difference.

**Comment by findepi** [comment]
Column comments are available

https://github.com/trinodb/trino/blob/03d8e5abc686c5c4a9f96ca14db07e2aed880174/core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaTable.java#L41

https://github.com/trinodb/trino/blob/7f954b57dbeb8b967e270c40902196183a914cfb/core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaPageSource.java#L268

Table comments (remarks) are not available in `information_schema.tables`.
Updating issue description to reflect this.

**Comment by findepi** [comment]
The reason why `information_schema.tables` has `table_comment` column is some tools compatibility

https://github.com/trinodb/trino/blob/03d8e5abc686c5c4a9f96ca14db07e2aed880174/core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaTable.java#L50

It would be very expensive to populate this fields, hence it's not populated (all NULLs).

That's why we have them in a separate table `system.metadata.table_comments`.

> It would be very useful for integrations like dbt which requires it to fully support persisting docs functionality.

What's the use-case which requires dbt to list tables along with the comments?
Can it join to `system.metadata.table_comments` to get them?
Note that in general this is going to be prohibitively expensive, so this should be done for one table (or at most for a handful of tables) at a time.

**Comment by martint** [comment]
> We do expose this under system.jdbc.tables it seems. Not sure why there is a difference.

The schema of `information_schema` tables and views is defined by the SQL specification. For extensions, we have dedicated tables under the system catalog. `system.jdbc.tables`, in particular, is designed to expose all the information needed by the JDBC driver.

**Comment by hovaesco** [comment]
Thanks for pointing out on hidden `comment` columns from `information_schema.columns`.

Use case is a functionality called [persist_docs](https://docs.getdbt.com/reference/resource-configs/persist_docs) which saves table-level and column-level comments which are then used in [dbt docs](https://docs.getdbt.com/docs/building-a-dbt-project/documentation). 

Technically speaking, it's feasible to join `system.metadata.table_comments` with `information_schema.tables`. However, I'm afraid about backwards compatibility since `system` catalog could require additional privileges. A query to get all details to generate docs currently uses only `information_schema`. 

From the description above it looks like that it's going to be a costly operation but the best solution from dbt-trino perspective would be to populate a `table_comment` column from `information_schema.tables`.

**Comment by findepi** [comment]
> populate a `table_comment` column from `information_schema.tables`.

This is no-go from perf perspective.

For example, listing tables in Hive is O(1) operation (counting the HMS calls, likely the dominant factor).
Listing tables with comments is a O(n) operation (where n is number of tables). 
In the past we've seen that O(n) for `information_schema.tables` is prohibitively expensive.

**Comment by hovaesco** [comment]
Thanks for detailed explanation. I'm good to close the issue.

**Comment by d33play** [comment]
Trino v479: `remarks` column (`system.jdbc.tables`) value is still NULL.

```
SELECT table_cat, table_schem, table_name, table_type, remarks
FROM system.jdbc.tables
WHERE TABLE_CAT='iceberg_cat' and  TABLE_SCHEM LIKE 'shema1' and table_name='my_table1';
```

In the era of AI and governance, it’s an important issue.
