### ISSUE TITLE
File based access control issue with partitions query

### ISSUE THREAD

**Issue by igorcalabria** [trinodb/trino#13718]
Hi, given an access control file like this
```json 
[
...
  {
	    "catalog": "catalog",
	    "schema": "schema",
	    "table": "(my_table)",
	    "user": "user",
            "privileges": ["SELECT"]
  }
]
```

Shouldn't user also have permission to run `SELECT * FROM catalog.schema.my_table$partitions`? It seems odd having to explicitly need something like `"table": "(my_table|my_table\\$partitions)"`

**Comment by findepi** [comment]
The system access control is not aware of "system tables" (the `$...` tables). They have no special handling in the engine from security perspective.
Also, there are many system tables types across connectors. Some are "benign" (like `$partitions`) and some potentially less so (like `$files` in Iceberg).
