### ISSUE TITLE
JdbcMetadata#listTableColumns is broken when there are two tables which differ by letter casing

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#1373]
Suppose you have two tables:
`Orders`,
`orders`

1) `io.prestosql.plugin.jdbc.JdbcMetadata#listTableColumns` will call `JdbcMetadata#listTables` when prefix does not contain table name.
2) However `io.prestosql.plugin.jdbc.BaseJdbcClient#getTableNames` will then fetch table names for both tables and build `SchemaTableName` from them.
3) `SchemaTableName` will lowercase the names (making them effectively the same name)
4) `io.prestosql.plugin.jdbc.JdbcMetadata#listTableColumns` will fail trying to put duplicate key into `columns` map `io/prestosql/plugin/jdbc/JdbcMetadata.java:176`.

**Comment by Praveen2112** [comment]
I guess this will come under this issue #17

**Comment by sopel39** [comment]
I think other connects are also affected (e.g. kudu or accumulo)

**Comment by hashhar** [comment]
Closing in favour of #17.
