### ISSUE TITLE
CockroachDB connector

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#13771]
- [ ] #8317

**Comment by mingfang** [comment]
PR https://github.com/trinodb/trino/pull/8317 has been closed but not merged.
Is there hope for progress on this?

**Comment by mosabua** [comment]
As mentioned in the PR .. anybody willing to run with it is free to take my initial version and improve or start fresh. I used the postgresql connector as a base fyi, but wont have time to move this forward.

**Comment by findepi** [comment]
No need to track the issue. If someone wants to contribute, they can do this without one.
