### ISSUE TITLE
implement local cache on trino

### ISSUE THREAD

**Issue by Jay-ju** [trinodb/trino#13815]
ref：[Introduce caching file system](https://github.com/prestodb/presto/pull/13644)
 prestodb has implemented this feature， can we apply this on trino. In addition，we can add  result cache on query‘s level，this is import for bi scene

**Comment by findepi** [comment]
Please see the docs for caching on the local file system: https://trino.io/docs/current/connector/hive-caching.html

**Comment by Jay-ju** [comment]
> Please see the docs for caching on the local file system: https://trino.io/docs/current/connector/hive-caching.html

it seems that depnd on rubix，but rubix’s architect is complex, and rubix won't update since 2020, so i prefer choosing lib like  presto on raptorx/alluxio,
