### ISSUE TITLE
Hive: Join Tables with Big and Small Table.

### ISSUE THREAD

**Issue by blank-manash** [trinodb/trino#13848]
### Discussed in https://github.com/trinodb/trino/discussions/13847

<div type='discussions-op-text'>

<sup>Originally posted by **blank-manash** August 25, 2022</sup>
## Context

We have two tables, A and B. The size of A is very large (over 500 GB) and the size of the other table B is small (about 44 rows)
We are executing a select query in three different ways

* Select Query on A
* Select Query on B
* Select Query on A LEFT JOIN B

## Issue

It is observed that the first and second queries execute very fast. But however, the third query takes much more time than expected. I was curious to discuss how the architecture works to allocate resources to such kinds of queries. And if there are any ways to speed it up.
</div>

**Comment by findepi** [comment]
Closing in favor of https://github.com/trinodb/trino/discussions/13847
