### ISSUE TITLE
Support CREATE FUNCTION and SQL-defined functions

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#13851]

**Comment by martint** [comment]
This is dependent on and related to https://github.com/trinodb/trino/issues/8

**Comment by tooptoop4** [comment]
https://github.com/prestodb/presto/pull/13481

**Comment by findepi** [comment]
from @martint 

> We’re actively working on it. It should hopefully be available in the next few releases

**Comment by martint** [comment]
This is now available in version 431
