### ISSUE TITLE
Trino ver 393 doesn't have compatiblity with old docker version ( JVM can't start )

### ISSUE THREAD

**Issue by shtoma** [trinodb/trino#13891]
In Trino 393 with older docker ver ( docker://18.6.3 ), the container can't start JVM.

```
$ java -X
[0.019s][warning][os,thread] Failed to start thread "VM Thread" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
```

This looks the issue of temurin . 
https://github.com/trinodb/trino/pull/13522

https://github.com/adoptium/temurin-build/issues/2976
Can trino support it ?

**Comment by findepi** [comment]
from @dain  on slack https://trinodb.slack.com/archives/CGB0QHWSW/p1662612713776499?thread_ts=1662612510.911199&cid=CGB0QHWSW

> That version was released 2019-02-19.  In general, this project doesn’t have the resources to support really old stuff like this.  I suggest you upgrade your docker to a newer version.
