### ISSUE TITLE
Enable authorized databases option in MongoDB connector

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#1398]
Currently, if the user doesn't have `listDatabases` privileges, we get not-authorized error from MongoDB. MongoDB version 4.0.5 added `authorizedDatabases` option to list only databases which the user have the permission. I think this option will resolve this issue.

https://docs.mongodb.com/manual/reference/command/listDatabases/#listdatabases-behavior

**Comment by Deninc** [comment]
+1

**Comment by findepi** [comment]
> This issue was closed by #14988, and that PR is proposed for revert in #15652.

revert closed.
