### ISSUE TITLE
Add checker for JUnit `@Test` annotation in overridden tests

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#14027]
TestNG runs overridden tests regardless of `@Test` annotation, but JUnit silently ignores such tests. It would be nice to have a checker to enforce the annotation since there're many overridden tests in Trino especially for `BaseConnectorTest` and `BaseConnectorSmokeTest`. 
```java
public abstract class BaseTest
{
    @Test
    public void test()
    {
        assertEquals(1, 1);
    }
}

public class TestBaseTest
        extends BaseTest
{
    // TestNG runs this test, but JUnit doesn't
    @Override
    public void test()
    {
        assertEquals(1, 2);
    }
}
```

Tested in https://github.com/trinodb/trino/pull/14025
Relates to https://github.com/trinodb/trino/issues/9378 and https://github.com/junit-team/junit5/issues/960

**Comment by ebyhr** [comment]
Relates to https://github.com/trinodb/trino/pull/18588#discussion_r1287412357
cc: @findinpath

**Comment by hashhar** [comment]
Seems https://www.baeldung.com/junit-5-extensions can be used to write something that we need.

**Comment by martint** [comment]
This is done
