### ISSUE TITLE
Document column mapping mode in Delta Lake connector

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#14051]
There're 3 column mapping mode in Delta Lake. Though these table property isn't exposed to users at this time, it would be nice to document it.
* none: default
* id: Use Parquet field id (≠column position)
* name: Use Parquet field name

https://github.com/delta-io/delta/blob/master/PROTOCOL.md#column-mapping

**Comment by Ankan0011** [comment]
I think this issue is already been completed. Please have a look at the [link](https://trino.io/docs/current/connector/delta-lake.html?highlight=delta+lake#table-properties). If some changes are left out please clarify, maybe I can help.
Thanks.
