### ISSUE TITLE
Iceberg predicate pushdown for date/time columns and year() function

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#14078]
Like https://github.com/trinodb/trino/pull/14011 but for year() function.

- for date, and timestamp this can be done in the engine
- for timestamp with time zone this can be done in a connector

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/14011 adds some tests for `year()` in `BaseIcebergConnectorTest` (with TODOs)

**Comment by osscm** [comment]
@findepi thanks for creating this issue!
We are looking to support this feature and others to improve the performance of the Iceberg queries.

for my understanding:

looks like following tests shows that timestamp is supported in the predicate pushdown ?https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java#L579

and here: https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java#L1654-L1655
its showing `year(d)` is pushed down

Do we already support other date functions like `month/day/hour`, didn't find test-cases which uses `month()` directly but found being used using `date_trunc('month', d)` https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java#L1415-L1416

**Comment by findepi** [comment]
> looks like following tests shows that timestamp is supported in the predicate pushdown ?https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java#L579

@osscm i don't know where this link was intended to point to.
Note that links without commit hash are subject to evolve as new changes are added to the code base.

> Do we already support other date functions like `month/day/hour`

nope. These functions, in isolation, are not very useful for the pushdown, i.e. they cannot be used to derive ranges of allowed values.

> didn't find test-cases which uses month() directly but found being used using date_trunc('month', d)

Yes, `date_trunc` is supported (since https://github.com/trinodb/trino/pull/14011)
