### ISSUE TITLE
trino BigQuery connector does not work with external service-accounts

### ISSUE THREAD

**Issue by erikerlandson** [trinodb/trino#14083]
We have configured a BigQuery connector, and for billing reasons, we need to use it with a service account created in a google project that is different than the project that the BQ data are living in.  When we use this service-acct, we cannot `select` from any tables. We can list schemas and tables, and even `describe` tables. But actually querying the table contents fails, with a "table not found" error.

As an experiment, we created a service-acct owned by the same google-project that the BQ tables live in, and that works correctly, so the problem appears to be with service accounts that are owned by other projects.

**Comment by erikerlandson** [comment]
Link to trino slack thread:
https://trinodb.slack.com/archives/CGB0QHWSW/p1661871177930719

**Comment by erikerlandson** [comment]
cc @hashhar

**Comment by erikerlandson** [comment]
Checking in to see if there is a fix for this.

**Comment by hashhar** [comment]
I have some partial fix but I've yet to prepare something to run CI against to verify it works for all operations we support.
