### ISSUE TITLE
Re-enable testCreateNamespaceWithLocation / testUseUniqueTableLocations in Iceberg TestTrinoRestCatalog

### ISSUE THREAD

**Issue by nastra** [trinodb/trino#14119]
Re-eable after https://github.com/apache/iceberg/pull/5737 is fixed and released

**Comment by nastra** [comment]
https://github.com/apache/iceberg/pull/5737 has been integrated into Iceberg 1.1.0, so I have fixed this as part of https://github.com/trinodb/trino/pull/13294

**Comment by findepi** [comment]
> so I have fixed this as part of #13294

That PR isn't merged, let me reopen

**Comment by nastra** [comment]
@findepi just FYI that this doesn't affect `master` as the issue only existed on https://github.com/trinodb/trino/pull/13294. Now that Iceberg 1.1.0 made it into Trino, I fixed the issue as part of https://github.com/trinodb/trino/pull/13294 so in this case I think it might make sense to close the issue, wdyt?
