### ISSUE TITLE
Do not limit number of tasks to the number of nodes for bucketed tables in fault tolerant execution

### ISSUE THREAD

**Issue by arhimondr** [trinodb/trino#14144]
Current the number of tasks is limited by the number of nodes as the buckets come preassigned to a specific node

**Comment by beapirate** [comment]
In case anyone else runs into this. We have successfully worked around this issue with this configuration in 394 release by disabling optimization of bucketed table reads.

Please do not make this the default setting in your cluster unless you've actually run into issues and you've compared how this setting affects your query plans.

`optimizer.use-table-scan-node-partitioning=false
`
It is also available as session property. If possible, only override this for queries where you run into issues with task sizing.

`set session use_table_scan_node_partitioning=false;`

**Comment by arhimondr** [comment]
https://github.com/trinodb/trino/pull/15627
