### ISSUE TITLE
Improve Iceberg deletes when an entire file can be removed

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#14165]
With the fix applied on https://github.com/apache/iceberg/pull/5568  available on Iceberg 0.14.1 we can take another attempt of dealing with the use case:

> If a delete would remove all rows from an individual file,
> remove the whole file, rather than writing a position delete.

Related PR https://github.com/trinodb/trino/pull/13485

Issue to keep in mind while testing the functionality https://github.com/trinodb/trino/issues/12843

**Comment by findepi** [comment]
> Issue to keep in mind while testing the functionality #12843

We should have a regression test for that already added when we closed that issue, right?

**Comment by alexjo2144** [comment]
Merged
