### ISSUE TITLE
DROP VIEW prepared statement fails when view qualified name requires quoting

### ISSUE THREAD

**Issue by lucasdlemos** [trinodb/trino#14196]
The parser is throwing `ParsingException` for valid `DROP VIEW IF EXISTS` query. Although properly quoted, it seems the quotes aren't being considered.

For example:

- This statement throws `ParsingException`
```
PREPARE statement1 FROM DROP VIEW IF EXISTS "catalog-test"."schema"."table"
```
- While the same statement for tables succeeds:
```
PREPARE statement1 FROM DROP TABLE IF EXISTS "catalog-test"."schema"."table"
```
- If we replace dashes with underscores in the 1st statement it also succeeds:
```
PREPARE statement1 FROM DROP VIEW IF EXISTS "catalog_test"."schema"."table"
```

**Comment by hashhar** [comment]
cc: @kasiafi similar to https://github.com/trinodb/trino/pull/11171 but for a different visitor.

**Comment by findepi** [comment]
@lucasdlemos do you plan to make a PR for this?

**Comment by lucasdlemos** [comment]
Unfortunately I can't in the near term @findepi.

**Comment by albericgenius** [comment]
@findepi @hashhar 
i could work on this issue. here is my PR #14276 
Thanks
