### ISSUE TITLE
Switch between distinct aggregation, mark distinct operator and OptimizeMixedDistinctAggregations automatically

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#14216]
Decide automatically (perhaps using CBO) which way of computing distinct aggregation to use. Potential rules:
* use mark distinct when number of distinct aggregations is low (e.g. 1 or 2). Using of mark distinct increases data shuffle across cluster.
* use `OptimizeMixedDistinctAggregations` when number of distinct aggregations is high. `OptimizeMixedDistinctAggregations` will limit number of intermediate stages and also allows for partial aggregation to be evaluated.

**Comment by sopel39** [comment]
cc @lukasz-stec

**Comment by lukasz-stec** [comment]
> also allows for partial aggregation to be evaluated.

I believe partial aggregation supports `MarkDistinct` too

**Comment by sopel39** [comment]
> I believe partial aggregation supports MarkDistinct too

It does, but the problem is when you have multiple distinct aggregations, e.g: `aggr(distinct a), aggr(distinct b), ..`. Then for each you have to create `MarkDistinctNode` shuffling the data across cluster

**Comment by sopel39** [comment]
Yup. This is what I meant

**Comment by sopel39** [comment]
Might be related to https://github.com/trinodb/trino/issues/15106, cc @lukasz-stec

**Comment by sopel39** [comment]
@lukasz-stec can we close it?
