### ISSUE TITLE
Fix Iceberg split calculations when metadata has offsets

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#14241]
@alexjo2144 on slack

>  If your Iceberg metadata has `splitOffsets` defined for the file you are reading the target-size will be ignored and you'll get one split per offset. 

target-size refers to `read.split.target-size` table property

I believe we need to disable that. That just doesn’t make sense, unless the split sizes calculated this way are “reasonable”

**Comment by findepi** [comment]
The offsets metadata may be useful for _calculating_ splits, but cannot be taken _directly_ as the split boundaries.

**Comment by electrum** [comment]
Are these the actual file boundaries, i.e. the stripe offsets in ORC? If so, then we should use them directly, at least for ORC, since we don’t support sub-splitting within an ORC stripe. Not sure about Parquet. Going smaller means empty splits.

**Comment by osscm** [comment]
@findepi 

 > target-size refers to `read.split.target-size` table property 
I believe we need to disable that. That just doesn’t make sense, unless the split sizes calculated this way are “reasonable”

You want to disable it in the `Iceberg` library, if the `splitOffsets` are available?

**Comment by vgankidi** [comment]
These are row group boundaries in Parquet too which cannot be split further, we could combine them if larger splits are required.

**Comment by alexjo2144** [comment]
Yeah, I think the question here was really if a user requests larger splits via a session property or config property if they should get it.

**Comment by findepi** [comment]
Per my understanding of https://github.com/trinodb/trino/issues/14241#issuecomment-1255399036 -- nothing to do here.
