### ISSUE TITLE
Can trino set threshold scan data size from hive connector？

### ISSUE THREAD

**Issue by sjx782392329** [trinodb/trino#14250]
My presto version is 344 prestosql.
Now i found some presto queries scan so much data from hive.
I want to limit max scan data input size per query into presto memory, but i don't know how to set this config.

**Comment by hashhar** [comment]
See `query.max-scan-physical-bytes` server config property or `query_max_scan_physical_bytes` catalog level session property.

Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there.

**Comment by hashhar** [comment]
cc: @mosabua seems the config is not documented. you can find it and explanation in https://trino.io/docs/current/release/release-339.html

**Comment by sjx782392329** [comment]
> 

Which channel in Slack I should use ,I have joined Trino Slack. But now i can't found the channel for discusses.

**Comment by tangjiangling** [comment]
> I want to limit max scan data input size per query into presto memory, but i don't know how to set this config.

> See query.max-scan-physical-bytes server config property or query_max_scan_physical_bytes catalog level session property.

This configuration is the answer to your question.

For example, you can set `query.max-scan-physical-bytes=1GB` in `etc/config.properties`, which means that all queries will not read more than 1GB of table data, or you can execute `set session query_max_scan_ physical_bytes='1GB'`, which means that only queries related to the current `session` will be limited to no more than 1GB of read data.

> I have joined Trino Slack. But now i can't found the channel for discusses.

> Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there.

What @hashhar means is that if you have further questions, you can ask in the [#troubleshooting](https://trinodb.slack.com/archives/CGB0QHWSW) channel (it's a better place to ask questions and get a quicker response)
