### ISSUE TITLE
Docker container run: ERROR: Java is not installed

### ISSUE THREAD

**Issue by sgreszcz** [trinodb/trino#14269]
trying to run trinodb/trino docker container:

```
Unable to find image 'trinodb/trino:latest' locally
latest: Pulling from trinodb/trino
2b55860d4c66: Pull complete
49a58ffb4a94: Pull complete
8889343dc9d4: Pull complete
5c321d92dfdb: Pull complete
b332f4b6f417: Pull complete
64d8fd27718e: Pull complete
afa6fc563a25: Pull complete
16a679c60568: Pull complete
ab30786d3152: Pull complete
Digest: sha256:792c6ba972aff568ab5df03eab50ed0f0c2308cd7f7daac8e134b6faeb20b40a
Status: Downloaded newer image for trinodb/trino:latest
+ launcher_opts=(--etc-dir /etc/trino)
+ grep -s -q node.id /etc/trino/node.properties
+ launcher_opts+=("-Dnode.id=${HOSTNAME}")
+ exec /usr/lib/trino/bin/launcher run --etc-dir /etc/trino -Dnode.id=fcf4f30162f6
ERROR: Java is not installed

**Comment by nineinchnick** [comment]
Might be related to https://github.com/adoptium/containers/issues/214

**Comment by hashhar** [comment]
See also https://github.com/adoptium/containers/issues/215#issuecomment-1142046045 for workaround.

But note that other up-to-date images will also start failing on the older Docker version.

**Comment by hashhar** [comment]
Closing as answered but feel free to re-open if you still run into with upgraded Docker.

Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there on #troubleshooting.

**Comment by wangxiaoying** [comment]
Had the same issue. Upgrade docker to the latest version works.

**Comment by cobolbaby** [comment]
Not supported in version 20.10.7, but supported in version 20.10.24.

**Comment by Chaho12** [comment]
FYI. similar issue happens when using m4
- https://forums.docker.com/t/image-builds-fail-on-new-macbook-despite-working-fine-on-prior-apple-silicon/145772/8
- https://github.com/corretto/corretto-21/issues/85#issuecomment-2537803123
