### ISSUE TITLE
trino access control check every column of the input tables but not the actual select colums

### ISSUE THREAD

**Issue by gjhkael** [trinodb/trino#14263]
After the Analyzer, trino use the AccessControl to authenticate, but just after analyze of the ast tree, the columns do not prune, all columns of the input tables need to authenticate, it doesn't make sense and has performance issues.
PS. the above problem is same of the "ColumnMask".

**Comment by findepi** [comment]
This is per SQL spec.
A query access all the columns user asked for, even if not all the columns are _required_ to compute the final query result.
