### ISSUE TITLE
Iceberg metadata location gets changed with newer Trino versions

### ISSUE THREAD

**Issue by NMonnerSans** [trinodb/trino#14299]
Hello all!

We are experiencing an issue when trying to upgrade Trino from version 386 to 397. We are using Iceberg tables with default `write.metadata.path` configurations, pointed at our S3 data warehouse bucket. Our S3 path's for our tables look like `s3://dw_bucket/prd_{table}_iceberg/`, and metadata is saved in the default `metadata` directory in that prefix. When trying newer versions (397 and 395 have been tried and present this issue, 391 is the newest version we have tried which doesn't), we have generic internal errors on every type of query pointing at some of our tables, because the metadata_location of the Iceberg table gets changed to `s3://dw_bucket/prd_{table}_iceberg//metadata/{metadata_file}.json` randomly. We have worked around this issue by manually rewriting the metadata_location property correctly using Spark, but we do not know what causes it, and can't guarantee it won't spuriously happen again.

For reference, we are building Trino from the official Docker image, and using Nomad to create containers and scale our production clusters.

**Comment by hashhar** [comment]
cc: @alexjo2144 @findepi

**Comment by findepi** [comment]
@NMonnerSans this sounds like an incorrect behavior.
Can you share steps one can use to reproduce the problem?

**Comment by NMonnerSans** [comment]
@findepi I'm not entirely sure, because as I said, it happens spuriously with some of the tables, but not others, but we created tables with Iceberg 0.13.1, with a location in an S3 prefix as shown above (`s3://dw_bucket/prd_{table}_iceberg/`). Inside that prefix, there are the usual `data` and `metadata` default locations. We use Livy as our Spark client on EMR for most of the ETLs, but for most of the tables we populate using Trino, after upgrading we start to see readErrors pointing to a wrongly located metadata file, where the path is right except for the `//`. I thought it could be a weird parsing issue when the table location ended with `/`, but we don't have a `/` in our location. 

After the upgrade, when doing a `SHOW TBLPROPERTIES`, the tables have a metadata location with the `//` issue, but the previous_metadata_location doesn't have that problem. It can be manually SET right, but we don't have any guarantee that it will stay that way, and manually altering metadata doesn't seem like a safe thing to do.

**Comment by NMonnerSans** [comment]
I forgot to say that this behavior can also be seen in v 395, which we also tried upgrading to and had to rollback also.

**Comment by alexjo2144** [comment]
Also possibly related: https://github.com/trinodb/trino/pull/13984 cc: @ebyhr

**Comment by alexjo2144** [comment]
> we have generic internal errors on every type of query pointing at some of our tables

Can you share the full stack trace of some of these errors?

**Comment by ebyhr** [comment]
Does this issue happen even when you create a new table?

**Comment by findepi** [comment]
@NMonnerSans are you using Glue catalog, or HMS?

**Comment by NMonnerSans** [comment]
We are using the Hive Metastore, with Iceberg, and as far as I can tell, new tables weren't affected, but as I said, this happened only on some of the tables, and we have yet to determine why (since all our table creations occurred at the same time, and are somewhat similar)

**Comment by findepi** [comment]
@NMonnerSans fwiw i tried to blindly repro this with https://github.com/trinodb/trino/pull/14346 but couldn't.

you may have more luck using the product test env (`testing/bin/ptl env up --environment singlenode-spark-iceberg`)
such synthetic repro steps would be best

**Comment by ebyhr** [comment]
I could reproduce the issue by manually updating `TABLE_PARAMS` table in metastore:
```sql
UPDATE TABLE_PARAMS SET PARAM_VALUE = 's3://test-bucket/tpch/test-3d213ef555ea424aad36b256178f40ba//metadata/00001-1fa828be-534d-44c2-a7b1-c276e57fe241.metadata.json' 
WHERE tbl_id = 9 AND param_key = 'metadata_location';
```

I think version 393 and 394 stores the metadata location like above (`//metadata`) and #13984 was insufficient for existing table cases. I will try fixing it.

**Comment by ebyhr** [comment]
@NMonnerSans Can you confirm if #14389 resolves the issue in your environment?

**Comment by electrum** [comment]
This issue is tricky. S3 is not a file system, so it doesn’t canonicalize double or repeated slashes. Thus, it’s possible that there are actually double slashes in the S3 path. While this looks strange, this is completely valid. 

We actually had to add handling in the Iceberg connector for this case, since Athena was writing such data and metadata. If we simply remove repeated slashes when reading the metadata, we won’t be able to read data files written under such locations.

I’m not sure I understand the reported issue, so I don’t know what to suggest here.
