### ISSUE TITLE
split_to_map function issue

### ISSUE THREAD

**Issue by ankitgupta8888** [trinodb/trino#14316]
Hive to Presto conversion issue

Hive Function
`SELECT str_to_map('p1=v1&url=https://www.abc.com/cart?a1=b1&p2=v2','&','=')
`
`Hive output : {"p1":"v1","p2":"v2","url":"https://www.abc.com/cart?a1=b1"}
`
Presto equivalent:
`SELECT split_to_map('p1=v1&url=https://www.abc.com/cart?a1=b1&p2=v2','&','=')
`
`Presto output:  presto error: Key-value delimiter must appear exactly once in each entry. Bad input: 'url=https://www.abc.com/cart?a1=b1'`

**Comment by ebyhr** [comment]
I suppose that is the expected behavior per https://github.com/trinodb/trino/blob/5738a1b/core/trino-main/src/test/java/io/trino/operator/scalar/TestStringFunctions.java#L548.
