### ISSUE TITLE
Coordinator out of memory due to too many FileStatuses been cached

### ISSUE THREAD

**Issue by xiacongling** [trinodb/trino#14313]
Recently, some of our Trino coordinators were out of memory and crashed after several times of full GCs. After analyze the heapdump, we find a lot of `HdfsLocatedFileStatus` instances on the heap.

The coordinator is a small instance with MaxHeapSize of 24GB. At the moment the coordinator shuts down, there are several big queries on Hive, and each of them scans nearly 1 million files.

Finally, we find that these FileStatuses come from `TransactionScopeCachingDirectoryLister` which is introduced in  https://github.com/trinodb/trino/pull/11650. There are some issues:

- a property `hive.per-transaction-file-status-cache-maximum-size` can be used to control the cache size, but no description is found in the latest document;
- the default value of `hive.per-transaction-file-status-cache-maximum-size` is 1,000,000, which means that a query can use up to  7GB (~7KB per FileStatus) of coordinator heap for caching HDFS file information, maybe a smaller value is more reasonable?
- there is no way to disable the cache (the minimum size of cache is 1)

**Comment by findepi** [comment]
> Finally, we find that these FileStatuses come from `TransactionScopeCachingDirectoryLister` which is introduced in #11650.

cc @sopel39 @raunaqmorarka

**Comment by sopel39** [comment]
Fixed via https://github.com/trinodb/trino/pull/14408
