### ISSUE TITLE
Simplify or remove scripts to load TPCH tables in BigQuery

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#14338]
BigQuery connector supports `CREATE TABLE AS SELECT` and `INSERT` statements now. We can simplify or remove scripts to load TPCH tables https://github.com/trinodb/trino/tree/master/plugin/trino-bigquery/bin

**Comment by hashhar** [comment]
I have something similar I did last night - I'll send a PR. Also it seems all data types that TPCH uses are supported right now.
