### ISSUE TITLE
Bump `jts` to a newer version

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#14343]
At the time of this writing, the library jts https://github.com/locationtech/jts is on `1.19.0`

Trino is using `1.16.1`

Along the way, address 

```
TODO: Remove if/when https://github.com/locationtech/jts/issues/684 is fixed.
```

https://github.com/trinodb/trino/blob/fe608f2723842037ff620d612a706900e79c52c8/lib/trino-geospatial-toolkit/src/main/java/io/trino/geospatial/GeometryUtils.java#L209

cc: @JamesRTaylor

**Comment by rohitemmadishetty** [comment]
Hi, I would like to contribute to this issue. Please let me know good starting point.
