### ISSUE TITLE
passing extra credential 

### ISSUE THREAD

**Issue by twokindswater** [trinodb/trino#14364]
`trino-cli` has `extra-credential` option. and `go-client`, `python-client` also have that.
but `trino-cli` has one different from `go-client`, `python-client`. `trino-cli` only have `extra-credential` header when build query request.
so `trino-cli` does not work when i use `extra-credential` to passing sts token. but others is okay. because token is to be set in header every request. 

i suggest `trino-cli` `extra-credential` option to be set every request not only build query request.

**Comment by findepi** [comment]
The extra credentials are consumed by the server where it accepts the query submission.
They are not used after that, e.g. not used when polling for query results.

Perhaps it could be useful to document such things on https://trino.io/docs/current/develop/client-protocol.html, what do you think @djsstarburst ?

**Comment by djsstarburst** [comment]
> Perhaps it could be useful to document such things on https://trino.io/docs/current/develop/client-protocol.html

Yes, that makes sense.  I'll add it to my list.

**Comment by hashhar** [comment]
We should fix the sending of extra credential on every request in other clients as well since it seems unnecessary and adds confusion like shown here (since server won't do anything with it) - cc: @nineinchnick @hovaesco

**Comment by findepi** [comment]
@hashhar do you know which clients are to be fixed?

**Comment by findepi** [comment]
i guess this says Go and Python clients are affected. if so, let's have specific issues in their repos.
