### ISSUE TITLE
mapping sql server uniqueidentifier to trino uuid

### ISSUE THREAD

**Issue by EminUZUN** [trinodb/trino#14456]
Hello,

In sql server connector, uniqueidentifier is becoming varchar. Can you change it to uuid?

Regards,

**Comment by weijiii** [comment]
Hi @EminUZUN @ebyhr if this issue is not picked up yet I'd like to give it a try.

**Comment by mosabua** [comment]
The semantics for UUID in SQL Server and Trino as significantly different. The PR #14924 showed that a change to the mapping results in performance regressions. 

What is the reason that you would want the mapping changed @EminUZUN ? Is there some queries or functions that rely on the UUID data type?

**Comment by EminUZUN** [comment]
@mosabua , we have decided not to use uniqueidentifier type at all, due to difference. Till microsoft decides to change it with standard UUID, it is better to be mapped as current one.

Thanks @weijiii  for the efforts.
