### ISSUE TITLE
Control the frequency of configuration reload from DB backed resource group manager

### ISSUE THREAD

**Issue by pankajgupta1-myntra** [trinodb/trino#14514]
Currently, The configuration is reloaded from the database every second. In significant cases, we want to control this frequency.

It is hardcoded [here](https://github.com/trinodb/trino/blob/18882afb87690efe22448dfe25d7be8be7d32aa2/plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/db/DbResourceGroupConfigurationManager.java#L132).

**Comment by ebyhr** [comment]
Do you want to contribute this feature?

**Comment by u6387664** [comment]
Hi there, I'm a first time contributor and would like to work on this issue/ be assigned to this issue. Any tips or help would be appreciated!

**Comment by pankajgupta1-myntra** [comment]
It can be set as Config properties just like resource-groups.max-refresh-interval.
Users will have control via resource-groups.properties file.

**Comment by pankaj-gupta140** [comment]
It can be set as Config properties just like resource-groups.max-refresh-interval.
Users will have control via resource-groups.properties file.
