### ISSUE TITLE
OOM while running `trino-hive`

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#14544]
```
Error:  java.lang.OutOfMemoryError: Java heap space
Error:  Terminating due to java.lang.OutOfMemoryError: Java heap space
```

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/actions/runs/3216856434/jobs/5259188338

**Comment by findepi** [comment]
@findinpath in this case, what were the ongoing test classes?
surefire sometimes reports this, look for "Crashed tests" in log. see https://github.com/trinodb/trino/issues/14485 for example

also, https://github.com/trinodb/trino/issues/14248 may be related

**Comment by findinpath** [comment]
Closing because this is a duplicate of https://github.com/trinodb/trino/issues/14248
