### ISSUE TITLE
Trino Driver - Oracle Catalog problem

### ISSUE THREAD

**Issue by Xenqifi** [trinodb/trino#14540]
Hi Guys,

There is a Hive Catalog setup for Trino but there is a pesky Oracle Catalog as well. We cannot access this Oracle Catalog, we also do not know how to remove it.

We are only interested in accessing Hive tables, views.

The problem is, some applications when trying to connect to Hive, fails because their tools try to Open/Access Oracle Catalog as well eventhough the Hive Catalog is specified in the jdbc connection string.

Any ideas how to get rid of the Oracle Catalog?

Thanks!

**Comment by hashhar** [comment]
You can remove the `<catalog_name>.properties` file from Trino's `etc/catalogs` directory to get rid of the catalog if you really have no use for it.

Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there or reopen if needed.
