### ISSUE TITLE
FAILED (TABLE_NOT_FOUND) when describing MySQL tables

### ISSUE THREAD

**Issue by paoliniluis** [trinodb/trino#14554]
Using metabase/qa-databases:mysql-sample-8 container, which is a MySQL 8 DB with some sample data (username: metabase / password metasample123)

If I connect to that DB via an external client, it works out of the box

If I connect to that DB via Trino with an external client (using https://trino.io/docs/current/connector/mysql.html), it will fail with the error in the title.

The problem is also interesting as there are some other commands that work:
```
SHOW SCHEMAS FROM "mysql";

SHOW TABLES FROM "mysql"."sample";

-- Everything below this line will fail
    
DESCRIBE "mysql"."sample"."products";
SHOW COLUMNS FROM "mysql"."sample"."products";

SELECT * FROM "mysql"."sample"."products";
```

Version: 399, haven't tried with older versions

Note: all testing was done with this simple docker-compose stack https://github.com/paoliniluis/metabase-trino.

It's a Trino (single node) + postgres + mysql + mongodb + Metabase. If you check the Trino logs, when Metabase tries to do the scanning by using "DESCRIBE", those queries error out

**Comment by ebyhr** [comment]
Does the table name contain uppercase in MySQL side? What happens if you enable `case-insensitive-name-matching` config property?

**Comment by paoliniluis** [comment]
Thanks! it worked!

Interesting facts:
1) in the SQL scripts, everything was in uppercase
2) Presto showed everything in lowercase in the first place (that's why I filled the bug, since "show tables from ..." was showing things in lowercase)

Is this an actual issue? (I mean, the behaviour should be consistent, either it fails completely or it works)

**Comment by ebyhr** [comment]
It's a known issue. Please take a look at https://github.com/trinodb/trino/issues/17.
