### ISSUE TITLE
Unable to alter iceberg table when location has trailing slash

### ISSUE THREAD

**Issue by billoliver42** [trinodb/trino#14552]
## Description
When I create a table using the iceberg connector and set the table's location to a bucket (without a subfolder), Trino throws a metadata location mismatch error (see below).

## Setup
Trino with the Iceberg connector using Minio as storage layer. Hive standalone metadata server using Postgres backend.

## Error
```
SQL Error [65536]: Query failed (#20221010_171704_00057_2juwr): Metadata location [s3a://datalake/metadata/00000-17fce192-87bb-4d14-8627-3508fbf1e4fd.metadata.json] is not same as table metadata location [s3a://datalake//metadata/00000-17fce192-87bb-4d14-8627-3508fbf1e4fd.metadata.json] for billtest.test1
```

It appears that the only difference between the two paths is an extra forward slash character before 'metadata'.
```s3a://datalake/metadata```
vs
```s3a://datalake//metadata```

## Steps to recreate
 Step 1: Create table using iceberg connector
```
CREATE TABLE iceberg.billtest.test1
(
    id BIGINT,
    name VARCHAR
)
WITH (
     format = 'PARQUET',
     location = 's3a://datalake/'
)
```

Step 2: alter table to add new column
```
ALTER TABLE iceberg.billtest.test1 ADD COLUMN IF NOT EXISTS score DOUBLE
```

After step two, the above error is returned.

## Workaround
The workaround is when creating the table, use a folder underneath the bucket, like this:
```
CREATE TABLE iceberg.billtest.test1
(
    id BIGINT,
    name VARCHAR
)
WITH (
     format = 'PARQUET',
     location = 's3a://datalake/test1'
)
```

**Comment by findepi** [comment]
@ebyhr's https://github.com/trinodb/trino/pull/14389 may help here, but that PR is supposed to deal with tables that got corrupted by versions 393 and 394.

Also https://github.com/trinodb/trino/pull/13984 may be related.

cc @ebyhr  @alexjo2144

**Comment by ebyhr** [comment]
@billoliver42 I can't reproduce the issue in upstream master. What Trino version are you using?

**Comment by billoliver42** [comment]
@ebyhr trino 372. We can try an updated version if it's been resolved recently?

**Comment by ebyhr** [comment]
Yes, I would recommend upgrading to upcoming 400. By the way, I believe the actual issue is trailing slash rather than under root bucket.
