### ISSUE TITLE
Support case insensitive name matching in MongoDB `query` table function

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#14591]
Note: MongoDB disallows the database name with different case, but it's allowed in collection name.

**Comment by leeyh0216** [comment]
As in issue 3453, if the "mongodb.case-insensitive-name-matching" option is false, renaming the collection variable from Remote Table to the actual table name that is Case Sensitive is what this ticket is about?

I am interested in the issue, and I am seeking the consent of the company regarding the CLA submission. If there is no assignee by then, I would like to be assigned.
