### ISSUE TITLE
trino not support for datetime in doris

### ISSUE THREAD

**Issue by forhead** [trinodb/trino#14654]
when I add doris as the soruce. I create below table, and insert a value with datetime in doris

```
CREATE TABLE tbl1
(
    k1 DATE
)
PARTITION BY RANGE(k1)
(
)
DISTRIBUTED BY HASH(k1)
PROPERTIES
(
    "dynamic_partition.enable" = "true",
    "dynamic_partition.time_unit" = "DAY",
    "dynamic_partition.start" = "-7",
    "dynamic_partition.end" = "3",
    "dynamic_partition.prefix" = "p",
    "dynamic_partition.buckets" = "32"
);
```

but when I query in doris with select
`select * from doris.example_db.tbl1;`

I get below error
`
Query 20221016_141052_00008_meyca failed: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: column size not present`

it seems trino is not support the datetime in doris

can you give some advice?

**Comment by tangjiangling** [comment]
> k1 DATE

Seems typo?

**Comment by tangjiangling** [comment]
FYI: [Apache Doris](https://doris.apache.org/)

If my guess correctly, did you reuse the MySQL connector to read the Doris data? 

If so, `DATETIME` or `TIMESTAMP` values in MySQL can include trailing fractional second parts with precision up to microseconds (6 bits). But in Doris `DATETIME` does not support the fractional seconds part. See https://doris.apache.org/docs/sql-manual/sql-reference/Data-Types/DATETIME

You can try adding: `jdbc-types-mapped-to-varchar=datetime` to the catalog properties file (in `etc/catalog`).

**Comment by forhead** [comment]
> FYI: [Apache Doris](https://doris.apache.org/)
> 
> If my guess correctly, did you reuse the MySQL connector to read the Doris data?
> 
> If so, `DATETIME` or `TIMESTAMP` values in MySQL can include trailing fractional second parts with precision up to microseconds (6 bits). But in Doris `DATETIME` does not support the fractional seconds part. See https://doris.apache.org/docs/sql-manual/sql-reference/Data-Types/DATETIME
> 
> You can try adding: `jdbc-types-mapped-to-varchar=datetime` to the catalog properties file (in `etc/catalog`).

really thanks for your help, works for me. 
Will close it.

**Comment by myfjdthink** [comment]
We have modified the Mysql Connector to support the datetime type of Doris, for a complete example you can see this [repository](https://github.com/myfjdthink/trino-doris-demo) 

@forhead

**Comment by Yiutto** [comment]
![image](https://github.com/trinodb/trino/assets/12077317/4e929828-d482-4bfd-93bf-5dc62700ec0d)


Query 20230719_101134_00044_r6m84, FAILED, 2 nodes
Splits: 383 total, 254 done (66.32%)
1:02 [44.7M rows, 440MB] [716K rows/s, 7.05MB/s]

Query 20230719_101134_00044_r6m84 failed: errCode = 2, detailMessage = query timeout


One problem is that I used trino to associate hive with kudu and doris tests, and I found that the query always timed out

doris> show variables like 'query_timeout';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| query_timeout | 60    |
+---------------+-------+
1 row in set (0.00 sec)

doris's timeout is 60 seconds
trino's query.client.timeout=5m,

trino itself does not support doris, so it is difficult to set the query timeout time of doris from trino. What should I do?
