### ISSUE TITLE
Incorrect equality delete filter happens when the field id order between `equalityFieldIds` and table `Schema` differs

### ISSUE THREAD

**Issue by luisfmcalado** [trinodb/trino#14693]
We have identified an issue when using iceberg (0.13.1) and a regression between 391 and 392. 
We are using iceberg with Flink version (1.14.2).

The id and partition_date columns were used as equality fields, being the partition_date the partition.

We did the query using Hive and the records are not duplicated.

```
CREATE TABLE iceberg.default.event (
    payload varchar NOT NULL,
    id varchar NOT NULL,
    partition_date varchar NOT NULL
 )
 WITH (
    format = 'PARQUET',
    format_version = 2,
    location = 's3a://hive/warehouse/event',
    partitioning = ARRAY['partition_date']
 )
```

```
trino> select * from iceberg.default.event;
 payload | id  | partition_date
---------+-----+----------------
 P1       | id1 |           2022
 P2      | id1 |           2022
```

# Steps
1. Create table using Iceberg API
2. Send message using Flink with upsert enabled and equality fields (`id` and `partition_date`)
3. Wait for the checkpoint to trigger
4. Query with Trino CLI and find a single entry.
5. Send another message using Flink with upsert enabled and equality fields (`id` and `partition_date`)
6. Query with Trino CLI (392 and forward) and see the **duplicated entry**.
7. Query using beeline and Hive and **it won't be duplicated**.
8. Use Trino 391 and **it won't be duplicated**.

# S3 data
[event.zip](https://github.com/trinodb/trino/files/9868200/event.zip)

# Result
```
trino> select * from iceberg.default.event;
 payload | id  | partition_date
---------+-----+----------------
 P1      | id1 |           2022
 P2     | id1 |           2022
```

# Expected
```
trino> select * from iceberg.default.event;
 payload | id  | partition_date
---------+-----+----------------
 P2     | id1 |           2022
```

**Comment by alexjo2144** [comment]
> Use Trino 391 and it won't be duplicated.

Do you mind trying your steps out with version 400? @ebyhr fixed some issues involving slashes that may have been related

**Comment by luisfmcalado** [comment]
> > Use Trino 391 and it won't be duplicated.
> 
> Do you mind trying your steps out with version 400? @ebyhr fixed some issues involving slashes that may have been related

We did try with the version 400. Actually, we tried with versions 385, 395, 391, 392, 399 and 400.

**Comment by ebyhr** [comment]
I tried to reproduce the issue using data.zip, but files look broken. Could you upload again? 
```
ive
└── warehouse
    └── event
        ├── data
        │   └── partition_date=2022
        │       ├── 00000-0-d56e830e-a97a-4b47-91ad-9e7c12598259-00001.parquet
        │       │   └── xl.meta
        │       ├── 00000-0-d56e830e-a97a-4b47-91ad-9e7c12598259-00002.parquet
        │       │   └── xl.meta
        │       ├── 00000-0-d56e830e-a97a-4b47-91ad-9e7c12598259-00003.parquet
        │       │   └── xl.meta
        │       └── 00000-0-d56e830e-a97a-4b47-91ad-9e7c12598259-00004.parquet
        │           └── xl.meta
        └── metadata
            ├── 00000-ce51caf2-b66b-416e-9b7d-b6125a3bf003.metadata.json
            │   └── xl.meta
            ├── 00001-12214753-4d6e-400c-bf86-f911c70b158d.metadata.json
            │   └── xl.meta
            ├── 00002-c589a8da-78be-419e-9a07-a6e6743e851c.metadata.json
            │   └── xl.meta
            ├── 3e818ab0-7c66-4b46-8352-92b4e794274e-m0.avro
            │   └── xl.meta
            ├── 3e818ab0-7c66-4b46-8352-92b4e794274e-m1.avro
            │   └── xl.meta
            ├── 68ff6b1c-86cd-4301-adde-6db759c132db-m0.avro
            │   └── xl.meta
            ├── 68ff6b1c-86cd-4301-adde-6db759c132db-m1.avro
            │   └── xl.meta
            ├── snap-6599118306566161761-1-68ff6b1c-86cd-4301-adde-6db759c132db.avro
            │   └── xl.meta
            └── snap-9139430333385829378-1-3e818ab0-7c66-4b46-8352-92b4e794274e.avro
                └── xl.meta
```

**Comment by luisfmcalado** [comment]
yes, of course.

[data.tar.gz](https://github.com/trinodb/trino/files/9839822/data.tar.gz)

**Comment by luisfmcalado** [comment]
Reading the same table using Spark.
```
spark-sql> select * from iceberg.default.event;
P2      id1     2022
Time taken: 0.206 seconds, Fetched 1 row(s)
```

**Comment by ebyhr** [comment]
Unfortunately, I can't reproduce the issue with the provided files. 
```
trino:tpch> SELECT * FROM event;
 payload | id  | partition_date
---------+-----+----------------
 P2      | id1 | 2022
 P1      | id1 | 2022
(2 rows)
```
