### ISSUE TITLE
Cast issue when reading upsert equality field in Iceberg

### ISSUE THREAD

**Issue by luisfmcalado** [trinodb/trino#14696]
We have identified an issue when using iceberg (0.13.1) and a regression between 391 and 392. We are using iceberg with Flink version (1.14.2).
After doing a few upserts trino returns the following message: "Cannot cast java.lang.Integer to java.lang.CharSequence".

The issue happened following the steps found at https://github.com/trinodb/trino/issues/14693. The only difference is that the partition column is an integer.

```sql
CREATE TABLE iceberg.default.event (
    payload varchar NOT NULL,
    id varchar NOT NULL,
    partition_date integer NOT NULL
 )
 WITH (
    format = 'PARQUET',
    format_version = 2,
    location = 's3a://hive/warehouse/event',
    partitioning = ARRAY['partition_date']
 )
```
### Steps to reproduce

```sql
ALTER TABLE event 
SET TBLPROPERTIES (
'metadata_location'='s3a://hive/warehouse/event/metadata/00004-4da011f8-8e59-441a-a550-cf7c37e45e3e.metadata.json')  
```

1. Create table using the example above
2. Copy [event.zip](https://github.com/trinodb/trino/files/9874362/event.zip) to the s3 bucket (s3a://hive/warehouse/event).
3. Change the table metadata location to the latest snapshot using Hive (use the alter table above).
4. Query the created database (```select * from iceberg.default.event```)

### Result

```
trino> select * from iceberg.default.event;
 payload | id  | partition_date
---------+-----+----------------
 P4      | id1 |           2022
(1 row)

Query 20221026_231533_00040_fmva2, FAILED, 2 nodes
Splits: 2 total, 1 done (50.00%)
0.98 [1 rows, 1.21KB] [1 rows/s, 1.24KB/s]

Query 20221026_231533_00040_fmva2 failed: Cannot cast java.lang.Integer to java.lang.CharSequence
```

### Expected
```
trino> select * from iceberg.default.event;
 payload | id  | partition_date
---------+-----+----------------
 P4      | id1 |           2022
(1 row)

Query 20221026_231533_00040_fmva2, FINISHED, 1 node
Splits: 2 total, 2 done (100.00%)
0.98 [1 rows, 1.21KB] [1 rows/s, 1.24KB/s]
```

**Comment by ebyhr** [comment]
Could you provide steps to reproduce or reproducible data & metadata?

**Comment by luisfmcalado** [comment]
> Could you provide steps to reproduce or reproducible data & metadata?

done @ebyhr.

**Comment by ebyhr** [comment]
I confirmed the root cause is same as #14693
