### ISSUE TITLE
select mysql views missing some columns

### ISSUE THREAD

**Issue by CCColby** [trinodb/trino#14719]
I have been created a view in mysql database,select this view, it has six columns, but when use trino connect this db, select this view, i got only one columns? some views is ok, only one happened this problem. Thanks!

**Comment by CCColby** [comment]
I found this problem, when select this view, jdbc return return a column , type decimal, but decimaldigits is 0. then return null columnMapping cause missing some columns.i add this test code pass:
`
                if (typeHandle.getDecimalDigits().isPresent() && typeHandle.getDecimalDigits().get() == 0
                        && typeHandle.getJdbcTypeName().isPresent() && typeHandle.getJdbcTypeName().get().equals("DECIMAL")) {
                    typeHandle = JDBC_INTEGER;
                }
`

**Comment by hashhar** [comment]
Can you provide the CREATE VIEW statement from MySQL and also the DESCRIBE output as seen by Trino?

I want to see why the JDBC driver is sending back incorrect information leading to such issue.

**Comment by CCColby** [comment]
> Can you provide the CREATE VIEW statement from MySQL and also the DESCRIBE output as seen by Trino?
> 
> I want to see why the JDBC driver is sending back incorrect information leading to such issue.

The view SQL like this:

`
SELECT
	"m"."month" AS "month",
	"m"."sign_user" AS "sign_user",
	"m"."saas_user" AS "saas_user",
	"m"."no_saas_user" AS "no_saas_user",
	"m"."user_ft" AS "user_ft",
	"m"."user_no_ft" AS "user_no_ft" 
FROM
	(
		"sco_month"
		LEFT JOIN (
		SELECT
			"b"."month" AS "month",
			sum( "a"."sign_user" ) AS "sign_user",
			sum( "a"."saas_user" ) AS "saas_user",
			sum( "a"."no_saas_user" ) AS "no_saas_user",
			sum( "a"."user_ft" ) AS "user_ft",
			sum( "a"."user_no_ft" ) AS "user_no_ft" 
		FROM
			((
				SELECT
					date_format( "sco_sign_table"."call_back", '%Y/%m' ) AS "month",
					count( "sco_sign_table"."user_name" ) AS "sign_username",
					sum(
					IF
					(( "sco_sign_table"."whether_kai" = 'no' ), 1, 0 )) AS "saas_user",
					sum(
					IF
					(( "sco_sign_table"."whether_kai" = 'yes' ), 1, 0 )) AS "no_saas_user",
					sum(
					IF
					(( "sco_sign_table"."Fintech" = 'yes' ), 1, 0 )) AS "user_ft",
					sum(
					IF
					(( "sco_sign_table"."Fintech" = 'no' ), 1, 0 )) AS "user_no_ft" 
				FROM
					"sco_sign_table" 
				WHERE
					((
							"sco_sign_table"."sign_amount" > '0' 
							) 
						AND ( "sco_sign_table"."whether_continue_user" IS NULL ) 
					AND ( "sco_sign_table"."call_back" IS NOT NULL )) 
				GROUP BY
					"month" 
					) "a"
				JOIN (
				SELECT
					date_format( "sco_sign_table"."call_back", '%Y/%m' ) AS "month",
					count( "sco_sign_table"."user_name" ) AS "sign_username",
					sum(
					IF
					(( "sco_sign_table"."whether_kai" = 'no' ), 1, 0 )) AS "saas_user",
					sum(
					IF
					(( "sco_sign_table"."whether_kai" = 'yes' ), 1, 0 )) AS "no_saas_user",
					sum(
					IF
					(( "sco_sign_table"."Fintech" = 'yes' ), 1, 0 )) AS "user_ft",
					sum(
					IF
					(( "sco_sign_table"."Fintech" = 'no' ), 1, 0 )) AS "user_no_ft" 
				FROM
					"sco_sign_table" 
				WHERE
					((
							"sco_sign_table"."sign_amount" > '0' 
							) 
						AND ( "sco_sign_table"."whether_sign_user" IS NULL ) 
					AND ( "sco_sign_table"."call_back" IS NOT NULL )) 
				GROUP BY
					"month" 
				) "b" 
			) 
		WHERE
			( "a"."month" <= "b"."month" ) 
		GROUP BY
			"b"."month" 
			) "m" ON ((
			"m"."month" = "sco_month"."month" 
	)))

`
I select this view , got six columns in navicate.
Desc this view by trino, only got 'month' this column.
Debug this query by trino, JDBC return six columns, other five columns got 'DECIMAL' data type, but digits got 0.

**Comment by ebyhr** [comment]
@CCColby Please provide table definition of `sco_sign_table` in MySQL.

**Comment by CCColby** [comment]
> @CCColby Please provide table definition of `sco_sign_table` in MySQL.


```
contract_no	        varchar	255	0	-1	0	0	0			
contract_nu	        varchar	255	0	-1	0	0	0			
team_name	        varchar	255	0	-1	0	0	0			
sales	            varchar	255	0	-1	0	0	0			
sale_local	        varchar	255	0	-1	0	0	0			
user_name	        varchar	255	0	-1	0	0	0			
b_com	            varchar	255	0	-1	0	0	0		
whether_new	        varchar	255	0	-1	0	0	0			
com_property	    varchar	255	0	-1	0	0	0			
sign_product	    varchar	255	0	-1	0	0	0			
sign_matainer	    varchar	255	0	-1	0	0	0			
sign_time	        varchar	255	0	-1	0	0	0		
contract_back_time	varchar	255	0	-1	0	0	0		
sign_amount	        decimal	12	2	-1	0	0	0		
whether_back	    varchar	255	0	-1	0	0	0			
back_amount	        decimal	12	2	-1	0	0	0		
whether_kai	        varchar	255	0	-1	0	0	0			
whether_user	    varchar	255	0	-1	0	0	0			
Fintech	            varchar	255	0	-1	0	0	0							
server_start	    varchar	255	0	-1	0	0	0		
server_end	        varchar	255	0	-1	0	0	0		
contract_time	    varchar	255	0	-1	0	0	0			
apply_start	        varchar	255	0	-1	0	0	0		
sale_apply_start	varchar	255	0	-1	0	0	0	
```

**Comment by ebyhr** [comment]
The nested sum returns larger precision (45) which is greater than the max supported precision (38). You will need to cast to supported precision or varchar types. JDBC driver returns the correct precision as far as I confirmed.
