### ISSUE TITLE
Connection property 'SSLVerification' is not allowed in Trino JDBC Driver

### ISSUE THREAD

**Issue by jackwang2** [trinodb/trino#14720]
Use the trino JDBC driver 400, seems it doesn't recognize property `SLVerification` mentioned in the Trino [doc](https://trino.io/docs/current/client/jdbc.html):
![Screen Shot 2022-10-24 at 16 23 13](https://user-images.githubusercontent.com/26425937/197488178-d5704dc4-9496-401e-aadc-dfb52ff5d8c7.png)

**Comment by mosabua** [comment]
Could this parameter be missing in the validation of allowed parameters @electrum ?

**Comment by mosabua** [comment]
It seems to be wired up correctly https://github.com/trinodb/trino/blob/master/client/trino-jdbc/src/main/java/io/trino/jdbc/ConnectionProperties.java#L104

Looking at your list of properties I think you might have an old jdbc driver on the classpath after all. Can you verify @jackwang2 ?

**Comment by jackwang2** [comment]
@mosabua Do you mean old `trino` JDBC driver? I checked the variable `java.class.path`, it only contains one jar of `trino-jdbc-400.jar`.

**Comment by ebyhr** [comment]
Please set `SSL` connection property as true.

**Comment by mosabua** [comment]
Ha! Good catch @ebyhr .. I totally missed that in the screenshot
