### ISSUE TITLE
Add array_histogram function

### ISSUE THREAD

**Issue by gurustron** [trinodb/trino#14725]
As the title says - add [`array_frequency`](https://prestodb.io/docs/current/functions/array.html#array_frequency) which seems to be missing currently from Trino.

**Comment by gurustron** [comment]
Or `unnest` + `histogram` like done [here](https://stackoverflow.com/a/74181472/2501279)

**Comment by bitsondatadev** [comment]
@gurustron are you thinking of implementing this or just reporting it for now?

**Comment by gurustron** [comment]
@bitsondatadev actually I was thinking about it. Give me a week or two to estimate my capacity to do it.

**Comment by nathanwilk7** [comment]
I've been looking for an operator to try implementing as an intro to developing on Trino, I will start putting together a PR and link to this issue when it's ready, please don't hesitate to leave any feedback on the PR

**Comment by bitsondatadev** [comment]
Buena suerte! Let us know if you need any support on the Slack! Try posting on the dev channel and tag me and @findinpath if you need help!
