### ISSUE TITLE
Hive connector returns an error when query is looking for a schema which does not exist

### ISSUE THREAD

**Issue by kamilgniewekstarburstdata** [trinodb/trino#14746]
When glue is used as a metastore for a hive-hadoop2 connector the query:

`select * FROM system.jdbc.tables;` 

is working as expected returning results where the user has an access to. However, when the user adds additional condition like:

`select * FROM system.jdbc.tables where table_schem='public';`

The query fails with following error:

`io.trino.spi.TrinoException: User: arn:aws:sts::<redacted> is not authorized to perform: glue:GetTables on resource: arn:aws:glue:<redacted> because no identity-based policy allows the glue:GetTables action (Service: AWSGlue; Status Code: 400; Error Code: AccessDeniedException; Request ID: <redacted>; Proxy: null)`

The expectation for the second query is to return only a subset of the results form the first query or to return no results instead of the error. This situation happen when the specified schema does not exist. 

Stacktrace of the error is attached.
[stacktrace.txt](https://github.com/trinodb/trino/files/9858681/stacktrace.txt)

**Comment by findepi** [comment]
Proposed solution:

in `io.trino.plugin.hive.metastore.glue.GlueHiveMetastore#getAllTables` when we get a permission denied (`AmazonServiceException`), add
```java
if (!getAllDatabases().contains(databaseNames)) {
  // E.g. we don't have access, so we don't know if it exists, assume it does not
 return ImmutableList.of();
```

**Comment by alexjo2144** [comment]
`getDatabase` might be better than `getAllDatabases`

**Comment by findepi** [comment]
> `getDatabase` might be better than `getAllDatabases`

getDatabase may result in similarly hard-to-interpret exception
at least that's why i suggested getAllDatabases

**Comment by alexjo2144** [comment]
Gotcha, I was more thinking that get all may return a large amount of unnecessary data compared to getting a single one.

**Comment by findepi** [comment]
> Gotcha, I was more thinking that get all may return a large amount of unnecessary data compared to getting a single one.

You're absolutely right.
