### ISSUE TITLE
json_query keyvalue() return NULL, when the object has more than one key

### ISSUE THREAD

**Issue by littlesnail0** [trinodb/trino#14761]
![image](https://user-images.githubusercontent.com/36443635/198007121-10413fa3-e188-42ea-a8a3-c84fbc2f3b41.png)

**Comment by littlesnail0** [comment]
How can I flatten the json object in the second query into multiple rows?

**Comment by findinpath** [comment]
Try out 

```
select json_query('{"weather":3, "da":2}', 'lax $.keyvalue()' WITH ARRAY WRAPPER);
```

Do take a look over the docs https://trino.io/docs/current/functions/json.html


If you want to get a deeper understanding of how the function works, have a look at:

https://github.com/trinodb/trino/blob/0dd99917919529fba2e8554c8d87a8cd25ec8eeb/core/trino-main/src/test/java/io/trino/sql/query/TestJsonQueryFunction.java

https://github.com/trinodb/trino/blob/0dd99917919529fba2e8554c8d87a8cd25ec8eeb/core/trino-main/src/main/java/io/trino/operator/scalar/json/JsonQueryFunction.java

**Comment by hashhar** [comment]
Closing as answered. Feel free to reopen or join our [Slack](https://trino.io/slack.html) and continue the conversation there.

**Comment by 397090770** [comment]
Hi @hashhar, The invitation link on the https://trino.io/slack.html page is invalid. Can you share a new slack invitation link?

**Comment by hashhar** [comment]
Thanks for bringing this to attention @397090770 . We've updated the link, please try again.
