### ISSUE TITLE
Remove Iceberg RESTCatalogAdapter after 1.1.0 release

### ISSUE THREAD

**Issue by danielcweeks** [trinodb/trino#14783]
The test class RESTCatalogAdapter is used for testing the Iceberg RESTCatalog connector, but this will be released in Iceberg natively to support testing in the Iceberg 1.1.0 Release and can be removed from the iceberg connector.

Originally introduced in #13294

**Comment by findinpath** [comment]
@danielcweeks  / @nastra  gentle reminder now that https://github.com/trinodb/trino/pull/15079 is merged in Trino

**Comment by nastra** [comment]
thanks for mentioning it here @findinpath, I've cleaned this up and integrated this into https://github.com/trinodb/trino/pull/13294
