### ISSUE TITLE
Allow Iceberg writes to use either `append` or `fastAppend`

### ISSUE THREAD

**Issue by alexjo2144** [trinodb/trino#14822]
Relates to: https://github.com/trinodb/trino/issues/9340 and https://github.com/trinodb/trino/issues/14821

`append` is a good default for Iceberg writes, as it periodically compacts Manifest files automatically. However, users in certain use cases may want to do compaction of Manifests async from writes. We should allow configuring `fastAppend` for that situation.

**Comment by SergeySereda0218** [comment]
Hi alexjo2144,
I'm completely new in open-source and would like to begin! :)
Can you assign this issue to me?
Thanks in advance.

**Comment by ebyhr** [comment]
@SergeySereda0218 Are you still working on this issue?

**Comment by SergeySereda0218** [comment]
Hi alexjo2144,
The analysis of the problem and the search for a solution took much more time than I expected. Before proceeding with the implementation, I would like to receive your advice.
I see this solution like this :
- check the value of the **commit.manifest-merge.enabled** parameter for the table
  if “true” (default value) – use Append
  if "false" - use FastAppend
Am I thinking right?
Thanks in advance.

**Comment by SergeySereda0218** [comment]
> 



> @SergeySereda0218 Are you still working on this issue?

Yes, I'm still working on a solution. Sorry, for taking so long.
I am completely new to Open Source and on the project. So it takes me quite a lot of time.

**Comment by findepi** [comment]
> However, users in certain use cases may want to do compaction of Manifests async from writes

What are these scenarios?
Can we define them? Can we detect them?

**Comment by alexjo2144** [comment]
> Can we detect them?

I'm not sure we can, at least at the moment. In Spark the [Write interface can be marked as streaming](https://spark.apache.org/docs/3.2.0/api/java/org/apache/spark/sql/connector/write/Write.html#toStreaming--), which sets fastAppend down the line. From a Trino perspective, all inserts are the same as far as I know.
