### ISSUE TITLE
BigQuery Connector - Schema does not exist

### ISSUE THREAD

**Issue by swamichandra** [trinodb/trino#14829]
I have setup the BigQuery connector on trino-server-401. `show catalogs` lists the right catalog name and `show schemas from <catalog name>` lists the right schemas in BigQuery as well. 

But when I run `show tables from <catalog name>.<schema name>`, get a `Query xxx failed: line 1:1: Schema '<schema name>' does not exist` error message. 

BQ permissions are fine and I'm able to connect to the BQ schema using tools like DBeaver and run queries. So the service credentials JSON file is not a problem.

**Comment by tangjiangling** [comment]
I guess the schema you are querying contains **capital letters** in BigQuery, if so, please add [bigquery.case-insensitive-name-matching](https://trino.io/docs/current/connector/bigquery.html?highlight=bigquery.case-insensitive-name-matching#configuration-properties) to the catalog properties file (under `etc/catalog`)

**Comment by swamichandra** [comment]
Thanks @tangjiangling !! That fixed the problem. Might help to add this as a recommended entry in the [BigQuery connector documentation](https://trino.io/docs/current/connector/bigquery.html?highlight=bigquery.case-insensitive-name-matching#configuration) page. 

**Configuration**
To configure the BigQuery connector, create a catalog properties file in `etc/catalog` named, for example, `bigquery.properties`, to mount the BigQuery connector as the bigquery catalog. Create the file with the following contents, replacing the connection properties as appropriate for your setup:

`connector.name=bigquery`
`bigquery.project-id=<your Google Cloud Platform project id>`
`bigquery.case-insensitive-name-matching=true`
