### ISSUE TITLE
possibility to generate date range

### ISSUE THREAD

**Issue by kodeine** [trinodb/trino#14826]
is it possible to generate date range in trino - mongodb connector.
something like

```
WITH all_dates AS (
    SELECT * FROM  UNNEST(GENERATE_DATE_ARRAY(CURRENT_DATE, END_DATE, INTERVAL 1 DAY) ) as reportDate
),
```

**Comment by tangjiangling** [comment]
Let me close it as it has already been answered in [community slack](https://trinodb.slack.com/archives/CGB0QHWSW/p1667012603976599?thread_ts=1667003060.625819&cid=CGB0QHWSW).
