### ISSUE TITLE
Unexpected behavior when using partition projection in hive connector

### ISSUE THREAD

**Issue by Larissa-Rocha** [trinodb/trino#14860]
I'm using Trino + Hive connector, I needed to turn on [partition projection](https://trino.io/docs/current/connector/hive.html#accessing-tables-with-athena-partition-projection-metadata) to query a specific table, so in the values.yaml file I have something like this:
```connectors:
  raw.properties: |-
    hive.partition-projection-enabled=true
```
 
This works for my one table that depends on it, however when I query other tables (also in raw) I get the following error: 

> TrinoUserError(type=USER_ERROR, name=INVALID_COLUMN_PROPERTY, message="Partition projection definition for column: '_sdc_started_at' missing")

I tried to set the `partition_projection_ignore` table property to true, but then I get the error:

> TrinoUserError(type=USER_ERROR, name=INVALID_TABLE_PROPERTY, message="Catalog 'trusted' table property 'partition_projection_ignore' does not exist")

In fact, this property does not exist in catalog trusted, only in raw... this query is a `create table` statement (using dbt, trino as query engine) and we are transforming data from raw to trusted:
```
create table "trusted"."my_schema"."my_table_tmp"
    
    WITH (
        location = 's3a://my-bucket/my-path/',
  partition_projection_ignore = true)
  as ( ...
```

Any advices on this?

**Comment by hashhar** [comment]
cc: @aczajkowski @chrlso

**Comment by aczajkowski** [comment]
@Larissa-Rocha Thank you for your report.

As for the problem.
Error reports it was executed in context of catalog called `trusted`
```
TrinoUserError(type=USER_ERROR, name=INVALID_TABLE_PROPERTY, message="Catalog 'trusted' table property 'partition_projection_ignore' does not exist")
```
Could you share its configuration ? If it's not Hive connector based catalog it will not work as
 `partition_projection_ignore` is hive connector property only.  

It think that creating same table over Hive catalog `raw` should work as expected.
```
create table "raw"."my_schema"."my_table_tmp"
    
    WITH (
        location = 's3a://my-bucket/my-path/',
  partition_projection_ignore = true)
  as ( ...
```
 
For some context:
- INVALID_TABLE_PROPERTY comes from here - very early in query processing:
https://github.com/trinodb/trino/blob/5f7ae2815c34fc2cc23a4dd58598b156cfc47a8f/core/trino-main/src/main/java/io/trino/metadata/AbstractCatalogPropertyManager.java#L89-L98

- And for Hive connector this property `partition_projection_ignore` is available on table lvl. for Hive connector only https://github.com/trinodb/trino/blob/5f7ae2815c34fc2cc23a4dd58598b156cfc47a8f/plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveTableProperties.java#L158-L162

**Comment by hashhar** [comment]
Both of the issues seems like misconfiguration/misuse. Closing for now, feel free to re-open if this is still an issue.
