### ISSUE TITLE
Apply recommended fault tolerant execution settings automatically

### ISSUE THREAD

**Issue by arhimondr** [trinodb/trino#14955]
Currently there are additional settings that must be modified for the fault tolerant execution to optimally function, e.g.:

```
exchange.compression-enabled=true
query.low-memory-killer.delay=0s
task.concurrency=8
```

Ideally it would be great if those were applied automatically when the `retry-policy=TASK` is enabled on the cluster.

**Comment by hashhar** [comment]
@arhimondr Is this done since https://github.com/trinodb/trino/pull/14957 is merged?
