### ISSUE TITLE
Can't change http_uri.

### ISSUE THREAD

**Issue by kiko0217** [trinodb/trino#14987]
I have problem. when setup Trino worker in other network with Trino coordinator. where trino coordinator inside k8s, so the network isolate with k8s and must use ingress to access the trino coordinator. The coordinator use http connection inside k8s, but the worker access the coordinator use discovery.uri with https directs at ingress. but the http_uri directs with local ip k8s. the worker can't communicate with the coordinator. to solve this problem so must create proxy. I think it's not effective.

example config
coordinator running in k8s ingress -> example.com

``` properties
coordinator=true
node-scheduler.include-coordinator=false
http-server.process-forwarded=true
http-server.authentication.type=PASSWORD
internal-communication.shared-secret="+LtR71xxxx="
http-server.http.port=8080
query.max-memory=12GB
query.max-memory-per-node=6GB
discovery.uri=http://localhost:8080
```

worker running in other network ->
``` properties
coordinator=false
internal-communication.shared-secret="+LtR71xxxx="
http-server.http.port=8080
exchange.http-client.http-proxy=proxy:port
node-manager.http-client.http-proxy=proxy:port
query.max-memory=12GB
query.max-memory-per-node=6GB
discovery.uri=https://example.com
```

on this config must use proxy. if without proxy can't work.

**Comment by electrum** [comment]
You can set `node.internal-address` on the coordinator to force discovery to return a specific IP or hostname

**Comment by hashhar** [comment]
Closing as answered.

Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there or reopen this if needed.

**Comment by kiko0217** [comment]
Thank you, it's so helpful.
