### ISSUE TITLE
Question: why subsequent executions are faster?

### ISSUE THREAD

**Issue by marsupialtail** [trinodb/trino#14991]
I am benchmarking Trino on AWS EMR reading from S3.

I added the config to explicitly turn off Hive caching, and to the best of my knowledge there is no local caching being done (I can't find the cached files)

I try running TPCH queries now, and the query gets successively faster. i.e. when running TPCH-1 on my setup on Parquet files, I go from 13 s on first hit to almost 7 s by the fifth run, a near 50% difference! 

What is the cause of this behavior? I notice that even after a query finishes, the Trino servers on the workers are still using a high volume of memory.

Does this mean Trino use caching in addition to Hive caching? Can someone please explain this behavior?

**Comment by martint** [comment]
Trino is implemented on top of the JVM, which has a JIT compiler. It generally takes a bit for it to "warm up" (the JIT optimizes and generates machine code at runtime), so the effect is that the initial runs might be slower than subsequent runs.

**Comment by marsupialtail** [comment]
Great. I just want to make sure that no intermediate data is cached, because then that wouldn't be representative of production scnearios

**Comment by raunaqmorarka** [comment]
There is no caching of intermediate data. There may be caching of metadata from metastore and file statuses, depending on what the default config of EMR is.
