### ISSUE TITLE
Predicate pushdown support

### ISSUE THREAD

**Issue by XiaoXin101** [trinodb/trino#15023]
when i used   
select (SUM(turnover))  as col0 from mysql_datacloud_306.datacloud.gc_real_data where (( (  date_diff('day',cast(gc_real_data."id" as date),current_date)  =  0   ) ) and   ( (  gc_real_data."id"  !=  '1'   ) ))   limit 100;

was wrong with trino 395

but when I used 
select (SUM(turnover))  as col0 from mysql_datacloud_306.datacloud.gc_real_data where (( (  date_diff('day',cast(gc_real_data."id" as date),current_date)  =  0   ) ) and   ( (  gc_real_data."id"  !=  '1'   ) ))   limit 100;
with prestosql 346 was right

when I used 
select (SUM(turnover))  as col0 from mysql_datacloud_306.datacloud.gc_real_data where ( ( (  gc_real_data."id"  !=  '1'   ) ) and ( (  date_diff('day',cast(gc_real_data."id" as date),current_date)  =  0   ) ) )   limit 100;
This is also true!

**Comment by XiaoXin101** [comment]
> Can you share the table definition and sample rows of `mysql_datacloud_306.datacloud.gc_real_data` so that we can reproduce the issue?

CREATE TABLE `gc_real_data` (
  `id` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'riqi',
  `riqi` varchar(200) DEFAULT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `turnover` decimal(32,2) DEFAULT NULL,
  `income` decimal(32,2) DEFAULT NULL,
  `platform_sub` decimal(32,2) DEFAULT NULL,
  `shop_sub` decimal(32,2) DEFAULT NULL,
  `platform_fee` decimal(32,2) DEFAULT NULL,
  `order_cnt` int DEFAULT NULL,
  `payment` decimal(32,2) DEFAULT NULL,
  `elm_cnt` int DEFAULT NULL,
  `mt_cnt` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `gc_real_data`(`id`, `riqi`, `create_time`, `turnover`, `income`, `platform_sub`, `shop_sub`, `platform_fee`, `order_cnt`, `payment`, `elm_cnt`, `mt_cnt`) VALUES ('1', '2022-07-16', '2022-07-16 14:05:31', 181542.97, 107294.01, 14095.44, 122637.02, 25146.18, 4103, 134125.31, 1585, 2518);
INSERT INTO `gc_real_data`(`id`, `riqi`, `create_time`, `turnover`, `income`, `platform_sub`, `shop_sub`, `platform_fee`, `order_cnt`, `payment`, `elm_cnt`, `mt_cnt`) VALUES ('2022-07-16', NULL, '2022-07-16 23:59:37', 379064.23, 223740.06, 28040.67, 250125.71, 51080.83, 8118, 277903.77, 3194, 4924);
INSERT INTO `gc_real_data`(`id`, `riqi`, `create_time`, `turnover`, `income`, `platform_sub`, `shop_sub`, `platform_fee`, `order_cnt`, `payment`, `elm_cnt`, `mt_cnt`) VALUES ('2022-07-17', NULL, '2022-07-17 23:59:58', 387470.59, 228439.24, 28374.49, 256790.96, 52193.87, 8214, 283654.00, 3229, 4985);
INSERT INTO `gc_real_data`(`id`, `riqi`, `create_time`, `turnover`, `income`, `platform_sub`, `shop_sub`, `platform_fee`, `order_cnt`, `payment`, `elm_cnt`, `mt_cnt`) VALUES ('2022-07-18', NULL, '2022-07-18 23:59:57', 548922.93, 316354.93, 50447.19, 385395.44, 75801.54, 13267, 390765.31, 5552, 7715);

**Comment by ebyhr** [comment]
> was wrong with trino 395

Could you clarify what was wrong? e.g. query failure, correctness issue

**Comment by XiaoXin101** [comment]
<img width="751" alt="image" src="https://user-images.githubusercontent.com/37534395/201880070-26b80cc6-3e29-4a7a-b9e3-b3c168410eb2.png">

**Comment by XiaoXin101** [comment]
> > was wrong with trino 395
> 
> Could you clarify what was wrong? e.g. query failure, correctness issue

<img width="1684" alt="image" src="https://user-images.githubusercontent.com/37534395/201880352-ac4d0342-96c0-45a5-9c17-551cd8afb89e.png">

**Comment by ebyhr** [comment]
`1` isn't a valid date format in Trino, Please fix the data in MySQL or transform in SELECT query.

**Comment by XiaoXin101** [comment]
> `1`在 Trino 中不是有效的日期格式，请修复 MySQL 中的数据或在 SELECT 查询中进行转换。

I think it's a filter order issue ,  is correct in mysql, trino cast first ,and the two conditions are not executed
