### ISSUE TITLE
cant get hive location use show create table

### ISSUE THREAD

**Issue by user-GitHub-user** [trinodb/trino#15020]

**Comment by ebyhr** [comment]
Could you share more details?

**Comment by user-GitHub-user** [comment]
HI, i want to get hive table location,but show create table not have location properties, any other way to get location?
show create table a;
               Create Table                
-------------------------------------------
 CREATE TABLE hive.defaultdb.a ( 
    a integer                              
 )                                         
 WITH (                                    
    format = 'ORC'                         
 )

**Comment by user-GitHub-user** [comment]
> Could you share more details?
HI, i want to get hive table location,but show create table not have location properties, any other way to get location?
show create table a;

CREATE TABLE hive.defaultdb.a (
a integer
)
WITH (
format = 'ORC'
)

**Comment by ebyhr** [comment]
Please subscribe #1277
