### ISSUE TITLE
Syntax error throws incorrect error message

### ISSUE THREAD

**Issue by weijiii** [trinodb/trino#15044]
For example with something like `SELECT ROW(DATE '2022-10-10', DOUBLE 12.0)` Trino throws following error
```
trino> select row(date '2022-10-10', double 12.0);
Query 20221116_040407_00006_fqudr failed: line 1:38: mismatched input 'date'. Expecting: <expression>
io.trino.sql.parser.ParsingException: line 1:38: mismatched input 'date'. Expecting: <expression>
```
The error position is correct but it reports `date` as mismatched input. Is this behavior expected?

**Comment by ebyhr** [comment]
It would be better to improve the error message.

**Comment by martint** [comment]
This is likely a bug in io.trino.sql.parser.ErrorHandler. It may be backtracking all the way to the beginning of the rule that matches the row fields when reporting the error.

**Comment by martint** [comment]
It's actually due to the unimplemented functionality described in this TODO:

```
// TODO expand ignored rules like we expand special rules
```
