### ISSUE TITLE
Show estimated data_size instead of NULL in SHOW STATS

### ISSUE THREAD

**Issue by raunaqmorarka** [trinodb/trino#15049]
Currently we print NULL whenever the connector does not provide `data_size` stats to the CBO. However, the CBO fills in some estimate for data_size for usage in costs calculations anyway in `PlanNodeStatsEstimate#getOutputSizeForSymbol`.
This can potentially confuse users into thinking that `data_size` is missing, even though the CBO has logic to compute it. It also doesn't allow users to observe the actual data_size statistic the CBO uses during its cost calculations.

cc: @findepi @martint @sopel39

**Comment by findepi** [comment]
`SHOW STATS FOR table` should be as faithful to the connector as possible.
It can be used in particular for troubleshooting stats -- eg not being provided by a connector, or being wrong.

CBO guess work should not affect `SHOW STATS FOR table`.
CBO guess work should still be reflect in

- `EXPLAIN` output
- `SHOW STATS FOR (SELECT * FROM table)`
