### ISSUE TITLE
How to use jdbc Connection with tls and https

### ISSUE THREAD

**Issue by AlienationX** [trinodb/trino#15048]
version: Trino-402

keytool -genkeypair -alias trino -keyalg RSA -keystore keystore.jks

coordinator
```shell
coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8081
query.max-memory=50GB
query.max-memory-per-node=1GB
# discovery.uri=http://10.63.82.213:8081
discovery.uri=https://10.63.82.213:8082

internal-communication.shared-secret=u51elfxYF8yEQA3Vu9visEHsDpg5nDMRTCBVjdD+jp/5HLKIT7rMxU7Np6ueT7U97UgosEpJz8Yq
internal-communication.https.required=true

http-server.https.enabled=true
http-server.https.port=8082
http-server.https.keystore.path=/home/trino/data/keystore.jks
http-server.https.keystore.key=trinoo
http-server.https.secure-random-algorithm=SHA1PRNG

http-server.authentication.type=PASSWORD
```

worker
```shell
coordinator=false
http-server.http.port=8081
query.max-memory=50GB
query.max-memory-per-node=1GB
# discovery.uri=http://hadoop-03:8081
discovery.uri=https://10.63.82.213:8082

internal-communication.shared-secret=u51elfxYF8yEQA3Vu9visEHsDpg5nDMRTCBVjdD+jp/5HLKIT7rMxU7Np6ueT7U97UgosEpJz8Yq
internal-communication.https.required=true

http-server.https.enabled=true
http-server.https.port=8082
http-server.https.keystore.path=/home/trino/data/keystore.jks
http-server.https.keystore.key=trinoo
http-server.https.secure-random-algorithm=SHA1PRNG

http-server.authentication.type=PASSWORD
```

password-authenticator.properties and password.db have been configured. I used the following command to test:

~/trino-server/bin/trino-cli --server https://10.63.82.213:8082 \
--execute="show catalogs" \
--keystore-path /home/trino/data/keystore.jks \
--keystore-password trinoo \
--user test \
--password

it's work. but my question:
If --keystore-path and --keystore-password is not specified, an error message is: **unable to find valid certification path to requested target** , and use jdbc connection for example datagrip tool, give the same error. 

So how to not specify keystore-path and password, also can use datagrip with jdbc link?

**Comment by hashhar** [comment]
You're using a self-signed certificate so there's no way to validate the HTTPS connection without providing the keystore.

Alternatives are to use a CA trusted certificate.

You can obviously disable verification too but then at that point why even use TLS? (via `--insecure` flag to the CLI).

**Comment by AlienationX** [comment]
I just want to add username and password authentication.... how to use CA trusted certificate?

**Comment by hashhar** [comment]
You can get a certificate from something like LetsEncrypt or ZeroSSL or any other CA.

**Comment by AlienationX** [comment]
I just want to add username and password authentication.... how to use CA trusted certificate?
