### ISSUE TITLE
Support partitioning on nested fields in Iceberg

### ISSUE THREAD

**Issue by alexjo2144** [trinodb/trino#15109]
Follow up for https://github.com/trinodb/trino/issues/15091
Initial work was started here: https://github.com/trinodb/trino/pull/9337

**Comment by ebyhr** [comment]
Spark can't read an ORC table that is partitioned by nested fields even when the table is created and rows are inserted by Spark. Also, Parquet table made by Trino has an issue - the nested field on the partitioned column somehow becomes null in Spark. 

Let me cancel to implement this enhancement. I will keep this ticket opened though.

**Comment by findepi** [comment]
> Spark can't read an ORC table that is partitioned by nested fields even when the table is created and rows are inserted by Spark.

@danielcweeks @rdblue is partitioning on nested fields supported by Iceberg?
