### ISSUE TITLE
Issue about `LATERAL VIEW EXPLODE` with experimental Hive views

### ISSUE THREAD

**Issue by OxanaKh** [trinodb/trino#15124]
Hi!
I have trino 400 installed and connected to Hive. I have tried to use experimental mode with LATERAL VIEW EXPLODE.
hive.hive-views.enabled=true
hive.hive-views.legacy-translation=false
...
from
    all_int LATERAL VIEW explode (all_opers) adTable AS exp
...

But I've this error
 mismatched input 'VIEW'. Expecting: '(', ',', 'CROSS', 'EXCEPT', 'FETCH', 'FULL', 'GROUP', 'HAVING', 'INNER', 'INTERSECT', 'JOIN', 'LEFT', 'LIMIT', 'MATCH_RECOGNIZE', 'NATURAL', 'OFFSET', 'ORDER', 'RIGHT', 'TABLESAMPLE', 'UNION', 'WHERE', 'WINDOW', <EOF>

**Comment by ebyhr** [comment]
Could you share the entire SELECT query and the view definition?

**Comment by OxanaKh** [comment]
Test example:

Hive:
CREATE TABLE `test_db.test_table`(
    `field1` string, 
    `field2` array<struct<str1:string,str2:string,str3:string,str4:string,oper1:int,oper2:int,str5:string>>)
PARTITIONED BY (  `date` string);

Trino 400:
select field1, field2
 from  "hive".test_db.test_table LATERAL VIEW explode (field2) Table AS field2

mismatched input 'VIEW'. Expecting: '(', ',', 'CROSS', 'EXCEPT', 'FETCH', 'FULL', 'GROUP', 'HAVING', 'INNER', 'INTERSECT', 'JOIN', 'LEFT', 'LIMIT', 'MATCH_RECOGNIZE', 'NATURAL', 'OFFSET', 'ORDER', 'RIGHT', 'TABLESAMPLE', 'UNION', 'WHERE', 'WINDOW', <EOF>

**Comment by ebyhr** [comment]
It seems there's a misunderstanding about Hive view translations. The config property for allowing to read complex Hive views, **_not_** for allowing Hive syntax in Trino.
