### ISSUE TITLE
better optimizer in converting the dynamic filtering predicates to a range 

### ISSUE THREAD

**Issue by eshirvana** [trinodb/trino#15136]
I have a postgrsql cte which i join with clickhouse view as below :

```
with postgrs_cte as (
   select id 
   from tablex 
  where ...
) 

,  history (
    select * from postgrs_cte
    join table_in_clickhouse  
       on id  = id
    where table_in_clickhouse.unixtimestamp between xx and yy
) 
```

the count of ids returned from `postgrs_cte` is ~300K rows (or unique ids)
however the trino push down the query below to clickhouse :
```
SELECT "id", "stamp", "value" 
FROM "history"."table_in_clickhouse" 
WHERE ("UnixStamp" >= 1637557200 AND "UnixStamp" < 1669006800) 
AND ("id" >= 725994922 AND "id" <= 1028102993)
```

which if you count distinct ids in that range it will return 71 M unique ids which is causing to fetch unnecessary data from clickhouse and slowing down my query significantly.

**Comment by findepi** [comment]
This is called "domain compaction".
We do this to avoid sending multi-MB or multi-GBs queries to the underlying system, as this usually doesn't work well.

You may tune this using `domain-compaction-threshold` catalog config property.

**Comment by raunaqmorarka** [comment]
Also discussed in https://trinodb.slack.com/archives/CGB0QHWSW/p1669053163417039
