### ISSUE TITLE
Delta-lake connector assumes paths to be URL encoded, but should be using URI encoding

### ISSUE THREAD

**Issue by jkylling** [trinodb/trino#15183]
Paths in Delta log actions are [URIs](https://www.ietf.org/rfc/rfc2396.txt) according to [the documentation](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#add-file-and-remove-file).

The delta-lake connector currently assumes paths are URL encoded: https://github.com/trinodb/trino/blob/1b934bf7406f0aee3f8969cc4e6df05f2a907b6c/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java#L293-L294

This prevents the delta-lake connector from querying some valid Delta tables. For instance, if a path in the Delta log contains a `+` this will be replaced with a space, and when Trino attempts to read the path from object store a 404 is returned.

Should we change this to use URIs instead? I believe this is what [delta-core does](https://github.com/delta-io/delta/blob/3488b212acd0a738ea6eaec177dab554662cb76f/core/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala#L415).

```java
String path = URI.create(addAction.getPath()).toString();
```
should do the trick.

**Comment by findepi** [comment]
@jkylling thank you for your issue.

would you want to contribute the fix?

**Comment by jkylling** [comment]
> @jkylling thank you for your issue.
> 
> would you want to contribute the fix?

Yes, I can contribute a fix.
