### ISSUE TITLE
the code of hdfs'parquet file reading?

### ISSUE THREAD

**Issue by LiuJiazhen1999** [trinodb/trino#15182]
Can anyone tell me where is the code of reading parquet file in hdfs？

**Comment by Praveen2112** [comment]
`trino-parquet` (https://github.com/trinodb/trino/tree/master/lib/trino-parquet) holds the code for reading parquet files. We might also need to check with ParquetPageSource (https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSource.java) provides an integration of parquet reader with Hive connector.

**Comment by hashhar** [comment]
Closing as answered. Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there or reopen if needed.
