### ISSUE TITLE
Unknown type void in Delta-lake connector 

### ISSUE THREAD

**Issue by jkylling** [trinodb/trino#15193]
Delta-tables can have columns of type [`void`](https://docs.databricks.com/sql/language-manual/data-types/null-type.html). DeltaLakeSchemaSupport does not handle this type
https://github.com/trinodb/trino/blob/17bf26ced3a6379d11c83cab669d733368e448d5/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java#L478-L505

Would it make sense to add a dependency on trino-main in trino-delta-lake and add
```java
            case "void":
                return UnknownType.UNKNOWN;
```
to the switch?

**Comment by findepi** [comment]
What problem are you trying to solve?

**Comment by jkylling** [comment]
> What problem are you trying to solve?

I want to query a delta-table which has a column of type `void`. Currently this is not possible.

**Comment by findepi** [comment]
I don't see "void" on https://github.com/delta-io/delta/blob/master/PROTOCOL.md#primitive-types

**Comment by jkylling** [comment]
> I don't see "void" on https://github.com/delta-io/delta/blob/master/PROTOCOL.md#primitive-types

Ah, okay. It seems to be a "feature" of Databricks. Running `CREATE TABLE default.void_table (x LONG, y VOID) USING DELTA` in the Databricks runtime will create a delta-table which it is possible to query. I'll raise an issue with delta-io on this to get a clarification.

**Comment by findepi** [comment]
@jkylling thank you for creating https://github.com/delta-io/delta/issues/1499

@dennyglee  do you know why Databricks deviates from Delta spec and allows some "void" type?
We can't support it if we don't know about it.

**Comment by dennyglee** [comment]
Thanks @jkylling for opening the issue.  @findepi I'm not sure, let get back to you and follow up on the @jkylling thread as well.
