### ISSUE TITLE
optimized DATE parsing and formatting by caching recent dates

### ISSUE THREAD

**Issue by ubyyj** [trinodb/trino#15229]
date parsing and formatting functions are widely used, and is expensive. After studying to our daily queries, most of them are parsing or formatting the recent dates, that means most of the function calls are dealing with the same input, which is not necessary, and can be improved with a cache.

so I'd like to proposal a PR to address this issue by cacheing the recent (like say last 10 years) date in a map.

the above mentioned functions are as below:
date(‘2022-10-14’)
date_parse(dt, '%Y-%m-%d')
cast(‘2022-10-14’ as date)
date_format(dt,'%Y-%m-%d')
format_datetime(dt, 'yyyy-MM-dd')

**Comment by findepi** [comment]
cc @lukasz-stec @raunaqmorarka @sopel39 @martint

**Comment by findepi** [comment]
Perhaps, instead of precomputing a bunch of "recent dates", we could have a fast path for dates following the ISO yyyy-MM-dd format strictly (eg with exactly two digits for month and day, and without any whitespace).

**Comment by sopel39** [comment]
@ubyyj would you like to work on that (or @findepi idea)?

**Comment by ubyyj** [comment]
yes, I'd like to work on this

**Comment by ubyyj** [comment]
prepared a PR https://github.com/trinodb/trino/pull/15548, may I ask you for reviewing?

**Comment by findepi** [comment]
Solved (without cache) by https://github.com/trinodb/trino/pull/15548
