### ISSUE TITLE
JWT issuer validation has slightly misleading error message.

### ISSUE THREAD

**Issue by tomrijntjes** [trinodb/trino#15236]
I'm using JWT. Enforcing the issuer does not seem to work correctly.

coordinator `config.properties`:
`http-server.authentication.jwt.required-issuer=https://login.microsoftonline.com/${tenant_id}/v2.0.`

```
error 401: b'Invalid credentials | Expected iss claim to be: 
https://login.microsoftonline.com/TENANT_ID/v2.0., but was: 
https://login.microsoftonline.com/TENANT_ID/v2.0.'
```

**Comment by lukasz-walkiewicz** [comment]
Is `.` at the end really a part of issuer url?

**Comment by tomrijntjes** [comment]
I tested, this is indeed the issue.

The error message should be `Expected iss claim to be: https://login.microsoftonline.com/TENANT_ID/v2.0, but was...` or `Expected iss claim to be: "https://login.microsoftonline.com/TENANT_ID/v2.0", but was...`

**Comment by lukasz-walkiewicz** [comment]
I believe it's correct. In the configuration you've provided:
`https://login.microsoftonline.com/TENANT_ID/v2.0.` so with `.` at the end. Whereas `.` at the end of the error message: `but was: 
https://login.microsoftonline.com/TENANT_ID/v2.0.` is just a part of the error message of the library we're using to parse JWTs https://github.com/jwtk/jjwt/blob/274749373f29108e777790351df4a0d45f63e64d/api/src/main/java/io/jsonwebtoken/ClaimJwtException.java#L25. You could try opening an issue in https://github.com/jwtk/jjwt if you think this error message should be improved.

**Comment by tomrijntjes** [comment]
I will do that, thanks for looking into it!
