### ISSUE TITLE
Load catalogs concurrently

### ISSUE THREAD

**Issue by BOFA1ex** [trinodb/trino#15234]
It took a long time to startup trino when catalog files were too many.

As I know, load plugins have been supported concurrently already.
see https://github.com/trinodb/trino/pull/9521

so why does ConnectManager#createCatalog modify with `sync`?
or does it have another way to improve catalog initialization?

**Comment by hashhar** [comment]
cc: @dain since you're working on dynamic catalogs already

**Comment by findepi** [comment]
> As I know, load plugins have been supported concurrently already.
> see #9521

When I was working on #9521 the whole catalog creation was synchronized https://github.com/trinodb/trino/blob/4b2565a98d622a5419263ba40fd0ae12ef077888/core/trino-main/src/main/java/io/trino/connector/ConnectorManager.java#L215, so it didn't make sense to run it in multiple threads.

This is no longer the case though, so -- https://github.com/trinodb/trino/pull/15295
