### ISSUE TITLE
Add test for Schema already exists error when creating a schema in hive

### ISSUE THREAD

**Issue by homar** [trinodb/trino#15282]
This [PR](https://github.com/trinodb/trino/pull/15177) was merged without a test as we didn't have an infrastructure for such tests at that time.
It was created in scope of https://github.com/trinodb/trino/pull/15198

It'd be good to add a test like this https://github.com/trinodb/trino/blob/21d723fd1335508221b5bdc98b96ca800cb2566c/plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueTableOperationsInsertFailure.java

**Comment by leeyh0216** [comment]
Hi @homar ,
I'm completely new in open-source and would like to begin!
Can you assign this issue to me?

**Comment by ebyhr** [comment]
#15328 added tests for Delta Lake connector.
