### ISSUE TITLE
SET TIME ZONE LOCAL does not work as documented

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#15314]
From 403's docs https://trino.io/docs/403/sql/set-time-zone.html

> If the LOCAL option is specified, the time zone for the current session is set to the initial time zone of the session.

Iinitial time zone is the client's default zone.

From the code:

https://github.com/trinodb/trino/blob/c05c73967185be545d01a8e1e7abb2d4dca9767b/core/trino-main/src/main/java/io/trino/execution/SetTimeZoneTask.java#L81

i.e. Trino server's default zone

### Expected

* clearly docs and code should be aligned
* intuitively, server's zone should be invisible to the client, so I think docs are right, not the code.

**Comment by findepi** [comment]
@leeyh0216 you can test this out with

1. start server in some zone, eg `America/Los_Angeles`
2. start CLI in some zone, eg. `Europe/Warsaw`
   - at this point, the session zone should be `Europe/Warsaw`
3. `SET TIME ZONE something`
   - after this, the session zone should be \<something>
4. `SET TIME ZONE LOCAL`
   - after this, the session zone should be (my assumption here) again `Europe/Warsaw`

You can see current session zone by doing
```
SELECT current_timestamp;
```

**Comment by leeyh0216** [comment]
@findepi 
Thanks, I understand it!!

After calling the `stateMachine.addSetSessionProperties(TIME_ZONE_ID, timeZoneId);` statement, the 'X-Trino-Session' value is set as 'time-zone-id={something}' in the client header, and this is registered as a SystemProperty in the HttpRequestSessionContextFactory.

And in QuerySessionSupplier, it looks SystemProperties first.
```
if (forcedSessionTimeZone.isPresent()) {
            sessionBuilder.setTimeZoneKey(forcedSessionTimeZone.get());
        }
        else {
            String sessionTimeZoneId = context.getSystemProperties().get(TIME_ZONE_ID);
            if (sessionTimeZoneId != null) {
                sessionBuilder.setTimeZoneKey(getTimeZoneKey(sessionTimeZoneId));
            }
            else {
                sessionBuilder.setTimeZoneKey(context.getTimeZoneId().map(TimeZoneKey::getTimeZoneKey));
            }
        }
```

I hope it will be of help.

**Comment by martint** [comment]
Per the SQL spec:

> If LOCAL is specified, then the current default time zone displacement of the current SQL-session is set to the original time zone displacement of the current SQL-session.
