### ISSUE TITLE
Remove redundant protobuf exclusions

### ISSUE THREAD

**Issue by Fokko** [trinodb/trino#15371]
When [bumping Iceberg from 1.0.0 to 1.1.0](https://github.com/trinodb/trino/pull/15079), we transitively bumped ORC from 1.7.x to 1.8.x. With 1.8.x comes protobuf files that shouldn't be packaged. These will be removed in ORC 1.8.2: https://issues.apache.org/jira/browse/ORC-1327 ([PR](https://github.com/apache/orc/pull/1334)).

**Comment by SergeySereda0218** [comment]
Hi Fokko,
Can you assign this issue to me?
Thanks in advance.

**Comment by tsafacjo** [comment]
is this issue still on going ?

**Comment by Fokko** [comment]
It looks like there is one occurrence that we can remove: https://github.com/Fokko/presto/blob/4177e3ba81abaf15194636b0b60fdd4a973b504c/plugin/trino-iceberg/pom.xml#L409-L410

**Comment by tsafacjo** [comment]
is this issue still on going ?
Can I take it ?

**Comment by Fokko** [comment]
@tsafacjo Certainly you can take it 👍 I think you can remove the lines I just referenced above.

**Comment by tsafacjo** [comment]
Ok.

**Comment by ebyhr** [comment]
Closing as https://github.com/trinodb/trino/commit/d6c257f8d65889fc9d935dd72012abadba59df31
