### ISSUE TITLE
Use enhanced switch statement

### ISSUE THREAD

**Issue by mx123** [trinodb/trino#15418]
Use enhanced switch statement in:

- io.trino.geospatial.serde.GeometrySerde#writeGeometry
- io.trino.plugin.deltalake.DeltaLakeMetadata#getTableHandleForExecute
- io.trino.plugin.iceberg.IcebergMetadata#getSnapshotIdFromVersion
- io.trino.plugin.deltalake.TestDeltaLakePageSink#getTrinoType

**Comment by mx123** [comment]
done with PR: [Use enhanced switch statement #15395](https://github.com/trinodb/trino/pull/15395)

**Comment by ebyhr** [comment]
@mx123 By the way, you don't need to file a GitHub issue for minor refactoring.
