### ISSUE TITLE
Document `postgresql.include-system-tables` config property

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#15424]
The property was added in version [320](https://trino.io/docs/current/release/release-320.html#postgresql-connector):

> PostgreSQL connector
Add support for reading PostgreSQL system tables, e.g., pg_catalog relations. The functionality is disabled by default and can be enabled using the postgresql.include-system-tables configuration property. ([#1527](https://github.com/trinodb/trino/issues/1527))

Relates to https://trinodb.slack.com/archives/CGB0QHWSW/p1671165424335919

**Comment by rohitemmadishetty** [comment]
Hi, I would like to contribute to this issue. What is a good starting point ?

**Comment by ebyhr** [comment]
You can update `docs/src/main/sphinx/connector/postgresql.rst`

**Comment by Ankan0011** [comment]
Hi, 
I have sometime to work on this issue, if this is still up for grabs.
Thank you.
