### ISSUE TITLE
Use Apache ORC library in OrcTester

### ISSUE THREAD

**Issue by mx123** [trinodb/trino#15420]
Use Apache ORC library to create dynamically content instead of relying on a test resource file:

https://github.com/trinodb/trino/blob/fe608f2723842037ff620d612a706900e79c52c8/lib/trino-orc/src/test/java/io/trino/orc/TestOrcLz4.java#L39

**Comment by findepi** [comment]
> on a test resource file:

relying on a test resource files has advantages when testing file formats.

a new version of library may be writing files differently, but we remain committed to supporting files written by old versions.
