### ISSUE TITLE
Unexpected value parsed in configuration when line contains trailing spaces

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#1546]
For config file like this:
```
hive.non-managed-table-writes-enabled=true 
```
(I guess you easily noticed the space character at the of the value)

The property `hive.non-managed-table-writes-enabled` is assigned a `false` value.
Direct cause is that `Boolean.valueOf("true ") == false`.
This causes bad user experience.

(Side note: when `launcher` reads the properties, it doesn't fall into this trap, as it `string.strip()` all the values (https://github.com/airlift/airlift/issues/633, https://github.com/airlift/airlift/blob/master/launcher/src/main/scripts/bin/launcher.py#L46-L48))

**Comment by findepi** [comment]
this is a copy of https://github.com/airlift/airlift/issues/738
I am making this copy because this issue affects Presto users directly.

**Comment by findepi** [comment]
Will be fixed when we upgrade to airlift 0.185

**Comment by hashhar** [comment]
Fixed in f6676e42e356b5b23c0b7684822417388bae1641
