### ISSUE TITLE
Add `register_table` and `unregister_table` procedures in Iceberg REST catalog

### ISSUE THREAD

**Issue by krvikash** [trinodb/trino#15512]
Iceberg RESTSessionCatalog Implementation has been merged. Add `register_table` procedure support with RESTSessionCatalog in the iceberg connector.

https://github.com/trinodb/trino/blob/4865a16ed535c7843ac6b979a37dfe4813b2dc4d/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java#L209-L212

Reference:
Add `register_table` procedure support for iceberg table #14375
Add Iceberg RESTSessionCatalog Implementation #13294

**Comment by AKARSHITJOSHI** [comment]
@krvikash I would like to contribute on this, could please tell where to take reference so that I can get started.
Thanks.

**Comment by krvikash** [comment]
@AKARSHITJOSHI thanks for your interest. Iceberg connector supports `register_table` procedure with Hive and Glue catalog. we have to add this support with RESTSession catalog as well.

You can see how `registerTable` is implemented for Hive and Glue catalogs and Implement for RESTSession catalog [here](https://github.com/danielcweeks/trino/blob/47bdeae92560d7556486b13f2e0fbbb79cbd4c8b/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java#L209).

https://github.com/krvikash/trino/blob/cfcfbd0d2b4c48d42b7ddf78e251c1dd6ddc9936/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java#L271

https://github.com/krvikash/trino/blob/cfcfbd0d2b4c48d42b7ddf78e251c1dd6ddc9936/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java#L376

Please feel free to comment here if you have any doubts.

**Comment by AKARSHITJOSHI** [comment]
@krvikash I am unable to setup Trino on my local environment. If there is any guide for setting it up using Docker please tell
reason being I'm using JDK:1.8.

**Comment by ebyhr** [comment]
@AKARSHITJOSHI This is the guideline. You need Java 17.0.4+. 
* https://github.com/trinodb/trino#build-requirements
* https://github.com/trinodb/trino/blob/master/.github/DEVELOPMENT.md

**Comment by AKARSHITJOSHI** [comment]
Hi, for [GlueCatalog](https://github.com/krvikash/trino/blob/cfcfbd0d2b4c48d42b7ddf78e251c1dd6ddc9936/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java#L271) we use createTable whereas it is not defined in TrinoRestCatalog. Also for [TrinoHiveCatalog](https://github.com/krvikash/trino/blob/cfcfbd0d2b4c48d42b7ddf78e251c1dd6ddc9936/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java#L376) we use metastore to create the table
which is not present for TrinoRestCatalog.
Should I implement the stated above or is there any other way to implement the functionality.
PS: Thanks

**Comment by krvikash** [comment]
Hi @AKARSHITJOSHI, You can try exploring the `restSessionCatalog` API.

**Comment by AKARSHITJOSHI** [comment]
> here
RESTSessionCatalog has build table L:279 but it requires Schema type object not SchemaTable, whereas registTable will 
throw Exception. Is there any way to convert to SchemaTableName to SchemaTable ?

**Comment by krvikash** [comment]
Hi @AKARSHITJOSHI, I have opened a PR https://github.com/apache/iceberg/pull/6512 in the iceberg library to support `registerTable` API in `RESTSessionCatalog`. Once it is available and used in trino, you can resume your work on this.

**Comment by ebyhr** [comment]
I included `unregister_table` procedure to this issue scope.
