### ISSUE TITLE
When hive plugin uses FileHiveMetastore, if FTPFileSystem is connected to the FTP server in linux, the table fails to be created because the '.${schema}.trinoSchema' file is hidden

### ISSUE THREAD

**Issue by c8679724** [trinodb/trino#15535]
When hive plugin uses FileHiveMetastore, if FTPFileSystem is connected to the FTP server in linux, the table fails to be created because the '.${schema}.trinoSchema' file is hidden，Need to modify the org, apache hadoop. Fs. FTP. FTPFileSystem the connect () method,
Let's change：
        client = new FTPClient();
        client.connect(host, port);
To：
        client = new FTPClient();
        client.setListHiddenFiles(true);
        client.connect(host, port);

**Comment by ebyhr** [comment]
Closing as the purpose of `FileHiveMetastore` is test, not production use case.

**Comment by c8679724** [comment]
We still expect trino's FileHiveMetastore to be productively ready. When we use trino as etl function, we need to use FileHiveMetastore to support writing data to the file system. Writing to ftp is for some batch business delivered to the business system team. oss is written to back up data.

**Comment by c8679724** [comment]
@ebyhr We still expect trino's FileHiveMetastore to be productively ready. When we use trino as etl function, we need to use FileHiveMetastore to support writing data to the file system. Writing to ftp is for some batch business delivered to the business system team. oss is written to back up data.
