### ISSUE TITLE
Expired slack invite link

### ISSUE THREAD

**Issue by mayurnewase** [trinodb/trino#15534]
Slack invitation link on readme is expired.
Wanted to join the community.

**Comment by ebyhr** [comment]
@mayurnewase Could you try https://join.slack.com/t/trinodb/shared_invite/zt-1mc4u9olv-8EV8SNCEzFF24_DhvUxmiw?

**Comment by mayurnewase** [comment]
thanks, I am in.
you may wanna put this in readme.

**Comment by mayurnewase** [comment]
will keep this open in case you wanna close this after updating readme.

**Comment by ebyhr** [comment]
This will be fixed by https://github.com/trinodb/trino.io/pull/396
