### ISSUE TITLE
Upgrade jgrapht library to a newer version

### ISSUE THREAD

**Issue by rohanag12** [trinodb/trino#15547]
The `trino-main` module depends on the [jgrapht](https://jgrapht.org/) library in some implementations of the ExecutionSchedule interface. The trino project depends on a really old version of this library `0.9.0`, which was released in 2013. There is a newer version `1.5.1` available, which was released in 2021. I am trying to use Trino in a project that already uses new version of jgrapht and running into dependency conflicts because there are some breaking changes to the jgrapht API between versions `0.9.0` and `1.5.1`.

Is there any particular reason for not moving to the latest version of jgrapht? Given the scope of jgrapht usage in the Trino project is quite limited, it seems simple to upgrade. I can submit a PR if there are no objections to upgrading jgrapht.

Thanks!

**Comment by ebyhr** [comment]
The dependency was removed in #15657
