### ISSUE TITLE
Hudi Connector performance issues while querying partitioned tables

### ISSUE THREAD

**Issue by Wrekkers** [trinodb/trino#15564]
Our team is testing the Hudi Connector on COPY ON WRITE HUDI tables. And we observed that the hudi connector in general performs poorly while querying partitioned tables, with or without metadata enabled. The query supposedly takes time in the state of `Creating InMemory based view for basePath`. Through the coordinator logs we see that query takes 1-2 mins after loading the metadata table to load the file system views using `AbstractTableFileSystemView`.

From seeing the explain plan of the query on Trino we could see that there were no specific filters on the partition column despite providing specific partition column values. Whereas if we do the same through the hive connector then it returns the specified values in the explain plan itself.

**Query:**
```
SELECT id 
FROM hudi.<schema_name>.<table_name>
WHERE insert_ds_ist in ('2022-12-12', '2022-12-11', '2022-12-01', '2022-12-02', '2022-12-03') 
LIMIT 12
```
**Explain Plan:**
`Fragment 0 [SINGLE] Output layout: [id] Output partitioning: SINGLE [] Output[columnNames = [id]] │ Layout: [id:bigint] │ Estimates: {rows: 12 (108B), cpu: 0, memory: 0B, network: 0B} └─ Limit[count = 12] │ Layout: [id:bigint] │ Estimates: {rows: 12 (108B), cpu: 108, memory: 0B, network: 0B} └─ LocalExchange[partitioning = SINGLE] │ Layout: [id:bigint] │ Estimates: {rows: 12 (108B), cpu: 0, memory: 0B, network: 0B} └─ RemoteSource[sourceFragmentIds = [1]] Layout: [id:bigint] Fragment 1 [SOURCE] Output layout: [id] Output partitioning: SINGLE [] LimitPartial[count = 12] │ Layout: [id:bigint] │ Estimates: {rows: 12 (108B), cpu: 108, memory: 0B, network: 0B} └─ TableScan[table = hudi:<schema_name>.<table_name>] Layout: [id:bigint] Estimates: {rows: ? (?), cpu: ?, memory: 0B, network: 0B} id := id:bigint:REGULAR`

**Explain Plain for same query through Hive connector:**
`Fragment 0 [SINGLE] Output layout: [id] Output partitioning: SINGLE [] Output[columnNames = [id]] │ Layout: [id:bigint] │ Estimates: {rows: 12 (108B), cpu: 0, memory: 0B, network: 0B} └─ Limit[count = 12] │ Layout: [id:bigint] │ Estimates: {rows: 12 (108B), cpu: 108, memory: 0B, network: 0B} └─ LocalExchange[partitioning = SINGLE] │ Layout: [id:bigint] │ Estimates: {rows: 12 (108B), cpu: 0, memory: 0B, network: 0B} └─ RemoteSource[sourceFragmentIds = [1]] Layout: [id:bigint] Fragment 1 [SOURCE] Output layout: [id] Output partitioning: SINGLE [] LimitPartial[count = 12] │ Layout: [id:bigint] │ Estimates: {rows: 12 (108B), cpu: 108, memory: 0B, network: 0B} └─ TableScan[table = hive:<schema_name>.<table_name>] Layout: [id:bigint] Estimates: {rows: ? (?), cpu: ?, memory: 0B, network: 0B} id := id:bigint:REGULAR insert_ds_ist:string:PARTITION_KEY :: [[2022-12-01], [2022-12-02], [2022-12-03], [2022-12-11], [2022-12-12]]`

Query runtime:
Hudi Connector: 1 - 2 mins
Hive connector: 4-6 secs

Trino version: 405
HUDI Table version: 0.10.1
Spark Version: 2.4

**Trino Hudi Connector Properties:**
```
connector.name=hudi
hive.metastore.uri={METASTORE_URI}
hive.s3.iam-role={S3_IAM_ROLE}
hive.metastore-refresh-interval=2m
hive.metastore-timeout=3m
hudi.max-outstanding-splits=1000
hive.s3.max-error-retries=50
hive.s3.connect-timeout=1m
hive.s3.socket-timeout=2m
hudi.parquet.use-column-names=true
hudi.metadata-enabled=true
```

**Hudi Properties set while writing:**
```
hoodie.datasource.write.partitionpath.field = "insert_ds_ist",
hoodie.datasource.write.recordkey.field = "id",
hoodie.datasource.write.precombine.field = "_hoodie_incremental_key", (self generated column),
hoodie.datasource.write.hive_style_partitioning = "true",
hoodie.datasource.hive_sync.auto_create_database = "true",
hoodie.parquet.compression.codec = "gzip",
hoodie.table.name = "<table_name>",
hoodie.datasource.write.keygenerator.class = "org.apache.hudi.keygen.SimpleKeyGenerator",
hoodie.datasource.write.table.type = "COPY_ON_WRITE",
hoodie.metadata.enable = "true",
hoodie.datasource.hive_sync.enable = "true",
hoodie.datasource.hive_sync.partition_fields = "insert_ds_ist",
hoodie.datasource.hive_sync.partition_extractor_class = "org.apache.hudi.hive.MultiPartKeysValueExtractor"
```

**General information of table:**
Total rows = 3,784,911,511
Total Partitions = 1700+
Total file objects = ~ 18,000
Total Size on S3 =  ~100 GB

**Coordinator logs for the query:**
[Partitioned_COW_HUDI_Table_Trino400.log](https://github.com/trinodb/trino/files/10323705/Partitioned_COW_HUDI_Table_Trino400.log)

**Comment by codope** [comment]
@Wrekkers This regression is a known issue. It's due to a change in Hudi code itself. Do you still see with the latest connector version (note that connector [v400 uses Hudi 0.11.1 ](https://github.com/trinodb/trino/blob/400/plugin/trino-hudi/pom.xml#L18)and the latest master branch uses Hudi 0.12.1 where this regression should be addressed).

**Comment by ebyhr** [comment]
Reposting the reply from Slack
> I did try with master branch but the performance is same

https://trinodb.slack.com/archives/CGB0QHWSW/p1672411985584459?thread_ts=1670837630.507929&cid=CGB0QHWSW

**Comment by BruceKellan** [comment]
Has this problem been solved? We also had this problem.

**Comment by codope** [comment]
@Wrekkers @BruceKellan I have a working patch with performance improvement: https://github.com/codope/trino/pull/23
I still need to make minor changes but I have tested it with a dataset having ~2k partitions to validate the performance gains. Could you please try as well in your environment?

**Comment by Wrekkers** [comment]
@codope Thank you, I tried with the patch and it does significantly improve the performance
