### ISSUE TITLE
timestamp query no longer working in 405, gives option to use int64 instead of just using option

### ISSUE THREAD

**Issue by EMCP** [trinodb/trino#15572]
Starting in Trino version 405, I have gotten the following error with my query

query done via python with library `v0.320.0` : 

```python
QUERY_TO_EXECUTE = """SELECT a.sec_type, a.contract_id, a.query_start_time, a.symbol, a.currency, a.primary_exchange, a.exchange
FROM ibtickers a
LEFT OUTER JOIN ibtickers b ON a.contract_id = b.contract_id AND a.query_start_time < b.query_start_time
WHERE b.contract_id IS NULL ORDER BY a.query_start_time desc"""
```

This query worked against version 403

Error against version 405:

> `trino.exceptions.TrinoUserError: TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="Unsupported Trino column type (timestamp(3)) for Parquet column ([query_start_time] optional int64 query_start_time)", query_id=20221231_063812_00001_4bwdf)`

My guess is, in past versions like 403, the default behavior was to simply run the query.. but now it is giving me this prompt.. I guess my question is how do I tell trino to go ahead and return long ?

https://github.com/trinodb/trino/pull/15204 related perhaps ? 

Thank you

**Comment by raunaqmorarka** [comment]
You can get back the previous behaviour using `parquet.optimized-reader.enabled=false` or setting catalog session property `parquet_optimized_reader_enabled` to false.
You could also change the data type of the column to a BIGINT and cast to timestamp explicitly if needed.
Could you share the full error stacktrace ? Also, how are these files written ? (A sample file with this data type would be great).
I suspect that the parquet file here does not specify a timestamp annotation. So if we try to read it as a timestamp(3), and a timestamp logical annotation is not found, then we don't know what unit we're dealing with in the parquet file.
The new optimized parquet reader behaviour is more in line with the parquet spec https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#time
I think the old code can give incorrect results if the data in the file is not of micros unit or if the values require rounding to a lower precision. So I'm sure that we want to restore old behaviour even though it is possible to do so in the optimized reader as well.
fyi @martint @findepi @skrzypo987

**Comment by EMCP** [comment]
appending a sample file.. it appears the schema of the parquet file is a LONG... and in the hive-metastore we utilize `TIMESTAMP` 

[20221230_190308-890906.snappy.parquet.txt](https://github.com/trinodb/trino/files/10331746/20221230_190308-890906.snappy.parquet.txt)

NOTE: RENAME FROM `.txt` to just `.parquet`, github doesn't seem to allow parquet files to be uploaded in tickets

the .sql file used to set the HIVE-Metastore

```
CREATE SCHEMA IF NOT EXISTS hive.stonks WITH (location='s3a://SOMEBUCKET/');

USE hive.stonks;

CREATE TABLE IF NOT EXISTS hive.stonks.stonks (
                 sec_type           VARCHAR,
                 currency           VARCHAR,
                 symbol             VARCHAR,
                 contract_id        BIGINT,
                 exchange           VARCHAR,
                 primary_exchange   VARCHAR,
                 query_start_time   TIMESTAMP)
               WITH (
                 external_location = 's3a://SOMEBUCKET/SOMEDIR/',
                 format = 'PARQUET');

CREATE VIEW stonks_view AS SELECT * FROM stonks;

```

**Comment by raunaqmorarka** [comment]
Thanks for sharing the file
I've verified that it's missing parquet timestamp logical annotation. Most likely the tool you're using to produce the file needs to somehow be made aware that it is writing a timestamp, so that it can add the appropriate annotations into the parquet file schema.
I've checked that Apache Hive also throws an error when trying to read such a file
```
Failed with exception java.io.IOException:org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.ClassCastException: org.apache.hadoop.io.LongWritable cannot be cast to org.apache.hadoop.hive.serde2.io.TimestampWritable
```
Same for Apache Spark
```
Caused by: org.apache.spark.sql.execution.QueryExecutionException: Parquet column cannot be converted in file hdfs://hadoop-master:9000/user/hive/warehouse/time-test/20221230_190308-890906.snappy.parquet. Column: [query_start_time], Expected: timestamp, Found: INT64
```
So I'm going to close this as it looks like the new optimized parquet reader is doing the right thing here.

**Comment by EMCP** [comment]
understood and thanks for the checkup with the file @raunaqmorarka 

I am googling to find to perhaps append this annotation in some post processing but not seeing anything yet.. is this page what I can refer to https://docs.informatica.com/data-integration/powerexchange-adapters-for-informatica/10-4-1/powerexchange-for-microsoft-azure-blob-storage-user-guide/data-type-reference/parquet-data-types-and-transformation-data-types.html ?

I'll attempt to see if modifying the meltano data type will yield a proper field as well.  thanks again

**Comment by EMCP** [comment]
@raunaqmorarka one last request, do you happen to have a .parquet file with this new format ? it seems under the hood that meltano tap uses pyarrow.. so I think it's quite straightforward if I get a look at what I am trying to output

**Comment by raunaqmorarka** [comment]
[sample_parquet.txt](https://github.com/trinodb/trino/files/10332940/sample_parquet.txt)

@EMCP see the attached file (ignore the .txt extension)

**Comment by nahyeon-an** [comment]
@raunaqmorarka Hi, I have the same issue. 
I'm trying to upgrade trino version from 399 to 471, and the same problems reading hive table with parquet format happen.
I can't find `parquet.optimized-reader.enabled=false `option in trino 471. 
Could you help me with this problem..??

**Comment by raunaqmorarka** [comment]
@nahyeon-an I think you should change the data type of the column to a BIGINT in the table definition and cast to timestamp explicitly if needed in the query.
Without the logical annotation, the engine cannot know the unit of the timestamp data in the file, so we wouldn't know if the values require scaling or if the values require rounding to a lower precision. Making assumptions can lead to incorrect results, so you should either change the writer to produce the correct timestamp logical annotation or use BIGINT type in table definition.
