### ISSUE TITLE
Blocking predicate pushdown through project operator with filter() function

### ISSUE THREAD

**Issue by sungheun** [trinodb/trino#15604]
Currently, `filter()` function is treated as non-deterministic function, and it prevents additional optimization opportunities such as predicate pushdown through projection.
Looking at the implementation of `filter()` function, it works in a deterministic way, so it should be okay to be marked as deterministic function, which enables more optimizations.

\<Example query>
In the query below, the filter `expr > 5` cannot be pushed down to a subquery because `filter()` function is considered as non-deterministic function. If the filter can be evaluated prior to the projection, it would be beneficial if the filter is selective and there are many number of projection columns.

```
select *
from 
(select ..., cardinality(filter(arr1, p -> p is not null)) + cardinality(filter(arr2, p -> p is not null)) as expr
from array_table) subq
where expr > 5;
```

**Comment by findepi** [comment]
> Currently, `filter()` function is treated as non-deterministic function

it might be a mistake from when the function was first added (9f91a9551fe50afa074b5d6d1b505a207014b9c5).
@sungheun do you want to make a PR changing that?
