### ISSUE TITLE
PrestoSQL 341 update trino 405 hive bug

### ISSUE THREAD

**Issue by qianmoQ** [trinodb/trino#15617]
source sql

```sql
select count() from (
select ymd,uid,split_part(split_part(cast(record_time as varchar),' ',2),':',1) hour
from dlabroaddv.view_dlabroad_app_presto 
where ymd='20230105' 
and regexp_replace(split_part(cast(record_time as varchar),' ',1),'-','')='20230105' 
and eid='dlabroad_app_heartbeat' 
group by ymd,uid,split_part(split_part(cast(record_time as varchar),' ',2),':',1)
);
```

prestosql 341 result

```
 _col0
-------
 14662
(1 row)

Query 20230105_145408_00464_jw7hq, FINISHED, 2 nodes
Splits: 520 total, 520 done (100.00%)
0:04 [390K rows, 113MB] [103K rows/s, 29.6MB/s]
```

trino 405 result

```
 _col0
-------
  9634
(1 row)

Query 20230105_145321_00001_r2kn3, FINISHED, 1 node
Splits: 391 total, 391 done (100.00%)
11.47 [388K rows, 112MB] [33.8K rows/s, 9.76MB/s]
```

catalog configure

```
connector.name=hive-hadoop2
hive.config.resources=/etc/ecm/hadoop-conf/core-site.xml, /etc/ecm/hadoop-conf/hdfs-site.xml
hive.metastore.uri=thrift://xxx
hive.allow-drop-table=false
hive.allow-rename-table=false
hive.ignore-absent-partitions=true
hive.recursive-directories=true
hive.metastore-timeout=3m
hive.max-partitions-per-scan=1000000
parquet.ignore-statistics=true
```

hive version 3.1.x

table format TEXTFILE

**Comment by findepi** [comment]
what is the simplest query with which you get different results?

**Comment by qianmoQ** [comment]
> 

```sql
select count() from (select ymd,uid,split_part(split_part(cast(record_time as varchar),' ',2),':',1) hour from dlabroaddv.view_dlabroad_app_presto where ymd='20230105' and regexp_replace(split_part(cast(record_time as varchar),' ',1),'-','')='20230105' and eid='dlabroad_app_heartbeat' group by ymd,uid,split_part(split_part(cast(record_time as varchar),' ',2),':',1))
```

The parsing TEXTFILE exception was caused by the version problem, so far I have not found out whether it is caused by which jar

**Comment by qianmoQ** [comment]
```sql
select count() from dlabroaddv.view_dlabroad_app_presto where ymd='20230105' and  eid='dlabroad_app_heartbeat';
```
Trino 
![image](https://user-images.githubusercontent.com/20521442/210834403-4482d791-6a4a-4984-ac57-9ce49ea229d5.png)

Presto 
![image](https://user-images.githubusercontent.com/20521442/210834511-e55d1a43-4edf-46c3-a8b4-d73cfb5af6f4.png)

This sql fetch data is consistent, add this condition `regexp_replace(split_part(cast(record_time as varchar),' ',1),'-','')='20230105'`, the data is abnormal

**Comment by qianmoQ** [comment]
![image](https://user-images.githubusercontent.com/20521442/210838384-2cb4f336-4791-4672-b581-e9a063c1f5f5.png)
![image](https://user-images.githubusercontent.com/20521442/210838466-217e5219-e65d-4849-9065-e8cd131b5843.png)
Oddly enough, the time zones are the same, but the query data shows a time zone difference

**Comment by qianmoQ** [comment]
I get to the heart of the problem. In trino, `from_unixtime` returns a time zone, while in prestosql, `from_unixtime` does not return any time zone

![image](https://user-images.githubusercontent.com/20521442/210840643-a0c5b9c8-d1ff-4197-aad4-af1fe610ffcf.png)
![image](https://user-images.githubusercontent.com/20521442/210840707-0db832db-118b-4805-b85f-789b949d7fc3.png)

**Comment by ebyhr** [comment]
It was changed in https://github.com/trinodb/trino/pull/7460 and returning timestamp with time zone is the expected code now.
