### ISSUE TITLE
Security issue with access control: column masking gets lost when querying only nested field

### ISSUE THREAD

**Issue by weiatwork** [trinodb/trino#15659]
We found a security issue with access control. Here's the repro

Create a table with a struct column and load some data:
```
use memory.default;
create table nestedtable (buyer row(customerId varchar), purchaseId varchar);
INSERT into nestedtable SELECT ROW('a') as buyer, 'p1';
INSERT into nestedtable SELECT ROW('b') as buyer, 'p2';
INSERT into nestedtable SELECT ROW('c') as buyer, 'p3';
```
Apply a file-based access control policy as such:
```
{
    "tables": [
        {
            "catalog": "memory",
            "schema": "default",
            "table": "nestedtable",
            "privileges": ["SELECT"],
            "columns" : [
                {
                    "name": "purchaseId",
                    "allow": true
                },
                {
                    "name": "buyer",
                    "mask": "if (purchaseId <> 'p3', buyer)"
                }
            ]
        }
    ]
}
```
Now run some queries
```
-- Correct
trino:default> select * from nestedtable;
     buyer      | purchaseid
----------------+------------
 {customerid=b} | p2
 NULL           | p3
 {customerid=a} | p1

-- Correct
trino:default> select buyer from nestedtable;
     buyer
----------------
 {customerid=a}
 {customerid=b}
 NULL
(3 rows)

-- Correct
trino:default> select buyer.customerid, buyer from nestedtable;
 customerid |     buyer
------------+----------------
 NULL       | NULL
 a          | {customerid=a}
 b          | {customerid=b}

-- Wrong
trino:default> select buyer.customerid from nestedtable;
 customerid
------------
 c <<< No content from column "buyer" should be exposed for this row
 b
 a
```
Based on the plan below, we can tell that when only nested subfield is queried, certain "unneeded" projected column gets pruned, in this case "buyer" (and its masking).
```
trino:default> explain select buyer.customerid from nestedtable;
                                                          Query Plan
-------------------------------------------------------------------------------------------------------------------------------
 Trino version: dev
 Fragment 0 [SOURCE]
     Output layout: [expr_0]
     Output partitioning: SINGLE []
     Output[columnNames = [customerid]]
     │   Layout: [expr_0:varchar]
     │   Estimates: {rows: 3 (165B), cpu: 0, memory: 0B, network: 0B}
     │   customerid := expr_0
     └─ ScanProject[table = memory:0]
            Layout: [expr_0:varchar]
            Estimates: {rows: 3 (165B), cpu: 165, memory: 0B, network: 0B}/{rows: 3 (165B), cpu: 165, memory: 0B, network: 0B}
            expr_0 := "buyer"[1]
            buyer := 0
```
The pruning is done at `PruneProjectColumns`. We believe this is wrong. Some mechanism should be added to tell whether a ProjectNode is for masking, and we should always retain that ProjectNode to be on the safe side.

**Comment by martint** [comment]
Can you paste the plan for `select buyer.customerid, buyer from nestedtable`?

**Comment by martint** [comment]
The dereference should happen on the result of the mask expression, so there’s probably something else going on.

**Comment by weiatwork** [comment]
@martint Thanks for the quick response! Sure, thanks to the existence of `buyer` column on the SELECT, the masking was intact.
```
trino:default> explain select buyer.customerid, buyer from nestedtable;
                                                            Query Plan
----------------------------------------------------------------------------------------------------------------------------------
 Trino version: dev
 Fragment 0 [SOURCE]
     Output layout: [expr, buyer]
     Output partitioning: SINGLE []
     Output[columnNames = [customerid, buyer]]
     │   Layout: [expr:varchar, buyer:row(customerid varchar)]
     │   Estimates: {rows: 3 (330B), cpu: 0, memory: 0B, network: 0B}
     │   customerid := expr
     └─ Project[]
        │   Layout: [buyer:row(customerid varchar), expr:varchar]
        │   Estimates: {rows: 3 (330B), cpu: 330, memory: 0B, network: 0B}
        │   expr := "buyer"[1]
        └─ ScanProject[table = memory:0]
               Layout: [buyer:row(customerid varchar)]
               Estimates: {rows: 3 (165B), cpu: 330, memory: 0B, network: 0B}/{rows: 3 (165B), cpu: 165, memory: 0B, network: 0B}
               buyer := (CASE WHEN ("purchaseid" <> VARCHAR 'p3') THEN "buyer" END)
               purchaseid := 1
               buyer := 0
```

**Comment by findepi** [comment]
cc @kokosing @Praveen2112 @lukasz-walkiewicz

**Comment by weiatwork** [comment]
> The dereference should happen on the result of the mask expression, so there’s probably something else going on.

That's true. And indeed some later optimization breaks this contract, specifically `PushDownDereferenceThroughProject`. With this rule disabled for the query, we get the correct plan/result. Now we need to find a way to skip processing the dereferences whose base expression has masking.

But in general, given the way how column/row level security is implemented, we want to make sure all optimization rules are "mask/filter aware", meaning they shouldn't make violating plan transformations that will void the security masking/row filtering.

**Comment by martint** [comment]
That's a correctness bug, then. Regardless of whether there is a mask expression or a regular projection, anything that depends on the result of that expression cannot be pushed through it unless it's guaranteed that it won't change semantics. Rules don't need to be "mask/filter aware" -- they need to implement semantically correct transformations and not undo the effect of such expressions.

**Comment by martint** [comment]
My guess is that it's related to the aliasing of symbols associated with the transformed column (`buyer = (CASE WHEN ("purchaseid" <> VARCHAR 'p3') THEN "buyer" END)`. It's probably triggering a bug in that rule.

**Comment by weiatwork** [comment]
What about bailing out this rule as long as the base expression is not an identity projection itself in the child node?
