### ISSUE TITLE
Queries fail when ASYNC caching is enabled

### ISSUE THREAD

**Issue by realknorke** [trinodb/trino#15687]
Different queries fail when caching is enabled and caching mode is ASYNC.
With caching disabled or caching mode `READ_THROUGH` everything works fine.

Affected versions v403 (moderate impact), v405 (consistent failures) - v402 and below is _not affected_

Please find the complete exception/stack trace, a minimal example, cluster configs, query plans etc. in [Trino Slack](https://trinodb.slack.com/archives/CGB0QHWSW/p1673342076360999).

To (reliably) reproduce the problem I had to clear the cache while restarting worker nodes in the cluster.

The problem is independent from the cluster size. I mostly tested with 4 worker, sometimes 1 worker, sometimes 20…

Apologies for the huge amount of text. :/

**Comment by realknorke** [comment]
Error still present in v430…

**Comment by realknorke** [comment]
Using the new S3 native code will not trigger that error.
```
fs.native-s3.enabled=true
s3.region=us-east-1
s3.aws-access-key=…
```

**Comment by electrum** [comment]
We plan to deprecate Rubix and replace it with [Alluxio caching](https://github.com/trinodb/trino/pull/18719).
