### ISSUE TITLE
Delta Lake transaction log stores `blindAppend` field unlike Spark `isBlindAppend`

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#15683]
`isBlindAppend` field in `io.trino.plugin.deltalake.transactionlog.CommitInfoEntry` needs fix. 

Trino example
```
{"commitInfo": ... "blindAppend":true}}
```

Spark example
```
{"commitInfo": ... "isBlindAppend":false}}
```

**Comment by MaruthiKo** [comment]
Hii, I would love to work on this issue
Could you elaborate on how to get started

**Comment by ebyhr** [comment]
@MaruthiKo Hi, I would recommend looking `CommitInfoEntry` class.
