### ISSUE TITLE
Support connecting to Kerberos secured MongoDB

### ISSUE THREAD

**Issue by kranthikiran01** [trinodb/trino#1573]
Current mongodb connector only supports username and password. I believe that implementing this is easier after #1183 PR. Let me know if you need help with integrating this for mongodb. I am in need of this.

**Comment by RameshByndoor** [comment]
@ebyhr Can you assign this to me

**Comment by academy-codex** [comment]
Can we incorporate #8591 and provide a more better fix here ?
@ebyhr @RameshByndoor
