### ISSUE TITLE
Improve the performance of Count(*) utilizing Iceberg table metrics

### ISSUE THREAD

**Issue by osscm** [trinodb/trino#15745]
**Main issue:** https://github.com/trinodb/trino/issues/10974

Borrowed from the Main issue.  

### Purpose

This issue is aimed to have a basic optimize rule for count(*) queries on the connectors having accurate table/partitions/columns statistics, like Iceberg composed of Orc/Parquet files.

### Reason

Nowadays, most storage engines or self-describing files are storing table level/partition level/column level statistics to supply a more effective ability of data retrieval, e.g. Iceberg, hive.

We know that Iceberg is now supporting Orc/Parquet files, of which table metrics are aggregated from each data file, therefore it's table metrics is trustworthy for calculating count(*), no matter the stored data is written by Trino or Spark, hence we can manually construct the results, for the queries only with count aggregations, from metadata.

For example, for query select count(*) from test, if the count at the file level is precomputed statistics then the result can be computed from these stats instead of the reading the Orc/Parquet files.
The files to be considered will be based on the partition filter, as in case of Iceberg we have feature to use partition for predicate pushdown. So, it will be possible to get the count(*) stats with partition filter as well.
For example:

`SELECT count(*) FROM tbl WHERE part_col=1` 
 

### Conclusion

Trino connector framework supports aggregation pushdown, so we will use it to support count(*) to start with.
This will be extended to support min(C)/max(C) as well.

There will be a flag to enable this feature.

**Comment by findepi** [comment]
FWIW https://github.com/trinodb/trino/pull/19303 should improve performance for `count(*)` queries (without a filter, or when filtering over partition values), so will close this issue. If the simple solution delivered so far doesn't need performance expectations (there still is a split per file), let's reopen or create new issue,

The more elaborate aggregation pushdown needs (https://github.com/trinodb/trino/issues/10974) remains open.
