### ISSUE TITLE
New window function: RLE ID

### ISSUE THREAD

**Issue by MichaelChirico** [trinodb/trino#1576]
Nomenclature comes from R:

```
$R
(x = rep(letters[1:3], 3:1))
# [1] "a" "a" "a" "b" "b" "c"
rle(x)
# Run Length Encoding
#   lengths: int [1:3] 3 2 1
#   values : chr [1:3] "a" "b" "c"
```

`rleid` is a quite useful function from `data.table` that I find myself doing quite awkwardly in SQL:

```
data.table::rleid(x)
# [1] 1 1 1 2 2 3
```

In SQL, we have to do two `SELECT` clauses:

```
with t(id, x) as (
  values (1, 'a'), (2, 'a'), (3, 'a'), (4, 'b'), (5, 'b'), (6, 'c')
), t_differ as (
  select *, x <> lag(x, 1, x) over(order by id) as x_change
  from t
)
select id, x, sum(cast(x_change as bigint)) over(order by id) as rleid
from t_differ
-- id x rleid
--  1 a     0
--  2 a     0
--  3 a     0
--  4 b     1
--  5 b     1
--  6 c     2
```

Nomenclature is by no means fixed but this operation is quite useful for generating "state IDs" for some individual or group whose "state" changes whenever some condition changes.

I also think it's pretty straightforward to implement, e.g. the crux of the C version is a few lines:

```
      for (R_xlen_t i=1; i<nrow; i++) {
        bool same = ijcol[i]==ijcol[i-1];
        ians[i] = (grp+=!same);
      }
```

https://github.com/Rdatatable/data.table/blob/d99b8ae4aa85a2426abc307a94c70905bd050416/src/uniqlist.c#L218-L221

Even the more complicated version that does like `rleid(col1, col2, ....)` (incrementing when any of the columns differ from the "previous" row) is only slightly more complicated:

```
      while (--j>=0 && same) {
        SEXP jcol = VECTOR_ELT(l, icols[j]-1);
        switch (TYPEOF(jcol)) {
        case INTSXP : case LGLSXP :
          same = INTEGER(jcol)[i]==INTEGER(jcol)[i-1];
          break;
        // similar branches for other column types
      }
      ians[i] = (grp+=!same);
```

https://github.com/Rdatatable/data.table/blob/d99b8ae4aa85a2426abc307a94c70905bd050416/src/uniqlist.c#L185-L211

I'm happy to have a go at implementing if it's deemed useful

**Comment by martint** [comment]
I believe this is a good fit for the MATCH RECOGNIZE feature in SQL 2016 (which Presto doesn't support yet, unfortunately). In that world, you'd do it like this:

```sql
SELECT t.id, t.rleid
FROM some_table
    MATCH RECOGNIZE (
      ORDER BY id
      MEASURES MATCH_NUMBER() AS rleid
      ALL ROWS PER MATCH
      PATTERN (new)
      DEFINE new AS id <> PREV(id)
    ) AS t
```

**Comment by MichaelChirico** [comment]
never seen that syntax before! is there any prioritization for supporting this?

`rleid` use case seems much narrower in scope, so it could be included separately anyway? in which case it would also be a good way to bridge the gap to new syntax (you've seen `rleid`, now try the much more general version, `MATCH RECOGNIZE`)

**Comment by mosabua** [comment]
MATCH RECOGNIZE is supported in Trino by now. https://trino.io/docs/current/sql/match-recognize.html
