### ISSUE TITLE
Document integration with Jupyter

### ISSUE THREAD

**Issue by edublancas** [trinodb/trino#15785]
Hi Trino team!

I noticed that in your [notebooks](https://trino.io/resources.html#ui) section, there is no example of running Trino on Jupyter. Since Jupyter is the most popular notebook-like interface, it'd be a great addition.

I'm the maintainer of [JupySQL](https://github.com/ploomber/jupysql), a package that allows running SQL queries in Jupyter like this:

```
%%sql
SELECT * FROM table
```

I'm happy to create an example notebook and open a PR, let me know if you're interested!

**Comment by martint** [comment]
Thanks @edublancas! This would be a good addition.

@mosabua, can you think of a good place to add such examples in the docs?

**Comment by edublancas** [comment]
Just a follow-up that we added an integration guide to our docs: https://jupysql.ploomber.io/en/latest/integrations/trinodb.html

any feedback? we're also happy to create a blog post or create a similar guide in Trino's documentation.

**Comment by mosabua** [comment]
Let me get the client tools section on the website off the ground and then we should link to your docs

**Comment by lfunderburk** [comment]
Hi @mosabua 
Happy to write a tutorial or blog on this. I am from the Ploomber team.
Following through discussion it sounds like there is openness to include our docs.

**Comment by mosabua** [comment]
I am heavily working on the tools PR now. I think having a Jupy SQL/Ploomber entry would be great. Let me add that.

**Comment by mosabua** [comment]
See https://github.com/trinodb/trino.io/pull/347 and https://deploy-preview-347--trino.netlify.app/ecosystem/client.html

**Comment by edublancas** [comment]
looks great, @mosabua!

**Comment by mosabua** [comment]
Hey  .. I think we can close this now 

https://trino.io/ecosystem/client.html#jupy-sql

If you have any other links to add or changes to suggest please just file a PR on the website repo.
