### ISSUE TITLE
CI `maven-checks` job reports 'cancelled' when it should fail

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#15794]
When there are failures (checkstyle, error-prone, dependencies), the maven invocation in the `maven-checks` job gets retried.
Retrying is repeated until timeout, so the build result is cancelled.
Sadly, task cancellation looks very similar to task skipping (both with some gray icon), so it really doesn't stand apart.
As a result, I've seen PRs being merged when `maven-checks` is cancelled, breaking the CI.

**Comment by findepi** [comment]
Would it be possible to retry maven on network issues only?
Or not retry maven on known failures, like checkstyle's or error-prone's?

Note that running `dependency:go-offline` with retries and then running the rest without may or may not solve the problem, see https://github.com/trinodb/trino/issues/15793#issue-1550496074. The network failures there were observed despite `dependency:go-offline` having succeeded.

**Comment by findepi** [comment]
cc @nineinchnick @MiguelWeezardo

**Comment by findepi** [comment]
Can the cancellations be a result of one job failure implying other jobs getting cancellations?

**Comment by MiguelWeezardo** [comment]
> Can the cancellations be a result of one job failure implying other jobs getting cancellations?

Yes, it's the result of the [fail-fast](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) strategy which AFAIK is set to `true` by default

**Comment by MiguelWeezardo** [comment]
My mistake, I thought you were talking about `check-commits` job.

**Comment by MiguelWeezardo** [comment]
Isn't it possible to only allow merging on green builds? Having even 1 cancelled job marks the entire build red: https://github.com/trinodb/trino/actions/runs/4025067326

**Comment by findepi** [comment]
> Isn't it possible to only allow merging on green builds?

Yes it's possible, but we don't do that in Trino currently.

**Comment by nineinchnick** [comment]
In #15797 we removed retries when compiling using Maven, so this should not be happening again. I'll close this, but please reopen if you see new occurrences.
