### ISSUE TITLE
Implement `stream` table function that will produce unlimited sequences

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#15845]
`sequence` is a very useful function that can produce all values of a discrete type within a range.
However, since the function returns a single ARRAY, it cannot return large sequences. In fact, it's constrained to limit sequences of at most 10,000 elements:

```
Query 20220608_121504_61596_etnj7 failed: result of sequence function must not have more than 10000 entries
```

Implement a [**table function**](https://trino.io/docs/current/develop/table-functions.html) that will not have such limitations

```sql
SELECT element FROM TABLE(stream(1, 10000000));
```

Note: if we can guarantee that function and table function namespaces will always be separate, then we should reuse the `sequence` for the name of the table function. In either case, we should keep signatures aligned.

**Comment by macroguo-ghy** [comment]
hi, @findepi. I'd like to take on this issue. Could you please assign it to me?

**Comment by kasiafi** [comment]
@findepi we already have a table function to produce "unlimited" sequences -- the `sequence()` function: https://trino.io/docs/current/functions/table.html#built-in-table-functions
It's only limitation is that the start and stop of sequence must fit in `BIGINT`.

Usage example:
```
SELECT *
FROM TABLE(sequence(
                start => 1000000,
                stop => -2000000,
                step => -3))
```



I found that this table function doesn't show up when searching for `sequence` in the docs. @mosabua is it something that could be fixed?

**Comment by mosabua** [comment]
It shows up .. but far down the list

https://trino.io/docs/current/search.html?q=sequence

and it also found in the a-z index

https://trino.io/docs/current/functions/list.html#s

Maybe we should also add a table functions section to https://trino.io/docs/current/functions/list-by-topic.html though .. will send a PR for that

**Comment by mosabua** [comment]
Here is the PR https://github.com/trinodb/trino/pull/20655
