### ISSUE TITLE
Support time travel in Delta Lake connector 

### ISSUE THREAD

**Issue by gui-elastic** [trinodb/trino#15894]
Hello,

I saw that Trino already has the time travel feature on Iceberg, so I am opening this issue to discuss plans for adding time travel support for Delta Lake. This would ideally support timestamps:

```
SELECT count(*) FROM my_table FOR SYSTEM_TIME AS OF "2019-01-01"
```
or with versions

```
SELECT count(*) FROM my_table FOR SYSTEM_VERSION AS OF 5238
```

**Comment by Guilherme-Silveira** [comment]
I'm also interested to know that. I am not from Trino Community. I just also want this feature available.

**Comment by cxl-todd** [comment]
I'm also very interested in this feature. Has any work on this begun yet?

**Comment by Visorgood** [comment]
Plus one from my side +1. This feature would enable several use-cases in my company.

**Comment by andrey-fadeev** [comment]
Here is my +1

**Comment by VardhanDeva** [comment]
+1 as well
