### ISSUE TITLE
Decouple Trino from Hadoop and Hive codebases

### ISSUE THREAD

**Issue by electrum** [trinodb/trino#15921]
# Background

The Trino Hive connector, along with Iceberg, Delta Lake, and Hudi, were built on top of the Hadoop and Hive libraries for features like Hive Metastore client for catalog metadata, clients for HDFS and cloud object stores, reading and writing data files, and so on.  Over the past 10 years, we have slowly been replacing or extending many of these core features to fix bugs, improve performance, add monitoring, and improve reliability. At the same time the Hive and Hadoop libraries have slowed in maintenance and feature development which has made the maintenance of the Trino Hive connector more difficult (e.g., fixing CVEs).

# Proposal

Replace all uses of Hadoop and Hive libraries with native Trino code. Trino will no longer depend on the Hive library at all, and Hadoop will be an optional dependency that is only used for accessing HDFS. The major areas that will require rewrites, porting, and new code are described below.

# Metadata

Metadata has been abstracted for a long time now with direct implementations for Glue, File, and a bridge to the Hive Thrift Metastore. Recently the HMS Thrift client implementation [has been replaced](https://github.com/trinodb/trino/pull/15833) with a [Trino specific client](https://github.com/trinodb/hive-thrift) generated using the newest Thrift code (the old version used by Hive had CVEs).

# File Systems

The Hive plugin uses the Hadoop file system API for accessing files, but the usage has been highly controlled since the [custom S3 file system](https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java) was introduced. Recently, we created the [`TrinoFileSystem`](https://github.com/trinodb/trino/blob/master/lib/trino-filesystem/src/main/java/io/trino/filesystem/TrinoFileSystem.java) API to abstract away from Hadoop APIs and this abstraction is already integrated into the Iceberg and Delta connectors. For this project, we will add Trino file system implementations for S3, GCS, and Azure storage system. HDFS will continue to be supported, of course, but via an implementation of the Trino file system API.

# File Formats

There are Trino native implementations of [ORC](https://github.com/trinodb/trino/tree/master/lib/trino-orc/src/main/java/io/trino/orc), [Parquet](https://github.com/trinodb/trino/tree/master/lib/trino-parquet/src/main/java/io/trino/parquet), and [RCFile](https://github.com/trinodb/trino/tree/master/lib/trino-rcfile/src/main/java/io/trino/rcfile). For this project, we will write native implementations for the other formats supported by Trino (CSV, JSON, Regex, TextFile, SequenceFile, and Avro). The old implementations will be available as a fallback during a transition period. Eventually, we will remove support for Hive input formats and serdes. This means that custom formats, which were never officially supported in Trino, will no longer work.

# Hive Type

The Hive plugin uses the internal Hive type system in several places for convenience.  The single biggest user of Hive types is during interactions with Hive file formats, and the transition to native implementation will eliminate these.

# Tasks

* #15071
* #15482 
* #15630
* #15775 
* #15833 
* #15918
* #16004
* #16020
* #16053
* #16073
* #16164
* #16172
* #16174
* #16175
* #16200
* #16226
* #16251
* #16256
* #16271
* #16373
* #16454
* #16469
* #16557
* #16773
* #17111
* #17190
* #17228
* #17229
* #17237
* #17291
* #17304
* #17312
* #17323
* #17326
* #17337
* #17378
* #17379
* #17392
* #17393
* #17400
* #17498
* #17522
* #17739
* #17741
* #17804
* #17910
* #17921
* #17931
* #18143
* #18146
* #18148 
* #18211
* #18235
* #18241
* #18215 
* #18223 
* #18261
* #18296
* #18407
* #18418
* #18420
* #18444
* #18445
* #18556
* #19314
* #19445
* #19566
* #19609
* #19634
* #19635
* #19639
* #19664
* #19667
* #20288
* #20624

**Comment by jordandakota** [comment]
Does this decouple the need to use a hive metastore standalone along with Trino? Otherwise to use dynamic catalog creation with connectors like iceberg and delta, you still need also add config to hive and restart it.

**Comment by electrum** [comment]
@jordandakota No, that's unrelated to this project. Please feel free to file an issue explaining your interest in detail.
