### ISSUE TITLE
Support changing Delta table protocol versions

### ISSUE THREAD

**Issue by alexjo2144** [trinodb/trino#15932]
We have several Delta Lake features in progress that require a minimum writer version of > 2:
- [Writing CDC Events](https://github.com/trinodb/trino/pull/15453)
- [Check Constraints](https://github.com/trinodb/trino/pull/14964) 

Users should be able to set a default writer/reader protocol version for newly created tables via a config property in `DeltaLakeConfig`, and should be able to upgrade the protocol versions of existing tables to enable new features. For reference, the Iceberg version of this uses `ALTER TABLE SET PROPERTIES` [link](https://trino.io/docs/current/connector/iceberg.html#alter-table-set-properties).

**Comment by alexjo2144** [comment]
Modeling the syntax off of what we did for Iceberg, we probably want something like

```
CREATE TABLE my_table (...) WITH (
    writerVersion = 3,
    readerVersion = 2
);
```

Or to be able to upgrade tables to newer writer version using:
```
ALTER TABLE my_table SET PROPERTIES writerVersion = 3, readerVersion = 2;
```

For now, this should just update the `protocol` entry of the table: https://github.com/delta-io/delta/blob/master/PROTOCOL.md#protocol-evolution

We don't need to support `readerFeatures` or `writerFeatures` yet, since they were added in writer v7 and reader v3, which we are not compatible with yet.

**Comment by findepi** [comment]
> Users should be able to set a default writer/reader protocol version for newly created tables via a config property in `DeltaLakeConfig`, and should be able to upgrade the protocol versions of existing tables to enable new features

I, as a user, wouldn't want to have to understand which reader/writer version provides a specific feature which I want.
As a user, I would expect Trino to do this for me.

@alexjo2144 @krvikash @ebyhr 
do we really need those reader_version and writer_version table properties?

**Comment by electrum** [comment]
Also, setting a version is problematic, because users might forget to update the config and be stuck on an old version.

**Comment by findepi** [comment]
We discussed more offline and decided to go with automatic approach: https://github.com/trinodb/trino/pull/16310
