### ISSUE TITLE
Document lack of view support in JDBC and REST catalogs

### ISSUE THREAD

**Issue by bitsondatadev** [trinodb/trino#15971]
Both [JDBC catalog](https://github.com/trinodb/trino/pull/11772#issuecomment-1386672714) and [REST catalog](https://github.com/trinodb/trino/pull/11772#issuecomment-1386672714) do not support materialized or logical views.

We missed documenting this so we will want to add something that clearly states this.

**Comment by netanelm-upstream** [comment]
Are there any plans to support them in the future?

**Comment by bitsondatadev** [comment]
> Are there any plans to support them in the future?

AFAIK not at the moment. 

cc: @findepi @ebyhr @martint
