### ISSUE TITLE
Delta `CommitInfoEntry`'s `operationParameters` has the incorrect type

### ISSUE THREAD

**Issue by alexjo2144** [trinodb/trino#15978]
Reported by Sujith Kumar.S on [Slack](https://trinodb.slack.com/archives/C03E2DYAS0J/p1675609218304289)

This field https://github.com/trinodb/trino/blob/master/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/CommitInfoEntry.java#L31 should be a `Map<String, Object>`, not `Map<String, String>`

It's not spelled out well in the specification, but it has an example with an array value: https://github.com/delta-io/delta/blob/master/PROTOCOL.md#commit-provenance-information

**Comment by sujiplr** [comment]
The table was cataloged using. 

CALL deltalake.system.register_table(schema_name => 'test_schema', table_name => 'test', table_location => 's3://test_schema/test/'). 

Created the tables and appended the data using Delta Python API. 

SQL Error [84279297]: Query failed (#20230205_145656_00171_yfk86): Failed to access table location:
SQL Error [84279296]: Query failed (#20230205_145822_00173_yfk86): Error getting snapshot for

**Comment by ebyhr** [comment]
> it has an example with an array value: https://github.com/delta-io/delta/blob/master/PROTOCOL.md#commit-provenance-information

The example seems String. 
```
"operationParameters":{"mode":"Append","partitionBy":"[]"}
```

Delta Lake code also seems expecting String values. 
https://github.com/delta-io/delta/blob/553476d/core/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala#L766-L767

I would say this is a bug of https://github.com/delta-io/delta-rs

**Comment by alexjo2144** [comment]
> I would say this is a bug of https://github.com/delta-io/delta-rs (https://github.com/delta-io/delta-rs/commit/4741a89c0f8518eaf3f3d46fb4ed0b86f4bbb13b)

Good point, totally missed the quotes on the array value.
