### ISSUE TITLE
Avoid materializing all results in `$files` Iceberg system table 

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#15991]
https://github.com/trinodb/trino/blob/1e5d0dee836986ac2017fdd629ca49a0bc72b003/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/FilesTable.java#L98-L104

There is no actual need to gather all the files in memory - this may actually require too much memory in case of dealing with a table with a  lot of files and/or columns.

See whether we can get the code to work without materializing all the `$files` results at once.

**Comment by findepi** [comment]
> See whether we can get the code to work without `FixedPageSource` for the `$files` system table. 

`FixedPageSource` provides a very nice programming interface.
We definitely want to retain the fluency, 

Also, note that `FixedPageSource` already accepts an `Iterable`, so we can continue to use that class, and still avoid materializing all the results in the memory.

I've updated the description.

**Comment by alexjo2144** [comment]
The interface may just need to be amended to be able to provide it a thing to close on `close()`

**Comment by ilfrin** [comment]
where are we with this?

**Comment by alexjo2144** [comment]
Vikash has started looking into a fix
