### ISSUE TITLE
Addition to Google Cloud Storage Configuration Properties

### ISSUE THREAD

**Issue by akshayjain3450** [trinodb/trino#16008]
Currently, Trino supports only two properties to connect with GCS-based Hive.

1. hive.gcs.json-key-file-path
2. hive.gcs.use-access-token

For other connectors of GCS, there is an option to authenticate using service-account mail, private-key-id, and private-key. It will be good to have a feature on Trino wherein we can authenticate with GCS using hive using the above three pieces of information. 

For eg.

1. hive.gcs.service.account.mail
2. hive.gcs.service.private.key.id
3. hive.gcs.service.private.key

**Comment by ebyhr** [comment]
Relates to https://trinodb.slack.com/archives/CP1MUNEUX/p1676447792296889

**Comment by akshayjain3450** [comment]
@ebyhr I have replied to your concern related to the mentioned thread and listed why this is required. Please go through that once.

**Comment by ebyhr** [comment]
Closing as answered in the above thread.
