### ISSUE TITLE
Reduce 'The target server failed to respond' errors in Amazon S3 by configuring connection ttl

### ISSUE THREAD

**Issue by hackeryang** [trinodb/trino#16005]
Hi dear community, we would like to contribute a S3 configuration to reduce a HTTP error which also might be met by other trino users. Below is the detail:  

We used Amazon S3 and met this kind of error at about 8 to 9 a.m. every day in one of our production environments:  
![d8537c5b-70ea-43ba-aa35-073180e73516](https://user-images.githubusercontent.com/26461591/217174591-6d8949c9-543d-48ff-bb78-1d31d2e98ba6.jpeg)  
![ea0ef00e-6b0d-4fa4-813c-e316f23354e8](https://user-images.githubusercontent.com/26461591/217174674-0c8639fb-85b5-4466-89b4-442e0fa601ec.jpeg)  
There is indeed a large query load in our trino cluster during that time period, so we asked the Amazon S3 technical support team for some advice, and they said:  
```
Hello,
Thanks for contacting AWS Premium Support, I'm Kenex, and I'm currently assisting with your case.
I understand that you opened a support case for a business-critical system down, indicating that you noticed an HTTP error in the application when the business requests S3 files during peak hours (8-9 am).

According to the log observation you provided, the exception thrown by the application is NoHttpResponseException. I initially checked that NoHttpResponseException means that the application cannot receive an HTTP reply, which may be a problem at the network layer.
Usually the path to connect to S3 is: Application --> Internet --> S3. There are three possible causes of NoHttpResponseException, so I will try to eliminate them step by step.

First, I inquired about the status of S3. As of today, the S3 service has not had any network anomalies. Since buckets in the same region share the same HTTP endpoint, an S3 anomaly will affect other customers at the same time. This phenomenon has not been observed yet.
In addition, the jitter of the Internet may also have an impact. Since external Internet factors are difficult to control, there will be a retry mechanism to solve the problem of network jitter when using the SDK.
In addition, you mentioned that this problem occurs during the peak period of 8-9 o'clock. I guess the most likely reason is that the SDK will maintain multiple connections with S3 when it is running. When a certain HTTP connection has been idle for a period of time , S3 will close the connection, but the SDK later tries to reuse the connection, then the Unable to execute HTTP request: The target server failed to respond error shown in your screenshot may appear.

The suggested solution is to reduce the connection TTL of ClientConfiguration [1] in the SDK, which can be configured by calling setConnectionTTL [2]. (The default value of connection TTL is -1, which means that the SDK will treat each connection as non-expirable by default)
[1] https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html
[2] https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#setConnectionTTL-long-

The following documents are about connection TTL:
https://docs.aws.amazon.com/zh_cn/sdk-for-java/v1/developer-guide/section-client-configuration.html#timeouts-and-error-handling

If the problem persists after you try to configure or lower the connection TTL of the SDK, please reply again, thank you
```
Then we followed their advice, and modified some trino source codes to set the S3 connection ttl, and deployed the modified trino to the production environment.  

And the error described above disappeared these days, and the queries executed in the high load period didn't fail again.

So we want to contribute this ttl configuration to our community, we believe that some other S3 users are also facing this problem.

**Comment by hackeryang** [comment]
If others also encountered this kind of error, you can refer to this issue too: https://github.com/aws/aws-sdk-java/issues/1212

**Comment by mrdominguez** [comment]
@hackeryang What value do you recommend for `hive.s3.connect-ttl` with high-load scenarios such as the one you describe here?

Also, in your case, is there any particular reason to use `TRINO` instead of `EMRFS` for `hive.s3-file-system-type`?

**Comment by hashhar** [comment]
In the past EMRFS was used because S3 did not have strongly consistent semantics but it supports strongly consistent read-after-writes now so there's no reason to use EMRFS anymore. See https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-plan-consistent-view.html

**Comment by mrdominguez** [comment]
@hashhar Any suggestions regarding specific values for `hive.s3.connect-ttl` to avoid or reduce 'The target server failed to respond' errors?

**Comment by hackeryang** [comment]
> @hashhar Any suggestions regarding specific values for `hive.s3.connect-ttl` to avoid or reduce 'The target server failed to respond' errors?

@mrdominguez In one of the production environment clusters of my company with 35 nodes having 32 core, 128G memory and 10000Mb/s network bandwidth, we configured about  20s, which I mentioned in this issue:  
<img width="1131" alt="image" src="https://github.com/trinodb/trino/assets/26461591/8ed97b4e-0901-4c2e-a604-5209a0f94bd3">
https://github.com/aws/aws-sdk-java/issues/1212

**Comment by realknorke** [comment]
The said property `s3.connect-ttl` is gone/not implemented when aws-sdk V2 is used (`fs.native-s3.enabled=true`) and thus the exception from httpclient is thrown when accessing AWS S3 using the hive connector.

**Comment by findinpath** [comment]
@realknorke  see https://github.com/trinodb/trino/pull/20541

**Comment by realknorke** [comment]
@findinpath I can confirm that the added TCP specific properties are not solving the issue. However, during my tests the problem just vanished from one second to the other.  I now suspect S3 (or one component of S3) was the cause of my problems because right now (and I tried hard with all kinds of configurations) I cannot reproduce the problems at all.
