### ISSUE TITLE
Migrate the Delta Lake connector to use TrinoFileSystem

### ISSUE THREAD

**Issue by alexjo2144** [trinodb/trino#16020]
We should swap out uses of the Hadoop `FileSystem` and `HdfsEnvironment` classes and instead use `TrinoFileSystem`.

Relates to: https://github.com/trinodb/trino/issues/14909 and https://github.com/trinodb/trino/issues/15921

**Comment by ebyhr** [comment]
Removed `good first issue` label since some code (e.g. `CheckpointWriter`) in Delta Lake connector depends on `HdfsEnvironment` tightly.
