### ISSUE TITLE
Update in Trino gives Invalid method name: 'alter_table_req'

### ISSUE THREAD

**Issue by divyanshidm** [trinodb/trino#16023]
When I run this on Trino -
_UPDATE table SET columnA='something' where columnA='somethingElse'_
but it fails with error **Invalid method name: 'alter_table_req'**

Versions used -
_Trino CLI 376
Hive Metastore 3.1.2
Both on dataproc gcp._

**Comment by ebyhr** [comment]
The issue was fixed in version 405. Please upgrade your cluster.
