### ISSUE TITLE
`map(...)` Return Type Not Rendering in Function Docs

### ISSUE THREAD

**Issue by nathanwilk7** [trinodb/trino#16030]
On the [Aggregate functions doc page](https://trino.io/docs/current/functions/aggregate.html#map-aggregate-functions), for some of the functions with a return value of `map(...)`, the return value is not rendering in Safari or Chrome. Below is a screenshot showing that `histogram`, `map_agg`, and `multimap_agg` have no return value visible. Note that `map_union` does have the expected return value visible. I have not inspected the HTML to see what is actually going on and am not sure what subset of functions with map returns types are affected. @bitsondatadev asked me to create this issue in a [PR discussion](https://github.com/trinodb/trino/pull/16024#discussion_r1100053109) and said I should tag @mosabua as well.

<img width="240" alt="image" src="https://user-images.githubusercontent.com/10050520/217630169-8e921401-ff72-45b5-aa96-f44baa2890eb.png">

**Comment by mosabua** [comment]
I got a fix with explanation in the linked ticket @nathanwilk7 and @bitsondatadev .. use the same approach in your PR please
