### ISSUE TITLE
Ability to connect via SSH Tunnel

### ISSUE THREAD

**Issue by ryan0x44** [trinodb/trino#16079]
We have some databases which we can only connect to via an SSH Bastion Host / Jump Host.

Many database tools (e.g. Metabase, DBeaver) allow you to connect to database via an SSH tunnel.

Currently we overcome this by running a custom sidecar which runs OpenSSH as an SSH Tunnel, but this approach is cumbersome and costly to set-up securely/reliably and to maintain.

It would be great if Trino had support for connecting to databases via SSH Tunnel, including key-based auth (primarily) and password-based auth (where keys may not be an option for some).

**Comment by hashhar** [comment]
There are no plans to add this. If someone is interested on working on this feel free to reopen and describe how the solution can look like with minimal and non-invasive changes to each connector separately.
