### ISSUE TITLE
Table properties in HiveSplit exausts outgoing bandwidth of coordinator

### ISSUE THREAD

**Issue by wsmithril** [trinodb/trino#16081]
We switch to Trino from PrestoDB recently and observed that the size of serialized `HiveSplit` is significantly larger, resulting in a significant amount of outgoing traffic from Coordinator to Workers, roughly 5x larger, even being capped by how much outgoing bandwidth we have. This will starve the workers in a large cluster.

Upon further investigation, we found out that the problem is that the field `schema` in `HiveSplit` is taking up over 95% of the size after serialization.
https://github.com/trinodb/trino/blob/607decc82d6a85cfc40ce5b157e7a206a4c9c5b8/plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplit.java#L78

It seems like this field contains all the table properties stored in Hive metastore for the table/partition referenced in that split, and in our cases, the table is generated by a separate Spark pipeline, and Spark will write tons of extra metadata to table/partition properties, and this may vary on fileformat used. 

We have mitigated this problem by filtering out most of the table properties. But I think there should be some filter in place for what table properties to be included in the split.

**Comment by raunaqmorarka** [comment]
Which release are you using ?
This was addressed by https://github.com/trinodb/trino/pull/15601 in 406 release.

**Comment by wsmithril** [comment]
It's an older release 377. And that commit fixes this issue. I'll close this issue. Thanks.
