### ISSUE TITLE
Average of cpu_time_distribution of a stage has a value of "NaN" when it should be a double

### ISSUE THREAD

**Issue by rollyboy13** [trinodb/trino#16087]
When publishing out events after a query completes, we noticed some schema related errors. Upon investigating, we noticed that certain stages contain "NaN" as the average for the "cpu_time_distribution" statistic. 

`{"stageId":8,"tasks":0,"p25":0,"p50":0,"p75":0,"p90":0,"p95":0,"p99":0,"min":0,"max":0,"total":0,"average":"NaN"}`

We would like to understand the reason for this, and why do we get a string result when a double is expected?

**Comment by electrum** [comment]
NaN means [Not a Number](https://en.wikipedia.org/wiki/NaN) and is an expected value for floating point computation results. I'm guessing this occurs for an average because the count is zero, and thus the sum divided by the zero count results in NaN.
