### ISSUE TITLE
Make Presto Kinesis metadata update interval from S3 configurable

### ISSUE THREAD

**Issue by ankitdixit** [trinodb/trino#1609]
Check startS3Updates method in S3TableConfigClient.java

**Comment by manan9299** [comment]
@ankitdixit Can I work on this issue?

**Comment by ebyhr** [comment]
@manan9299 It's ongoing in #6521. Sorry, I was missing this issue.

**Comment by manan9299** [comment]
Ok, No worries. Thank you for the update.
