### ISSUE TITLE
Iceberg Glue catalog throws "Explicit schema owner is not supported" when username contains uppercase characters

### ISSUE THREAD

**Issue by EFonsecaPag** [trinodb/trino#16116]
I'm facing the error: `Explicit schema owner is not supported` 
when i try to execute the command:  `CREATE SCHEMA  iceberg.trino_test5;`

I saw a detail:  when the logged user name contains ANY upper case letter the error is thrown. If all the user name letters are lower case, the error isn't triggered.

Looking through the source code I realized that the error is triggered in this snippet:

`
...
@Override
    public void createNamespace(ConnectorSession session, String namespace, Map<String, Object> properties, TrinoPrincipal owner)
    {
        checkArgument(owner.getType() == PrincipalType.USER, "Owner type must be USER");
        checkArgument(owner.getName().equals(session.getUser()), "Explicit schema owner is not supported");
`
From the class io.trino.plugin.iceberg.catalog.glue.TrinoGlueCatalog.
This classes uses the constructor: 
`

@JsonCreator
    public TrinoPrincipal(@JsonProperty("type") PrincipalType type, @JsonProperty("name") String name)
    {
        this.type = requireNonNull(type, "type is null");
        this.name = name.toLowerCase(ENGLISH);
    }
`

from  io.trino.spi.security.TrinoPrincipal class. 

I suspect that ` name.toLowerCase(ENGLISH);`  snnipet can be reason of the problem.

[TrinoGlueCreateSchemaException.txt](https://github.com/trinodb/trino/files/10736415/TrinoGlueCreateSchemaException.txt)

I'm using the Iceberg connector and the glue catalog.

**Comment by krvikash** [comment]
I will take a look.
