### ISSUE TITLE
Support enabling CDC on Delta Lake tables

### ISSUE THREAD

**Issue by alexjo2144** [trinodb/trino#16129]
Relates to: https://github.com/trinodb/trino/issues/15932

407 includes support for writing CDC events to Delta Lake tables, however that PR doesn't include a way to turn the feature on in Trino. We should be able to do that via a table property. That table property should set the `delta.enableChangeDataFeed` flag in the table metadata so that the feature is enabled in both Spark and Trino.

ref: https://github.com/trinodb/trino/pull/15453

We should be able to do something like:

```
CREATE TABLE my_table (...) WITH (
    writerVersion = 4,
    cdcEnabled = true
);
```

or

```
ALTER TABLE my_table SET PROPERTIES writerVersion = 4, cdcEnabled = true;
```

**Comment by homar** [comment]
https://github.com/trinodb/trino/pull/16131

**Comment by alexjo2144** [comment]
Fixed by: https://github.com/trinodb/trino/pull/16310
