### ISSUE TITLE
Change FetchSize from 1k to 10k

### ISSUE THREAD

**Issue by vikingUnet** [trinodb/trino#16153]
**Hello!**

We have stumped for a month with very slow working Postgresql connector to db from another city - 
we have ping 10ms to this host and this producing slow receiving a lot of rows from it. 

We changed [FetchSize(](https://github.com/trinodb/trino/blob/289dd57186e6c2056d829908689dde298a14ce16/plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java#L387)) call value from 1000 to 10 000 and all become fine: data receiving very fast without any network overhead.

Can you explain - is it safe to change FetchSize from 1000 to another value (maybe 1 million rows for iteration), do we have risks with bigger values?

When will release new Trino version, we must rebuild it with this little change - may i ask you to change this value to 10 000 in master branch or create config parameter to be able to change this value globally or even much better for each connector separately to can change this value dynamically without risk if it really necessary? It will be **awesome**!

Or it will be better to do this source changes in my own Pool Request?

_Big Thanks to Trino Team for your work!_

@electrum

**Comment by chenjian2664** [comment]
@vikingUnet  I think it's worth to allow customer to define the `jdbcFetchSize` as it solve your real problem. 
I'll start investigate this and  many thanks for sharing all of this.
