### ISSUE TITLE
Web ui CI failed 

### ISSUE THREAD

**Issue by chenjian2664** [trinodb/trino#16179]
Web UI CI failed 
eg: https://github.com/trinodb/trino/actions/runs/4210346127/jobs/7307966833

message:
>   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'

may similar to : https://stackoverflow.com/questions/69665222/node-js-17-0-1-gatsby-error-digital-envelope-routinesunsupported-err-os 
cc @raghavsethi

**Comment by martint** [comment]
There's a fix in progress: https://github.com/trinodb/trino/pull/16160
