### ISSUE TITLE
Support `query` pass-through table function in ClickHouse connector

### ISSUE THREAD

**Issue by dishkakrauch** [trinodb/trino#16182]
Hi.

I didnt' find any in Trino [docs](https://trino.io/docs/current/connector/clickhouse.html) any mention about using [jdbc-bridge](https://clickhouse.com/docs/en/integrations/jdbc/jdbc-with-clickhouse/). Can someone share any workaround or approve that it's a bug?

![Screenshot_20230220_123356_Teams](https://user-images.githubusercontent.com/34490641/220067691-145563fa-aa2c-40de-960c-d98847479c8c.jpg)

**Comment by ebyhr** [comment]
This is not a bug as I replied in Slack. https://trinodb.slack.com/archives/CGB0QHWSW/p1676884887772259

**Comment by dishkakrauch** [comment]
Thx. Looks like it could be feature request for ClickHouse connector to add table function support.

**Comment by suhli** [comment]
> This is not a bug as I replied in Slack. https://trinodb.slack.com/archives/CGB0QHWSW/p1676884887772259

Is it because of can not get ResultSetMetadata in PrepareStatement of clickhouse-jdbc?

ref:[clickhouse jdbc issue](https://github.com/ClickHouse/clickhouse-java/issues/1430)
