### ISSUE TITLE
Support Trino CTAS data setup process for Ignite connector

### ISSUE THREAD

**Issue by chenjian2664** [trinodb/trino#16214]
Added `trinoCreateAsSelect` DataSetup for Ignite sql type mapping test.
Follow up for https://github.com/trinodb/trino/pull/8323

**Comment by sudip-unb** [comment]
I am new to Trino and I am interested to work on this. Thanks in advance.

**Comment by chenjian2664** [comment]
@sudip-unb You can look at the implementation about the `io.trino.plugin.ignite.TestIgniteTypeMapping`, we only support create the `DataSetup` by create and then insert, we need to build the `DataSetup` using create as select(in Trino).
For the demo you can refer the  `io.trino.plugin.postgresql.TestPostgreSqlTypeMapping`

**Comment by chenjian2664** [comment]
@sudip-unb We want a method similar to `TestPostgreSqlTypeMapping.trinoCreateAsSelect` in `io.trino.plugin.ignite.TestIgniteTypeMapping`
