### ISSUE TITLE
Make sure Ignite primary_key column exists while creating table

### ISSUE THREAD

**Issue by chenjian2664** [trinodb/trino#16215]
Make sure Ignite `primary_key` column exists in column definition.
Follow up for https://github.com/trinodb/trino/issues/8323

**Comment by sahoss** [comment]
@chenjian2664 i am interested in solving this issue as its marked as a "good first issue".

Can you tell me more about what this issue is about? I setup a local ignite instance and ignite indeed throws an error `No PRIMARY KEY defined for CREATE TABLE`

**Comment by ebyhr** [comment]
You can look into `io.trino.plugin.ignite.IgniteClient#buildCreateSql` method. Currently, the method doesn't verify if entries of `List<String> primaryKeys` exist in column definition. We should throw an exception if it doesn't exist.

**Comment by sahoss** [comment]
thanks @ebyhr . i ll try to solve this issue

**Comment by maarioos123** [comment]
Can you provide me more details about the problem?
