### ISSUE TITLE
Table statistics reader ignores filter predicates

### ISSUE THREAD

**Issue by davseitsev** [trinodb/trino#16239]
During Trino upgrade from 367 to 407 we faced query planning time regression on big tables.
On partitioned table with 600TB of parquet data planning time increased from 20ms to 3 minutes when query execution time is 3-5s.

On a flame graph I saw that query thread is fully busy with making table statistics:
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/1793410/220939245-113a9ba4-895e-4766-8ca3-96ee13293ef0.png">

So I tried to turn off table statistics usage `set session iceberg.statistics_enabled = false` and planning time back to normal.

Deeper investigation showed that method https://github.com/trinodb/trino/blob/d2739c47f363c941a2a67bac90fe09f9bb19ed1a/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java#L2320 receives ConnectorTableHandle with following values:

```
enforcedPredicate=ALL
```

And later on `enforcedPredicate` is used to build table statistics, and as it's value is `ALL`, it gather statistics for all the files.
https://github.com/trinodb/trino/blob/d2739c47f363c941a2a67bac90fe09f9bb19ed1a/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsReader.java#L132-L135

I tested locally using following query set:
```
CREATE TABLE iceberg.test.test_table ( dt timestamp(6), guid varchar, hash varchar )
WITH ( partitioning = ARRAY['day(dt)','bucket(guid, 1024)'] );

INSERT INTO iceberg.test.test_table (dt, guid, hash) VALUES
 (timestamp '2023-01-22 13:04:43.462', '54dc6a2c-ae8c-42e2-8ee0-73c5e7beb4d1', '220939245113a9ba4895e4769');

SELECT dt, guid, hash
FROM iceberg.test.test_table
WHERE
  guid = '54dc6a2c-ae8c-42e2-8ee0-73c5e7beb4d1'
  AND dt = timestamp '2023-01-22 13:04:43.462'
  AND hash = '220939245113a9ba4895e4769'
```

Is it ok that we use `enforcedPredicate` instead of `unenforcedPredicate` to build table statistics? Should I create a table in some other way to avoid all files scan during statistics build?

**Comment by alexjo2144** [comment]
Thanks for reporting!

My guess is that was introduced by https://github.com/trinodb/trino/pull/11877 (@nineinchnick  @findepi) I think we just need to intersect the `enforcedConstraint` with the `unenforcedConstraint` in `TableStatisticsReader`

**Comment by alexjo2144** [comment]
@krvikash we should run your benchmarks with small files again after we fix this.
