### ISSUE TITLE
Allow adding a specific field in nested field in iceberg connector

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#16248]
We're going to support for dropping nested fields in #15975. It would be nice to support adding nested fields as well.

**Comment by grantatspothero** [comment]
@ebyhr (or whoever picks this up): IMO adding fields to nested data types is more important than dropping fields of nested data types. 

Dropping fields is a backwards incompatible change while adding fields is a backwards compatible change. A workaround for not supporting dropping nested fields is just setting the field as null. There is no workaround for not supporting adding nested fields.

**Comment by erichwang** [comment]
Ping on this again. This is actually really important since modifying complex structures is actually a common operation.
