### ISSUE TITLE
Add hive.max-outstanding-splits-size to Hive performance tuning configuration documentation

### ISSUE THREAD

**Issue by amir-upstream** [trinodb/trino#16240]
We had an issue with queries vs hive getting HIVE_EXCEEDED_SPLIT_BUFFERING_LIMIT (256MB)
and changing the limit through hive.max-outstanding-splits-size fixed our issue.

I believe its not so minor config and should be exposed through the documentation (I found it  though the source code)

Also the word "presto" appears for the description on hive.max-splits-per-second in the official documentation which should be changed :)

**Comment by raunaqmorarka** [comment]
cc: @mosabua

**Comment by mosabua** [comment]
Good idea .. I dont know where you see the Presto mention btw @amir-upstream 

@michaeleby1 can you take this on. Ping myself and @m57lyra for reference on where to best put this.

**Comment by amir-upstream** [comment]
@mosabua thx for your quick response!
here is a screenshot of the presto mention
![presto](https://user-images.githubusercontent.com/68607802/221863227-02b1eb9d-6566-4700-bf29-dc0432c5c989.png)

**Comment by mosabua** [comment]
This was completed with the linked PR.
