### ISSUE TITLE
Add support for invalidHostNameAllowed in mongodb connector TLS config

### ISSUE THREAD

**Issue by samperetz** [trinodb/trino#16241]
The `com.mongodb.connection.SslSettings` used in `io.trino.plugin.mongodb.MongoClientModule` has an `invalidHostNameAllowed` setting.  This is extremely useful to allow connecting to mongod or mongos instances using IP address instead of hostname in the connection string.  It would be really useful to add a new property such as `mongodb.tls.invalid-host-name-allowed` that allows you to set this flag.

This requires 2 simple changes.

`io.trino.plugin.mongodb.MongoClientConfig`:
```java
    private boolean tlsInvalidHostNameAllowed;

    ...

    public boolean getTlsInvalidHostNameAllowed()
    {
        return this.tlsInvalidHostNameAllowed;
    }

    @Config("mongodb.tls.invalid-host-name-allowed")
    public MongoClientConfig setTlsInvalidHostNameAllowed(boolean tlsInvalidHostNameAllowed)
    {
        this.tlsInvalidHostNameAllowed = tlsInvalidHostNameAllowed;
        return this;
    }
```

`io.trino.plugin.mongodb.MongoClientModule`:
```java
        if (config.getTlsEnabled()) {
            options.applyToSslSettings(builder -> {
                builder.enabled(true);
                builder.invalidHostNameAllowed(config.getTlsInvalidHostNameAllowed());  <--- only this line is added
                ...
            });
        }
```

**Comment by ebyhr** [comment]
Why can't we set `tlsAllowInvalidHostnames` via connection-url? 
https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/connection/connection-options/
