### ISSUE TITLE
Reorder Azure storage options in docs

### ISSUE THREAD

**Issue by dain** [trinodb/trino#16352]
In the [Azure docs](https://trino.io/docs/current/connector/hive-azure.html) we configs for "WASB", "ADLS Gen2 / ABFS storage", and "ADLS Gen1".  Both WASAB and Gen1 are very legacy now.  I suggest we put ABFS first, and add `(legacy)` to the other two.  Also maybe add a stronger warning that the two legacy options will be removed at some point (you can't even provision these in Azure anymore).

**Comment by mosabua** [comment]
Sounds great. @blvckcoffee can you run with this?

**Comment by mosabua** [comment]
This is done and was implemented by the linked PR.
