### ISSUE TITLE
SET SESSION hive.compression_codec not working

### ISSUE THREAD

**Issue by cvaliente** [trinodb/trino#16358]
SET SESSION hive.compression_codec = 'SNAPPY';
SHOW SESSION like 'hive.compression_codec';
returns hive.compression_codec|GZIP
even though I just set it to snappy?

**Comment by ebyhr** [comment]
What client are you using?

**Comment by cvaliente** [comment]
tried both pyhive and datagrip.
in the previous presto cluster it was working, when we upgraded to trino (on EMR) the same script no longer worked.

**Comment by ebyhr** [comment]
I can't reproduce it with CLI. Can you join the community Slack and ask in `#troubleshooting` channel? [trino slack](https://trino.io/slack.html)

**Comment by cvaliente** [comment]
discussing on slack https://trinodb.slack.com/archives/CGB0QHWSW/p1678157746289569

**Comment by ebyhr** [comment]
Closing per
> the official trino python package and the cli and it works there.
