### ISSUE TITLE
Queries are getting stuck.

### ISSUE THREAD

**Issue by yatintaluja** [trinodb/trino#1638]
Hi,
We are running presto with 6 workers(r5.4xlarge ec2 machines). Even then, when we have more than 60 queries/ or have a greedy query which takes mostly 100-150 GB of reserved memory. The whole system is getting stuck. We saw the queries which take a few secs, taking hours to run.
We looked into the cause and found out at some point the threads on workers are getting stuck. Still, not able to figure out why it's happening.
Presto version we are using 302-E.9(Starburst Presto).
Jstack thread dump of a worker.  
[jstack.log](https://github.com/prestosql/presto/files/3678398/jstack.log)

**Comment by sopel39** [comment]
Hi @yatintaluja 

1. Do you observe any queries running in reserved memory pool?
2. Is any query progressing at all?

**Comment by dggs123** [comment]
Hi @sopel39, I work with @yatintaluja.
Yes, there were some queries which were running in a reserved memory pool during that time. But no queries were progressing forward for a very long time.

**Comment by sopel39** [comment]
> Yes, there were some queries which were running in a reserved memory pool during that time.

You might want to try to disable reserved pool and see how queries behave then. It could be that some queries start failing with OOM. You could deal with that using spill to disk feature.

In order to disable reserved pool set:
```
experimental.reserved-pool-enabled=false
query.low-memory-killer.policy=TOTAL_RESERVATION
```

**Comment by tooptoop4** [comment]
did u solve @yatintaluja @gaurav8297  ? I also face particular older worker processing splits much slower than other workers

**Comment by yatintaluja** [comment]
Thanks, this was resolved. Marking closed.

**Comment by tooptoop4** [comment]
@yatintaluja what was the fix?
