### ISSUE TITLE
Off by +1 error causing HIVE connector skipping parquet files

### ISSUE THREAD

**Issue by dprophet** [trinodb/trino#16386]
There is an issue with the HIVE connector

If the second character of a parquet file contains an "\_" or "." then the HiveFileIterator.java will skip that file. According to documentation if the 1st character is an "\_" or "." then it should be hidden.

See
https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/HiveFileIterator.java#L153

Test case:
-  2 parquet files in S3 storage.
- p_file1.parquet
- p_file2.parquet
- create a schema
- Run SQL query. You will see due to the 2nd (not the 1st) character is an _ nothing will be returned in a select *

**Comment by tfonllad** [comment]
This function tested in https://github.com/trinodb/trino/blob/726fbd77f59ebff1885f58819d3dbdbd23f41708/plugin/trino-hive/src/test/java/io/trino/plugin/hive/fs/TestHiveFileIterator.java#L28-L37
In the tests the prefix does not end with a `/` which is why checking the character at `prefix.length() + 1` works in the tests.
Let's make sure that the files are still being properly skipped when removing the `+1`  from the starting index.

**Comment by dprophet** [comment]
[parquet_off_by_1.zip](https://github.com/trinodb/trino/files/10901200/parquet_off_by_1.zip)

Attaches is a zip file with 1 parquet files. These can be used to test the problem.

1) upload the files to S3
2) 
`
CREATE TABLE catalog.schema.off_by_1 (
    index integer
 )
 WITH (
    external_location = 's3a://s3bucketname/',
    format = 'PARQUET'
)
`
3) select * from catalog.schema.off_catalog.schema.off_by_1

**Comment by dprophet** [comment]
> String root = new Path("file:///root-path").toUri().getPath();

This testcase is bad. If you try and create a file path without the trailing / you will get the error

Query failed (#20230306_224856_00001_haeh3): java.lang.IllegalArgumentException: Can not create a Path from an empty string

Caused by: org.apache.hadoop.hive.metastore.api.MetaException: java.lang.IllegalArgumentException: Can not create a Path from an empty string
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_result$create_table_resultStandardScheme.read(ThriftHiveMetastore.java:54418)

**Comment by findepi** [comment]
> If the second character of a parquet file contains an "_" or "." then the HiveFileIterator.java will skip that file. According to documentation if the 1st character is an "_" or "." then it should be hidden.

we should have a product test for that, to ensure Hive connector behavior is indeed consistent with Hive (HiveServer2) behavior.

@dprophet can you make a PR with such a product test?
@bitsondatadev can help guide you if needed
