### ISSUE TITLE
SSL with Trino JDBC driver not working

### ISSUE THREAD

**Issue by Subhashini2610** [trinodb/trino#16435]
I have an instance of Trino deployed on K8s. This is routed through the nginx layer where I have configured server certificate and mTLS. This is also additionally protected by OAuth 2.0. The setup is working perfectly fine. The browser asks for a client cert when accessed and does the redirects with OAuth 2.0 as well. With this I can say the Trino is configured well enough.

I need to connect to this instance of Trino from a client (DBeaver). I have configured the JDBC driver with the following settings:
SSLKeyStorePassword - password of keystore.jks
SSLKeyStorePath - path to the jks file that contains my client cert
SSLTrustStorePassword - password of truststore.jks
SSLTrustStorePath - path to the jks file that contains my server's root CA cert 
SSLVerification - CA
externalAuthentication - true

This is my Trino configuration:
Trino version - 406
environment - production

The connection seems to be successful, but I am not able to see the catalogs. I get the following error:
```
SQL Error: Error executing query: Expected URL scheme 'http' or 'https' but no colon was found
  Error executing query: Expected URL scheme 'http' or 'https' but no colon was found
  Error executing query: Expected URL scheme 'http' or 'https' but no colon was found
    Expected URL scheme 'http' or 'https' but no colon was found
    Expected URL scheme 'http' or 'https' but no colon was found

```

**Comment by Subhashini2610** [comment]
Still facing the issue. Any help is greatly appreciated.

**Comment by hashhar** [comment]
What URL are you using for the connection to Trino? The URL scheme needs to be specified, so either `http://<trino_host>:<trino_port>` or `https://<trino_host>:<trino_port>`

**Comment by Subhashini2610** [comment]
This was an issue with the JDBC driver. I upgraded it to the latest version and it works!!! Closing the issue now.
