### ISSUE TITLE
Huge slow perf if LIKE in the JOIN condition with pattern %xxx%, v407

### ISSUE THREAD

**Issue by ubyyj** [trinodb/trino#16456]
The following query is huge slow(5 minutes+) though data size is quite small, in version 407, while it quite fast (1 second) in version 377.

with a as (
	select cast(name as varchar) col_a
	from (select sequence(1,200,1) as seq)
	cross join unnest(seq) as t(name)
),
b as (
	select '%' || cast(name as varchar) || '%' col_b
	from (select sequence(1,1000,1) as seq)
	cross join unnest(seq) as t(name)
)

select a.*, c.*, d.*, e.*, f.*, g.*
from a
left join b c

  on   a.col_a like  c.col_b
    left join b d
  on   a.col_a like  c.col_b
    left join b e
  on   a.col_a like  c.col_b
    left join b f
  on   a.col_a like  c.col_b
    left join b g
  on   a.col_a like  c.col_b

**Comment by phd3** [comment]
can you try this on 409? There's perf improvement for dynamic like patterns in https://github.com/trinodb/trino/pull/15999

**Comment by raunaqmorarka** [comment]
cc: @martint 
Closing as this is expected to be solved in 409. Please re-open if it's not solved even after upgrading to 409.

**Comment by ubyyj** [comment]
confirmed, fixed in 409
