### ISSUE TITLE
add catalog problem

### ISSUE THREAD

**Issue by zqsgithub2023** [trinodb/trino#16483]
![image](https://user-images.githubusercontent.com/125441824/224219637-67221c32-372f-44dc-b8e6-b2183a28a172.png)
/opt/datasophon/trino-367/etc/catalog  添加了对应的文件，重启trino，但是通过客户端还是查不到新增的catalog
![image](https://user-images.githubusercontent.com/125441824/224219819-48b19271-a50f-47db-ac63-c8c83fd7c7f1.png)

**Comment by ebyhr** [comment]
The file name has a typo. `propertis`
