### ISSUE TITLE
CSV headers broken in Hive tables

### ISSUE THREAD

**Issue by jotarada** [trinodb/trino#16492]
Hi, Since the upgrade to version 409 i started to have this errors when creating an Hive table based on CSV files.
```
CREATE TABLE hive.{schema}.{table} (
    field1 VARCHAR,
    field2 VARCHAR
)
WITH (
  format = 'CSV',
  skip_header_line_count = 1,  -- THIS LINE IS THE PROBLEM but is required to skip column headers
  external_location = '<storage_location>'
)
```

```
Error: TrinoQueryError(type=INTERNAL_ERROR, name=GENERIC_INTERNAL_ERROR, message="Header not supported for a split file", query_id=20230309_180613_62604_ud47x)
```

I suspect it has to do with the [implementation of a native CSV writer/reader](https://github.com/trinodb/trino/pull/15918), but I’m not sure what the breaking change is, or how to resolve it. Could you please have a look?

**Comment by findepi** [comment]
@jotarada the case like described above seems exercised by this test
https://github.com/trinodb/trino/blob/a125581ca8907a1001bf1cd076a2f5519c631a38/testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestCsvFileHiveTable.java#L33-L36

can you please verify this test passes for you locally?
would you be able to propose changes in the test that would expose the potential regression?

(if you have questions how to run product tests @findinpath and @wendigo can help)

**Comment by findepi** [comment]
when `skip_header_line_count=1` we shouldn't split the files at all, AFAIR.

@dain please correct me if i am wrong.

**Comment by dain** [comment]
I the meantime you can disabled these with the `csv_native_reader_enabled` and `csv_native_writer_enabled` session properties or the `csv.native-reader.enabled` and `csv.native-writer.enabled` configuration property.

**Comment by dain** [comment]
@jotarada is it possible this file is modified during the execution of the query?
