### ISSUE TITLE
Support writing bloom filters in optimized parquet writer

### ISSUE THREAD

**Issue by raunaqmorarka** [trinodb/trino#16536]
Currently the reader is able to take advantage of bloom filters in parquet files, but we do not support writing bloom filters in parquet files yet.

**Comment by AnirudhVyas** [comment]
is this done? what kind of help is needed in getting this in place?

**Comment by raunaqmorarka** [comment]
@AnirudhVyas This is not done yet. It needs someone to take a look at the existing parquet-mr code to write bloom filters and replicate it in Trino parquet writer.

**Comment by AnirudhVyas** [comment]
where's the parquet write in source for trino can you point me please?

**Comment by AnirudhVyas** [comment]
I imagine it'd be here: https://github.com/trinodb/trino/blob/da507b9a322e618999e535bc07d923c6fb9f91e0/lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java#L76
