### ISSUE TITLE
The actual table is created from the explain query statement (CTAS) - Postgresql connector.

### ISSUE THREAD

**Issue by bbasosuho** [trinodb/trino#16542]
There is a problem that a table is created when "explain Create table ~~ as Select * from table ~~" is executed in the Postgresql connector.

An actual table is not created when the "explain Create table ~~" query statement is executed.

There is a problem that actual tables are created when explain is executed for the CTAS query statement.

I wonder if the intended function is correct.

**Version : 410 ( K8S )**

**Comment by hashhar** [comment]
`EXPLAIN` only prints the explain plan.
`EXPLAIN ANALYZE` executes the query and then prints the explain plan.

So it's correct behavior if `EXPLAIN CTAS` doesn't cause a table to get created but `EXPLAIN ANALYZE CTAS` causes it to get created.

**Comment by bbasosuho** [comment]
@hashhar 
Thank you for answer.
However, the current situation is not "EXPLAIN ANALYZE", but only "EXPLAIN", but the table is being created.
To be precise, the CTAS table (no data) and the tmp_trino_XXXX (no data) table are created.

Postgresql Version : 15.1
Trino Version : 410

SQL : explain CREATE TABLE postgresql.public.info_ctas_01 as select * from postgresql.public.info;
Result : postgresql.public.info_ctas_01 created && postgresql.public.tmp_trino_648408fa_60aaca11 created
