### ISSUE TITLE
Support Iceberg branch read

### ISSUE THREAD

**Issue by jackye1995** [trinodb/trino#16569]
Similar to https://github.com/apache/iceberg/pull/5150 for Spark

```
SELECT * FROM "table$branch_test"
```

**Comment by jackye1995** [comment]
cc @bitsondatadev @alexjo2144 @findepi @ebyhr @JunhyungSong @pettyjamesm @electrum

**Comment by findinpath** [comment]
Handled through time travel syntax

```
SELECT *
FROM example.testdb.customer_orders FOR VERSION AS OF 'test-branch'
```

See https://trino.io/docs/current/connector/iceberg.html#time-travel-queries
