### ISSUE TITLE
FTE tests are cancelled due to timeout on CI

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#16577]
https://github.com/trinodb/trino/actions/runs/4431617249/jobs/7775201312

<img width="906" alt="Screenshot 2023-03-16 at 14 00 40" src="https://user-images.githubusercontent.com/6237050/225519557-720df46e-3689-4360-8397-2353cb46374a.png">

**Comment by ebyhr** [comment]
cc: @arhimondr @losipiuk

**Comment by hashhar** [comment]
Seems to have started with https://github.com/trinodb/trino/commit/20f2d448b568d238d00688d27292d50f290af24e

**Comment by losipiuk** [comment]
👀
