### ISSUE TITLE
Support Iceberg branch write

### ISSUE THREAD

**Issue by jackye1995** [trinodb/trino#16570]
Similar to https://github.com/apache/iceberg/pull/6965/ for Spark

```
INSERT INTO "table$branch_test" VALUES (1,2,3)
```

**Comment by jackye1995** [comment]
cc @bitsondatadev @alexjo2144 @findepi @ebyhr @JunhyungSong @pettyjamesm @electrum

**Comment by ebyhr** [comment]
Let's continue in https://github.com/trinodb/trino/issues/12844
