### ISSUE TITLE
Function json_query not registered

### ISSUE THREAD

**Issue by fhrzn** [trinodb/trino#16591]
Hello, I am trying to query my json column with `json_query` function but it gave me an error Function 'json_value' not registered. I am pretty new to this tool, can someone help me out?

Thanks.

**Comment by Praveen2112** [comment]
Hi !! Can you provide us which version of Trino have you used it and can you share the stacktrace so that we could debug further.

**Comment by fhrzn** [comment]
Hi, thanks for the reply. First of all, how to check Trino version? Currently, my Trino was deployed via kubernetes. I've tried to access the pods and running `launcher help` but no clue about the version

**Comment by Praveen2112** [comment]
Can you run this query in your trino cluster 
```
SELECT version();
```

**Comment by fhrzn** [comment]
yeah, I got version 361. I think its pretty old now, does the mentioned function already supported in my current version?

**Comment by Praveen2112** [comment]
The above function was added in 383 version. https://github.com/trinodb/trino/pull/9831.

**Comment by Praveen2112** [comment]
I'll be closing this issue. Feel free to re-open this if the issue still exists in the latest version. Also join our [Slack](https://trino.io/slack.html) for further discussion related to Trino.
