### ISSUE TITLE
Improve log messages for duplicate CTAS queries failure

### ISSUE THREAD

**Issue by rupamk** [trinodb/trino#1670]
In case of parallel duplicate CTAS queries, one succeeds and the other fails. A sample failure message:

`[2019-08-12T20:24:33.826929 #18986] ERROR -- : Command execution failed with exception: Query 20190812_192512_00006_rw82k failed: java.lang.RuntimeException
Error deleting directory s3://<location-to-table>/<table-name> for staging/target_new directory rollback for table <table-name>. Can not delete the directory.`

While this given query was running, another query had created the same table which caused commit to fail as table already existed by the time this query tried commit. Then rollback also failed because there were files from the other query under this directory which were left behind.

This is not evident from the log message, and required changes needs to be added in `SemiTransactionalHiveMetastore.java` to capture this exception properly like:

`[2019-09-19T19:00:02.488081 #8452] ERROR -- : Command execution failed with exception: Query 20190919_185902_00000_3evp9 failed: com.facebook.presto.spi.PrestoException

Error during Commit : Table already exists: <table-name>

Error during Rollback: Error deleting directory s3:// location-to-table / table-name for staging/target_new directory rollback for table <table-name>. Can not delete the directory. Some non eligible items can not be deleted [files from the other running query]`

**Comment by hashhar** [comment]
Closing since the PR is no longer being actively worked on and fell through the cracks.

Feel free to reopen or resend the PR.
