### ISSUE TITLE
The scalar function `sequence` does not handle long overflow correctly

### ISSUE THREAD

**Issue by kasiafi** [trinodb/trino#16742]
The function does not use `exact` arithmetic operations, leading to silent correctness bugs.
```
trino:tiny> SELECT * FROM UNNEST(sequence(9223372036854775807, -9223372036854775808, -100));
        _col0
---------------------
 9223372036854775807
(1 row)
```
```
trino:tiny> SELECT * FROM UNNEST(sequence(9223372036854775807, -9223372036854775808, -1));
 _col0
-------
(0 rows)
```

in both examples above, the wrong  length of the sequence is assumed due to:
`int length = toIntExact((stop - start) / step + 1L);` in the method `fixedWidthSequence()`

This issue was found while testing the table function `sequence` against the scalar function `sequence`: https://github.com/trinodb/trino/pull/16716

**Comment by chenjian2664** [comment]
@kasiafi How about using `BigInteger`?
