### ISSUE TITLE
Please re-open expired slack link!!

### ISSUE THREAD

**Issue by wschung1113** [trinodb/trino#16756]
I would like to join the channel as I have some questions regarding connectors for Tibero db. Thanks!

**Comment by ebyhr** [comment]
@wschung1113 Can you try https://join.slack.com/t/trinodb/shared_invite/zt-1s1o6uk4i-N3dbXIs1M2Z9RkLew9WrWQ? 

cc: @martint

**Comment by wschung1113** [comment]
thanks! seems like it works. Btw, do you have any clue about connecting Tibero DB to Trino?

**Comment by ebyhr** [comment]
Sorry, I don't know. You can refer to https://github.com/trinodb/trino/tree/master/plugin/trino-example-jdbc if you want to develop the dedicated connector for Tibero DB.
