### ISSUE TITLE
Redundant file system stat calls when reading Delta Lake transaction log checkpoint

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#16775]
See TODO in the code being added in https://github.com/trinodb/trino/pull/16776

**Comment by ebyhr** [comment]
Skimmed `testIncrementalCacheUpdates`. The 4 calls for `TrinoInputFile#length` come from `getCheckpointTransactionLogEntries` & `getCheckpointMetadataEntry` in `TableSnapshot`. The half of access (2/4) doesn't cause disk access because `HdfsInputFile` caches `length` internally.
