### ISSUE TITLE
Redundant file system access to Delta's _last_checkpoint

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#16782]
See TODO being added in https://github.com/trinodb/trino/pull/16784

**Comment by ebyhr** [comment]
Note: regarding `SELECT key, max(data) FROM test_read_part_key GROUP BY key`, the 3 access come from
1. DeltaLakeMetadata#getTableHandle
2. DeltaLakeMetadata#getTableStatistics
3. DeltaLakeSplitManager#getSplits
