### ISSUE TITLE
Overly verbose Iceberg product test execution

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#16813]
`pt (default, suite-iceberg, )` (eg https://github.com/trinodb/trino/actions/runs/4561063428/jobs/8050545170) can produce 66M log output. This makes viewing test results harder.

**Comment by electrum** [comment]
The majority is `INFO` log messages from the `spark` container. Can we change Spark logging to `ERROR` level?

**Comment by ebyhr** [comment]
#17818 reduces log size to 18M. `iceberg-with-rest` and `nessie-server` are still noisy.
