### ISSUE TITLE
Oracle Native Encryption support

### ISSUE THREAD

**Issue by PlePato** [trinodb/trino#16812]
Add support for oracle native encryption (TLS) for Oracle connector. 

[](https://docs.oracle.com/en/database/oracle/oracle-database/19/dbseg/configuring-network-data-encryption-and-integrity.html#GUID-7F12066A-2BA1-476C-809B-BB95A3F727CF)

I checked some code. Based on 
https://github.com/trinodb/trino/blob/543cd1f93d63c381403bc68e76fb3cb16f7e1cbb/plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OraclePoolConnectionFactory.java#L57

following files should be changed
* https://github.com/trinodb/trino/blob/master/plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClientModule.java
* https://github.com/trinodb/trino/blob/master/plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleConfig.java

**Comment by ebyhr** [comment]
> following files should be changed

L66 is an empty line. 
L54, why do you need to change the flag?
