### ISSUE TITLE
Does postgresql connector support UPDATE

### ISSUE THREAD

**Issue by cntwelve** [trinodb/trino#16823]
Hi, everyone:

**Does postgresql connector support UPDATE**? I go through the documents and the issues, but cant find a clear description about this question. And when I run a update statement, it will throw an error at my enviroment.

Thanks a lot!

**Comment by ebyhr** [comment]
No, it doesn't. It's ongoing in https://github.com/trinodb/trino/pull/16445.
Let me close as duplicate of #6993
