### ISSUE TITLE
Remove unused FallbackToFullNodePartitionMemoryEstimator

### ISSUE THREAD

**Issue by reswqa** [trinodb/trino#16845]
We have already removed `FullNodeCapableNodeAllocatorService` in https://github.com/trinodb/trino/pull/12191. As a result, `FallbackToFullNodePartitionMemoryEstimator` maybe is no longer needed. I'm not sure exactly why it wasn't removed. I wonder if we can safely remove it, and if so, I'd like to open a PR to cleanup this.

**Comment by reswqa** [comment]
cc @losipiuk for further information.

**Comment by losipiuk** [comment]
Yeah - it is not needed any more. Happy to accept cleanup PR.

**Comment by reswqa** [comment]
@losipiuk Thanks for your attention and quick reply, I have submitted the CLA file to `cla@trino.io` and created the pull request. Would you mind taking a look at this in your free time.
