### ISSUE TITLE
Trino's case sensitive issue: The iceberg S3 table with upper case name was browsed as lower case in Trino

### ISSUE THREAD

**Issue by atptour2017** [trinodb/trino#16915]
I have data in tables stored in AWS S3 format. And I use Trino with iceberg connector to browse the table and the data. I found out that the tables with upper-case name were browsed as lower-case name and column name as same. What's the matter? Why does Trino could not read out case-sensitivity correctly?

**Comment by ebyhr** [comment]
Please take a look at https://github.com/trinodb/trino/issues/17

**Comment by atptour2017** [comment]
> Please take a look at #17

I took a look at #17. The content is about discussion how to solve it. But as a user, I do not have interest in the detail realization, I only want to use case-sensitivity. how can I get case-sensitivity result during browsing? I were puzzled. I use the latest docker image. But it does not work well on case-sensitivity.

**Comment by atptour2017** [comment]
> Please take a look at #17

It seems that we can solve this problem by setting case-insensitive-name-matching=true. But according to the official doc this setting is only effective for some of the connector types but not iceberg. I have tried to set this for iceberg but the docker container can not run up. How can I get to the aim for iceberg?

**Comment by atptour2017** [comment]
> Please take a look at #17

Are the contents in https://github.com/trinodb/trino/wiki/Delimited-Identifiers and #17 the solution to solve case-sensitivity?
