### ISSUE TITLE
Parser mistakes grouping set specification for ROW in ROLLUP and CUBE

### ISSUE THREAD

**Issue by lukaseder** [trinodb/trino#16981]
I'm using trino 412 from here: https://hub.docker.com/r/trinodb/trino.

These two queries should be equivalent, given that `ROLLUP` is just syntax sugar for `GROUPING SETS`:

```sql
select a, b, c, count(*)
from (values (1, 1, 1), (1, 2, 2), (1, 2, 2)) t (a, b, c)
group by rollup (a, (b, c))
order by 1, 2, 3;

select a, b, c, count(*)
from (values (1, 1, 1), (1, 2, 2), (1, 2, 2)) t (a, b, c)
group by grouping sets ((a, b, c), a, ())
order by 1, 2, 3;
```

They should both produce:

```
|a  |b  |c  |count|
|---|---|---|-----|
|1  |1  |1  |1    |
|1  |2  |2  |2    |
|1  |   |   |3    |
|   |   |   |3    |
```

But the trino parser seems to think that `(b, c)` is a row value expression, rather than a grouping set specification:

> SQL Error [63]: Query failed (#20230412_114613_00004_whng5): line 3:21: GROUP BY expression must be a column reference: ROW (b, c)

Given that the parser does the right thing for the `GROUPING SETS` syntax (which is the workaround here, of course), I think that's just a parser bug?

`CUBE` is also affected.

**Comment by martint** [comment]
Yes, this is actually missing functionality in Trino. It currently only supports CUBE and ROLLUP with simple column references.
