### ISSUE TITLE
Support for data type int256 (32 bytes number)

### ISSUE THREAD

**Issue by himitsuko** [trinodb/trino#17005]
## Feature request
This is a feature request to enable Trino to support uint256 on Ethereum's Smart Contract data types (int256 is more generally).
## A bit of background
I have indexed Transfer [2] event logs [1] for a token from the Ethereum blockchain to S3 in json format as example [2].
And did an aggregate query to calculate the token's balance of all addresses with Trino as below.
```sql
select contract_address, address, sum(am)/pow(10,18) as balance from (select contract_address, from_address as address, -1*try_cast(amount as DECIMAL) as am FROM transfer_events
union all
select contract_address, to_address as address, try_cast(amount as DECIMAL) as am FROM transfer_events) group by contract_address, address order by balance desc;
```
This request is important because without a data type which supports these numbers we will not be able to perform any queries or filtering to aggregate the extract value of the address's balance without the overflow when casting the number.

## References
[1] https://goethereumbook.org/en/event-read-erc20/

## Examples
[2] Transfer event:
```json
{
  "contract_address": "0x2dff88a56767223a5529ea5960da7a3f5f766406",
  "from_address":"0x0000000000016a723d0d576df7dc79ec149ac760",
  "to_address":"0x0000000000d81255748d2173523d52518803ad99",
  "amount":"18000000000000000000000000000000000000"
}
```

**Comment by zeropool** [comment]
also need this enhancement

**Comment by azisi** [comment]
The amount is also unint256, so there is a need to query and aggregate these values.

**Comment by shubham-kanodia** [comment]
Need this enhancement too

**Comment by hashhar** [comment]
I'm closing for now, feel free to re-open if you still intend to work on this (although it's unlikely to be merged) or if you want to implement arbitrary precision numeric type.
