### ISSUE TITLE
Trino Docker container does not work out of the box on Windows 11

### ISSUE THREAD

**Issue by delsehi** [trinodb/trino#17019]
I tried using the provided commands for starting the demo container on Windows with Docker Desktop installed.

For example: 

`$ docker run --name trino -d -p 8080:8080 --volume $PWD/etc:/etc/trino trinodb/trino`
or
`docker run --name trino -d -p 8080:8080 trinodb/trino`

The container wouldn't start however. I got the following error: 
```
+ launcher_opts=(--etc-dir /etc/trino)
+ grep -s -q node.id /etc/trino/node.properties
+ launcher_opts+=("-Dnode.id=${HOSTNAME}")
+ exec /usr/lib/trino/bin/launcher run --etc-dir /etc/trino -Dnode.id=1698fc6f6a57
ERROR: [Errno 28] No space left on device: '/data/trino/var'
```

If I mounted several volumes however, I got the container working again:

`docker run --name trino -d -p 8080:8080 --volume $PWD/etc/catalog:/etc/trino/catalog --volume $PWD/data/trino:/data/trino --volume $PWD/usr/lib/trino/var:/usr/lib/trino/var trinodb/trino`

I don't know if this is a bug, if I've configured Docker in a strange way or something else.

**Comment by nineinchnick** [comment]
Go to Docker Desktop settings, to the `Resources` tab, and check the `Virtual disk limit`. This is shared between images and containers. If you have lots of images, you might not have any space left for containers. I'm not sure why the container starts at all, if there would be too little space left, but try either increasing this value, or reclaiming some space by removing unused images with a command like `docker system prune`. Read up on all side effects of that before running it.
