### ISSUE TITLE
trino 413 test failed on arm builds

### ISSUE THREAD

**Issue by chenrui333** [trinodb/trino#17023]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  ==> /opt/homebrew/Cellar/trino/413/bin/trino --debug --server localhost:54830 --execute 'SELECT state FROM system.runtime.nodes'
  Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
  Apr 12, 2023 7:28:46 PM org.jline.utils.Log logr
  WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
  Error running command: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:54830
  java.io.UncheckedIOException: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:54830
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/4684771344/jobs/8301867773
relates to Homebrew/homebrew-core#128227

**Comment by hashhar** [comment]
the error suggests nothing is listening on the given port.

Feel free to reopen if this is reproducible or if you can collect more details.
