### ISSUE TITLE
Remove TODOs that about the table name

### ISSUE THREAD

**Issue by chenjian2664** [trinodb/trino#17043]
Remove  about the `TODO (https://github.com/trinodb/trino/issues/5901) Use longer table name once Oracle version is updated` in the tests, given test table readable name.
Follow up about the https://github.com/trinodb/trino/issues/5901

**Comment by dhananjay0610** [comment]
Hi, I will Raise the PR for the same, please assign this to me.

**Comment by ebyhr** [comment]
This should be handled in #5901, not as follow-up. See TODO comments about #5901.
