### ISSUE TITLE
CI runs on every comment

### ISSUE THREAD

**Issue by paoliniluis** [trinodb/trino#17076]
Seems you run the CI on every issue comment. I made a comment in an old issue and got an email from Github saying that a task ran

https://github.com/trinodb/trino/blob/4ab52e4a5e2abd31d7b28aa506dd788e11f62091/.github/workflows/ok-to-test.yml#L6

**Comment by nineinchnick** [comment]
What was in the email you got? We run these tasks on purpose, but it should not be notifying anyone.

**Comment by paoliniluis** [comment]
This "might" have been something on my end, as I had a fork of Trino after my comment (don't know why yet), and got this email 
![image](https://user-images.githubusercontent.com/1711649/232600508-8f37d584-1b89-4cfc-912e-e8ce9224b901.png)
