### ISSUE TITLE
Postgres connector doesn't support subquery in delete where clause

### ISSUE THREAD

**Issue by RugratsJ** [trinodb/trino#17081]
If we try to delete from a Postgres table with the following sub-query in where clause:

delete from table1 where key_1 in (select distinct key_1 from table2)

It throw the following error:

failed: Unsupported delete

When will this type of delete in Postgres connector be supported?

Thanks

**Comment by hashhar** [comment]
This is a known limitation for now. Follow https://github.com/trinodb/trino/issues/6993
