### ISSUE TITLE
timestamp is different queried by trino and presto.

### ISSUE THREAD

**Issue by njalan** [trinodb/trino#17091]
prestosql is 340.
trino is 406.
hudi is 0.9

Below is the output for query select max(modified)   from  ods.xxx (**hudi table**);
prestosql is 2023-04-18 15:00:13.000000000
trino is 2023-04-18 07:00:13.000000000(UTC time)

I didn't set any timezone on jvm or config files. I check both timezome is Asia/Shanghai. But Got the same result on **hive** **table**.  
How can I get the output as  2023-04-18 15:00:13 for trino?

**Comment by ebyhr** [comment]
Answered in https://trinodb.slack.com/archives/C03R7CJG8TH/p1681806970061219
