### ISSUE TITLE
Simplify `LIKE '%'` predicates

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#17124]
`information_schema` and `system.jdbc` queries would benefit if we simplified `table_name LIKE '%'`  (and `table_name LIKE '%%'` etc.) queries to `table_name IS NOT NULL`.

**Comment by findepi** [comment]
cc @huberty89 @kokosing @martint

**Comment by kokosing** [comment]
Is this only `information_schema` specific? It sounds like it could be a generic optimization. Does `%` match an empty string too?

**Comment by findepi** [comment]
yes, the optimization should be generic. i mentioned `information_schema` and `system.jdbc` to emphasize importance of such optimization. In these places, today we take different, less optimal code path when `LIKE '%'` predicate is present.

**Comment by chenjian2664** [comment]
I am interested in this part, Could you guide me on how to start on this part?

**Comment by kokosing** [comment]
I am under impression that this rewrite could be handled by `io.trino.sql.planner.iterative.rule.SimplifyExpressions`

**Comment by chenjian2664** [comment]
@kokosing Thank you
