### ISSUE TITLE
Add partition column/details to Iceberg's Files table

### ISSUE THREAD

**Issue by osscm** [trinodb/trino#17148]
Right now `$files` table does not have the `partition` column, though the https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/ContentFile.java#L52 has the partition which can be used (DataFile extends ContentFile)

users can use it for file analysis with the partition filters, debugging, associating partitions with the files.

**Comment by osscm** [comment]
cc @alexjo2144 @findepi 
if you can share your thoughts, please.

**Comment by ebyhr** [comment]
Closing as https://github.com/trinodb/trino/pull/24102
