### ISSUE TITLE
SQL aggregate function for longest common prefix

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#17194]
ie an equivalent to:
https://www.tutorialspoint.com/longest-common-prefix-in-python

**Comment by chenjian2664** [comment]
Could you elaborate more about this? @tooptoop4

**Comment by tooptoop4** [comment]
@chenjian2664 its an aggregate function, i imagine it would look like select longest_common_prefix(somecolumn) from inputtable.

if inputtable had these 3 rows:
"school"
"schedule"
"scotland"

the function should return "sc" because that is the longest value that ALL rows fed into the aggregate function start with

**Comment by chenjian2664** [comment]
@tooptoop4 Got it, thanks!
