### ISSUE TITLE
AccumuloClient init failure

### ISSUE THREAD

**Issue by chenjian2664** [trinodb/trino#17203]
https://github.com/trinodb/trino/actions/runs/4782593419/jobs/8502414789?pr=17196#step:6:5623
Due to the namespace already exists.

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/4782604126/jobs/8502456745

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/4774356723/jobs/8488183532?pr=17174
