### ISSUE TITLE
Add test for datetime type in MariaDB connector 

### ISSUE THREAD

**Issue by zhaoyim** [trinodb/trino#17242]
Got new requirement for datetime support in MariaDB connector

**Comment by willshen** [comment]
Thank for creating the ticket @zhaoyim - right now I see that DateTime type in MariaDB would get converted to Timestamp when queried from Trino. It seems to work. Do you know what might be the limitations of not having a DateTime type in Trino?

**Comment by ebyhr** [comment]
Let's just update type mapping test and `mariadb.rst`.

**Comment by rohankumardubey** [comment]
Hi everyone just wanted to know if this issue is still open. New to the Trino community.

**Comment by ebyhr** [comment]
It's still open. Please feel free to send a PR.
