### ISSUE TITLE
Efficient deterministic pagination on pre-sorted data

### ISSUE THREAD

**Issue by mustafahafidi** [trinodb/trino#17302]
I'm exploring Trino as a query engine for an underlying data lake (based on raw Parquet/ORC). I've stumbled against a blocker to support deterministic pagination on the querying.
Data is partitioned per date and there's a guarantee this is maintained on the write path.

When I perform TopN queries such as:
```
SELECT * FROM table
ORDER BY createdAt
FETCH FIRST 3 ROWS WITH TIES
```
It unnecessarily performs a full scan of the data lake although `createdAt` is indeed the partition key. I have tried this with Glue, using the Hive connector (S3) on raw files w/ partition projection. As well as on Iceberg tables with locally sorted data (within partition).

The use case is to support deterministic pagination, sorting is not a requirement for us. Any recommendation how to achieve this efficiently?

Thanks

**Comment by thomafred** [comment]
Hi @mystaroll, did you solve this?
