### ISSUE TITLE
Update documentation for type mapping in MongoDB connector

### ISSUE THREAD

**Issue by Praveen2112** [trinodb/trino#17322]
https://trino.io/docs/current/connector/mongodb.html?highlight=mongodb#type-mapping - Docs doesn't specify the support for Decimal data type in MongoDB connector but the [test coverage](https://github.com/trinodb/trino/blob/24c0f6272f2ff285831a0251d02afc9b7d1b6cf1/plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java#L164) proves we support decimal type. So we might need to make the doc in sync for MongoDB connector

**Comment by Praveen2112** [comment]
cc: @ebyhr - Please confirm if the `Decimal` type is supported in MongoDB connector 
cc: @mosabua - For docs related changes

**Comment by mosabua** [comment]
I can add more details for the docs PR if we need to ..

**Comment by ebyhr** [comment]
> Please confirm if the Decimal type is supported in MongoDB connector

Yes, the connector supports decimal type.
