### ISSUE TITLE
Add support for EXECUTE IMMEDIATE statement

### ISSUE THREAD

**Issue by aalbu** [trinodb/trino#17353]
Currently, running a prepared statement requires 3 requests: `PREPARE`, `EXECUTE... USING`, and `DEALLOCATE`.  In some cases, once a statement is prepared, it's executed many times before it's deallocated, so the cost of additional requests gets amortized.  However, some frameworks will generate a sequence like above for every operation.

Proposal:

Add a new parametrized statement that also includes the parameters to be bound.  Note that while the SQL spec contains a statement with similar syntax and semantics, we are deviating from the standard (as it does not allow parameters to be bound).

Syntax:
```
EXECUTE IMMEDIATE
'SELECT * FROM t WHERE a = ? and b = ?'
USING 'foo', 42
```

The semantics are the same as:
```
PREPARE stmt1 FROM SELECT * FROM t WHERE a = ? and b = ?
EXECUTE stmt1 USING 'foo', 42
DEALLOCATE PREPARE stmt1
```

**Comment by findepi** [comment]
> EXECUTE IMMEDIATE
> 'SELECT * FROM t WHERE a = ? and b = ?'
> USING 'foo', 42

i don't think we need apostrophes around the query.
And apostrophes will make the feature hard to use in command line or in tests.
(i have been thinking about this feature  every time i see our simplistic SQL-injection-like SQL queries in integration tests)

we can do without apostrophes
```sql
EXECUTE IMMEDIATE <query>
USING <parameters>
```

if this could lead to parsing  ambiguities, we can put braces around `<query>` (and then we probably no longer need `IMMEDIATE` as a differentiator from normal `EXECUTE`):

```sql
EXECUTE [IMMEDIATE] (<query>)
USING <parameters>
```

or we can reverse the order
```sql
WITH PARAMETER <parameters>
EXECUTE <query>
```

cc @trinodb/maintainers

**Comment by aalbu** [comment]
I agree that not embedding the statement to be executed as a string is more convenient.  The motivation for choosing this form is that the syntax is closer to the standard (though as I mentioned not compliant).  `PREPARE`, `EXECUTE`, `DEALLOCATE` are all part of the dynamic SQL specification (incidentally, it turns out that `PREPARE` should also include the statement as a string).

```
<execute immediate statement> ::=
  EXECUTE IMMEDIATE <SQL statement variable>

<SQL statement variable> ::=
  <simple value specification>

<simple value specification> ::= <literal>
  | <host parameter name>
  | <SQL parameter reference>
  | <embedded variable name>
```

**Comment by martint** [comment]
@findepi, the syntax per the SQL standard requires using a host variable of type string. We don’t have such a concept in Trino, so the closest we can get is to support a string literal instead.

In fact, PREPARE is implemented incorrectly (not per spec), so we should retrofit it to support this syntax, too, at some point.

**Comment by nineinchnick** [comment]
Should we document why we don't want to interpolate queries on the client side?

**Comment by hashhar** [comment]
> Should we document why we don't want to interpolate queries on the client side?

- prevent SQL injection bugs (by not having to worry about it)
- make all clients benefit from new data type support (i.e. no need to modify client when adding new data type)
- no need to modify client for custom Trino types
- keeping clients simple to implement
