### ISSUE TITLE
Fix `--password` option for CLI documentation

### ISSUE THREAD

**Issue by hassanahmadkhani** [trinodb/trino#17402]
In https://trino.io/docs/current/client/cli.html#authentication
seems required to edit and change as below :

--password parameter also required in cli command after setting TRINO_PASSWORD environment variable.

export TRINO_PASSWORD='LongSecurePassword123!@#'

The password is automatically used in any following start of the CLI if we use --password in cli as below:

./trino --server https://trino.example.com --user=exampleusername --password

**Comment by ebyhr** [comment]
@hassanahmadkhani Do you want to send a PR?

**Comment by hassanahmadkhani** [comment]
> @hassanahmadkhani Do you want to send a PR?
No

**Comment by mosabua** [comment]
Fix will go live with the documentation for 420. Your testing was correct. Thank you so much for reporting @hassanahmadkhani
