### ISSUE TITLE
Add `extra_properties` to Iceberg table properties

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#17427]
Same as #16592 , but for Iceberg

**Comment by osscm** [comment]
Hi @findinpath 
please find some discussion around this, our team also wanted to build similar feature. https://trinodb.slack.com/archives/CJ6UC075E/p1663694635639759

cc @marton-bod @vgankidi

**Comment by vgankidi** [comment]
We have a patch for this internally and could contribute if community sees benefit in this feature.

**Comment by findinpath** [comment]
@vgankidi  please create a corresponding PR

**Comment by Priyansh121096** [comment]
/assign

Hello, I'd like to work on this feature.

**Comment by szisiu** [comment]
nice work!
