### ISSUE TITLE
Store all table metadata to the metastore in the Delta lake connector

### ISSUE THREAD

**Issue by jkylling** [trinodb/trino#17519]
The Delta lake connector [does not store table metadata](https://github.com/trinodb/trino/blob/e0532846d8971d376ca9276aa452cbf62403d101/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java#L849), like table comments or column names and data types to the Hive metastore. Instead a dummy data column is inserted, while table comments are not stored. The additional table metadata could in principle be obtained from the delta log, but this is awkward for tools which connect directly to the Hive metastore to get the table metadata. Could the trino-delta-lake plugin be modified to store the full table metadata to the metastore?

There are some risks with storing table metadata in both the Delta log and in the metastore, as the update to the Delta log and the metastore do not happen transactionally. This means that operations like `ALTER TABLE` could lead to divergent state in the delta log and the metastore. Potentially a stored procedure could be added to sync the state in the metastore and the delta log, in case the state is suspected to be divergent.

**Comment by hashhar** [comment]
The metastore isn't the source of truth for anything regarding Delta Lake tables other than the location.

What tools are using metastore when interacting with Delta Lake tables? Ideally they need to be fixed to properly support Delta Lake.
Note that everything that Delta Lake supports isn't supported by HMS (e.g. not all column type changes are valid and hence the sync would fail) anyway so the sync won't work always.

cc: @alexjo2144

**Comment by jkylling** [comment]
> The metastore isn't the source of truth for anything regarding Delta Lake tables other than the location.
> 
> What tools are using metastore when interacting with Delta Lake tables? Ideally they need to be fixed to properly support Delta Lake. Note that everything that Delta Lake supports isn't supported by HMS (e.g. not all column type changes are valid and hence the sync would fail) anyway so the sync won't work always.
> 
> cc: @alexjo2144

These are custom tools for creating table explorer like functionality (e.g., show which tables are in a database, and which columns are in the table). Obtaining this information directly from the Delta logs and keeping it in sync is resource intensive if you have a large amount of tables, as it requires reading all the delta logs from S3 (this could be a couple of MBs per table).

The Databricks runtime does store table comments and column metadata of Delta tables to its metastore, although they might be running with a custom implementation.

**Comment by findinpath** [comment]
Closing this issue because it has been fixed through https://github.com/trinodb/trino/pull/21463

cc @ebyhr
