### ISSUE TITLE
Delta Lake connector can't change data on Alluxio

### ISSUE THREAD

**Issue by soliverr** [trinodb/trino#17537]
Delta Lake connector perfectly works in this case:

```sql
create table if not exists my_test (
	id varchar,
	aggregator_id varchar,
	parent_name varchar,
	create_dt date
)
with (
	location='s3a://my-data-warehouse/warehouse/marts/test', 
	partitioned_by = array['create_dt']
);

insert into my_test values('1', '0', 'test name 1', date('2023-01-01'));
insert into my_test values('2', '1', 'test name 2', date('2023-01-01'));

delete from my_test;

drop table my_test;
```

But can't do the same on Alluxio FS:

```sql
create table if not exists my_test (
	id varchar,
	aggregator_id varchar,
	parent_name varchar,
	create_dt date
)
with (
	location='alluxio://alluxio-master-0:19998/warehouse/marts/test', 
	partitioned_by = array['create_dt']
);

insert into my_test values('1', '0', 'test name 1', date('2023-01-01'));
```

Any inserts, updates and deletes generate an error:

```
SQL Error [13]: Query failed (#20230517_134110_00225_s4yin): Inserts are not enabled on the alluxio filesystem in order to avoid eventual data corruption which may be caused by concurrent data modifications on the table. Writes to the alluxio filesystem can be however enabled with the 'delta.enable-non-concurrent-writes' configuration property.
```

Configuration property `delta.enable-non-concurrent-writes` has no effect.

**Comment by findepi** [comment]
I think the exception is coming from Alluxio code. The `alluxio://` filesystem seems to be read-only.
I will close this, as there is nothing we can do.

BTW I would not recommend using Alluxio. The Alluxio integration doesn't seem to me properly maintained.

**Comment by soliverr** [comment]
The Alluxio filesystem is not in read-only mode, 'cause CTAS works fine. Looks like some check failed in Trino code. I'll be dig further.

**Comment by findepi** [comment]
You're right. The exception message changed a bit that's why I couldn't find it and though it's coming from alluxio code.

> Configuration property delta.enable-non-concurrent-writes has no effect.

What's the full stacktrace you're getting?
