### ISSUE TITLE
add collect_set(col) function

### ISSUE THREAD

**Issue by bhji123** [trinodb/trino#1756]
Hi, in my company, there are many scenarios that require a function to return a set of objects with duplicate elements eliminated, can you add this support? Just like collect_set(col) in hive.

**Comment by Praveen2112** [comment]
hi, I'm not sure about this approach , how about using array functions for the same `array_agg(distinct(col))` or even this`array_distinct(array_agg(col))`

**Comment by bhji123** [comment]
> hi, I'm not sure about this approach , how about using array functions for the same `array_agg(distinct(col))` or even this`array_distinct(array_agg(col))`

Yes, array_agg(distinct(col)) can help, but question is distinct operation used to be slow, especially when data is huge.

**Comment by bhji123** [comment]
> hi, I'm not sure about this approach , how about using array functions for the same `array_agg(distinct(col))` or even this`array_distinct(array_agg(col))`

I have implemented such approach, could you review it? 
https://github.com/prestosql/presto/pull/1757
