### ISSUE TITLE
Test `TIMESTAMP_NTZ` type in Iceberg connector

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#17562]
Relates to https://github.com/apache/iceberg/issues/7456 & https://github.com/apache/iceberg/pull/7553

**Comment by findepi** [comment]
How is TIMESTAMP_NTZ different from timestamp?

Is TIMESTAMP_NTZ a Spark name for the Iceberg `timestamp` (without zone) type which we map to Trino `timestamp`?
