### ISSUE TITLE
Defunct property log.max-history is included in docs.

### ISSUE THREAD

**Issue by ankushChatterjee** [trinodb/trino#17588]
The property `log.max-history` has been marked as defunct Airlift.
Ref PR : https://github.com/airlift/airlift/pull/1042/files

When this property is provided, the trino server fails to start with airlift errors. Given this, should this property be mentioned in the docs?

Instead, can the docs mention the property : `log.max-total-size` ?

**Comment by ebyhr** [comment]
cc: @mosabua

**Comment by mosabua** [comment]
Addressed both in the PR

**Comment by willshen** [comment]
Adding a note on the trail of changes (in case anyone is looking in the future):
- This property became defunt in Release 411 in https://github.com/trinodb/trino/pull/16401 when we moved from Airlift 225 to 228.
- In Airlift 226, the deprecated property was officially removed in https://github.com/airlift/airlift/pull/1042.
