### ISSUE TITLE
query_max_scan_physical_bytes is not working

### ISSUE THREAD

**Issue by akenO8** [trinodb/trino#17600]
Trino version : 417

![image](https://github.com/trinodb/trino/assets/37773807/76a97113-09c3-4dec-bdd5-1878fc659d9e)

I have set query.max-scan-physical-bytes to 1MB in config.properties and have restarted all nodes, but found that this does not prevent queries that exceed the threshold.

Is there something wrong?

**Comment by raunaqmorarka** [comment]
`query.max-scan-physical-bytes` doesn't guarantee exact limits. The coordinator needs to observe statistics about bytes read from the task statuses to make the decision to kill the query and the orc/parquet reader on workers will generally read many files in parallel in 8MB chunks by the time the coordinator can take action.

**Comment by akenO8** [comment]
When query.max-scan-physical-bytes is set to how many, it's almost accurate? greater than 8MB*wokers?
