### ISSUE TITLE
replaceall regex does not produce result for control characters in trino CLI

### ISSUE THREAD

**Issue by natarajank11** [trinodb/trino#17614]
Trino UDF (version 407):
Basically i want to remove control characters from the string.

I tried following regex pattern,
`String regex = "[\\\\p{C}]";`

Trino result,
`
select rm_code('hello\bhello\thello'); => hellobhellothello`

This ticket is similar to https://github.com/trinodb/trino/discussions/17474

**Comment by hashhar** [comment]
Answered at https://github.com/trinodb/trino/discussions/17673, avoid posting in multiple places. It doesn't help in getting quicker answers.
