### ISSUE TITLE
Make IcebergSplitSource generate splits asynchronously

### ISSUE THREAD

**Issue by lirui-apache** [trinodb/trino#17631]
The current `IcebergSplitSource::getNextBatch` is synchronous by returning a completed future. I wonder if there're specific reasons why it's implemented this way and whether we can make it asynchronous.

Some background: we made our iceberg use a blocking queue when planning files (in order to reduce memory consumption). Then if multiple-stage query run concurrently in trino, it can run into some kind of dead lock, because the stage scheduler can be blocked at `IcebergSplitSource::getNextBatch` while the thread pool used in planning files is occupied by other stages.

**Comment by findinpath** [comment]
This request is probably handled by https://github.com/apache/iceberg/pull/10691

**Comment by lirui-apache** [comment]
Yes, I think this is not needed anymore, closing it
