### ISSUE TITLE
OAuth2.0: Support for different JWT types such as at+jwt

### ISSUE THREAD

**Issue by ghost** [trinodb/trino#17640]
Hi,

I would like to add support for different jwt types for local jwt validation, such as at+jwt to allow compliance with the following standard: https://datatracker.ietf.org/doc/html/rfc9068

Currently the nimbus-jose-jwt validator implementation used does not support validation of at+jwt typ headers as it uses the default JOSEObjectType of plain JWT https://github.com/trinodb/trino/blob/408855ee8cd5fadf7c0cfbeab00e6901419ed838/core/trino-main/src/main/java/io/trino/server/security/oauth2/NimbusOAuth2Client.java#L140-L150

If support is to be added, it needs to be configured explicitly as described in the nimbus-jose-jwt documentation here: https://connect2id.com/products/nimbus-jose-jwt/examples/validating-jwt-access-tokens

The implementation I'm thinking of would involve making a change to add a new configuration option which, when set, sets the required "typ" header to the configuration value for access tokens as
`processor.setJWSTypeVerifier(new DefaultJOSEObjectTypeVerifier<>(new JOSEObjectType(configVal)));
`

Please let me know if I am missing something

**Comment by connorlwilkes** [comment]
This would be really useful
