### ISSUE TITLE
How to set the trino character set encoding

### ISSUE THREAD

**Issue by akenO8** [trinodb/trino#17674]
about trino character set encoding
`desc tb` is ok, but `show create table tb` is not ok

![image](https://github.com/trinodb/trino/assets/37773807/3cefbef2-5769-4ca1-9af9-aa03d77d813d)

How do I set the trino character set encoding, to make `show create table tb` comment appear properly?

**Comment by ebyhr** [comment]
Closing as duplicate of #5061
