### ISSUE TITLE
Migrate deprecated `QueryAssert.assertThat` method

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#17690]
`io.trino.tempto.assertions.assertThat` method is deprecated now. We want to migrate like this:
* `QueryAssert assertThat(QueryResult queryResult`) → `Assertions#assertThat(AssertProvider)`
* `QueryExecutionAssert assertThat(QueryCallback queryCallback)` → `assertQueryFailure(QueryCallback)`

**Comment by Sam-ScottLogic** [comment]
May I work on this?
