### ISSUE TITLE
MySQL connection: An error is generated when the text data type field is queried ( Apache Doris), 

### ISSUE THREAD

**Issue by langbai20** [trinodb/trino#17750]
Trino version: 403

The problem is described as follows:
The table in the doris data source uses the text data type：
<img width="602" alt="image" src="https://github.com/trinodb/trino/assets/88966261/97ccf6a9-292d-4c38-a9a4-adec45275c32">
The result of querying doris metadata using trino is varchar(1).
![image](https://github.com/trinodb/trino/assets/88966261/5edfd8a0-3c37-497f-933e-775631bd2019)

Therefore, the query table failed:
<img width="511" alt="image" src="https://github.com/trinodb/trino/assets/88966261/43891d5b-dff2-4eb6-ba42-04d2deac3386">

Is there a configuration parameter that can solve this problem？Look forward to the community friends help, thanks!

**Comment by langbai20** [comment]
when we used presto to query, text is converted to varchar(65535)
![image](https://github.com/trinodb/trino/assets/88966261/bd1861e4-787e-454e-a00d-48590be5817c)

trino doc also display "text convert to varchar(65535)"
<img width="1440" alt="image" src="https://github.com/trinodb/trino/assets/88966261/4645bffa-faea-4233-88b0-d3b8e1044f60">

**Comment by ebyhr** [comment]
First of all, Doris isn't supported. Please take a look at #8653

**Comment by langbai20** [comment]
doris supports mysql connection. 
The same scene presto is supported, but trino isn’t work. Isn't that a problem?
