### ISSUE TITLE
trino-server takes up more memory than the heap-size plus off-heap-size memory and does not release it for a long time

### ISSUE THREAD

**Issue by akenO8** [trinodb/trino#17766]
trino version: 417

This trino woker still has high memory usage even though there are no user queries throughout the cluster.
![image](https://github.com/trinodb/trino/assets/37773807/cc01aab1-c936-4d44-947b-f22c3075b535)
![image](https://github.com/trinodb/trino/assets/37773807/7efb5769-5f9d-462c-a26d-7e8439abbf54)

However, I use `jhsdb jmap --heap --pid 20507` to check the heap information of this process and find that its heap memory usage is only 5 G, mainly because the old age accounts for 4 G. Although I do not understand why there are so many old age unreleased after such a long time, other workers in the cluster do not have this situation.
![image](https://github.com/trinodb/trino/assets/37773807/200c6727-032d-43cc-859c-9330eb5d45a4)

Then I found out through `http://hostname:port/v1/jmx/mbean` that the off-heap memory used by this machine was only 200m+.
![image](https://github.com/trinodb/trino/assets/37773807/bd0367dd-edeb-4c35-9ec7-758faba74191)

The question is, why does the operating system show that the trino-server process is using so much memory, but I can't find out where the memory is being used.

Can you give me some advice? Thank you

**Comment by raunaqmorarka** [comment]
See related discussion in slack https://trinodb.slack.com/archives/CP1MUNEUX/p1671768273411949

> findepi
  (https://trinodb.slack.com/archives/CP1MUNEUX/p1671773620402979?thread_ts=1671768273.411949&cid=CP1MUNEUX)
JVM generally doesn’t give back memory to the operating system.
And within JVM, heap occupancy will appear large until garbage is collected, but G1 GC won’t do that, if no-one needs memory.

> raunaqm
  (https://trinodb.slack.com/archives/CP1MUNEUX/p1675840188088789?thread_ts=1671768273.411949&cid=CP1MUNEUX)
To make JVM release memory back to OS, if you're using JVM version >=12, you can add something like -XX:G1PeriodicGCSystemLoadThreshold=5 -XX:G1PeriodicGCInterval=900k to JVM configs to make the JVM periodically release memory to OS during periods of low load avg on the system (https://openjdk.org/jeps/346).
Alternatively, you could monitor Trino's internal memory pools usage through JMX metrics and rely on that to understand memory usage if that's your aim. Typically Trino containers are not scaled vertically, most ppl use horizontal scaling to reduce resource usage during idle periods, so there isn't much practical benefit to making Trino JVM release memory back to the OS.

**Comment by akenO8** [comment]
> See related discussion in slack https://trinodb.slack.com/archives/CP1MUNEUX/p1671768273411949
> 
> > findepi
> > (https://trinodb.slack.com/archives/CP1MUNEUX/p1671773620402979?thread_ts=1671768273.411949&cid=CP1MUNEUX)
> > JVM generally doesn’t give back memory to the operating system.
> > And within JVM, heap occupancy will appear large until garbage is collected, but G1 GC won’t do that, if no-one needs memory.
> 
> > raunaqm
> > (https://trinodb.slack.com/archives/CP1MUNEUX/p1675840188088789?thread_ts=1671768273.411949&cid=CP1MUNEUX)
> > To make JVM release memory back to OS, if you're using JVM version >=12, you can add something like -XX:G1PeriodicGCSystemLoadThreshold=5 -XX:G1PeriodicGCInterval=900k to JVM configs to make the JVM periodically release memory to OS during periods of low load avg on the system (https://openjdk.org/jeps/346).
> > Alternatively, you could monitor Trino's internal memory pools usage through JMX metrics and rely on that to understand memory usage if that's your aim. Typically Trino containers are not scaled vertically, most ppl use horizontal scaling to reduce resource usage during idle periods, so there isn't much practical benefit to making Trino JVM release memory back to the OS.


Thank you very mach.
The above discussion focuses on heap memory.
However, I found through jmap that the heap memory usage of the trino-server is not much (5G), and the out-of-heap memory is also very little (200M), but the trino-server process takes up 42G of memory.
I want to know what is taking up 42G of memory?

**Comment by hashhar** [comment]
JVM allocates entire heap to itself. So it's possible that the JVM asked for 42G from OS out of which only 5GB is used at the moment.

I'm not sure how `jmap` shows it but tools like visualVM show three values - max (-Xmx), size (42G in your case), used (5G in your case).
