### ISSUE TITLE
Correctness issues in S3 Select Pushdown

### ISSUE THREAD

**Issue by alexjo2144** [trinodb/trino#17775]
An initial set of corrections is here: https://github.com/trinodb/trino/pull/17563
- This fixed issues around null comparison and added tests

While testing that PR there were a few other issues I ran into:
- Comparison of decimal types produces incorrect results on AWS. (works on Minio)
- TEXTFILE tables (using CSV in S3 Select) fail to parse or produce incorrect results if these three properties are not explicitly set 
  `textfile_field_separator, textfile_field_separator_escape, null_format`
  - The reason for this is that AWS uses default values which assume CSV encoding, but they are not the same defaults as LazySimpleSerde which is what it's mapped to in Trino.
- The `S3SelectCsvRecordReader` checks for a [quote character](https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3select/csv/S3SelectCsvRecordReader.java#LL63C1-L63C65) in the Hive schema, but that property can't be set when creating tables in Trino using the `TEXTFILE` format

**Comment by pettyjamesm** [comment]
Not specifically, let's see if @dnanuti can help out with that

**Comment by alexjo2144** [comment]
Thanks Diana (replied with the decimal comparison example in a [different thread](https://github.com/trinodb/trino/pull/17563#discussion_r1222072290))

For anyone looking at potentially picking this up, these are some additional tests that don't pass. I belive all the issues here are on the Trino side, not AWS:
```
    @Test(dataProvider = "s3SelectFileFormats")
    public void testS3SelectPushdownWithSpecialCharacters(String tableProperties)
    {
        Session usingAppendInserts = Session.builder(getSession())
                .setCatalogSessionProperty("hive", "insert_existing_partitions_behavior", "APPEND")
                .build();
        List<String> values = ImmutableList.of(
                "1, 'a,comma'",
                "2, 'a|pipe'",
                "3, 'an''escaped quote'",
                "4, 'a~null encoding'");
        try (TestTable table = new TestTable(
                sql -> getQueryRunner().execute(usingAppendInserts, sql),
                "hive.%s.test_s3_select_pushdown".formatted(HIVE_TEST_SCHEMA),
                "(id INT, string_t VARCHAR) WITH (" + tableProperties + ")", values)) {
            assertS3SelectQuery("SELECT id FROM " + table.getName() + " WHERE string_t ='a,comma'", "VALUES 1", false);
            assertS3SelectQuery("SELECT id FROM " + table.getName() + " WHERE string_t ='a|pipe'", "VALUES 2", false);
            assertS3SelectQuery("SELECT id FROM " + table.getName() + " WHERE string_t ='an''escaped quote'", "VALUES 3", false);
            assertS3SelectQuery("SELECT id FROM " + table.getName() + " WHERE string_t ='a~null encoding'", "VALUES 4", false);
        }
    }
```

Additionally if you add 
```
{"format = 'TEXTFILE'"},
```
to the test data provider [here](https://github.com/trinodb/trino/pull/17563/files#diff-8213454100b62e8d193dd2e5cece6453115a1d705b81535540e1db667a662ce4R178)

**Comment by electrum** [comment]
@pettyjamesm @dnanuti can you reply to the above? @alexjo2144 has #18102 to disable S3 Select CSV support until this can be fixed (or worked around on our side)

**Comment by pettyjamesm** [comment]
The approach in https://github.com/trinodb/trino/pull/18102 seems reasonable- it seems like `decimal` types aren't handled correctly on the service side, and removing support for push down on that type makes sense for now until the team can triage the issue and prioritize a fix on their side.

The other issues do sound like they're fixable from the Trino side (something about a mismatch between `LazySimpleSerDe` and S3 Select defaults for escape characters?), but putting the feature behind a flag would be an OK mitigation in the mean time if we're not confident about the root cause or not sure how to fix the other (non-decimal) issues.

**Comment by alexjo2144** [comment]
S3 select was removed in https://github.com/trinodb/trino/pull/18241
