### ISSUE TITLE
Add support for comments on VIEW columns for Delta Lake

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#17773]
See similar implementation in HIve

https://github.com/trinodb/trino/blob/3298d6dbe84a1a65fb0aebfcf8008ebcde661e3a/plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java#L1454

**Comment by reswqa** [comment]
Hi @findinpath, I'd like to take this issue, could you help assign this to me? Thanks!
