### ISSUE TITLE
Invalid value 'jdbc' for type CatalogType (property 'iceberg.catalog.type') in order to call [public IcebergConfig IcebergConfig.setCatalogType(CatalogType)]

### ISSUE THREAD

**Issue by luxl6** [trinodb/trino#17781]
1) Error: Invalid value 'jdbc' for type CatalogType (property 'iceberg.catalog.type') in order to call [public IcebergConfig IcebergConfig.setCatalogType(CatalogType)]

2) Error: Configuration property 'iceberg.extended-statistics.enabled' was not used

3) Error: Configuration property 'iceberg.jdbc-catalog.catalog-name' was not used

4) Error: Configuration property 'iceberg.jdbc-catalog.connection-password' was not used

5) Error: Configuration property 'iceberg.jdbc-catalog.connection-url' was not used

6) Error: Configuration property 'iceberg.jdbc-catalog.connection-user' was not used

7) Error: Configuration property 'iceberg.jdbc-catalog.default-warehouse-dir' was not used

8) Error: Configuration property 'iceberg.jdbc-catalog.driver-class' was not used

**Comment by ebyhr** [comment]
What Trino version are you using?

**Comment by luxl6** [comment]
> 我相信 Trino 版本是旧的。请升级您的集群。

Running the container[#](https://trino.io/docs/current/installation/containers.html#running-the-container)
To run Trino in Docker, you must have the Docker engine installed on your machine. You can download Docker from the [Docker website](https://www.docker.com/), or use the packaging system of your operating systems.

Use the docker command to create a container from the trinodb/trino image. Assign it the trino name, to make it easier to reference it later. Run it in the background, and map the default Trino port, which is 8080, from inside the container to port 8080 on your workstation.

docker run --name trino -d -p 8080:8080 trinodb/trino

I deployed it in docker, using this method on the official website
