### ISSUE TITLE
Correctness issue with double slash location on Glue & S3 in Hive connector

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#17803]
The file is generated correctly under the table location, but it returns an empty result. Delta and Iceberg connectors are fine as far as I confirmed. 
```sql
create table test_slash (c1 int) with (external_location = 's3://bucket/foo//bar');
insert into test_slash values (1);
table test_slash;
 c1
----
(0 rows)
```

**Comment by findepi** [comment]
if we merge https://github.com/trinodb/trino/pull/17958, this will no longer be a release-blocker.

**Comment by findepi** [comment]
after https://github.com/trinodb/trino/issues/17803,  this
```sql
create table test_slash (c1 int) with (external_location = 's3://bucket/foo//bar');
```

will be rejected/
