### ISSUE TITLE
querying hudi is very slow in plan/optimizer stage

### ISSUE THREAD

**Issue by yx-keith** [trinodb/trino#17894]
too many function calls  for hive metastore api **io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient::getTable** in planning/optimizer stage: ****
 
    `---[32.827568ms] io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore:getTable()
        `---[97.49% 32.005212ms ] io.trino.plugin.hive.metastore.thrift.ThriftMetastore:getTable() #93

**every call takes tens of milliseconds when query hudi, so I optimized this in BridgingHiveMetastore use a cache.**

during every query, result of getTable in first time called will cached, subsequent calls in this query process will get table information from the cache. **cache key is queryId+databaseName+tableName, value is io.trino.plugin.hive.metastore.Table object**

**Comment by yx-keith** [comment]
when log level is debug, there are many calls  for hive metastore api: **io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient::getTable**
every call takes 25-50ms, so I optimized this in BridgingHiveMetastore using a cache,

**Comment by CTTY** [comment]
Does this happen when using Hudi Hive connector or Hudi Trino connector? If it's the latter then it should be fixed by this PR: https://github.com/trinodb/trino/pull/16034

**Comment by yx-keith** [comment]
> Does this happen when using Trino Hive connector or Hudi Trino connector? If it's the latter then it should be fixed by this PR: #16034
OK

**Comment by yx-keith** [comment]
> Does this happen when using Trino Hive connector or Hudi Trino connector? If it's the latter then it should be fixed by this PR: #16034

ths

**Comment by codope** [comment]
@yx-keith Can you please try with Trino version 420 or later?

**Comment by hashhar** [comment]
Closing since the relevant [PR](https://github.com/trinodb/trino/pull/16034) was merged. Feel free to reopen @yx-keith if you still see the performance issues.
