### ISSUE TITLE
Incorrect redirect in docs page

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#17906]
https://trino.io/docs/current redirects to https://trinodb.github.io/docs.trino.io/current/
the browser should stay in `https://trino.io/*`

**Comment by mosabua** [comment]
I will have to check if that is possible by adding a current.html file or a netlify redirect

**Comment by mosabua** [comment]
the normal behavior uses the link https://trino.io/docs/current/ (note the last / that indicates a folder vs a file) and works.

Out of curiosity so we can potentially fix .. where do you see the busted link in use @findepi ?

**Comment by findepi** [comment]
in my browser address bar

for example i search for specific docs, but land eg on https://trino.io/docs/current/functions/list.html instead
then i edit address to go up. hierarchical semantic addresses are cool after all.
if i happen to get https://trino.io/docs/current/ , i am fine. if i end up with https://trino.io/docs/current , i get an unwanted redirect

**Comment by mosabua** [comment]
ok ... so its purely that usage. Thats good to know. I will look into adding redirect or fix.

**Comment by mosabua** [comment]
ok.. netlify redirect did NOT work in production although it seemed to work locally. My next idea is a file in the repo.

**Comment by mosabua** [comment]
The second approach worked @findepi .. should be good for you now as well.
