### ISSUE TITLE
Trino gets protobuf or avro data from redis

### ISSUE THREAD

**Issue by sssssssansan** [trinodb/trino#17914]
### Discussed in https://github.com/trinodb/trino/discussions/17913

<div type='discussions-op-text'>

<sup>Originally posted by **sssssssansan** June 15, 2023</sup>
I use python to establish a connection with redis and write the serialized avro data to redis, and set the configuration file and dataschema path according to the format in the official document, but the error dataschema is null is always reported when querying.

![image](https://github.com/trinodb/trino/assets/65671005/47ba27c8-d53d-4a9e-b288-c79fffe170d0)

I checked the source code and found that currently redis seems to support the parsing of avro data according to the specified format, but there is no variable defined to receive dataschema parameters at the corresponding interface, and the corresponding method and interface are defined in the Kafka object file. Does this mean that trino does not yet support getting avro data from redis and automatically parsing it?
The figure below is the corresponding redis configuration setting source code and kafka setting source code
![image](https://github.com/trinodb/trino/assets/65671005/afe3bd40-63e3-463a-bc5f-6819e739f346)
![image](https://github.com/trinodb/trino/assets/65671005/5061d97b-4e93-4694-bdd2-0d1e22b9625c)
</div>

**Comment by hashhar** [comment]
Duplicates https://github.com/trinodb/trino/discussions/17913
