### ISSUE TITLE
Paste non-ASCII character into trino-cli causes Mojibake (garbled text) 

### ISSUE THREAD

**Issue by oneonestar** [trinodb/trino#17915]
Pasting a relatively long string with non-ASCII character into trino-cli causes part of the string becomes Mojibake (garbled text).

`jline` reads 64 bytes at a time. It will then decode that 64 bytes using `CharsetDecoder`.
When pasting a line contains more that 64bytes, it will repeat the above action until the end.

For non-ASCII character using UTF-8, a code point could take 1-4 bytes. For example, one Japanese character usually takes 3 bytes. If we paste 22 Japanese characters into trino-cli, that string is 22*3byte = 66 bytes. The last character will be broken.

```
First 64 bytes read: 21 Japanese characters + 1st byte of the last character
=> the 1st byte then being dropped silently

Second 64 bytes read: 2nd & 3rd byte of the last character
=> failed to decode and becomes Mojibake
```

How to reproduce:
Paste `一二三四五六七八九〇一二三四五六七八九〇一二三` into trino-cli (without using the slow pasting feature provided by terminal).
![image](https://github.com/trinodb/trino/assets/2330687/398f6c4a-a48b-47c9-9b2d-5f813f4bd53d)

Environment:
* trino-cli-388 & trino-cli-419
* jline 3.21.0
* MacOS Monterey 12.6.1
* iTerm2 Build 3.4.19

Looks like https://github.com/jline/jline3/pull/782 fixed this issue unintentional(?).
Update `jline` to `3.22.0` fixed this issue on my machine.

**Comment by ebyhr** [comment]
Can you report the above issue to https://github.com/jline/jline3 just in case? Otherwise, they may cause regression in the future.

**Comment by oneonestar** [comment]
Reported.
