### ISSUE TITLE
Support multiple password authentication plugins 

### ISSUE THREAD

**Issue by oneonestar** [trinodb/trino#1791]
Presto supports multiple authentication types since 0.189 by specify multiple values for `http-server.authentication.type`, separated with commas. This includes `CERTIFICATE, KERBEROS, PASSWORD, JWT`.

However, currently only one single PASSWORD plugin can be enabled at a time, because only one `password-authenticator.properties` file can exist.

**Comment by electrum** [comment]
This seems reasonable, but can you explain more about the specific use case? We currently ship with just LDAP, and will soon have a file one. But I’m not sure that combing those makes sense, and if you have a custom one, it can do whatever you need.

**Comment by oneonestar** [comment]
We have a custom password plugin for long time and most of our client libs are using it. Recently, we want to add a third party BI tool that only support LDAP. We want to enable both custom password plugin and LDAP plugin.

Of course we can import `presto-password-authenticators` into our custom plugin, but the configurations of both plugins will mix together. A switch of turning on/off LDAP also has to be added into the custom plugin. This feels quite ugly.

**Comment by electrum** [comment]
We can allow multiple password authenticators similar to the recently added support for multiple event listeners by adding a `password-authenticator.config-files` property to list the config files. If not specified, it defaults to the existing `etc/password-authenticator.properties`

**Comment by anmtan** [comment]
@electrum Thanks for the update. Do I set `password-authenticator.config-files=file1,file2` in config.properties? I have tried that but failed with  `Configuration property 'password-authenticator.config-files' was not used`. I guess the version that I am using does not have this feature. Which version has this feature?

**Comment by electrum** [comment]
@anmtan This is an issue explaining a feature to be implemented — it’s not available yet.

**Comment by Donderia** [comment]
Hi @electrum 

Do we have this functionality available in Presto 340. My requirement is to use File-based & LDAP authentication both . 

For external users we want LDAP and for internal connections we want File Based Authentication.
