### ISSUE TITLE
Disallow tables with `s3://bucket` location (without trailing slash after bucket name)

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#17921]
This was missed in test coverage in https://github.com/trinodb/trino/pull/17848

We should also define whether we accept locations like s3://bucket.

HMS rejects this (so it's hard to test in the above PR's test setup), but Trino does not. 
So one can use such a location with Glue, for example. Athena won’t read from such table, but we may.

If we want to support these, we need to have test coverage for that. Marking `release-blocker` since it should be part of https://github.com/trinodb/trino/pull/17848 which was a release-blocker itself.

If we do not want to support these, we need to reject them on Trino side, otherwise such locations may be used in real world, and then we cannot take this back.

For context: I believe such locations weren't supported before #15921, but haven't checked.

**Comment by findepi** [comment]
This needs to be tested without HMS.
Maybe we have similar to ones in https://github.com/trinodb/trino/commit/854c15ffe62c6c413504168bd3c3aac09a733b6c#diff-c6ac76ce5a102f34fe5cdca7794cff7404bf8ed13740ae7232c25ad6205a1245
but with Glue and real S3.

cc @findinpath @alexjo2144 @ebyhr

**Comment by findepi** [comment]
I am taking a stab at this.

**Comment by martint** [comment]
Removing the release-blocker task, since this is just about adding a test. As long as the underlying bug is fixed, we will go ahead and release.

**Comment by findepi** [comment]
@martint there is a misunderstanding. The release-blocker tag is for this decision:

> If we want to support these, we need to have test coverage for that. Marking release-blocker since it should be part of https://github.com/trinodb/trino/pull/17848 which was a release-blocker itself.
> 
> If we do not want to support these, we need to reject them on Trino side, otherwise such locations may be used in real world, and then we cannot take this back.

sorry for not making this clear earlier.

**Comment by findepi** [comment]
We need to make this decision ASAP, otherwise we can paint ourselves into a corner and have to support `s3://bucket` locations even if we decide we do not want them.

as shown in https://github.com/trinodb/trino/pull/17923 they are currently accepted and can be used to write data (but read currently fails).

cc @electrum @findinpath @alexjo2144 @losipiuk on how to best block locations like `s3://bucket`  that are not interoperable and are partially working today.

**Comment by findepi** [comment]
i've renamed this ticket to reflect the intent. Once more apologies for making this blurred initially.

**Comment by findepi** [comment]
I checked on Trino ~417 that we were allowing locations like `s3://bucket`, INSERT worked, SELECT did not.

I did not check earlier versions yet. However, that version may not be widely deployed yet since it had issues like https://github.com/trinodb/trino/issues/17803 (with different failure mode), let me keep the `release-blocker` tag. I hope we can get this clarified soon.

**Comment by hashhar** [comment]
> i've renamed this ticket to reflect the intent. Once more apologies for making this blurred initially.

It'll help to rename the PR title as well since it's unclear without actually testing the branch locally.
