### ISSUE TITLE
How identify a newly added catalog with out restarting trino- any updates please

### ISSUE THREAD

**Issue by bhaskarani** [trinodb/trino#17932]
As of now Presto doesn't support adding a catalog on runtime, every time a new catalog is added we have to restart Presto to detect that catalog, this pull request solves the problem by exposing rest endpoints which will allow the user to add a catalog without even restarting Presto server. Ideas are very much appreciated.. Do we have any updates on that.

**Comment by ebyhr** [comment]
Please take a look at #12709
