### ISSUE TITLE
JDBC(Star durst) connectivity issue Using Splunk DB Connect

### ISSUE THREAD

**Issue by rsathish4433** [trinodb/trino#17960]
### Discussed in https://github.com/trinodb/trino/discussions/17959

<div type='discussions-op-text'>

<sup>Originally posted by **rsathish4433** June 19, 2023</sup>
Hello Team,

I am trying to connect statdurst  using JDBC Driver in Splunk DB connect app and getting error 
It looks like am missing to set time zone parament in the connection sting . Could you please help me to find correct parameter to sent the time zone .

Error:
Error executing query: The datetime zone id 'GMT+10:00' is not recognised

Trino JDBC driver version .417

JDBC URL:
jdbc:trino://<<hostname>>:443?SSL=True&SSLVerification=NONE

please let me know if you need any more details.
</div>

**Comment by ebyhr** [comment]
Please avoid cross posting in GitHub issue and discussion. Also, we don't manage Starburst issues in this repository. Please ask to support team or post a question in `#vendor-starburst` Slack channel.
