### ISSUE TITLE
Don't project `_id` field in Mongo DB connector when it's not required

### ISSUE THREAD

**Issue by krvikash** [trinodb/trino#17970]
Currently, `_id` field is retrieved even when it's not necessary. We can exclude by https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/builders/projections/#exclusion-of-_id.

Reference to https://github.com/trinodb/trino/pull/17710#discussion_r1223714314

**Comment by Praveen2112** [comment]
We can also use `projection(fields(include(fieldName))` - `projection`,  `fields` `include` and `exclude` to handle them.

**Comment by sahoss** [comment]
@krvikash @Praveen2112 i'd like to take up this issue as its marked a good first issue.

**Comment by krvikash** [comment]
Thanks @sahoss for your interest to work on this. I have assigned this issue to you.

**Comment by sahoss** [comment]
@krvikash so from my understanding so far:

we need to make a change in mongdb/MongoSession#execute()
The change itself would be to check if  `Document output/List<MongoColumnHandle> columns` contains _id. if it does, we dont exclude it. if it does not contain _id, then we follow the guidlines in the linked mongodb documention to exclude _id from projection.

I tried a few queries such as 

`select _id from orders`,  ` select * from customer inner join orders on customer._id = orders._id` etc. to check if `_id` is populated by the caller in the argument to execute(`List<MongoColumnHandle> columns`) and it seems to be so. So for this issue, the outlined approach should work. 

Also any way to test/assert what parameters were actually sent down to mongo? (without mocking, and mocking seems to discouraged in Development.md)



Can you please let me know your thoughts?

**Comment by krvikash** [comment]
Hi @sahoss, The approach looks fine. However, For testing, I am not really sure. But, we have to verify that `MongoSession#execute` should return the `MongoCursor` which does not have `_id` if not queried explicitly.
