### ISSUE TITLE
Support view when using Iceberg+REST+catalog

### ISSUE THREAD

**Issue by cntwelve** [trinodb/trino#18056]
Need supporting view when using Iceberg+REST+catalog. 
I found "REST catalog does not support [views](https://trino.io/docs/current/sql/create-view.html) or [materialized views](https://trino.io/docs/current/sql/create-materialized-view.html)." in the doc of iceberg connecter. But it's really handy and efficient。

Thanks a lot.

**Comment by ebyhr** [comment]
Closing as duplicate of #14120
