### ISSUE TITLE
Allow named parameter in Prepare statement.

### ISSUE THREAD

**Issue by quazi-irfan** [trinodb/trino#18084]
### Current Status
Given a [Prepare statement](https://trino.io/docs/current/sql/prepare.html),
```PREPARE my_select2 FROM SELECT name FROM nation WHERE regionkey = ? and nationkey < ?;```
and a follow-up call to [Execute](https://trino.io/docs/current/sql/execute.html),
```EXECUTE my_select2 USING 1, 3;``` 
will generate and execute the following SQL.
```SELECT name FROM nation WHERE regionkey = 1 AND nationkey < 3;```

### Limitation
Execute will consume passed arguments and replace `?` sequentially as they appear on the body of prepare statement. There is no way to refer to a passed argument by name.

### Possible Solution
Introducing some notion of named parameters to Prepare statements make it more widely usable. Here is a dummy syntax, where each parameter can be referred to by `?#`, where `#` is the numeric position of the argument, in the prepare statement.

```
PREPARE my_select2 FROM SELECT name FROM nation WHERE regionkey = ?1 and nationkey < ?1 and GDP > ?2
EXECUTE my_select2 USING 1, 3;

-- Generated statement
SELECT name FROM nation WHERE regionkey = 1 AND nationkey < 1 AND GDP > 3
```
Within prepare statement, the first argument can be referred using `?1` and the second argument can be referred using `?2`.

**Comment by hashhar** [comment]
The functionality and features of `PreparedStatements` is enforced by the JDBC API. The JDBC API doesn't allow the extensions you are proposing.

If you want named parameters have a look at JDBC wrappers like https://jdbi.org/, https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/JdbcTemplate.html or https://www.jooq.org/doc/latest/manual/sql-building/bind-values/named-parameters/ or maybe more.

**Comment by hungarianguy** [comment]
I really wish this feature would exist as well.  in microsoft SQL I'm able to create a parameter on a stored procedure then pass than use that parameter multiple times.....

**Comment by hashhar** [comment]
Stored procedures are a completely different thing. You can do the same with SQL routines in Trino. See for example https://trino.io/docs/current/routines/examples.html#date-string-parsing-example and other examples on that page.
