### ISSUE TITLE
Trino dependency vulnerability - org.webjars:swagger-ui:3.23.11:jar

### ISSUE THREAD

**Issue by krishnasdfw** [trinodb/trino#18090]
Since Trino downloads are staged in Maven repository, vulnerability scans prevent downloads from repositories.  The below vulnerability is being reported on swagger jar from org.webjars

          Link:   https://snyk.io/vuln/SNYK-JAVA-ORGWEBJARS-2314887

**Comment by hashhar** [comment]
`swagger-ui` is no longer present in the dependency tree which according to the advisory makes us unaffected (as of today).
