### ISSUE TITLE
Can we get the statistical information of total splits processed of a query from the class 'QueryInfo'

### ISSUE THREAD

**Issue by wangyeweikuer** [trinodb/trino#1819]
Hi:
   We have run lots of queries on Presto, and in our scenario, we realized that reading numerous splits from HDFS or OSS(provided by Alibaba Cloud) was the most important part of performance, so we would like to trace and record the number of splits of the queries for following optimization.
  But so far, I haven't found any available methods to fetch the number of splits in the class of 'QueryInfo', a running context object of query. So guys, what do you suggest me to get such information?

**Comment by raunaqmorarka** [comment]
One way is to query `system.runtime.tasks`. It contains information about queued, running, completed and total splits for each query.

**Comment by wangyeweikuer** [comment]
@raunaqmorarka Which interface can I use to do so?

**Comment by raunaqmorarka** [comment]
> @raunaqmorarka Which interface can I use to do so?

You can run a query on Presto using any client. E.g.: `select * from system.runtime.tasks`

Another option is to implement EventListener interface in your plugin, the `splitCompleted` method receives a `SplitCompletedEvent` on completion of every split. You could export this info into some other system and make use of it from there.

**Comment by wangyeweikuer** [comment]
> > @raunaqmorarka Which interface can I use to do so?
> 
> You can run a query on Presto using any client. E.g.: `select * from system.runtime.tasks`
> 
> Another option is to implement EventListener interface in your plugin, the `splitCompleted` method receives a `SplitCompletedEvent` on completion of every split. You could export this info into some other system and make use of it from there.

Let me have a look, Thank you~
