### ISSUE TITLE
Flaky Iceberg tests

### ISSUE THREAD

**Issue by martint** [trinodb/trino#18217]
Many PRs have been failing recently with OOM errors:

https://github.com/trinodb/trino/actions/runs/5504489833/jobs/10031240378#step:6:19071
https://github.com/trinodb/trino/actions/runs/5504159612/jobs/10043814028#step:6:15224
https://github.com/trinodb/trino/actions/runs/5507534408/jobs/10039286823#step:6:16980
https://github.com/trinodb/trino/actions/runs/5506981220/jobs/10038176272#step:6:16133

**Comment by raunaqmorarka** [comment]
All 4 show major GC happening after
```
2023-07-10T09:18:45.525-0600	INFO	Query-20230710_151845_00111_5tfsb-4601	org.apache.iceberg.SnapshotScan	Scanning table tpch."test_sorted_lineitem_table14wrlm0jrd" snapshot 1862858806616989099 created at 2023-07-10T15:18:45.474+00:00 with filter true
```
testFileSortingWithLargerTable creates a parquet file with 60175 single row parquet row-groups to verify file sorting, this is slow (as expected). Most likely the recent change to make parquet the default file format in iceberg exposed this in tests more than it was previously.

Trying https://github.com/trinodb/trino/pull/18225 to see if it's more stable

**Comment by ebyhr** [comment]
OOM still happens on #18212
https://github.com/trinodb/trino/actions/runs/5514513655/jobs/10054570994?pr=18212

**Comment by ebyhr** [comment]
Closing as there was no OOM past few days. Please feel free to reopen if it still happens.
