### ISSUE TITLE
Incorrect type mapping for boolean in Clickhouse connector

### ISSUE THREAD

**Issue by hsnprsd** [trinodb/trino#18228]
I expect the following to work on Trino but it does not.
```
CREATE TABLE clickhouse.users.gender (user_id INT NOT NULL, is_male BOOLEAN NOT NULL) WITH (ENGINE = 'MergeTree', ORDER_BY = ARRAY['id']);
INSERT INTO clickhouse.users.gender (id, is_male) VALUES (1, true);
```
The error I get is:
```
Insert query has mismatched column types: Table: [integer, smallint], Query: [integer, boolean]
```

**Comment by hsnprsd** [comment]
I think the problem is that when reading from a table (see [here](https://github.com/trinodb/trino/blob/master/plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java#L522)) we are returning SMALLINT for UInt8 type in Clickhouse but when writing we are using UInt8 (see [here](https://github.com/trinodb/trino/blob/master/plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java#L643)).

**Comment by ebyhr** [comment]
That's not a bug. That's the expected behavior of ClickHouse connector and https://trino.io/docs/current/connector/clickhouse.html#trino-type-to-clickhouse-type-mapping already mentions the type mapping.
