### ISSUE TITLE
Coordinator Old Generation takes 99% of heap, major gc frequently, but free tiny, eventually OOM

### ISSUE THREAD

**Issue by akenO8** [trinodb/trino#18242]
version: 417

Here is a graph of coordinator heap size in the middle:
![image](https://github.com/trinodb/trino/assets/37773807/8b5f3092-1b44-4f84-b06c-216a4fc0bc15)
Later, the capacity of G1 Old Generation will account for 90%+ of the entire heap, and then the used capacity of G1 Old Generation will reach 99%+. At this moment, the coordinator will perform major GC frequently, but the space released each time is very small, and the process will eventually oom.

Here is a heap memory usage graph for the coordinator from start to oom, from the trino jmx metric:
![image](https://github.com/trinodb/trino/assets/37773807/d4f7c530-3666-4dd5-b8ce-d5d42e808ede)

coordinator oom then generated the hprof file, which I analyzed using the java analysis tool and showed that these two accounted for the vast majority:
![image](https://github.com/trinodb/trino/assets/37773807/931d6c09-da12-4933-9450-8fc1958d764c)

May I ask how this is caused and how to solve it? I would appreciate your advice.

**Comment by Dith3r** [comment]
Do you see anything suspicious in log (for example: "Query exceeded maximum time limit of .*")?
You could try to reduce `query.min-expire-age` to something like 1-3 minutes instead of 15. Also, you could check if old queries (older than `minExpireAge`) has `endTime` set properly.

**Comment by akenO8** [comment]
> Do you see anything suspicious in log (for example: "Query exceeded maximum time limit of .*")? You could try to reduce `query.min-expire-age` to something like 1-3 minutes instead of 15. Also, you could check if old queries (older than `minExpireAge`) has `endTime` set properly.

I do not see this log in coordinator and worker logs(for example: "Query exceeded maximum time limit of .*")

I set `query.min-expire-age` to `7d` earlier, Yesterday, I also suspected that this was the cause, so I adjusted to `1d`, and I will observe again in a few days.
Is that the cause?

**Comment by Dith3r** [comment]
Default is `15m` and it is set to such value as this significantly increase memory usage for coordinator, which cannot be reclaimed if is not expired. I would recommend stick to default and if requirement is to have such long history of queries, move it to other storage.

**Comment by hashhar** [comment]
Please reopen if you can still observe this with the default values.

**Comment by akenO8** [comment]
I has reduce `query.min-expire-age` to 60m, but some times, I want to find some bad queries that has consumed a lot of resources  and dragged down the cluster in past time(60m ago), I need the Web UI [Resource Utilization Summary] metrics, Is there a good solution to this situation?
@Dith3r @hashhar

**Comment by hashhar** [comment]
Take a look at event listener SPI. You can implement a listener which writes the data into a database. https://trino.io/docs/current/develop/event-listener.html
