### ISSUE TITLE
Poor performance for tpch concurrent queries with tables in memory 

### ISSUE THREAD

**Issue by geooo109** [trinodb/trino#18259]
Assume that we have the tpch schema with sf = 30. I have 1 coordinator (server) and 2 workers (server) with 252 gb memory and 16 cores each.
I copy all the tables of the tpch to the main memory, thus the queries use the memory connector.
I run 2 queries concurrently (the queries are the same):
"select avg(p.retailprice) as retail from memory.sf30.lineitem as l, memory.sf30.partsupp as ps, memory.sf30.part as p, memory.sf30.orders as o where l.partkey = ps.partkey and ps.partkey = p.partkey and o.orderkey = l.orderkey;", and  the total execution time for these queries is 30s, but when I run only 1 query alone the total execution time is 13s.
The x2 slower time isn't something that i would expect. I did experiments for max_drivers_per_task = {1,2,4,8,16}, but I get the same execution times.
my configuration is (coordinator, same for the workers with cooridnator = false):
```
coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8080
discovery.uri=http://coordinator:8080/
query.max-memory=200GB
query.max-memory-per-node=100GB
query.max-total-memory-per-node=100GB
query.execution-policy=phased
node-scheduler.max-splits-per-node=400
node-scheduler.max-pending-splits-per-task=40
task.concurrency=16
```
Is there any intuition why this is happening ? am I missing something ? My intuition is that there is a problem with the schedulig of stages/tasks.
**I'm using trino 360 version** (which uses the legacy phased scheduler) and as I have seen from here https://github.com/trinodb/trino/pull/10350 a new stage execution scheduler was created (in a version higher than 360), but as I can understand leaf stages (for example scans) will be scheduled and run at the same time and this may hurt the performance of the system while you run concurrent queries. A "real" sequential stage scheduler, that takes each stage and runs it sequentially (in each stage there would be threads that run the pipelines in parallel, based on the created drivers and the max_drivers_per_task variable) would be more beneficial ?
Moreover, **I tried the same with the trino 421** and i have the same problem

**Comment by raunaqmorarka** [comment]
Are you maxing out CPU usage with single query ? If yes, it's not surprising that running 2 queries concurrently is 2X slower as performance on memory connector is mostly CPU bound.
Also answered at https://trinodb.slack.com/archives/CP1MUNEUX/p1691730222426619?thread_ts=1691721628.315929&cid=CP1MUNEUX
