### ISSUE TITLE
No schema for file system location error in Hudi connector

### ISSUE THREAD

**Issue by cx707662950** [trinodb/trino#18313]
when I use trino-421 to select some data from a hudi table that has already finished clustering, there is a error , "No schema for file system location: xxxxx", I think this may be a bug, related code is in file HudiActiveTimeline.java in method getInstantFileNamePath on line 88, "metaClient.getMetaPath().path()" ,this line cause "hdfs://a.x" to "a.x"

**Comment by ksoullpwk** [comment]
Actually, it is the same issue from #18188.
The error message is
```java.lang.IllegalArgumentException: No scheme for file system location: xxxxx```

I guess Hudi has some processes to prune metadata files and it makes some files in HudiActiveTimeline lost.

**Comment by ksoullpwk** [comment]
I have replaced `.path()` to `.toString()` and it works correctly, but I'm not sure if it will have the other effects.

It seems like the scheme (like `gs://`, `s3a://`) is lost when we call `.path()` and `Location.of` have some assert logic to check if the scheme exists.

**Comment by atezs82** [comment]
Yes, it is. We do not see the issue anymore after upgrading to release 427.

**Comment by hashhar** [comment]
Thanks for confirming. Closing this then.
