### ISSUE TITLE
Reduce S3 GetObject API Calls in Trino Compared to Presto

### ISSUE THREAD

**Issue by muroon** [trinodb/trino#18334]
In Athena ver3 (using Trino), when running SQL against tables with the following parquet format, the number of GetObject API calls to S3 is four times greater compared to ver2 (using Presto). It has been confirmed that the cause of the increase is the use of Trino.

When running SQL against a table in the parquet format, the result is the same regardless of the version used. However, while there was only one access to a certain object on S3 in ver2, there are four accesses in ver3.

Upon building Trino and Presto in a local environment and verifying, the increase in accesses with Trino was similarly confirmed. Therefore, it is considered not to be an issue with Athena specifically.

We strongly desire for the number of S3 accesses to be the same as when using Presto.

Example:

```
# table

CREATE EXTERNAL TABLE `sample_table`(
  `time` bigint COMMENT '', 
  `application_id` bigint COMMENT '', 
  `uuid` string COMMENT '', 
  `raw_url` string COMMENT '', 
  `device` bigint COMMENT '', 
  `sess_id` string COMMENT '', 
  `ver` string COMMENT '', 
  `ua` string COMMENT '', 
  `lang` string COMMENT '', 
  `remote_ip_address` string COMMENT ‘’,
  `table_name` string COMMENT '')
PARTITIONED BY ( 
  `dt` string COMMENT '', 
  `hour` string COMMENT '')
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://sample-bucket/parquet/v1/sample’
TBLPROPERTIES (
  'parquet.compression'='GZIP', 
  'projection.dt.format'='yyyyMMdd', 
  'projection.dt.range'='NOW-3YEARS,NOW', 
  'projection.dt.type'='date', 
  'projection.enabled'='true', 
  'projection.hour.digits'='2', 
  'projection.hour.range'='0,23', 
  'projection.hour.type'='integer')

# sql

SELECT *
FROM sample_table
WHERE dt = '20230601'
```

**Comment by raunaqmorarka** [comment]
Could you share the files from the partition `dt = '20230601'` ?
Does tuning `parquet.max-buffer-size` higher make a difference ?

**Comment by ebyhr** [comment]
> Upon building Trino and Presto in a local environment and verifying, the increase in accesses with Trino was similarly confirmed.

Please share the entire steps to reproduce. We can't reproduce only with CREATE TABLE and SELECT statement.

**Comment by ebyhr** [comment]
@muroon Could you confirm the above questions?

**Comment by muroon** [comment]
Thank you for your confirmation.
Also, I apologize for the delay in my response.

The data I'm verifying is used in business, and hence, it is not in a state where it can be immediately shared. Once I've formatted and validated it to the point where it can be made public, I will contact you again. Please bear with us in the meantime.

**Comment by ebyhr** [comment]
@muroon Even just sharing summaries (file count & size) under the partition is helpful.

**Comment by raunaqmorarka** [comment]
@muroon were you able to verify whether tuning `parquet.max-buffer-size` makes a difference ?
Do you happen to have parquet file footers caching enabled in prestodb (`parquet.metadata-cache-enabled`) ?
Output of `parquet meta` and `parquet pages` for a typical file would also help.

**Comment by muroon** [comment]
@ebyhr 
> Even just sharing summaries (file count & size) under the partition is helpful.

There are 30 files per partition and each file is less than 40MB in size.

**Comment by muroon** [comment]
Thank you for your earnest advice and prompt action. I've been in touch with the AWS Athena developers, and they should be reaching out to this repository. In light of these developments, I will now be closing this issue.

**Comment by ebyhr** [comment]
You can ask questions in community Slack https://trino.io/slack.html from next time so we can talk interactively.

**Comment by ebyhr** [comment]
@muroon #19127 reduced redundant S3 requests when reading files below `parquet.small-file-threshold` config property or `parquet_small_file_threshold` session property. Can you confirm if these properties help you in your environment?

**Comment by muroon** [comment]
@ebyhr Thank you for your kind message. I am using Trino through Athena, and I will inform AWS support about this merge. I believe they can address the issue more promptly and effectively as they look into it.

**Comment by findepi** [comment]
Athena != Trino. It would be awesome if you could verify behavior in Trino, @kobethuwis .
Otherwise only @pettyjamesm can really know whether the problem is Athena specific.
