### ISSUE TITLE
Support for TABLE keyword in queries

### ISSUE THREAD

**Issue by purcell** [trinodb/trino#18361]
Quick idea for a quality-of-life enhancement: PostgreSQL (at least, this might be ANSI) allows the `TABLE somename` to be used as (roughly) an alternative to `SELECT * FROM somename`. This is specifically useful in CTEs to provide aliases, e.g.

```sql
WITH orders AS (TABLE customers234.orders)
SELECT SUM(amount) FROM orders
```

With Trino, it seems like tables with the same structure are often materialised in different places, such that their structure is the same but their connector- and schema-qualified name is different. Querying those identical tables in different places requires clunky rewriting, but the syntax above would solve this neatly, as well as generally improving query readability.

I understand from #5878 that supporting this syntax and making it exactly equivalent to `SELECT * FROM table` would immediately be terrible for performance in Trino, but perhaps there's a useful path which allows this syntax as an alias for the underlying table that is flattened out by the planner.

Keep up the great work!

**Comment by Praveen2112** [comment]
Can please confirm which version are you using - I tested with a branch derived from 421 and this query was running fine 
```
with temp_orders as (table tpch.tiny.orders) select * from temp_orders;
```

**Comment by Praveen2112** [comment]
I'll be closing this issue as it was already implemented. Feel free to re-open this issue if it fails for specific pattern of query. You can also join our community [here](https://trinodb.slack.com/join/shared_invite/zt-1xhrgebdt-8Pk2CNjtekGWy6eHY3It4w#/shared-invite/email)

**Comment by purcell** [comment]
Argh, humble apologies — I must have messed something up when testing, I can confirm this is indeed working. If I discover there's genuinely a failing case, I'll re-open. Thanks for your time and patience.
