### ISSUE TITLE
Unable to Hide Schema Metadata from User Despite Applying Access Limitations

### ISSUE THREAD

**Issue by GiorgioBaldelli** [trinodb/trino#18370]
Hello everyone,

We are currently working on limiting Catalog, Schema, and Table access for specific users, following the [documentation provided](https://trino.io/docs/current/security/file-system-access-control.html#catalog-schema-and-table-access). 

However, we have encountered an unexpected behavior when trying to restrict schema access for a given user.

****Observed Behavior:****
Setting `owner: false` does not seem to have any impact on schema visibility. The user can still see the schema that we intended to hide.

We have successfully used table rules to hide specific tables from the user within a given schema. However, the schemas themselves remain visible to the user:

The `system.jdbc.schemas`  endpoint lists all schemas, including the ones we are attempting to hide from the user. This is not the expected behavior and poses a security concern. Additionally, the user can still perform a `SHOW SCHEMAS in catalog`  operation to get the full list of schemas.

****Desired Outcome:****
We would like to find a solution or example of how to effectively hide a given schema from a user, along with any relevant metadata that the user should not be able to access.

****Additional Information:****

Trino version: 420
Thread Reference:
We came across this Slack thread (https://trinodb.slack.com/archives/C0305TQ05KL/p1685007241037539), but unfortunately, it does not provide any solutions to our specific problem.

Any assistance or guidance on achieving the desired behavior of hiding a schema and relevant metadata from a user would be greatly appreciated.

Thank you in advance for your support!

**Comment by freeknortier** [comment]
I'm also having this issue.

**Comment by findepi** [comment]
is this the same problem as  https://github.com/trinodb/trino/issues/18565?

**Comment by GiorgioBaldelli** [comment]
> is this the same problem as #18565?

@findepi yeah, that seems the same symptom I'm observing in this issue.

quoting the other issue:

> What we noticed is that regardless of Catalog, Schema, Table configured permissions - "SHOW SCHEMAS IN catalog" always returns all schemas from a database. It's not possible to list tables or do anything else but even a schema name leak to me is a pretty huge security issue.

**Comment by huberty89** [comment]
@GiorgioBaldelli @zach-overflow  Hey, I post PR https://github.com/trinodb/trino/pull/19175 with a possible improvement. Could you tests it if that helps in your case?

**Comment by kokosing** [comment]
I guess it is related to https://github.com/trinodb/trino/pull/13713, @GiorgioBaldelli can you verify if it works as expected for you on Trino 400?
Also, can you please try to specify deny access rules all to functions in your file based access control to see if that helps you?

**Comment by ksobolew** [comment]
When there are no `"schemas": ...` rules in the permissions file, then there is an `ALLOW_ALL` schema-level default rule injected. It makes all schemas in all accessible catalogs visible. A simple workaround is to add a "dummy" section like this:

```json
    "schemas": [],
```

@dain I don't think is expected behavior?

**Comment by GiorgioBaldelli** [comment]
@ksobolew, thank you for the input.

We've attempted to add a dummy schema section but it has no effect. All schemas within the catalog are still visible to all users.

Let's assume the following catalog, schemas, and tables exist:

`iceberg.dummy_user_a.dummy_table_a`
`iceberg.dummy_user_b.dummy_table_b`
`iceberg.dummy_user_c.dummy_table_c`

Let's now login as `dummy_user_a`. When applying the following set of permissions, we're able to hide `dummy_table_b` & `dummy_table_c` from `dummy_user_a`. However, the schemas themselves remain visible when using DBeaver as a client.  I assume that's because the schemas appear in `system.jdbc.schemas` for `dummy_user_a`. 

```
      {
        "system_information": [
            {
              "user": "admin",
              "allow": ["read", "write"]
            }
        ],
        "catalogs": [
          {
            "user": "admin",
            "catalog": "(hive|iceberg)",
            "allow": "all"
          },
          {
            "user": "dummy_user_a",
            "catalog": "iceberg",
            "allow": "read-only"
          }
        ],
        "schemas": [],
        "tables": [
          {
            "user": "admin",
            "privileges": ["SELECT", "INSERT", "DELETE", "OWNERSHIP"]
          },
          {
            "user": "dummy_user_a",
            "catalog": "system",
            "table": ".*",
            "privileges": ["SELECT"]
          },
          {
             "user": "dummy_user_a",
             "catalog": "iceberg",
             "schema": "dummy_user_a",
             "table": ".*",
             "privileges": ["SELECT"]
          }
        ],
        "queries": [
          {
            "user": "admin",
            "allow": ["execute", "kill", "view"]
          },
          {
            "user": "dummy_a",
            "allow": ["execute"]
          }
        ]
      }
```

When executing a `select * from system.jdbc.schemas` logged in as `dummy_user_a`, we get the following results:

```
table,table_catalog
default,iceberg
dummy_a,iceberg
dummy_b,iceberg
dummy_c,iceberg
information_schema,iceberg
information_schema,system
jdbc,system
metadata,system
runtime,system
```

**Comment by GiorgioBaldelli** [comment]
>I guess it is related to https://github.com/trinodb/trino/pull/13713, @GiorgioBaldelli can you verify if it works as expected for you on Trino 400?
Also, can you please try to specify deny access rules all to functions in your file based access control to see if that helps you?

@kokosing, thank you for the suggestion. Denying access to all functions did the trick!

**Comment by d33play** [comment]
> > I guess it is related to #13713, @GiorgioBaldelli can you verify if it works as expected for you on Trino 400?
> > Also, can you please try to specify deny access rules all to functions in your file based access control to see if that helps you?
> 
> @kokosing, thank you for the suggestion. Denying access to all functions did the trick!

Dear @kokosing , can you please share you fully working rules.json file? I'm using 436 and having exactly this issue.

**Comment by analisis1data** [comment]
> > I guess it is related to #13713, @GiorgioBaldelli can you verify if it works as expected for you on Trino 400?
> > Also, can you please try to specify deny access rules all to functions in your file based access control to see if that helps you?
> 
> @kokosing, thank you for the suggestion. Denying access to all functions did the trick!

In Trino 439 version, i have the same issues.

My simple rules don't work as i expect, or on the contrary I do not understand.

I want the user to be able to access a particular schema in the cassandra catalog, but I get that the user can access the whole catalog or none of it.

`
{
        "catalogs": [
                {
                        "user": "josh",
                        "catalog": "cassandra",
                        "allow": "read-only"
                }
        ],
        "schemas": []
}
`
or 
`
{
	"schemas": [
		{
			"user": "josh",
			"schema": "task"
			"owner": true
		}
	]
}
`

**Comment by FleischerT** [comment]
@analisis1data we have the same problem. Did you find a solution?
