### ISSUE TITLE
Iceberg: Inefficient Equality Delete file handling

### ISSUE THREAD

**Issue by jasonf20** [trinodb/trino#18396]
Currently, the Iceberg plugin will:

1. Load equality delete files in each split. If the same delete file is used by many splits it will be re-read many times
2. Store a map of the deleted rows per loaded delete file. This is inefficient if rows are updated often. It should be enough to store a single map with the row and the max data sequence number in which it was deleted.

**Comment by findinpath** [comment]
Does https://github.com/trinodb/trino/pull/17115 relates to this issue ?

**Comment by jasonf20** [comment]
@findinpath It addresses 2. but not 1. from what I can tell. PR #18397 addresses both. I have a more detailed explanation here: https://github.com/trinodb/trino/pull/18397#issuecomment-1666796331

**Comment by ebyhr** [comment]
Closing as https://github.com/trinodb/trino/pull/21441
