### ISSUE TITLE
iceberg cannot migrate table from hive with timestamp(6) column

### ISSUE THREAD

**Issue by akenO8** [trinodb/trino#18399]
version: 422

`show create table hive.tmp.tb;`
``` 
CREATE TABLE hive.tmp.tb ( 
    stime timestamp(6),             
    col1 varchar,                           
    ptime bigint                    
 )                                  
 WITH (                             
    format = 'PARQUET',             
    partitioned_by = ARRAY['ptime'] 
 ) 
```

`CALL ice.system.migrate(schema_name => 'tmp', table_name => 'tb');`
```
Query failed: Timestamp precision (3) not supported for Iceberg. Use "timestamp(6)" instead.
```

The type is already timestamp(6), why does this error occur?

**Comment by ebyhr** [comment]
I already answered in https://trinodb.slack.com/archives/CJ6UC075E/p1684051834296409. Closing as duplicate of #17006. The root cause is the same and it will be handled in #17391
