### ISSUE TITLE
Slack invite link not active

### ISSUE THREAD

**Issue by KiranVelumuri** [trinodb/trino#18433]
The invite link to Trino community chat on Slack shows up as no longer active with the following message:
"To join this workspace, you’ll need to ask the person who originally invited you for a new link."

Page URL: [https://trino.io/slack.html](https://trino.io/slack.html)

Could you please update the invite link?

Thanks
Kiran

**Comment by martint** [comment]
Updated the invite link. Let us know if you have any further issues.
