### ISSUE TITLE
TrinoDB does not support manual commit mode for JDBC connectors

### ISSUE THREAD

**Issue by ranjanp75** [trinodb/trino#18438]
We are trying to do a manual commit of a transaction using the following code for trino communicating with MYSQL DB.

    import trino
    from trino.transaction import IsolationLevel
    from trino.sqlalchemy import URL
    
    config = {
        "host": "********",
        "port":*****,
        "user":"*******",
        "catalog":'*****',
        "schema":'*****'
    }

    
    with trino.dbapi.connect(**config, isolation_level=IsolationLevel.REPEATABLE_READ) as conn:
        cur = conn.cursor()
        query = "INSERT INTO ...."
        rest = cur.execute(query)
        
        conn.commit()

The error seen is `trino.exceptions.TrinoUserError: TrinoUserError(type=USER_ERROR, name=AUTOCOMMIT_WRITE_CONFLICT, message="Catalog only supports writes using autocommit: ******", query_id=******)`

Also, it looks like from the JDBC connector code that the following method is not implemented as specified by the Connector interface.
` default boolean isSingleStatementWritesOnly()
    {
        return true;
    }`

Is there a way to disable this for the JDBC connector?

**Comment by hashhar** [comment]
JDBC connectors don't support using Trino transactions yet. Mostly because transactions today in Trino (at least in hive connector) are modeled as `{ action, compensation-action }` pairs. This  means that there is no transactional isolation provided within Trino. i.e. you cannot operate on results of an `INSERT` using a `SELECT` within same transaction.

**Comment by hashhar** [comment]
Also the general direction we have regarding transactions is to remove them instead of implementing them poorly leading to possible correctness and corruption issues.
