### ISSUE TITLE
cors related issues when using rest api 

### ISSUE THREAD

**Issue by yosiasz** [trinodb/trino#18442]
Greetings,

I have been able to fetch data leveraging trino rest api, using pure javascript. it works from vscode but when I plug in this same code in grafana, I am getting cors related issues. I am not sure if this is on the trino rest api side or grafana. but the error seems to indicate it is from the trino side.

Access to fetch at 'http://localhost:8080/v1/statement' from origin 'http://localhost:3951/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

```
    headers: {
      'accept': 'application/json',
      'X-Trino-User': 'root',
      'X-Trino-Catalog': 'tpch',
      'X-Trino-Schema': 'sf1',
      'accept': 'application/json',       
      //'Authorization': 'Basic root',
      //'Access-Control-Allow-Origin': 'http://localhost:3951',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'DELETE, POST, GET, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Requested-With'
    }
```

Is there anything custom I need to do with the headers? 
I have tried many different ways without success, 
Maybe there is a difference of headers data between GET POST OPTIONS?

Thanks

**Comment by yosiasz** [comment]
> Try adding **PUT** to the methods.
> 
> ```
> 'Access-Control-Allow-Methods': 'DELETE, POST, GET, PUT, OPTIONS'
> ```

nope does not make a difference

**Comment by sciencenawaaz** [comment]
make sure to uncomment

```
'Authorization': 'Basic root',
```

**Comment by yosiasz** [comment]
did that still a no go

**Comment by sciencenawaaz** [comment]
> did that still a no go

Why are you writing root , problem most probably is in it cause everything else looks good to my knowledge it requires a **base64 encoding** the username and password should be in the format ``username:password``, maybe try passing it directly instead of the root,

it will look something like this :
```
'Authorization': 'Basic cm9vdDo='
```

```
'Authorization': 'Basic root',
```

**Comment by yosiasz** [comment]
I doubt it is not an auth issue. cause it works if I call the script directly in vscode

<img width="309" alt="image" src="https://github.com/trinodb/trino/assets/900951/494c8498-0468-4a1b-a0b2-094dae9f64ea">

**Comment by yosiasz** [comment]
maybe it is not a trino rest api issue at all. maybe chrome let me try edge

**Comment by yosiasz** [comment]
same issue in edge. oh well, it was a good attempt moving on. thanks for the effort @sciencenawaaz

**Comment by sciencenawaaz** [comment]
> I doubt it is not an auth issue. cause it works if I call the script directly in vscode
> 
> <img alt="image" width="309" src="https://user-images.githubusercontent.com/900951/256607469-494c8498-0468-4a1b-a0b2-094dae9f64ea.png">

Oh, then i have no idea everything looks alright to my eyes.

**Comment by yosiasz** [comment]
maybe by default the rest api is not configured for cors

**Comment by sciencenawaaz** [comment]
> maybe by default the rest api is not configured for cors

Maybe 🤔.Too advanced issue for me or maybe we are missing something very simple.

**Comment by yosiasz** [comment]
ok, the issue is not trino but the calling app needs to be run behind a proxy server that will handle cors issues
