### ISSUE TITLE
Timeout `test (plugin/trino-redshift, fte-tests)` job

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#18446]
https://github.com/trinodb/trino/actions/runs/5686163288/job/15412510471

**Comment by findinpath** [comment]
The `test (plugin/trino-redshift, fte-tests)` shouldn't be executed.
Given the fact that the location of the github runners is picked at random, they may be farther away from the location of the AWS Redshift cluster, which  increases the latency of the tests.

@grantatspothero  given these constraints, probably these tests should run on Trino OSS.

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/5716561690/job/15493187904?pr=18315

**Comment by ebyhr** [comment]
@grantatspothero @findinpath Can you send the PR?
