### ISSUE TITLE
Insufficient access control checks in system.metadata.table_comments when redirections enabled 

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#18514]
the code https://github.com/trinodb/trino/blob/2cbd05436b134c9fd6a70452c34b08bb83116c51/core/trino-main/src/main/java/io/trino/connector/system/TableCommentSystemTable.java#L134-L157

doesn't consult `AccessControl` for redirected table.
non-redirected tables are passed thru `io.trino.security.AccessControl#filterTables` inside `io.trino.metadata.MetadataListing#listTables`.

**Comment by findepi** [comment]
@lukasz-walkiewicz can you consider picking this up?

**Comment by lukasz-walkiewicz** [comment]
I can take a look.

**Comment by findepi** [comment]
@mosabua  @colebow i can't find it. do the docs say whether access control is consulted before redirection, after, or both?

**Comment by mosabua** [comment]
I dont think we have any security related info about redirection
