### ISSUE TITLE
Memory tracking issue: worker OOM in PrimitiveColumnWriter

### ISSUE THREAD

**Issue by davseitsev** [trinodb/trino#18557]
### Summary

From time to time workers on our cluster die with OOM. Our investigation showed that it's caused by `io.trino.parquet.writer.PrimitiveColumnWriter` which doesn't track all the memory it allocates. When the cluster is loaded, some query with heavy writer can cause OOM. A heavy writer means that it writes partitioned table and some specific values which consume more memory.

### Details

Below is per query statistics of how much a query actually takes memory (retained_size) and how much it allocates in the memory context (memory_context_memory):

```
query_id                   |  retained_size | memory_context_memory | untracked_memory
--------------------------------------------------------------------------------------
20230802_184156_65993_i2g79| 18 821 377 064 |         1 505 057 188 |   17 316 319 876
20230802_184207_66007_i2g79| 17 042 574 352 |         1 328 309 810 |   15 714 264 542
20230802_184207_66008_i2g79| 16 721 447 928 |         1 364 478 595 |   15 356 969 333
20230802_185952_68245_i2g79|  1 728 619 520 |           183 188 804 |    1 545 430 716
20230802_185806_68089_i2g79|    527 467 840 |            45 081 979 |      482 385 861
Total: 5 entries           | 54 841 486 704 |         4 426 116 376 |   50 415 370 328
```

The statistics is buit in [Eclipse Memory Analyzer](https://projects.eclipse.org/projects/tools.mat) with the query:
```
select 
	o.this['operatorContext.driverContext.pipelineContext.taskContext.queryContext.queryId.id'] as query_id, 
	sum(retainedSize(o.this['pageSink'])) retained_size,
	sum(cast(o.this['pageSinkMemoryContext.delegate.usedBytes'] as bigint)) as memory_context_memory,
	sum(retainedSize(o.this['pageSink']) - cast(o.this['pageSinkMemoryContext.delegate.usedBytes'] as bigint)) as untracked_memory
  from "io.trino.operator.TableWriterOperator" o
group by 1
order by 4 desc
```
As we can see  the memory context tracks only 8% of consumed memory and total amount of consumed heap is too big and can easily cause OOM.
We can take and analyze the biggest `io.trino.operator.TableWriterOperator`. Outbound dependency tree shows that memory is consummed by 70 `io.trino.plugin.iceberg.IcebergPageSink$WriteContext` (70 table partitions is written) each of which writes 13 columns.

**Image 1**
![image](https://github.com/trinodb/trino/assets/1793410/c1e13cf3-4356-4255-99e5-1dc304ab6d24)

Actual memory is tracked by `TableWriterOperator`, it eventually calls `PrimitiveColumnWriter#getRetainedBytes` method:
https://github.com/trinodb/trino/blob/0aeb0b77ab50ca963f6d26cac0953df0023f1c0d/lib/trino-parquet/src/main/java/io/trino/parquet/writer/PrimitiveColumnWriter.java#L296-L302

#### Problem 1

As far as I understand, above method considers the size of page writers of currently writing page, but it doesn't consider page buffer size which is the most memory consuming part in our case. Page buffer contains **31885** buffered pages and headers and takes 47Mb when value writers take only 1.25Mb.

**Image 2**

![image](https://github.com/trinodb/trino/assets/1793410/da0e14bc-53f1-4be2-9291-a42b08005500)

There is challange how to take actual page buffer retained size. From the first view we can use `pageBufferedBytes` variable
https://github.com/trinodb/trino/blob/0aeb0b77ab50ca963f6d26cac0953df0023f1c0d/lib/trino-parquet/src/main/java/io/trino/parquet/writer/PrimitiveColumnWriter.java#L230-L231
This variable contains actual size of buffered data. But it doesn't consider the byte buffers overhead created by parquet compressors. The slice from the **Image 2** holds the 4053 bytes array, but its data size is only 3237 bytes:

**Image 3**
![image](https://github.com/trinodb/trino/assets/1793410/568c5ca9-5a2a-4d98-b070-4cf6b70ab8a9)

It's because compressor is always pessimistic when it creates a buffer: [ParquetCompressor.java#L89C4-L90](https://github.com/trinodb/trino/blob/0aeb0b77ab50ca963f6d26cac0953df0023f1c0d/lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetCompressor.java#L89C4-L90)

The table below shows that `pageBuffer` takes 85% of the column writer retained heap but `pageBufferedBytes` represents only 60% of its size.

```
column_type      | retained_size | pageBuffer_retainedSize | pageBufferedBytes
-------------------------------------------------------------------------------
BINARY           |    50 638 328 |              49 292 080 |        36 380 785
INT32            |       807 008 |                   1 008 |                99
BINARY           |        94 544 |                   2 832 |               297
INT64            |       284 008 |                   2 200 |               231
BINARY           |        91 312 |                   2 832 |               297
BINARY           |       156 728 |                   4 648 |               495
BOOLEAN          |       164 608 |                      40 |                 0
BOOLEAN          |       164 608 |                      40 |                 0
BOOLEAN          |       164 608 |                      40 |                 0
BOOLEAN          |       164 608 |                      40 |                 0
INT64            |    16 460 408 |               9 938 704 |         5 521 626
INT32            |     1 118 008 |                 927 952 |           794 724
BOOLEAN          |       164 608 |                      40 |                 0
BOOLEAN          |       164 608 |                      40 |                 0
Total: 14 entries|    70 637 992 |              60 172 496 |        42 698 554
-------------------------------------------------------------------------------
```

The table is built using the query below:

```
select 
	refs.this['columnDescriptor.type.primitive.name'] as column_type,
	retainedSize(refs.this) retained_size,
	retainedSize(refs.this['pageBuffer']) pageBuffer_retainedSize,
	cast(refs.this['pageBufferedBytes'] as bigint) pageBufferedBytes
  from "java.lang.Object[]" o,
	   lateral table(getOutboundReferences(o.this)) refs
 where getAddress(o.this) = 140013266626912 -- 0x7f5761056960
 	and refs.this['@className'] = 'io.trino.parquet.writer.PrimitiveColumnWriter'
```

#### Problem 2

Anothe issue is how current page writers are tracked. To get a writer retained bytes we call `getAllocatedSize` method. For `FallbackValuesWriter` this method returns information only about `currentWriter` [FallbackValuesWriter.java#L128-L131](https://github.com/apache/parquet-mr/blob/db4183109d5b734ec5930d870cdae161e408ddba/parquet-column/src/main/java/org/apache/parquet/column/values/fallback/FallbackValuesWriter.java#L128-L131)
But it doesn't consider the size allocated by `initialWriter`:

**Image 4**
![image](https://github.com/trinodb/trino/assets/1793410/20ba99ef-e5e6-445b-90e7-d541ff0a9b52)

But it could be tricky to get actual size of initialWriter. In this case initialWriter is an instance of `org.apache.parquet.column.values.dictionary.DictionaryValuesWriter$PlainBinaryDictionaryValuesWriter`. Its [getAllocatedSize](https://github.com/apache/parquet-mr/blob/db4183109d5b734ec5930d870cdae161e408ddba/parquet-column/src/main/java/org/apache/parquet/column/values/dictionary/DictionaryValuesWriter.java#L147-L151) method returns `encodedValues.size() * 4 + dictionaryByteSize`. But it's actuall equals to 0 because encodedValues has no elements and dictionaryByteSize=0. All the data is in `binaryDictionaryContent` field.

**Image 5**
![image](https://github.com/trinodb/trino/assets/1793410/aa2d4491-8c1d-4315-9f90-d5bb396a6e08)

### Summary

```
query_id                   | memory_context_memory | sink_retained_size | pageBuffer     | pageBufferedBytes | valueWriters
                           |                       |                    | retained_size  | value             | retained_size
------------------------------------------------------------------------------------------------------------------------------
20230802_184156_65993_i2g79|         1 505 057 188 |     13 735 849 336 |  7 599 093 792 |     5 363 078 478 |   5 597 896 392
20230802_184207_66007_i2g79|         1 328 309 810 |     12 284 152 640 |  6 921 539 056 |     4 884 368 564 |   4 880 075 072
20230802_184207_66008_i2g79|         1 364 478 595 |     12 136 316 232 |  6 675 513 176 |     4 724 202 924 |   4 965 242 376
20230802_185952_68245_i2g79|           183 188 804 |      1 728 585 839 |    688 626 840 |       501 076 240 |     919 483 664
20230802_185806_68089_i2g79|            45 081 979 |        527 434 143 |    302 182 584 |       233 203 759 |     185 233 160
Total: 5 entries           |         4 426 116 376 |     40 412 338 190 | 22 186 955 448 |    15 705 929 965 |  16 547 930 664
------------------------------------------------------------------------------------------------------------------------------


```

Where:
**sink_retained_size**  is total size of `io.trino.plugin.iceberg.IcebergPageSink$WriteContext`
**pageBuffer_retained_size**  is total size of `io.trino.parquet.writer.PrimitiveColumnWriter#pageBuffer`
**pageBufferedBytes_value** is summ of all `io.trino.parquet.writer.PrimitiveColumnWriter#pageBufferedBytes`
**valueWriters_retained_size** is total size of `primitiveValueWriter` + `definitionLevelWriter` + `repetitionLevelWriter` in `io.trino.parquet.writer.PrimitiveColumnWriter`

The table shows that accurate calculation of pageBuffer size (22.1Gb) and value writers (15.5Gb) would cover 96% or retained heap.
Simple calculation by pageBufferedBytes (15.7Gb) and using `getAllocatedSize` of writers (4.4Gb) would cover 50% of actually used heap.

#### Environment
Trino version 409

**Comment by raunaqmorarka** [comment]
@davseitsev thanks a lot for the very detailed analysis here
I believe you should benefit to some extent from the bug fix here https://github.com/trinodb/trino/pull/17373
I recommend upgrading to 420 to get that fix
I also created a PR which addresses the first problem https://github.com/trinodb/trino/pull/18564 
It would be great if you could try out the above fixes and see to what extent that addresses the problem here.
