### ISSUE TITLE
Schema Filtering not Working for MySQL Schemas

### ISSUE THREAD

**Issue by vkhoroshko** [trinodb/trino#18565]
Hello,

We're running the latest Trino version (422) and trying to use File Based Access Control to limit different users access to concrete schemas (on the same physical db).

What we noticed is that regardless of Catalog, Schema, Table configured permissions - "SHOW SCHEMAS IN catalog" always returns all schemas from a database. It's not possible to list tables or do anything else but even a schema name leak to me is a pretty huge security issue. 

For sure it's possible to configure a separate connector per a db user and limit the access on the database level but for simplicity we want to use a single db user with read-only access to all schemas and rely on Trino access control.

Shouldn't there be a way to filter out a schema name that a Trino user doesn't have access to?
Based on the config below - test-user is expected to have an access to test schema only and other schemas shouldn't be listed in "SHOW SCHEMAS in mysql" output. However, they are.

Config:

```
{
	"catalogs": [
		{
			"catalog": "jmx",
			"allow": "none"
		},
		{
			"catalog": "memory",
			"allow": "none"
		},
		{
			"catalog": "system",
			"allow": "none"
		},
		{
			"allow": "read-only"
		}
	],
	"tables": [
		{
			"user": "test-user",
			"catalog": "mysql",
			"schema": "test",
			"privileges": [
				"SELECT"
			]
		},
		{
			"privileges": []
		}
	],
	"queries": [
		{
			"allow": [
				"execute"
			]
		}
	]
}
```

**Comment by findepi** [comment]
per the access spec above here https://github.com/trinodb/trino/blob/db8dccd9cf2bbf9c050e7f88fb8c7780ce6d04c0/lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java#L1039 we should have exactly one `AnyCatalogSchemaPermissionsRule` and it should not match schemas other than `test` (but i haven't verified that).


cc @kokosing @huberty89

**Comment by huberty89** [comment]
@vkhoroshko Hey, I post PR https://github.com/trinodb/trino/pull/19175 with a possible improvement. Could you tests it if that helps in your case?

**Comment by kokosing** [comment]
Closing as duplicate of https://github.com/trinodb/trino/issues/18370
