### ISSUE TITLE
Incorrect results when constant literal distinct aggregation is used in the query

### ISSUE THREAD

**Issue by Bhargavi-Sagi** [trinodb/trino#18562]
Wrong results when distinct aggregation on a constant literal is used in the query 
Repro query
`with test_distinct_agg as (select orderkey, 'asdf' constant_str from orders limit 10) select count(distinct constant_str), count(*) from test_distinct_agg`
Results:
10, 10
But correct result should be 1, 10

**Comment by Praveen2112** [comment]
Can you mention from which version are we facing this issue ?

**Comment by Bhargavi-Sagi** [comment]
We noticed this in 411. But i think the bug exists from 370.

**Comment by findepi** [comment]
fixed by https://github.com/trinodb/trino/pull/18566
