### ISSUE TITLE
Optimize of a Delta Lake table with one small file rewrites the table

### ISSUE THREAD

**Issue by jkylling** [trinodb/trino#18645]
When running `ALTER TALBE EXECUTE OPTIMIZE` on a Delta Lake table with a single file below `file_size_threshold=100MB`, the file will be rewritten on each run. This can be expensive in terms of storage and time consuming.

This can become a big issue if the table has many partitions, each of which is fairly small (arguably, it is an indication that the table is over-partitioned). Then each run of optimize might rewrite the entire table. Over time this consumes a lot of storage, and also causes the checkpoint files to become enormous.

The test in [this PR](https://github.com/trinodb/trino/pull/18644) reproduces the issue.

We have applied [this patch](https://github.com/trinodb/trino/commit/e0270c05e5db6736f1b8c8fb907277f4d65e6f31) to partly mitigate the issue. Unfortunately, this still does not make optimize stable or fully incremental. Possibly, this is caused by optimize triggering on compressed data, while writers are scaled on uncompressed data. I will create a follow up issue for this.

**Comment by raunaqmorarka** [comment]
fyi @losipiuk @alexjo2144
