### ISSUE TITLE
Trino can support ETL in big data warehouse and replace spark?

### ISSUE THREAD

**Issue by zhaojintaozhao** [trinodb/trino#18659]
Trino can support ETL in big data warehouse and replace spark?

Trino should support these features then can replace spark.
Trino should support ETL in big data warehouse and replace spark.
Trino should support multi-stage execution and ETL capabilities at the execution layer, support batch processing and exchange shufle, support complex SQL statements for querying large tables in the data warehouse.
Trino should support support write to ORC files.

**Comment by martint** [comment]
Yes, Trino can do that. Please take a look at https://trino.io/docs/current/admin/fault-tolerant-execution.html
