### ISSUE TITLE
Report bytes written in query results statistics

### ISSUE THREAD

**Issue by jkylling** [trinodb/trino#18651]
It would be useful for clients of the HTTP REST API which are iterating over the `nextUri`s of some write operation to know the approximate number of bytes written so far, in addition to the number of bytes processed or CPU time used. This can for instance be used to cancel queries writing too much data early.

The `physicalWrittenDataSize` is already part of the `infoUri`, but this URL is more expensive.

The `StatementStats` created [here](https://github.com/trinodb/trino/blob/51f10c6b5c2c4d2a3814d7f5fc7efe98e422c109/core/trino-main/src/main/java/io/trino/server/protocol/ProtocolUtil.java#L178) could be extended to include `queryStats.getPhysicalWrittenDataSize().toBytes()`.

**Comment by electrum** [comment]
This seems reasonable. Feel free to submit a PR.
