### ISSUE TITLE
Delta Connector should support the Hive Cache

### ISSUE THREAD

**Issue by whitleykeith** [trinodb/trino#18723]
The Delta Connector should be extended to support the Hive Cache feature currently available https://trino.io/docs/current/connector/hive-caching.html

**Comment by ebyhr** [comment]
I would recommend reading this thread https://github.com/trinodb/trino/pull/12812

**Comment by whitleykeith** [comment]
@ebyhr thanks for the context

I get the aversion to further baking in a dependency to an unmaintained project, but is there an alternative path the community is investigating to support this feature? We've had significant performance gains from using this cache in our Hive Catalogs (~2-3x speed improvements), with very little added maintance overhead.  We don't want to have to manage another service like Alluxio to bring this behavior to other catalogs, so would be interested in seeing if there's a plan to support a feature like this wholistically within Trino. I'd personally be open to help contribute to this work as well

**Comment by raunaqmorarka** [comment]
@whitleykeith one of https://github.com/trinodb/trino/pull/18719 or https://github.com/trinodb/trino/pull/16375 should resolve this by adding support for Alluxio's embedded cache which shouldn't require managing external service
cc: @beinan @Pluies

**Comment by Pluies** [comment]
Closing this as implemented in #18719
