### ISSUE TITLE
In v406 node-scheduler.include-coordinator default value is set as True although documentation states it as False

### ISSUE THREAD

**Issue by atifiu** [trinodb/trino#18749]
I am using version 406 and have 9 node cluster. Since as per the [documentation ](https://trino.io/docs/current/admin/properties-node-scheduler.html) node-scheduler.include-coordinator is false

> Node scheduler properties[#](https://trino.io/docs/current/admin/properties-node-scheduler.html#admin-properties-node-scheduler--page-root)
> node-scheduler.include-coordinator[#](https://trino.io/docs/current/admin/properties-node-scheduler.html#node-scheduler-include-coordinator)
> Type: [boolean](https://trino.io/docs/current/admin/properties.html#prop-type-boolean)
> 
> Default value: false

But my coordinator node always shows up as worker node in the cluster unless I explicitly set the value as false in config.properties file of coordinator node. This seems to be a bug or there is change in the default value after  version 406 which is not documentated.

**Comment by ebyhr** [comment]
We should fix the documentation. The default value is true. Do you want to send a PR? 
https://github.com/trinodb/trino/blob/d0fb41f6db05e44031c45b164150e2fa317c4533/core/trino-main/src/main/java/io/trino/execution/scheduler/NodeSchedulerConfig.java#L47
