### ISSUE TITLE
Optimizer Slowdown/Timeout on Large Delta Tables

### ISSUE THREAD

**Issue by whitleykeith** [trinodb/trino#18775]
When querying large Delta tables, a significant amount of time is spent in the planning phase even when queries are relatively simple. Most of the time the query will eventually get planned and start normally, but can take 2-3x the query execution time to do so. Other times it yields a true failure with the following exception:

```
Query 20230821_214652_05331_9jjde failed: The optimizer exhausted the time limit of 180000 ms: Top rules: {
		io.trino.sql.planner.iterative.rule.ReorderJoins: 301685435631 ms, 3 invocations, 0 applications }
```

An example query can be as simple as the following, where day is a partition column

```sql

select count(distinct col) from delta.hydro.table where day = '2023-08-14';
```

For context these Delta Tables are over a Trillion rows, and my testing has been done while we're doing a one-time migration into these tables. I haven't noticed any issues with load on the coordinator when these queries are planning either. 

I've noticed once the query plans successfully at least once, that subsequent attempts are much faster at planning and executing. Could the migration (and subsequent increase in large Delta transactions) be negatively impacting this phase? These are streaming tables that get populated via Spark jobs ~5min, but the steady state data volume is much lower than what we're currently pumping into the table.

**Comment by ebyhr** [comment]
How many transaction logs do you have? Also, what about the last checkpoint? Can you enable tracing with `tracing.enabled` & `tracing.exporter.endpoint` to find the bottleneck?

**Comment by whitleykeith** [comment]
I haven't enabled tracing but TIL Trino does that! Let me go look into that

The log is on txn 2468 and it being a streaming table means we'll get ~1 txn / 5 mins. We've also been migrating historical data (this is a Hive table we're moving to Delta)

The table is extremely large though, >1PB and we're using extended table stats on it. Even showing the stats for the table can take 8-10 min and disabling it via session props gets us back to being near instant in terms of planning time.

**Comment by whitleykeith** [comment]
@ebyhr I got some traces with the long planning time and I can confirm it looks like the issue is downloading the transaction log (the input.readFully spans repeat all the way down)

![Screenshot 2023-09-01 at 2 18 06 PM](https://github.com/trinodb/trino/assets/21354274/3c69e9fb-2fd9-46e5-8cee-f326ccce6a85)

From the looks of it it seems like it's spawning an awful lot of threads to pull down the checkpoint, is that a thing we can configure or is it based off of how many files are in the log?

**Comment by rijojoseph07** [comment]
@whitleykeith Did you solve this problem? we are also facing similar issues with large datasets getting migrated from hive to delta. 

_Even showing the stats for the table can take 8-10 min and disabling it via session props gets us back to being near instant in terms of planning time._

which session property did you disable it here ?

**Comment by whitleykeith** [comment]
@rijojoseph07 you have to disable both extended stats and regular stats as well with `<catalog>.statistics_enabled`

**Comment by whitleykeith** [comment]
Closing this as we stopped seeing this soon after a background optimize job started compacting our Delta log.

We ran a dedicated Spark Job to do the compaction which took our delta log from ~7GB to 1.1GB, and completely resolved the optimizer timeouts even with table stats
