### ISSUE TITLE
Add large number format function

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#1878]
Create a function to shorten and format numbers (using suffixes like B - billion, M - million, K - thousand, etc).

Examples of functionality:
* `1000000` would become `'1M'`
* `123456` would become `'123K'`

Ref https://github.com/prestodb/presto/issues/4130
https://github.com/prestosql/presto/blob/master/presto-cli/src/main/java/io/prestosql/cli/FormatUtils.java

cc: @yuokada

**Comment by szymon-jedrzejewski** [comment]
Can i take this one?

**Comment by findepi** [comment]
@szymon-jedrzejewski i think this is being covered by @ebyhr 's PR -- https://github.com/prestosql/presto/pull/1905
you can always help by participating in its review

**Comment by amitna1r** [comment]
Hi @ebyhr, looking forward to this function. Any updates on this?
