### ISSUE TITLE
ANALYZE broken since 420 for Hive tables without (full) statistics

### ISSUE THREAD

**Issue by marvin-roesch** [trinodb/trino#18798]
It appears that `ANALYZE` to gather table statistics has been broken since version 420 for certain table states and when using the (Thrift) Hive Metastore. I noticed this as we started getting errors with a `NumberFormatException` in responses from the metastore when the partition is getting updated.

In my search for the root cause, I came across #17677, which appears to be at fault here as it was introduced in version 420 and I was not able to reproduce this on version 419.

The exact cause seems to be as follows: A partition might have some limited "easy" statistics attached, e.g. the number of files and the total file size, but not the number of rows. In this case, the changes introduced in #17677 would override the statistics with completely empty ones. Hive Metastore would fail and throw the exception in the following method:
https://github.com/apache/hive/blob/0ecbd12df518bd9666a26b877d02a26b3e5bcbdc/standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java#L627-L644
To be exact, it would throw when trying to invoke `Long.parseLong(newPart.getParameters().get(stat))` with `stat` being one of `numFiles` or `totalSize`. Looking at the origin of the `newPart` object, it is passed in via a Thrift method and in our case (through introspection of the Thrift traffic using [thrift-tools](https://github.com/pinterest/thrift-tools)), the parameters for this partition would look something like this:
```python
 {
    'transient_lastDdlTime': '1691738112',
    'presto_query_id': '20230811_071512_01009_d25wg',
    'STATS_GENERATED_VIA_STATS_TASK': 'workaround for potential lack of HIVE-12730',
    'numRows': '292'
}
```
Note the lack of `numFiles` or `totalSize` in this map. Hive Metastore assumes any new partition statistics to at least have all parameters that the partition used to have, but this is clearly not the case here.

For reference, the parameters for the partition as they currently are stored in the metastore are as follows:
```python
 {
    'transient_lastDdlTime': '1691846113',
    'presto_query_id': '20230812_131512_01243_d25wg',
    'STATS_GENERATED_VIA_STATS_TASK': 'workaround for potential lack of HIVE-12730',
    'totalSize': '13022',
    'numFiles': '1'
}
```

To elaborate on how something like this can occur: We directly write Parquet files to S3 storage from a Spark job. This then gets picked up by a scheduled invocation of `CALL system.sync_partition_metadata` via Trino. I assume that Hive Metastore writes the `totalSize` and `numFiles` parameters at this time, but doesn't count the total rows or similar. So this issue only occurs for tables and partitions that have not yet been analyzed (by a working version of Trino) and likely those that were created outside of Trino in some fashion.

**Comment by ebyhr** [comment]
cc: @Dith3r @raunaqmorarka

**Comment by Dith3r** [comment]
The issue with fast statistics was fixed in metastore (https://issues.apache.org/jira/browse/HIVE-19254). All testing suites used a patched version.

**Comment by marvin-roesch** [comment]
Ah, we're still on version 3.x of the metastore, while that issue appears to only be fixed as of 4.x. Thanks for providing a Trino-side fix, anyway, @Dith3r!
