### ISSUE TITLE
Update testing docker images from centos 7 to almalinux 9

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#18824]
> The end of life dates for CentOS 7 and 8 are as follows: CentOS 8 - December 31, 2021. CentOS 7 - June 30, 2024.

And

> On December 8, 2020, [Red Hat](https://en.wikipedia.org/wiki/Red_Hat) announced that development of [CentOS](https://en.wikipedia.org/wiki/CentOS), a free-of-cost [downstream](https://en.wikipedia.org/wiki/Downstream_(software_development)) fork of the commercial Red Hat Enterprise Linux (RHEL), would be discontinued and its official support would be cut short to focus on CentOS Stream, a stable LTS release without minor releases officially used by Red Hat to preview what is intended for inclusion in updates to RHEL.[[4]](https://en.wikipedia.org/wiki/AlmaLinux#cite_note-4)[[5]](https://en.wikipedia.org/wiki/AlmaLinux#cite_note-5)[[6]](https://en.wikipedia.org/wiki/AlmaLinux#cite_note-6)

> In response, CloudLinux – which maintains its own commercial Linux distribution, [CloudLinux OS](https://en.wikipedia.org/wiki/CloudLinux_OS) – created AlmaLinux to provide a community-supported spiritual successor to CentOS Linux, aiming for binary-compatibility with the current version of RHEL

Taken from [wikipedia](https://en.wikipedia.org/wiki/AlmaLinux)

We should update our testing images.

**Comment by Rahulreddy1020** [comment]
@kokosing can i pick up this issue ?

**Comment by kokosing** [comment]
@Rahulreddy1020 You are welcome!

**Comment by kokosing** [comment]
Please annotate me as a review in all your PRs.

**Comment by kokosing** [comment]
@wendigo it looks like the deadline is crossed, I guess now CI will be red.
