### ISSUE TITLE
predicate doesn't take effect after renaming Iceberg table's column

### ISSUE THREAD

**Issue by iBuddha** [trinodb/trino#18855]
After rename an Iceberg table column,  in `IcebergPageSourceProvider.getParquetTupleDomain` the generated TupleDomain doesn't take count of the renaming.

For example, after I renamed `city` to `user_city`, with query 
```
SELECT user_city FROM iceberg.presto_dev.my_table
WHERE user_city = 'sh'
LIMIT 10
```
in IcebergPageSourceProvider.createParquetPageSource, the generated `TupleDomain<ColumnDescriptor> parquetTupleDomain` is `ALL`

```java
            TupleDomain<ColumnDescriptor> parquetTupleDomain = getParquetTupleDomain(descriptorsByPath, effectivePredicate);
            TupleDomainParquetPredicate parquetPredicate = buildPredicate(requestedSchema, parquetTupleDomain, descriptorsByPath, UTC);

```

**Comment by raunaqmorarka** [comment]
cc: @findinpath @alexjo2144
