### ISSUE TITLE
JMX Metric Docs Issue: Port Value Difference

### ISSUE THREAD

**Issue by alionar** [trinodb/trino#18869]
When exploring the [documentation for Monitoring Trino with JMX](https://trino.io/docs/410/admin/jmx.html), I came across an issue. To enable JMX in Trino, you need to set up the config.properties file with the following values:

```jmx.rmiregistry.port=9080```
```jmx.rmiserver.port=9081```

However, after I deployed it with JMX enabled, I encountered a connection timeout when trying to connect to JMX port `9080` using JConsole.

After some research, I found an [article](https://iceburn.medium.com/how-to-expose-jmx-in-kubernetes-b1faad450451) stating that to enable JMX in a Java app, you need to set up jmx.rmiregistry and jmx.rmiserver on the same port.

So, I redeployed it with the following values:

```jmx.rmiregistry.port=9081```
```jmx.rmiserver.port=9081```

with additional jvm.properties
```-Dcom.sun.management.jmxremote```
```-Dcom.sun.management.jmxremote.port=9081```
```-Dcom.sun.management.jmxremote.rmi.port=9081```
```-Dcom.sun.management.jmxremote.authenticate=false```
```-Dcom.sun.management.jmxremote.ssl=false```
```-Dcom.sun.management.jmxremote.local.only=false```
```-Djava.rmi.server.hostname=localhost```

And voila, it worked!

Can anyone confirm if this is a typo in the documentation?

**Comment by ebyhr** [comment]
The latest documentation contains additional Java system property.

**Comment by alionar** [comment]
Yes, additional Java system properties already exist in the [latest documentation](https://trino.io/docs/current/admin/jmx.html) 
![Screenshot 2023-09-04 at 09 24 16](https://github.com/trinodb/trino/assets/18596757/0a573af2-ee0a-4dff-9442-6ab62889f4e8)

but I wanted to confirm the difference in the JMX port issue in this documentation, which is causing the JMX metrics to be inaccessible
![Screenshot 2023-09-04 at 09 21 28](https://github.com/trinodb/trino/assets/18596757/b5be3715-7122-4da5-b282-b1700e79ddd3)

**Comment by hashhar** [comment]
The ports can be different. It's expected to work like that too. The JMX tools ask the `rmiregistry` port to tell where the `rmiserver` can be found so both the ports need to be accessible from the tool you're using to connect to JMX.

**Comment by hashhar** [comment]
the main thing is that `com.sun.management.jmxremote.port` must match `jmx.rmiserver.port` and `com.sun.management.jmxremote.rmi.port` must match the `jmx.rmiregistry.port`.
