### ISSUE TITLE
Enabled `flatGroupByHash` causes higher memory peak consumtion for tpch benchmarks

### ISSUE THREAD

**Issue by radek-kondziolka** [trinodb/trino#18861]
It was observed that when `flatGroupByHash` is enabled then one observe higher peak memory usage for tpch benchmark `iceberg/sf1000/parquet_part`
When: 
-  `flatGroupByHash=false` -> 560 GiB
-  `flatGroupByHash=true` -> 585 GiB

Try to explain that and possibly mitigate the issue.

**Comment by raunaqmorarka** [comment]
Can this be closed now ?
