### ISSUE TITLE
TestBigQueryCaseInsensitiveMapping.testTableNameClash is broken

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#18889]
The test is failing master. https://github.com/trinodb/trino/actions/runs/6042981671/job/16399295160

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/6044637869/job/16403577735?pr=18888

**Comment by hashhar** [comment]
Figured it out. We no longer call `getTableHandle` due to https://github.com/trinodb/trino/commit/c9fa5ffe64439cae24070628275d22d1ccbaa897

**Comment by hashhar** [comment]
Since BigQuery is the only connector which tries to provide "disambiguation" in case of case-only table name differences it's the only connector affected.

Only the tests need to be adjusted AFAIK.
