### ISSUE TITLE
how to connection with SAP hana

### ISSUE THREAD

**Issue by jaimesilvads** [trinodb/trino#18909]
With how to connection  with Sap hana.
Erro:
 ERROR   main    io.trino.server.Server  No factory for connector****

**Comment by ebyhr** [comment]
SAP HANA isn't supported. We need to add a new connector or use existing connectors developed by 3rd pirty.

**Comment by zz22394** [comment]
FYI:
https://medium.com/@dasshims/sap-hana-connector-for-trino-8f94ef68b16b
Some information about `SAP HANA connector for Trino`
