### ISSUE TITLE
mongoDb : SELECT query fails with "Multiple entries with same key"

### ISSUE THREAD

**Issue by rahulr35** [trinodb/trino#18925]
Trino encounters an issue when querying a MongoDB collection that contains fields with identical names, differing only in their case sensitivity. Any attempt to execute a select query on this collection results in an error message: 
`Multiple entries with same key: abc=abC:varchar and abc=abc:varchar`

Field    | Datatype
----------------
"abc"  | varchar
"abC" | varchar

Sample collection to reproduce issue:

`db.createCollection("testCollection")`
`db.testCollection.insertOne({
    abc: "string_1",
    abC: "string_2"
})`

Trino Query:  `select * from testCollection limit 1;`
Trino Output: `Query 20230905_092521_00632_gxv5w failed: Multiple entries with same key: abc=abC:varchar and abc=abc:varchar`

**Comment by ebyhr** [comment]
Closing as we can't handle such fields because of #17
