### ISSUE TITLE
Trino/Iceberg Connector - Handling Timestamp without Timezone - TIMESTAMP(6)

### ISSUE THREAD

**Issue by TonBits** [trinodb/trino#18947]
When using TIMESTAMP in Iceberg which is mapped to TIMESTAMP(6) in Trino/Iceberg connection, querying that field in Trino automatically converts the value in UTC.

This means, any TIMESTAMP without timezone will be translated by Trino on the fly and adds a timezone which defaults to UTC.

Scenario:
Local Time is PST (Server time)

Data is inserted into Iceberg through spark - e.g. 2023/01/01 01:00:00
Querying this in spark will return the same value which is 2023/01/01 01:00:00
However, exactly the same data queried in trino will return 2023/01/01 08:00:00 UTC

Trino seems to be converting the results base on localtime and coverts the value of timestamp without timezone to UTC.

The problem with this, is that TIMESTAMP without timezone could be interpreted by the application differently.
When we migrated the data from HIVE to Iceberg, the application displays a different value (+7 Hours) compared to the previous environment.

Trino Iceberg connection should ignore and should not convert any TIMESTAMP that has no timezone and leave this to the application.
Applications migrating to TRINO will be force to handle this behavior and will add additional conversion to handle TIMESTAMP without timezone fields. Its not a straight data migration anymore as it will involve changing the application as well as the query/sql returns TIMESTAMP without timezone as a timetamp value converted to a UTC.

In the scenario above, the value of the timestamp is logically the same. 
e.g.
2023/01/01 01:00:00
2023/01/01 08:00:00 UTC - how it is queried from Trino/Iceberg

But still it causes an issue to the application as the application will be force to handle TIMESTAMP without timezone as TIMESTAMP with timezone.

**Comment by TonBits** [comment]
Apparently, spark was creating a TIMESTAMP that has a TIMEZONE.
So this is actually a spark issue where SPARK is trying to create TIMESTAMP where the TIMESTAMP was supposedly TIMESTAMP without timezone but actually created a TIMESTAMP with timezone in Iceberg.

Closing this issue.

**Comment by mixermt** [comment]
> Apparently, spark was creating a TIMESTAMP that has a TIMEZONE. So this is actually a spark issue where SPARK is trying to create TIMESTAMP where the TIMESTAMP was supposedly TIMESTAMP without timezone but actually created a TIMESTAMP with timezone in Iceberg.
> 
> Closing this issue.

Hi @TonBits 
Is there any option not to write timezone from Spark

**Comment by TonBits** [comment]
@mixermt sorry for late reply. If I can recall correctly, there was no way to create timestamp in spark without a timezone with iceberg. We have to abandon the combination of spark writing timestamp into iceberg and reading it using trino as it shows different result. Though technically the values are the same if you handle timezones, we cannot afford to change application that uses trino to query the timestamp and handle it with timezone. We have to change a lot of places in the code to handle the timestamp with timezone and convert it to the right timezone before using the value or even displaying it to the user. So we did not migrate to Iceberg for the time being.
