### ISSUE TITLE
trino.example.com: Name or service not known

### ISSUE THREAD

**Issue by whznpu** [trinodb/trino#18974]
I have tried in this way
https://trino.io/docs/405/installation/deployment.html
Then when I ran ./trino --server http://trino.example.com:8080 and SELECT count(*) FROM tpch.tiny.nation;
I got this information and failed.
(by the way, bin/launcher run was also failed and the error message is 
2023-09-08T22:11:39.739+0800	ERROR	Announcer-0	io.airlift.discovery.client.Announcer	Cannot connect to discovery server for announce
io.airlift.discovery.client.DiscoveryException: Announcement failed for http://example.net:8080
)
Thanks a lot!

**Comment by ebyhr** [comment]
`example.net` is just an example url. Pleae replace it with your environment's url.
