### ISSUE TITLE
Wrong CPU reporting in explain plan

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#19016]
Running 

```
explain select * from tpch.tiny.customer;
```

I get

```
Trino version: 426                                                                                                    >
 Fragment 0 [SOURCE]                                                                                                   >
     Output layout: [custkey, name, address, nationkey, phone, acctbal, mktsegment, comment]                           >
     Output partitioning: SINGLE []                                                                                    >
     Output[columnNames = [custkey, name, address, nationkey, phone, acctbal, mktsegment, comment]]                    >
     │   Layout: [custkey:bigint, name:varchar(25), address:varchar(40), nationkey:bigint, phone:varchar(15), acctbal:d>
     │   Estimates: {rows: 1500 (268.00kB), cpu: 0, memory: 0B, network: 0B}                                           >
     └─ TableScan[table = tpch:tiny:customer]                                                                          >
            Layout: [custkey:bigint, name:varchar(25), address:varchar(40), nationkey:bigint, phone:varchar(15), acctba>
            Estimates: {rows: 1500 (268.00kB), cpu: 268.00k, memory: 0B, network: 0B}                                  >
            nationkey := tpch:nationkey                                                                                >
            mktsegment := tpch:mktsegment                                                                              >
            address := tpch:address                                                                                    >
            phone := tpch:phone                                                                                        >
            custkey := tpch:custkey                                                                                    >
            name := tpch:name                                                                                          >
            comment := tpch:comment                                                                                    >
            acctbal := tpch:acctbal
```

Looking at the CPU value of 268.00k this looks to be a memory value as reflected in 268.00kB in the rows data.

However in the WebUI all CPU cost values are all reported as time values.   

Looking at 
https://github.com/trinodb/trino/blob/029e1a07ae6823b9ce61eac82ebd7bb65daea966/core/trino-main/src/main/java/io/trino/sql/planner/planprinter/TextRenderer.java#L260

and 

https://github.com/trinodb/trino/blob/029e1a07ae6823b9ce61eac82ebd7bb65daea966/core/trino-main/src/main/java/io/trino/sql/planner/planprinter/TextRenderer.java#L283

however it somehow uses data size.

Is this a bug in the UI, the explain plan, or am I just misunderstanding something.

**Comment by mosabua** [comment]
This also seems to be explained wrongly in https://www.youtube.com/watch?v=B5PJPYmBlRM as a result.

**Comment by martint** [comment]
CPU cost is an abstract metric that's not necessarily related to actual CPU usage. It's useful to compare the expected relative cost of two operations.

The use of `formatAsDataSize` is just for convenience, but as you can see, it's removing the "size" portion. In the example above, the estimated CPU cost is "268,000" of the abstract unit of CPU cost.

**Comment by mosabua** [comment]
But how come it make sense for the CPU value of cost to be the same value as the memory all the time .. just with a different abstract unit?

**Comment by martint** [comment]
Because it’s derived from the number of tows processed for single operators such as scan/filter/project

**Comment by mosabua** [comment]
Thank you for clarifying @martint . I am closing this issue understanding what is happening, and even though this is confusing.
