### ISSUE TITLE
426 dont support paimon

### ISSUE THREAD

**Issue by leichangqing** [trinodb/trino#19034]
io.trino.server.Server  No factory for connector 'paimon'.  Available factories: [hive, ignite, delta_lake, memory, kudu, blackhole,
kinesis, redis, accumulo, gsheets, elasticsearch, jmx, postgresql, redshift, sqlserver, localfile, example_http, tpch, iceberg, mysql, bigquery, prometheus, mongodb, pinot, tpcds, h
udi, oracle, mariadb, druid, cassandra, clickhouse, kafka, singlestore, atop, raptor_legacy, trino_thrift, phoenix5]
java.lang.IllegalArgumentException: No factory for connector 'paimon'.  Available factories: [hive, ignite, delta_lake, memory, kudu, blackhole, kinesis, redis, accumulo, gsheets, e
lasticsearch, jmx, postgresql, redshift, sqlserver, localfile, example_http, tpch, iceberg, mysql, bigquery, prometheus, mongodb, pinot, tpcds, hudi, oracle, mariadb, druid, cassand
ra, clickhouse, kafka, singlestore, atop, raptor_legacy, trino_thrift, phoenix5]

**Comment by hashhar** [comment]
Trino doesn't ship a `paimon` connector. Is it a custom connector you have developed? If so then you need to add it to the `plugin` directory in your Trino installation.

**Comment by zhuzhengjun01** [comment]
Is there any plan support paimon connector in the future?  We may use paimon connector to select paimon table  writted by flink.

**Comment by zhuzhengjun01** [comment]
> Trino doesn't ship a `paimon` connector. Is it a custom connector you have developed? If so then you need to add it to the `plugin` directory in your Trino installation.
Is there any plan support paimon connector in the future? We may use paimon connector to select paimon table writted by flink.

**Comment by zhuzhengjun01** [comment]
> Paimon has a trino connector that you can install manually: https://paimon.apache.org/docs/master/engines/trino/. Afaik they have not discussed contributing this to the Trino project with anyone from the community.
okk, thanks
