### ISSUE TITLE
Iceberg Parquet writer creates incorrect min/max varchar statistics

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#19052]
When some row groups' min/max values are too long, they don't have min/max.
Then the file min/max for a column is derive from other row groups and thus incorrect, leading to incorrect query results.

**Comment by findepi** [comment]
@ebyhr 's https://github.com/apache/iceberg/pull/8559 is going to fix the problem.

**Comment by ebyhr** [comment]
Releavant Slack thread https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1695059807783119

**Comment by ebyhr** [comment]
Closing as #19215
