### ISSUE TITLE
Can't self-invite to slack community

### ISSUE THREAD

**Issue by tarun2603** [trinodb/trino#19050]
This is the error message i see 
<img width="1231" alt="Screenshot 2023-09-14 at 3 07 30 PM" src="https://github.com/trinodb/trino/assets/102321585/bc32944b-94af-4f38-af8d-5ca1a88e781e">

when i click this link https://join.slack.com/t/trinodb/shared_invite/zt-203h0505f-Nb6KQ6LNdcYFgLZvLw0QgQ. 

What's the alternate way to get invited to slack community

**Comment by martint** [comment]
Thanks for reporting it. It should be fixed now. Can you give it another try?
