### ISSUE TITLE
Support `SELECT * EXCEPT`

### ISSUE THREAD

**Issue by hongbo-miao** [trinodb/trino#19077]
It would be great to support `SELECT * EXCEPT` to select all columns except for certain columns (note not for rows).

For examples, Databricks, BigQuery, DuckDB support:

- Databricks: https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-qry-select.html#syntax
- BigQuery: https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#select_except
- DuckDB (DuckDB uses `EXCLUDE` instead of `EXCEPT`): https://duckdb.org/docs/sql/query_syntax/select

Thanks! ☺️

---

Reference: https://stackoverflow.com/a/58700908/2000548

**Comment by ebyhr** [comment]
There's a `exclude_columns ` table function. https://trino.io/docs/current/functions/table.html?#exclude_columns

**Comment by hongbo-miao** [comment]
Thanks @ebyhr ! ☺️
