### ISSUE TITLE
Incorrect predicate creation for: date (day_partition) >= date_add('day', - 30, CURRENT_DATE) 

### ISSUE THREAD

**Issue by vburenin** [trinodb/trino#19097]
Updated problem statement.

It appears that there is a big difference in how hive, hudi and iceberg optimizers work. Running this query on the same table represented as hudi table and iceberg table gives very different optimizer output. Tables are partitioned by day_partition field that has a format 2023-09-15.

```
Query for Hudi:
explain SELECT object_id FROM hudi_data.vburenin_dev.test_hudi WHERE date(day_partition) >= date_add('day', - 30, CURRENT_DATE) group by 1;

Query for Iceberg:
explain SELECT object_id FROM hudi_data.vburenin_dev.test_iceberg WHERE date(day_partition) >= date_add('day', - 30, CURRENT_DATE) group by 1;

```

On 419 with hive connector and tiny mod to read hudi tables:

```

     │      day_partition := day_partition:string:PARTITION_KEY                                                                                   >
     │          :: [[2023-08-21], [2023-08-22], [2023-08-23], [2023-08-24], [2023-08-25], [2023-08-26], [2023-08-27], [2023-08-28], [2023-08-29], >
     │      created_at := created_at:bigint:REGULAR    
```

On 426 with Hudi connector:
```
    │      day_partition := day_partition:string:PARTITION_KEY        
```

On Iceberg for 419 and 426:
```
 day_partition := 325:day_partition:varchar                                                                                            >
                :: [(<min>, 1), (2022, <max>)]                                                                                                    >  
```

This particular behavior greatly affects the cost at the large scale due to more of LIST operations for Hudi and more of GetObject calls.

# ----------------------------------------------------
Original problem statement:
I have a bunch of hudi and iceberg tables partitioned by varchar day_partition field in the following format: 2023-09-19
When I supply this WHERE condition: DATE (day_partition) >= Date_add('day', - 30, CURRENT_DATE) 
It appears that the filtering predicate is calculated incorrectly as it looks like this:

day_partition := 21:day_partition:varchar
           :: [(<min>, 1), (2022, <max>)]

The issue happened after Trino 419, I have run my tests on Trino 426.

Initially I spotted it when I noticed that Hudi connector is looking up too many partitions even though they are way out of scope.

**Comment by electrum** [comment]
Predicate pushdown generally requires that the partition column be used directly in the comparison, not inside a function. Try changing your query to something like this:
```sql
WHERE day_partition >= CAST(date_add('day', -30, CURRENT_DATE) AS varchar)

**Comment by martint** [comment]
> Predicate pushdown generally requires that the partition column be used directly in the comparison, not inside a function. 

For this case, there's an optimization that unwraps the column reference from inside the `DATE(...)` expression, which is really just syntactic sugar for a cast from varchar to date. See https://trino.io/blog/2019/05/21/optimizing-the-casts-away.html.

**Comment by vburenin** [comment]
This issue appears like a regression as it worked in Trino 419. While changing the SQL query is not a big of an issue, changing a few thousands of them scattered around userbase might pose a serious challenge.

**Comment by martint** [comment]
@vburenin, are you able to pinpoint exactly which version introduced the problem?

**Comment by vburenin** [comment]
@martint Unfortunately no. I jumped from 419 to 426 and spotted the problem only yesterdays when I added my own custom metadata handling into hudi connector.

**Comment by findepi** [comment]
> For this case, there's an optimization that unwraps the column reference from inside the `date(...)` expression, which is really just syntactic sugar for a cast from varchar to date. See https://trino.io/blog/2019/05/21/optimizing-the-casts-away.html.

The blog post is awesome. Note that it predates the optimization that you're observing at work.
It was implemented in https://github.com/trinodb/trino/pull/13567, so Trino 394. I am not aware of any changes in this area between 419 and 426.

> when I added my own custom metadata handling into hudi connector.

@vburenin i think we can consider the issue actionable, if there is a problem with vanilla Trino, without any custom modifications.
Are you seeing a difference on vanilla Trino Iceberg connector between version 419 and 426?
If so, can you please share output of `EXPLAIN SELECT .. FROM your_table DATE (day_partition) >= Date_add('day', - 30, CURRENT_DATE)` from both these versions?

**Comment by vburenin** [comment]
I am planning to poke around to pinpoint a version during the day today CT.
I wish I was familiar with Trino code base to debug it deeper.

**Comment by vburenin** [comment]
I am certainly mistaken on the version it is introduced, I have dug out a symptom in a combination of hive(to read hudi, i had to mode hive connector)+google sheets connector that lead me to the reproduction of the issue in iceberg, but that is apparently not the root cause.
I will update bug description once I narrow my search down more.

**Comment by vburenin** [comment]
Here is more info from the SQL explain that lead me to believe it is a problem of the predicated:

```
explain SELECT object_id FROM hudi_data.vburenin_dev.test_hudi WHERE date(day_partition) >= date_add('day', - 30, CURRENT_DATE) group by 1;
```

On 419 with hive connector and tiny mod to read hudi table:

```

     │      day_partition := day_partition:string:PARTITION_KEY                                                                                   >
     │          :: [[2023-08-21], [2023-08-22], [2023-08-23], [2023-08-24], [2023-08-25], [2023-08-26], [2023-08-27], [2023-08-28], [2023-08-29], >
     │      created_at := created_at:bigint:REGULAR    
```


On 426:
```
    │      day_partition := day_partition:string:PARTITION_KEY        
```

**Comment by vburenin** [comment]
After Upgrading to Trino 466, this problem is gone and overall performance for that particular use case has greatly imporoved.
