### ISSUE TITLE
Support for trailing slashes in ICEBERG register_table procedure table_location

### ISSUE THREAD

**Issue by oskar-szwajkowski** [trinodb/trino#19143]
`table_location` in ICEBERG's `register_table` procedure checks for exact location, which leads to i.e.:
`s3://dummy` and `s3://dummy/` being perceived differently

**Comment by Jake-00** [comment]
Hi @ebyhr , I got interested in solving this issue, could you assgin to me

**Comment by Jake-00** [comment]
hi @oskar-szwajkowski , is `dummy` from example shown above represents bucket name?

**Comment by oskar-szwajkowski** [comment]
> hi @oskar-szwajkowski , is `dummy` from example shown above represents bucket name?

yes, effectively this is bucket name, but whole S3 URI is represented as `tableLocation` in code, from what I can see here:

https://github.com/trinodb/trino/blob/08ef2eec79dad141ce363e6d5e82961e1ac70efb/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/RegisterTableProcedure.java#L127C13-L127C20

**Comment by Jake-00** [comment]
> > hi @oskar-szwajkowski , is `dummy` from example shown above represents bucket name?
> 
> yes, effectively this is bucket name, but whole S3 URI is represented as `tableLocation` in code, from what I can see here:
> 
> https://github.com/trinodb/trino/blob/08ef2eec79dad141ce363e6d5e82961e1ac70efb/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/RegisterTableProcedure.java#L127C13-L127C20

Thanks for your response, I will dig deeply and get more details.
