### ISSUE TITLE
Add support for predicate pushdown for both metadata and protocol in CheckpointEntryIterator

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#19156]
https://github.com/trinodb/trino/blob/e1dc146f2409447318c47a0ebf1167fa4c315942/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java#L185-L187

**Comment by vimalJD** [comment]
### Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue".
