### ISSUE TITLE
Read checkpoint in parallel on the coordinator on the Delta connector

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#19168]
Slack discussion:

https://trinodb.slack.com/archives/C03E2DYAS0J/p1694542953561749

Considerations:
- We usually want to avoid large number of S3 reads from coordinator as it might get throttled. 
- Parquet reader has to buffer 1 parquet page in memory per **column** being read (~**1mb** per page). If you read many row groups in parallel, you have more parquet pages buffered in memory and therefore higher memory usage.
- Additionally we also buffer the compressed data read from S3 per column, this is up to parquet.max-buffer-size per column (default 8MB), could be smaller if the column size is small.

**Comment by rijojoseph07** [comment]
@findinpath See this ticket as completed. Do you know if this feature is released? I was looking for a PR against this ticket, but couldn't find one.
