### ISSUE TITLE
UI not displaying queries after upgrade to 426 with Ranger

### ISSUE THREAD

**Issue by jinyangli34** [trinodb/trino#19172]
After this [PR](https://github.com/trinodb/trino/pull/18911) in 426 version, Trino UI doesn't display any queries except numbers on the top.
We use fixed admin user for UI
```
web-ui.enabled=true
web-ui.authentication.type=fixed
web-ui.user=admin 
```

I noticed that [filterViewQueryOwnedBy method](https://github.com/trinodb/trino/pull/18911/files#diff-9c1c468145e70554a262a95c50bd9bdd474935e69663e803df567939f0b4da0cL160) in Trino now returns empty collection. Whereas in [Ranger/plugin-trino](https://github.com/apache/ranger/blob/696d4340bfdf6c38f7cb4f53fc31b14e1ffaa0e7/plugin-trino/src/main/java/org/apache/ranger/authorization/trino/authorizer/RangerSystemAccessControl.java#L662C1-L668C4), it returns queryOwners directly. 

After changing the `filterViewQueryOwnedBy` to return queryOwners, UI back to normal. 

any ideas?

**Comment by ksobolew** [comment]
Ranger should update their plugin to the new Trino SPI, it's not a Trino bug. These methods had been deprecated for a long time (almost two years).
