### ISSUE TITLE
sortpom-maven-plugin should fail maven checks but not running tests

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#19226]
currently `sortpom-maven-plugin` fails pretty much every CI job
it should run in maven checks
it should not run eg in test matrix, of when building the test matrix

**Comment by findepi** [comment]
cc @nineinchnick @aczajkowski

**Comment by nineinchnick** [comment]
@findepi can you include a link to an example run? Why it shouldn't run in the jobs you mentioned, are you concerned with the overhead?

**Comment by findepi** [comment]
I am solely concerned with the lack of test output from CI for what i see a really minor issue.

**Comment by u7452206** [comment]
hi, does this task anyone work on right now? If not, I would like to help.

**Comment by nineinchnick** [comment]
@u7452206 go ahead and give it a try

**Comment by ritishalaungani** [comment]
Hi @u7452206, have you been able to give this a shot? Wondering if I can give it a try..

Meanwhile, @nineinchnick, @findepi - I am new to contributing here and wanted to join the trino slack channel to ask a few questions. The 'join slack' link on [this](https://trino.io/slack) page seems to be expired. A new invite link is needed - are one of you able to help me get that? Thanks!

**Comment by u7452206** [comment]
> Hi @u7452206, have you been able to give this a shot? Wondering if I can give it a try..
> 
> Meanwhile, @nineinchnick, @findepi - I am new to contributing here and wanted to join the trino slack channel to ask a few questions. The 'join slack' link on [this](https://trino.io/slack) page seems to be expired. A new invite link is needed - are one of you able to help me get that? Thanks!

I didn't work this out. Feel free to continuous.

**Comment by nineinchnick** [comment]
@ritishalaungani the Slack invite link has been updated, please try again, and thanks for reporting!

**Comment by ritishalaungani** [comment]
Thanks @nineinchnick 

@findepi, AFAICT, sortpom-maven-plugin is not being used in this project atall (in any of the jobs or in pom.xml) - I couldn't find any results when I search for sortpom throughout the project. Perhaps it was being used before and was removed at some point? Am I missing something?

In addition, you mention above that checkstyle is disabled in other ci steps. I couldn't figure out where that is happening in the ci.yml file. Can you please point me to it? Thanks!

**Comment by hashhar** [comment]
This should now work out of the box.

We use `-Dair.check.skip-all=true` in non-maven checks and that is respected in airbase for the sortpom plugin - https://github.com/airlift/airbase/blob/c824cada1c69286a9a666d6fe9dd55efa6075389/airbase/pom.xml#L1505-L1511
