### ISSUE TITLE
Long planning time for queries containing unionall with more than 20 subqueries/branches

### ISSUE THREAD

**Issue by Bhargavi-Sagi** [trinodb/trino#19239]
Sample Query:
```
with t(col1, col2) as (values ('c1','c2'))
SELECT 1 AS _col0
FROM
  (
   (
      SELECT 'db_1' AS _db_
      FROM
        t
   ) UNION ALL (
      SELECT 'db_2' AS _db_
      FROM
        t
  .....
  .....
  .....
   ) UNION ALL (
      SELECT 'db_25' AS _db_
      FROM
        t
   ) )
LIMIT 2;
```
This query used to finish within a second till 412. But starting from 413 even this simple query takes more than 6 min to complete. Looks like this might be related to this [#15378](https://github.com/trinodb/trino/pull/15378). @arhimondr

**Comment by martint** [comment]
This is probably the same issue described here: https://github.com/trinodb/trino/issues/18491#issuecomment-1661200881

**Comment by pettyjamesm** [comment]
This issue is resolved by https://github.com/trinodb/trino/pull/19538 (and the plan shape will be improved by https://github.com/trinodb/trino/pull/19471 once it merges)
