### ISSUE TITLE
`test (plugin/trino-druid)` is cancelled by 1h timeout

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#19250]
https://github.com/trinodb/trino/actions/runs/6399693300/job/17372833828

We should investigate why the Druid test is so slow.

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/pull/19251 removes a redundant connector test. TestDruidTypeMapping still needs improvement.

**Comment by hashhar** [comment]
nice, after this change it's 12 mins faster.
