### ISSUE TITLE
Bump org.apache.ignite : ignite-core : 2.15.0 -> Upgrade to 3.0.0-beta1

### ISSUE THREAD

**Issue by Akanksha-kedia** [trinodb/trino#19373]

**Comment by ebyhr** [comment]
We will upgrade to a non-beta library once it's released.

**Comment by mingfang** [comment]
can we upgrade now 
https://mvnrepository.com/artifact/org.apache.ignite/ignite-jdbc/3.0.0

I'm unable to use Trino to connect to Ignite 3
