### ISSUE TITLE
ADD/RENAME COLUMN does not work with Iceberg and Nessie catalog

### ISSUE THREAD

**Issue by domnikl** [trinodb/trino#19424]
Whenever running an `ALTER TABLE` statement that modifies an existing table by eg. adding a new column, Nessie throws an error very similar to what is mentioned here: https://github.com/projectnessie/nessie/issues/7492, although in this case Nessie does not even get the content ID from Trino/Iceberg. It can be reproduced with the following steps (tested with Nessie 0.71.1 and 0.72.0 and Trino 422 and 429):

```sql
CREATE SCHEMA IF NOT EXISTS iceberg.default;
CREATE TABLE IF NOT EXISTS iceberg.default.example (column int);
ALTER TABLE iceberg.default.example ADD COLUMN another_column VARCHAR; -- fails
```

And it will throw this error:

```
Failed to add column: Bad Request (HTTP/400): New value to update existing key 'default.example' has no content ID
```

But in contrary to the aforementioned issue, in this case Nessie indeed does not get the existing content ID. This is what is sent to Nessie:

```json
{
  "commitMeta" : {
    "properties" : {
      "application-type" : "iceberg"
    },
    "hash" : null,
    "committer" : null,
    "message" : "Iceberg schema change against default.example",
    "commitTime" : null,
    "authorTime" : null,
    "author" : "trino",
    "signedOffBy" : null
  },
  "operations" : [ {
    "type" : "PUT",
    "key" : {
      "elements" : [ "default", "example" ]
    },
    "content" : {
      "type" : "ICEBERG_TABLE",
      "id" : null, /* missing content ID */
      "metadataLocation" : "/data/iceberg/default/example-0a0bcc28c41f49b6a197af14ea0529e7/metadata/00003-8a12625b-1426-427b-9dd0-7c322f2bcb81.metadata.json",
      "snapshotId" : 7252275108899396458,
      "schemaId" : 1,
      "specId" : 0,
      "sortOrderId" : 0
    },
    "expectedContent" : null
  } ]
}
```

**Comment by alonahmias** [comment]
Did you have any insights?

**Comment by ajantha-bhat** [comment]
`commitToExistingTable` from the callstack was having a bug and in the latest version (while bumping Iceberg to 1.5.0), it was fixed by adding a lookup to fetch the content id if it is null. Which might have fixed this issue.

So, feel free to try it on the latest version and let me know.

**Comment by domnikl** [comment]
Works perfectly with the latest version, thanks @ajantha-bhat! 👍🏻

**Comment by ajantha-bhat** [comment]
Thanks for confirming.
