### ISSUE TITLE
Update Hive schema evolution documentation

### ISSUE THREAD

**Issue by dain** [trinodb/trino#19459]
I happen to be reading the [code](https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/CoercionUtils.java#L88) today, and I think the docs are out of date.  The docs seem to be missing:
* varchar <-> timestamp
* varchar -> date
* varchar -> narrower varchar
* char -> narrower char
* double -> float
* decimal -> decimal (looks like narrowing and widening)
* decimal -> double, real, varchar, tinyint, smallint, integer, bigint 
* double/real -> decimal

It is strange there is no  there is no date to varchar or varchar to decimal.

Maybe we should add a matrix for this?

**Comment by mosabua** [comment]
Docs are at https://trino.io/docs/current/connector/hive.html#schema-evolution 

I will send a PR to update
