### ISSUE TITLE
Implement zero safe division

### ISSUE THREAD

**Issue by lirui-apache** [trinodb/trino#19491]
Sometimes our users want trino to return NULL when a division-by-zero error happens. And they're reluctant to change their SQLs to achieve that. I wonder whether it makes sense to implement a zero-safe division, e.g. when it's enabled, an expression rewrite rule automatically wrap the divisor with a NULLIF expression?

**Comment by electrum** [comment]
We avoid adding configuration or session properties to Trino that changes query behavior, as this makes testing more difficult, surprises users, makes it impossible to tell what a query does without additional hidden context, etc.

You can use [TRY](https://trino.io/docs/current/functions/conditional.html#try) for zero-safe division. The documentation has an example of using it with division.

**Comment by lirui-apache** [comment]
Thanks for the comment @electrum . I understand we can change the query to do that. Problem is our users don't want to do that, and the reasons may be they'd like the queries to run and return same results in different engines, or because there're too many queries to change. But I also get your point that it's better not to rely on hidden context to tell what a query does. So closing the issue.
