### ISSUE TITLE
trino 429 debug local SqlBaseLexer 

### ISSUE THREAD

**Issue by A-little-bit-of-data** [trinodb/trino#19536]
I try to debug trino429 version locally. The following content is displayed when running DevelopmentServer
java: symbol not found
   Symbol: variable SqlBaseLexer
   Location: Class io.trino.grammar.sql.SqlKeywords

![image](https://github.com/trinodb/trino/assets/31812278/66135c9e-48e7-4f9f-a983-bb46e4511579)

**Comment by A-little-bit-of-data** [comment]
> ```shell
> clean install -DskipTests
> ```

I am operating under Windows. How can I execute this command? I compiled it directly with idea's maven. Isn't this possible?

**Comment by ebyhr** [comment]
Window isn't supported as the development environment. https://github.com/trinodb/trino#build-requirements

I would recommend using WSL2 or VM.

**Comment by Richard-chen3** [comment]
I'm using Mac and I run the command ./mvnw clean install -DskipTests. When I click Run on IDEA, it still tell me that it can't found SqlBaseLexer.
