### ISSUE TITLE
SHOW COLUMNS has no return value

### ISSUE THREAD

**Issue by A-little-bit-of-data** [trinodb/trino#19548]
When I use the SHOW COLUMNS command there is no return value in the 429 version, while the 425 version does
![image](https://github.com/trinodb/trino/assets/31812278/b0cc43c3-aec8-41de-a810-d524164cf222)

![image](https://github.com/trinodb/trino/assets/31812278/2057403a-2726-4212-af07-8464e7ab4131)

I wonder if any friends have encountered this problem?

**Comment by hashhar** [comment]
I cannot reproduce this

Does it happen for all tables in all catalog or just `tpcds.sf1.item`?

```
trino> show columns from tpcds.sf1.item;
      Column      |     Type     | Extra | Comment
------------------+--------------+-------+---------
 i_item_sk        | bigint       |       |
 i_item_id        | char(16)     |       |
 i_rec_start_date | date         |       |
 i_rec_end_date   | date         |       |
 i_item_desc      | varchar(200) |       |
 i_current_price  | decimal(7,2) |       |
 i_wholesale_cost | decimal(7,2) |       |
 i_brand_id       | integer      |       |
 i_brand          | char(50)     |       |
 i_class_id       | integer      |       |
 i_class          | char(50)     |       |
 i_category_id    | integer      |       |
 i_category       | char(50)     |       |
 i_manufact_id    | integer      |       |
 i_manufact       | char(50)     |       |
 i_size           | char(20)     |       |
 i_formulation    | char(20)     |       |
 i_color          | char(20)     |       |
 i_units          | char(10)     |       |
 i_container      | char(10)     |       |
 i_manager_id     | integer      |       |
 i_product_name   | char(50)     |       |
(22 rows)

Query 20231027_134436_00002_8hmtm, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0.25 [22 rows, 1.19KB] [87 rows/s, 4.71KB/s]

trino> select version();
 _col0
-------
 429
(1 row)

Query 20231027_134441_00003_8hmtm, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.21 [0 rows, 0B] [0 rows/s, 0B/s]
```

**Comment by A-little-bit-of-data** [comment]
> I cannot reproduce this
> 
> Does it happen for all tables in all catalog or just `tpcds.sf1.item`?
> 
> ```
> trino> show columns from tpcds.sf1.item;
>       Column      |     Type     | Extra | Comment
> ------------------+--------------+-------+---------
>  i_item_sk        | bigint       |       |
>  i_item_id        | char(16)     |       |
>  i_rec_start_date | date         |       |
>  i_rec_end_date   | date         |       |
>  i_item_desc      | varchar(200) |       |
>  i_current_price  | decimal(7,2) |       |
>  i_wholesale_cost | decimal(7,2) |       |
>  i_brand_id       | integer      |       |
>  i_brand          | char(50)     |       |
>  i_class_id       | integer      |       |
>  i_class          | char(50)     |       |
>  i_category_id    | integer      |       |
>  i_category       | char(50)     |       |
>  i_manufact_id    | integer      |       |
>  i_manufact       | char(50)     |       |
>  i_size           | char(20)     |       |
>  i_formulation    | char(20)     |       |
>  i_color          | char(20)     |       |
>  i_units          | char(10)     |       |
>  i_container      | char(10)     |       |
>  i_manager_id     | integer      |       |
>  i_product_name   | char(50)     |       |
> (22 rows)
> 
> Query 20231027_134436_00002_8hmtm, FINISHED, 1 node
> Splits: 19 total, 19 done (100.00%)
> 0.25 [22 rows, 1.19KB] [87 rows/s, 4.71KB/s]
> 
> trino> select version();
>  _col0
> -------
>  429
> (1 row)
> 
> Query 20231027_134441_00003_8hmtm, FINISHED, 1 node
> Splits: 1 total, 1 done (100.00%)
> 0.21 [0 rows, 0B] [0 rows/s, 0B/s]
> ```
only in columns 

![image](https://github.com/trinodb/trino/assets/31812278/1b9d4f3b-58f6-4487-b593-f041331523bf)

**Comment by A-little-bit-of-data** [comment]
> I cannot reproduce this
> 
> Does it happen for all tables in all catalog or just `tpcds.sf1.item`?
> 
> ```
> trino> show columns from tpcds.sf1.item;
>       Column      |     Type     | Extra | Comment
> ------------------+--------------+-------+---------
>  i_item_sk        | bigint       |       |
>  i_item_id        | char(16)     |       |
>  i_rec_start_date | date         |       |
>  i_rec_end_date   | date         |       |
>  i_item_desc      | varchar(200) |       |
>  i_current_price  | decimal(7,2) |       |
>  i_wholesale_cost | decimal(7,2) |       |
>  i_brand_id       | integer      |       |
>  i_brand          | char(50)     |       |
>  i_class_id       | integer      |       |
>  i_class          | char(50)     |       |
>  i_category_id    | integer      |       |
>  i_category       | char(50)     |       |
>  i_manufact_id    | integer      |       |
>  i_manufact       | char(50)     |       |
>  i_size           | char(20)     |       |
>  i_formulation    | char(20)     |       |
>  i_color          | char(20)     |       |
>  i_units          | char(10)     |       |
>  i_container      | char(10)     |       |
>  i_manager_id     | integer      |       |
>  i_product_name   | char(50)     |       |
> (22 rows)
> 
> Query 20231027_134436_00002_8hmtm, FINISHED, 1 node
> Splits: 19 total, 19 done (100.00%)
> 0.25 [22 rows, 1.19KB] [87 rows/s, 4.71KB/s]
> 
> trino> select version();
>  _col0
> -------
>  429
> (1 row)
> 
> Query 20231027_134441_00003_8hmtm, FINISHED, 1 node
> Splits: 1 total, 1 done (100.00%)
> 0.21 [0 rows, 0B] [0 rows/s, 0B/s]
> ```

I know why there is no return value. It is because the ranger plug-in is loaded, but I don’t know exactly where it is affected. It only affects the columns and the rest is not affected. Thanks.

**Comment by hashhar** [comment]
Ranger allows policies to limit access to certain columns within a table. So it's possible to have tables visible but with 0 columns.

**Comment by A-little-bit-of-data** [comment]
> Ranger allows policies to limit access to certain columns within a table. So it's possible to have tables visible but with 0 columns.


I know, but I have given full permissions and this statement: show columns from tpcds.sf1.item; can be executed, but the list of columns cannot be displayed on the ranger web interface, and the data of this item table can be queried. of.
I don’t know which method affects the display of this column.
![image](https://github.com/trinodb/trino/assets/31812278/5664f092-49fa-42cc-9e91-6b9de954f835)
