### ISSUE TITLE
Problem with configuring a Trino JMX in Kubernetes - no metrics exposed

### ISSUE THREAD

**Issue by ModyTM** [trinodb/trino#19546]
Hello  Trino team and @hashhar i have similar problem described in [JMX Metric Docs Issue: Port Value Difference #18869](https://github.com/trinodb/trino/issues/18869) 
My Trino i deployed using kubernetes cluster.
I tried to enable JMX in Trino YAML (using Helm) and then to export metrics to Datadog monitoring by adding following config:

    additionalConfigProperties:
      jmx-registry: jmx.rmiregistry.port=9080
      jmx-server: jmx.rmiserver.port=9081
    coordinator:
      ad.datadoghq.com/trino-coordinator.checks: |
        {
          "jmx": {
            "init_config": {
              "is_jmx": true,
              "conf": [
                {
                  "include": {
                    "domain": "java.lang",
                    "type": "OperatingSystem",
                    "attribute": {
                      "FreePhysicalMemorySize": {
                        "metric_type": "gauge",
                        "alias": "jvm.free_physical_memory"
                      }
                    }
                  }
                },
                {
                  "include": {
                    "bean": "trino.execution.executor:name=TaskExecutor",
                    "attribute": {
                      "AbandonedQueries.OneMinute.Count": {
                        "alias": "trino.execution.abandoned_queries.one_minute.count"
                      }
                    }
                  }
                }
              ]
            },
            "instances": [
              {
                "host": "%%host%%",
                "port": 9081
              }
            ]
          }
        }
      additionalExposedPorts:
      - name: jmx
        port: 9081
        protocol: TCP
        servicePort: 9081
      additionalJVMConfig:
        jmx-auth: -Dcom.sun.management.jmxremote.authenticate=false
        jmx-hostname: -Djava.rmi.server.hostname=localhost
        jmx-local: -Dcom.sun.management.jmxremote.local.only=false
        jmx-port: -Dcom.sun.management.jmxremote.port=9080
        jmx-remote: -Dcom.sun.management.jmxremote
        jmx-rmi-port: -Dcom.sun.management.jmxremote.rmi.port=9081
        jmx-ssl: -Dcom.sun.management.jmxremote.ssl=false
        
Then i FW ports in kube by executing:

        kubectl port-forward trino-system-trino-coordinator-5c574d679f-x4snp -n trino-system 9123:9081
        Forwarding from 127.0.0.1:9123 -> 9081
        Forwarding from [::1]:9123 -> 9081
        Handling connection for 9123
        Handling connection for 9123
        
And using Jconsole i am getting this error "Connection failed: no such object in table"

![image](https://github.com/trinodb/trino/assets/145591605/eedf8e74-d266-4a41-bd6c-27b015d59864)

I tried to fw ports on 9080 and try to connect to 9080 as well, but then getting this error:

![image](https://github.com/trinodb/trino/assets/145591605/80382988-731a-43ef-af86-e979c9e80d2b)

When i click insecure connection, it try to connect and then throws:
![image](https://github.com/trinodb/trino/assets/145591605/cadda160-fc9b-4167-9899-4cabb76e14af)

Ofc i do not receiving any metrics from JMX Trino coordinator pod in Datadog agent, probably reason of this is that metrics are not properly exposed via JMX. 

Is there anything i can do in order to fix this?
Can we have a direct chat with you @hashhar on Slack / Teams in order to try to fix this?

**Comment by PuszekSE** [comment]
Hi,

Is there any update regarding this issue? I seem to be facing the exact same problem :/ ...

**Comment by ModyTM** [comment]
i fixed it by adding `annotations` in right place of config:

`    coordinator:
      annotations:
        ad.datadoghq.com/trino-coordinator.checks: |`
        
 From here i was able to get metrics.
