### ISSUE TITLE
Allow creation of and writing to Hive transactional/ACID tables in Presto

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#1956]
https://github.com/prestosql/presto/issues/576 adds support for reading from Hive transactional (ACID or insert-only) tables.

This is about adding support for creating such tables from Presto and supporting writes to ACID/Transactional.

**Comment by mirajgodha** [comment]
Hi Team, is there any probability of picking up this task in the near future?

**Comment by findepi** [comment]
@mirajgodha thanks for asking! this is on our tentative roadmap, but i cannot promise any timeline yet

**Comment by findepi** [comment]
Creation and CTAS of ACID tables landed in https://github.com/prestosql/presto/pull/4574.
We still need to be able to INSERT (write) to transactional tables.

**Comment by djsstarburst** [comment]
FTR: Support for INSERT and DELETE for Hive transactional tables was merged in October 2020 by PR #5402

Support for UPDATE for Hive transactional tables was merged in February 2021 by PR #5861

A first step is supporting column statistics for Hive transactional tables can be found in PR #7010 

@findepi, given these developments, is there any point in keeping this issue open?
