### ISSUE TITLE
TTL for a column (asking for cassandra)

### ISSUE THREAD

**Issue by smandyaj** [trinodb/trino#19578]
Is there a way to query for TTL for a column in cassandra using trino ? Seems like i dont see any function/interface registered for the use case!

SELECT TTL(a1) FROM cassandra_tb1_a where a1  = 'abc';

**Comment by ebyhr** [comment]
You can use `query` pass-through table function https://trino.io/docs/current/connector/cassandra.html#query-varchar-table
