### ISSUE TITLE
Can't query data compressed of tables using TimescaleDB with Postgres connector

### ISSUE THREAD

**Issue by thiennguyen-waf** [trinodb/trino#19640]
I'm using TimescaleDB with Postgres connector for store timeserial data in table hypertable. After i compress data in bucket each week before for minimun size of table stored.
problem with Trino is can't query data in hypertable after bucked compressed

If I connect directly to the database using the same user of the connector, it works as expected.

Connector: postgresql
Trino version: 423
Database: PG with timescaledb extention 
hyperTable with compresion

**Comment by hashhar** [comment]
Please include what error you see with the stack trace.
Also include some steps for how to reproduce this.

**Comment by thiennguyen-waf** [comment]
the query not have error or exception. it just don't have data with condition time range query (had compression).
step by step in my case
1. create table on PG , ex: table_a
2. create hypertable for table_a.
3. insert data in table_a. => in this step Trino still can query all data on table_a
4. config for table compression for data old than 1 week.
5. after compression done. Trino can't query data had been compress , just query data on bucket not compress

**Comment by ebyhr** [comment]
@thiennguyen-waf Please share the exact queries so that we can reproduce easily.

**Comment by thiennguyen-waf** [comment]
I found the cause of the problem.
Trino is connecting to PG Replicate.
I don't know why the library asynchrony between master and replicate of the extended TimescaleDB PG occurred, but after adding the timescaleDB library to the replicate node, Trino was able to query the compressed buckets.

**Comment by ebyhr** [comment]
First of all, we don't support TimescaleDB officially. Probably, we need a dedicated connector in the future.
