### ISSUE TITLE
Alter table add column in Iceberg does not support timestamp

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#19708]
The following statements works

```
CREATE TABLE person (
  uuid uuid,
  firstname varchar(50),
  lastname varchar(50),
  dob date,
  create_ts timestamp
);
```

However adding a column of timestamp type does not work.

```
ALTER TABLE person
ADD COLUMN update_ts timestamp;
```

I get the error message.

```
Timestamp precision (3) not supported for Iceberg. Use "timestamp(6)" instead.
```

and as expected this works.

```
ALTER TABLE person
ADD COLUMN update_ts timestamp(6);
```

However it should really either work for both CREATE and ALTER .. or fail for both. Personally I prefer if it works for both...

**Comment by martint** [comment]
CREATE and ALTER should work consistently. We've added a mechanism for connectors to "override" the precision of a type. This just seems like a bug or oversight when the feature was added. It needs to be extended to support ADD COLUMN.

**Comment by mosabua** [comment]
@alexjo2144 @ebyhr @findinpath - fyi

**Comment by mosabua** [comment]
Awesome.. thanks!
