### ISSUE TITLE
Flaky TestKafkaPlugin

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#19702]
```
Error:  io.trino.plugin.kafka.TestKafkaPlugin.testSslTruststoreMissingFileSpindown -- Time elapsed: 0.220 s <<< FAILURE!
java.lang.AssertionError: 

Expecting throwable message:
  "Configuration errors:

1) Error: Configuration property 'kafka.ssl.endpoint-identification-algorithm' was not used

2) Error: Configuration property 'kafka.ssl.key.password' was not used

3) Error: Configuration property 'kafka.ssl.keystore.location' was not used

4) Error: Configuration property 'kafka.ssl.keystore.password' was not used

5) Error: Configuration property 'kafka.ssl.keystore.type' was not used

6) Error: Configuration property 'kafka.ssl.truststore.location' was not used

7) Error: Configuration property 'kafka.ssl.truststore.password' was not used

8) Error: Configuration property 'kafka.ssl.truststore.type' was not used

8 errors"
to contain:
  "Error: Invalid configuration property kafka.ssl.truststore.location: file does not exist: /not/a/real/path"
but did not.
```

Happened on https://github.com/trinodb/trino/actions/runs/6821919079/job/18553418277

**Comment by wendigo** [comment]
It's totally indeterministic. Sometimes I'm able to reproduce it locally, sometimes not. In isolation this test works all the time, when run as a part of tests in the module, it doesn't.

More occurrences: 

- https://github.com/trinodb/trino/actions/runs/6817992840/job/18543757303
- https://github.com/trinodb/trino/actions/runs/6814368126/job/18531227195
- https://github.com/trinodb/trino/actions/runs/6812756163/job/18525978049

I thinks it's related to the JUnit parallelism hence cc @martint

**Comment by martint** [comment]
Those tests are completely independent from each other, so there are no concurrency effects. I think it has to do with some order-dependent construction of the Guice modules in the Kafka connector.
