### ISSUE TITLE
Enabling Fault Tolerance with a retry policy of "QUERY" results in INTERNAL_ERROR

### ISSUE THREAD

**Issue by Gingernaut** [trinodb/trino#19758]
I'm using Trino 430 and have the following fault tolerance settings enabled on both the Coordinator and Worker nodes:

```
## retries
retry-policy=QUERY
retry-initial-delay=4s
retry-max-delay=40s
query-retry-attempts=4
retry-delay-scale-factor=2.0
```

I've seen a sudden increase in `TrinoQueryError(type=INTERNAL_ERROR, name=EXCHANGE_MANAGER_NOT_CONFIGURED, message="Exchange manager must be configured for the failure recovery capabilities to be fully functional", ` in my application.

The retry policy documentation states that configuring an exchange manager is required for `TASK` level retry policy but it doesn't say that for `QUERY`. Should this error be occurring for a `QUERY` level retry?

**Comment by hashhar** [comment]
cc: @losipiuk @linzebing

**Comment by losipiuk** [comment]
Query level retries will work without exchange manager as long as query result is small. For queries which return large result set we need to spool it somewhere before returning to user, and we use exchange manager for that. Without query level retries we would stream query result to client but we cannot do that with retires enabled as we do not know if query will complete successfully. If we need a retry we cannot tell client to discard part of result it consumed so far (protocol does not suppport that; and even if it did handling that on client side is problematic).

You can configure how big responses will work without exchange configured with `exchange.deduplication-buffer-size`. It is 32MB by default. Note that making it larger will increase memory pressure on coordinator.

The docs touch on thate here https://trino.io/docs/current/admin/fault-tolerant-execution.html#query
