### ISSUE TITLE
ArrayIndexOutOfBoundsException when using parquet.ignore-statistics 

### ISSUE THREAD

**Issue by jinyangli34** [trinodb/trino#19760]
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77)
	at io.trino.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:265)
	... 32 more
```

**Comment by jinyangli34** [comment]
Could be related to https://github.com/trinodb/trino/pull/19439

**Comment by findepi** [comment]
Fixed by https://github.com/trinodb/trino/pull/19761

**Comment by findepi** [comment]
@jinyangli34  Thank you for the fix and quick turn around on the PR!

Just curious, what's your use-case for `parquet.ignore-statistics`?
We initially had this flag due to some statistics handling bugs. I hoped it's no longer necessary and could be removed, and would love to know in what situations it is still needed.

**Comment by jinyangli34** [comment]
> Just curious, what's your use-case for `parquet.ignore-statistics`? We initially had this flag due to some statistics handling bugs. I hoped it's no longer necessary and could be removed, and would love to know in what situations it is still needed.

We have `parquet.ignore-statistics` turned on due to query failure on corrupted statistics. 
We only enabled this flag for Hive catalog, and disabled on newer Iceberg catalog. With more tables migrating to Iceberg, the usage of this flag will be less, and we haven't seen any issues with flag off on Iceberg catalog.
