### ISSUE TITLE
Table Type Mismatch in AWS Glue Metastore using Delta and Hive Connectors

### ISSUE THREAD

**Issue by hoaxduong** [trinodb/trino#19771]
Hi there,

I'm encountering an issue with Trino 433 in the context of using AWS Glue as a metastore. Here's the problem:

- When I create a view using the Delta connector, it gets stored in `delta.INFORMATION_SCHEMA.tables` and is marked as a 'BASE TABLE'.
- However, when I use the Hive connector and select `hive.INFORMATION_SCHEMA.tables`, the table type remains 'VIEW'.

This inconsistency is puzzling. I'm not sure if it's a configuration issue, an expected behavior, or a bug in how Trino interacts with these connectors.

Any insights or suggestions on what might be happening and how to resolve this would be greatly appreciated.

Thanks!

**Comment by ebyhr** [comment]
The cause is the following method. The result stream doesn't contain Trino views. 
https://github.com/trinodb/trino/blob/d2586fd57271e47042fac431237f5275a1ddc0bc/plugin/trino-hive/src/main/java/io/trino/plugin/hive/TrinoViewHiveMetastore.java#L157-L162
