### ISSUE TITLE
Document on system information rules is incorrect

### ISSUE THREAD

**Issue by oneonestar** [trinodb/trino#19781]
> These rules specify which users can access the system information management interface. System information access includes the following aspects:
> Read access to details such as Trino version, uptime of the node, and others from the /v1/info and /v1/status REST endpoints.

[Document](https://github.com/trinodb/trino/blob/3cbe0c2d828e3291c895363abe7305511f780396/docs/src/main/sphinx/security/file-system-access-control.md?plain=1#L639C1-L643C55) states that read access from `/v1/info` and `/v1/status` are affected by system information rules. However they are not. 

Public:
* `HEAD /v1/status`
* `GET /v1/status`
* `GET /v1/info`
* `GET /v1/info/state`
* `GET /v1/info/coordinator`

MANAGEMENT_WRITE check:
* `PUT /v1/info/state` (Endpoint for graceful shutdown)

---
Ref:
https://github.com/trinodb/trino/blob/3cbe0c2d828e3291c895363abe7305511f780396/core/trino-main/src/main/java/io/trino/server/StatusResource.java#L67
https://github.com/trinodb/trino/blob/3cbe0c2d828e3291c895363abe7305511f780396/core/trino-main/src/main/java/io/trino/server/ServerInfoResource.java#L64

https://github.com/trinodb/trino/pull/17153

**Comment by mosabua** [comment]
@dain @electrum is the implementation as desired so we should update the docs? 

@oneonestar can you send a PR potentially?

**Comment by hashhar** [comment]
`/v1/status` at the very least is expected to be public since they are used as health-checks by things like load-balancers, our Docker images, k8s probes and so on.
