### ISSUE TITLE
query.max-writer-task-count doesn't match with the documentation

### ISSUE THREAD

**Issue by oneonestar** [trinodb/trino#19783]
|         | Configuration property       | Session property       |
|---------|------------------------------|------------------------|
| In Code | query.max-writer-task-count  | max_writer_tasks_count |
| In Doc  | query.max-writer-tasks-count | max_writer_tasks_count |

Ref:
https://trino.io/docs/428/admin/properties-query-management.html?highlight=max_writer_tasks_count#query-max-writer-tasks-count
https://github.com/trinodb/trino/blob/49072b65cd01c216cfbf2ef5624556b70ff3e19b/core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java#L268

Since the description is "The maximum number of **_tasks_** that will take part in writing data",
I think we should change the code to match the doc.
ie. `query.max-writer-task-count` -> `query.max-writer-tasks-count`

https://trino.io/docs/428/release/release-411.html
Also, in release note the config was mentioned as `query.max-writer-tasks-count`.

**Comment by radek-starburst** [comment]
https://github.com/trinodb/trino/pull/19793
