### ISSUE TITLE
After the upgrade to version 431 Delta Lake connector issue 

### ISSUE THREAD

**Issue by andyliao0508** [trinodb/trino#19825]
Version 430, I use system.register_table
sample:
CALL example.system.register_table(schema_name => 'testdb', table_name => 'customer_orders', table_location => 's3://my-bucket/a/path')
  The function is normal.
But after version 431, the following error will appear
SQL Error [4]: ​​Query failed (#20231120_012309_00001_w24x5): Access Denied: Cannot execute procedure delta_lake.system.register_table.

delta_lake catalog configuration file I have set the following properties
**delta.register-table-procedure.enabled=true**

**Comment by Phani2811** [comment]
Am also facing same issue. I have enabled Delta lake connector for the first time and trying to execute the procedure. getting same exact issue as above. Can anyone please help.

**Comment by ebyhr** [comment]
Are you using file-based access control?

**Comment by andyliao0508** [comment]
> Are you using file-based access control?

yes

**Comment by ebyhr** [comment]
Thanks, please confirm https://trino.io/docs/current/release/release-431.html#security

**Comment by andyliao0508** [comment]
> Thanks, please confirm https://trino.io/docs/current/release/release-431.html#security

sorry 
about link  [https://github.com/trinodb/trino/blob/master/lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FunctionAccessControlRule.java]

I don't quite understand
this my rule.json file bellow:

{
  "queries": [
    {
      "user": "admin",
      "allow": ["execute", "kill", "view"]
    },
    {
      "allow": ["execute"]
    }
  ],
  "functions": [
    {
      "privileges": [
        "EXECUTE",
        "GRANT_EXECUTE"
      ]
    },
    {
      "user": "admin",
      "function": "query",
      "privileges": [
        "EXECUTE"
      ]
    }
  ],
  "catalogs": [
    {
      "user":"admin",
      "catalog": ".*",
      "allow": "all"
    }
  ],
    "tables": [
      {
        "user": "admin",
        "privileges": ["SELECT", "INSERT", "DELETE", "UPDATE", "OWNERSHIP"]
      }
    ]
}
