### ISSUE TITLE
Incorrect query result involving -0.0

### ISSUE THREAD

**Issue by inglesp** [trinodb/trino#19828]
Given the following tables and data:

```
CREATE TABLE p (id INTEGER)
CREATE TABLE t1 (id INTEGER, d DOUBLE)
CREATE TABLE t2 (id INTEGER, d DOUBLE)
INSERT INTO p (id) VALUES (1)
INSERT INTO t1 (id, d) VALUES (1, 0.0)
INSERT INTO t2 (id, d) VALUES (1, 0.0)
```

This query unexpectedly does not return any results:

```
SELECT t1.d, t2.d
FROM p
JOIN t1 ON p.id = t1.id
JOIN t2 ON p.id = t2.id
WHERE t1.d = -t2.d
```

However, changing the signs on the conditional expression...

```
SELECT t1.d, t2.d
FROM p
JOIN t1 ON p.id = t1.id
JOIN t2 ON p.id = t2.id
WHERE -t1.d = t2.d
```

...returns `(0.0, -0.0)`.

We have confirmed this behaviour is present in the latest Trino release: https://hub.docker.com/layers/trinodb/trino/432/images/sha256-5b2dbd6df59fabaef35600166ef018e1b416a0b45a258ab688a4b95d1b7b7fd4?context=explore.

**Comment by hashhar** [comment]
@martint

**Comment by martint** [comment]
Thanks for the report. We'll look into it.

Here's a simpler reproduction:

```sql
CREATE TABLE t(d) AS (VALUES 0e0);

SELECT *
FROM t t1 JOIN t t2 ON t1.d = -t2.d
```

**Comment by martint** [comment]
It appears to be an issue with dynamic filtering. The problem disappears when setting the `enable_dynamic_filtering` session property to false.

**Comment by inglesp** [comment]
Thanks for the quick fix!
