### ISSUE TITLE
Session properties in doc don't match with the implementation

### ISSUE THREAD

**Issue by oneonestar** [trinodb/trino#19826]
After ran through all the session properties in doc, the following properties don't match with the implementation:

| **Doc**                                        | **Impl**                                         |
|------------------------------------------------|--------------------------------------------------|
| push_aggregation_through_join                  | push_aggregation_through_outer_join              |
| min_hash_partition_count_for_writre            | min_hash_partition_count_for_write               |
| query_remote_task_enable_adaptive_request_size | remote_task_adaptive_update_request_size_enabled |
| query_remote_task_guaranteed_splits_per_task   | remote_task_guaranteed_splits_per_request        |
| query_remote_task_max_request_size             | remote_task_max_request_size                     |
| query_remote_task_request_size_headroom        | remote_task_request_size_headroom                |

Ref: 
* https://github.com/trinodb/trino/pull/3205
* https://github.com/trinodb/trino/pull/15721
* https://github.com/trinodb/trino/pull/15951

---
Extract all session properties in doc
```
$ grep --include=\*.md -rn docs/src/main/sphinx -e '\*\*Session property:'
docs/src/main/sphinx/admin/properties-spilling.md:9:- **Session property:** `spill_enabled`
docs/src/main/sphinx/admin/properties-write-partitioning.md:9:- **Session property:** `use_preferred_write_partitioning`
....
```

**Comment by ebyhr** [comment]
cc: @mosabua

**Comment by mosabua** [comment]
Great job finding this. Do you plan on sending a PR to fix this @oneonestar ?

**Comment by oneonestar** [comment]
Fix the first two items in https://github.com/trinodb/trino/pull/20461.
`remote_task_*` require some discussion because I think the implementation should be changed to keep naming consistent. This will be a breaking change. Should I open another issue or can we just discuss here?

**Comment by mosabua** [comment]
I think we should just fix the docs .. and if we want to rename the properties that is a separate topic to discuss with various others. We can tackle that afterwards.

**Comment by oneonestar** [comment]
https://github.com/trinodb/trino/issues/20075#issuecomment-1862616374
> the names are constructed hierarchical

Referring to this comment, these session properties should follow the naming convention.
Thus the implementation should be fixed instead of the doc.

**Comment by mosabua** [comment]
At this stage we dont have agreement on the renaming .. but we do have agreement that the docs are wrong and should be fixed. So lets fix the docs for now.
