### ISSUE TITLE
Trino 433 print too many logs!

### ISSUE THREAD

**Issue by ImTangYun** [trinodb/trino#19840]
When I start trino 433, I found there are many debug logs, is there any new log config need adjust?
my log.properties which in trino 426 works well:
io.trino=INFO

and I tried add:
org.eclipse.jetty=WARN
the problem not solved

There is part content of server.log :
![image](https://github.com/trinodb/trino/assets/5945486/a268ed74-0e25-493e-9c53-def5656dbc66)

**Comment by hashhar** [comment]
cc: @wendigo @electrum New Jetty version?

**Comment by wendigo** [comment]
@hashhar no. Some log levels seems to be enabled

**Comment by hashhar** [comment]
well, it doesn't behave like this out of the box. Please check what logs levels are actually in use or if some JVM properties are being caused which enable Jetty debug logs.

From the text it's apparent that DEBUG is enabled for some classes at least under Jetty.

Closing. Feel free to re-open if you still hit this.
