### ISSUE TITLE
TableFunction PARTITION BY behavior

### ISSUE THREAD

**Issue by tbaeg** [trinodb/trino#19865]
For a table function such as below I am seeing column `foo` be returned even if `TableFunctionAnalysis.returnedType` does not contain the column itself. This causes the insert to fail throwing a `SemanticException` because of mismatching types.

```INSERT INTO catalog1.schema.table2
SELECT *
FROM TABLE(
    catalog.schema.tablefunc(
        input => TABLE(
          SELECT data, abs(random(20)) AS foo
          FROM catalog1.schema.table1
        ) PARTITION BY foo
    )
);
```

Location of where partition by field is added:
https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java#L1769

It is similar to a `GROUP BY` or `WINDOW` operation, so not returning the grouping column wouldn't make sense. But in this case, the `PARTITION BY` is part of the argument, not the return type. It also seems to be more of a means to force a means of parallelism.

Is this is the intended behavior? I started a slack discussion but didn't get much traction so I am posing the question here for the community.

https://trinodb.slack.com/archives/CP1MUNEUX/p1699736414130039

**Comment by wendigo** [comment]
cc @martint
