### ISSUE TITLE
Potential infinite loop at IterativeOptimizer with Iceberg

### ISSUE THREAD

**Issue by assaf2** [trinodb/trino#19876]
At `io.trino.plugin.iceberg.IcebergMetadata#applyFilter`, returning `Optional.empty` is conditioned by `constraint.getPredicateColumns()` being empty:
https://github.com/trinodb/trino/blob/4cb3072a2aee3cc2fba08b9f70ffcba0f9190361/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java#L2541
When this condition was added this field was always empty when the rule was running within iterative optimizer (see discussion at https://github.com/trinodb/trino/pull/17263/files#r1189575899) but this is not the case since https://github.com/trinodb/trino/pull/16019/files#diff-624ea155d75175ba8802d5f93af759bdb88c6f63f1ca9660d6704892e1033f1dR814-R825. According to my check, we don't see an infinite loop only because `io.trino.sql.planner.iterative.rule.PushPredicateIntoTableScan#arePlansSame` returns `true` and stops the iterative process. If in the future `io.trino.plugin.iceberg.IcebergTableHandle#equals` will return `false` when comparing 2 tables of 2 different iterations, then we'll see an infinite loop. That's while `io.trino.spi.connector.ConnectorTableHandle` is an empty interface that doesn't declare `equals()`.

**Comment by findepi** [comment]
cc @raunaqmorarka @sopel39

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/20007
