### ISSUE TITLE
PREPARE statement formats sql

### ISSUE THREAD

**Issue by yonatand** [trinodb/trino#19873]
Hello,

I use the PREPARE statement to check user inputted SQL for errors (without running it as if the SQL is correct I need to inject more SQL),
It looks like the PREPARE statement formats the SQL and the returned error row + column numbers are not matching the prepared SQL.

EXAMPLE:
```SQL
PREPARE TEST_SQL FROM  ( SELECT * FROM (
SELECT FLAG1, NOT_REAL_COL
FROM REAL_TABLE
) )
```
```SQL
DESCRIBE OUTPUT TEST_SQL
```

EXPECTED:
```
line 2:15: Column 'not_real_col' cannot be resolved
```

CURRENT RESULT (bug):
```
line 7:9: Column 'not_real_col' cannot be resolved
```

**Comment by hashhar** [comment]
For checking query correctness use `EXPLAIN TYPE VALIDATE`. See https://trino.io/docs/current/sql/explain.html
