### ISSUE TITLE
Selective tests execution

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#1988]
Currently we always run all the tests per each build. Either for master branch as well for each pull requests. This is great because it gives high confidence that change is working, however it is very time and resource consuming which becomes more important while Presto is getting bigger and bigger.

The idea here is to run less tests without sacrificing confidence that change is correct. In other words run only tests for components that are affected by the change. Like not running tests for Kudu connector when someone changes authorization code in Hive connector.

Today we are doing something to address that. Not running tests for HDP 3 Hadoop platform when running build for pull requests. These tests are run only for master branch.

This issue is raised to start broader discussion.

Below there is the example implementation design details. The best when it would be possible to implement this only using Travis.
Let say they are:
 - complete test build - that runs all tests (some way as it is done today)
 - partial test build -  that runs only tests for components affected by the change
 - storage - that stores information about which git commit hashes passed successfully complete test build. Storage needs to be publically accessible. Maybe we could use private infra to mark successful builds, if that is not possible using Travis.
- component to test mapping - a map that points what tests have to be executed when testing given component. e.g. for presto-hive we would run all unit tests in presto-hive, hive integration tests in presto-hive-hadoop2/bin and set of product tests execution.

1. We still run complete build for each commit (merge) in master branch.
2. Whenever complete build passes successfully we store the git commit hash in the storage.
3. When running partial build (for pull request) we would check in the storage latest successful complete build git commit hash. Then we could check all the commits till HEAD since that git commit hash to find what components were changed. Having a list of changed components we need to find a list of affected components that would be list of changed components with all the components that are using them. e.g. when presto-hive is changed we need to test also presto-iceberg. Then using component to test mapping we could run only tests for components that are affected by the change.

**Comment by kokosing** [comment]
We could use github commit statuses to mark commit that passed successfully complete test build. See https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks

**Comment by jvanzyl** [comment]
This is generally referred to as impact analysis: https://martinfowler.com/articles/rise-test-impact-analysis.html

Paul Hammant has written quite a bit on this topic and he even has an implementation he's written about here: https://paulhammant.com/2019/10/20/quicker-local-maven-builds/

Something could certainly be implemented in Java for Maven.

**Comment by hashhar** [comment]
See #10323 and #10895

**Comment by findepi** [comment]
Marked https://github.com/trinodb/trino/pull/10895 as fixing this issue. cc @nineinchnick
