### ISSUE TITLE
Trino+iceberg, select count(*) is too slow

### ISSUE THREAD

**Issue by paulpaul1076** [trinodb/trino#19909]
I tried 2 queries:

select sum(record_count) from "clickstream_v3$files"

and 

select count(*) from clickstream_v3

The first one is very fast, the second one is very slow. Why is the second one slow? It seems to not go into metadata, but literally go row by row in parquet.

**Comment by raunaqmorarka** [comment]
COUNT(*) queries on parquet are not executed row by row, it's executed by reading row counts from parquet file footers.
Additionally, https://github.com/trinodb/trino/pull/19303 improved this to read only iceberg metadata. Please try this on 430+ release.
