### ISSUE TITLE
[Iceberg] Materialized View based on PTF is always stale

### ISSUE THREAD

**Issue by Barbayar** [trinodb/trino#19904]
# Context
We've noticed that a materialized view we created through Iceberg behaved as a logic view.
After checking the code we found out that it happened because we used PTF instead of an actual table in our query.

1. [Here](https://github.com/trinodb/trino/blob/ee27de460faba5239c521cb7ecb387aaa86731a4/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java#L2811) Iceberg iterates over the tables used in the query. Because we don't have any table, `dependencies` becomes `'' (empty string)`.
2. Because, `dependencies` is an empty string, [here](https://github.com/trinodb/trino/blob/ee27de460faba5239c521cb7ecb387aaa86731a4/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java#L2901) Iceberg rules out the view as stale.

# Possible Solutions
### Quick Fix
We can check if `sourceTableHandles` is empty [here](https://github.com/trinodb/trino/blob/ee27de460faba5239c521cb7ecb387aaa86731a4/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java#L2811), and if it's empty, we can set `UNKNOWN_SNAPSHOT_TOKEN` in `dependencies`.

### (Probably) More Proper Fix
In `StatementAnalyzer`, we [track](https://github.com/trinodb/trino/blob/18e1a79eb3f10d4daac76349aa56940739750351/core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java#L1658) PTFs referenced in the query. We could pass the registered PTFs along with the tables into Materialized View finisher, so we can know if there a PTF was referenced or not.

**Comment by findepi** [comment]
> ### Quick Fix
> We can check if `sourceTableHandles` is empty [here](https://github.com/trinodb/trino/blob/ee27de460faba5239c521cb7ecb387aaa86731a4/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java#L2811), and if it's empty, we can set `UNKNOWN_SNAPSHOT_TOKEN` in `dependencies`.

Would this work if MV definition mixes PTFs and regular tables?

> ### (Probably) More Proper Fix
> In `StatementAnalyzer`, we [track](https://github.com/trinodb/trino/blob/18e1a79eb3f10d4daac76349aa56940739750351/core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java#L1658) PTFs referenced in the query. We could pass the registered PTFs along with the tables into Materialized View finisher, so we can know if there a PTF was referenced or not.

Yeah, that might work. I think the right way to identify a PTF would by by it's fully qualified name.
