### ISSUE TITLE
Misleading surefire reports on number of tests run from base class

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#19908]
When we have a common base class with Junit tests and two subclasses which are run concurrently the output of surefire is misleading.
It looks like when first test class completes surefire reports the number of tests which have been run which is sum of tests run so far from both subclasses.
It can be observed with `BaseDeltaFailureRecoveryTest` which has two subclasses: `TestDeltaQueryFailureRecoveryTest` and `TestDeltaTaskFailureRecoveryTest`.

Output:
```
Tests run: 26, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 560.2 s -- in io.trino.plugin.deltalake.TestDeltaQueryFailureRecoveryTest
...
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 630.1 s -- in io.trino.plugin.deltalake.TestDeltaTaskFailureRecoveryTest
```

https://github.com/trinodb/trino/actions/runs/7000158137/job/19040462459

cc: @martint @findepi

**Comment by losipiuk** [comment]
Created surefire bug: https://issues.apache.org/jira/browse/SUREFIRE-2217

**Comment by losipiuk** [comment]
Duplicate of https://github.com/trinodb/trino/issues/20113

**Comment by findepi** [comment]
Sorry for re-filing same issue.
