### ISSUE TITLE
Apache pinot connector 1.0.0 release

### ISSUE THREAD

**Issue by ChristianJohnston97** [trinodb/trino#19919]
Please could you update the Pinot connector to 1.0.0 release.

**Comment by ChristianJohnston97** [comment]
@ebyhr its had very little activity on it in past month. Can I help on it at all? The org I work for needs this pinot client update asap

**Comment by ebyhr** [comment]
@ChristianJohnston97 See https://github.com/trinodb/trino/pull/19136#issuecomment-1734135415
