### ISSUE TITLE
iceberg.materialized-views.hide-storage-table missing in Documentation

### ISSUE THREAD

**Issue by McKMarcBruchner** [trinodb/trino#19949]
Hi trino guys,

While upgrading our trino version we figured out that the config flag `iceberg.materialized-views.hide-storage-table` is missing in your current documentation https://trino.io/docs/current/connector/iceberg.html#general-configuration (version 433).

![Screenshot 2023-11-29 at 12 47 59](https://github.com/trinodb/trino/assets/87852749/c96cc744-05e3-4cfd-8bdd-d78ece2d487f)

The flag was added in this PR https://github.com/trinodb/trino/pull/18853/files , but it seems like documentation was not updated.

I'm not sure if you are aware that it is missing there, that's why I've opened this issue.

Thanks for providing this flag, this helps us a lot, since our Iceberg needs access to the storage table!

**Comment by ebyhr** [comment]
cc: @mosabua

**Comment by McKMarcBruchner** [comment]
thank you very much!
