### ISSUE TITLE
[master] io.trino.server.Server Exchange manager factory 'filesystem' is not registered. Available factories: []

### ISSUE THREAD

**Issue by Slashoper** [trinodb/trino#19974]
![image](https://github.com/trinodb/trino/assets/19834014/d0c12a2a-4599-4394-84ad-45a09436b31c)

when i debug in local , i found the problem , cannot found Exchange manager factory

**Comment by ebyhr** [comment]
Let me close as the current master doesn't have such a problem. Pleaser feel free to continue in Trino Slack `#dev` channel.
