### ISSUE TITLE
Support mapping TINYINT to INT when copying from SQL Server to Iceberg

### ISSUE THREAD

**Issue by jonashaag** [trinodb/trino#19971]
I want to copy a table from SQL Server to Iceberg like so

```sql
CREATE TABLE iceberg.y.z AS SELECT * FROM mssql.y.z
```

One of the columns is TINYINT/SMALLINT in SQL Server and so Trino will fail executing that query.

Is there a way to automatically convert these types without having to add `CAST(... AS INT)` to all problematic columns?

**Comment by Praveen2112** [comment]
> Is there a way to automatically convert these types without having to add CAST(... AS INT) to all problematic columns?

Now in Trino we have a way to automatically coerce a column to a type which is supported by the connector - this can be achieved by implementing `getSupportedType` in `IcebergMetadata` - Would like to open a PR which supports `TINYINT` to `INT` mapping in Iceberg connector ?
