### ISSUE TITLE
Iceberg ParallelIterable will cause coodinator a memory leak

### ISSUE THREAD

**Issue by Heltman** [trinodb/trino#19986]
I found trino read iceberg table will call `scan.planFiles()` in `IcebergSplitSource`.  This will use iceberg api to get all `FileScanTask`. But iceberg code exist memory leak. When trino use `IcebergSplitSource.close()` to close `fileScanIterable`, it will continue to run.
```java
// IcebergSplitSource in trino
@Override
public CompletableFuture<ConnectorSplitBatch> getNextBatch(int maxSize)
{
    ...
    if (fileScanIterable == null) { 
        this.fileScanIterable = closer.register(scan.planFiles());
        ...
    }
...
}
```

Because iceberg use `ParallelIterable` to asynchronous read manifest files, it generate `GenericDataFile` to a ConcurrentLinkedQueue. When trino use `IcebergSplitSource.close()`, it will cancel all futureTask, but actural it cancel failed. All run future will continue to add to queue. Trino coordinator will continue read manifests to generator `GenericDataFile` but not use, cpu and memory will waste.
```java
# ParallelIterable in iceberg
private final ConcurrentLinkedQueue<T> queue = new ConcurrentLinkedQueue<>();

this.tasks =
          Iterables.transform(
                  iterables,
                  iterable ->
                      (Runnable)
                          () -> {
                            try (Closeable ignored =
                                (iterable instanceof Closeable) ? (Closeable) iterable : () -> {}) {
                              for (T item : iterable) {
                                queue.add(item);   // this will not exist, because ConcurrentLinkedQueue can't interrupt
                              }
                            } catch (IOException e) {
                              throw new RuntimeIOException(e, "Failed to close iterable");
                            }
                          })
              .iterator();
...
this.taskFutures = new Future[2 * ThreadPools.WORKER_THREAD_POOL_SIZE];
...
@Override
public void close() {
  this.closed = true;

  for (Future<?> taskFuture : taskFutures) {
    if (taskFuture != null && !taskFuture.isDone()) {
      taskFuture.cancel(true); // this don't interrupt ConcurrentLinkedQueue
    }
  }
  // clean queue
  this.queue.clear();
}
```

detail see https://github.com/apache/iceberg/pull/7844

**Comment by Heltman** [comment]
In addition, the `ConcurrentLinkedQueue` it use cannot limit the size. When the iceberg table is large, the queue will be too large, which will also cause OOM in the coordinator. This part of the memory is not tracked by trino and cannot be configured to limit. So my submission change `ConcurrentLinkedQueue` to `LinkedBlockingQueue` and adds a parameter `iceberg.iterator.queue-size` so that the client can limit this queue to avoid uncontrollable memory.

**Comment by hashhar** [comment]
FYI @findepi @sopel39

**Comment by findepi** [comment]
Thanks @Heltman for reporting this!
Fixing this will require changes in Iceberg library and I see you're already working on these, thanks!

cc @danielcweeks  @alexjo2144 @findinpath

**Comment by findinpath** [comment]
Should be fixed by https://github.com/apache/iceberg/pull/9402 which will be included in the upcoming `1.6.0` release.

Gist of the change - the `queue` field of `ParallelIterable` class should be cleared now when calling  `IcebergSplitSource.close()`

https://github.com/apache/iceberg/blob/fc213cc3937b4cefbc21beb6d5b47f564c439810/core/src/test/java/org/apache/iceberg/util/TestParallelIterable.java#L130-L133

**Comment by davseitsev** [comment]
https://github.com/apache/iceberg/pull/9402 fixes only half of the problem. We faced same issue when we had problems with files compaction. And we get OOM before the iterator is closed:
![image](https://github.com/trinodb/trino/assets/1793410/d58221fb-a7da-4b3c-980b-29320b97203f)
I described our case in the comment of related issue: https://github.com/apache/iceberg/issues/3179#issuecomment-2220507710
Should we open another issue for Trino to track the progress of the fix for back pressure?

**Comment by raunaqmorarka** [comment]
@davseitsev we think that https://github.com/trinodb/trino/pull/22555 and https://github.com/trinodb/trino/pull/22584 should help to reduce the amount of memory used for file scan tasks from iceberg.
Could you try these patches out and let us know if they help the situation ?

**Comment by raunaqmorarka** [comment]
@davseitsev did those patches help at all ?
This issue should be fully fixed by https://github.com/apache/iceberg/pull/10691
The next iceberg release (1.6.1 or 1.7) will have this fix

**Comment by raunaqmorarka** [comment]
This should be resolved with https://github.com/trinodb/trino/pull/23146
