### ISSUE TITLE
Iceberg OPTIMIZE doesn't write new stats file

### ISSUE THREAD

**Issue by homar** [trinodb/trino#19992]
`ALTER TABLE … EXECUTE OPTIMIZE` doesnt create new `.stats` file and makes existing one invalid - it is not longer used.

This should not be the case. 
Investigate if existing `.stats` file can still be used (it should imho) and use it, or make OPTIMIZE compute a new one

**Comment by pajaks** [comment]
Executing `OPTIMIZE` alone seem to not be problematic as `.stats` from previous snapshot are still read. 
The problem occurs after `EXPIRE_SNAPSHOTS`, when `.stats` are indeed removed.
