### ISSUE TITLE
Error: It is not possible to delete a table from Hive

### ISSUE THREAD

**Issue by dmyar21** [trinodb/trino#20015]
I am creating a table(table_test) in Hive via Trino(434) on behalf of the user "test".
A user without a password.
When I try to delete this table through another user, for example "admin", I get the error "Access Denied: Cannot drop table default.table_test: Owner of the table ('test') is different from session user ('admin')" 
Although the "access-control.name=allow-all" parameter is set in Trino in the access-control.properties section
I can't delete it anyway.
Can you tell me what the problem might be?

**Comment by mosabua** [comment]
See https://trino.io/docs/current/connector/hive-security.html#sql-standard-based-authorization

**Comment by mosabua** [comment]
Or https://trino.io/docs/current/connector/hive.html#data-management

**Comment by ebyhr** [comment]
The table owner and session user must be the same when using legacy access control.
