### ISSUE TITLE
How to run multiple workers in container?

### ISSUE THREAD

**Issue by jonashaag** [trinodb/trino#20017]
I've started 1 coordinator + 1 worker, each in a Podman container. They have different Node IDs, but when I click on the worker UI (`worker.html?<node ID>`) I'm shown the info of the coordinator. The worker is also never used.

Both are show as having the same IP address; maybe that's why the UI confused them? They both are shown as having IP 10.0.2.100 (which is NOT their actual IP, but a special IP by Podman).

**Comment by mosabua** [comment]
Looks like they are completely isolated from each other network wise. How did you deploy them?

**Comment by jonashaag** [comment]
They are not. The worker can connect to the coordinator (but not receive any work). I can ping/telnet between the machines/servers using the correct IPs and ports. But Trino's mechanism of detecting the IP (and maybe port?) seems to be not working here.

**Comment by mosabua** [comment]
There is not detection mechanism.. you need to configure the discovery server URL (and port) in  each node and have that set in config.properties
