### ISSUE TITLE
Confusing names in session property

### ISSUE THREAD

**Issue by oneonestar** [trinodb/trino#20075]
* `max_writer_task_count`
* `task_max_writer_count`

One controls the "maximum number of local parallel table writers per task" and one for "maximum number of tasks".
It's difficult to tell without looking at the doc.

**Comment by raunaqmorarka** [comment]
fyi @sopel39 @gaurav8297

**Comment by findepi** [comment]
The names are not random permutations of same words. There is a logic there, the names are constructed hierarchical.
I agree that them being permutation of each other is confusing and require though process to understand. At the same time, turning this properties definitely requires thought process, they should not be turned by an average user.

I propose that we don't change them.

**Comment by sopel39** [comment]
Decided to keep it as is
