### ISSUE TITLE
Some INSERT statements are ignored with Iceberg

### ISSUE THREAD

**Issue by ricardopereira33** [trinodb/trino#20092]
We noticed a weird issue with Trino version 434 (latest). Some of our users do a lot of `INSERT INTO ...`  in an iceberg table with Trino. However, **when we changed the version from 428 to 434, seems like some inserts are ignored**. It actually writes the file on the object storage, and commits a new snapshot, mentioning that it added X records (we get the same result from the stats in the Trino UI). However, when we query the table, it does not return any records. We tried to query the iceberg table with Spark as well, and it does not return anything. 

<img width="1659" alt="Screenshot 2023-12-11 at 17 18 57" src="https://github.com/trinodb/trino/assets/16037370/0dfec72d-dad5-491a-8553-a0aa0f0e55ed">
<img width="1004" alt="Screenshot 2023-12-11 at 17 15 35" src="https://github.com/trinodb/trino/assets/16037370/864bdcb3-b8da-4d47-98ba-f0ff6335e4a5">
<img width="1330" alt="Screenshot 2023-12-11 at 17 13 28" src="https://github.com/trinodb/trino/assets/16037370/e3da447c-9082-482b-9be2-d624459e7432">

We analysed the metadata and manifest files, and we found out the following:

Until the **sequence-number 15934**, everything was fine. Then we have 2 inserts almost at the same time, that committed 2 new snapshots:
```
29819-ccca636b-3279-4fe2-a733-bc3eed379312.metadata.json  03:56:15
29819-982db761-e158-42ee-8b5e-2c2ac92681ac.metadata.json  03:56:12
```

We can see a pattern on the metadata files where the prefix increments on every new snapshot, but in this case it is the same (not sure if it is expected). Anyway, if we open both metadata files, we can see the reference to the manifests (Avro files), and the latest metadata file includes the previous one, so I guess it could handle the concurrency.

- Last manifest in `29819-982db761-e158-42ee-8b5e-2c2ac92681ac.metadata.json`:
```
 {
    "sequence-number" : 15935,
    "snapshot-id" : 2349488274696194790,
    "parent-snapshot-id" : 4184787990992439919,
    "timestamp-ms" : 1702007762898,
    "summary" : {
      "operation" : "append",
      "trino_query_id" : "20231208_035545_04129_jywup",
      "added-data-files" : "1",
      "added-records" : "14",
      "added-files-size" : "14047",
      "changed-partition-count" : "1",
      "total-records" : "2670050571",
      "total-files-size" : "211155960909",
      "total-data-files" : "36273",
      "total-delete-files" : "1616",
      "total-position-deletes" : "5429420",
      "total-equality-deletes" : "0"
    },
    "manifest-list" : "gs://...b2a6894c12fb.avro",
    "schema-id" : 3
  }
```

- Last manifest in `29819-ccca636b-3279-4fe2-a733-bc3eed379312.metadata.json`:
```
{
    "sequence-number" : 15935,
    "snapshot-id" : 2349488274696194790,
    "parent-snapshot-id" : 4184787990992439919,
    "timestamp-ms" : 1702007762898,
    "summary" : {
      "operation" : "append",
      "trino_query_id" : "20231208_035545_04129_jywup",
      "added-data-files" : "1",
      "added-records" : "14",
      "added-files-size" : "14047",
      "changed-partition-count" : "1",
      "total-records" : "2670050571",
      "total-files-size" : "211155960909",
      "total-data-files" : "36273",
      "total-delete-files" : "1616",
      "total-position-deletes" : "5429420",
      "total-equality-deletes" : "0"
    },
    "manifest-list" : "gs://...b2a6894c12fb.avro",
    "schema-id" : 3
},
{
    "sequence-number" : 15936,
    "snapshot-id" : 6897514136146417222,
    "parent-snapshot-id" : 2349488274696194790,
    "timestamp-ms" : 1702007773563,
    "summary" : {
      "operation" : "append",
      "trino_query_id" : "20231208_035556_04136_jywup",
      "added-data-files" : "1",
      "added-records" : "6",
      "added-files-size" : "14039",
      "changed-partition-count" : "1",
      "total-records" : "2670050577",
      "total-files-size" : "211155974948",
      "total-data-files" : "36274",
      "total-delete-files" : "1616",
      "total-position-deletes" : "5429420",
      "total-equality-deletes" : "0"
    },
    "manifest-list" : "gs://...5cfc3f50c6c9.avro",
    "schema-id" : 3
  } ],
```

When we tried to check the Avro files, we could see the problem. For the commit before these 2 inserts, it has the following information about the **sequence number 15934**:
```
{'avro.schema': ..., 
'avro.codec': b'deflate', 
'snapshot-id': b'4184787990992439919', 
'format-version': b'2', 
'sequence-number': b'15934', 
'iceberg.schema': ...
'parent-snapshot-id': b'7860648970688177621'}
{'manifest_path': 'gs://...954ea5f5a0a0-m0.avro', 'manifest_length': 13879, 'sequence_number': 15934, 'min_sequence_number': 15934, 'added_snapshot_id': 4184787990992439919, ...}
````

However, for the 2 commits we have this on each avro file:

- `gs://...b2a6894c12fb.avro`:
```
{'avro.schema': ..., 
'avro.codec': b'deflate', 
'snapshot-id': b'2349488274696194790', 
'format-version': b'2', 
'sequence-number': b'15935', 
'iceberg.schema': ..., 
'parent-snapshot-id': b'4184787990992439919'}
{'manifest_path': 'gs://...954ea5f5a0a0-m0.avro', 'manifest_length': 13879, 'sequence_number': 15934, 'min_sequence_number': 15934, 'added_snapshot_id': 4184787990992439919, ...}
```

- `gs://...5cfc3f50c6c9.avro`:
```
{'avro.schema': ..., 
    'avro.codec': b'deflate', 
    'snapshot-id': b'6897514136146417222', 
    'format-version': b'2', 
    'sequence-number': b'15936', 
    'iceberg.schema': ..., 
    'parent-snapshot-id': b'2349488274696194790'
}
{'manifest_path': 'gs://...954ea5f5a0a0-m0.avro', 'manifest_length': 13879, 'sequence_number': 15934, 'min_sequence_number': 15934, 'added_snapshot_id': 4184787990992439919, ...}
```

For some reason, it doesn’t include a `-mX.avro`  file for these inserts…

**Comment by findinpath** [comment]
Slack discussion:

https://trinodb.slack.com/archives/CJ6UC075E/p1702376393926019

**Comment by findinpath** [comment]
Snapshot IDs sequence for the table:
`7860648970688177621` -> `4184787990992439919` -> `2349488274696194790`  -> `6897514136146417222`

The snapshots `2349488274696194790` and `6897514136146417222` have:
- an own sequence number (monotonically ascending) :heavy_check_mark: 
- an own manifest list file  :heavy_check_mark: 
- almost identical manifest files :heavy_multiplication_x: 

> it just changed the header, with the sequence number and snapshots ids:

```
{'avro.schema': ..., 
'avro.codec': b'deflate', 
'snapshot-id': b'2349488274696194790', 
'format-version': b'2', 
'sequence-number': b'15935', 
'iceberg.schema': ..., 
'parent-snapshot-id': b'4184787990992439919'}
```

Relevant Trino code:

https://github.com/trinodb/trino/blob/3cbf4986524425d2272b44e2d2287a6ad0beab14/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java#L1088-L1113

Relevant Iceberg code:
https://github.com/apache/iceberg/blob/3112ec91617ef080604f47ac92c255b517458522/core/src/main/java/org/apache/iceberg/SnapshotProducer.java#L226-L244

**Comment by yoniiny** [comment]
@findinpath I think it's probably a regression introduced in Iceberg 1.4. If it's the same issue, here's the relevant PR that should fix it: https://github.com/apache/iceberg/pull/9230

**Comment by findepi** [comment]
@alexjo2144 posted a temporary fix for Trino -- https://github.com/trinodb/trino/pull/20159
thank you Alex!

**Comment by findepi** [comment]
It's disturbing that `io.trino.testing.BaseConnectorTest#testInsertRowConcurrently` didn't catch the problem.
i would expect it to catch it, assuming no special setup is needed for repro.
@yoniiny any idea what were we missing in this test?

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/20159 would fix the problem , but the current plan is to have a better fix (https://github.com/trinodb/trino/pull/20159#issuecomment-1862103585)

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/pull/20207 should address the reported issue.
