### ISSUE TITLE
OpenTelemetry: use trace context from HTTP headers

### ISSUE THREAD

**Issue by NickLarsenNZ** [trinodb/trino#20103]
To make end-to-end tracing from the client through the Trino server complete, the traceId would be generated by the client, and should then be used as the parent.

I believe this is done via Propagators, and I think this might be the relevant example.

https://github.com/open-telemetry/opentelemetry-java-examples/blob/5954e2b66cd8a85fd3045a09917cae99d76ddef1/http/src/main/java/io/opentelemetry/example/http/HttpServer.java#L72-L73

**Comment by nineinchnick** [comment]
This should be already possible, which client are you using, the JDBC driver?

**Comment by NickLarsenNZ** [comment]
Oh cool, I didn't realise.
I was looking at the code in https://github.com/trinodb/trino/pull/16950 and noticed `setNoParent()`, but looking closer I see others with `setParent`.

We're using a custom client and instrumenting it, so I'll take a closer look at propagating the trace ID.

I'll close this now. Thanks for your quick response.
