### ISSUE TITLE
File based access control is blocking dynamic catalog

### ISSUE THREAD

**Issue by vithushanms** [trinodb/trino#20109]
Hi All,

I have used the enabled the dynamic catalogs feature. when I execute the CREATE statement I am getting "Access Denied: Cannot create catalog", although I have set the current user to access .* catalogs privileges under catalogs. are there any other specific permission I need to set in the file based access control JSON?

A quick response would be appreciated!

Regards,
Vithushan

**Comment by maksim77** [comment]
Facing the same problem. I hope there is a solution.

**Comment by Laonel** [comment]
The matched catalog rule must include `owner` as the access mode.

```
{
  "role": "admin",
  "catalog": ".*",
  "allow": ["owner"]
}
```

**Comment by maksim77** [comment]
> The matched catalog rule must include `owner` as the access mode.

That's unexpected :). According to the documentation this field is not even a list, but a string. Nevertheless, thank you. I will definitely try it.

**Comment by Laonel** [comment]
> According to the documentation this field is not even a list, but a string

My bad :) It shouldn't be a list, it should be equal to `owner`.
