### ISSUE TITLE
TimescaleDB federation

### ISSUE THREAD

**Issue by sstamatopoulos** [trinodb/trino#20115]
I am attempting to use Apache Trino to federate multiple TimescaleDBs. However, the query engine does not recognize timescaledb commands that are time related, time_bucket, interval, etc. Is Trino capable to federate such dbs and execute TimescaleDB queries? Attached I provide you an image of a query execution.
![Screenshot 2023-12-14 112802](https://github.com/trinodb/trino/assets/135005757/0ac6e234-6d21-471c-a117-7a10a66148ad)

**Comment by ebyhr** [comment]
You can use `query` pass-though table function when calling non-Trino functions. https://trino.io/docs/current/connector/postgresql.html#query-varchar-table
