### ISSUE TITLE
Slack invite on home page is expired

### ISSUE THREAD

**Issue by spens** [trinodb/trino#20149]
I have tried to join the community, going from https://trino.io/slack.html; however, keep getting error message that "This link is no longer active, To join this workspace, you’ll need to ask the person who originally invited you for a new link.".

Is there a new link to join slack?

Thank you

**Comment by Akanksha-kedia** [comment]
https://trinodb.slack.com/?redir=%2Fssb%2Fsignin_redirect%3Fs%3D1%26v%3D4.35.126%26ssb_vid%3D79d3d8213aae57def9830cc3caa17f28%26ssb_instance_id%3Dd5668cfe-1c00-45a4-b676-bcbd7a9353af%26is_ssb_browser_signin%3D1

**Comment by spens** [comment]
With the link from Akanksha-kedia, Slack asks me to provide my email.  Then it sends me an email saying there is no account on Trino tied to my email address.

**Comment by hashhar** [comment]
@martint @mosabua

**Comment by martint** [comment]
It should be fixed now. Can you try again and let me know if it doesn't work?

**Comment by spens** [comment]
Works!!!  Thank you
