### ISSUE TITLE
Don't supprt "yyyy-MM-dd HH:mm:ss" cast Date type

### ISSUE THREAD

**Issue by everypp** [trinodb/trino#20153]
![image](https://github.com/trinodb/trino/assets/54396288/67eaf4ef-b621-458a-802f-303d7c12b1dd)
trino don't supprt "yyyy-MM-dd HH:mm:ss" cast Date type

**Comment by rlawnsxo098** [comment]
Are you must using date? 
maybe i guess a cast of timestamp solve for your problem.

![image](https://github.com/trinodb/trino/assets/67186984/dbeea5d0-8686-4c55-8601-f918887c19fd)

**Comment by hirolee88** [comment]
date maybe only supports Iso8601Date format   yyyy-MM-dd

**Comment by hirolee88** [comment]
date maybe only supports Iso8601Date format yyyy-MM-dd
yyyy-MM-dd HH:mm:ss is timestamp  See above  @rlawnsxo098

**Comment by hashhar** [comment]
You can do:

```
SELECT CAST(TIMESTAMP '2023-01-01 01:01:01' as DATE);
   _col0
------------
 2023-01-01
(1 row)
```

In your existing query you are casting a varchar to date which isn't a valid cast.

If you don't have a literal value you can use one of the functions from https://trino.io/docs/current/functions/datetime.html, one example being:

```
trino> with t(c) as (values '2023-01-01T01:01:01') select cast(from_iso8601_timestamp(c) as DATE) from t;
   _col0
------------
 2023-01-01
(1 row)
```

or

```
trino> with t(c) as (values '2023-01-01 01:01:01') select cast(date_parse(c, '%Y-%m-%d %H:%i:%s') as DATE) from t;
   _col0
------------
 2023-01-01
(1 row)
```
