### ISSUE TITLE
Fix BigQuery CI timeout

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#20178]
TestBigQueryAvroConnectorTest takes about 50m~. 
```
2023-12-19T18:58:37.6633148Z [WARNING] Tests run: 287, Failures: 0, Errors: 0, Skipped: 77, Time elapsed: 3117 s -- in io.trino.plugin.bigquery.TestBigQueryAvroConnectorTest
```

https://github.com/trinodb/trino/actions/runs/7265705177/job/19796124305

**Comment by nineinchnick** [comment]
I was checking the test report recently and here are some candidates for optimization in `BaseConnectorTest`:
* `testSelectInformationSchemaColumns` takes 10 minutes but executes very few queries - maybe fetching column metadata takes a long time
* `testDataMappingSmokeTest` takes 20s each and is executed for every Trino data type, creating a new temporary table - consider merging this into a single test creating one table with many columns

**Comment by ebyhr** [comment]
Thanks for the helpful information! It seems there're many tables with longer table names (https://github.com/trinodb/trino/pull/20119).

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/7776795611/job/21204415664
