### ISSUE TITLE
We can't able to connect RDS Postgres version 11.19

### ISSUE THREAD

**Issue by vignesh-clustrex** [trinodb/trino#20191]
We are trying to connect  AWS RDS Postgres using trino. We can able to connect Postgres Version 13.10. But when we try to connect Postgres Version 11.19 it is throwing an error like.

`[ERROR] TrinoExternalError: TrinoExternalError(type=EXTERNAL, name=JDBC_ERROR, message="org.postgresql.util.PSQLException: The connection attempt failed.", query_id=20231218_055331_00001_58ggp)`

It will be really helpful if you help us solve this.

Thanks,
Vignesh

**Comment by nineinchnick** [comment]
Can you include the full stack-trace? It should have a more detailed underlying exception.

**Comment by vignesh-clustrex** [comment]
> Can you include the full stack-trace? 

What do you mean by full stack trace ? How to produce it ?

**Comment by nineinchnick** [comment]
You should find it in the server log on the coordinator node. You can also usually get a full stack trace in the client when using the Trino CLI with the `--debug` flag.

**Comment by vignesh-clustrex** [comment]
Sorry, I couldn't get you, can explain a steps to produce this? Since we used trino image to build

**Comment by nineinchnick** [comment]
If you run Trino in a container using Docker, run `docker logs <coordinator-container-id-or-name>`

**Comment by vignesh-clustrex** [comment]
> If you run Trino in a container using Docker, run `docker logs <coordinator-container-id-or-name>`

2023-12-21T09:58:45.139Z        INFO    dispatcher-query-10     io.trino.event.QueryMonitor     TIMELINE: Query 20231221_095835_00003_pz39q :: FAILED (JDBC_ERROR) :: elapsed 10018ms :: planning 10018ms :: waiting 0ms :: scheduling 0ms :: running 0ms :: finishing 0ms :: begin 2023-12-21T09:58:35.116Z :: end 2023-12-21T09:58:45.134Z

Is this the one that you are asking for?

**Comment by nineinchnick** [comment]
No, this is just a log entry for the executed query. There's no multiline stack trace? Can you try using the Trino CLI with the `--debug` flag?

**Comment by nineinchnick** [comment]
You can see that the underlying exception is a:
```
Caused by: java.net.SocketTimeoutException: Read timed out
```
Can you check if you're using different security groups for that RDS instance?

**Comment by vignesh-clustrex** [comment]
> Can you check if you're using different security groups for that RDS instance?

No, we are using the same security group for both the RDS.

**Comment by nineinchnick** [comment]
Can you connect to it from the same host using a different client?

**Comment by vignesh-clustrex** [comment]
No, we are using the same client to connect the both RDS, We only change the catalog name in same client.

**Comment by nineinchnick** [comment]
I mean a Postgresql client, not Trino. You have to verify connectivity outside of Trino

**Comment by vignesh-clustrex** [comment]
It is working when we connect it using pyscopg2.

**Comment by nineinchnick** [comment]
Are you specifying any connection options that are not default values? You have to provide more details in this issue, enough so it can be reproduced.
