### ISSUE TITLE
Support DictionaryBlock for Parquet dictionary encoded columns

### ISSUE THREAD

**Issue by ryanrupp** [trinodb/trino#2020]
The Presto SPI has a `DictionaryBlock` construct which when paired with `DictionaryAwarePageFilter` can optimize out the number of times a filter needs to be applied to just the cardinality of the dictionary instead of processing for every row. For a simple test if I have a single file table with a single string column that has 50 unique values and 100k rows in it and I do:
```
select count(*) from my_table where string_field like 'foo%'
```
For ORC the underlying like regex only has to be evaluated 50 times (once per unique value). In contrast for a dictionary encoded column in Parquet the regex runs 100k times.

Looking into this, the ORC reader generates `DictionaryBlock`s in `SliceDictionaryColumnReader`. It appears that the Parquet reader does not do this currently e.g. when debugging the `DictionaryAwarePageFilter` it's just working on a `VariableWidthBlock`

Parquet column metadata for reference:
```
string_field:  BINARY GZIP DO:0 FPO:4 SZ:74888/75702/1.01 VC:100000 ENC:BIT_PACKED,PLAIN_DICTIONARY,RLE
```

**Comment by ryanrupp** [comment]
https://github.com/prestosql/presto/pull/2333 Updated to parquet-mr 1.11.0 so the API for this should be available now at least

**Comment by raunaqmorarka** [comment]
Will be fixed by https://github.com/trinodb/trino/pull/15269
