### ISSUE TITLE
The memory occupied by trino-coordinator is never released

### ISSUE THREAD

**Issue by A-little-bit-of-data** [trinodb/trino#20285]
![image](https://github.com/trinodb/trino/assets/31812278/ae710f29-f53b-46fd-9912-8621406e22b0)
trino version:430
jvm.config：
-DHADOOP_USER_NAME=hive
-server
-Xmx30G
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+UseGCOverheadLimit
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-XX:+ExitOnOutOfMemoryError
-Djdk.attach.allowAttachSelf=true
-XX:-UseBiasedLocking
-XX:ReservedCodeCacheSize=512M
-XX:PerMethodRecompilationCutoff=10000
-XX:PerBytecodeRecompilationCutoff=10000
-Djdk.nio.maxCachedBufferSize=2000000
-XX:+UnlockDiagnosticVMOptions
-XX:+UseAESCTRIntrinsics
-XX:G1PeriodicGCInterval=10000
-Duser.timezone=Etc/GMT-8

access-control.properties：
access-control.name=file
security.config-file=/etc/trino/rules.json
security.refresh-period=1s

config.properties：
coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8080
query.max-memory=25GB
query.max-memory-per-node=21GB
discovery-server.enabled=true
discovery.uri=http://localhost:8080
query.min-expire-age=3600m
event-listener.config-files=/etc/trino/mysql-event-listener.properties

The above is some basic configuration and version information. I would like to know why the memory usage of trino-coordinator is not released. After restarting, the memory usage decreases, then increases all the way, and restarts after reaching the limit. During the process of memory increase, the cluster has In your free time, has anyone encountered this situation?

```[tasklist]
### Tasks
```

**Comment by atifiu** [comment]
@A-little-bit-of-data I am also observing a similar behavior in my environment, I am using version 405. Were you able to resolve it and how ?
