### ISSUE TITLE
Can't perform Trino Transaction queries in RDS Postgres

### ISSUE THREAD

**Issue by vignesh-clustrex** [trinodb/trino#20286]
We are trying to perform transaction queries in AWS RDS Postgres using Trino. But we can't perform the Transaction queries it throws an error.

`trino.exceptions.TrinoUserError: TrinoUserError(type=USER_ERROR, name=AUTOCOMMIT_WRITE_CONFLICT, message="Catalog only supports writes using autocommit: <catalog-name>", query_id=20240107_063221_00001_66r8c)`

 Postgres Version 13.10 and Trino Version 435.

Here is my Python code:
```
from trino.dbapi import connect
from trino.auth import BasicAuthentication
from trino.transaction import IsolationLevel

with connect(
        host="trino-server-ip",
        port=8080,
        user="user-name",
        auth=BasicAuthentication("user-name", "password"),
        http_scheme="https",
        isolation_level=IsolationLevel.SERIALIZABLE,
        verify=False,
        catalog="catalog-name"
) as conn:
    cur = conn.cursor()
    cur.execute("INSERT INTO sometable VALUES (4, 5, 6)")
```

Here is my catalog config: 
```
connector.name=postgresql
connection-url=jdbc:postgresql://host:5432/db_name?ssl=true
connection-user=postgres
connection-password=password 
```
It will be really helpful if you help us solve this.

Thanks,
Vignesh

**Comment by hashhar** [comment]
Not all connectors support transactions.

Trino tries to emulate transactions on some connectors (e.g. Hive) and hence can't offer it in all connectors.
