### ISSUE TITLE
1.0 * 1 / 21 returns 0.0 in version 435, while it's 0.047619047619047616 in version 407

### ISSUE THREAD

**Issue by ubyyj** [trinodb/trino#20293]
we are working migrating from version 407 to the latest version 435, we found the following breaking behavior:
in version 407:
```
select 1.0 * 1 / 21;
        _col0
----------------------
 0.047619047619047616
```

in version 435:
```
 select 1.0 * 1 / 21;
 _col0
-------
   0.0
```

looks like it's shown as 0.0 if the actual value < 0.05 in version 435.
we expect it returns the exactly same result as version 407 does.

**Comment by martint** [comment]
Also, are you using the `parse-decimal-literals-as-double` configuration option? It was removed in release 428 (https://trino.io/docs/current/release/release-428.html), so if you were relying on it, literals such as `1.0` would start being treated as decimals instead of doubles.

**Comment by ubyyj** [comment]
ah I see, thanks for the info. Yes our current version (407) is running with `parse-decimal-literals-as-double` set to true.

So, in order to make it compatible with the existing behavior, is there any configuration we can set? or do we need to update the SQL?

**Comment by martint** [comment]
Yes, you’ll need to adjust your queries to use the appropriate type. You can do that by changing those literals to scientific notation. E.g., 1e0

**Comment by ubyyj** [comment]
the scientific notation trick is quite helpful, it minimizes the code change.
Thanks again!
