### ISSUE TITLE
where is the location path of  server.log?

### ISSUE THREAD

**Issue by andyliao0508** [trinodb/trino#20379]
hi  i have a problem that I can't solve~
i refer to this website link  => https://trino.io/docs/current/installation/deployment.html?highlight=config%20properties

i use the docker version to deploy trino

set steps according to the document

node.properties file settings are as follows
**node.data-dir=/data/trino**

but the path /data/trino/var/log , i can only see http-request.log

can anyone help me? 
thanks

**Comment by hirolee88** [comment]
Check the launcher.log  to see if the process starts successfully？
see your etc/log.properties  log.output-file=

**Comment by kyungjunleeme** [comment]
hello
this option is not working.
show me your yaml.file

**Comment by andyliao0508** [comment]
> hello this option is not working. show me your yaml.file

config.properties add Reference is as follows:
# server.log
log.path=var/log/server.log
[https://trino.io/docs/current/admin/properties-logging.html#log-path](url)

If you use trino helm chart
[https://github.com/trinodb/charts](url)
 .Values.additionalConfigProperties can be set

**Comment by kyungjunleeme** [comment]
<img width="1043" alt="image" src="https://github.com/user-attachments/assets/1a718e54-66f8-4c4b-bbea-91d5701be695">
