### ISSUE TITLE
Can't query postgres when DB has hyphen - 

### ISSUE THREAD

**Issue by GuguRD** [trinodb/trino#20421]
Trino Version: 436

Using postgres 12 on AWS RDS, we have the database name setup with an hyphen like database-name.
When we try to query: `select * from "database-name".public.table1` it gives me the following error ` Table '"database-name".public.table1' does not exist` but if I do `show tables "database-name".public` it works. 

An I doing something wrong?

**Comment by ebyhr** [comment]
I can't reproduce the issue. Do those identifiers contain uppercase characters in AWS RSD side? Note that Trino lowercase results in `SHOW` statements.

**Comment by GuguRD** [comment]
There is no uppercase just hyphen, let me show you a print:

<img width="723" alt="image" src="https://github.com/trinodb/trino/assets/328346/777d1f6a-4ddc-419b-91f1-b8fa679eec3c">

**Comment by ebyhr** [comment]
@GuguRD Please confirm in AWS RDS without Trino.

**Comment by GuguRD** [comment]
Using DBeaver it works fine connected to the database without Trino.

**Comment by ebyhr** [comment]
@GuguRD I'm asking the case sensitivity, not DBeaver behavior.

**Comment by GuguRD** [comment]
Just to let you know I fixed renaming the database with _ not -, but there is still a problem with the column type, when it is a camel case column type trino says  `ERROR: type "camelcasetype" does not exist` but it should search for `CamelCaseType`. I will open another issue for this
