### ISSUE TITLE
Expose Trino view's columns on the metastore

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#20422]
We currently use a `dummy` column on the metastore when creating / altering a Trino View.

https://github.com/trinodb/trino/blob/a68b609140e205e4004d7cc95945a48861db0958/plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java#L2698-L2705

Use the actual columns of the view in the definition of the table created on the metastore.

cc @electrum

**Comment by MayaCarmon** [comment]
hey :)
Can you pls elaborate what do you mean by using the actual columns of the view?

**Comment by ebyhr** [comment]
I'm not sure if we really want this. What happens if the view definition contains column types which metastore doesn't support?

**Comment by MayaCarmon** [comment]
Like what? 
From my knowledge the metastore support all supported types by trino
