### ISSUE TITLE
launcher.pid is not available after installation

### ISSUE THREAD

**Issue by ashfordm** [trinodb/trino#20447]
-Downloaded
trino-server-436.tar.gz

-Followed exactly
https://trino.io/docs/current/installation/deployment.html

-Error when Launching
PermissionError: [Errno 13] Permission denied: '/opt/trino/data/var/run/launcher.pid'
... the files is missing? Thoughts?

**Comment by ashfordm** [comment]
On it! Thank you!

**Comment by mosabua** [comment]
I sent a PR to update docs.
