### ISSUE TITLE
Oracle Native Encryption support

### ISSUE THREAD

**Issue by PlePato** [trinodb/trino#20453]
Implementing oracle native encryption.
This was solved by https://github.com/trinodb/trino/issues/16812 , the solution was to upgrade oJDBC to version 21, which supports setting encryption setup via jdbc url parameters.
This was reverted by https://github.com/trinodb/trino/pull/19851 , because oJDBC 21 is not LTS. 
Is it possible to implement Oracle Native encyrption with oJDBC 19 by setting the parameters direcly in the java code, getting the needed properties from catalog.properties file?

**Comment by ebyhr** [comment]
The current Oracle JDBC version is 23.3.0.23.09. Let me close.
