### ISSUE TITLE
sqlserver connector won't connect to a db using TLSv1

### ISSUE THREAD

**Issue by eladitzhakian** [trinodb/trino#20473]
Unfortunately l **have** to connect to an SQL server which is "secured" using TLSv1

However Trino doesn't support TLSv1, as it's disabled on JDK level for more than a few years now

Using `encrypt=false` in the connection string doesn't help, I'm still getting a JDBC error saying `TLS10` isn't supported and only `TLS12,TLS13` are acceptable

How can I work around that? I tried removing `TLSv1` from `java.security` file, but then I only got an exception saying `SHA-1` is missing. 

Is there any way to tell the connector to skip TLS validation completely? All of the DSN params I tried failed to do it 

(Using version 437. Also failed with 436 and 390)

**Comment by eladitzhakian** [comment]
## Solution:
* Create a copy of the JDK's `java.security` file, name it `java_tlsv1.security`
* In `java_tlsv1.security` file edit the following:
  * In `jdk.tls.disabledAlgorithms` remove `TLSv1`
  * Set `crypto.policy` to `unlimited`
  * Edit all of the `security.provider.tbd` keys and number them, e.g: `security.provider.tbd=SUN -> security.provider.1=SUN`, `security.provider.tbd=SunRsaSign -> security.provider.2=SunRsaSign` etc
 * Run your app with `-Djava.security.properties=java_tlsv1.security`

**Comment by huv95** [comment]
OMG!
