### ISSUE TITLE
Simple `INSERT INTO SELECT` exceeded memory limit Top Consumers is TableScanOperator

### ISSUE THREAD

**Issue by sj-ganwh** [trinodb/trino#20533]
### Env
- centos-7.8
- trino-server-435
- hadoop-2.7
- hive-2.1

### SQL
src table: parquet uncompress table
dst table: parquet with gzip compression
```sql
set session hive.insert_existing_partitions_behavior='overwrite';
set session use_preferred_write_partitioning=true;
set session task_max_writer_count=1;

insert into dst
select <424 columns> from src;
```

### Error detail
> Query 20240201_092809_00011_xjvtv failed: Query exceeded per-node memory limit of 5GB [Allocated: 4.94GB, Delta: 82.84MB, Top Consumers: {TableScanOperator=4.59GB, LazyOutputBuffer=187.12MB, TableWriterOperator=61.62MB}]

Are there any settings to reduce TableScanOperator memory usage?

**Comment by raunaqmorarka** [comment]
You might benefit from tuning parquet.writer.page-size lower or try out the recently merged https://github.com/trinodb/trino/pull/20171

**Comment by sj-ganwh** [comment]
> You might benefit from tuning `parquet.writer.page-size` lower or try out the recently merged #20171

It seems not working by settings all there:
```sql
set session hive.parquet_max_read_block_size='4MB';
set session hive.parquet_writer_page_size='248576B';
set session hive.parquet_max_read_block_row_count=1024;

set session hive.insert_existing_partitions_behavior='overwrite';
set session use_preferred_write_partitioning=true;
set session task_max_writer_count=1;
```

**Comment by raunaqmorarka** [comment]
I actually meant the parquet writer setting to be tuned for the process writing the source parquet table, that way the reader will be able to reduce it's memory requirements by having smaller parquet pages in memory.
On the reader side, you can try tuning `parquet.max-buffer-size` lower.

**Comment by sj-ganwh** [comment]
> I actually meant the parquet writer setting to be tuned for the process writing the source parquet table, that way the reader will be able to reduce it's memory requirements by having smaller parquet pages in memory. On the reader side, you can try tuning `parquet.max-buffer-size` lower.

It does work. THX
