### ISSUE TITLE
date function is not working as expected

### ISSUE THREAD

**Issue by njalan** [trinodb/trino#20530]
I am using trino 426 and 397 and both are not working.
When I run below query there is no records but actually there are records on for 2024-02-01. But If I check the date before today(2024-02-01) and it is working correctly. I checked many tables and all the the other table are working file. Only this  table can't see the data on for today. 

 
select  
from hive.xxx.xxx
where  date(created_datetime) = date('2024-02-01')
 order by created_datetime desc
limit 10

**Comment by njalan** [comment]
why below timezone is hardcode in methond from  TupleDomainParquetPredicate (trino 397 and 406)
 TrinoTimestampEncoder<?> timestampEncoder = createTimestampEncoder((TimestampType) type, DateTimeZone.**UTC**);

**Comment by Heltman** [comment]
Trino's timestamp type use UTC timezone, so it's always use UTC. In order to be compatible with hive, it use local timezone in HiveConifg like below:
```java
private String parquetTimeZone = TimeZone.getDefault().getID();
```
You mention hardcode in methond from `TupleDomainParquetPredicate`, because it is INT64 type which can't contain timezone. Hive's timestamp type use INT96 type in Parquet, it will use local timezone. 
```java
if (column.getPrimitiveType().getPrimitiveTypeName().equals(INT96)) {
    TrinoTimestampEncoder<?> timestampEncoder = createTimestampEncoder((TimestampType) type, timeZone);
    ...
    }
if (column.getPrimitiveType().getPrimitiveTypeName().equals(INT64)) {
    ...
    TrinoTimestampEncoder<?> timestampEncoder = createTimestampEncoder((TimestampType) type, getSparkTimestampTimezone().orElse(DateTimeZone.UTC));
    ...
```

About you issue, please add more information.

**Comment by hashhar** [comment]
If you somehow wrote non-UTC timestamps then you can change `hive.parquet.time-zone`/`hive.orc.time-zone`/`hive.rcfile.time-zone` config properties to adjust.

However it's much better to simply store UTC since the Int64 encoding doesn't store timezones.
