### ISSUE TITLE
Add mechanism to get metadata file location of Iceberg table

### ISSUE THREAD

**Issue by jkylling** [trinodb/trino#20584]
It should be possible to get the location of the current metadata file of an Iceberg table. The location of the metadata file is often required when registering an Iceberg table in another system without a common Iceberg catalog. For instance, [Trino](https://trino.io/docs/current/connector/iceberg.html#register-table) needs the metadata file location when registering a table.

It does not look like any of the existing system tables for Iceberg returns the location of the current metadata file. Should we add another system table `"table$metadata_file_location"`, with a single column `metadata_file_location`, and a single row with the metadata file location?

An alternative to such a specific table could be to have something like a general metadata table for an iceberg table (e.g., we could show most of the content of https://iceberg.apache.org/spec/#table-metadata-fields). Perhaps the existing `$properties` table could be re-used.

A third alternative, would be to extend the existing `$snapshots` table to include the a column `metadata_file_name`, with value the metadata file containing each snapshot.

**Comment by oneonestar** [comment]
How about this?
https://github.com/trinodb/trino/pull/20410
