### ISSUE TITLE
Mongo "admin" database not visible in schema list

### ISSUE THREAD

**Issue by shubhshah01** [trinodb/trino#20608]
While trying to configure mongodb even using root and admin users having appropriate permissions to "admin" database, trino is not reading admin database.
when I see schema list using SHOW SCHEMAS in mongo i don't see "admin" in the list, I can see other databases listed.

If this is a limitation from mongo, Is there any workaround to be able to access admin db collections via trino ? or If not all collections can specific collections be accessed ?

Tried following Mongo "admin" user roles - root, dbOwner, userAdminAnyDatabase.

Trino version - latest
Mongo version - latest

**Comment by ebyhr** [comment]
The connector hides internal databases - admin, local and config 

https://github.com/trinodb/trino/blob/04910737c74f9eb3432a50d7699c98793759aa94/plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java#L133
