### ISSUE TITLE
BigQuery connector is not passing the credentials downstream after upgrade from 400->437

### ISSUE THREAD

**Issue by PuszekSE** [trinodb/trino#20729]
I've upgraded a Trino instance from 400 to the 437 and it seems like after that operation the secret we're loading as have stopped working.

For the context, right after the trino version upgrade, the new deployment failed with:
`1) [Guice/ErrorInjectingConstructor]: IllegalArgumentException: Illegal base64 character a at StaticBigQueryCredentialsSupplier.<init>(StaticBigQueryCredentialsSupplier.java:41) while locating StaticBigQueryCredentialsSupplier [...]`

Reverting back to 400 without any changes in the secret itself resolved this error.

Initially I have thought, that maybe something is wrong with how the env is defined, but I've verified contents of ENV being present and proper reference in the <connector>.properties file was also set (I've directly checked on the live trino coordinator pod).

Afterwards I've compiled custom trino-bigquery jar adding log.debug(key) into `StaticBigQueryCredentialsSupplier` - apparently after upgrading to 437, the key value passed to the Credentials' Supplier ended up being empty.

**Comment by ebyhr** [comment]
https://trinodb.slack.com/archives/CGB0QHWSW/p1708045342998539
