### ISSUE TITLE
Add integration tests for Azure file system based on Azurite

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#20780]
Using https://github.com/Azure/Azurite may be a handy alternative to test `trino-filesystem-azure`.
This wouldn't replace the tests against the actual Azure storage, but it would probably accelerate development & testing in regards to integration with Azure.

**Comment by dain** [comment]
Azureite does not implement the Azure APIs correctly, and leads to code that works on Azureite, but fails on real Azure.  I filed some issues with them but they do not have the budgets to complete the implementation.  So, even though this is pretty straight forward to implement, I don't think we should.
