### ISSUE TITLE
[Kafka-Connector] How to read avro format using Kafka Connector

### ISSUE THREAD

**Issue by BePPPower** [trinodb/trino#20808]
I'm trying to read data in `Avro` format stored in Kafka using `Kafka Connector,`
But I always read it as `NULL`. I think it must be that the way I use is wrong. Can anyone help me see?

Here is my kafka.properties:
```
connector.name=kafka
kafka.table-names=avro.topic1
kafka.nodes=localhost:9092
kafka.hide-internal-columns=false
```

The avro schema is：avro_data2.avsc
```json
{
    "type":"record",
    "name":"myrecord",
    "fields":[
         {"name":"f1","type":"string"}
    ]
}
```

And my file table description is:
```json
{
    "tableName": "topic1",
    "schemaName": "avro",
    "topicName": "topic1",
    "key": {
        "dataFormat": "raw",
        "fields": [
            {
                "name": "key1",
                "dataFormat": "BYTE",
                "type": "VARCHAR",
                "hidden": "false"
            }
        ]
    },
    "message": {
	"dataSchema": "/mnt/datadisk1/fangtiewei/tmpdata/tmo/avro_data2.avsc",
	"dataFormat": "avro",
        "fields": [
            {
                "name": "f1",
                "type": "VARCHAR",
                "mapping": "f1"
            }
        ]
    }
}
```

When I query this table in trino, the f1 field is `NULL`. (the number of rows is correct)
```
key1 |  f1  | _partition_id | _partition_offset | _message_corrupt | _message | _headers | _message_length | _key_corrupt | _key | _key_length |       _timestamp
------+------+---------------+-------------------+------------------+----------+----------+-----------------+--------------+------+-------------+-------------------------
 key1 | NULL |             0 |                 0 | true             | ^@^@^@^@^B^Lvalue1   | {}       |              12 | false        | key1 |           4 | 2024-02-22 13:11:19.309
```

Is there anything wrong with my configuration above?

**Comment by hashhar** [comment]
`_message_corrupt` is true which indicates the message couldn't be deserialized.

How is the Avro data on Kafka serialized? Through some schema registry? Or the Avro single-object encoding (i.e. schema embedded in message).

Note that we don't support reading schemaless Avro messages.

I can help verify this for you if you can share output of:

```
kcat -C -b <broker>:<port> -t <topic_name> -o _partition_offset -p _partition_id -c1 | hexdump -C
```

replace `_partition_offset` and `_partition_id` with the value from the query output.

**Comment by BePPPower** [comment]
> `_message_corrupt` is true which indicates the message couldn't be deserialized.
> 
> How is the Avro data on Kafka serialized? Through some schema registry? Or the Avro single-object encoding (i.e. schema embedded in message).
> 
> Note that we don't support reading schemaless Avro messages. From https://trino.io/docs/current/connector/kafka.html#avro-decoder
> 
> > The message must have the Avro schema embedded. Trino does not support schemaless Avro decoding.
> 
> I can help verify this for you if you can share output of:
> 
> ```
> kcat -C -b <broker>:<port> -t <topic_name> -o _partition_offset -p _partition_id -c1 | hexdump -C
> ```
> 
> replace `_partition_offset` and `_partition_id` with the value from the query output.

hi, hashhar, thank you for your reply.
I used the Schema Registry service of confluent 7.5.2 to serialize the avro data. Can't I use Schema Registry？
And my kcat command output is:
```shell
$ ./kcat -C -b localhost:9092 -t topic1 -o 0 -p 0 -c1 | hexdump -C
00000000  00 00 00 00 02 0c 76 61  6c 75 65 31 0a           |......value1.|
0000000d
```

**Comment by hashhar** [comment]
For confluent schema registry you can't use file based table descriptions.

See https://trino.io/docs/current/connector/kafka.html#confluent-table-description-supplier for how to configure Kafka connector for confluent schema registry integration.

**Comment by BePPPower** [comment]
> For confluent schema registry you can't use file based table descriptions.
> 
> See https://trino.io/docs/current/connector/kafka.html#confluent-table-description-supplier for how to configure Kafka connector for confluent schema registry integration.

Hi, hashhar, thank you for your reply.

That solved my question perfectly! Thanks again!

**Comment by hashhar** [comment]
Glad to hear that.
