### ISSUE TITLE
Returns scientific notation when converting double to varchar

### ISSUE THREAD

**Issue by yuansiyong** [trinodb/trino#20823]
Trino 412 version

When querying a hive table and converting a field of type double to varchar, the query result is in scientific notation format;

The expected result is returned when converting first to decimal(10,1) and then to varchar;

<img width="456" alt="1708670509900_76755942-EE3B-49cd-A594-E0ED64C62D08" src="https://github.com/trinodb/trino/assets/21075164/9c07432a-7900-4957-98ba-6ea79b6e04df">

Is this normal, and is there any way to convert double to varchar directly?

**Comment by hashhar** [comment]
see https://trino.io/docs/current/functions/conversion.html#format

`SELECT format('%f', pi());` for example.

**Comment by yuansiyong** [comment]
Okay, thanks a lot.
