### ISSUE TITLE
Trino client and jdbc driver, kerberos authentication doesn't work with IBM java

### ISSUE THREAD

**Issue by PlePato** [trinodb/trino#20835]
Unable to use Trino JDBC driver on a machine with IBM java to login to keberized trino.
Right now the Trino client kerberos authentication is dependentent on a sun java package for keberos authentication.

https://github.com/trinodb/trino/blob/master/client/trino-client/src/main/java/io/trino/client/auth/kerberos/LoginBasedUnconstrainedContextProvider.java#L18

**Comment by wendigo** [comment]
It was never suppose to work with IBM java

**Comment by PlePato** [comment]
is it possible to make it work with IBM java? Even if we had to compile it by ourselves

**Comment by wendigo** [comment]
@PlePato everything is possible but it's a matter of testing and we don't have access to IBM JDK.

**Comment by PlePato** [comment]
Thanks for replies @wendigo . I managed to compile a version of client and jdbc connector that works with IBM java for krb authentication. I am not sure if it's a feature that you would like to have in trino OSS. 

Just for information for anyone else in future looking for this. 
I am pasting here the code snippet and some information how to get the TrinoClient and JDBC connector work with IBM java. 
File needed to change LoginBasedUnconstrainedContextProvider.java

Following code works only with IBM java, can be rewritten to work with both IBM java and sun java. 
The option options.put("credsType", "initiator"); is used as a constant, because there is no JDBC URI parameter in Trino for this. 
For anyone else trying to make this run, please refer to following link, when to use this parameter as initiator, acceptor or both and how to set up the keytab and credentialCache accordingly https://www.ibm.com/docs/en/i/7.2?topic=applications-jaas-kerberos-login-interface

@wendigo please feel free to close this issue, or comment if you would like to get this in Trino - I am not a Java developer, so I am not sure if I would be able to create a proper Pull Request for such a change.

```
try {
            loginContext = new LoginContext("", null, null, new Configuration()
            {
                @Override
                public AppConfigurationEntry[] getAppConfigurationEntry(String name)
                {
                    ImmutableMap.Builder<String, String> options = ImmutableMap.builder();
                    options.put("credsType", "initiator");
                    options.put("forwardable", "false");

                    if (getBoolean("trino.client.debugKerberos")) {
                        options.put("debug", "true");
                    }

                    keytab.ifPresent(file -> options.put("useKeytab", file.toURI().toString()));

                    credentialCache.ifPresent(file -> options.put("useCcache", file.toURI().toString()));

                    principal.ifPresent(value -> options.put("principal", value));

                    return new AppConfigurationEntry[] {
                            new AppConfigurationEntry("com.ibm.security.auth.module.Krb5LoginModule", REQUIRED, options.buildOrThrow())
                    };
                }
            });

            loginContext.login();
        }
        catch (LoginException e) {
            String keytabPath = keytab.map(File::getAbsolutePath).orElse("not defined");
            String credentialCachePath = credentialCache.map(File::getAbsolutePath).orElse("not defined");
            String principalValue = principal.orElse("not defined");

            throw new ClientException(format("Kerberos login error for principal [%s], keytab [%s], credential cache [%s]: %s", principalValue, keytabPath, credentialCachePath, e.getMessage()), e);
        }
```
