### ISSUE TITLE
Trino 380 cannot verify JWT Audience

### ISSUE THREAD

**Issue by cain129** [trinodb/trino#20868]
Hello,

We have a Apache Airflow instance that runs queries on trino and authenticates using a service account token managed by K8s. JWT authentication is enabled on trino and we can verify that it does work to authenticate in this way.

The problem came up when we tried to verify in trino and airflow that the jwt audience is "Trino".

We are using this Helm chart: https://github.com/valeriano-manassero/helm-charts -- version 2.7.0 with trino version 380

We have these extraConfigs set:

extraConfig: |-
      http-server.https.enabled=true
      http-server.https.port=8043
      http-server.process-forwarded=true
      http-server.https.keystore.path=PATH/FILE.jks
      http-server.https.keystore.key=password
      http-server.https.truststore.path=PATH/FILE.jks
      http-server.https.truststore.key=password
      http-server.authentication.type=JWT,OAUTH2
      http-server.authentication.oauth2.issuer=keycloak
      http-server.authentication.oauth2.client-id=trino
      http-server.authentication.oauth2.client-secret=SECRET
      http-server.authentication.oauth2.auth-url=keycloak
      http-server.authentication.oauth2.token-url=keycloak
      http-server.authentication.oauth2.jwks-url=keycloak
      http-server.authentication.oauth2.userinfo-url=keycloak
      http-server.authentication.oauth2.principal-field=name
      http-server.authentication.jwt.key-file=http://localhost:8001/openid/v1/jwks
      http-server.authentication.jwt.required-audience=Trino # line that causes issue
      http-server.authentication.allow-insecure-over-http=true
      web-ui.authentication.type=oauth2
      web-ui.enabled=true

Airflow gives us the following error:
Expected aud claim to be: trino-dev, but was: [trino-dev]

Trino Documentation for JWT Audience: 
http-server.authentication.jwt.required-audience | Specifies a string that must match the value of the JWT’s Audience (aud) field in order to consider this JWT valid. The aud field in the JWT identifies the recipients that the JWT is intended for

Trino can ony authenticate a single audience, however Helm/K8s make audiences an array.

**Comment by kfox1111** [comment]
I think the issue is in the implementation of requried-audience. Reading: https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3 

Trino should accept the required-audience as specified in the jwt as an array of the one value and not just a string?
