### ISSUE TITLE
Trino 439 and Postgres Connector: It takes more planning time when query has limit clause for very small dataset

### ISSUE THREAD

**Issue by RealDeanZhao** [trinodb/trino#20883]
For query with limit clause, it took  2 seconds to get the data :
`
select * from pg12test.public."binary_cd0802e1cd7d4a068e25d248bb534bae"
order by f_8f30e9f8678c24496921bebae6ca2ac6
limit 100
`

Resource Group | global
-- | --
Submission Time | 2024-02-29 8:30pm
Completion Time | 2024-02-29 8:30pm
Elapsed Time | 2.24s
Queued Time | 672.89us
Analysis Time | 23.27ms
Planning Time | 2.17s
Execution Time | 2.22s

For query without limit clause, it took 100ms to get the data:
`
select * from pg12test.public."binary_cd0802e1cd7d4a068e25d248bb534bae"
order by f_8f30e9f8678c24496921bebae6ca2ac6
`

Resource Group | global
-- | --
Submission Time | 2024-02-29 8:33pm
Completion Time | 2024-02-29 8:33pm
Elapsed Time | 164.57ms
Queued Time | 957.91us
Analysis Time | 26.90ms
Planning Time | 7.41ms
Execution Time | 136.57ms

**Comment by hashhar** [comment]
I cannot reproduce this.

do you have metadata caching enabled?

Also does the faster query change if you reverse the order: i.e. run query without limit first and then query with limit?

**Comment by RealDeanZhao** [comment]
> I cannot reproduce this.
> 
> do you have metadata caching enabled?
> 
> Also does the faster query change if you reverse the order: i.e. run query without limit first and then query with limit?

1. Metadata cache is not enabled(I use the default connector config).
2. The faster query not change. The one with limit is always much slower.

I also tried to ```explain analyze``` these two query, they both took more than 2 seconds to finish,.

**Comment by RealDeanZhao** [comment]
It slow because there are too many tables in the database..
