### ISSUE TITLE
Add a `timezone(timestamp(p) with time zone) -> varchar` extraction function to get IANA timezone ID

### ISSUE THREAD

**Issue by stephen-zhao** [trinodb/trino#20893]
### Request
Similar to the `current_timezone()` function which returns the timezone of the current session, it would be nice to generalize this to allow extraction of timezone info from any provided `timestamp(p) with time zone`. Currently there are already functions to get timezone offsets (`extract(TIMEZONE_HOUR from x)` and `extract(TIMEZONE_MINUTE from x)`), but this loses information about the actual timezone. A lossless extraction function that would return the IANA timezone ID would be ideal.

### Workaround
You can cast the `timestamp(p) with time zone` to a string, and manually extract the suffix.

**Comment by hashhar** [comment]
cc: @martint

**Comment by ebyhr** [comment]
The argument for `EXTRACT` is defined in SQL standard:
```
<time zone field> ::=
    TIMEZONE_HOUR
  | TIMEZONE_MINUTE
```

Is `format_datetime` function sufficient in your use case?
```sql
SELECT format_datetime(TIMESTAMP '2001-01-09 13:04:05.321 Asia/Tokyo', 'ZZZ');
   _col0
------------
 Asia/Tokyo
```

**Comment by martint** [comment]
Apologies for the delay. This is a reasonable request. To keep alignment with existing extraction functions (https://trino.io/docs/current/functions/datetime.html#convenience-extraction-functions), we should define it as:

```
timezone(<timestamp(p) with time zone>) -> varchar
timezone(<time(p) with time zone>) -> varchar
```

**Comment by PhNorberg** [comment]
Can I try this out?:)

**Comment by hashhar** [comment]
@PhNorberg Go ahead. Feel free to link your PR to this issue once you have it. Or ask on Slack for help.

**Comment by PhNorberg** [comment]
Hi, follow up on this issue.
What if the input is UTC/CET or some other time zone abbrevation (or even offsets like +01:00), and not like Europe/Copenhagen or Asia/Tokyo? Should this method then catch an error?
