### ISSUE TITLE
Use AWS's Redshift JDBC driver in redshift connector

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#2094]
We should replace old postgresql driver
https://github.com/prestosql/presto/blob/ec35f58a01b26f12bdd44e39523d6c574953872b/presto-redshift/pom.xml#L45-L50

with Redshift-specific
https://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html

**Comment by ebyhr** [comment]
I guess we need to contact them to distribute JDBC driver. What do you think about it?
> If you need to distribute these drivers to your customers or other third parties, please send email to redshift-pm@amazon.com to arrange an appropriate license.

**Comment by ebyhr** [comment]
Probably, they removed the above limitation and published in https://github.com/aws/amazon-redshift-jdbc-driver. 
(The maven repository is mulesoft)
