### ISSUE TITLE
Don't populate _schema if the collection is empty in MongoDB connector

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#20972]
The connector stores an empty field in _schema collection when the target collection doesn't have any data:
```
mongosh> db.createCollection("test_empty")

trino> SELECT * FROM "_schema" where "table" = 'test_empty';
   table    | fields
------------+--------
 test_empty | []

trino> SELECT * FROM test_empty;
Query 20240307_085207_00043_cqthw failed: line 1:8: SELECT * not allowed from relation that has no columns
...
```

SELECT keeps failing even after inserting data into the collection in MongoDB:
```
mongosh> db.test_empty.insertOne({
     name: "John Doe",
     age: 30,
     email: "john@example.com"
 });

trino> SELECT * FROM test_empty;
Query 20240307_085315_00044_cqthw failed: line 1:8: SELECT * not allowed from relation that has no columns
```

**Comment by build2create** [comment]
@ebyhr  Can I pick this up? Was just going through the code will there be a check before inserting metadata?
[code_ref](https://github.com/trinodb/trino/blob/abed9df4737d412f6d80e84fac57aab9dc76896e/plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java#L860)

To fix I was thinking to add a check as below:
```
fields.addAll(columns.stream()
                .map(MongoColumnHandle::getDocument)
                .collect(toList()));
```
to 

```
fields.addAll(columns.stream()
                .map(MongoColumnHandle::getDocument)
                .collect(toList()));

if(fields.isEmpty()) 
{
// return from the function  logging a message
}
```

**Comment by ebyhr** [comment]
Sure, please feel free to send the RP. Don't forget including the test. I think just changing the following line in `guessTableFields` method is sufficient:
```java
        if (doc == null) {
↓
        if (doc == null || doc.isEmpty()) {
```

**Comment by build2create** [comment]
Hi @ebyhr  I did raise a PR here but writing test case specifically for this condition seems a bit overhead given method is private. Is there any existing test case that covers this branch already? I was going through the `TestMongoSession` but couldn't find any test case that covers this path. 

PR link: https://github.com/trinodb/trino/pull/21236

**Comment by build2create** [comment]
Hi @ebyhr  is it expected for `_schema` to have an entry for the collection once there is a document within it? If so I was writing a test case as such:
```
        String tableName = "test_empty";
        MongoDatabase database = client.getDatabase("test");
        database.createCollection(tableName);
        assertQueryReturnsEmptyResult("SELECT * FROM \"_schema\" where \"table\" = 'test_empty'");

        database.getCollection(tableName).insertOne(new Document(ImmutableMap.of("k", "v")));
        assertQueryReturnsEmptyResult("SELECT * FROM \"_schema\" where \"table\" = 'test_empty'");
```

But the second assert also passes. Which makes me think if the check for `doc.isEmpty()` sufficient or do we need to modify some place else as well?

**Comment by ebyhr** [comment]
The SELECT should read from test_empty instead of _schema collection.

**Comment by build2create** [comment]
No so my point is if we populate the `test_empty` collection should there be an entry in `_schema` collection as well?

**Comment by ebyhr** [comment]
> test_empty collection should there be an entry in _schema collection as well?

The entry should exist after the first access.

**Comment by build2create** [comment]
Okay thanks for clarifying. Now I modified the test case but I still feel just adding the `doc.isEmpty()` is insufficient.
Because with this fix if I execute
```
        String tableName = "test_empty";
        MongoDatabase database = client.getDatabase("test");
        database.createCollection(tableName);
        MaterializedResult result = getQueryRunner().execute(getSession(), "SELECT * FROM mongodb.test." + tableName);
        assertThat(result.getRowCount()).isEqualTo(0);

```
It throws

```
TestMongoConnectorTest.testEmptyCollection:167 » QueryFailed line 1:8: SELECT * not allowed from relation that has no columns

```

**Comment by build2create** [comment]
@ebyhr any thoughts on the above?

**Comment by ebyhr** [comment]
The exception is the expected behavior because `test_empty` is an empty.
