### ISSUE TITLE
Problem with IF ELSE in SQL routines

### ISSUE THREAD

**Issue by ahop1** [trinodb/trino#20995]
I have been working in Dune analytics (dune.com) (which uses Trino SQL) and have been using a few "WITH FUNCTION... SELECT" statements and I've noticed something pretty weird... Minimal example showing the problem is below.

The following code returns 'default' when I would expect it to return 'output 3':
```
WITH FUNCTION check_basic_if_else()
    RETURNS varchar
    BEGIN
        DECLARE output varchar DEFAULT 'default';
        IF FALSE THEN
            SET output = 'output 1';
        -- ELSEIF FALSE THEN
        --     RETURN 'output 2';
        ELSE
            SET output = 'output 3';
        END IF;
        RETURN output;
    END
SELECT check_basic_if_else()
```
I'm guessing this might be an issue with Trino SQL rather than Dune specifically (?) which is why I'm raising it here. Have also raised on their discord in case it is specific to them (https://discord.com/channels/757637422384283659/1215713076100341781/1215713078390292603).

Other observations:
1) Uncommenting the "ELSEIF" lines results in the expected output.
2) Replacing "IF" with "CASE WHEN" (and "END IF" with "END CASE") also gives the expected output. It seems like the issue is specifically when using this syntax of IF/ELSE, which as far as I know only applies to SQL routines.

**Comment by wendigo** [comment]
This should be fixed by https://github.com/trinodb/trino/commit/dc73c859c24fcbd2f8a8f86d34a86e8180147368

@alexjo2144 ptal and confirm

**Comment by ahop1** [comment]
Okay thanks for the speedy response, so it's on the team at Dune to "upgrade their version of Trino"? Is that what I should tell them?

**Comment by wendigo** [comment]
Yes. Once 440 is out

**Comment by wendigo** [comment]
440 was released
