### ISSUE TITLE
Persist the user into the snapshot summary for iceberg tables

### ISSUE THREAD

**Issue by nikita-sheremet-java-developer** [trinodb/trino#21010]
This feature request very similar to [Persist the Trino query ID into the snapshot summary](https://github.com/trinodb/trino/pull/15576/files#top). The idea is the same but add user that running query to summary. For now it is imposible (as I understand) to answer: "Whats user made change for this snapshot in iceberg table".

**Note**

I have searched usage `io.trino.plugin.hive.HiveMetadata#TRINO_QUERY_ID_NAME` in the sources - so as I understand:

1. `user` of query can be taken from `io.trino.spi.connector.ConnectorSession#getUser`
2. `user` must be set whenevery `queryId` is set
3. Code change is "just" add new property "near" queryId setting?

Am I right? If yes may I try to implement the feature? It looks like very simple for implementation.

Thanks in advance

**Comment by electrum** [comment]
Your understanding sounds correct. This should be very easy to implement. Go for it!
