### ISSUE TITLE
Delta Lake: Can't find files within partition values containing forward slashes on ABFS

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#21019]
Trino fails to correctly encode partition values containing `/` forward slashes leading to the interpretation of these values as directory path `a/b` instead of `a%2Fb`.

Happens for both hdfs as well as native Trino filesystem clients on 

Reproduction test:

```
    @Test
    public void testForwardSlashUriDecoding()
    {
        String tableName = "test_uri_table_" + randomNameSuffix();
        assertUpdate("CREATE TABLE " + tableName + " (a int, part varchar) " +
                "WITH (location = '" + getLocationForTable(bucketName, tableName) + "', partitioned_by = ARRAY['part'])");
        assertUpdate("INSERT INTO " + tableName +" VALUES (1, 'a/b')", 1);
        assertQuery("SELECT * FROM " + tableName, "VALUES (1, 'a/b')");
        assertUpdate("DROP TABLE " + tableName);
    }
```

With Hadoop Azure client
```
 Error opening Hive split abfs://mycontainer@myaccount.dfs.core.windows.net/test-delta-lake-integration-smoke-test-2lahwkcrwm/test_uri_table_5scpbv8ob5/part=a/b/20240311_222416_00002_pt7sn_c67d055f-3333-42eb-b1c7-144819482862 (offset=0, length=197): abfs://mycontainer@myaccount.dfs.core.windows.net/test-delta-lake-integration-smoke-test-2lahwkcrwm/test_uri_table_5scpbv8ob5/part=a/b/20240311_222416_00002_pt7sn_c67d055f-3333-42eb-b1c7-144819482862
```

With Trino Azure client
```
Error opening Hive split abfs://mycontainer@myaccount.dfs.core.windows.net/test-delta-lake-integration-smoke-test-q8p6vo14ph/test_uri_table_q3yvouc7bm/part=a/b/20240311_221601_00002_vp7k5_8539d5d1-7d29-4bcb-a7f3-98001c50b102 (offset=0, length=197): abfs://mycontainer@myaccount.dfs.core.windows.net/test-delta-lake-integration-smoke-test-q8p6vo14ph/test_uri_table_q3yvouc7bm/part=a/b/20240311_221601_00002_vp7k5_8539d5d1-7d29-4bcb-a7f3-98001c50b102
```

**Current status**

`abfs://mycontainer@myaccount.dfs.core.windows.net/test-delta-lake-integration-smoke-test-q8p6vo14ph/test_uri_table_q3yvouc7bm/part=a/b/20240311_221601_00002_vp7k5_8539d5d1-7d29-4bcb-a7f3-98001c50b102`

**Expected status**

`abfs://mycontainer@myaccount.dfs.core.windows.net/test-delta-lake-integration-smoke-test-q8p6vo14ph/test_uri_table_q3yvouc7bm/part=a%2Fb/20240311_221601_00002_vp7k5_8539d5d1-7d29-4bcb-a7f3-98001c50b102`

### Related issues 

Relates to https://github.com/trinodb/trino/pull/15381
This is caused by the encoding handling reported in  https://issues.apache.org/jira/browse/HADOOP-18580

cc @dain  @ebyhr

**Comment by findepi** [comment]
is https://github.com/trinodb/trino/pull/15381#discussion_r1047325305 related?
do we still have abfs-specific code in Delta connector?

**Comment by findinpath** [comment]
> is https://github.com/trinodb/trino/pull/15381#discussion_r1047325305 related?

Yes, see https://github.com/trinodb/trino/pull/21030 - goes in the same direction :(
