### ISSUE TITLE
fs.cache.enabled=false prevents server start up if other required fields are set

### ISSUE THREAD

**Issue by Sartan4455** [trinodb/trino#21061]
If enabling caching, the directories and max-sizes(or percentage) are required.

> fs.cache.enabled=true
> fs.cache.directories=/data/trino/cache
> fs.cache.max-sizes=50GB

However, setting fs.cache.enabled=false prevents server from starting up if the directories or max-sizes is set.  There is no point in fs.cache.enabled=false if you can't set the other config options. 

> fs.cache.enabled=false
> fs.cache.directories=/data/trino/cache
> fs.cache.max-sizes=50GB

> 024-03-13T22:48:51.860Z	ERROR	main	io.trino.server.Server	Configuration errors:
> 
> 1) Error: Configuration property 'fs.cache.directories' was not used
> 
> 2) Error: Configuration property 'fs.cache.max-sizes' was not used

This is unexpected and goes against what other options do, such as spill.
For example, this doesn't prevent start up of server

> spill-enabled=false
> spiller-spill-path=/data/trino/spill

**Comment by mosabua** [comment]
So you are saying it should just send a warning rather than produce an error. Are you planning to send a PR for that?

**Comment by mosabua** [comment]
Just had a discussion with @martint and @dain  -- essentially the behavior with `fs.cache` is correct, and the behavior with `spill-enabled` is a bug.

**Comment by Sartan4455** [comment]
I do no see what is wrong with conditional settings that are ignored?  To me, that's not an uncommon thing for config files.   Then again, neither is comment out options. :)

I did indeed comment them out because the server errored.  But what's the point of = false if = false and comment out are the same?

To me these 4 are equivalent
`cache.enabled = false`
`# cache.enabled = false`
`# cache.enabled = true`
`<nothing>`


The only difference is  the  first one causes the server to not start if other settings are set. 
I was thinking no warnings or errors.   
cache.enabled is there and true, check for required fields.
If not,  ignore those required fields.
By commenting them out, that's a sign they are not needed.  Then if they are removed potentially valuable information(the directory/size and other settings) could be lost.    However I can see if they were old bad settings they'd might silently just work.  

I am fine with either way really.  It just seemed odd to me, thus the bug.

**Comment by wendigo** [comment]
Setting spill configuration when spill is disabled is a bug, not the other way around

**Comment by mosabua** [comment]
There is really no right answer with this .. and the Trino convention is as implemented for caching. I will therefore close this bug. If anyone wants to send a PR to fix the behavior for spilling .. that would be good but can be tracked separately.
