### ISSUE TITLE
Trino Google sheet connector no DELETE UPDATE SQL support 

### ISSUE THREAD

**Issue by cw1427** [trinodb/trino#21100]
As per title, Google sheet connector can only support for SELECT INSERT, but not able to have DELETE UPDATE

trino.exceptions.TrinoUserError: TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="This connector does not support modifying table rows", query_id=20240315_065508_00093_8qrwr)

**Comment by gauravknu10** [comment]
Same Issue with Postgres Connector.
TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="This connector does not support modifying table rows", query_id=20240511_130411_00061_ds9ba)
trino=1.8.0
dbt=1.8.0
postgres= 11

**Comment by hashhar** [comment]
This is a documented limitation - https://trino.io/docs/current/connector/googlesheets.html#sql-support and currently no one is working on this.
