### ISSUE TITLE
Support CREATE VIEW in JDBC-based connectors for MS SQL Server

### ISSUE THREAD

**Issue by JustGitting** [trinodb/trino#21118]
I've been using DBT to transform tables on an SQL Server, but now want to connect to several DBs and Trino is the way to go. I've setup Trino and can connect successfully to the different SQL Servers. However, I'm unable to create views, which is a key task of DBT.

Trino and JDBC version: 440
Using official Docker image.

To test "Create View" I did the following:

```
$ cat /etc/trino/catalog/sql_server_1.properties
connector.name=sqlserver
connection-url=jdbc:sqlserver://SQLSERVER1:1433;databaseName=Test_DB;encrypt=false;trustcertificate=true
connection-user=${ENV:DB_USER_SQLSERVER}
connection-password=${ENV:DB_PASSWORD_SQLSERVER}
```

`$ sudo docker exec -it <CONTAINTERID> trino --catalog sql_server_1`

Try to create view directly in trino:
```
trino> CREATE VIEW sql_server_1.my_schema.test_view AS SELECT 1 AS val;
Query ... failed: This connector does not support creating views
```

What is the work-around for MS SQL Server using the JDBC connector or something we can change in DBT?

The documentation for the SQL Server connector (https://trino.io/docs/current/connector/sqlserver.html#sql-support) indicates it supports all basic SQL syntax, including "CREATE VIEW" (https://trino.io/docs/current/sql/create-view.html). Hence my confusion.

Also of note, when I checked the catalog in DBeaver, it shows all the views that I've created previously in DBT as tables, not views. Very odd.

**Comment by ebyhr** [comment]
The connector doesn't support creating views as https://github.com/trinodb/trino/issues/11588. Closing as a duplicated issue.

**Comment by JustGitting** [comment]
Hi @ebyhr, is there any plan to support creating views? As it's a fundamental SQL feature and is needed for DBT.

I found the PR to support generic JDBC drivers for Trino to connect to other DBs (https://github.com/trinodb/trino/pull/3105). However, development stopped in 2022.

In this case, can the Trino SQL Server docs (https://trino.io/docs/current/connector/sqlserver.html) be updated to let people know of this limitation (cannot create views). It only mentions "Column names with leading and trailing spaces are not supported" as a limitation.

If I had know of this problem, I would have looked at an alternative SQL Engine.

**Comment by JustGitting** [comment]
Just found found the issue "Document CREATE VIEW is not supported in connectors #7150"

Only supported features are listed, not the limitations as there are too many.
