### ISSUE TITLE
Snowflake CI keeps facing timeout

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#21157]
https://github.com/trinodb/trino/actions/runs/8337770441/job/22817074816

**Comment by ebyhr** [comment]
cc: @yuuteng @dprophet

**Comment by dprophet** [comment]
I suspect its just a lot of load during testing. I increased the compute size

![image](https://github.com/trinodb/trino/assets/3594022/f33117fb-09b9-49ea-90ed-4efc7a855ac4)

Let me know if this fixes the problem.

**Comment by ebyhr** [comment]
@dprophet Thanks! CI is green now. We also disabled problematic test in https://github.com/trinodb/trino/pull/21158 because it's too slow for SaaS connectors. Let me close this issue.

**Comment by ebyhr** [comment]
Reopened because the timeout happened again:
* https://github.com/trinodb/trino/actions/runs/8583105680/job/23554376949
* https://github.com/trinodb/trino/actions/runs/8598108639/job/23559349156

**Comment by ebyhr** [comment]
It's stable after https://github.com/trinodb/trino/pull/21459.

**Comment by ebyhr** [comment]
* https://github.com/trinodb/trino/actions/runs/8812703672/job/24189313095
* https://github.com/trinodb/trino/actions/runs/8823690433/job/24224714527
