### ISSUE TITLE
Support custom authentication on HTTP header

### ISSUE THREAD

**Issue by oneonestar** [trinodb/trino#2117]
```
# Current abstraction
Authenticator
  - JWT
  - Kerberos
  - Certificate
  - Password
    - LDAP
    - File
    - <Custom password plugin>

--------

# Proposed abstraction
Authenticator
  - JWT
  - Kerberos
  - Certificate
  - LDAP
  - File
  - <Custom authenticator plugin>
```

Advantages:
- Support custom authentication on HTTP header
  This enables a lot of new options, including:
    - Authentication between proxy and presto
    - Arbitrary bearer token besides JWT
    - Work with identity aware proxy
    - Handle `X-Forwarded-Client-Cert`
- Multiple password authentication plugins can be used together (solve #1791)

Disadvantages:
- Change of SPI (PasswordAuthenticator -> Authenticator)
- Add dependency "javax.servlet-api" into SPI (may not be a big deal since this is only an api package)

We may add a migration period and some helper functions for the SPI change.

**Comment by electrum** [comment]
Requirements from @knwg145 in #3572:

* headers (`Authorization` and `X-Forwarded-For`)
* remote address
* ability to send back `WWW-Authenticate` header on failure

**Comment by RobertIndie** [comment]
+1

**Comment by hashhar** [comment]
For headers specifically SPI was added in https://github.com/trinodb/trino/pull/8895
