### ISSUE TITLE
Delta Lake Rename Table Mismatch Between Documentation and Runtime Behavior

### ISSUE THREAD

**Issue by fishfood34** [trinodb/trino#21271]
I am currently running Trino version 439 using Thrift for the delta lake metastore with data stored in ABFS. Upon trying to rename a delta table created by Trino I got the error message "Renaming managed tables is not allowed with current metastore configuration."

The [documentation](https://trino.io/docs/current/connector/delta-lake.html#alter-table-rename-to) clearly indicated that this should be possible as `delta.unique-table-location` is set to it's default value of `true` meaning the tables will be set as external and I am using Thrift. However #14066 [disables managed table renames for Thrift](https://github.com/homar/trino/blob/88e75142bf647c4412a87e5f6a67b4d493390c3a/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/thrift/DeltaLakeThriftMetastoreModule.java#L29).

Is this an issue with the documentation, or is this a bug in the code?

**Comment by ebyhr** [comment]
That's the expected behavior, not a bug.
