### ISSUE TITLE
Order by limit sorting problem, is there any forced sorting configuration?

### ISSUE THREAD

**Issue by zyclove** [trinodb/trino#21300]
```
select * from ( SELECT
  dev_num
FROM
  bi_dm.dm_dev_order_paid_month_df
where
  dt = '20240318'
ORDER by
  dev_num desc ) a limit 10
``` 
spark executes normally and presto sorts randomly.

```
SELECT
  dev_num
FROM
  bi_dm.dm_dev_order_paid_month_df
where
  dt = '20240318'
ORDER by
  dev_num desc limit 10
``` 
 
All execute normally

**Comment by zyclove** [comment]
fix: https://github.com/prestodb/presto/pull/14915

add : skip_redundant_sort=false;

**Comment by ebyhr** [comment]
https://github.com/prestodb/presto/pull/14915 is cherry-pick of https://github.com/trinodb/trino/pull/441 and https://github.com/trinodb/trino/pull/818. 

Let me close.
