### ISSUE TITLE
Configuration properties for kafka connector is not proper

### ISSUE THREAD

**Issue by njalan** [trinodb/trino#21302]
Properties for kafka ssl listed on below page is not proper:

https://trino.io/docs/current/connector/kafka.html?highlight=kafka+ssl+keystore+location#

**kafka**.security-protocol
**kafka**.ssl.keystore.location 
**kafka**.ssl.keystore.password 
**kafka**.ssl.truststore.location 
**kafka**.ssl.truststore.password 

In my testing there is no need to add prefix kafka and should use below properties:

security-protocol
ssl.keystore.location 
ssl.keystore.password 
ssl.truststore.location 
ssl.truststore.password 

I check the code it is using kafka-clients and in java code there also no need to add "kafka."

**Comment by ebyhr** [comment]
The prefix is required. See TestKafkaSslConfig class.

**Comment by njalan** [comment]
@ebyhr In my testing if I add prefix there are warnning below are error message:
2024-03-28T15:06:07.285+0800    WARN    Query-20240328_070606_00001_e3hz3-268   org.apache.kafka.clients.consumer.ConsumerConfig        The configuration 'kafka.ssl.truststore.password' was supplied but isn't a known config.
It is also not working if I added kafka prefix

**Comment by hashhar** [comment]
those configs should go into the Trino Kafka catalog config not the file you specify in `kafka.config.resources`.
