### ISSUE TITLE
 Unused Configuration Properties Causing Errors in Non-Kerberized and Non-HTTPS Environments

### ISSUE THREAD

**Issue by Akanksha-kedia** [trinodb/trino#21328]
Title: Unused Configuration Properties Causing Errors in Non-Kerberized and Non-HTTPS Environments

I am currently working on a Trino setup in a non-Kerberized and non-HTTPS environment. However, I have noticed that certain configuration properties are causing errors, even though they are not relevant or required in my current environment.

Here are the properties in question:

http-server.authentication.krb5.principal-hostname
http-server.authentication.krb5.service-name
http-server.authentication.krb5.user-mapping.file
http-server.https.excluded-cipher
http-server.https.keystore.key
http-server.https.keystore.path
http-server.https.port
http.authentication.krb5.config
These properties appear to be related to Kerberos and HTTPS configurations. Given that my setup does not involve either Kerberos or HTTPS, I believe these properties should not be causing errors.

I have temporarily resolved this issue by commenting out these properties from my configuration files. wanted to understand perhaps by ignoring these properties if they are not applicable, rather than throwing errors.

I look forward to the community's thoughts and suggestions on this matter if any wrong i m doing 
Errors:
 
1) Configuration property 'http-server.authentication.krb5.principal-hostname' was not used
2) Configuration property 'http-server.authentication.krb5.service-name' was not used
3) Configuration property 'http-server.authentication.krb5.user-mapping.file' was not used
4) Configuration property 'http-server.https.excluded-cipher' was not used
5) Configuration property 'http-server.https.keystore.key' was not used
6) Configuration property 'http-server.https.keystore.path' was not used
7) Configuration property 'http-server.https.port' was not used
8) Configuration property 'http.authentication.krb5.config' was not used

@martint @electrum @mosabua @joshk @jvanzyl @wendigo

**Comment by electrum** [comment]
You’re correct that these properties are for HTTPS and Kerberos. They should not be included in your config if you’re not using these features.

You can join us on Slack: https://trino.io/slack.html

**Comment by Akanksha-kedia** [comment]
@electrum but code wise i dnt see any mandatory, any annotations or error defined, is it coming from airlift module?

**Comment by electrum** [comment]
Airlift requires that all configuration properties are used. For example, if HTTPS is disabled, then setting any HTTPS properties is not allowed, as they would not be used.
