### ISSUE TITLE
Server Fails to Start When HTTPS is Disabled

### ISSUE THREAD

**Issue by Akanksha-kedia** [trinodb/trino#21339]
Title: Server Fails to Start When HTTPS is Disabled

Description:

When setting http-server.https.enabled=false in the configuration, Trino server fails to start, citing unused HTTPS properties as the reason. This happens even when HTTPS communication is disabled and only non-SSL communication is being used.

Configuration:

internal-communication.https.required=false
http-server.https.enabled=false
http-server.https.port=9090
http-server.https.keystore.path=/tmp/
Error Log:

2024-04-01T08:57:08.402Z INFO main io.airlift.log.Logging Disabling stderr output
2024-04-01T08:57:09.480Z ERROR main io.trino.server.Server Configuration is invalid

Errors:

1) Configuration property 'http-server.https.keystore.path' was not used
2) Configuration property 'http-server.https.port' was not used
Expected Behavior:

When http-server.https.enabled is set to false, Trino server should start successfully without any further validation on HTTPS related properties.

@wendigo @martint @electrum @joshk @monkey-mas @mosabua  i suspect this is a bug but need community understanding on this. Other scenario is https://github.com/trinodb/trino/issues/21328

**Comment by Akanksha-kedia** [comment]
@wendigo can you explain on this a little please. How its not a bug

**Comment by Akanksha-kedia** [comment]
This is not a bug. Configuration system is strict - if some configuration properties apply only when some other property is true (like in this case), unused properties are treated as error, can you direct me to code or is trino using airlift?

**Comment by Akanksha-kedia** [comment]
<img width="1539" alt="Screenshot 2024-04-01 at 2 56 23 PM" src="https://github.com/trinodb/trino/assets/89628774/b39ad0a8-b265-4328-972b-26e757b30634">
I understand your point. This is more about improving the user experience with the configuration system. While the strict configuration system helps to prevent misconfigurations, it can be tedious in cases like this where disabling a feature doesn't ignore the related properties.

**Comment by Akanksha-kedia** [comment]
and also https://trino.io/docs/345/security/tls.html on 345.0 
<img width="289" alt="Screenshot 2024-04-01 at 3 06 01 PM" src="https://github.com/trinodb/trino/assets/89628774/3fb4ce19-0405-4a68-8193-4fa67e582f18">
and having unused properties, we are successfully able to start the service.presto   3379312       1 99 09:36 ?        00:01:23 java

**Comment by wendigo** [comment]
@Akanksha-kedia as I've said - this is not a bug. Allowing unused properties does not improve user experience, just the opposite - makes the configuration more error prone. Leads to situations where typos and deprecate properties are accepted but not applied. This strictness of the configuration won't be relaxed and it's up to the user to provide a configuration that is valid. Error messages are informative enough to fix a configuration.

**Comment by wendigo** [comment]
If the incorrect configuration was somehow accepted in 345 it was definitely a bug, not a correct behavior

**Comment by Akanksha-kedia** [comment]
Thanks for the information, can we have document this or we are good without any document regarding this.

**Comment by wendigo** [comment]
@mosabua can you check whether this is stated in the docs?

**Comment by mosabua** [comment]
The general behavior around strictness and such?
