### ISSUE TITLE
Resource group metrics are not exported via JMX since 440

### ISSUE THREAD

**Issue by ivanvy-wix** [trinodb/trino#21343]
I believe, the change in https://github.com/trinodb/trino/pull/20810 means that the `setJmxExport()` on the line https://github.com/trinodb/trino/blob/809722e63ea834c523b44b18250bf246f4ccac71/plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/AbstractResourceConfigurationManager.java#L211

is called only when `match.getJmxExport()` returns `Optional.of(false)`, because `group.getJmxExport()` now returns `true`, so the groups end up never exported.

**Comment by hashhar** [comment]
cc: @polomek
