### ISSUE TITLE
Trino hive count(*) are not matching with the same set of data on two tables

### ISSUE THREAD

**Issue by yerrabothula-npm** [trinodb/trino#21353]
HI There,

we have a trino setup with hive catalog and using scality s3 as a storage,
so we have done distcp from hive hadoop environment to trino hive s3 

what we have observed is table count(*) in trino hive s3 is double than hive hadoop table

can you help in resolving this issue.

Thanks,
Raja R.

**Comment by hashhar** [comment]
What was the issue you encountered? It'd help future readers.
