### ISSUE TITLE
CI sometimes fails on JDK 23-ea

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#21414]
https://github.com/trinodb/trino/actions/runs/8567473904/job/23479408561?pr=21411

> `Error:  Failed to execute goal ca.vanzyl.provisio.maven.plugins:provisio-maven-plugin:1.0.22:provision (default-provision) on project trino-server: Error provisioning assembly. java.lang.ClassCastException: class [Ljdk.internal.vm.FillerElement; cannot be cast to class ca.vanzyl.provisio.archive.ExtendedArchiveEntry ([Ljdk.internal.vm.FillerElement; is in module java.base of loader 'bootstrap'; ca.vanzyl.provisio.archive.ExtendedArchiveEntry is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @27e5b378) -> [Help 1]`

**Comment by findepi** [comment]
cc @wendigo

**Comment by wendigo** [comment]
Yeah I saw that @findepi. It just started to happen recently

**Comment by wendigo** [comment]
It's solved.
