### ISSUE TITLE
Different query results when using aggregate function over a null value

### ISSUE THREAD

**Issue by mattheusv** [trinodb/trino#21457]
Starting at version `444` Trino returns different query results when using an aggregation function over a hardcoded null value.

Example:
```sql
WITH t0 AS (
    SELECT
        s_manager,
        s_market_manager,
        s_market_desc,
        COUNT(*) AS total
    FROM tpcds.sf10.store
    GROUP BY 1, 2, 3
),
t1 AS (
    SELECT
        s_manager as s_manager1,
        s_market_manager,
        /*
            When using max(null) the query return a result set, but when using just
            `null` the query returns an empty result set.
        */
        -- max(null) AS null_column,
        null AS null_column,
        SUM(total) AS total_sum
    FROM t0
    GROUP BY 1, 2
),
t2 AS (
    SELECT
        s_manager1 as s_manager2,
        null_column,
        SUM(total_sum) AS total_sum2
    FROM t1
    where  s_market_manager != 'Michael Aguilar'
    GROUP BY 1, 2
),
t3 AS (
    SELECT
        *
    FROM t2
        inner JOIN t1
        ON t1.s_manager1 = t2.s_manager2
)
SELECT *
    FROM t3
order by 1, 2, 3, 4, 5, 6, 7
```

When using the same query (with `null AS null_column`)  but replacing the `FROM t2 INNER JOIN t1` with  `FROM t2 LEFT JOIN t1` the query returns data but all values from t1 CTE is null:
![image](https://github.com/trinodb/trino/assets/35453476/1214f72f-a186-4263-94f4-b4f4f9a62884)

The query works properly for both `max(null) as ...` and `null as ...` if I remove the `where s_market_manager != 'Michael Aguilar'` statement from t2 CTE.

I've tested with version `443` and both queries (with `max(null) as ...` and `null as ...`) works properly.

**Comment by wendigo** [comment]
@martint is this related to your recent changes?

**Comment by martint** [comment]
Possibly. I’ll take a look.

**Comment by martint** [comment]
This is the first commit with the problem: c511c915396d12971e2559dbbd498b52ba554000. I'm looking into why it affects that type of query.
