### ISSUE TITLE
create table parquet external_location no values

### ISSUE THREAD

**Issue by ashfordm** [trinodb/trino#21690]
Set-up minio data store with parquet file Weather.parquet
-Can Access file from duckdb
SELECT count(1) FROM 's3://datalake/Weather.parquet';
=> 366

When attempting the same in trino get 0 rows ... please advise

Catalog File ...
connector.name=hive
hive.metastore=file
hive.s3-file-system-type=TRINO
hive.metastore.catalog.dir=s3://datalake/
hive.s3.aws-access-key=xxx
hive.s3.aws-secret-key=xxx
hive.s3.endpoint=127.0.0.1:9000
hive.s3.path-style-access=true
hive.s3.ssl.enabled=false

All below runs wo error and not finding errors in logs (INFO or DEBUG)

drop schema datalake.weather;

CREATE SCHEMA datalake.weather
WITH (location = 's3://datalake/');

drop table datalake.weather.weather_table;

CREATE TABLE datalake.weather.weather_table (
  MinTemp DOUBLE,
  MaxTemp DOUBLE,
  Rainfall DOUBLE,
  Evaporation DOUBLE,
  Sunshine VARCHAR,
  WindGustDir VARCHAR,
  WindGustSpeed VARCHAR,
  WindDir9am VARCHAR,
  WindDir3pm VARCHAR,
  WindSpeed9am VARCHAR,
  WindSpeed3pm BIGINT,
  Humidity9am BIGINT,
  Humidity3pm BIGINT,
  Pressure9am DOUBLE,
  Pressure3pm DOUBLE,
  Cloud9am BIGINT,
 Cloud3pm BIGINT,
 Temp9am DOUBLE,
 Temp3pm DOUBLE,
 RainToday VARCHAR,
 RISK_MM DOUBLE,
 RainTomorrow VARCHAR
)
WITH (
format = 'parquet',  
external_location = 's3://datalake/Weather.parquet'
);

select count(1) from datalake.weather.weather_table;
=> 0

**Comment by ashfordm** [comment]
what other information is required?

**Comment by awdavidson** [comment]
I believe you need to use `system.sync_partition_metadata` - more information can be found here https://trino.io/docs/current/connector/hive.html#procedures
