### ISSUE TITLE
Support and enable HTTP/2

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#21793]
As discussed in numerous contributor and maintainer meetings, we plan to move Trino towards HTTP/2. Patches to support that and use it in production exist already in the user and contributor community. Experience in terms of performance gains is very promising and a desire to have this feature in Trino itself is shared across numerous stakeholders. 

This issue aims to pull the various efforts together and serve as communication tool.

Following are a couple of tasks and aspects to consider:

* Upgrade to Jetty 12 for solid HTTP/2 support, done?
* Receive approval at community contributor company
* Issue PR from community contributor
* Test HTTP2 for internal communication, and maybe enable by default
* Test with secured internal communication, and maybe enable by default
* Expand towards using for client communication
* Expand towards using for data source (connector-level) communication
* Expand towards other HTTP client usage
* Configuration will be necessary to finely control where HTTP2 is used, ideally have a naming convention and consistent behavior and defaults
* For many usages it will be possible and probably beneficial to support and use longer polled sockets that stay open

**Comment by wendigo** [comment]
Jetty 12 is done but some changes in the airlift would be still needed (ALPN, HTTP/3?)

**Comment by wendigo** [comment]
https://github.com/airlift/airlift/pull/1156

**Comment by mosabua** [comment]
Related NPE fix in Airlift - https://github.com/airlift/airlift/pull/1154

**Comment by mosabua** [comment]
Related issue in Jetty https://github.com/jetty/jetty.project/issues/11631

Fix will be out with 12.0.9

**Comment by mosabua** [comment]
Related Trino isssue - https://github.com/trinodb/trino/issues/21735

**Comment by wendigo** [comment]
@mosabua I'd say that 21735 is unrelated to HTTP/2 itself - it applies to HTTP/1 and any other protocol as well

**Comment by wendigo** [comment]
I've experimented with HTTP/2 support in the Airlift and I came to the following conclusions that I'd like to discuss and seek approval from @dain @electrum.

Let's start with the features that we have implemented and knobs and switches that we expose right now:

1) Airlift's http-server supports:
  - http/1.1 + TLS for secure connections
  - http/1.1 and h2c for insecure ones

2) Airlift's http-client supports:
- http/1.1 + TLS for secure connections
- http/1.1 for insecure connections
- http/2 + TLS and h2c (HTTP/2 over clear-text) if http2 is enabled (disabled by default)

If the default configuration is used for both server and client: HTTP/1.1 is only used for both clear-text and encrypted communication.

**Comment by electrum** [comment]
This sounds reasonable to me -- summarized as remove `H2C` and make `HTTP/2` the default on both client and server. My only comment is that for the server side, we should also have an enable flag for HTTP/2 rather than a binder, since this something an administrator would control -- not something that the application code would depend on.

**Comment by mosabua** [comment]
Related to that I need some input and review on https://github.com/trinodb/trino/pull/22166

Once that is in place we can also expand to add the http/2 config stuff in there.. and the existing http-client page. And probably also stuff in the internal communication page.

**Comment by mosabua** [comment]
Questions - 

how do we enable http/2 by default for internal communication?
do we want it to be on default? 
do we need a fallback switch?
How does this affect the cert stuff?

**Comment by dain** [comment]
> how do we enable http/2 by default for internal communication? 
> do we want it to be on default? do we need a fallback switch?

Good questions.  @wendigo I assume we would want to use this by default when `internal-communication.https.required` is set.  Basically we would always use http/2 when https is enabled, or do we still want the `internal-communication.http2.enabled` flag?
In general, I'd like move to always using http/2 internally because the multiplexed nature means we can use long polling everywhere without worrying about running out of sockets.  That would mean we move to always using https internally.  I'm less concerned about this now that we have the auto-keying feature.

**Comment by wendigo** [comment]
@dain with the implementation that I've added in airlift we can have HTTP/2 always on for both secure and insecure internal communication. We don't need https always on for that.

**Comment by mosabua** [comment]
So are we plunging right into using it without a switch to disable @wendigo @dain ? And this is for internal communication.. what about other HTTP usage

**Comment by wendigo** [comment]
Merged to master.
