### ISSUE TITLE
Docker trino cli complains about deprecated jna usage

### ISSUE THREAD

**Issue by Sartan4455** [trinodb/trino#21804]
Did not occur docker version: 439
Upgrade to Current Docker version: 446

command to run trino:

`docker exec --env LC_ALL=$LC_ALL -it trino trino --server https://<server_ip>:5578 --catalog iceberg --keystore-path=/etc/trino/certs/trino.pem --truststore-path=/etc/trino/certs/ca.crt`

result is 
```
May 02, 2024 4:20:26 PM org.jline.utils.Log logr
WARNING: The terminal provider jna has been deprecated, check your configuration. This warning can be disabled by setting the system property org.jline.terminal.disableDeprecatedProviderWarning to true.
```

fix by using  disableDeprecatedProviderWarning
`docker exec --env LC_ALL=$LC_ALL -it trino java -Dorg.jline.terminal.disableDeprecatedProviderWarning=true -jar /usr/bin/trino --server https://<server_ip>:5578 --catalog iceberg --keystore-path=/etc/trino/certs/trino.pem --truststore-path=/etc/trino/certs/ca.crt`

adding  to jvm.config did not work(I am not great with jvm or java so that may not be the best place)
```
-Dorg.jline.terminal.disableDeprecatedProviderWarning=true
-Dorg.jline.terminal.dumb=true
```

Talking in slack was:

```
Jan Waś
 
The Readme explains the differences, we can add these required flags to enable the new implementation
https://github.com/jline/jline3?tab=readme-ov-file#ffm


Jan Waś
  29 minutes ago
We just update the jline dependency, they have some new stuff there


Mateusz Gajewski
  [29 minutes ago](https://trinodb.slack.com/archives/CGB0QHWSW/p1714665228771469?thread_ts=1714606441.499839&cid=CGB0QHWSW)
That won’t work under JDK 8 I believe

Jan Waś
  28 minutes ago
But will work in the Trino container


Mateusz Gajewski
  27 minutes ago
Yeah. That makes sense
```

**Comment by wendigo** [comment]
This was fixed in 447 release. I've checked on the docker image that we publish and the warning is gone.
