### ISSUE TITLE
[Iceberg] Support custom catalog name for the Iceberg RESTCatalog

### ISSUE THREAD

**Issue by osscm** [trinodb/trino#21813]
Looks like currently the catalogName is the Trino's `catalog-name` (https://github.com/trinodb/trino/blob/master/lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/CatalogNameModule.java#L29)

there will be cases where the catalogName used on the REST Server side could be different, specially when users are migrating from HMS to RESTCatalog, than in the current model, we force user to rename the Trino catalog name.

ref: https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java#L493

**Comment by osscm** [comment]
cc @danielcweeks if you can please validate my understanding, and does request make sense? Or I am just blabbering :)

**Comment by danielcweeks** [comment]
@osscm I don't think this is an issue.

The catalog name in Trino (as referenced by sql) will be baed on the `<catalog>.properties` filename or the name of the registered catalog using `CREATE CATALOG <catalog_name> . . .` sql syntax.

The name of the warehouse for the REST catalog will either be defined by the uri endpoint itself or can be provided by the `iceberg.rest-catalog.warehouse` property in the [REST catalog configuration](https://trino.io/docs/current/object-storage/metastores.html#rest-catalog).  This is up to the backing REST catalog implementation.

These two identifiers are independent (but generally good idea to use the same catalog names everywhere if they represent the same thing).

**Comment by osscm** [comment]
thanks @danielcweeks for a quick response.

so we are saying if someone is using a custom hive metastore catalog-name, and migrating to REST, than it should be used as the `iceberg.rest-catalog.warehouse` or the suffix of the URL, and as per the RESTCatalog spec, and RESTCatalog server ideally should support either of these options?

**Comment by osscm** [comment]
fyi, related Iceberg issue https://github.com/apache/iceberg/issues/10205

**Comment by ebyhr** [comment]
Closing as https://github.com/apache/iceberg/issues/10205 has been closed.
