### ISSUE TITLE
JSON path doesn't accept wildcard array accessor

### ISSUE THREAD

**Issue by kekwan** [trinodb/trino#21847]
I have the following JSON object under `stagegcstatistics` column
```
[
  {
    "averageFullGcSec": 0,
    "fullGcTasks": 0,
    "maxFullGcSec": 0,
    "minFullGcSec": 0,
    "stageId": 0,
    "tasks": 1,
    "totalFullGcSec": 0
  },
  {
    "averageFullGcSec": 0,
    "fullGcTasks": 0,
    "maxFullGcSec": 0,
    "minFullGcSec": 0,
    "stageId": 1,
    "tasks": 110,
    "totalFullGcSec": 0
  }
]
```

I am trying to extract the number of tasks using `json_extract`. The method accepts a JSON path which I put as `select json_extract(stagegcstatistics, '$[*].tasks') `

Despite the documentation saying [wildcard array accessor](https://trino.io/docs/current/functions/json.html#wildcard-array-accessor) is supported and even giving an example, I get this error 

```
io.trino.spi.TrinoException: Invalid JSON path: '$[*].tasks'
	at io.trino.operator.scalar.JsonPathTokenizer.invalidJsonPath(JsonPathTokenizer.java:196)
	at io.trino.operator.scalar.JsonPathTokenizer.matchUnquotedSubscript(JsonPathTokenizer.java:109)
	at io.trino.operator.scalar.JsonPathTokenizer.computeNext(JsonPathTokenizer.java:63)
	at io.trino.operator.scalar.JsonPathTokenizer.computeNext(JsonPathTokenizer.java:26)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:275)
	at io.trino.operator.scalar.JsonExtract.generateExtractor(JsonExtract.java:156)
	at io.trino.operator.scalar.JsonExtract.generateExtractor(JsonExtract.java:151)
	at io.trino.operator.scalar.JsonPath.<init>(JsonPath.java:30)
	at io.trino.operator.scalar.JsonFunctions.castVarcharToJsonPath(JsonFunctions.java:71)

```

This should be valid JSONpath syntax as i validated it here https://jsonpath.com/

**Comment by wendigo** [comment]
@kekwan You are referring to the docs of the `json_extract` function that supports subset of the jsonpath specification. If you want to use the [*] subscript type you need to use functions like `json_query`

**Comment by kekwan** [comment]
@wendigo Thanks for taking a look. I am not longer getting the error using `json_query` but still not having success using [*] type.

I'm able to return the elements using index like `json_query(json_format(stagegcstatistics),  'strict $[0]')`  but `json_query(json_format(stagegcstatistics),  'strict $[*]')` and `json_query(json_format(stagegcstatistics),  'strict $[*].tasks')` gives me NULL.

**Comment by wendigo** [comment]
@kasiafi @martint I can't get [*] to work. Please advise

**Comment by wendigo** [comment]
Actually this is documented:

```
Note that the json_query function can only output a single JSON item. If you don’t use array wrapper, you get an error for every customer with multiple children. The error is handled according to the ON ERROR clause.
```

So in your case this should look like this: 
```
select json_query('[
  {
    "averageFullGcSec": 0,
    "fullGcTasks": 0,
    "maxFullGcSec": 0,
    "minFullGcSec": 0,
    "stageId": 0,
    "tasks": 1,
    "totalFullGcSec": 0
  },
  {
    "averageFullGcSec": 0,
    "fullGcTasks": 0,
    "maxFullGcSec": 0,
    "minFullGcSec": 0,
    "stageId": 1,
    "tasks": 110,
    "totalFullGcSec": 0
  }
]', 'strict $[*].tasks' WITH ARRAY WRAPPER)
```

**Comment by wendigo** [comment]
Tested on Starburst Galaxy:
<img width="661" alt="Screenshot 2024-05-08 at 19 46 22" src="https://github.com/trinodb/trino/assets/66972/321b63cb-0e83-4232-ba36-b2c2078294d4">

**Comment by kekwan** [comment]
it works, thank you so much !

**Comment by martint** [comment]
cc @mosabua -- we should add some examples to the docs

**Comment by Heltman** [comment]
why json_extract not support [*] ?
