### ISSUE TITLE
Issue while querying the nested data parquet files.

### ISSUE THREAD

**Issue by guderamesh** [trinodb/trino#21850]
I get the below error when trying to query the nested data parquet files.

**"class org.apache.parquet.io.primitiveColumnIO cannot be cast to class org.apache.parquet.io.GroupColumnIO (org.apache.parquet.io.primitiveColumnIO and org.apache.parquet.io.GroupColumnIO are in unnamed module of loader io.trino.server.PluginClassLoader @16488ed7)"**

below is the sample record in the file.
clusterid=3243242, decesed=False, overallscroe=0, tier=0, buildverison=20230615, buildtype=0, names=arrays([{'firstname': 'myranda', 'middleinitial': 'K',
'middlename': 'K', 'lastname': 'Fielder', 'sources': array([3434], dtype=int32), 'sourcelevel':3, 'bizname':''}], dtype=object),
dobs=array([{{'year': 2005, 'month': 4, 'day': 8, 'yearscore': 7093, 'monthscore', 'sources': array([[3434], dtype=int32), 'sourcelevel':3, 'appendable':'False'}], dtype=object),
ethincities=array([], dtype=object),
phones=array([], dtype=object)

Note: The same parquet file was able to query through bigquery external table.
Please suggest, how to resolve the issue.
Thank you.

**Comment by ebyhr** [comment]
How did you create the Parquet file? Can you share the entire steps to reproduce?

**Comment by guderamesh** [comment]
The parquet file is being created by the upstream application. At this point in time, not sure, need to check.

**Comment by raunaqmorarka** [comment]
Which release of Trino are you using ? It might have been fixed by https://github.com/trinodb/trino/pull/20943
We need a sample file and table definition to work on this problem.

**Comment by guderamesh** [comment]
Got the issue resolved after reading the parquet file schema and creating the corresponding hive table compatible with that schema, now able to query the parquet files.

**Comment by guderamesh** [comment]
thank you
