### ISSUE TITLE
Pinot connector has no way to pass query option along with query

### ISSUE THREAD

**Issue by naman-patel** [trinodb/trino#21897]
Similar to PR https://github.com/prestodb/presto/pull/18475/files

We need to be able to pass query options along with pinot queries.

**Comment by ebyhr** [comment]
The connector already supports passing query options with `SET` in dynamic tables: https://github.com/trinodb/trino/pull/19078

**Comment by ebyhr** [comment]
Let me close this issue because supporting arbitrary query options without tests is troublesome. Please file a new issue if you want to add a dedicate option.
