### ISSUE TITLE
Trino postgres connector does not support modifying table rows

### ISSUE THREAD

**Issue by gauravknu10** [trinodb/trino#21938]
TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="This connector does not support modifying table rows", query_id=20240511_130411_00061_ds9ba)
trino=image: "trinodb/trino:latest"
dbt=1.8.0
postgres= 11

**Comment by hashhar** [comment]
This is expected and documented. See https://trino.io/docs/current/connector/postgresql.html#sql-support and the limitations mentioned there.
