### ISSUE TITLE
MySQL slow in 447

### ISSUE THREAD

**Issue by wangzy1976** [trinodb/trino#21945]
The sql access mysql in 447 is too slow , after replace the mysql driver from 8.4.0 to 8.3.0 , the issue dispear.

**Comment by ebyhr** [comment]
cc: @wendigo

**Comment by wendigo** [comment]
@wangzy1976 please elaborate on the "slow" part i.e. by including benchmark results.

**Comment by wangzy1976** [comment]
[447.with.mysql8.3.0-1.json](https://github.com/trinodb/trino/files/15292717/447.with.mysql8.3.0-1.json)

the sql execute less than 4s using 447 with 8.3.0 driver

[447.with.mysql8.4.0-1.json](https://github.com/trinodb/trino/files/15292720/447.with.mysql8.4.0-1.json)

the sql execute 53s using 447 with 8.4.0 driver

**Comment by wangzy1976** [comment]
- [447.with.mysql8.3.0-1.json](https://github.com/trinodb/trino/files/15292782/447.with.mysql8.3.0-1.json)

the sql execute less than 4s using 447 with mysql8.3.0 driver ; 445 / 446 is the same time

- [447.with.mysql8.4.0-1.json](https://github.com/trinodb/trino/files/15292783/447.with.mysql8.4.0-1.json)

the sql execute 57s using 447 with mysql8.4.0 driver

**Comment by mosabua** [comment]
@wangzy1976 could you maybe try this out with the new 9.0.0 driver .. also fyi @wendigo for any potential updates we might do
