### ISSUE TITLE
Improve performance of SortedRangeSet discrete union

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#21992]
When all SortedRangeSets are discrete, then performance of `SortedRangeSet#union` could de improved greatly. Improving union would reduce DF collection latency and reduce coordinator CPU usage (DF are unioned on coordinator).

This is follow up from: https://github.com/trinodb/trino/pull/21657

**Comment by chenjian2664** [comment]
Hi, I want to take this, could you give me some hits about this? @sopel39

**Comment by Dith3r** [comment]
@chenjian2664 
Add special case for unions where all SortedRangeSet are discrete, similar to linked PR. The main point is to avoid copy of single value and use range copy of raw values as much as possible.

**Comment by chenjian2664** [comment]
@Dith3r Thanks for the guidance

**Comment by sopel39** [comment]
The other thing is when you are dealing with discrete set you can just use single comparison to compare to "ranges" (as in https://github.com/trinodb/trino/pull/21657/files#diff-a3ede16a05943d869ba6d7b8821761bc3ed3d23915bb0b3bf8bac363b7038deaR585).
