### ISSUE TITLE
Can't load JDBC Driver trino-jdbc-448.jar whith an URL ClassLoader

### ISSUE THREAD

**Issue by prrvchr** [trinodb/trino#22081]
Hi,

I try to load the trino-jdbc-448.jar driver under LibreOffice Base, but I can't...
I have to [load my drivers](https://github.com/prrvchr/jdbcDriverOOo/blob/master/source/jdbcDriverOOo/source/io/github/prrvchr/uno/sdbc/DriverBase.java#L299) with an URL class loader because the jdbcDriver extension is itself launched by an URL class loader launched by LibreOffice.

Perhaps in your driver you use the current thread Class Loader (ie: `Thread.currentThread().getContextClassLoader()`) to load components or do you use `java.util.ServiceLoader` services?

I know that a special configuration is required to be able to propagate the class loader which loads the jdbcDriverOOo extension and which is the only one able to load the jdbc drivers.

**Comment by prrvchr** [comment]
Well I was missing the archive `okhttp-4.12.0.jar`.

Now everything works fine. Sorry for the inconvenience I'm closing...

**Comment by findepi** [comment]
`trino-jdbc` driver should be standalone, it should not require any dependencies. 

cc @electrum @wendigo

**Comment by wendigo** [comment]
It is standalone. We verify the shading

**Comment by prrvchr** [comment]
It would be good to include in the technical specifications:
- Java 8
- okhttp

**Comment by findepi** [comment]
@prrvchr yes, Java 8 is required
but okhttp must not be required. can you verify the problem with a standalone Java application with only trino-jdbc on the classpath?

**Comment by prrvchr** [comment]
Hi findepi,

I have accumulated problems and I made a mistake, **the okHttp archive is not necessary** I still cannot connect but the absence of the archive does not change anything.

> java.sql.SQLException: Error executing query: java.io.IOException: unexpected end of stream on http://127.0.0.1:8888/...

Sorry for this fake bug...

**Comment by findepi** [comment]
> I have accumulated problems and I made a mistake, the okHttp archive is not necessary I still cannot connect but the absence of the archive does not change anything.


no worries, thanks for checking

> I can't figure out how to configure a catalog with docker

@mosabua will be able to help

**Comment by mosabua** [comment]
See https://trino.io/docs/current/installation/containers.html#configuring-trino for how to use external config file (including additional catalog properties files) with the docker container
