### ISSUE TITLE
package Trino-server-rpm  error :ailed to execute goal org.codehaus.gmaven:groovy-maven-plugin:2.1.1:e...

### ISSUE THREAD

**Issue by RYiHui** [trinodb/trino#22086]
[INFO] --- maven-dependency-plugin:3.1.2:analyze-duplicate (default) @ trino-server-rpm ---
[INFO] Skipping plugin execution
[INFO] 
[INFO] --- duplicate-finder-maven-plugin:1.5.0:check (default) @ trino-server-rpm ---
[INFO] Skipping duplicate-finder execution!
[INFO] 
[INFO] --- modernizer-maven-plugin:2.2.0:modernizer (modernizer) @ trino-server-rpm ---
[INFO] Skipping modernizer execution!
[INFO] 
[INFO] --- provisio-maven-plugin:1.0.18:provision (unpack) @ trino-server-rpm ---
[INFO] 
[INFO] --- groovy-maven-plugin:2.1.1:execute (default) @ trino-server-rpm ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/C:/Users/renyh10/.m2/repository/org/codehaus/groovy/groovy-all/2.4.9/groovy-all-2.4.9.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  23.309 s
[INFO] Finished at: 2024-05-23T10:40:56+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.gmaven:groovy-maven-plugin:2.1.1:execute (default) on project trino-server-rpm: Execution default of goal org.codehaus.gmaven:groovy-maven-plugin:2.1.1:execute failed: java.nio.file.FileSystemException: D:\****\****\core\trino-server-rpm\target\classes\trino-server-361\lib\HdrHistogram-2.1.9.jar: 客户端没有所需的特权。
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

Process finished with exit code 1

**Comment by hashhar** [comment]
windows is not supported as a build environment for Trino. Try using Linux or WSL.
See https://github.com/trinodb/trino/tree/master?tab=readme-ov-file#build-requirements

**Comment by RYiHui** [comment]
> windows is not supported as a build environment for Trino. Try using Linux or WSL. See https://github.com/trinodb/trino/tree/master?tab=readme-ov-file#build-requirements

Thanks，I  have changed build environment to linux and successfully built Trino.
