### ISSUE TITLE
PreparedStatement dont support java.sql.Statement.NO_GENERATED_KEYS option

### ISSUE THREAD

**Issue by prrvchr** [trinodb/trino#22100]
Hi all,

I just noticed that it is not possible to execute the `java.sql.Connection.prepareStatement(String sql, int option)` method with option on `java.sql.Statement.NO_GENERATED_KEYS` without getting the error:

> java.sql.SQLFeatureNotSupportedException: Auto generated keys must be NO_GENERATED_KEYS

It is still possible to call this method without an option. But using the option `java.sql.Statement.NO_GENERATED_KEYS` should be the same as without the option.

**Comment by findepi** [comment]
Trino does not support generating keys (from engine perspective, even if some connectors do that under the hood),
so I agree that NO_GENERATED_KEYS can currently be ignored (instead of rejecting).
