### ISSUE TITLE
[Feature Request] Support "Single Row Mode" similar to PostgreSQL

### ISSUE THREAD

**Issue by Sartan4455** [trinodb/trino#22124]
In postgres there is a row-by-row results.  Which, if possible, will start to stream data before the query is over.  
https://www.postgresql.org/docs/16/libpq-single-row-mode.html

Is this option, or some thing similar,  available in trino?  A sort of stream of results as it were. 

The use case, for us, are large and long query that will not be ordered or sorted in any way but take a long time to finish.  If a user could see some of the early data they can decide if they need to wait for it all or if they could maybe stop the query and do a more targeted one.

On occasion, and I'm not sure why, the trino CLI will spit out small amount of results but then continue with the query.  Maybe this is just an oddity with low amount of results or something else I do not understand.  But this would be useful for our project.

p.s. if this is not the place for feature request I am sorry.

**Comment by findepi** [comment]
Trino streams results as they are available back to the client.
You can observe this if you run 
```
SELECT * FROM very_large_table
```

you will get some results back to your client (eg CLI), while query is still running. The query won't consume a lot of memory.

So, i believe that Trino already does what is being ask for.

> On occasion, and I'm not sure why, the trino CLI will spit out small amount of results but then continue with the query. 

CLI uses a pager (eg `less`)

**Comment by electrum** [comment]
If you pipe the results of the CLI to a file, disable the pager (`export TRINO_PAGER=cat`), or use the JDBC driver, you will see that the results are streamed immediately.

**Comment by Sartan4455** [comment]
Certainly! Here’s a cleaned-up version of your text:

I am using the HTTP API, if that makes a difference. I don't mean streamed results; I mean incremental results. Maybe that's what you mean, and that's what it's doing. That's totally fine.

Our use case involves time-series data. Suppose a user wants information with a complex query over a time period, say one day, and the order doesn't matter. We have billions of rows in each table, so such a query will take a while, 30+ minutes or more. During that time, no results will be streamed back, or at least it doesn't appear that way – I won't see 100 results come back and then more results trickle in. This might be due to how things need to be collated on the master and how SQL works (I am not an expert on that).

Our older proprietary system (which is one reason we are moving to open source), because of how it was laid out on disk, would already have data in time order, so it would get incremental results in seconds as it walked through the data.

One solution we have considered is breaking apart the day into subqueries, such as breaking a day query into hours. This would then run on much less data and could provide incremental results. Each hour query might take 1 minute, and we could show results every minute instead of waiting 30 minutes. This could be further reduced to 30 seconds, 15 seconds, and so on. This led me to think that if Trino could stream results more incrementally, it would be much less complicated on our end. I saw that Postgres has a single row mode, which seems similar to this idea, or perhaps even using a CURSOR.

Anyway, maybe I am misunderstanding or wanting something unrealistic. That's absolutely possible and even highly probable.

Thanks for looking into it! My team and I appreciate all the work you put into Trino.
