### ISSUE TITLE
Normalize conjunct order in CanonicalSubplanExtractor

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#22120]
subqueries like 1. `x = 10 AND y = 10` 2. `y = 10 and x = 10` should have same canonical representation. Order canonicalized conjuncts in some deterministic way.

**Comment by osscm** [comment]
Do you have any idea how to achieve it?

One brute force way could be to reorder the predicate and try to match, while identifying if that part of query is cached or not?

**Comment by sopel39** [comment]
> One brute force way could be to reorder the predicate and try to match, while identifying if that part of query is cached or not?

This is actually already done.

If you look at https://github.com/trinodb/trino/pull/21888 then there is a concept of `PlanSignature` that `CacheManager` uses as a cache key. `PlanSignatures` are computed in `io.trino.cache.CommonSubqueriesExtractor#computePlanSignature`. Specifically:
```
            signatureKey = combine(
                    signatureKey,
                    "filters=" + formatExpression(combineConjuncts(
                            // Order remaining expressions alphabetically to improve signature generalisation
                            Stream.of(remainingDomainExpression, extractionResult.getRemainingExpression())
                                    .map(IrUtils::extractConjuncts)
                                    .flatMap(Collection::stream)
                                    .sorted(comparing(Expression::toString))
                                    .collect(toImmutableList()))));
``` 
these are already ordered by their string representation
