### ISSUE TITLE
When Trino uses Iceberg and HDFS, the metadata of Iceberg will be concentrated on the HDFS node where the Trino master is located, causing an excessive number of files on that node.

### ISSUE THREAD

**Issue by c8679724** [trinodb/trino#22148]
When using the Trino + Iceberg + HDFS combination, the metadata of Iceberg will be concentrated on the HDFS node where the Trino master is located, leading to an excessive number of files on that node and causing the HDFS DataNode where the master is located to nearly crash.

**Comment by raunaqmorarka** [comment]
After https://github.com/trinodb/trino/pull/22739 iceberg metadata will be cached by default in coordinator memory.
You can also consider using https://trino.io/docs/current/object-storage/file-system-cache.html
