### ISSUE TITLE
java.sql.DatabaseMetadata.getTables() does not return a newly created table.

### ISSUE THREAD

**Issue by prrvchr** [trinodb/trino#22204]
Hi all,

I am trying to integrate the Trino JDBC driver into the [jdbcDriverOOo](https://prrvchr.github.io/jdbcDriverOOo/) extension which is a JDBC driver for **LibreOffice Base**.

When creating a table in **Base** table design two things are done:
- a CREATE TABLE command is executed to create a new_table.
- a query on `DatabaseMetaData.getTables(new_table_catalog, new_table_schema, new_table_name, null)` is done to retrieve the new created table.

It appears that just after the creation of a table it is not possible to find it with `getTables()` however after a certain delay this table is indeed found and returned by `getTables()`...

**Comment by ebyhr** [comment]
Can you reproduce the issue only using Trino JDBC driver without jdbcDriverOOo?

**Comment by prrvchr** [comment]
Well by doing more investigation I realized that I hadn't seen everything.

The table is well created, however its name is converted to lower case and `DatabaseMetaData.getTables()` cannot find it with its name given during creation if it contains capital letters...

**Comment by ebyhr** [comment]
It's related to https://github.com/trinodb/trino/issues/17. Let me close this issue.

**Comment by prrvchr** [comment]
The workaround is to only create tables in lower case but do you have anything planned on your side to resolve this problem?

**Comment by prrvchr** [comment]
I don't know how Trino works, but if Trino handles table names only in lowercase then `DatabaseMetaData.getTables()` should perform case-insensitive comparisons?
