### ISSUE TITLE
Bug: trino-druid plugin; Table functions result set don't respect ORDER BY clause if given in embedded sql statement

### ISSUE THREAD

**Issue by charlesmack34** [trinodb/trino#22284]
Albeit, I currently use a super old version of trino (`v. 410`) I'm wondering if anyone has ran into the issue I'm seeing. I've search tthrough all issues and can't find anything that resembles what I'm currently seeing.
 
Issue: As mentioned in the title, for connections to Druid using the `trino-druid` plugin, table functions seem to be failing to respect any `ORDER BY` clause if given in a query. *Interesting fact*: this seems to only happen on tables that have large amounts of data i.e. hundreds of millions and even billions of rows. I don't have an exact number to be super precise.
 
How To Reproduce:
 
1. Setup a Druid cluster, create a simple table within a schema and load the table with roughly ~billion rows
2. Spin up trino, and use druid properties file to connect to the druid cluster above
3. Use any DB query tool to connect and query the druid table. Making sure that the query is indeed a `table function` and that you have a `ORDER BY` clause within the embedded query of the table function.
4. Execute the query and observe the result set (specifically the column you asked to `ORDER BY` and the order its supposed to render)
 
Few Examples:
 
This table has ~ 7 billion rows. The following is a dummy table filled with dummy data.
<img width="616" alt="Datasources" src="https://github.com/trinodb/trino/assets/46236077/be6409a6-5ecb-4751-ad26-e8126a073dd1">

Here's the table definition and data. Druid has no issue returning the data back.
<img width="1553" alt="3f6e592ad938fee98c60876bcd3fc34185aed934fbe10b0031343dcc3313bc23" src="https://github.com/trinodb/trino/assets/46236077/6cc48463-c340-41e1-adc5-ba4a21c2688b">

Fire off query with `ORDER BY`. It is not show here but the query that is executed gets wrapped into a table function that will look like so: `SELECT * FROM TABLE(druid_storeperf.system.query(query => 'SELECT l_comment, l_extendedprice FROM druid.lineitem_big ORDER BY l_extendedprice ASC'))`

You can clearly see that the `l_extendedprice` column in the result set IS NOT ordered in ascending order..
<img width="970" alt="f6a8c85920cead3ebe557ce20cd19ea74c90c5af6ea23849534014a8b4ada50c" src="https://github.com/trinodb/trino/assets/46236077/50a5dd10-24cb-4f11-aee1-2fe85f0bc042">

What I do know:

When `trino-druid` plugin executes it's code and rewrites the embedded query to send to Druid directly for processing, it generates a SQL statement of the like: `SELECT \"l_comment\", \"l_extendedprice\" FROM (SELECT * FROM druid.lineitem_big ORDER BY l_extendedprice ASC) o`

I am not sure what is causing this bug but would love some help in figuring this out. Thanks in advance.

**Comment by ebyhr** [comment]
The table function doesn't ensure the result order. See `Notes` in Druid connector page: https://trino.io/docs/current/connector/druid.html#query-varchar-table
