### ISSUE TITLE
Trino-cli has no option to accept targetResultSize query parameter

### ISSUE THREAD

**Issue by anilsomisetty** [trinodb/trino#22303]
In query result GET request from coordinator it has a query parameter targetResultSize which is per get request how much a coordinator can send to client.
I see there is no way to configure it from trino client.

**Comment by mosabua** [comment]
What is the use case you are trying to solve with exposing this parameter? The protocol is already conversational so there is no real limit for the overall data returned.

**Comment by anilsomisetty** [comment]
Hi @mosabua 

Currently in below mentioned code I see that for query get request to fetch resultset we have a queryparameter  targetResultSize defined with a default size as 16MB i.e 16MB of result set would be sent to client from coordinator but there is no way this parameter can be set from client.

Another thing to note here is this parameter is never set i.e it's always null but I see a condition to check take min of this value and max target size which is 128MB.

If this parameter can be set through client for queries that would fetch large resultset from coordinator it would minimize the get request calls which would reduce the wait time and queries would complete faster.

ExecuteStatementResource.java(https://github.com/trinodb/trino/blob/1b0a0116d34e77a9fa8f5c47207ac62e3b16c87b/core/trino-main/src/main/java/io/trino/server/protocol/ExecutingStatementResource.java#L216)

please let me know your comments on my understanding.

**Comment by mosabua** [comment]
This might be something we can do in our current work on improving client protocol performance with Project Swift. 

https://github.com/trinodb/trino/issues/22271

Note that we don't know if increasing the size does indeed improve performance. Did you test this and can report any findings?

**Comment by anilsomisetty** [comment]
What I have observed is in code targetResultSize was set as QueryParam and was never getting used or set from trino client while running a query, so I was just curious on why it was not done.

I have run a query which returns approximately **6GB of data with 7.7Million rows** on a trino cluster from DBVisualizer using trino-jdbc client driver jar, these are my findigs: 
1. When targetResultSize is default i.e 16MB it took **1hour** to fetch this result
2. When targetResultSize is made maximum i.e 128MB it took **4minutes** to fetch this result

**Comment by mosabua** [comment]
Wow .. very interesting finding. We should take this into account for Project Swift @wendigo @dain @electrum @martint

**Comment by wendigo** [comment]
@mosabua I can't agree with these numbers - I've been benchmarking changing this value and there is a diminishing improvement for values over 32 MB. The buffering and compression happens on the coordinator so setting this value high, puts an additional pressure on the coordinator. That doesn't scale well.

**Comment by anilsomisetty** [comment]
My trino cluster has 6 nodes = 5 workers and 1 coordinator(doesn't act as worker) where each node has 1TB memory and 128 CPU where I have run the query.

**Comment by wendigo** [comment]
We don't want to expose this parameter to the clients. With the spooled client protocol extension (https://github.com/trinodb/trino/issues/22662) it won't be effective either way.

**Comment by pichlerpa** [comment]
Interesting, I just added this parameter to the Power BI connector for testing and I did notice a significant performance change on my local machine, where 16MB was the fastest for loading 500k rows into Power BI.

![Image](https://github.com/user-attachments/assets/6b939059-cff0-429b-a1e3-05970c8f4541)

**TargetResultSize 1MB (default) --> time taken: 00:02:37**

![Image](https://github.com/user-attachments/assets/b66bf55a-9b51-4e6a-a07e-9a1055d6a7dc)

**TargetResultSize 16MB --> time taken: 00:01:46**

![Image](https://github.com/user-attachments/assets/e60a64a9-fab2-4d08-b271-226a98890d59)

**TargetResultSize 128MB --> time taken: 00:01:58**

![Image](https://github.com/user-attachments/assets/56d06248-cc06-400b-9897-3ebd498f0c05)

**Comment by wendigo** [comment]
@pichlerpa this puts an additional pressure on the coordinator as the last response is cached in order for the client to be able to retry the last call. That's why it's not recommended approach.

**Comment by pichlerpa** [comment]
@wendigo I understand, but I think it's great to have the option at least. In case of Power BI, this can be very useful to speed up imports which often happen just once per night or a few times during the day.

**Comment by wendigo** [comment]
@pichlerpa that's why we've added a spooled protocol that allows you to have segments of a bigger size. In our benchmarks the new jdbc driver is 2-4x faster.

**Comment by pichlerpa** [comment]
@wendigo Ok, yes, it seems to work like Databricks' cloud fetch mechanism. But what if I don't have an object store available? Isn't this a relatively simple option to improve performance, as long as the coordinator isn't too busy at those times to avoid OOM errors? I don't really see the problem, if you know the system and functionality, why not? Isn't it better than having endless round-trips to collect query results.

**Comment by wendigo** [comment]
@pichlerpa we are considering adding a spooling manager that works with the local worker storage

**Comment by wendigo** [comment]
@pichlerpa https://github.com/trinodb/trino/issues/22662
