### ISSUE TITLE
 give me a complete example of Redis

### ISSUE THREAD

**Issue by hope1234567hope** [trinodb/trino#22352]
redis clinent  is 
127.0.0.1:6379>  hmset schema1.table2 username jack age 2
OK
127.0.0.1:6379> hgetall schema1.table2
"username"
"jack"
"age"
"2"  

now  mysql json file  is:  
cat schema1.table2.json
{
"tableName": "table2",
"schemaName": "schema1",
"value": {
"dataFormat": "hash",
"fields": [
{"name": "username", "type": "varchar"},
{"name": "age", "type": "bigint"}
]
}
}
now use trino-cli:
trino:schema1> select * from  table2;
Query 20240607_070109_00008_g445v, FAILED, 1 node
Splits: 1 total, 0 done (0.00%)
0.15 [0 rows, 0B] [0 rows/s, 0B/s]
Query 20240607_070109_00008_g445v failed: WRONGTYPE Operation against a key holding the wrong kind of value 
How to solve this

The document I am referring to is   ：https://trino.io/docs/current/connector/redis.html，
Can you give me a complete example of Redis

**Comment by ebyhr** [comment]
You can refer to test resources: https://github.com/trinodb/trino/tree/master/plugin/trino-redis/src/test/resources
Please feel free to continue at community Slack: https://trino.io/slack.html

**Comment by hope1234567hope** [comment]
thank，Due to geographical reasons, I am unable to join the at community Slack。not open  url。

now my redis clinent is
127.0.0.1:6379> hmset schema1.table2 username jack age 2
OK
127.0.0.1:6379> hgetall schema1.table2
"username"
"jack"
"age"
"2"
but this  json  how  write？can  you give me this json？ and how use trino-cli  search？ very thank！！！
