### ISSUE TITLE
Change length of `client_info` column in MySQL event listener

### ISSUE THREAD

**Issue by vjain143** [trinodb/trino#22362]
Change length of clintInfo Column in trino_event db trino_queries table from archer(255) to varcher(16777215)

Airflow populate this field and put the information below if dag name is longer and more than 255 event listener is unable to insert 

`{"dag_owner": \"airflow\", | "dag "{\"dag id\": \"create iceberg_tables_xyz\": \ "manual myk8s\", "create_mv "execution_date)": 1"2023-07-11T03:53:41.939266+00:00\", |"task_id\": 2023-07-1103: 53:41.939266+00:00\", iceberg_mytable"，V"try_ number": \"1\"}",`

**Comment by ebyhr** [comment]
You're using MySQL event listener and `clintInfo` means `client_info`, right?

**Comment by monmooney5523** [comment]
Yes we are using the MySQL Event Listener - client_info is correct

**Comment by avirlrma** [comment]
@ebyhr I can pick this up. I think we can just make the `client_info` a `MEDIUMTEXT` column, that will be in accordance with other columns also. 

Reference: https://github.com/trinodb/trino/blob/master/plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/QueryDao.java#L24
