### ISSUE TITLE
Expose alluxio file system stats via JMX

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#2240]
We should expose metrics of the communication between Presto and Alluxio too. When there is a failure unexpected long latency at Alluxio layer for whatever reason, Presto has no visibility of that.

FYI @apc999

**Comment by findepi** [comment]
Alluxio integration isn't really maintained. There is no point adding such troubleshooting statistics -- in quite a while no-one ever reported any environment with Alluxio installed.
