### ISSUE TITLE
Add support for comment on view

### ISSUE THREAD

**Issue by OmerJog** [trinodb/trino#2241]
Many DBs support:
`comment on view some_view is 'Some View';
`
Example:
https://stackoverflow.com/questions/4457656/create-view-in-postgres-sql-with-comments

can we have such support on presto?

**Comment by ebyhr** [comment]
> can we have such support on presto?

Yes, I created the prototype before. Let me submit the PR.

**Comment by OmerJog** [comment]
thx. looking forward to it.
Will it be in the next release?

**Comment by ebyhr** [comment]
Hmm, I think we can't merge it in the next version. Please wait for a while.

**Comment by OmerJog** [comment]
@ebyhr great. I hope this feature will be available soon

**Comment by ebyhr** [comment]
@OmerJog By the way, could you tell me the view type you want to add a comment, remote view (e.g. view in PostgreSQL) or Presto view?

**Comment by OmerJog** [comment]
@ebyhr that's exactly what I want.
Comments for native prestos views.

**Comment by hylas-dev** [comment]
Bump for this. Looks like comments can be put on views based on issue #2557 but "COMMENT ON VIEW" still has not been implemented.

**Comment by ebyhr** [comment]
Let us handle in #8349
