### ISSUE TITLE
High CPU usage when reading parquet with wide schema

### ISSUE THREAD

**Issue by davseitsev** [trinodb/trino#22434]
We have a use case when we store big structures to iceberg tables. Recently we have found a case where a structure has 45K+  nested fields totally. Simple select queries fail with `Exceeded CPU limit of 48.00h`. For example:

```sql
select * from events.trms.trm_crud
  where (
     laid='3f263312-22f0-22eb-868e-ee4cccb49114'
  or taid='3f263312-22f0-22eb-868e-ee4cccb49114'
  or luid='3f263312-22f0-22eb-868e-ee4cccb49114'
  )
  and ts >= from_unixtime(1672531200)
  and ts <  from_unixtime(1718235603)
order by ts;
```

Select `count()` with the same filters return 0 records, which means data filtering consume all the CPU.

<img width="901" alt="image" src="https://github.com/trinodb/trino/assets/1793410/0d7eb23e-14e7-457a-a775-69a838e505ef">

We ran CPU profiler on one of the workers and it showed that all the CPU is consumed by `IcebergPageSourceProvider.createParquetPageSource` method.

<img width="1169" alt="image" src="https://github.com/trinodb/trino/assets/1793410/03b10552-665b-4206-a674-beeeda834ad0">

There 2 loops which take all the CPU time. In the first one we try to find `ColumnChunkMetaData` by iterating through all the columns:
https://github.com/trinodb/trino/blob/ad97087b3939818e33511712b48b05419f4463cb/lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java#L496-L500

In the second one we iterate over all the columns to find column index:
https://github.com/trinodb/trino/blob/ad97087b3939818e33511712b48b05419f4463cb/lib/trino-parquet/src/main/java/io/trino/parquet/ParquetTypeUtils.java#L134-L151

As we do it for all the primitive fields, totally we call equals/equalsIgnoreCase more than 2B times. And it happens at least for each file (there are 1400 files in the table).

We are discussing changing schema of this table to use JSON. But anyway maybe it worth improving for smaller schemas.

Trino version: 444

**Comment by wendigo** [comment]
cc @raunaqmorarka

**Comment by raunaqmorarka** [comment]
@davseitsev could you try benchmarking your case with https://github.com/trinodb/trino/pull/22451 ?
There could be further improvements made, but I wanted to see if those changes are sufficient for your scenario.

**Comment by davseitsev** [comment]
Sure I will check it

**Comment by davseitsev** [comment]
Now it's a little bit better.

<img width="1094" alt="image" src="https://github.com/trinodb/trino/assets/1793410/abc7e517-7f44-4603-84b9-881948531cad">

In comparison to previous results I would say it's about 1.35x time better.

Flame graph looks similar:
<img width="1195" alt="image" src="https://github.com/trinodb/trino/assets/1793410/85c35592-e2a8-4973-8dbb-352cf5d4e4b6">

**Comment by raunaqmorarka** [comment]
That still looks strange because I removed the usage of ColumnPath#get from `getColumnChunkMetaData`, but it's still somehow showing in your flamegraph.

**Comment by davseitsev** [comment]
I will check it

**Comment by davseitsev** [comment]
Ok, it's my bad, I didn't deploy the change properly.

<img width="1142" alt="image" src="https://github.com/trinodb/trino/assets/1793410/53b830f1-1a88-454b-8ab6-db5b03d49e1b">


<img width="1247" alt="image" src="https://github.com/trinodb/trino/assets/1793410/c666e42b-8f39-44b1-8451-9233eb948d34">

**Comment by raunaqmorarka** [comment]
Okay, so we have improved significantly with the new changes but this needs further improvement still. Would you be able to share a sample file, table definition and test query with me so that I can assess potential optimizations more easily ?

**Comment by raunaqmorarka** [comment]
@davseitsev I've updated my PR with some more changes, I think the changes should help some more. Can you try out the updated PR as well ?

**Comment by davseitsev** [comment]
Sure I will test it and post the results today. Also I'm trying to write some unit test with our wide schema which can be used to estimate the changes.

**Comment by davseitsev** [comment]
Here is the result with the latest changes:
<img width="1289" alt="image" src="https://github.com/trinodb/trino/assets/1793410/d30a5511-7788-45f1-aeef-9bc5164b5f51">

<img width="1277" alt="image" src="https://github.com/trinodb/trino/assets/1793410/03f9ef87-4755-4e7b-8da2-fb9c84a509e6">

**Comment by raunaqmorarka** [comment]
Thanks @davseitsev 
We've essentially removed the bottleneck from `getDescriptors` call, but `getColumnChunkMetaData` still needs improvement. I will look for ways to address that in a different PR.

**Comment by davseitsev** [comment]
Here is the test you can use to understand the use case and profile it locally [TestIcebergWideSchemaRead.java.txt](https://github.com/user-attachments/files/15973046/TestIcebergWideSchemaRead.java.txt)
And there is table schema which is used in the test to create test table and generate test data: 
[create_table_no_formatting.txt](https://github.com/user-attachments/files/15973024/create_table_no_formatting.txt)

Test flame graph look similar to production one:
<img width="1259" alt="image" src="https://github.com/trinodb/trino/assets/1793410/41e94b19-1289-4b7d-af45-3cb1de337235">

If you have new changes I can test it on real data to compare total CPU time to previous results.


BTW I just thought, what about generating HashMap index here:
https://github.com/trinodb/trino/blob/ad97087b3939818e33511712b48b05419f4463cb/lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java#L180-L184
for all the columns in block, something like:
```java
 Map<ArrayWrapper, ColumnChunkMetaData> blocks = metadata.getColumns().stream().collect(Collectors.toMap(
        column -> new ArrayWrapper(column.getPath().toArray()),
        column -> column
));
```
And obtain necessary ColumnChunkMetaData from the map to avoid iterating over all the columns again and again. Can it cause any side effects?

**Comment by raunaqmorarka** [comment]
@davseitsev PTAL at https://github.com/trinodb/trino/pull/22538 . I think this should resolve the remaining bottlenecks as well. Please try it out and let me know.

**Comment by davseitsev** [comment]
Looks really good, total CPU time dropped to 1h.

<img width="1224" alt="image" src="https://github.com/trinodb/trino/assets/1793410/197cfc87-93a4-4d48-a33e-1963d9670578">

<img width="1600" alt="image" src="https://github.com/trinodb/trino/assets/1793410/6756b87c-d062-471c-b597-4459172fea7c">

**Comment by raunaqmorarka** [comment]
@davseitsev thanks for confirming. 
Could you also share the JFR/flamegraph file with me ? 
I suspect there may be more to improve here since majority of time spent is still in page source creation, but now the stacks are too narrow to fully see in the above image.

**Comment by davseitsev** [comment]
I've checked the `jfr` file, it contains a lot of internal stuff so unfortunately I can't share it.
I generated detailed call-tree graph, maybe it can provide some details which are not visible on the flame graph.

![image](https://github.com/trinodb/trino/assets/1793410/611a64e7-10b9-468a-b6e4-cdb1169fc8b3)
