### ISSUE TITLE
Insufficient Cache Control in admin UI page which contain user-supplied information

### ISSUE THREAD

**Issue by sug-ghosh** [trinodb/trino#22479]
Not setting the proper header values may cause browsers to store pages within their respective caches. On public, shared, or any other non-private computers, a malicious person may search through the browser cache to locate sensitive information cached during another user's session. 

In Trino WebUI also, we have all the query details pages, we are storing the cache in browser which should be remediated.

**Comment by wendigo** [comment]
Closed by https://github.com/trinodb/trino/pull/22502
