### ISSUE TITLE
Postgres Connector table function native query returns UTC+0 for now() function rather than user timezone

### ISSUE THREAD

**Issue by RealDeanZhao** [trinodb/trino#22510]
Trino Version：443
```
select
	*
from
	table(
catalog_postgresql_e674bfa71af14d6fbaced11ab687a209.system.query(
  query => 'select now()'
))
```
```
2024-06-26 11:55:09.531626 UTC
```
The query returns a UTC+0 time instead of current user timezone.  Is there any configuration to get the user local timezone data?

**Comment by hashhar** [comment]
the native functions runs natively on remote database hence it has no way to know what the Trino user's session timezone is.

If you want a specific timezone specify that in your query.

In general for native queries you must be aware that the Trino session is not anyhow related or passed through to the underlying database's session - so for session-dependent behaviour the queries must be written in a way to not depend on the session details.
