### ISSUE TITLE
[ORC]For timestamps(6) earlier than 00:00:00 on January 1, 1970, the ORC data read and written by the trino has a difference of 1 second

### ISSUE THREAD

**Issue by allenfudunhui** [trinodb/trino#22511]
Trino write: `Timestamp(6) '1969-01-01 00:00:00.000001'`
ORC data store: `Timestamp(6) '1969-01-01 00:00:01.000001'`

Spark write: `Timestamp(6) '1969-01-01 00:00:00.000001'`
ORC data store: `Timestamp(6) '1969-01-01 00:00:00.000001'`
Trino read: `Timestamp(6) '1968-12-31 23:59:59.000001'`

**Comment by raunaqmorarka** [comment]
This behaviour is intentional and was originally implemented in https://github.com/prestodb/presto/pull/10642
cc: @dain @electrum

**Comment by allenfudunhui** [comment]
Dear friend(s),
    It's my honor to hear from you! What a pity I'm not in just now, and I'll check it asap. Sorry for any inconvenience caused to you.
Thank you.
Best yours
Your Allen
