### ISSUE TITLE
[Bug][Trino 450] CASE Statements unexpectedly propagate NULL values 

### ISSUE THREAD

**Issue by whitleykeith** [trinodb/trino#22530]
This issue started occurring after upgrading from Trino 439 -> Trino 450. 

In Trino 450, CASE statements that previously worked as expected now start unexpectedly propogating NULL values, even when the CASE should never allow for that to happen. This seems to only happen if the source column in a conditional is NULL and not explicitly null-checked

Steps to reproduce:

Create test table with values

```SQL
create table scratch.foo (id integer, val varchar);
insert into scratch.foo VALUES (1, 'True'), (2, 'False'), (3, null)
```

Try to query it

```SQL
SELECT
CASE WHEN val = 'True' THEN TRUE
ELSE FALSE END AS boolean_value from scratch.foo;
```

Results:

```
 boolean_value
---------------
 true
 false
 NULL
```

This can be fixed by explicitly checking for nullness:

```sql
SELECT
CASE WHEN val = 'True' and val is not null THEN TRUE
ELSE FALSE END AS boolean_value from scratch.foo;
```

But pre 450 this wasn't the case. Has something changed with the logic to force explicit null checks?

**Comment by davigust** [comment]
Can also be reproduced from a CTE:
```
with src AS (
     select 1 as a, 'foo' as b
     union all
     select 1 as a, NULL as b
     )
select *,
   CASE WHEN b = 'goo' THEN TRUE ELSE FALSE END
from src


a |  b   | _col2
---+------+-------
 1 | foo  | false
 1 | NULL | NULL
```
