### ISSUE TITLE
CSV headers not getting added while writing to external location using CTAS

### ISSUE THREAD

**Issue by singhalkavmware** [trinodb/trino#22541]
Hi team,

I am exporting data into .gz files using the below query on Trino from AWS Glue tables.

`CREATE TABLE cht_mdr_temp.temp_table
WITH (external_location='s3://cht-mdr/mdr_temp/temp_table_kanika',format = 'CSV')
AS
SELECT pre_installed_software AS pre_installed_software, region_code AS region_code,  CAST(convertible_1yr_all_upfront_upfront_cost AS varchar) AS convertible_1yr_all_upfront_upfront_cost, 
FROM cht_mdr_temp.a0aapqkfo_1719536524875` 

The .gz files that are getting created does not contain the headers of the columns. We have tried using the property '`skip_header_line_count`' but it does not help. 

Is it possible to get CSV headers as per the aliases provided in the query, in the file exported via CTAS?

**Comment by findinpath** [comment]
```
testing/bin/ptl env up --environment multinode --config config-default
```


```
trino> create table hive.default.ht1 (col1 varchar, col2 varchar) with (format = 'csv', skip_header_line_count =1);
CREATE TABLE
trino> insert into hive.default.ht1 values ('a', 'A'), ('b', 'BB'), ('c', 'CCC');
INSERT: 3 rows
```


```
[root@hadoop-master /]# hdfs dfs -copyToLocal /user/hive/warehouse/ht1/20240705_203744_00013_c3tem_230893da-0298-4e21-8eb0-3604aed0c3c9.gz .
[root@hadoop-master /]# zcat 20240705_203744_00013_c3tem_230893da-0298-4e21-8eb0-3604aed0c3c9.gz
"col1","col2"
"a","A"
"b","BB"
"c","CCC"
```

Seems to be working for me

**Comment by singhalkavmware** [comment]
Thanks, we are able to get the headers in the csv file now.
