### ISSUE TITLE
ipv6 gp catalog query Failed

### ISSUE THREAD

**Issue by eyesmoons** [trinodb/trino#22614]
when I create a greemplum catalog with ipv6 address， and execute a query like this：select * from gp_v6.public.test_person limit 10; it says： SQL 错误 [67108864]: Query failed (#20240707_014710_00128_w92pq): FATAL: no pg_hba.conf entry for host "1200:300:1000::11", user "xxx", database "xxx", SSL off

**Comment by ebyhr** [comment]
We don't have Greenplum connector. Are you using PostgreSQL connector?

**Comment by eyesmoons** [comment]
thanks，pg_hba.conf need to set entry for host "1200:300:1000::11"
