### ISSUE TITLE
Add Apache Ranger authorizer plugin

### ISSUE THREAD

**Issue by mneethiraj** [trinodb/trino#22674]
Plugin to authorize data access in Trino using Apache Ranger policies is in Apache Ranger git repo - for more than 2 years. Trino authorizer interface, SystemAccessControl, continues to evolve with many updates (new methods, removed methods, signature changes). Apache Ranger community proposes to move the plugin implementation from Ranger git repo to Trino git repo, as this will make it easier to keep the plugin in sync with the authorizer interface evolution. This effort is tracked in Apache Ranger with [RANGER-4810](https://issues.apache.org/jira/browse/RANGER-4810).

**Comment by ebyhr** [comment]
Closing as #22675
