### ISSUE TITLE
Add support for `execute` procedure in Cassandra connector

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#22693]
Follow-up of https://github.com/trinodb/trino/pull/22556

1. Add `ExecuteProcedure` class that implements `Provider<Procedure>`. Inject `CassandraSession` and call `execute(String cql)` method. 
2. Bind the procedure in `CassandraClientModule` class
3. Override `getProcedures` method in `CassandraConnector` class
4. Add tests in `TestCassandraConnectorTest` class

**Comment by senlizishi** [comment]
Hi @ebyhr ,  can I try to work on this issue ?
