### ISSUE TITLE
Add support for `execute` procedure in BigQuery connector

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#22692]
Follow-up of https://github.com/trinodb/trino/pull/22556

1. Add `ExecuteProcedure` class that implements `Provider<Procedure>`. Inject `BigQueryClientFactory` and call `executeUpdate` method. 
2. Bind the procedure in `BigQueryConnectorModule` class
3. Override `getProcedures` method in `BigQueryConnector` class
4. Add tests in `BaseBigQueryConnectorTest` class

**Comment by unyimeudemy** [comment]
@ebyhr can I take up this issue
