### ISSUE TITLE
iceberg - dictionaryPagesSize and bloomFilter cannot both be set

### ISSUE THREAD

**Issue by raphaelauv** [trinodb/trino#22701]
hi , I can't run 

```sql
ALTER TABLE iceberg.default.AA EXECUTE optimize
```

on a table that have bloom filters

```sql
CREATE TABLE iceberg.default.AA 
( 
 created_at timestamp(6) NOT NULL,
 toto varchar NOT NULL
 ) WITH ( 
 format = 'PARQUET',
 format_version = 2,
 location = 's3://XXXX/default/AA',
 parquet_bloom_filter_columns = ARRAY['toto'],
 partitioning = ARRAY['hour(created_at)'] 
 )

```

it log

```log
dictionaryPagesSize and bloomFilter cannot both be set
```

**Comment by raunaqmorarka** [comment]
@jkylling PTAL

**Comment by jkylling** [comment]
It even fails on
```java
        String tableName = "parquet_with_bloom_filters_" + randomNameSuffix();
        CatalogSchemaTableName catalogSchemaTableName = new CatalogSchemaTableName("iceberg", new SchemaTableName("tpch", tableName));
        assertUpdate(format("CREATE TABLE %s WITH (format = 'PARQUET', parquet_bloom_filter_columns = ARRAY['t']) AS SELECT * FROM (VALUES 1, 1) s(t)", catalogSchemaTableName), 2);
```
If a page of a column chunk has dictionary encoding we currently do not write its values into the Bloom filter, but we will still try to write a Bloom filter for that column. Luckily this check caught it.

It probably makes sense to remove the check and do one of:
* Not write the Bloom filter if some pages of a column chunk are dictionary encoded?
* Always populate the Bloom filter in memory, but not write it if all the pages of a column chunk are dictionary encoded?

**Comment by illomi7** [comment]
Hi, any update on this?
We just upgrade our cluster from version 448 to 455 and figure it out we get the same error on an ingestion of our.
To fix the problem we decide to downgrade the version  to 451 but still get the error.
After that we find out that the last version not giving the error is the 450.

**Comment by AlekHed** [comment]
Same problem here for version 455. Bloom filters are broken.

**Comment by Firstero** [comment]
Same problem here for version 455. Bloom filters are broken.
