### ISSUE TITLE
Regression: Hive sync_partition_metadata function has become significantly slower when table has many partitions

### ISSUE THREAD

**Issue by guyco33** [trinodb/trino#22756]
Adding partitions to a table with 300K partitions with hive `sync_partition_metadata` function takes about 1 minute in `451` while in `452` it takes about 6 minutes.
For a table with 1M partitions the operation fails reaching `hive.metastore-timeout` (300sec)

This huge performance degradation is related to a change done in https://github.com/trinodb/trino/pull/22484
Maybe we can relax the new implemented constraints only when `case_sensitive` is false

**Comment by martint** [comment]
cc @ebyhr
