### ISSUE TITLE
Custom plugin SystemAccessControl cannot auth shutdown()

### ISSUE THREAD

**Issue by JRemitz** [trinodb/trino#22849]
Trino Version: `445`

We have a custom system-access plugin that extends `SystemAccessControl` that needed a refresh. In upgrading to recent versions, we've found that we can no longer authenticate `root` (or any user) to allow access to gracefully shutdown servers.  I may be misunderstanding how this pattern is done now, however the abstract method for [`shutdown()`](https://github.com/trinodb/trino/blob/e994585740f4ae936a47e860c264dd5484ec8c29/core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java#L953) does not have any context into the request, so I'm unclear how to authenticate that a user can be permitted to shutdown the server.  I've tried bypassing this and having multiple access-control plugins (file) to explicitly give permissions to `root` to shutdown, but this doesn't appear to work either.

I believe this was introduced in release [`414`](https://trino.io/docs/current/release/release-414.html#security)

Is there an example somewhere or could someone point me in the right direction on how to grant access in a custom plugin to give a user permission to shutdown or determine that they do have access to shutdown?

**Comment by JRemitz** [comment]
If it helps explain my thought process, I am looking at the super class method:
```java
default void shutdown()
```
and thinking it should be implemented as:

```java
default void checkCanShutdown(Identity identity)
```

but again, I may be misunderstanding the proper way to handle a shutdown and provide permissions.  Thank you in advance!

**Comment by ebyhr** [comment]
> I believe this was introduced in release [414](https://trino.io/docs/current/release/release-414.html#security)

No, version 440 added the method to destroy objects for fixing resource leaks: https://github.com/trinodb/trino/commit/995763b21ded84e945678a345d1d4d806db3124c

**Comment by wendigo** [comment]
Server shutdown requires a `MANAGEMENT_WRITE` permission that checks `checkCanWriteSystemInformation`

**Comment by wendigo** [comment]
Documented as: 
```
/**
     * Check if identity is allowed to write system information such as marking nodes
     * offline, or changing runtime flags.  This is typically allowed for administrators.
     *
     * @throws AccessDeniedException if not allowed
     */
    void checkCanWriteSystemInformation(Identity identity);
```

**Comment by JRemitz** [comment]
Okay, I thought it would have been that initially but I'm not seeing that function get called in my logs.  Possibly something I'm doing. I'll double check and confirm - thank you @wendigo and @ebyhr for the quick replies! 🙏🏻

**Comment by JRemitz** [comment]
I'm going to chalk this up as "user error." I think it was that my session config wasn't setup properly.  Thanks again!
