### ISSUE TITLE
Iceberg tables not registered in system.jdbc.tables

### ISSUE THREAD

**Issue by szisiu** [trinodb/trino#22868]
I found that Iceberg tables are not registered in `system.jdbc.tables` and `system.jdbc.columns`. 

I used to use IDEs (like IntelliJ, DBeaver) with the trino-jdbc driver jar to connect to my trino clusters and now those tools could not discover the existence of tables.

It stopepd working from trino `v443` (tested several older and newer versions up to `v453` with docker).

Note that tables exists and can be succefully queried (eg from java app with trino-jdbc driver) but it's annoying during development.

How to reproduce:

```sql
create schema iceberg.test with (location='s3a://test/test/'); -- minio
create table iceberg.test.tbl as select * from tpch.sf1.customer limit 10;
select * from system.jdbc.tables where table_cat = 'iceberg';
select * from iceberg.test.tbl;
```

This issue sounds similar to https://github.com/trinodb/trino/issues/11060

**Comment by ebyhr** [comment]
I can't reproduce the issue on master. Can you share `iceberg` config property after masking the confidential info? Also, did you enable metadata cache or something on those IDEs? 
![Screenshot 2024-07-30 at 8 24 35](https://github.com/user-attachments/assets/41abb344-c6a6-43ec-8dd0-7ebfeb250991)

**Comment by szisiu** [comment]
Sure. Let me share more details.

Environment:

- Ubuntu 22.04.4 LTS
- Docker version 27.0.3, build 7d4bcd8
- IntelliJ IDEA 2024.1.4

My containerized deployment consist of 1 trino v453 service (coordinator and worker with iceberg connector), 1 minio service, 1 mysql v8 and 1 hive metastore service (hms) .

Prepared and attached files we could use as an example.

[trino-docker-test.zip](https://github.com/user-attachments/files/16424223/trino-docker-test.zip)

Also this is my IJ setup for trino datasource (mostly defaults, except trino driver version and connection details):

![trino-ij-setup1](https://github.com/user-attachments/assets/b34d64dc-e2f0-40c2-9b13-6050237192e2)

![trino-ij-setup2](https://github.com/user-attachments/assets/fe16c10b-45cf-4a3d-b7c6-46e1ed95a534)

![trino-ij-setup3](https://github.com/user-attachments/assets/48d26e1d-b767-45d1-b8b8-3de4804f3fc2)

![trino-ij-setup4](https://github.com/user-attachments/assets/89389da0-75ab-4fa9-b1cc-74d94924eece)

No tables are displayed for the test schema but they exist and the data is there. Tried different settings also with all schemas enabled/visible.

![trino-ij-db-view](https://github.com/user-attachments/assets/c13054e7-ef80-489c-ba3a-e0f7325ba46c)

![trino-iceberg-ij-output](https://github.com/user-attachments/assets/7341bd95-88b2-442d-b55b-40793da74bc3)

![image](https://github.com/user-attachments/assets/1785fa12-7b40-4f3b-899e-2fe6ebe75073)

As mentioned the same issues happen when using eg DBeaver.

Thanks in advance.

**Comment by szisiu** [comment]
I tried again with `v454` without a success. Iceberg catalog and schema are listed but **tables are not**.

Did you have a change to look at the attached example?

**Comment by gietki** [comment]
Any new info? Dealing with the same situation

**Comment by szisiu** [comment]
Additional info: in my configuration Hive Metastore Standalone v3.1.0 is used as metadata catalog for Iceberg.

During the investigation in https://github.com/trinodb/trino/issues/23132 it appears that the problem **does not exist** when 

```xml
<property>
        <name>metastore.rawstore.impl</name>
        <value>org.apache.hadoop.hive.metastore.cache.CachedStore</value>
    </property>
```

property is removed from the Hive Metastore Standalone config (`metastore-site.xml`).

Moreover Iceberg tables are registered in `system.jdbc.tables` and `system.jdbc.columns`.

On the other hand leaving CachedStore enabled seems like a reasonable default for HMS (improves query performance - needs measurement to be sure).

Leaving the decision if there is something that needs improvement to the trino team.
