### ISSUE TITLE
Reject X-Forwarded-* headers behaviour breaks requests

### ISSUE THREAD

**Issue by huw0** [trinodb/trino#22865]
The fix described in #6552 (airlift/airlift#1183) now results in requests being rejected with a 406 error code when `X-Forwarded-*` headers are present but unwanted.

Broadly, I have the issues that @electrum describes as a potential issue in the comments. Some requests have been proxied and so have these headers.

Enabling `http-server.process-forwarded` is not desirable, because I do not want to trust the IP provided.

**Comment by wendigo** [comment]
So the X-Forwarded headers should be removed before they reach Trino coordinator

**Comment by electrum** [comment]
We can fix this by making `http-server.process-forwarded` be an enum of `{ TRUE, FALSE, IGNORE }` similar to @losipiuk's suggestion in the original discussion. This would be a backwards compatible change, but would allow ignoring such headers rather than rejecting the request.

**Comment by wendigo** [comment]
@electrum I can implement this. IGNORE will remove these headers so that jax-rs won't get it

**Comment by wendigo** [comment]
@electrum https://github.com/airlift/airlift/pull/1226
