### ISSUE TITLE
JDBC driver forces a username causing issues with external authentication

### ISSUE THREAD

**Issue by kirkhansen** [trinodb/trino#22901]
Prior to 453, access to a trino server using DBeaver and the Trino JDBC driver worked without passing an explicit username via the connection string. It seems the most recent release is forcing a default. This is problematic for use cases where we have OIDC auth and are using non-human-friendly principals. The example here is using `oid` or `sub` as the principal field, and that will not match the username returned by `java.lang.System.getProperty("user.name")` causing users to lookup their `oid` and put that in as a username field in dbeaver.

Was this an intentional side effect to force usernames when using external auth, or an artifact of resolving defaults causing a regression?

**Comment by wendigo** [comment]
@kirkhansen this is a regression

**Comment by wendigo** [comment]
@kirkhansen please use previous jdbc driver. They are compatible with the newer server and vice versa
