### ISSUE TITLE
Faced Lock issue when developed vertica connector

### ISSUE THREAD

**Issue by njalan** [trinodb/trino#22937]
I refer blow link to package one jar for vertica connector
https://github.com/darthskotina/trino-vertica-connector/tree/main

But faced below issues:
X lock Global Catalog - timeout error Timed out X locking Global Catalog. X held by [user xxx]

is there any suggestion on it?

**Comment by wendigo** [comment]
@njalan you should ask the author of this plugin. It isn't maintained by Trino project
