### ISSUE TITLE
Allow any subquery in SHOW STATS FOR

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#2294]
Today SHOW STATS allows only partition column predicates (in case of Hive connector).

Extend https://prestosql.io/docs/current/sql/show-stats.html `SHOW STATS` to allow any subquery.
This would make it easier to diagnose intermediate column stats derived from a subquery.

**Comment by findepi** [comment]
Alternatively we could extend `EXPLAIN` to show more stats information.

**Comment by ebyhr** [comment]
Closed via #3109
