### ISSUE TITLE
The way to pushdown to datasource when data is got from the same source

### ISSUE THREAD

**Issue by hntdtt** [trinodb/trino#22968]
I use trino to connect to some datasource: Clickhouse and iceberg... When I write a command to get data by sql command from the same source (clickhouse), Trino get all data from clickhouse after perform fillter condition (--> use a lot of ram and slow). When command only get from a source, I want to Trino push all command to source to execute and return result to have beter performance. Now, I see trino only pushdown a little command to source (only pushdown when fillter with varchar/string type column)

Thanks,

**Comment by ebyhr** [comment]
Please report the missing types in https://github.com/trinodb/trino/issues/7100
