### ISSUE TITLE
Impossible to do authentication in a mTLS Istio Mesh

### ISSUE THREAD

**Issue by imdominicreed** [trinodb/trino#22997]
I have Trino set up in an mTLS Istio mesh, with sidecars adding appropriate information needed for authentication. Requests need to be HTTP.

Looking into the [AuthenticationFilter](https://github.com/trinodb/trino/blob/ce90afa42dd1c65e3a261e052faf1b8fe9c7f71f/core/trino-main/src/main/java/io/trino/server/security/AuthenticationFilter.java#L70), seems like that's impossible since insecure authentication over HTTP is its on authenticator (it would be really nice if authentication would work over http, even just a config allowing that). 

If I added to the config`http-server.process-forwarded=true` it still gets denied.

if `X-Forwarded-Proto=https`  trino changes the URI to be https causing the trino client to use the wrong URL.
if `X-Forwarded-Proto=http` trino forbids the request.

**Comment by shantanu-dahiya** [comment]
I am also in the same situation. `http-server.process-forwarded=true` is not working. Perhaps the Trino JDBC driver will need to allow non-TLS authenticated connections with authentication.

**Comment by imdominicreed** [comment]
Note to people who want to solve this issue in the future with Istio, this is how I got around it.

Use TLS Origination with ISTIO to make the HTTP request to HTTPs, that way the AuthenticationFilter no longer blocks it.

But this will send future requests over HTTPS. So in the VirtualService set the `X-Forwarded-Host` to your host and `X-Forwarded-Proto` to `http` this will ensure that future request will be over http.

Ideally, a config where we can set this would be nice.

Hopes this helps! If you have a better solution let me know @shantanu-dahiya

**Comment by hashhar** [comment]
Closing since this duplicates https://github.com/trinodb/trino/issues/18387 and more discussion is already there.
