### ISSUE TITLE
SHOW TABLES hive slowdown as of v443

### ISSUE THREAD

**Issue by abridgett** [trinodb/trino#23038]
e.g for 70000 tables (ahem!) this was taking 4.5s but now takes 35s. 

This is often used by client UIs in addition to typical usage and so an optimised version is probably justified.

The root cause is that in https://github.com/trinodb/trino/pull/21114 the optimised "get_all_tables call was dropped in favor of reusing "get_table_meta".  (We don't want to cache to avoid dirty reads).

**Comment by ebyhr** [comment]
cc: @dain

**Comment by ebyhr** [comment]
Let's continue at #24164
