### ISSUE TITLE
S3Location should remove double slashes from `path`

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#23043]
`S3Location` doesn't remove double slashes from paths while HDFS `Path` and NIO `Path` do. This causes issues when Iceberg metastore returns path to table location with double-slashes. In native FS metadata file will be stored on S3 with double slashes (which is valid location), but it won't be possible to read it via legacy FS. For compatibility purposes `S3Location` should remove double slashes.

cc @electrum

**Comment by electrum** [comment]
These paths can be read due to `io.trino.filesystem.hdfs.HadoopPaths`. See `TestS3HadoopPaths`. Also, the legacy file systems will be removed in the near future.

**Comment by osscm** [comment]
hi @electrum can we we can add it,  for the backward compatibility,  till we remove the legacy one.
plus I believe a lot people will be transition mode or might legacy for a few more months/years :) 
and this will help, thanks!

**Comment by electrum** [comment]
No, this this will prevent reading any existing files that have double slashes in the path. As I mentioned, such paths should already be readable using legacy FS. If that is not working, can you provide a test?

What is blocking you from using the native FS? We have to remove the legacy one soon as it uses the AWS SDK v1 which is end of life and will no longer be updated.

**Comment by rstyp** [comment]
This could potentially lead to a problem if we commit files using `native-fs` that includes a double slash in the file path. When attempting to access these files from another Trino or Spark configured with `legacy-fs`, it might result in a '404 Not Found' error from S3.

**Comment by sopel39** [comment]
@electrum the problem is that initially table metadata was stored in `s3://bucket/schema/table/metadata/*` and it drifted to `s3://bucket/schema//table/metadata/*` which suggest `//` are erroneously along the way somwhere.

**Comment by electrum** [comment]
These locations are legal for both S3 and Iceberg. We have to support reading these locations. That's why we added the hack to the legacy FS to preserve the S3 location in the Hadoop path.

**Comment by electrum** [comment]
Are you saying that you have Iceberg manifest files containing locations that don't match the paths on S3?

**Comment by sopel39** [comment]
> Are you saying that you have Iceberg manifest files containing locations that don't match the paths on S3?

More like S3 paths to manifest that originally did have `/` have contain `//` which suggest a bug somewhere (either Trino or Iceberg or catalog)

**Comment by electrum** [comment]
Let’s determine how these are getting created.

**Comment by sopel39** [comment]
> Let’s determine how these are getting created.

There are most likely result of https://github.com/trinodb/trino/pull/23081
