### ISSUE TITLE
select all rows from table in mysql plugin MySqlClient in method getCaseSensitivityForColumns

### ISSUE THREAD

**Issue by coderwf** [trinodb/trino#23068]
MySqlClient class in mysql plugin, for getCaseSensitivityForColumns method, use `select * from table sql` to get metadata, if row amount of this table is very large, it will cost much time and cause much pressure on target db.

why not use limit 1 or get metadata form information_schema?

**Comment by ebyhr** [comment]
cc: @Praveen2112 @vlad-lyutenko

**Comment by vlad-lyutenko** [comment]
Hi, big thanks for info, as far as I see we get metadata from PreparedStatement, but don't actually execute the query:
```
try (PreparedStatement preparedStatement = queryBuilder.prepareStatement(this, session, connection, preparedQuery, Optional.empty())) {
            ResultSetMetaData metadata = preparedStatement.getMetaData();
```

In docs we have:
```
Retrieves a ResultSetMetaData object that contains information about the columns of the ResultSet object that will be returned when this PreparedStatement object is executed.
Because a PreparedStatement object is precompiled, it is possible to know about the ResultSet object that it will return without having to execute it. Consequently, it is possible to invoke the method getMetaData on a PreparedStatement object rather than waiting to execute it and then invoking the ResultSet. getMetaData method on the ResultSet object that is returned.
```

However there is a note:
`NOTE: Using this method may be expensive for some drivers due to the lack of underlying DBMS support.`

And another note:
```
Throws:
SQLFeatureNotSupportedException – if the JDBC driver does not support this method
```

Implementation is current:
for ClientPreparedStatement:

```
mdStmt = new ClientPreparedStatement(this.connection, ((PreparedQuery)this.query).getOriginalSql(), this.getCurrentDatabase(), this.getQueryInfo());
                            mdStmt.setMaxRows(1);
```

Maybe I miss somthing, did you perform any measurements with `SELECT *` vs `SELECT * LIMIT 1`

**Comment by vlad-lyutenko** [comment]
I think if we will notice any performance impact, we could try get case sensitivity based on table collation.

**Comment by coderwf** [comment]
@vlad-lyutenko This might be a good way

**Comment by coderwf** [comment]
> Hi, big thanks for info, as far as I see we get metadata from PreparedStatement, but don't actually execute the query:
> 
> ```
> try (PreparedStatement preparedStatement = queryBuilder.prepareStatement(this, session, connection, preparedQuery, Optional.empty())) {
>             ResultSetMetaData metadata = preparedStatement.getMetaData();
> ```
> 
> In docs we have:
> 
> ```
> Retrieves a ResultSetMetaData object that contains information about the columns of the ResultSet object that will be returned when this PreparedStatement object is executed.
> Because a PreparedStatement object is precompiled, it is possible to know about the ResultSet object that it will return without having to execute it. Consequently, it is possible to invoke the method getMetaData on a PreparedStatement object rather than waiting to execute it and then invoking the ResultSet. getMetaData method on the ResultSet object that is returned.
> ```
> 
> However there is a note: `NOTE: Using this method may be expensive for some drivers due to the lack of underlying DBMS support.`
> 
> And another note:
> 
> ```
> Throws:
> SQLFeatureNotSupportedException – if the JDBC driver does not support this method
> ```
> 
> Implementation is current: for ClientPreparedStatement:
> 
> ```
> mdStmt = new ClientPreparedStatement(this.connection, ((PreparedQuery)this.query).getOriginalSql(), this.getCurrentDatabase(), this.getQueryInfo());
>                             mdStmt.setMaxRows(1);
> ```
> 
> Maybe I miss somthing, did you perform any measurements with `SELECT *` vs `SELECT * LIMIT 1`

Thanks, I got it. I didn't do any performance testing.
It because I use a mysql plugin to connect and query doris(table contains one billion rows), and maybe that doris doesn't support sql_select_limit yet, so query is timeout, when I use `limit 1` explicitly, the query succeeds.
