### ISSUE TITLE
can't get trino.execution.executor:name=TaskExecutor.RunningSplits

### ISSUE THREAD

**Issue by wwbbcjeyc** [trinodb/trino#23078]
Introduce:
After upgrading to the v450 can't get trino.execution.executor:name=TaskExecutor.RunningSplits from http://worker:9300/v1/jmx/mbean .
Experimental config. experimental.thread-per-driver-scheduler-enabled was enabled by default since v438.When I disabled it, then this issue was removed..! 。

Problem:
There is no way to solve this problem without closing this configuration. Is there a new jmx  that can be replaced
```[tasklist]
### Tasks
```

**Comment by wwbbcjeyc** [comment]
> 您好，我们遇到了同样的问题。 我们想保留默认配置，但由于缺少指标...

https://github.com/trinodb/trino/pull/22914   I found a fix for this issue in the new version. The jmx bean TaskExecutor was indeed removed

**Comment by wwbbcjeyc** [comment]
> 您好，我们遇到了同样的问题。 我们想保留默认配置，但由于缺少指标...

 I found a fix for this issue in the new version. The jmx mbean TaskExecutor was indeed deleted. The new metrics are provided below
                   https://github.com/trinodb/trino/pull/22914

**Comment by raunaqmorarka** [comment]
Fixed by https://github.com/trinodb/trino/pull/22914
