### ISSUE TITLE
Iceberg REST configurable OAuth Endpoint

### ISSUE THREAD

**Issue by c-thiel** [trinodb/trino#23086]
[Recent changes in Iceberg REST](https://github.com/apache/iceberg/pull/10603/files#diff-02549ca620d020dc9ead80088cc14e311e12a69651fa8d394cd41a4308debb2e) deprecated the oauth2 endpoint as part of the REST spec. Instead, the OAuth2 endpoint of the IdP should be used.

**Extract from the spec:**
The `oauth/tokens` endpoint is **DEPRECATED for REMOVAL**. It is _not_ recommended to implement this endpoint, unless you are fully aware of the potential security implications.

All clients are encouraged to explicitly set the configuration property `oauth2-server-uri` to the correct OAuth endpoint.

It would be great to make the oauth2 server uri configurable by adding a `iceberg.rest-catalog.oauth2.server-uri` configuration for the Iceberg Rest Catalog.

**Comment by ebyhr** [comment]
cc: @findinpath @mayankvadariya

**Comment by c-thiel** [comment]
I noticed presto has implemented this now. Maybe it helps!
https://github.com/prestodb/presto/pull/23739
