### ISSUE TITLE
Reduce slack channels

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#23122]
A number of channels are pretty much dead .. we need to remove those, consolidate that scope into other channels and potentially replace some with fewer channels with a wider scope.

**Comment by mosabua** [comment]
I had a look now and propose we remove the following channels

* absence (can just use maintainers channel for that)
* bentito-k8s-operator
* community-discussions
* company-goldman-sachs
* company-redis
* csclient
* dbt (maybe, just refer users to python channel and dbt slack)
* exasol-connector 
* maintainer-devrel
* materialized-views
* new-expressions
* pinot
* private-team-developer-relations
* project-names
* redis
* salesforce
* sensitive-identifiers
* snowflake (maybe)
* starburst-galaxy 
* tmp-book-cn
* tmp-contrib-collab-sync
* tmp-follow-redirect
* tmp-vertica-connector
* trino-contributor-congregation (maybe rename or open up and reuse for all calls as well)
* trino-website (we can include that in documentation channel)
* vendor-quobole
* vendor-tabular

I also suggest we change the name of the following channels to indicate that they are temporary:

* aircompressor - tmp-aircompressor (and later just in airlift)

**Comment by dain** [comment]
I'm cool with this

**Comment by mosabua** [comment]
One thing I am not sure how to best deal with is the different clients and related ecosystem .. currently its kinda inconsistent

* Jdbc has no channel
* cli has no channel
* dbt has its own channel but kinda belongs to python client and really into the dbt slack for most questions
* python-client is used as channel name but it also covers the wide ecosystem, slqalchemy and so on
* javascript-client might also need a wider scope since it also covers things like usage in node/npm
* go has no channel .. which is probably fine

But all that can be part of a separate follow up clean up. Just putting it here since I am thinking about it currently when looking at the list

**Comment by mosabua** [comment]
@dain @electrum and @mosabua agreed to proceed with archiving the channels in the list above.

**Comment by mosabua** [comment]
We are going to open a thread around the client channels to discuss this proposal:

* Remove all client channels
* Redirect users of clients to beginner and troubleshooting
* Create a new client-dev channel that is used for discussion and more around all the client development work and also touched on protocol changes and such
* Use the announcements channel for any release announcements of any libraries or components including all clients with separate release cycle (python, js, ..) and projects like Trino Gateway

**Comment by mosabua** [comment]
Channels in the list are all archived now. Announcement with request for feedback/help is also posted.

**Comment by hashhar** [comment]
IMO we should keep having channels focused on language/clients. Makes it much easier for experienced community members to help too. In Python channel for example people often answer each other and it's also easier for me to be sure all the requests there are things I should look at.

The fact that other language channels don't get enough attention is because we don't ask people to move there. For python related stuff we often ask people to move discussion to python channel.

Also consider that some of those questions are not even about Trino directly but the language ecosystem like DBT for example in Python.

**Comment by mosabua** [comment]
Yeah @hashhar .. for lively communities I think it makes sense to keep one channel .. so maybe for python .. but for that ecosystem we should probably drop dbt and discuss that an other stuff in the python channel. Sounds good? 

i am thinking that javascript will be similar soon.

so which ones do we want 

and what names should we do

**Comment by hashhar** [comment]
> we should probably drop dbt and discuss that an other stuff in the python channel.

I agree.

> so which ones do we want

I think Python and JavaScript deserve their own "ecosystem" at this stage.

Go, C# etc. don't have the volume for the "ecosystem" to be useful as of now AFAIK.

**Comment by mosabua** [comment]
Great .. i think we have a plan forward then

**Comment by hashhar** [comment]
Maybe just `#python-ecosystem/#javascript-ecosystem` to be less wordy? Naming is hard, and I'm particularly bad at it. 😄

**Comment by mosabua** [comment]
We renamed to `#python` and `#javascript` as decided by @dain and @martint . This keeps it clean and simple. 

Last task is to potentially close the dbt channel and send users to the python channel. 

O
