### ISSUE TITLE
JMX metric collection on native S3 file system

### ISSUE THREAD

**Issue by ljw9111** [trinodb/trino#23177]
### Overview
The goal of this issue is to add support for JMX metrics collection on native S3 file system. Currently, Trino doesn’t have JMX metric collection in native file system from [S3FileSystemLoader](https://github.com/trinodb/trino/blob/3c95ec13a6760dcb9831a71559f8ff299b20fb27/lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemLoader.java#L114) while we have it in legacy S3 file system in [TrinoS3FileSystemStats](https://github.com/trinodb/trino/blob/3a72d9c4de4642ecd5da09529763ea9ca66be397/lib/trino-hdfs/src/main/java/io/trino/hdfs/s3/TrinoS3FileSystemStats.java#L26) which is related to Trino official docs [Monitoring with JMX](https://trino.io/docs/current/admin/jmx.html) and [JMX connector](https://trino.io/docs/current/connector/jmx.html). I'm currently working on this with the below implementation plan. Please let me know if there's any feedback on the issue itself and the implementation plan. 

### Implementation Plan
1. AwsSdkV2ApiCallStats class
I plan to add new AwsSdkV2ApiCallStats class which will be used to track core metrics per API operations (e.g. getObject, listObjectsV2). This will track metrics e.g. latency, call count, failure count, retries, throttling count, server errors based on AWS SDK V2's core metrics defined in [here](https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/metrics/CoreMetric.java). 

2. S3FileSystemStats class
Similar to [TrinoS3FileSystemStats](https://github.com/trinodb/trino/blob/3a72d9c4de4642ecd5da09529763ea9ca66be397/lib/trino-hdfs/src/main/java/io/trino/hdfs/s3/TrinoS3FileSystemStats.java#L26) we have for the legacy S3 file system, I plan to add new S3FileSystemStats class which includes all the JMX metrics to be collected for native file system. It will have 1. per API metrics, 2. total metrics over all APIs. I will use AwsSdkV2ApiCallStats defined above to list APIs to be tracked e.g. `private final AwsSdkV2ApiCallStats createMultipartUpload = new AwsSdkV2ApiCallStats();`. 

3. JmxMetricPublisher
Since native S3 file system uses AWS SDK V2 instead of V1 which was used for the legacy file system, I plan to define new JmxMetricPublisher implementing [MetricPublisher](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/metrics/MetricPublisher.html). This will be passed as a parameter when we initialize S3 client in SDK V2. MetricPublisher basically has only two methods `publish` and `close`. So in JmxMetricPublisher's `publish`, we plan to utilize [OPERATION_NAME](https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/metrics/CoreMetric.java#L40) and use it to update counters for each API metrics defined in S3FileSystemStats class.

I plan to add PR on this issue soon and we can discuss further. I appreciate for any feedback. Thank you!
```[tasklist]
### Tasks
```

**Comment by hashhar** [comment]
cc: @electrum

**Comment by electrum** [comment]
This plan looks good to me. Thanks for writing it up.

**Comment by ljw9111** [comment]
Thank you all! The PR is merged. Closing the issue.
