### ISSUE TITLE
Read Json formatted API response

### ISSUE THREAD

**Issue by shoaibahmed9922** [trinodb/trino#23171]
Does http connector allows reading json formatted API responses as well?
I have seen only csv examples in the repo..

**Comment by nineinchnick** [comment]
You mean the `trino-example-http` connector? I don't think so. It's an example connector that can be used as a base for building a custom one. You could try extending it to parse JSON.

You could also try https://github.com/nineinchnick/trino-openapi/. If the HTTP endpoint you want to read from doesn't provide an OpenAPI spec, you can write one yourself.
