### ISSUE TITLE
Slack invite link no longer active (again)

### ISSUE THREAD

**Issue by codesorcery** [trinodb/trino#23232]
Slack responds with `This link is no longer active` when clicking on the invite link on https://trino.io/slack.html

Seems like it's the same problem as previously in #8415 #12470 #16096 #18433 #20149

**Comment by wendigo** [comment]
@mosabua @martint help :)

**Comment by wendigo** [comment]
In the meantime: https://join.slack.com/t/trinodb/shared_invite/zt-2pytc4775-wqH1j5Jz1gSOKnb5onCUTg

**Comment by wendigo** [comment]
These links are valid for 30 days hence the need to update them

**Comment by martint** [comment]
The links are supposed to never expire based on time, but I think there's a limit on the number of signups they will allow.

I've updated the link on the website.

**Comment by mosabua** [comment]
From what I can tell this expiring based on time and number of registrations even when set to "never expire" is on purpose from slack and wont change. The best tips I have seen are to have a script that runs and tests regularly. 

https://www.reddit.com/r/Slack/comments/cmj56t/invite_link_set_to_never_expire_expired/

https://github.com/open-metadata/OpenMetadata/blob/main/scripts/slack-link-monitor.py

Maybe we can implement a github action run on the trino.io repo that checks the link once a day and does some notification when it expired. Then we still have to manually update the site but at least we will catch it earlier. 

This GH Action might work for it https://github.com/marketplace/actions/http-check-url

**Comment by sunghj1118** [comment]
> In the meantime: https://join.slack.com/t/trinodb/shared_invite/zt-2pytc4775-wqH1j5Jz1gSOKnb5onCUTg

Thank you, the link you provided works as of Jan 2026. However, it seems that the [slack link](https://join.slack.com/t/trinodb/shared_invite/zt-3fn43nzgw-XTqIn4ZVlWPZAh2sznxgyA) in the official trino site (https://trino.io/slack.html) and [trino slack redirect link](https://trinodb.slack.com/ssb/redirect) have also gone stale, as they both keep returning the expired link issue.

**Comment by mosabua** [comment]
Can you send a PR for https://github.com/trinodb/trino.io/blob/master/slack.md   @sunghj1118  .. then I can review and merge

**Comment by sunghj1118** [comment]
Sure thing. I have submitted the CLA and sent a PR. Please let me know if I need to do anything else.
