### ISSUE TITLE
Add docs for Authenticated Proxy configuration

### ISSUE THREAD

**Issue by Praveen2112** [trinodb/trino#23297]
This PR https://github.com/airlift/airlift/pull/1231 adds authentication support for Proxy and we would like to update the docs for the same in https://trino.io/docs/current/admin/properties-http-client.html#proxy-properties.

**Comment by mosabua** [comment]
Sounds good. You are going to send a PR or is this for anyone in the community to pick up?

**Comment by marcinsbd** [comment]
PR is merged so I'm closing the issue.
