### ISSUE TITLE
to_iso8601(from_unixtime( ... )) returns 0NaN-NaN-NaN inside a map()

### ISSUE THREAD

**Issue by nfriend** [trinodb/trino#23315]
## Steps to Reproduce
Run this query:

```sql
select
  to_iso8601(from_unixtime(1725631307.027)) as "a_date_string",
  map(
    array['a_date'],
    array[to_iso8601(from_unixtime(1725631307.027))]
  ) as "a_map_with_a_date_string"
```

## Expected Behavior
I expect `to_iso8601(from_unixtime(1725631307.027))` to work the same both in and outside the context of a `map()`:

| a_date_string | a_map_with_a_date_string |
| - | - |
| 2024-09-06 14:01:47.027 | {"a_date":"2024-09-06 14:01:47.027"} |

## Current Behavior
The `map()` call evaluates to `0NaN-NaN-NaN`:

| a_date_string | a_map_with_a_date_string |
| - | - |
| 2024-09-06 14:01:47.027 | 0NaN-NaN-NaN |

## My environment
I'm using release 414.

**Comment by wendigo** [comment]
It works in the latest version:

```
trino> select
    ->   to_iso8601(from_unixtime(1725631307.027)) as "a_date_string",
    ->   map(
    ->     array['a_date'],
    ->     array[to_iso8601(from_unixtime(1725631307.027))]
    ->   ) as "a_map_with_a_date_string";
         a_date_string         |        a_map_with_a_date_string
-------------------------------+----------------------------------------
 2024-09-06T16:01:47.027+02:00 | {a_date=2024-09-06T16:01:47.027+02:00}
```

**Comment by nfriend** [comment]
Cool, thanks!
