### ISSUE TITLE
 Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.15.0:npm (package (webapp)) on project trino-web-ui

### ISSUE THREAD

**Issue by developer-guy** [trinodb/trino#23334]
We were trying to upgrade the trino from version 453 to 457 but the build breaks to due following issue:

```bash
Error: /08 13:35:11 INFO [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.15.0:npm (package (webapp)) on project trino-web-ui: Failed to run task: 'npm run package' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 127 (Exit value: 127) -> [Help 1]
```

We were using the maven command be like:

```bash
      ./mvnw package -q -DskipTests -Dmaven.source.skip=true -Dair.check.skip-all -T 8  -pl '!:trino-docs,!:trino-server-rpm,!:trino-tests,!:trino-product-tests,!:trino-product-tests-launcher' -am
```

You can find more info here: https://github.com/wolfi-dev/os/pull/27848/files

**Comment by martint** [comment]
cc @wendigo

**Comment by wendigo** [comment]
What os are you using? That works fine on macos/linux. Can you share more of the error message? Exit code 127 tells nothing

**Comment by developer-guy** [comment]
I used -X option for enabling the debug log but it didn't tell much either, I shared the whole error message with you.

**Comment by wendigo** [comment]
can you go into the directory: `core/trino-web-ui/src/main/resources/webapp/src` and run
`npm clean-install` and `npm run package` ?

**Comment by developer-guy** [comment]
yeah, it did that already and it worked without any issue 🫠

**Comment by wendigo** [comment]
Well, I can't help you without this kind of a detail.

**Comment by wendigo** [comment]
I'm closing until further information is provided. Project builds fine locally, on the CI, in the reproducible central (https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/io/trino/README.md)
