### ISSUE TITLE
log https cipher used by client to connect to presto server

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#2337]
from slack

how to know what https cipher a client used to run a sql? context is want to tighten the ciphers list but dont want legacy clients to face error

First step is to see if Jetty provides that information to the HTTP request object. If it does, you could add some logging for it.

https://blogs.oracle.com/java-platform-group/diagnosing-tls,-ssl,-and-https shows an example of this with 'Example of diagnosing a problem' section. would also be useful to log http 1.1vs2 is used or tls version ( ie 1.2 or 1.3)

still to try below with https but extremely noisy:
cat etc/log.properties
io.prestosql=DEBUG
com.sybase=DEBUG
javax.net=DEBUG
io.airlift=DEBUG
org.eclipse.jetty=DEBUG

etc/jvm.config
-Djavax.net.debug=all     (or -Djavax.net.debug=ssl,handshake,data)

more notes:
https://stackoverflow.com/questions/29245586/debugging-jetty-https -DDEBUG=true -Dorg.eclipse.jetty.LEVEL=DEBUG
https://lightbend.github.io/ssl-config/DebuggingSSL.html -Djava.security.debug=

potentially change would go in https://github.com/airlift/airlift/tree/master/http-server/src/main/java/io/airlift/http/server

**Comment by hashhar** [comment]
This might be useful but should be implemented either at a proxy/gateway or in Airlift. Not Trino.

Closing. Feel free to file against airlift if still relevant.
