### ISSUE TITLE
Persist JWT auth Token 

### ISSUE THREAD

**Issue by jimPeill** [trinodb/trino#23404]
Requirements:
To persist JWT token while authentication and after, in order to check user authentication and related ACLs on every SQL Trino request (not only for login).

Trino improvements:
In JWTAuthenticator, add an access token attribute while creating Identity

**Comment by wendigo** [comment]
This isn't something that we are going to do. Closing.

**Comment by jimPeill** [comment]
@wendigo  I mean I cannot save any new attributes to the user Identity. I could be interesting to allow that feature, in order to save headers / token ... for proxy access, web service call, identity provider...

**Comment by hashhar** [comment]
use `extraCredentials` for that, not `Identity`. Using Trino Identity for pass-through authentication is problematic for various reasons. One of the obvious ones being user-mapping - a principal name on source != trino != your access control system.
