### ISSUE TITLE
Lost the ability of omit the remainingExpression in ConstraintApplicationResult constructor

### ISSUE THREAD

**Issue by YuriSmychkovich** [trinodb/trino#23465]
#23272 introduces the problem: One not able to omit the `remainingExpression` in `ConstraintApplicationResult` constructor anymore. Null value is not accepted because `Optional.of(remainingExpression)` would throw NPE. 

The problem could be fixed by replacing `Optional.of(remainingExpression)` with `Optional.ofNullable(remainingExpression)`

**Comment by martint** [comment]
Use TRUE to represent a residual filter that shouldn’t filter any rows.
