### ISSUE TITLE
Performance Issue with Retrieving Columns from Iceberg Catalog

### ISSUE THREAD

**Issue by shohamyamin** [trinodb/trino#23468]
Hi,

We are experiencing a performance issue when retrieving column metadata from the Iceberg catalog using the following query:

```sql
SELECT * FROM iceberg.information_schema.columns;
```

In our environment this query takes approximately 30 seconds to return results with clean cache, and we have around 500 tables with 3.5k columns in total.

From our analysis of the logs on both the Iceberg catalog and Trino side, it appears that requests to the catalog might be executed sequentially for each table.

### Setup Details:
- **Trino version**: 453

We tried both catalogs:
- **Nessie version**: 0.94.4 -with PostgreSQL configuration
- **Catalog**: [Tabular REST Catalog example (based on JDBC)](https://github.com/tabular-io/iceberg-rest-image) 

[link](https://trinodb.slack.com/archives/CJ6UC075E/p1726594499184929)  to slack discussion

To investigate the performance issue, I set up a Docker Compose environment with  Trino 451 and the latest versions of the REST catalog, and the Nessie catalog (using in-memory configuration), along with MinIO for Iceberg data storage and Jaeger for tracing. This test was conducted on my laptop, which has 32GB of RAM and an Intel Core 9 processor.

I executed the following SQL query for both the REST and Nessie catalogs:

```sql
SELECT * FROM iceberg.information_schema.columns;
```

After each query, I restarted Trino to clear the cache.

Here are the results for 500 tables, each containing 10 columns (a total of 5,000 columns):
- Nessie catalog: 9.09 seconds
- REST catalog: 9.03 seconds

I suspect that the reason I observed these better performance results compared to my Kubernetes cluster is due to the local setup. Running MinIO locally allows for a closer proximity to Trino, reducing latency.

Is there any optimization or configuration change we could apply to improve the performance of this query? Additionally, any insights into the sequential request behavior would be helpful.

Thanks in advance for your assistance!

Here are some of the tracing(thanks @mosiac1 for the advice it is very useful )  that i got from open telemetry:

Timelines of both nessie and rest:
![nessie_timeline](https://github.com/user-attachments/assets/45a8ca00-e759-4049-9d3b-945f631596e0)
![rest_timeline](https://github.com/user-attachments/assets/56c83ceb-0158-4d24-8b28-9b11231c3ea6)

You can see in the nessie(for some reson it is more detailed than the rest) timeline that for each table it makes a get from the s3 and it do it one after the other. 
![nessie_get_column_list_timeline](https://github.com/user-attachments/assets/998d0032-9272-4619-b72d-d9638cee35ba)

Here is the tracing as table:
![nessie_table](https://github.com/user-attachments/assets/5024b326-f854-4508-bea8-8c1667b6e335)
![rest_table](https://github.com/user-attachments/assets/165ec8a4-e72b-4a72-a802-4aa458d55b62)

Here are the jsons of the tracing if someone wants to load them to jaeger:
[rest_jaeger_columns_benchmark.json](https://github.com/user-attachments/files/17067836/rest_jaeger_columns_benchmark.json)
[nessie_jaeger_columns_benchmark.json.json](https://github.com/user-attachments/files/17067842/nessie_jaeger_columns_benchmark.json.json)

**Comment by shohamyamin** [comment]
@mosiac1 @ebyhr @findepi I added some tracing information that show the problem and maybe will help to understand why and how to deal with that.

**Comment by sopel39** [comment]
@shohamyamin perhaps https://github.com/trinodb/trino/pull/22739 could help in your case. It requres 454. cc @raunaqmorarka

**Comment by alonahmias** [comment]
Do you know the answer to this question?
https://github.com/trinodb/trino/pull/22739#pullrequestreview-2187805641
Because the select from information schema is being done by the coordinator

**Comment by sopel39** [comment]
Yes, its created specifically for coordinator

**Comment by shohamyamin** [comment]
The cache is being preformed before the filter columns apply for the specific user that has being logged in?

Because each user has access to different columns
and our problem is that we need that information has the user login to Trino using our system. So the first time should be very fast

Another question this cache is separated from the regular cache?

**Comment by mosiac1** [comment]
I think its worth understanding why the traces from the Rest catalog do not show S3 operations. I am not very familiar with how Iceberg catalogs work (besides the very basic JDBC one), but from the traces I'm guessing Trino is delegating fetching of metadata to the Rest catalog - in that case there isn't much that can be done on the Trino side.

Another observation is that in the Nessie trace the `ConnectorMetadata.streamRelationColumns` span is 8.94s, but the self-time (time spent not waiting on children) is `5752.43ms`, which implies Trino is spending some time on processing as well, this isn't bound just by IO.

In any case, its probably a good idea to do the S3 reads in parallel.

For your test, was Trino is a coordinator-only setup? Wondering is this would generate multiple splits, but I doubt that.

IMHO parallel reads of metadata files in Trino would be a band-aid solution. If you want this to fast (sub 500ms) you likely want to delegate the a Rest Iceberg catalog that reads from a Redis cache or Postgres DB without ever going to S3.

**Comment by shohamyamin** [comment]
Yes, the Trino setup for this test is indeed coordinator-only.
And i agreed that making thous s3 requests in parallel will improve significant time 

The s3 GET requests are not preformed by Trino?

About that self-time that can't be affected also by that trino need to wait for the responses?

**Comment by shohamyamin** [comment]
@mosiac1 , it looks like this is the for loop performing the S3 get request synchronously:


[link to code](
https://github.com/trinodb/trino/blob/52b98d56ab5ec57c0d77cfb51ff2ffcac8d5bbcc/core/trino-main/src/main/java/io/trino/connector/system/jdbc/ColumnJdbcTable.java#L282C1-L290C22)
