### ISSUE TITLE
Fix and reenable S3 Select for table with skip.header.line.count=1

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#2349]
Hive table property `skip.header.line.count` seems to be ignored when S3 Select is enabled.

**Comment by findepi** [comment]
S3 Select supports skipping first header line, but it was not working for me correctly in my testing.
We disable S3 Select for uncompressed files.
cc @same3r

**Comment by same3r** [comment]
Hey, sorry for the delay in response. I have forwarded the issue to the concerned team to provide an ETA on the fix.

**Comment by findepi** [comment]
(I removed `correctness` and `bug` labels, because the bug is fixed from Presto perspective.)

**Comment by hashhar** [comment]
S3 select is gone after https://github.com/trinodb/trino/pull/18241
