### ISSUE TITLE
fs.cache seems to be enabled by default

### ISSUE THREAD

**Issue by metalshanked** [trinodb/trino#23517]
Upgraded from 454 to 458 and see below errors on many iceberg queries.
The doc says that fs.cache is disabled by default and I dont have any configs set for enabling cache yet the stacktrace seems to suggest that caching is being used
`Failed to open file: io.trino.filesystem.cache.CacheInputFile@3849a554`

Can you please advise?
Thanks!

```
{"type":"org.apache.iceberg.exceptions.RuntimeIOException","message":"Failed to open file: io.trino.filesystem.cache.CacheInputFile@3849a554","cause":{"type":"org.apache.avro.InvalidAvroMagicException","message":"Not an Avro data file","suppressed":[],"stack":["org.apache.avro.file.DataFileReader.openReader(DataFileReader.java:79)","org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:102)","org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:77)","org.apache.iceberg.io.CloseableIterable$7$1.<init>(CloseableIterable.java:188)","org.apache.iceberg.io.CloseableIter
```

**Comment by wendigo** [comment]
Cc @raunaqmorarka

**Comment by raunaqmorarka** [comment]
Filesystem cache is different, this is an in-memory cache of iceberg metadata that is enabled by default. It can be disabled using `iceberg.metadata-cache.enabled=false`.
Can you show the full error stacktrace ?

**Comment by metalshanked** [comment]
Thanks @raunaqmorarka. seems like a standard issue of a corrupted avro on my side.
Thanks for clarifying that file cache here is a metadata cache not the main cache and so it is not any bug on the Trino side.

**Comment by raunaqmorarka** [comment]
Thanks for the confirmation
