### ISSUE TITLE
physicalInputDataSize greater than the HDFS file size 

### ISSUE THREAD

**Issue by wuLeranCode** [trinodb/trino#23530]
Table storage format is Parquet
![image](https://github.com/user-attachments/assets/be8e0ef2-ca8d-4e2a-9ae0-0e009268bd8f)

hdfs file size total is 4.42KB
![image](https://github.com/user-attachments/assets/adc36b28-a881-42d1-b75c-abf8a206074c)

select * from hive.default.scan_test1;

but WEB UI Physical Input Data is 5.75KB
![image](https://github.com/user-attachments/assets/7dcc410e-d8e1-4885-8be1-9ff25f6c51be)

```[tasklist]
### Tasks
```

**Comment by wendigo** [comment]
What's the issue here?

**Comment by wuLeranCode** [comment]
> What's the issue here?

when select * from table，why Physical Input Data size is greater than the actual hdfs file size?

**Comment by Akanksha-kedia** [comment]
trino:akk10> CREATE TABLE ana (
          ->     id BIGINT,
          ->     name VARCHAR,
          ->     salary DOUBLE,
          ->     hire_date DATE
          -> )
          -> WITH (
          ->     format = 'PARQUET'
          -> );
CREATE TABLE
trino:akk10> INSERT INTO ana(id, name, salary, hire_date) VALUES
          ->     (1, 'Alice', 75000.00, DATE '2023-01-15'),
          ->     (2, 'Bob', 82000.00, DATE '2022-11-23'),
          ->     (3, 'Charlie', 67000.00, DATE '2021-07-01');
INSERT: 3 rows

Query 20240924_093513_00013_i4kuw, FINISHED, 1 node
Splits: 44 total, 44 done (100.00%)
11.22 [0 rows, 0B] [0 rows/s, 0B/s]

trino:akk10> select * from ana;
 id |  name   | salary  | hire_date  
----+---------+---------+------------
  1 | Alice   | 75000.0 | 2023-01-15 
  2 | Bob     | 82000.0 | 2022-11-23 
  3 | Charlie | 67000.0 | 2021-07-01 
(3 rows)

Query 20240924_093537_00014_i4kuw, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
2.03 [3 rows, 722B] [1 rows/s, 355B/s

**Comment by Akanksha-kedia** [comment]
hdfs dfs -du -s -h /hive/external/hive/akk10.db/ana
722  2.1 K  /warehouse/tablespace/external/hive/akk10.db/ana

<img width="589" alt="Screenshot 2024-09-24 at 3 08 45 PM" src="https://github.com/user-attachments/assets/a324765b-35c4-4800-83a6-4ac09dbd5a75">

**Comment by Akanksha-kedia** [comment]
@wuLeranCode could u explain more on this.

**Comment by raunaqmorarka** [comment]
Closing based on above.
Please re-open if it's reproducible on a recent version.
