### ISSUE TITLE
Support `select * exclude(list, of, columns) ...` and `select * replace(a as b, ...) ...` like BigQuery, DuckDB, Snowflake

### ISSUE THREAD

**Issue by neilmcguigan** [trinodb/trino#23532]
data warehouses tend to have lots of columns! so it'd be handy to select all except a few...

BigQuery: https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#select_list

Snowflake: https://docs.snowflake.com/en/sql-reference/sql/select

DuckDB: https://duckdb.org/docs/sql/query_syntax/select.html

**Comment by ebyhr** [comment]
You can use `exclude_columns` table function: https://trino.io/docs/current/functions/table.html#exclude-columns-table-function
