### ISSUE TITLE
Document how to to configure multiple azure storage accounts in single catalog using native-azure

### ISSUE THREAD

**Issue by AlakmarShafin** [trinodb/trino#23538]
There is no way to confugure multiple azure storage account in a single delta lake connector when **fs.native-azure.enabled=true** as core-sites.xml is not used when this config property is true and if we are going to depreciate legacy azure connector there will be no way to do so.

**Comment by hashhar** [comment]
cc: @anusudarsan / @electrum

**Comment by anusudarsan** [comment]
Im looking into this. Will update shortly

**Comment by anusudarsan** [comment]
@AlakmarShafin I just verified that you can use [oauth](https://trino.io/docs/current/object-storage/file-system-azure.html#oauth-2-0-authentication) authentication to achieve this . 

1. You will have to create a service principal in Azure (App registrations).  Take a note of client secret to use in Trino config later. 
2. For all storage accounts you want to access from Trino, assign the appropriate policies for your service principal.
```
Select Access Control (IAM) - > Click Add role assignment. -> Select the appropriate Role (e.g., Storage Blob Data Contributor or Storage Account Contributor) -> In the Assign access to dropdown, choose User, group, or service principal ->  Search for the service principal you created -> Save.

```
3. Once the Azure set up is complete, in Trino you can use the following config. 

```
fs.native-azure.enabled=true
azure.auth-type=oauth
azure.oauth.endpoint=https://login.microsoftonline.com/<tenantid>/oauth2/token
azure.oauth.client-id=application-clientid
azure.oauth.tenant-id=tenantid
azure.oauth.secret=client secret (this will be from step 1)

**Comment by hashhar** [comment]
cc: @mosabua this might be useful to have in docs (as a how-to maybe?)

**Comment by mosabua** [comment]
Definitely could be added to the docs in https://trino.io/docs/current/object-storage/file-system-azure.html somewhere. Lets leave this issue open as doc task for whowever wants to send a PR

**Comment by mosabua** [comment]
Question will also be .. does that only work for Delta Lake .. it should work for all formats.

**Comment by anusudarsan** [comment]
@mosabua all formats. nothing specific to any table format here

**Comment by anusudarsan** [comment]
I will send a docs PR

**Comment by anusudarsan** [comment]
doc PR merged. Closing. @AlakmarShafin let us know if the above suggestion works.

**Comment by AlakmarShafin** [comment]
Thanks @anusudarsan for resolving it quickly. we have tried and tested it, it's working perfectly.
