### ISSUE TITLE
Failure during catalog upsert leads to inconsistent state

### ISSUE THREAD

**Issue by piotrrzysko** [trinodb/trino#23557]
In `CoordinatorDynamicCatalogManager`, when a new catalog is created, the in-memory map storing active catalogs is updated before calling `CatalogStore` to upsert the catalog: https://github.com/trinodb/trino/blob/db35155249660aa407944c5c00da1532cf9b5259/core/trino-main/src/main/java/io/trino/connector/CoordinatorDynamicCatalogManager.java#L279-L280

If the upsert fails (for example, if `FileCatalogStore` throws an exception due to an inability to store the catalog's properties), the catalog is still considered active, even though it hasn't been persisted.

**Comment by hashhar** [comment]
FYI @dain. We'll propose a fix and send a PR for this soon.
