### ISSUE TITLE
How can I open debug log of hadoop hdfs client??

### ISSUE THREAD

**Issue by cmwenxin** [trinodb/trino#2360]
Recently when i execute a  create-table sql ,I find in stage 2,most of tasks are finished,but only one or to two tasks are closing file for a long time.It caused the total time cosst for too long .I want to open debug log of hadoop hdfs client .so i add follow property in log.properties ,but it dose not work.
**org.apache.hadoop=DEBUG**
i add log4j.properties in etc directory ,it still dose not work?
What should I do to see more log information

**Comment by findepi** [comment]
@cmwenxin we currently discard logging from hadoop and hive libraries.
AFAIR the basic reason is that they tend to log too much by default (>=INFO).

@electrum do you remember particular reason for https://github.com/prestosql/presto-hadoop-apache/commit/25de8eade3d5dab8e90485fae136e3959c9bfe64?
was it "they log too much by default" or something else?

**Comment by electrum** [comment]
It logs too much by default and caused the CI to fail due to hitting the log size limit.

**Comment by cmwenxin** [comment]
It means we have no way to  open any level of hdfs logs,is it?

**Comment by electrum** [comment]
Correct, there’s no way to do it now (without recompiling). This is a known issue.

**Comment by cmwenxin** [comment]
If I want to recompile, how can I modify the code so that it can print hdfs logs?How do I modify the configuration file?

**Comment by Praveen2112** [comment]
I think if we can replace this line in [pom.xml](https://github.com/prestosql/presto-hadoop-apache/blob/9e1ca5e627f267c7540f244bb7aedd64a8fdce52/pom.xml#L355) with slf4j-jdk14 then it should solve the issue. 

Ref : https://github.com/Praveen2112/presto-hadoop-apache/commit/aec22a1ea7f559ca58ee1cf99bf9345435c90bf4

**Comment by cmwenxin** [comment]
@Praveen2112 I have replace it and recompile it.Then i have replace the jar in my environment.It workers well.

**Comment by preston-m-price** [comment]
This mitigation for this issue doesn't seem to apply any more. I'm trying to get logs under `org.apache.hadoop.fs` but the advice mentioned above, to tune the pom file is no longer valid because that pom file doesn't exist anymore (I just pulled 348).

**Comment by Praveen2112** [comment]
@cmwenxin Since you are able to open the debug logs, I'm closing this issue. Feel free to join our [Slack](https://trino.io/slack.html) and we could continue the conversation there.
