### ISSUE TITLE
Trino 457 compatibility with JDK 21v(LTS)

### ISSUE THREAD

**Issue by Rakeshya-Kore** [trinodb/trino#23624]
In reference to https://github.com/trinodb/trino/issues/22570, since JDK 21 is now the LTS version (https://endoflife.date/oracle-jdk), could you please confirm if Trino version 457 supports JDK 21?

**Comment by wendigo** [comment]
No, Trino 457 doesn't support JDK 21. It requires at least JDK 22

**Comment by Rakeshya-Kore** [comment]
Hi @wendigo ,
Seems to be JDK 22 is not LTS as per https://endoflife.date/oracle-jdk. That's the reason we raised this issue.
Could you please helps us in understanding why trino 457 not supporting jdk 21.

**Comment by wendigo** [comment]
As an open source project we are aligned with the Java release cadence. We are going soon to require JDK 23 and JDK 24 in six months from now

**Comment by martint** [comment]
Please see https://trino.io/blog/2024/03/13/java-22
