### ISSUE TITLE
Support controlling duplicate files in `add_files` & `add_files_from_table` procedures

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#23678]
Spark supports boolean `check_duplicate_files` argument: 
> Whether to prevent files existing in the table from being added (defaults to true)

I propose adding a similar enum argument (e.g. `duplicate_files`) having 3 modes: 
* `skip` or `ignore` : don't add files that the target table already has
* `add` : add all files even if the target table already has. This is same as `check_duplicate_files` enabled on Spark.
* `fail` : throws an exception like default Spark behavior

**Comment by dain** [comment]
I propose we just make it illegal, and anytime we detect this we throw an exception saying the table is corrupted.  If there are complains, we can add a procedure to fix the table by making multiple copies of the files.
