### ISSUE TITLE
Mongodb schemas not getting picked up by Trino

### ISSUE THREAD

**Issue by krish240574** [trinodb/trino#23674]
Hi, 
My mongodb.properties looks as follows:
connector.name=mongodb
mongodb.connection-url=mongodb://localhost:27017/
mongodb.schema-collection="test_allschemas"

When I then try to run the following code:
conn = presto.connect(host='127.0.0.1', port=8080, username='******',  protocol='https',requests_session=session)
cursor = conn.cursor()
cursor.execute("select * from mongodb.test_documents.Financial_Report")

I get the following :
pyhive.exc.DatabaseError: {'message': 'line 1:8: SELECT * not allowed from relation that has no columns', 'errorCode': 47, 'errorName': 'COLUMN_NOT_FOUND', 'errorType': 'USER_ERROR', 'errorLocation': {'lineNumber': 1, 'columnNumber': 8}, 'failureInfo': {'type': 'io.trino.spi.TrinoException', 'message': 'line 1:8: SELECT * not allowed from relation that has no columns', 'suppressed': [], 'stack': ['io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:58)', 'io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:52)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelectAllColumns(StatementAnalyzer.java:4698)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelect(StatementAnalyzer.java:4626)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:3098)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:520)', 'io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)', 'io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:539)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:547)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1562)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:520)', 'io.trino.sql.tree.Query.accept(Query.java:118)', 'io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)', 'io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:539)', 'io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:499)', 'io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:488)', 'io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:98)', 'io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:87)', 'io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:289)', 'io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:222)', 'io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:892)', 'io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:153)', 'io.trino.$gen.Trino_459____20241004_030804_2.call(Unknown Source)', 'com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)', 'com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)', 'com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)', 'java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)', 'java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)', 'java.base/java.lang.Thread.run(Thread.java:1570)'], 'errorInfo': {'code': 47, 'name': 'COLUMN_NOT_FOUND', 'type': 'USER_ERROR'}, 'errorLocation': {'lineNumber': 1, 'columnNumber': 8}}}

I've made sure I have documents inside the Financial_Report collection inside the db - test_documents. 
Also, I checked if the corresponding schemas are contained in  the mongodb collection "test_allschemas", as specified in the .properties file. 

Still, no luck. 
Please advise. 
Thank you.

**Comment by ebyhr** [comment]
Please enable `mongodb.case-insensitive-name-matching` config property.

**Comment by krish240574** [comment]
BRILLIANT, it works, thank you so much @ebyhr , this saved me so much heartburn !
