### ISSUE TITLE
Error create table in Clickhouse connector

### ISSUE THREAD

**Issue by nguyendinhlam88** [trinodb/trino#23686]
CREATE TABLE clickhouse.default.trino_ck (
                ->   id int NOT NULL,
                ->   birthday DATE NOT NULL,
                ->   name VARCHAR,
                ->   age BIGINT,
                ->   logdate DATE NOT NULL
                -> )
                -> WITH (
                ->   engine = 'MergeTree',
                ->   order_by = ARRAY['id', 'birthday'],
                ->   partition_by = ARRAY['toYYYYMM(logdate)'],
                ->   primary_key = ARRAY['id'],
                ->   sample_by = 'id'
                -> );
Query 20241005_121743_00829_asax5 failed: Code: 47. DB::Exception: Missing columns: 'toYYYYMM(logdate)' while processing query: '`toYYYYMM(logdate)`', required columns: 'toYYYYMM(logdate)' 'toYYYYMM(logdate)'. (UNKNOWN_IDENTIFIER) (version 24.9.1.3278 (official build))

Trino version: 460

**Comment by wendigo** [comment]
Definition is incorrect. Partition_by doesn't allow for function calls.
