### ISSUE TITLE
Snowflake created objects in external Polaris catalog are not accessible from Trino

### ISSUE THREAD

**Issue by mayankvadariya** [trinodb/trino#23715]
Snowflake may create namespace/table in Polaris external catalog with mixed case letters. However, Trino rest catalog supports reading only lowercase object names. It leads to Trino unable to find remote namespace/table in remote catalog.

**Comment by soumilshah1995** [comment]
+1 
https://github.com/trinodb/trino/issues/23957#issuecomment-2445624766

**Comment by findinpath** [comment]
Can you please add a SQL sketch to the description to show the limitation?
