### ISSUE TITLE
Document or add extra JVM flags for Phoenix and Java 23.

### ISSUE THREAD

**Issue by lhofhansl** [trinodb/trino#23749]
Phoenix (and anything that relies on Hadoop et al) requires "-Djava.security.manager=allow" with JVM 23.

**Comment by ebyhr** [comment]
@lhofhansl Can you send a PR?

**Comment by lhofhansl** [comment]
You mean a documentation PR?
Would need to add "-Djava.security.manager=allow" to jvm.config.

**Comment by hashhar** [comment]
For phoenix specifically see https://github.com/trinodb/trino/issues/24135.

But yes this was missed as part of https://github.com/trinodb/trino/commit/de64b5ec1fff9b1023fd00452dd80cc927e68e76.
