### ISSUE TITLE
Gap below query text in UI

### ISSUE THREAD

**Issue by martint** [trinodb/trino#23746]
Since version 458, there's a gap below the box that contains the query text in the UI:

<img width="1206" alt="Screenshot 2024-10-10 at 3 13 16 PM" src="https://github.com/user-attachments/assets/c46cc71e-af0b-4be1-9d27-1e84360a8682">

It seems to be caused by the newly added "non-spooled" entry on the left.

**Comment by mosabua** [comment]
Its probably a hardcoded height for that box that we need to adjust
