### ISSUE TITLE
Allow http connection: mTls already secures traffic inside the Service Mesh

### ISSUE THREAD

**Issue by hakan-77** [trinodb/trino#23763]
### Problem:
When Trino is not exposed to the outside world, and all traffic is inside a Kubernetes cluster and already encrypted via mTls, the necessity to use certificates is a MAJOR OVERKILL.

Service mesh systems do not add X-Forwarded-Proto http headers for mTls. So, Trino assumes the traffic is insecure, which is not true.

### Suggested Solution:
Add a parameter that allows http traffic to Trino, similar to any other data/database platform on the market.

**Comment by wendigo** [comment]
Trino requires a direct communication between workers. Any intermediaries between them are unsupported.
