### ISSUE TITLE
Continuous Integration for Presto with Azure Data Lake Blob, ADLS Gen1 and ADLS Gen2

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#2380]
Presto already supports Azure storages: Blob (`wasb://`), ADLS Gen1 (`adl://`) and ADLS Gen2 (`abfs://`).

We should ensure nothing breaks in these integration with a set of regularly run tests, similarly to AWS-related functionalities (https://github.com/prestosql/presto/issues/274).

**Comment by findepi** [comment]
@anusudarsan Do https://github.com/trinodb/trino/pull/3044 + https://github.com/trinodb/trino/pull/2494 make the issue done?

**Comment by hashhar** [comment]
Closing since we have CI for ADL, ABFS and WASB for quite some time now. Feel free to re-open if something is missing.
