### ISSUE TITLE
Add support spark hive metastore views for delta lake connector

### ISSUE THREAD

**Issue by dishkakrauch** [trinodb/trino#23819]
Currently you can create views with spark.sql in hive metastore but trino can't read it. Do you have plans to fix this?

**Comment by ebyhr** [comment]
There is no plan because https://github.com/linkedin/coral doesn't support translating Saprk SQL to Trino SQL. Let me close this issue as it's basically duplicate of #18122. Please feel free to leave comments in the issue.

**Comment by anilsomisetty** [comment]
Hi @ebyhr 

The coral repository mentions that they provide support for translating Spark SQL to Trino SQL.
https://github.com/linkedin/coral?tab=readme-ov-file#currently-supported-translation-flows
