### ISSUE TITLE
Support reading geometries in EWKB format.

### ISSUE THREAD

**Issue by umartin** [trinodb/trino#23824]
EWKB is a common binary representation for geometries.

PostGIS and Apache Sedona supports reading both WKB and EWKB formats in their ST_GeomFromBinary/WKB functions transparently.

https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry#Format_variations
https://sedona.apache.org/latest/api/sql/Constructor/#st_geomfromwkb

**Comment by umartin** [comment]
The WKB reader in JTS supports both formats. Adding support for EWKB in Trino is just a matter of replacing the ESRI implementation with JTS.
https://github.com/trinodb/trino/compare/master...umartin:trino:ewkb

If you are happy with the proposed changes I'd be happy to sign the CLA and open a PR

**Comment by wendigo** [comment]
@umartin please open a PR and we will review it
