### ISSUE TITLE
Actual columns other than single summy column for Hive Metastore(+AWS Glue) views

### ISSUE THREAD

**Issue by EugeneChung** [trinodb/trino#23837]
- Is there any specific reason that fills only single dummy column on Hive view? 
- https://github.com/trinodb/trino/blob/ff794d2b1f12ed2eb8c6da89b416b8fa5e696c79/plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java#L2756
- It's very inconvenient for all catalog-based SQL tools like redash because it only shows `dummy`.

- I've implemented the function that fills view columns properly. If there's no reason not to do it, I'm going to make a PR.
![Image](https://github.com/user-attachments/assets/d13f4883-7b59-4495-9b0c-fbd85ab943fa)

**Comment by ebyhr** [comment]
There're some situations we can't store column definitions in Glue. 
1. Trino views supports column types Glue can't represent. e.g. UUID, HyperLogLog, and etc. https://trino.io/docs/current/language/types.html
2. Glue has stricter rules for length. For instance, their max length of column's name and comment is 255 though a Trino view doesn't have such limitations. https://docs.aws.amazon.com/glue/latest/webapi/API_Column.html

**Comment by EugeneChung** [comment]
Then can we use dummy column only for check those cases?
