### ISSUE TITLE
Negative dates are accepted without errors

### ISSUE THREAD

**Issue by emmansh** [trinodb/trino#23853]
How come that Trino doesn't throw an error for "negative" dates? Also `try_cast()` doesn't return `NULL`.

I'm running the following SQL on AWS Athena (which uses Trino as engine):
```sql
WITH tbl (my_non_standard_date) 
    AS 
    (
    VALUES
    (TIMESTAMP '-0001-11-26 04:56:02.000')
)

SELECT my_non_standard_date, 
       typeof(my_non_standard_date) AS type_of,
       try_cast(my_non_standard_date as DATE) AS trycast
FROM tbl;

-- my_non_standard_date     	type_of      	trycast
-- -0001-11-26 04:56:02.000 	timestamp(3) 	-0001-11-26
```

_Expected behavior_
I would expect to get an error saying the date value is not valid.

---
Is this behavior unique to AWS Athena or old versions of Trino, or does it exist in recent Trino versions as well? 
Otherwise, is it by design?

**Comment by wendigo** [comment]
Why it should an error?

**Comment by emmansh** [comment]
@wendigo – I will be grateful if you could elaborate. What is a negative date and why is it valid? In my example, there's the date of `-0001-11-26`. How would you explain this date to a human?

Also, is there any piece of documentation or otherwise a technical reference so I could learn more on the subject?

**Comment by wendigo** [comment]
This is defined by ISO 8601 and supported by Java 9+ java.time.*:

> Years represented by this class follow the ISO-8601 standard and use the proleptic numbering system. Year 1 is preceded by year 0, then by year -1.

**Comment by wendigo** [comment]
Why do you think this is invalid @emmansh?

**Comment by emmansh** [comment]
@wendigo 
I think about dates the same way I think about time in general. As the hour cannot be `-2 PM`, the year cannot be `-1`. But from what you are saying, I understand the the year of -1 is therefore simply [1 BC](https://en.wikipedia.org/wiki/1_BC), is that right?

**Comment by wendigo** [comment]
the - applies to the whole date, not to it's component, so yes, this is 1 BC
