### ISSUE TITLE
Feature request: sparate class path option for catalogs of same type

### ISSUE THREAD

**Issue by jonashartwig** [trinodb/trino#23860]
Hi,

in our system we mainly use spark to transform data and build external tables inside a hive metastore. Hive is then consumed by Trino to query the data. Some data we build uses iceberg. It would be great to be able to have two catalogs of iceberg that support different versions (incompatible to each other) of iceberg.

It would be like adding a class to the classpath (via configuration) that might be loaded and unloaded dynamically for all iceberg catalogs. Or maybe the catalogs must be own processes or micro services?

Any thoughts about that feature?

Regards

**Comment by wendigo** [comment]
It's highly unlikely that we will ever support such feature.

**Comment by hashhar** [comment]
It's also not just about classpath, the code in Trino itself would then need to have code written to work with all possible variations of the iceberg library and same for Trino internal code (e.g. older connector version in current server version).

I don't see us going in this direction. And the current use-case you mention has simpler (for the code) solutions like running two clusters. If there are truly cases which cannot be solved outside then we might be open to discuss but so far no use case has been brought up.
