### ISSUE TITLE
`WINDOW` clause alias is not case sensitive

### ISSUE THREAD

**Issue by emmansh** [trinodb/trino#23943]
* Following the example from the [documentation](https://trino.io/blog/2021/03/10/introducing-new-window-features.html#support-for-window-clause), I can use the `WINDOW` clause to calculate the average of `totalprice`.
* I'm aliasing the window as `w` (lowercase `w`).
* I'm referencing to this window in the `SELECT` statement.
* How come that when I'm referencing to `W` (uppercase `W`) it works? Is the alias expected to be case insensitive? 
```sql
WITH orders (custkey, orderdate, totalprice) 
    AS 
    (
    VALUES
    ('cust_1', DATE '2020-10-10', 100),
    ('cust_2', DATE '2020-10-10', 15),
    ('cust_1', DATE '2020-10-15', 200),
    ('cust_1', DATE '2020-10-16', 240),
    ('cust_2', DATE '2020-12-20', 25),
    ('cust_1', DATE '2020-12-25', 140),
    ('cust_2', DATE '2021-01-01', 5)    
)

SELECT 
	avg(totalprice) OVER w AS avg_w, -- lowercase `w`
	avg(totalprice) OVER W AS avg_W  -- uppercase `W`
FROM orders
WINDOW w -- lowercase `w`
    AS (
    PARTITION BY custkey
    ORDER BY orderdate
    RANGE BETWEEN interval '1' month PRECEDING AND CURRENT ROW)


-- avg_w|avg_W|
-- -----+-----+
-- 100.0|100.0|
-- 150.0|150.0|
-- 180.0|180.0|
-- 140.0|140.0|
--  15.0| 15.0|
--  25.0| 25.0|
--  15.0| 15.0|
```

_Expected Output_
I expect an `INVALID_WINDOW_REFERENCE` error.

**Comment by martint** [comment]
That’s expected behavior. Identifiers in SQL are case insensitive unless you use double quotes around them.
