### ISSUE TITLE
Coalesce func is not giving right results

### ISSUE THREAD

**Issue by Akanksha-kedia** [trinodb/trino#24017]
select coalesce(1234,'56');
Query 20241104_070647_00024_7es2f failed: line 1:22: All COALESCE operands must be the same type or coercible to a common type. Cannot find common type between integer and varchar(2), all types (without duplicates): [integer, varchar(2)]
select coalesce(1234,'56')

hive :

select coalesce(1234,'56');
INFO  : Compiling command(queryId=hive_20241104070921_2864fef1-4449-4e08-b181-9d082f70e542): select coalesce(1234,'56')
INFO  : Semantic Analysis Completed (retrial = false)
INFO  : Created Hive schema: Schema(fieldSchemas:[FieldSchema(name:_c0, type:string, comment:null)], properties:null)
INFO  : Completed compiling command(queryId=hive_20241104070921_2864fef1-4449-4e08-b181-9d082f70e542); Time taken: 0.093 seconds
INFO  : Operation QUERY obtained 0 locks
INFO  : Executing command(queryId=hive_20241104070921_2864fef1-4449-4e08-b181-9d082f70e542): select coalesce(1234,'56')
INFO  : Completed executing command(queryId=hive_20241104070921_2864fef1-4449-4e08-b181-9d082f70e542); Time taken: 0.003 seconds
+-------+
|  _c0  |
+-------+
| 1234  |
+-------+

however trino:kite1> select coalesce('1234','56');
 _col0 
-------
 1234  
(1 row)

Query 20241104_070900_00025_7es2f, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.40 [0 rows, 0B] [0 rows/s, 0B/s]

In trino v446

**Comment by martint** [comment]
As the error message indicates, coalesce expects all arguments to be compatible (the same or implicitly coercible to a common type). You need to cast the values to the proper type before calling the function.
