### ISSUE TITLE
Alias is not working as expected

### ISSUE THREAD

**Issue by Akanksha-kedia** [trinodb/trino#24019]
Create hive table :
![Image](https://github.com/user-attachments/assets/b5608962-df03-47d2-94a4-78711dbd7542)

create hive view 
![Image](https://github.com/user-attachments/assets/d13006da-17ff-4c58-b10a-d43964b5b6ae)

Trino 👍 
select * from inner_query;
Query 20241104_055531_00007_7es2f failed: Failed to translate Hive view 'kite.inner_query': org.apache.calcite.tools.ValidationException: org.apache.calcite.runtime.CalciteContextException: From line 6, column 5 to line 6, column 9: Column '_c4' not found in table 't'

**Comment by wendigo** [comment]
Where is the table `t` defined?

**Comment by wendigo** [comment]
You need to add explicit names to these CAST calls. Trino doesn't have hive semantics.
