### ISSUE TITLE
Issue with _col4 and _col5 column while creating view

### ISSUE THREAD

**Issue by Akanksha-kedia** [trinodb/trino#24020]
![Image](https://github.com/user-attachments/assets/3f4d58a1-acb0-4ad5-b13e-c1c0e34e3c34)

CREATE VIEW inner_query AS 
SELECT 
    t.lgl_ntwrk_grp_cd AS lgl_ntwrk_grp_cd, 
    t.cpd_mnth_id AS cpd_mnth_id, 
    t.cpd_dt AS cpd_dt, 
    t.issr_regn_cd AS issr_regn_cd, 
    t._col4 AS acct_num_curr_cd, 
    t._col5 AS acct_num_extn_num
FROM (
    SELECT 
        tcaef_cs_dtl_full.lgl_ntwrk_grp_cd, 
        tcaef_cs_dtl_full.cpd_mnth_id, 
        tcaef_cs_dtl_full.cpd_dt, 
        tcaef_cs_dtl_full.issr_regn_cd, 
        CAST(tcaef_cs_dtl_full.vsps_stop_instrn_typ AS VARCHAR), 
        CAST(tcaef_cs_dtl_full.vsps_ttl_stop_instrn_num AS VARCHAR)
    FROM 
        tcaef_cs_dtl_full
    WHERE 
        dest_flg <> 'E'
    UNION ALL 
    SELECT 
        tcaef_cs_dtl_nspk_full.lgl_ntwrk_grp_cd, 
        tcaef_cs_dtl_nspk_full.cpd_mnth_id, 
        tcaef_cs_dtl_nspk_full.cpd_dt, 
        tcaef_cs_dtl_nspk_full.issr_regn_cd, 
        CAST(tcaef_cs_dtl_nspk_full.acct_num_curr_cd AS VARCHAR), 
        CAST(tcaef_cs_dtl_nspk_full.acct_num_extn_num AS VARCHAR)
    FROM 
        tcaef_cs_dtl_nspk_full
    WHERE 
        dest_flg <> 'E'
) t;

Query 20241104_085940_00034_7es2f failed: line 2:5: Column 't.lgl_ntwrk_grp_cd' cannot be resolved

on running inner query :

 lgl_ntwrk_grp_cd | cpd_mnth_id | cpd_dt | issr_regn_cd | _col4 | _col5 
------------------+-------------+--------+--------------+-------+-------
(0 rows)
this should work as based on SELECT 
        tcaef_cs_dtl_full.lgl_ntwrk_grp_cd, 
        tcaef_cs_dtl_full.cpd_mnth_id, 
        tcaef_cs_dtl_full.cpd_dt, 
        tcaef_cs_dtl_full.issr_regn_cd, 
        CAST(tcaef_cs_dtl_full.vsps_stop_instrn_typ AS VARCHAR), 
        CAST(tcaef_cs_dtl_full.vsps_ttl_stop_instrn_num AS VARCHAR)
    FROM 
        tcaef_cs_dtl_full
    WHERE 
        dest_flg <> 'E'
    UNION ALL 
    SELECT 
        tcaef_cs_dtl_nspk_full.lgl_ntwrk_grp_cd, 
        tcaef_cs_dtl_nspk_full.cpd_mnth_id, 
        tcaef_cs_dtl_nspk_full.cpd_dt, 
        tcaef_cs_dtl_nspk_full.issr_regn_cd, 
        CAST(tcaef_cs_dtl_nspk_full.acct_num_curr_cd AS VARCHAR), 
        CAST(tcaef_cs_dtl_nspk_full.acct_num_extn_num AS VARCHAR)
    FROM 
        tcaef_cs_dtl_nspk_full
    WHERE 
        dest_flg <> 'E' we got 

 lgl_ntwrk_grp_cd | cpd_mnth_id | cpd_dt | issr_regn_cd | _col4 | _col5 
------------------+-------------+--------+--------------+-------+-------
(0 rows) 

so on creating view on top of this should not give any error.

Version :Trino v446
jdk :21

**Comment by wendigo** [comment]
`Column 't.lgl_ntwrk_grp_cd' cannot be resolved`

**Comment by Akanksha-kedia** [comment]
But inner auery gives _col4 and likewise?
