### ISSUE TITLE
Slack invites expired

### ISSUE THREAD

**Issue by mbbooing** [trinodb/trino#24090]
The "Join us on Slack" button on https://trino.io/slack.html & other search results lead to expired invites. Could the invite be refreshed?

**Comment by martint** [comment]
Thanks for reporting. I’ve updated the link.

**Comment by KevinGlinski** [comment]
Looks like the invite link has expired again.

**Comment by martint** [comment]
Thanks! I've just updated it. It should appear on the site shortly.
