### ISSUE TITLE
User-Defined JSON Schemas for MongoDB Collections

### ISSUE THREAD

**Issue by ErikTheBerik** [trinodb/trino#24106]
I am working with Trino to query data from a MongoDB database, and I’ve encountered some challenges around schema handling.

### **Issue**
The documents in my MongoDB collections are complex, with many possible document types within a collection. Currently, Trino appears to generate schemas by inspecting the first document it encounters. This approach results in incomplete or incorrect schemas because Trino.

I already have schema definitions for these collections written in TypeScript, using Typebox. I can convert these Typebox definitions into JSON Schemas, but currently, from what I've found, there doesn’t seem to be a way to feed these JSON Schemas into Trinos MongoDB connector to ensure consistent schema interpretation.

### **Potential Feature Request**
Would it be possible to allow user-defined JSON Schemas to be applied to MongoDB collections within Trino? Or is there an existing approach to the problem I'm facing? Ideally, we could supply a JSON Schema configuration that Trino would use to parse each MongoDB collection, bypassing the automatic schema inference or enhancing it. This feature would greatly simplify working with diverse document structures and eliminate the need for extensive manual schema correction.

**Comment by ebyhr** [comment]
You can modify `_schema` collection likes https://trino.io/docs/current/connector/mongodb.html#table-definition when the schema inference doesn't work well. 

I would recommend writing a small script for translating the Typebox definitions into MongoDB connector definitions.

**Comment by ebyhr** [comment]
>  is there an automated way to apply this conversion?

Nope.
