### ISSUE TITLE
Support Iceberg REST Catalog OAuth2 endpoint

### ISSUE THREAD

**Issue by nqvuong1998** [trinodb/trino#24138]
Trino lacks functionality to configure the [oauth2 endpoint](https://projectnessie.org/nessie-latest/trino/#oauth2-support) and is therefore unable to work with any Iceberg REST catalog implementation and demands a standard OAuth2 server like Keycloak or ADFS.

**Comment by ebyhr** [comment]
Duplicate of #23086
