### ISSUE TITLE
Faker connector produces incorrect results

### ISSUE THREAD

**Issue by martint** [trinodb/trino#24147]
The connector seems to be using the WHERE clause to make decisions on which values to produce. This is an abuse of SQL semantics, and it leads to inconsistent and nonsensical results.

For example, given:

```sql
CREATE TABLE t (x bigint)
```

The following query produces 1000 values of random data, as expected:

```sql
SELECT * FROM t
```

However,

```sql
SELECT * FROM t WHERE x = 1
```

on *the same table*, produces 1000 rows with a value of `1`. By SQL semantics, that should not be the case unless the table contains 1000 rows with `x = 1`, which contradicts the first query.

Additionally, 

```sql
SELECT * FROM t WHERE x = 1 OR rand() >= 0
```

produces the same data as if the first query. By SQL semantics, `x = 1` is equivalent to `x =1 OR rand() >= 0`, so both queries should produce the same results.

See related discussion in https://github.com/trinodb/trino/pull/24078

**Comment by martint** [comment]
cc @nineinchnick , @raunaqmorarka

**Comment by nineinchnick** [comment]
I think this is more about the implied limit, than predicates. There's a default limit used as a safeguard. Does it also violate the sql semantics?

**Comment by nineinchnick** [comment]
In #24098, I'm proposing to automatically create a view with additional predicates when using `CTAS`. If we'd always created this extra view, we can add a default `LIMIT` there, and make it required when selecting from the regular table. WDYT?

**Comment by raunaqmorarka** [comment]
> In [#24098](https://github.com/trinodb/trino/pull/24098), I'm proposing to automatically create a view with additional predicates when using `CTAS`. If we'd always created this extra view, we can add a default `LIMIT` there, and make it required when selecting from the regular table. WDYT?

I'm not convinced about the view approach yet. You can make a separate PR for storing row count from CTAS into table property.
For CREATE TABLE, I recommend we either drop the default limit or we make the relevant table property compulsory for CREATE.
I also think it would be clearer to rename "default-limit" to "row-count".

**Comment by nineinchnick** [comment]
I'll remove the `default-limit` property and will make the `LIMIT` clause mandatory.

**Comment by raunaqmorarka** [comment]
> I'll remove the `default-limit` property and will make the `LIMIT` clause mandatory. There's no other way of applying a default limit than with a view.

Making LIMIT mandatory for all SELECTs on the connector is also awkward, e.g. I might have a query which I know should filter out everything in the table, but i'll be forced to put a LIMIT clause on it for no reason.
To me having a required `row-count` property on the table seems reasonable.

**Comment by nineinchnick** [comment]
I agree, but I don't see another way of avoiding abusing the SQL semantics.

**Comment by raunaqmorarka** [comment]
> I agree, but I don't see another way of avoiding abusing the SQL semantics.

Maybe I'm missing something but having a required row count property on the table doesn't seem an abuse of SQL semantics to me.
It seems to align with
```
Conceptually, the table contains a certain number of rows, already predetermined. Any query over that table should behave as if the table were being fully materialized and then the query executed over those vaalues.
```

**Comment by nineinchnick** [comment]
It won't work with applying ranges with predicates. We'd have to remove predicate pushdown entirely, and add column properties for specifying ranges, but that requires implementing parsing of expressions or literal values. I don't know how to do this without copying a lot of code.

We need to make a decision here how the connector should limit data ranges and row count, we can only pick one:
1. Using the WHERE and LIMIT clauses.
2. Using column properties.

If going with 1 would make the UX significantly worse, I'm ok with removing the connector entirely.

**Comment by nineinchnick** [comment]
@losipiuk helped me understand how we should not use predicate pushdown to influence the generated data. I'll remove any predicate pushdown from this connector and reimplement that with column properties.
