### ISSUE TITLE
Trino fails to create hive table  with textfile_field_separator='\t'

### ISSUE THREAD

**Issue by luhea** [trinodb/trino#24213]
trino:464
hive:3.1.3
Trino-cli:463

DDL SQL:CREATE TABLE test1.test1 ( id int,name string)   WITH ( format = 'TEXTFILE',textfile_field_separator ='\t') 
Error:failed: textfile_field_separator must be a single character string, but was: '\t'

**Comment by ebyhr** [comment]
Could you use `chr(9)` instead?
