### ISSUE TITLE
Trino supports materialized views ?

### ISSUE THREAD

**Issue by vignesh-clustrex** [trinodb/trino#24304]
If trino supports materialized views, why do I get error when running dbt models using dbt-trino, 

Error : This connector doesn’t support materialized_views 

Any thoughts on this ?

**Comment by mosabua** [comment]
Only the Iceberg connector supports materialized views. Every connectors supports different operations to some degree and you can find out more from the documentation.

https://trino.io/docs/current/connector/iceberg.html#sql-support
