### ISSUE TITLE
Timestamp precision

### ISSUE THREAD

**Issue by rostamizahra** [trinodb/trino#24317]
# Support TIMESTAMPS with precisions higher than 3 in MySQL Connector

## Description

When querying tables with `DATETIME(6)` columns in MySQL using Trino, we encounter the following error:

TrinoExternalError(type=EXTERNAL, name=JDBC_ERROR, message="Invalid value of epochMicros for precision 0: 1578221530367877", query_id=<some_query_id>)

This error occurs because Trino's JDBC driver for MySQL doesn't properly handle timestamp values with more than 3 digits of precision.

## Environment

- Database: MySQL
- Timestamp precision: 6 digits (`DATETIME(6)`)
- Trino version: <0.330.0>

## Steps to Reproduce

1. Create a table with a `DATETIME(6)` column in MySQL
2. Query the table using Trino

## Expected Behavior

Trino should correctly handle timestamp values with up to 6 digits of precision.

## Actual Behavior

Trino throws an error when encountering timestamp values with more than 3 digits of precision.

## Impact

This issue prevents users from querying tables that use MySQL's high-precision timestamps, which can lead to data loss and query failures in time-sensitive applications.

## Proposed Solution

Update Trino's MySQL connector to support reading and writing timestamp values with up to 6 digits of precision.

## Additional Context

We kindly request that this issue be addressed to ensure compatibility with MySQL's high-precision timestamps.

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/commit/48519ff925f943a3fe1b04238ed6cd2ab7a30a1c added support for higher precision. Please upgrade your Trino version.

**Comment by rostamizahra** [comment]
My trino server version is 460 and its client version is 330. But still I have this issue.
