### ISSUE TITLE
Feature Request: Add Support for Customizable User-Agent Suffix in Object Storage File Systems (S3/GCS/Azure)

### ISSUE THREAD

**Issue by kennyhsieh1111** [trinodb/trino#24328]
**Feature Request**
- Add support for customizable User-Agent Suffix configuration for Trino S3/GCS/Azure object storage file system

**Objective**
In production environments with multiple Trino clusters, distinguishing which cluster is making requests to object storage services can be crucial for monitoring and debugging. By supporting a configurable User-Agent suffix, Trino could enable administrators to identify the specific cluster responsible for requests in S3 Access Logs, GCS Usage Logs, or Azure Storage Analytics logs.

**Example: Google Cloud Storage (GCS)**
- Trino utilizes the `gcs-connector` jar, which supports the `fs.gs.application.name.suffix` property. This property appends a custom suffix to the HTTP User-Agent header for all Cloud Storage requests, providing cluster-level identification. ([Reference Documentation](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/CONFIGURATION.md#http-transport-configuration))

**Comment by wendigo** [comment]
Will be part of the 467 release.
