### ISSUE TITLE
Missing org.alluxio metrics if Alluxio cache is enabled for multiple catalogs

### ISSUE THREAD

**Issue by jingyi-dd** [trinodb/trino#24510]
When enabling Alluxio cache for multiple catalogs, the JMX metrics under `org.alluxio` are tied to only one catalog. And it doesn't seem to be deterministic which catalog it's initialized with.

**Comment by raunaqmorarka** [comment]
I think this https://github.com/trinodb/trino/pull/24514 should resolve it

**Comment by jingyi-dd** [comment]
> I think this [#24514](https://github.com/trinodb/trino/pull/24514) should resolve it

Thank you for the quick fix!
