### ISSUE TITLE
Add support for partition in BigQuery connector

### ISSUE THREAD

**Issue by KimPlv** [trinodb/trino#24545]
Is it possible to add [partitioning](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#TimePartitioning) to **Bigquery** connector ? 

like 
```
CREATE TABLE default.trino_bq (
  id int NOT NULL,
  name VARCHAR,
  age BIGINT,
  logdate DATE NOT NULL
)
WITH (
  partition_by = ARRAY['toYYYYMM(logdate)']
);
```

**Comment by ebyhr** [comment]
Nope, it's unsupported.
