### ISSUE TITLE
Using `sequence()` between dates returns an array of timestamps rather than array of dates

### ISSUE THREAD

**Issue by emmansh** [trinodb/trino#24591]
Running the following
```sql
SELECT typeof(sequence(date '2023-10-20', date '2023-11-11', INTERVAL '7' DAY))

-- _col0              |
-- -------------------+
-- array(timestamp(0))|
```
made me wonder: why is the returned output an array of timestamps rather than array of dates (as the input type)?

Currently I need to wrap with `cast(sequence(x, y, z) as array(date))` to get the same type as the input.

---
I'm using Trino as part of AWS Athena, so I don't know what Trino version this is.

**Comment by nineinchnick** [comment]
It works as expected in Trino 464:
```
% trino trino.rocks --no-progress
trino> SELECT typeof(sequence(date '2023-10-20', date '2023-11-11', INTERVAL '7' DAY));
    _col0    
-------------
 array(date) 
(1 row)
trino> select version();
 _col0 
-------
 464   
(1 row)
```

**Comment by nineinchnick** [comment]
I don't see anything relevant in the Trino release notes. Maybe try reporting this to AWS?

**Comment by emmansh** [comment]
@nineinchnick thanks.
Following your suggestion I posted in AWS platform ([see here](https://repost.aws/questions/QUsPwQ5quQQUq3c2UXVtWvRg/using-sequence-between-dates-returns-an-array-of-timestamps-rather-than-array-of-dates)), hopefully it gets attention.

**Comment by emmansh** [comment]
FYI that my post at AWS [got an answer](https://repost.aws/questions/QUsPwQ5quQQUq3c2UXVtWvRg/using-sequence-between-dates-returns-an-array-of-timestamps-rather-than-array-of-dates#ANUPY30DsfSN2SctQlfW2dVQ). The answer doesn't make too much sense to me, but it is what it is.

**Comment by nineinchnick** [comment]
It looks like generated by AI...
