### ISSUE TITLE
INSERT, DELETE - event-listener records don't provide the number of affected rows and bytes

### ISSUE THREAD

**Issue by bhzaeri** [trinodb/trino#24596]
The events for DELETE and UPDATE rows don't have the number of affected rows.
queryCompletedEvent.getStatistics().getOutputRows()); is `1`
and
queryCompletedEvent.getStatistics().getOutputBytes()) is `9`
But I deleted/updated multiple rows in a table.

**Comment by wendigo** [comment]
The output rows is 1 because this is a single digit output (number of modified rows). This isn't the value of the modified/deleted rows.

**Comment by bhzaeri** [comment]
@wendigo 
I modified multiple rows in a single command. So, that number should not be `1`.

**Comment by wendigo** [comment]
@bhzaeri as said the output rows is not meant to represent this information

**Comment by bhzaeri** [comment]
@wendigo 
Thanks!
Is it possible to include affected rows in the `queryCompletedEvent` too?
