### ISSUE TITLE
Support negative hexadecimal integer literals

### ISSUE THREAD

**Issue by nineinchnick** [trinodb/trino#24601]
When running a query like this:
```sql
select -0x80;
```

It fails with:
```
line 1:8: Invalid numeric literal: -0x80
```

But this works and returns `-128` as expected:
```sql
select -1 * 0x80;
```

**Comment by nineinchnick** [comment]
Also note that we use this notation in the docs: https://trino.io/docs/current/language/types.html#tinyint

**Comment by wendigo** [comment]
@nineinchnick it was in the grammar but the parsing wasn't there - I've created a PR with a fix
