### ISSUE TITLE
Fix and reenable S3 Select for uncompressed files

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#2475]

**Comment by findepi** [comment]
Until this is fixed, we disable S3 Select for uncompressed files.
cc @same3r

**Comment by findepi** [comment]
(I removed `correctness` and `bug` labels, because the bug is fixed from Presto perspective.)

**Comment by ramondeklein** [comment]
@findepi Can you explain why S3 Select is explicitly disabled for uncompressed files?

**Comment by naushadh** [comment]
Link to original PR that prevented support for uncompressed files: https://github.com/trinodb/trino/pull/2399

It appears both AWS SDK and Trino reader should support uncompressed files
- https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/CompressionType.html
- https://github.com/trinodb/trino/blob/e26b47a6a568100e95b8b301c97d19c34964d485/plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3select/S3SelectLineRecordReader.java#L120-L122

Its this block that appears to prevent using uncompressed files: https://github.com/trinodb/trino/blob/e26b47a6a568100e95b8b301c97d19c34964d485/plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3select/S3SelectPushdown.java#L111

**Comment by findepi** [comment]
> Link to original PR that prevented support for uncompressed files: #2399

it was disabled because of correctness issues.
it might be fixed since then on the AWS S3 side.

**Comment by preethiratnam** [comment]
Hi @findepi can you please describe how to reproduce the correctness issue? I'm interested in fixing this.

**Comment by findepi** [comment]
`presto-hive-hadoop2/bin/run_hive_s3_tests.sh` should reproduce the problem if it hasn't been fixed.
If you do a PR, this test won't run, because it requires secrets.
Since re-enabling is trivial, i run the build myself: https://github.com/trinodb/trino/pull/12256
