### ISSUE TITLE
Expose rule stats in QueryStats

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#2578]
Currently we gather JMX stats for rule execution. However, we could also expose rule stats for particular query in `QueryStats`. This would simplify query debugging

**Comment by Terry93** [comment]
Hello, I would love to try on this work. Thanks!

**Comment by findepi** [comment]
I am concerned this could significantly increase size of `QueryStats`. There are about 100 rules today, but this number is going to increase.

**Comment by Terry93** [comment]
@findepi How about showing, say, top 20 rule stats by default? And other rules can be chosen to expose if the user sets the rule name by session property explicitly?

Just make sure I understand the issue correctly: the rules we mentioned here refer to the optimization rules for logical plan right?

**Comment by kokosing** [comment]
Maybe there should be config switch for that, where user might want to enable it when debugging a query.

**Comment by sopel39** [comment]
> @findepi How about showing, say, top 20 rule stats by default? And other rules can be chosen to expose if the user sets the rule name by session property explicitly?

That seems like a good idea. It will enable us to debug planning latency. We could also have a session property that would make query json contain stats for all rules.
