### ISSUE TITLE
Expose planningCpu time in QueryStats

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#2579]
We could expose total CPU planning time in `QueryStats`. This would simplify debugging planning issues and latency.

**Comment by Terry93** [comment]
Hello, I would love to try on this work. Thanks!

**Comment by sopel39** [comment]
Sure, go ahead

**Comment by weijiii** [comment]
@sopel39 Hi I think this stat will be useful to use. Can I continue on this?

**Comment by sopel39** [comment]
Sure @weijiii
