### ISSUE TITLE
Iceberg: test partition pruning

### ISSUE THREAD

**Issue by manishmalhotrawork** [trinodb/trino#2660]
Iceberg connector has implemented partition pruning.
Though there are not test-case to validate it.

**Comment by manishmalhotrawork** [comment]
@lxynov

What I found is,

there is test-case in Hive test-case, which validate the partition pruning.
`TestHiveIntegrationSmokeTest.testPartitionPruning`

which is dependent on the `ConnectorTableProperties` returned by 
` public ConnectorTableProperties getTableProperties(ConnectorSession session, ConnectorTableHandle table)` of `HiveMetadata`

In `IcebergMetadata` its returning default `ConnectorTableProperties` so we can't rely on the similar logic for test.
We need to populate `ConnectorTableProperties` to achieve this ? Is my understanding correct ? 

thanks.

**Comment by manishmalhotrawork** [comment]
Hi @electrum 
Whenever you get time, can you also please see if my understanding is correct?

**Comment by ebyhr** [comment]
Closing as we have `BaseIcebergConnectorTest#testPredicatePushdown`.
