### ISSUE TITLE
Presto CLI is firing 2 Queries when user submit  use information_schema; function could be loaded only once

### ISSUE THREAD

**Issue by AbhishekNew** [trinodb/trino#2802]
During Initializing the Presto CLI  auto fires the 2 Queries
SELECT table_name FROM information_schema.tables WHERE table_schema = 'information_schema';
SHOW FUNCTIONS;
But after Presto CLI is user just give use information_schema; then also 2 Queries are get firs automatically. 
So suppose user give use information_schema; 10 times then total 30 Queries  in Query Details.
![WhofiresIt](https://user-images.githubusercontent.com/51321459/74318542-78ce1080-4da3-11ea-9cdd-2e2abf415333.PNG)
![useinformation](https://user-images.githubusercontent.com/51321459/74318570-85eaff80-4da3-11ea-8827-6cc831dd5669.PNG)

**Comment by electrum** [comment]
The CLI has tab completion for table names and function names, which is why these queries are run. Are they causing a problem for you? They should be quick and cheap.

**Comment by AbhishekNew** [comment]
But I feel every time user give use schema; command these queries should not be fire. Yes I agree first time when launching CLI it is getting fire ok.

**Comment by electrum** [comment]
The table name completion is per schema, so it needs to be loaded for the current schema. I agree that functions could be loaded only once.

**Comment by AbhishekNew** [comment]
The table name completion is per schema -- But if u see suppose user give use 'default'; then it is loaded for current 'default' schema and user is inside the 'default' schema and again fire use 'default'(same schema ) again loaded.

**Comment by AbhishekNew** [comment]
We can handle this - functions could be loaded only once against this issue.

**Comment by electrum** [comment]
Yes, we could be smart and skip refresh if the current schema is the same. But I’m not sure it’s worth the trouble — how often do users run `use` for the schema they are already using?

**Comment by AbhishekNew** [comment]
We can handle this - functions could be loaded only once against this issue.
