### ISSUE TITLE
Add support for json_path wildcard

### ISSUE THREAD

**Issue by Cabeda** [trinodb/trino#2883]
When dealing with json data (usually from non sql databases) it's usual to find nested data where the only constant is the json key. This would be really easy to query if presto implemented the wildcard from JsonPath https://github.com/json-path/JsonPath#operators. 

Is this something feasible or is there any known issues to implement this?

**Comment by martint** [comment]
There's no syntax to match a key at an arbitrary level. In standard JSON path, that would be via the `..` operator, but that's not supported in the variant defined by the SQL specification.
