### ISSUE TITLE
Ellipsis not display for all the queries in Cluster Overview UI Page

### ISSUE THREAD

**Issue by AbhishekNew** [trinodb/trino#2886]
Executed TPCDS Queries and in Cluster overview UI page in in Query Details some big query display with with ellipsis(...) some without ellipsis. Not good UI Experience for users. 
Also we should provide expansion of queries if it is big on clicking the ellipsis and scrollbar as user are allowed to copy the whole query from the container.
![Ellipsis](https://user-images.githubusercontent.com/51321459/74929337-4a82ad80-5401-11ea-969e-1ff4cec0b90d.PNG)

**Comment by findepi** [comment]
> Also we should provide expansion of queries if it is big on clicking the ellipsis and scrollbar as user are allowed to copy the whole query from the container.

I would hold on on this. This is available on query details page.

**Comment by ebyhr** [comment]
Going to close this issue since fixed by #6216
