### ISSUE TITLE
hive connector - ability to read from .csv.zip files (not gz/gzip)

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#2904]
Apache Drill supports this: https://github.com/apache/drill/pull/1879/files https://issues.apache.org/jira/browse/DRILL-5674
it makes use of:
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import java.util.zip.ZipOutputStream;

**Comment by dain** [comment]
A zip file can contain multiple files.  Is the code supposed to process all files, or does it fail if there is not exactly one file.  If multiple files, do standard Hive exclude rules apply to the file names?

**Comment by findepi** [comment]
Is this a Drill-specific feature, or does Hive support this too?

**Comment by hashhar** [comment]
Drill feature, it added support for reading ZIP files assuming they had a single entry.

I don't think it makes sense to support, there isn't enough demand and semantics are ill-defined.

Closing.
