### ISSUE TITLE
Clarify documentation for OWNERSHIP within Hive file based access controls

### ISSUE THREAD

**Issue by alrolorojas** [trinodb/trino#2953]
It is not clear what are the permissions you get when OWNERSHIP is either assigned within the schema or the table Hive File based access control permissions. It'd be worth clarifying what users are allowed/not allowed if that permission is assigned.

Doc https://prestosql.io/docs/current/connector/hive-security.html#hive-file-based-authorization

**Comment by chenjian2664** [comment]
@findepi can i take this, seems no body notice :)

**Comment by chenjian2664** [comment]
@mosabua Hi, can you suggest where i should put the doc details about `OWNERSHIP`?
