### ISSUE TITLE
Ranger integration with presto works on "Release 317" but fails on versions later

### ISSUE THREAD

**Issue by har5havardhan** [trinodb/trino#2987]
Hi,

I am trying to integrate ranger with presto and its working on "Release 317" 
I followed the following documentation : https://cwiki.apache.org/confluence/display/RANGER/Presto+Plugin

But, when when I go with versions after that, It throws the following errors.

**query**: _SHOW CATALOGS_
**error** : _[65536] Query failed (#20200303_063413_00002_h5s89): Internal error java.lang.RuntimeException: java.lang.IllegalStateException_

**query**:_select * from hive.db_name.table_name limit 10_
**error**:_[4] Query failed (#20200303_063836_00000_x47vg): Access Denied: Cannot access catalog hive java.lang.RuntimeException: io.prestosql.spi.security.AccessDeniedException: Access Denied: Cannot access catalog hive_

I've tried versions 318,319,323,329 and i am facing similar errors. How do I solve this ?

**Comment by tooptoop4** [comment]
can u post whole stacktrace?

**Comment by ebyhr** [comment]
Thanks for filing the JIRA ticket https://issues.apache.org/jira/browse/RANGER-2747. Let me post so that other people can follow it.

**Comment by bolkedebruin** [comment]
There is an api change in Presto that makes the plugin incompatible. I’m holding off for presto 331 to release a new version with a compatible api and row/column filtering

**Comment by bolkedebruin** [comment]
https://issues.apache.org/jira/browse/RANGER-2754

**Comment by mit012** [comment]
@ebyhr ebyhr/ranger@5f01488 with same changes in file ranger/ranger-presto-plugin-shim/src/main/java/org/apache/ranger/authorization/presto/authorizer/RangerSystemAccessControl.java resolved the issue.

But we are facing some another issue
1. query: describe tablename
error: io.prestosql.spi.security.AccessDeniedException: Access Denied: Cannot show columns of table tablename

2. When we create a group in ranger and add users in that group then we still got access denied for that user

**Comment by ebyhr** [comment]
@mit012 What Presto version are you using?

**Comment by tooptoop4** [comment]
@mit012 "same changes" - did u make different changes than just what was in ebyhrs PR? Also did you ever get access working before for groups? as it only works if u add local linux user/groups

**Comment by mit012** [comment]
@ebyhr We are using presto version 323.
@tooptoop4 yes we have changes in ranger/ranger-presto-plugin-shim/src/main/java/org/apache/ranger/authorization/presto/authorizer/RangerSystemAccessControl.java also (replaced Identity with SystemSecurityContext).
We do not have access for groups before also.

**Comment by ebyhr** [comment]
@mit012 Added one more commit https://github.com/ebyhr/ranger/commit/841a4d59b4402496edc167180dec8ae55459c4bb to use version 323. Could you try again?

**Comment by bolkedebruin** [comment]
https://issues.apache.org/jira/browse/RANGER-2754 has an attached patch that supports Presto 331 and includes Row filtering, Column Masking and Presto groups support. Note that you will need to upgrade your service definitions.

**Comment by mit012** [comment]
@ebyhr Yes its working

**Comment by KentonParton** [comment]
So I don't run into the same issue har5havardhan has, what are the latest stable versions of prestosql and Ranger that work together? 

Will prestosql here: https://repo1.maven.org/maven2/io/prestosql/presto-server/331/presto-server-331.tar.gz
and ranger branch: https://github.com/apache/ranger/tree/ranger-2.0
work together?

**Comment by bolkedebruin** [comment]
@KentonParton no. The above linked issued has a patch that works with Presto 331. I think you need to be below 321 to have ranger 2.0 work

**Comment by KentonParton** [comment]
@bolkedebruin Have these changes been applied to any of the ranger branches yet? Personally, I am am just testing Presto and Ranger so if I can avoid running patches that would be great.

If patching is the only option, how do I go about running it? From what I have read, you have to run it on each file that needs to be updated. Is that correct?

Thanks for the help.

**Comment by KentonParton** [comment]
Found out how to apply the patch.

After applying the patch to ranger (master branch) and executing `enable-presto-plugin.sh` successfully, it appears that Ranger only has access to Presto catalogs and not schemas, tables, columns.

Connection to the Presto UI http://localhost:8080/ui/ and from an IDE is refused. Is anyone else experiencing this?

**Comment by dain** [comment]
Looking at the stack I don't see how a NPE is possible there unless there is a custom system access control installed that implements `filterViewQueryOwnedBy` as `return null`

**Comment by bolkedebruin** [comment]
If you want Presto > 317 take the latest patch from here: https://issues.apache.org/jira/browse/RANGER-2754 . It is undergoing review and has unit tests.

NPEs can happen with Ranger if Ranger does not find a config file unfortunately. So make sure ranger has a proper config file.

**Comment by bolkedebruin** [comment]
Patch has been updated and should not throw this NPE anymore @dain @KentonParton

**Comment by KentonParton** [comment]
@bolkedebruin thank you for updating the patch I will give it a try this evening. 

Regarding the policies set in Ranger. When I limit a users access to anything other than full access, the following is displayed.

```
[4] Query failed (#20200410_183150_00081_q4erf): Access Denied: Cannot access catalog wemingle io.prestosql.spi.security.AccessDeniedException: Access Denied: Cannot access catalog wemingle
```

I am  connecting to presto with the user "kentonparton" and this is the policy that I have created in Ranger.
![image](https://user-images.githubusercontent.com/20202312/79014525-b3002800-7b30-11ea-8096-a21aad4c8547.png)

If I provide full access, then this user is able to query data as expected but as soon as I limit something, access is denied at the catalog level.

Have you been able to limit which columns a user has access to or am I doing something wrong in Ranger?

**Comment by bolkedebruin** [comment]
You will need to create policies at the Catalog level, Schema level and Table level in order to ensure access.

Access determination does not drill down to lower levels. The default policy is deny and as such the first check will indeed end up with an access denied.

**Comment by tooptoop4** [comment]
@bolkedebruin what policies should be created to allow just 1 tbl? use priv at catalog?

**Comment by KentonParton** [comment]
@bolkedebruin I applied the latest patch "0001-RANGER-2754-Upgrade-presto-dependency-and-improve-lo.patch". The queries are coming through to the UI now; however, all queries made from my IDE, DataGrip, are causing a "Query failed internal error NullPointerException". I have tried prestosql release 331 and 332.

Can you confirm that you are or are not seeing this. Thanks

**Comment by bolkedebruin** [comment]
I don't use an IDE to connect. Can you provide a stacktrace of that exception?

**Comment by KentonParton** [comment]
It just shows what I mentioned above "Query failed (#20200414_202708_00007_c5pcn): Internal error java.lang.NullPointerException" I would expect this to happen if you query it in any way, not just from an IDE.

**Comment by bolkedebruin** [comment]
Please have a look at the logs of Presto. For all its worth this could also be an error from your idea.

**Comment by bolkedebruin** [comment]
Update has been merged into Ranger and should be part of its 2.1 release.

**Comment by bolkedebruin** [comment]
@dain how do you view integrating the Plugin with Presto itself? The release cycle of Ranger is quite slow and changes to the security system in Presto happen quite frequently at the moment. 

I can do the work for it.

**Comment by KentonParton** [comment]
@bolkedebruin  were you able to run Presto and Ranger using Java 11? I was able to successfully run them together using Java 8 but ran into the following errors when using Java 11:

`java.lang.NoClassDefFoundError: javax/annotation/PostConstruct`

resolved this by adding javax.annotation-api and then ran into the following:

`java.lang.NoClassDefFoundError: org/apache/ranger/plugin/classloader/RangerPluginClassLoader`

**Comment by bolkedebruin** [comment]
No not yet. Ranger officially has support for Java 8 not for 11 yet

**Comment by KentonParton** [comment]
@bolkedebruin looks like Ranger 2.0 and master support version 11. [Here's](https://github.com/apache/ranger/commit/08f32cd35824399eaac573f47338fbe8433ed97e) the commit and [here's](https://issues.apache.org/jira/browse/RANGER-2317) the Jira issue.

javax.annotation-api needs to be included. Haven't resolved the classloader issue yet.

**Comment by capacman** [comment]
I built with latest snapshot it and the added javax.annotation and now presto can start. But when i query a table with like "select count(*) from movies" it says Access Denied: Cannot execute function count.  When i look at logs it says:
java.lang.NoClassDefFoundError: org/apache/zookeeper/server/ByteBufferInputStream

when try to write audit log to solr. I dont understand why it does not include zookeeper since in assembly xml it have
<include>org.apache.zookeeper:zookeeper:jar:${zookeeper.version}</include>

**Comment by capacman** [comment]
With latest patch i can make it work. I have hive->default->movies table. First i should gave execute for procedures and functions for all users. Then i created use/show/select for hive and then default and the for all tables under default. But to make it work i think you should give *->information_schema->*->* select for all users. Otherwise show tables are not working. If you want ide support i think you should give select grant to system->jdbc->*->* for all users.

**Comment by hwk42** [comment]
> @bolkedebruin were you able to run Presto and Ranger using Java 11? I was able to successfully run them together using Java 8 but ran into the following errors when using Java 11:
> 
> `java.lang.NoClassDefFoundError: javax/annotation/PostConstruct`
> 
> resolved this by adding javax.annotation-api and then ran into the following:
> 
> `java.lang.NoClassDefFoundError: org/apache/ranger/plugin/classloader/RangerPluginClassLoader`

I got the same error,but when I use java 8,the presto of 333 version is not supported( it requires java 11).How to solve them,any suggestion?Thanks.

**Comment by ebyhr** [comment]
Newer Trino versions are supported in Ranger now. Let me close this ticket.
