### ISSUE TITLE
ldap.group-auth-pattern changes without restart

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#3033]
feature req - allow updates to ldap.group-auth-pattern (ie adding a new AD group) without needing to restart presto server. 

I'm guessing this could be read from an external file like some other configs that handle auto-refresh without restart

**Comment by hashhar** [comment]
No plans to add this. If we ever get to dynamic config we'd want to do it for configs in general and not as one-off implementations for each specific config.
