### ISSUE TITLE
CLI rarely returns duplicated rows when executed SHOW FUNCTIONS

### ISSUE THREAD

**Issue by AbhishekNew** [trinodb/trino#3040]
As discussed offline @ebyhr
The Presto version is 327 and this issue happened only once.
SSH client is SuperPuTTy on Windows and connects to the remote Presto server.

Steps:
```sql
show functions like 'a%'; -  listing total 10 abs functions
show functions like 'ab%'; - listing total 7 abs functions
show functions like 'a%'; - listing total 7 abs funtions
```

There are 3 `abs` rows having `decimal(p, s)` Retrun Type.
![Show Functions10](https://user-images.githubusercontent.com/51321459/76208121-10007980-6225-11ea-8b77-36fa03a7b124.PNG)
![Show Function7](https://user-images.githubusercontent.com/51321459/76208150-1abb0e80-6225-11ea-91eb-d278003852df.PNG)

[JsonFIle.txt](https://github.com/prestosql/presto/files/4306284/JsonFIle.txt)

**Comment by ebyhr** [comment]
Let's reopen this issue if it happens once again.
