### ISSUE TITLE
Support custom http headers on JDBC Driver

### ISSUE THREAD

**Issue by psg2** [trinodb/trino#3179]
I would like to pass a header like `X-Presto-Routing-Group` that works for lyft/presto-gateway to configure which routing group the query should end up going to. 
Also, from the latest releases, there is a feature for impersonation users, if I send queries over HTTP directly passing a different user on the `Authorization` header from the user on `X-Presto-User` it will try to impersonate the `X-Presto-User`, but from my understanding of the code, the `X-Presto-User` and `Authorization` are both coming from the `user` property on the JDBC driver.

Is it reasonable to add a property to allow a list of custom headers like the property `extraCredentials`?

**Comment by electrum** [comment]
I dislike the idea of custom headers. It is a low level detail of the protocol that we shouldn't expose to users, and has issues around encoding, security, etc.

We already support several standard informational fields that can be used for routing decisions:

* source
* client tags
* client info

If none of these suffice, it's reasonable to add *routing group* as a standard property that can be supported consistently across clients and gateways (the exact usage and meaning of the property would be specific to each deployment).

**Comment by psg2** [comment]
I was more inclined to use custom headers, because this routing-group header wouldn't have any meaning on Presto itself, but would allow customization to proxies in front of it. However, I'm not well aware of the encoding or security implications.

On a second note, what about the header X-Presto-User usage for user impersonation?

**Comment by electrum** [comment]
Presto has always supported impersonation (and was simplified in recent releases), but the CLI and JDBC do not allow this password based authorization, as you noted. We could add a new parameter to separate the authentication user from the impersonated user.

The main issue there is whether then standard `user` property should be authenticated or impersonated. I see arguments for both options:

* JDBC has first class support for `user` and `password` parameters, such as in [`DriverManager.getConnection()`](https://docs.oracle.com/javase/8/docs/api/java/sql/DriverManager.html#getConnection-java.lang.String-java.lang.String-java.lang.String-). As these are provided together, and password is for authentication, it makes sense for the user to be the authentication user.
* The standard `user` parameter is used as the impersonated user for other authentication methods like Kerberos or TLS client certificates. There is a value in having it used consistently.

**Comment by psg2** [comment]
Oh, you're completely right about the impersonation support. I'm kinda new to Presto and made the wrong assumption reading the recent release notes.

From a first perspective, I would go with the second argument that the `user` property should be impersonated, because it would keep the backward compatibility of the driver if anyone updates it and is using those other authentication methods. But I'm not the best suited for this decision.

**Comment by findepi** [comment]
I created a dedicated issue for the impersonation in CLI & JDBC: https://github.com/prestosql/presto/issues/3690

As the routing question seems to be answered, can we close this issue?

**Comment by psg2** [comment]
Yes, I think it's ok to close it now.

Also, apparently, the newest version just released this enhancement with the Pull Request: https://github.com/trinodb/trino/pull/6549

**Comment by findepi** [comment]
Thanks for the feedback.
