### ISSUE TITLE
Redis test sometimes takes about 1 hour

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#3233]
As far as I looked into, It was about 35 minutes before switching to dockerized Redis. 
* https://github.com/prestosql/presto/runs/523162628 (54m)
* https://github.com/prestosql/presto/runs/528794328 (59m)
* https://github.com/prestosql/presto/runs/423758520 (70m)
~ dockerized Redis ~
* https://github.com/prestosql/presto/runs/399806024 (37m)
* https://github.com/prestosql/presto/runs/403790203 (33m)
* https://github.com/prestosql/presto/runs/402470158 (36m)

**Comment by electrum** [comment]
#3201 brings it down to 38m, but we should independently try to figure out what caused the regression with Dockerized Redis (since fixing both would further reduce the runtime).

**Comment by ebyhr** [comment]
The test takes about 10 minutes recently. Closing.
