### ISSUE TITLE
Waterfall graph to visualize where time is being spent in query

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#3468]
idea: Waterfall graph from presto-cli

presto-cli client submits query at **time x**
DNS resolution, TLS negotiation, proxying to coordinator happens
Coordinator receives query at time **x+1**
LDAP authentication happens
Coordinator acknowledges successful authentication at time **x+2**
Ranger authorisation check happens
Coordinator confirms successful authorization at time **x+3**
Hive metastore lookups happen
Coordinator receives metadata at time **x+4**
Coordinator plans/analyzes/optimizes query
Coordinator finishes all planning/analysis.etc at time **x+5**
Coordinator sends query to workers, workers start doing the 'heavy lifting' of retreiving source data, computing query results
Coordinator receives all data from workers at time **x+6**
Data is sent back to client (ie presto-cli)
Client receives all data from coordinator at time **x+7**

similar to:

chrome
![image](https://user-images.githubusercontent.com/33283496/79602623-b83a1580-80e2-11ea-88e4-4f7584c2fc90.png)

spark
![](https://docs.cloudera.com/cloudera-manager/7.1.0/monitoring-and-diagnostics/images/cm-webui-5.png)

**Comment by hashhar** [comment]
OpenTelemetry is now available since https://github.com/trinodb/trino/pull/16950
