### ISSUE TITLE
Create Table will generate empty folder in temporaryStagingDirectoryPath and never clean up

### ISSUE THREAD

**Issue by lxqfy** [trinodb/trino#3498]
Steps to reproduce

1. `CREATE TABLE hive.test.test_table (
    test_col bigint
 )
 WITH (
    format = 'PARQUET'
 )`
2. A empty folder will be created under temporaryStagingDirectoryPath e.g. `/tmp/presto-$USER/a68b29f5-6d01-4485-95de-65242f0fd48e`

**Comment by hashhar** [comment]
I can no longer reproduce this - at least with the provided instructions.

Feel free to reopen if this is still an issue.
