### ISSUE TITLE
Cast ROW to JSON including column names

### ISSUE THREAD

**Issue by alrolorojas** [trinodb/trino#3536]
We would like to have a way to cast ROW data type to JSON while keeping the column names using Presto SQL. The current Presto behavior differs from Hive and it is preventing migrating some jobs over to Presto.

Current behavior, original ROW `ROW(123, 'abc', true) AS ROW(v1 BIGINT, v2 VARCHAR, v3 BOOLEAN)`:

`'[123,"abc",true]'`

Desired behavior:

`{"v1":123,"v2":"abc","v3":true}`

Following our conversation on [PrestoSQL Slack](https://prestosql.slack.com/archives/CFLB9AMBN/p1587056390113100)

/cc @bxw11 @bathompso @romanofoti

**Comment by ebyhr** [comment]
Relavant Stackoverflow question: https://stackoverflow.com/questions/65464436/presto-produce-json-results
