### ISSUE TITLE
LastAccessTime in Hive metastore not updated when executing query

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#3544]
I have a query regarding hive metastore. I wanted to access the LAST_ACCESS_TIME from table TBLS , so I configured setting according this link.
http://www.hadoopadmin.co.in/hive/last-access-time-of-a-table-is-showing-zero/ (note: So this is configuration for HS2 (hive runtime). This is why it doesn’t work with Presto (or any other execution engine that connects to metastore) we would need to add support for this on Presto side. Because of the way Hive design their feature )
but the LAST_ACCESS_TIME is getting  updated only when I use tool such beeline and NOT getting updated when I use hive connector from presto. 

For the implementation, I’d start somewhere around io.prestosql.plugin.hive.metastore.thrift.ThriftMetastoreUtil#toMetastoreApiTable(io.prestosql.plugin.hive.metastore.Table) . This is the place where you can hack something quickly and inject parameters, but i am not yet sure if this is the right place in general. For instance, it’s not something being called for Glue.
that will update LAST_ACCESS_TIME for writes; for reads is more complicated; You can start at io.prestosql.plugin.hive.HiveMetadata#getTableHandle but you cannot just update table property on read; eg the metastore can be in read-only mode or we have no write permission, etc.

https://github.com/prestodb/presto/issues/7126

this issue came up from trouble answering below 3 questions:
1. how to check when table created?
2. when table last had select query run on it? 
3. last time a table had underlying files (ie parquet) changed? 'SELECT max("$file_modified_time") FROM'

**Comment by findepi** [comment]
related conversation on Slack https://prestosql.slack.com/archives/CGB0QHWSW/p1583145728189700
