### ISSUE TITLE
Mysql connector does not allow single database jdbc connection

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#3545]
"Database (catalog) must not be specified in JDBC URL for MySQL connector" why this restriction?

_The JDBC connectors map all “databases” to schemas, so setting the “database” doesn’t make sense.
Is there a problem with removing that?_

1. restricting some sensitive databases from presto 
2. some mysql user can't access all databases. I was thinking presto could could just map single database to single schema

**Comment by zhaoyim** [comment]
Did following test and found the trino can implement the mysql privilege, generally we use the mysql privilege to control the user access the database.


### Mysql :
Login with root user:
```
mysql> CREATE USER 'zhaoyim'@'%' IDENTIFIED BY 'test';
Query OK, 0 rows affected (0.13 sec)

mysql> create database data1;
Query OK, 1 row affected (0.02 sec)

mysql> GRANT ALL PRIVILEGES ON data1.* TO 'zhaoyim'@'%';
Query OK, 0 rows affected (0.03 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.03 sec)
```

Login with user:zhaoyim
```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| data1              |
| information_schema |
+--------------------+
2 rows in set (0.01 sec)
```

### Trino
catalog properties using user zhaoyim
```
trino:tpch> show schemas  from mysql;
       Schema
--------------------
 data1
 information_schema
(2 rows)
```

**Comment by ebyhr** [comment]
> Is there a problem with removing that?

Some query builder will break. 

Specifying the database in JDBC connection url isn't effective for access control. It's for default database.

**Comment by mpontillo** [comment]
> Specifying the database in JDBC connection url isn't effective for access control. It's for default database.

It would still be nice if this restriction could be removed, IMHO. Because, unfortunately, this also means that ProxySQL cannot direct queries to the appropriate shard when a user has access to multiple databases.
