### ISSUE TITLE
Rubix will not store cache files on coordinator, even it serves as worker

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#3563]
Even if we enable scheduling splits on coordinator via `node-scheduler.include-coordinator` Rubix will not store  any cache files on it (unless it is only node in the cluster).
The reason for that is Rubix uses `v1/nodes` endpoint to enumerate nodes in the cluster and list returned there never contains coordinator (btw, @electrum, is that intended?).

cc: @stagraqubole

**Comment by losipiuk** [comment]
I tagged it as bug. Please correct me if that is actually intended behavior :).

**Comment by stagraqubole** [comment]
This is a bug we never fixed given this was not a production scenario. For dev testing, rubix does support master-only mode.

**Comment by hashhar** [comment]
Rubix has been removed as of https://github.com/trinodb/trino/pull/20102 and replaced with file-system caching in https://github.com/trinodb/trino/pull/18719
