### ISSUE TITLE
Elastic searching for field with null and value not working correctly

### ISSUE THREAD

**Issue by eskabetxe** [trinodb/trino#3605]
this query:
`select id from tmp_table
where value is null or value = 37`

will generate this query 
`{
  "size" : 1000,
  "query" : {
    "bool" : {
      "filter" : [
        {
          "bool" : {
            "must" : [
              {
                "bool" : {
                  "should" : [
                    {
                      "bool" : {
                        "filter" : [
                          {
                            "term" : {
                              "value" : {
                                "value" : 37,
                                "boost" : 1.0
                              }
                            }
                          }
                        ],
                        "adjust_pure_negative" : true,
                        "boost" : 1.0
                      }
                    }
                  ],
                  "adjust_pure_negative" : true,
                  "boost" : 1.0
                }
              }
            ],
            "adjust_pure_negative" : true,
            "boost" : 1.0
          }
        }
      ],
      "adjust_pure_negative" : true,
      "boost" : 1.0
    }
  },
  "_source" : {
    "includes" : [
      "id"
    ],
    "excludes" : [ ]
  },
  "sort" : [
    {
      "_doc" : {
        "order" : "asc"
      }
    }
  ]
}`

but this excludes de null values, it only gives records with value 37..

the translation from elastic for that query is 
`{
  "query" : {
    "bool" : {
      "should" : [
        {
          "bool" : {
            "must_not" : [
              {
                "exists" : {
                  "field" : "value",
                  "boost" : 1.0
                }
              }
            ],
            "adjust_pure_negative" : true,
            "boost" : 1.0
          }
        },
        {
          "term" : {
            "value" : {
              "value" : 37,
              "boost" : 1.0
            }
          }
        }
      ],
      "adjust_pure_negative" : true,
      "boost" : 1.0
    }
  },
  "_source" : {
    "includes" : [
      "id"
    ],
    "excludes" : [ ]
  },
  "sort" : [
    {
      "_doc" : {
        "order" : "asc"
      }
    }
  ]
}`

**Comment by findepi** [comment]
#3480 adds `TestElasticsearch7DistributedQueries `, so this bug will be covered by a generic test case:
https://github.com/prestosql/presto/blob/a380c5d1bdc40056860f4b06f4dacd2dd8bbdff8/presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java#L1385

@eskabetxe are you planning on addressing this?

**Comment by eskabetxe** [comment]
I found that adding the test to that PR, the test is comment..

I try to fix it, but for some reason the "is null" filter is missing on query builder and I cant understand why. if you could guide me, I fix it

**Comment by findepi** [comment]
i am not an expert, but "is null" seems to be here:
https://github.com/prestosql/presto/blob/56aa0d71fad111e76b596a59f45380246c49b94e/presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchQueryBuilder.java#L85

**Comment by eskabetxe** [comment]
at that point, the domain only have the second value (= 37)

**Comment by findepi** [comment]
NULL is indicated with `domain.isNullAllowed()`.

**Comment by sumannewton** [comment]
@findepi @eskabetxe Addressed this issue in this [PR](https://github.com/trinodb/trino/pull/8204).
