### ISSUE TITLE
Presto csv format is not supported

### ISSUE THREAD

**Issue by AbhishekNew** [trinodb/trino#3664]
presto:default> CREATE TABLE onequerytb(
             -> order_date varchar,
             -> order_region varchar,
             -> order_id varchar,
             -> order_info varchar
             -> )
             -> WITH (format='CSV');
             -> ;
CREATE TABLE
presto:default> insert into onequerytb values('2019-9-17', 'kk', '3', 'pp');
Query 20200507_135842_00017_9cdss failed: java.lang.UnsupportedOperationException: Storage schema reading not supported

From Hive 
hive> create table update003(aa tinyint, bb smallint, cc int, dd bigint) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' ;

hive> LOAD DATA LOCAL INPATH '/root/sample.csv' INTO TABLE update003;
hive> select * from update003;
OK
1       1       1       1
1       1       1       0
Time taken: 1.275 seconds, Fetched: 2 row(s)

**Comment by ebyhr** [comment]
@AbhishekNew Could you take a look at this issue https://github.com/prestosql/presto/issues/2678?

**Comment by AbhishekNew** [comment]
I checked the issue details before it was talking more about external table and in this  case table is managed one.

**Comment by findepi** [comment]
@AbhishekNew see https://github.com/prestosql/presto/issues/2678#issuecomment-580255387 in particular

**Comment by ebyhr** [comment]
Feel free to reopen if you're still facing the issue.
