### ISSUE TITLE
LDAP authentication debugging

### ISSUE THREAD

**Issue by electrum** [trinodb/trino#3665]
Mention on the LDAP page about setting the log level to debug:
```
io.prestosql.plugin.password.ldap=DEBUG
```
With a reference to https://prestosql.io/docs/current/installation/deployment.html#log-levels

**Comment by mosabua** [comment]
Should we io.trino.

**Comment by Kshitiz-Mhto** [comment]
Is this issue about to add the line io.trino.plugin.password.ldap=DEBUG in the master/core/docker/default/etc/log.properties
or master/testing/trino-server-dev/etc/log.properties @electrum. If so, i am a newbie to open source contribution, i want to contribute to the docs.

**Comment by Ankan0011** [comment]
@mosabua 
This issue can be closes as it is already implemented.
https://trino.io/docs/current/security/ldap.html?highlight=ldap#debug-trino-to-ldap-server-issues
