### ISSUE TITLE
Allow CLI option for max_seconds_before_kill

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#3692]
Currently below command gets 'Error running command: StatementClient thread was interrupted' message if the query has not completed within 5 seconds:

timeout 5 ./presto --execute "SELECT blah.....

But the query continues running on the server, taking resources, even though for a SELECT the client has detached and will not receive the result.

This new option 'max_seconds_before_kill' would mean that the query gets killed if it has not completed by x seconds

**Comment by findepi** [comment]
There is a session property for this.

**Comment by yuokada** [comment]
@tooptoop4  
FYI: `query_max_execution_time` OR `query_max_run_time` are for this.
https://prestosql.io/docs/current/admin/properties-query-management.html

**Comment by ebyhr** [comment]
Closing as answered.
