### ISSUE TITLE
Document hive.parquet.use-column-names, hive.orc.use-column-names, hive.partition-use-column-names

### ISSUE THREAD

**Issue by jiegzhan** [trinodb/trino#3698]
Found out these three parameters via Teradata and Slack. 

hive.parquet.use-column-names
hive.orc.use-column-names
hive.partition-use-column-names

**Comment by findepi** [comment]
When documenting mind that defaults should be changed from their current setting (https://github.com/prestosql/presto/issues/1558).

**Comment by mosabua** [comment]
We have separate sections for orc and parquet now 

https://trino.io/docs/current/connector/hive.html#orc-format-configuration-properties

And hive.partition-use-column-names has been removed in 352 so we should no longer document it. ;-)

**Comment by ebyhr** [comment]
Let me close this issue:
* hive.parquet.use-column-names & hive.orc.use-column-names were already documented
* hive.partition-use-column-names has been removed
