### ISSUE TITLE
'result of sequence function must not have more than 10000 entries'

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#3699]
Following query errors:

 select x from unnest(sequence(date '1992-01-01', date '2019-12-31')) t(x)

https://github.com/prestosql/presto/blob/master/presto-main/src/main/java/io/prestosql/operator/scalar/SequenceFunction.java#L41

I know i can union multiple sequence as a workaround but 10k is small if backtesting a large date range. Proposing increasing to 100k

**Comment by korkile** [comment]
Same issue here? Any updates?

**Comment by electrum** [comment]
From a pure size limit, increasing to 100k, since that is still under 1MB.

**Comment by findepi** [comment]
With table functions we can avoid having any particular limit: https://github.com/trinodb/trino/issues/15845

**Comment by hashhar** [comment]
We now have table functions for this. https://trino.io/docs/current/functions/table.html#sequence-table-function
