### ISSUE TITLE
Elasticsearch IP field search enhancement

### ISSUE THREAD

**Issue by HernanMora** [trinodb/trino#3719]
Hi!

Since it is possible to query Ip fields in the following way:
```sql
select * from "myIndex" where ipField = IPADDRESS '10.11.0.32'
```
It'd be interesting to make queries where you can search on a subnet in the way Elasticsearch does it:

Elasticsearch:
```
... ipField:"10.11.0.0/17"
```
Presto:
```sql
select * from "myIndex" where ipField = IPADDRESS '10.11.0.0/17'
```
Do you think this would be possible in the near future?

**Comment by martint** [comment]
This is related to https://github.com/prestosql/presto/pull/110

To model this, we’d use a function, not an equality comparison. That also requires we add support for pushing  down functions into connectors (see https://github.com/prestosql/presto/issues/18) to be able to use Elasticsearch’s CIDR term queries.

**Comment by canob** [comment]
Hi @ebyhr. With **contains** you cannot search for an IP in a subnet.

Suppose that you have the IP 10.10.5.5, that is part of 10.10.0.0/16 subnet. You cannot use **contains** in that situation I think.
