### ISSUE TITLE
Validate operand types for operators like =, <, > or IS DISTINCT FROM

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#3728]
An operator should be defined on a type, ie so both left and right operand types should be the same.

- I am confident this is how they should be defined according to the SQL spec
- we rely on this in many places in the planner and optimizer

Make sure it's not possible to register an operator function with operands of different types.

**Comment by dain** [comment]
This was implemented as part of the TypeOperators code.  Operators are now defined directly on Types and have strictly enforced parameter types
