### ISSUE TITLE
Cassandra - Support pushdown for date, tinyint & smallint types

### ISSUE THREAD

**Issue by sundeeparun** [trinodb/trino#3763]
Date data type support was added as part of https://github.com/prestosql/presto/pull/141 but it is not pushed down to Cassandra when Date is a partition key 

`SELECT * FROM cassandra.testks.test 
WHERE dateCol = date '2020-01-05'`

**Table Structure**

`CREATE TABLE testks.test 
(
 dateCol date,
 textCol text,
 PRIMARY KEY (dateCol, textCol)
)`

When I looked at the Cassandra Connector code, we seem to be missing Date type added to https://github.com/prestosql/presto/blob/master/presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraType.java#L426

**Comment by Serenthia** [comment]
I'm also not able to retrieve data when the `date` type column is a clustering column (but not part of the partition key).  Is this also due to be solved by the linked PR, and if so might it be merged soon?
