### ISSUE TITLE
Support pushdown on row type column in MongoDB

### ISSUE THREAD

**Issue by sean-azoci** [trinodb/trino#3765]
Hi. I am testing prestosql with mongodb connector. 

I need to know if pushdown operation works on row type.
mongo table schema is below :
table : test
columns : 
a, row type, row type schema : row ( varchar r_a, row r_b( varcher rr_a, int rr_b))
b, varchar type

If I try to query a select statement like
select *
from test
where b = 'a'
 and a.r_a = 'b';

pushdown works well on b column, but doesn't work on a row type column.

to do this, I think It needs two functions. one is generating filter conditions on row type.
another is converting it to connector sql at connector level.

does it support pushdown on row type column?

**Comment by marioramaglia** [comment]
hello there,  any progress on this ?
In Mongo deeply nested documents and arrays are very common: 
is there any workaround to apply to a trino-mongo mapping schema (ie: mongodb.schema-collection)  to have better performance with Trino selects querying on nested mongo fields ?

Mongo Document:
![mongodoc](https://user-images.githubusercontent.com/82051970/114444127-cbd16c80-9bce-11eb-80a9-c0778cd2a87c.GIF)

here you have the auto generated schema:
[schema.txt](https://github.com/trinodb/trino/files/6299079/schema.txt)


On a 145k documents collection a simple query as:

` select a.b.TaxCode from mongocatalog.mongodb.collection
where a.b.TaxCode='08815100154';
`
takes approx 4 minutes.
thanks,
best regards.

**Comment by findepi** [comment]
To anyone who would want to work on this.

That should be possible via:

1. `ConnectorMetadata#applyProjection` -- Mongo connector should accept `a.b.TaxCode` dereference and expose it as a `TaxCode'` column
2. `ConnectorMetadata#applyFilter` -- Mongo connector to accept `TaxCode' = '08815100154'` filter as any other filter it accepts today.

**Comment by ebyhr** [comment]
Closing as https://github.com/trinodb/trino/pull/17710
