### ISSUE TITLE
Clarify unnest and cross join behavior

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#3812]
Copied from slack conversation with a user, @martint and @findepi : 

Hello community,
I'm running a query with a select on a field "addresses" that is a nested array (we use the Elasticsearch connector) that returns all the records in the database, the records that have a value in the field and those that have a null value.
    select addresses from customer_contacts;
But, if I run this query but with a CROSS JOIN UNNEST to the same field "addresses", only the registers with a non null value in the field are returned.
    select addresses from customer_contacts cross join unnest(addresses);
This is problem with Presto? By the docs, the CROSS JOIN should return all combinations of the values, which, in my understanding, includes null values...

martin  6 hours ago
If the addresses field is empty or null, UNNEST produces 0 rows, so the CROSS JOIN would produce 0 rows for that entry.
What you want is:
SELECT addresses FROM customer_contacts LEFT JOIN UNNEST(addresses) ON true

martin  6 hours ago
cc @Manfred Moser, we may want to add something to the docs explaining this scenario

findepi  5 hours ago
People are so used that UNNEST “equals” to CROSS JOIN UNNEST (because it used to be so).
This is why we should highlight the LEFT JOIN UNNEST more than we otherwise would need to. This in fast should be our leading examples, and perhaps default “unnest paradigm”.

martin  4 hours ago
Indeed. UNNEST  is just a table function, and as any other table-producing entity, it can be used in the FROM clause or as part of a JOIN clause. The regular semantics of  JOIN apply.

**Comment by mosabua** [comment]
This query
SELECT addresses FROM customer_contacts LEFT JOIN UNNEST(addresses) ON true
is really what I wanted. I tried the LEFT JOIN, but without the ON true and got an error, so I thought the UNNEST would only works with the CROSS JOIN.
Thank you very much everyone!

**Comment by rsaw4** [comment]
similar to https://github.com/trinodb/trino/issues/8471
