### ISSUE TITLE
Pass dynamic filters back to workers from coordinator

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#3972]
After https://github.com/prestosql/presto/pull/1072 dynamic filters from all nodes will be collected in coordinator. Such filters should be passed back to workers so that during table scans filters from all Presto nodes (not only node local) are used to skip data in files.

**Comment by findepi** [comment]
You would combine them with OR, wouldn't that make them less effective?

**Comment by sopel39** [comment]
> You would combine them with OR, wouldn't that make them less effective?

Why OR? It should be AND with whatever local predicate there is

**Comment by findepi** [comment]
DFs are AND-ed with static predicates, but DFs are combined with OR, right?
So node-local DF will be more restrictive than a global DF.

**Comment by sopel39** [comment]
> but DFs are combined with OR, right?

No. Everything is AND-ed (apart for DFs originating from same join).

This issue is about table scans that are not filtered by local dynamic filters (e.g because of hash join) or are not fully filtered.
