### ISSUE TITLE
Add support for variable-precision timestamp type to Hive connector

### ISSUE THREAD

**Issue by martint** [trinodb/trino#3977]
# Considerations

* Currently, the connector supports only `timestamp(3)`. The metastore supports "timestamp with optional nanosecond precision" (see https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Types#LanguageManualTypes-TimestampstimestampTimestamps). 
    * Each data format may support a different underlying type, so appropriate conversions need to be implemented. Currently, values are truncated to the precision expected by Presto. We should update to do rounding to match the type semantics.
* There's a performance cliff above timestamp(6), so equating Hive's timestamp to Presto timestamp(9) might not be optimal. We'll probably want a configuration option in the connector to indicate how Hive timestamps should be mapped. We'll also need this for backward compatibility. If existing Hive tables all switch to timestamp(9), may queries may start to fail due to type mismatch issues.

**Comment by findepi** [comment]
Read part is generally done by in https://github.com/prestosql/presto/pull/4953 and will be available in 342.

**Comment by findepi** [comment]
Done by @aalbu and @jirassimok . Thank you!
