### ISSUE TITLE
Error connecting to ElasticSearch with TLS

### ISSUE THREAD

**Issue by dekelev** [trinodb/trino#3989]
I'm unable to connect to ElasticSearch with TLS and getting this error when running a query:

```
javax.net.ssl.SSLPeerUnverifiedException: Host name some.host.name does not match the certificate subject provided by the peer (CN=instance)
```

I thought that `elasticsearch.tls.verify-hostnames` option set to `false` will fix that, but it didn't.

This is my `elasticsearch.properties` file:
```
connector.name=elasticsearch
elasticsearch.host=some.host.name
elasticsearch.port=9200
elasticsearch.default-schema-name=default
elasticsearch.tls.enabled=true
elasticsearch.tls.verify-hostnames=false
elasticsearch.tls.keystore-path=/some/path/some-es-cert.p12
elasticsearch.tls.truststore-path=/some/path/some-es-cert.p12
elasticsearch.tls.keystore-password=
elasticsearch.tls.truststore-password=
```

The target ElasticSearch server config file `elasticsearch.yml` includes only the following regarding TLS:
```
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: none
xpack.security.transport.ssl.keystore.path: certs/some-es-cert.p12
xpack.security.transport.ssl.truststore.path: certs/some-es-cert.p12
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.keystore.path: certs/some-es-cert.p12
xpack.security.http.ssl.truststore.path: certs/some-es-cert.p12
xpack.security.http.ssl.verification_mode: none
```

BTW, I'm unable to open the `some-es-cert.p12` file without a password and I'm not sure if this is required. I don't have the password for this file anyway and if it will be required, I'll have to re-generate the file and replace it in all the ElasticSearch servers.

Presto v337
Mac OS Catalina v10.15.4

**Comment by dyhyao6** [comment]
hi, do you solve this problem? i had the same problem with it . how to solve it ? @dekelev

**Comment by dekelev** [comment]
I was missing the password for the keystore/truststore. I guess it should work with it.

**Comment by ebyhr** [comment]
Please reopen if the issue still occurs.

**Comment by ksajjan** [comment]
Below worked for me

```
connector.name=elasticsearch
elasticsearch.host=elastichost.com
elasticsearch.port=9200
elasticsearch.security=PASSWORD
elasticsearch.auth.user=elastic_user
elasticsearch.auth.password=elastic_user_password
elasticsearch.default-schema-name=default
elasticsearch.ignore-publish-address=true
elasticsearch.tls.enabled=true
elasticsearch.tls.truststore-path=/home/ubuntu/ca.crt

```

Also give a try to property

`elasticsearch.tls.verify-hostnames=false`
