### ISSUE TITLE
Web UI downloading too much data

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#4102]
Web UI is downloading 1MB every 2 seconds. jquery.min.js mainly shows up in chrome tools.

"The exact size depends on the number of workers/active queries.
I can see 500kb per request.

Yeah, the main page can be pretty heavy if you have a lot of queries. It's a known issue but has never been a big priority to fix. It's a hard problem, as you need to separate out immutable data like query text from mutable data like stats, probably also need to keep track of deltas, etc.

There are most likely still easy wins to be had around pruning the data down.  For example, I don’t think we show the full query text.

in the past this was more difficult, but when I redid the UI for security I separated out all of the endpoints the UI uses, so they can be changed without breaking anything else in Presto.

We should not need to refresh data for completed queries, since this doesn’t change.

This might have regressed after 331. We have 331 with fast UI response, but 334 onwards things have been very slow. Now I avoid going to the UI."

**Comment by tooptoop4** [comment]
similar to https://github.com/prestosql/presto/issues/5929

**Comment by qgxiaozhan** [comment]
Is anyone doing this ? I also find that the large amount of data leads to the jam of chrome page。
