### ISSUE TITLE
wildcard tables not supported for BigQuery connector

### ISSUE THREAD

**Issue by yunrougong** [trinodb/trino#4124]
The Presto BigQuery connection doesn't support wildcard tables statements like below
`select * from bigquery.bq_schema.ga_sessions_* limit 100`

`SQL Error [65536]: Query failed: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: request failed: wildcard tables are not supported. 
`

Here is the documentation for more details https://cloud.google.com/bigquery/docs/reference/standard-sql/wildcard-table-reference

**Comment by findepi** [comment]
One way of doing this is transplanting BigQuery syntax and supporting this within table name (as currently done in https://github.com/trinodb/trino/pull/12428).
```sql
SELECT *  FROM "table_prefix_*" ...
```

 This has the advantage of being familiar to BigQuery users, but also some disadvantages -- a table with `*` may actually exist (unless this is forbidden by bigquery). Also, a wildcard table is not a real table, so one e.g. cannot add a column to it (unless we translate this to adding column on a collection of tables).

The other option would be to support this as a engine-level syntax.

```sql
SELECT *  FROM table_prefix_* ...
```

This has the advantage of neing applicable to all connectors. And a disadvantage of being a departure from SQL spec and therefore something unlikely we want.

A third option would be to implement this as a polymorphic table function reading a collection of tables, e.g.
```sql
SELECT *  FROM TABLE tables_by_prefix('table_prefix_')
```

cc @martint @kasiafi @trinodb/maintainers

**Comment by ebyhr** [comment]
> a table with * may actually exist (unless this is forbidden by bigquery)

It's forbidden in BigQuery

> a wildcard table is not a real table, so one e.g. cannot add a column to it (unless we translate this to adding column on a collection of tables).

Just throwing an exception as unsupported operations is acceptable to me. (BigQuery also prohibits DML on wildcard tables)

> A third option would be to implement this as a polymorphic table function reading a collection of tables

I guess a polymorphic table function makes the codes complicated especially when we want to support pushdowns to remote databases?

**Comment by findepi** [comment]
> I guess a polymorphic table function makes the codes complicated especially when we want to support pushdowns to remote databases?

PTF doesn't preclude pushdowns. see #12325 for example.

**Comment by ebyhr** [comment]
Exactly. I thought it doesn't support pushdowns since there's no such test in the PR. Verified it works correctly.

**Comment by findepi** [comment]
I am in favor of `"table_prefix_*"` syntax because

- it's BigQuery-specific but at this point the use-case seems BigQuery-specific too
- it's most familiar for the users

let's wait few more days for others @trinodb/maintainers to chime in if they have opinion.

**Comment by kasiafi** [comment]
@findepi @ebyhr The `"table_prefix_*"` syntax seems a good solution because it fits in the Trino identifier semantics, and so does not burden the engine with BigQuery-specific syntax or semantics.
On the other hand, I think that polymorphic table functions should be considered the canonical solution to the issue of non-standard syntax. If we add query pass-through PTF for BigQuery, it will also address any other non-standard syntax that BigQuery supports.

**Comment by findepi** [comment]
BigQuery query pass-though is a good idea.
`"table_prefix_*"` syntax is nice, because it's "natural" for the users and doesn't require switching over to SQL-in-SQL that query pass-through involves.

**Comment by kasiafi** [comment]
> `"table_prefix_*"` syntax is nice, because it's "natural" for the users and doesn't require switching over to SQL-in-SQL that query pass-through involves.

I'm OK with it, especially that this change is local to BigQuery connector.

**Comment by ebyhr** [comment]
Actually, I was investigating if I we can use query pass-though in BigQuery connector last week, but it looks difficult to get output metadata before actual execution. BigQuery supports "dry run" option, but it returns some statistics and doesn't include column names and types.

**Comment by kasiafi** [comment]
> BigQuery supports "dry run" option, but it returns some statistics and doesn't include column names and types.

We could try to run the passed query with limit 0, but that would require careful verification that it has no side-effects.

Other solution would be to require that the user provides the expected relation type, as the function parameter. The `DESCRIPTOR` argument type would be a good fit.

**Comment by findepi** [comment]
> We could try to run the passed query with limit 0,

That works only if the remote engine's (ie BigQuery) optimizer really prunes the query plan and replaces it with equivalent of VALUES.
That's not obvious to me it would do this.

**Comment by kasiafi** [comment]
> That's not obvious to me it would do this.

Sure, that's the basic thing we should learn before we go this way. I would be surprised if BigQuery, or any engine, lacked this optimization.

**Comment by martint** [comment]
`"table_prefix_*"` is acceptable for now, but using a table function as suggested above (`SELECT *  FROM TABLE (tables_by_prefix('table_prefix_'))`) is more SQL idiomatic. Note that it doesn't need to implement full query passthrough for this -- just a function that enumerates tables and extracts metadata, and a table-function-to-table-scan substitution.

**Comment by kasiafi** [comment]
> "table_prefix_*" is acceptable for now, but using a table function as suggested above (SELECT * FROM TABLE (tables_by_prefix('table_prefix_'))) is more SQL idiomatic. Note that it doesn't need to implement full query passthrough for this -- just a function that enumerates tables and extracts metadata, and a table-function-to-table-scan substitution.

@martint I'm not sure it's that easy. If we "import" the matching tables to Trino, and union them on our own, then we also have to coerce to supertype. Our coercion rules might differ from BigQuery.

**Comment by kasiafi** [comment]
> Does bigquery allow getting metadata for a “wildcard table”?

@ebyhr do you know the answer?

**Comment by ebyhr** [comment]
@kasiafi Yes, it does. `com.google.cloud.bigquery.BigQuery#getTable()` accepts wildcard tables and returns the metadata.
