### ISSUE TITLE
presto-server-rpm cannot be eraserd  when presto service has been stoped

### ISSUE THREAD

**Issue by qfrtrt** [trinodb/trino#4174]
`[ /etc/presto]$ sudo rpm -e --allmatches presto-server-rpm-335-1.x86_64`
`Please stop the Presto service before erasing RPM`
`...`
`[ /etc/presto]$ service presto status`
`Getting status for presto`
`Not running`

**Comment by kokosing** [comment]
What is the output of:
```
/etc/init.d/presto status
echo $?
```

**Comment by qfrtrt** [comment]
```
$ /etc/init.d/presto status
Getting status for presto
Not running
$ echo $?
3
```

**Comment by kokosing** [comment]
According to https://github.com/prestosql/presto/blob/master/presto-server-rpm/src/main/rpm/preremove#L2 it should work correctly.

Can you retry: `sudo rpm -e --allmatches presto-server-rpm-335-1.x86_64`?

**Comment by qfrtrt** [comment]
![image](https://user-images.githubusercontent.com/32293062/85519934-d23d2a80-b634-11ea-96c0-e87a37ad2844.png)

**Comment by hashhar** [comment]
Seems to work on current versions. Tested on centos 7.

```
[root@fbae07f9e558 /]# rpm -e trino-server-rpm-440.SNAPSHOT-1.noarch
Please stop the Trino service before erasing RPM
error: %preun(trino-server-rpm-0:440.SNAPSHOT-1.noarch) scriptlet failed, exit status 1
error: trino-server-rpm-0:440.SNAPSHOT-1.noarch: erase failed
[root@fbae07f9e558 /]# /etc/init.d/trino stop
Stopping trino
Stopped 254
[root@fbae07f9e558 /]# rpm -e trino-server-rpm-440.SNAPSHOT-1.noarch
warning: /etc/trino/node.properties saved as /etc/trino/node.properties.rpmsave
warning: /etc/trino/env.sh saved as /etc/trino/env.sh.rpmsave
```

Possibly fixed via https://github.com/trinodb/trino/commit/53f2fda3ba57130f12eac7ddd702bdf48998bd50#diff-a646745b719eb9d8086288222c1d0f6dc40306be0892029945e703f534c9e7d7 (before this change we were comparing integers to strings)
