### ISSUE TITLE
Insert behavior in Hive connector needs documentation

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#4180]
Some info can be found here 

http://www.ebyhr.org/2019/04/insert-overwrite-in-presto.html

set session hive.insert_existing_partitions_behavior = 'overwrite'; 
then insert overwrite sometable select * from tmp;

hive.insert-existing-partitions-behavior  

fyi @electrum @ebyhr @tnatssb

**Comment by josonle** [comment]
still use insert into table select ...

**Comment by mosabua** [comment]
This is documented now
