### ISSUE TITLE
Enable format checks on loggers

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#4189]
Investigate usefulness of `AnnotateFormatMethod` errorprone check (see https://github.com/prestosql/presto/issues/4188 for more context).

We would need airlift loggers (https://github.com/airlift/airlift/tree/master/log) to be annotated with `@FormatMethod`.

To be checked: does it need to be _any_ `@FormatMethod` annotation (by name), or `com.google.errorprone.annotations.FormatMethod` specifically?

**Comment by wendigo** [comment]
@findepi I've enabled `AnnotateFormatMethod` errorprone check and a number of places are pretty huge in PrestoSQL. When I've enabled `-Xep:FormatString:ERROR` I've found a couple of places with bad `String.format` use which should be fixed first.

**Comment by hashhar** [comment]
Some attempt here - https://github.com/trinodb/trino/pull/14933

**Comment by findepi** [comment]
Seems done in https://github.com/airlift/airlift/pull/922

**Comment by ksobolew** [comment]
There's also airlift/airlift#954, but it was deemed "too much" ;)
