### ISSUE TITLE
Schema migration tool for DB-based resource group and session property managers

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#4191]
Currently we the DB-based resource/session managers create required schema on start. E.g.

https://github.com/prestosql/presto/blob/6d9d47e0909b3fe9367584ba8450827dbbb8e1d7/presto-resource-group-managers/src/main/java/io/prestosql/plugin/resourcegroups/db/DbResourceGroupConfigurationManager.java#L102-L104

This works if schema does not change.

We should provide an automated or guided way of schema migration, to future-proof for any changes we may want to introduce there.
For example, DB-based resource group  managers do not support group-based selectors yet.

This is a necessary step to allow for broader adoption of DB-based resource group and session property managers.
Currently this is very "expertly feature".

cc @rclaude

**Comment by findepi** [comment]
Proposed solution would be to use Flyway on startup automatically, just as we `CREATE TABLE IF NOT EXISTS` on startup today.

**Comment by nineinchnick** [comment]
I think this can be closed now, reopen if I'm wrong.
