### ISSUE TITLE
Show session zone in query details page

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#4196]

**Comment by vishalya** [comment]
The issue originated to troubleshoot the difference between the outputs produced by the presto-cli and odbc driver. I see that the queries received in both the cases are same (conditioned on date/time) and they produce different results.
so, it would be good to know the timezone or any other session details which might be affecting the results.

**Comment by dain** [comment]
@findepi do we still need this with the fixed timestamp semantics?

**Comment by amitsingh-10** [comment]
Do we want something like this here? @findepi 

![Session Time Zone added into Query UI](https://user-images.githubusercontent.com/51735639/106383173-5edd7180-63ea-11eb-966f-9bd348c63b3a.png)

**Comment by amitds1997** [comment]
Do we want something like this, @findepi ?
![Session TimeZone added to Query UI](https://user-images.githubusercontent.com/29333147/106383223-baa7fa80-63ea-11eb-9f26-297597c877fd.png)

**Comment by findepi** [comment]
@amitds1997 yes, that would be great!
