### ISSUE TITLE
Add hooks to call an open tracing api to feed telemetry data to various tracing systems

### ISSUE THREAD

**Issue by bitsondatadev** [trinodb/trino#4207]
There have been [some requests for query tracing](https://github.com/prestosql/presto/issues/1826) as well as suggestions on the slack channel to add some method to understand presto workflow at a more granular level. I think it would be useful to implement some advice hooks that call [open tracing apis](https://github.com/opentracing/opentracing-java) that could feed into distributed tracing systems such as [Jaeger](https://www.jaegertracing.io/) or [ZipKin](https://zipkin.io/). 

These tracing systems provide useful concepts such as [spans](https://opentracing.io/docs/overview/spans/#what-is-a-span) and [tracers](https://opentracing.io/docs/overview/tracers/#tracer-interface) and enable visualizing workflows for troubleshooting and educational purposes.

**Comment by bitsondatadev** [comment]
An example of cool things we could do with this https://github.com/trinodb/trino/issues/3468.

**Comment by martint** [comment]
cc @mattstep
