### ISSUE TITLE
Add support for aggregate pushdown of `count(distinct expr)`

### ISSUE THREAD

**Issue by Parth-Brahmbhatt** [trinodb/trino#4323]
Currently the optimizer rule is not invoked for `count(distinct expr)`. We may need to add a new rule or set of rules to handle this in order to support this when mark distinct is enabled vs when it is not.

**Comment by electrum** [comment]
Technically, all aggregate functions can support distinct, although it doesn’t seem particularly useful or common in practice.

**Comment by findepi** [comment]
I believe this is done now.
cc @alexjo2144 @hashhar
