### ISSUE TITLE
Support GRANT/REVOKE privileges on columns

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#4328]
Currently it is possible to grant/revoke access to tables (and views). This ticket is about adding similar functionality on columns level.

Suggested syntax:

```
GRANT SELECT (column) ON schema.table TO USER bob;
```

**Comment by hashhar** [comment]
isn't this possible after https://github.com/trinodb/trino/commit/b5988bfc8adac4adf3f80ff6201b48a6937d60eb?
Or do you mean engine should provide this?
