### ISSUE TITLE
Create connector for ClickHouse

### ISSUE THREAD

**Issue by GPF199541** [trinodb/trino#4500]

**Comment by mosabua** [comment]
You could implement a new connector that uses the Clickhouse JDBC driver https://clickhouse.tech/docs/en/interfaces/jdbc/

Similar to e.g. how the PostgreSQL connector works.

**Comment by wgzhao** [comment]
I had create clickhouse for prestosql version 338 and has applied my production environment.

https://github.com/wgzhao/presto-clickhouse

**Comment by findepi** [comment]
@wgzhao nice! Would you be interested in contributing this?
This would make it easier for others to use your connector and also 
it would be kept up to date.

**Comment by wgzhao** [comment]
OK，I will try it later

Piotr Findeisen <notifications@github.com>于2020年7月24日 周五17:46写道：

**Comment by wgzhao** [comment]
> @wgzhao nice! Would you be interested in contributing this?
> 
> This would make it easier for others to use your connector and also 
> 
> it would be kept up to date.
ok 
how can i do for it?

**Comment by mosabua** [comment]
You would have to send a pull request that adds the connector to the main project here. We have detailed documentation on [the website](https://prestosql.io/development/process.html)

**Comment by findepi** [comment]
The connector has been merged (https://github.com/trinodb/trino/pull/4909) and will be availble in the next release.

I created #7103 to track follow up work.
