### ISSUE TITLE
Add system table to expose optimizer stats

### ISSUE THREAD

**Issue by martint** [trinodb/trino#4504]
Currently, the only ways to look at per-rule execution stats are via JMX (VisualVM or JConsole) or by querying their mbeans via the JMX connector. Unfortunately, each rule gets its own table, so it's very inconvenient to query each one individually.

We should add a system table that exposes the performance stats tracked by optimizer rules in a single, more convenient place.
The table should contain:
* Rule name
* Count
* Matches
* Failures
* Average Time
* Time distribution (percentiles)

**Comment by kokosing** [comment]
Notice that JMX connector supports wildcards in table name so you can query many tables at once. 

Maybe JMX connector should allow to define a view?

**Comment by martint** [comment]
Yes, I forgot about wildcard tables. In any case, the resulting table contains more data that's needed (e.g., node id, time unit fields). We may want other data later on that cannot be exposed via JMX directly, or map to appropriate SQL types that the JMX connector can't handle generically.

> Maybe JMX connector should allow to define a view?

Where would it be stored?

**Comment by kokosing** [comment]
> Where would it be stored?

They could be statically defined in JMX. Maybe under `jmx.views`? Maybe we could allow user to provider their own views provided with configuration files?

**Comment by sopel39** [comment]
related: https://github.com/trinodb/trino/issues/2578

**Comment by sopel39** [comment]
@martint @phd3 can this be closed via https://github.com/trinodb/trino/pull/4659?

**Comment by phd3** [comment]
Closed by #4659
