### ISSUE TITLE
Invalid value returned by CLI, JDBC when ROW contains `fieldN` field

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#4594]
```
presto> SELECT CAST(ROW(1, 2) AS ROW(field1 integer, integer));
   _col0
------------
 {field1=2}
(1 row)
```

This is because the second, unnamed field, gets a default name `field1`, causing a collision.
https://github.com/prestosql/presto/blob/838048343f6868f65f574bc00edf612a1b5ee77e/presto-client/src/main/java/io/prestosql/client/FixJsonDataUtils.java#L117

Relates to: https://github.com/prestosql/presto/issues/4587

**Comment by wendigo** [comment]
@findepi Should we allow named and unnamed fields in the row at the same time in the first place?

**Comment by ebyhr** [comment]
Going to close this issue since it's already fixed in both CLI and JDBC driver.
