### ISSUE TITLE
Hash aggregation spill should yield on GroupByHash memory reservations

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#460]
Currently, `SpillableHashAggregationBuilder#rebuildHashAggregationBuilder` creates `InMemoryHashAggregationBuilder` with yielding disabled. This is particularly important as revocable memory reservations are large and `GroupByHash` rehashing (without yielding) might put memory pressure on GC. In order to support `GroupByHash` memory yielding for spilling aggregations we should:
1. Remove dependency on `InMemoryHashAggregationBuilder` from `SpillableHashAggregationBuilder`. `SpillableHashAggregationBuilder`
    should use `GroupByHash` directly.
2. `GroupByHash` should have methods that don't return `Work` but
    return next page position (`addPage` method) or partial `GroupByIdBlock`
    (`getGroupIds` method) when input `Page` was not fully consumed.

**Comment by hashhar** [comment]
@sopel39 do we want to get rid of spilling eventually in favor of FTE?
