### ISSUE TITLE
Write timestamp as int96 by default in the optimizer Parquet writer

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#4608]
Currently, the optimizer Parquet writer writes timestamp as int64.
This is supported by Hive 4+, but apparently not by earlier versions.
We should write timestamp as int96 for compatibility with existing
readers.

Also, this requires updating `testParquetTimestampInt64PredicatePushdown` test (https://github.com/prestosql/presto/pull/4526#discussion_r476458707)

**Comment by findepi** [comment]
cc @alexjo2144

**Comment by findepi** [comment]
Closing in favor of https://github.com/trinodb/trino/issues/9244 and https://github.com/trinodb/trino/issues/6377

**Comment by findinpath** [comment]
Note that in Parquet `2.5.0` the `INT96` type used by some Hive distributions to encode timestamps has been deprecated.

https://issues.apache.org/jira/browse/PARQUET-323
