### ISSUE TITLE
Support Oracle's NUMBER data type

### ISSUE THREAD

**Issue by walter-weinmann** [trinodb/trino#4764]
Please set a default value in Oracle Connector as follows:

`oracle.number.default-scale=10
`

and also add a short description of the property 

`oracle.number.default-scale 
`

to the documentation of the Oracle Connector.

**Comment by ebyhr** [comment]
I'm not sure why the default value is required. Could you share the reason? How did you choose 10?

Agreed to add the documentation.

**Comment by walter-weinmann** [comment]
The problem is that 38 is not working (bug) and 10 covers the maximum integer (2 147 483 647) which seems pretty sensible.

**Comment by losipiuk** [comment]
There is no default value for `oracle.number.default-scale` on purpose as there is not one-size-fits all solution.
Also the `oracle.number.default-scale` is not about total number of digits in a number (which is represented by precision). 
The precision is always set to 38 for mapping of Oracle's NUMBER type without precision specified.
Scale is about number of decimal point. So setting scale to 10 results would result in mapping of Oracle's `NUMBER` to Presto's `DECIMAL(38,10)` (28 decimal digits before decimal point and 10 after).

**Comment by walter-weinmann** [comment]
Ok - the problem is that BIGINT is not supported without this property - please see #4750.

**Comment by losipiuk** [comment]
> Ok - the problem is that BIGINT is not supported without this undocumented property - please see #4750.

I understand. Yet my point is that it is very non-obvious what values to expect in Oracle's column typed as `NUMBER`.
If there are values in range 0-2^^31 with no decimal digits, then using e.g 10 as `oracle.number.default-scale` make sense.
But if someone stores there some factional number 0.<many_fractional_digits> `10` does not make sense at all.

IMO the choice here is too arbitrary to just go with `10`. I would rather fix documentation and explicitly state there that one need to specify `oracle.number.default-scale` to use Oracles generic `NUMBER`. And also explain how the mapping works.

**Comment by walter-weinmann** [comment]
The problem is still not solved with version 344 - it is still necessary to specify a default value, e.g: 

`oracle.number.default-scale=10`

**Comment by findepi** [comment]
I am closing this in favor of https://github.com/trinodb/trino/issues/2274

**Comment by findepi** [comment]
Finally fixed in
- https://github.com/trinodb/trino/pull/28748
