### ISSUE TITLE
Implement TopN pushdown for JDBC connectors

### ISSUE THREAD

**Issue by Parth-Brahmbhatt** [trinodb/trino#4769]
We introduced topN pushdown rule recently. This issue is to do the actual implementation on presto jdbc connector so it can handle topN pushdown.

**Comment by Parth-Brahmbhatt** [comment]
Work in progress https://github.com/prestosql/presto/pull/4784

**Comment by findepi** [comment]
This has been implemented for PostgreSQL in https://github.com/trinodb/trino/pull/4784 / https://github.com/trinodb/trino/pull/6847. Thanks @Parth-Brahmbhatt @wendigo !

This needs to be now extended for other connectors as well. 
Also, this is not yet enabled by default, see https://github.com/trinodb/trino/issues/7031.
