### ISSUE TITLE
Can't find documentation for 'IN' operator 

### ISSUE THREAD

**Issue by chhsiao90** [trinodb/trino#4791]
https://prestosql.io/docs/340/functions/list.html

I can't find any documentation about the 'IN' operator for `SELECT * FROM table WHERE col IN ('foo', 'bar')`

**Comment by ebyhr** [comment]
`IN` is documented at https://prestosql.io/docs/current/sql/select.html#in

**Comment by electrum** [comment]
@mosabua We should also document this on https://prestosql.io/docs/current/functions/comparison.html with examples of how this works for null and with tuples (and tuples with nulls)

**Comment by mosabua** [comment]
Let's keep this open since we still need to add this information at https://trino.io/docs/current/functions/comparison.html

**Comment by ishween** [comment]
Hi, I'm interested in working on this. Can someone assign it to me?
Thank you!

**Comment by mosabua** [comment]
Once you have a PR please link to this ticket and we can help with review.

**Comment by ishween** [comment]
Thank you @mosabua 
Also, I wanted to confirm upon searching for IN clause in Presto documentation it's present in the [SELECT](https://prestodb.io/docs/current/sql/select.html#in) clause and not in [Comparison](https://prestodb.io/docs/current/functions/comparison.html). 
For the Trino documentation, it's the same present in the [SELECT](https://trino.io/docs/current/sql/select.html?highlight=exist#exists) clause and not in [Comparison](https://trino.io/docs/current/functions/comparison.html)

I wanted to confirm, that we want to add more information about IN regarding its behavior with null and with tuples in the Comparison tab in Trino documentation only?

**Comment by mosabua** [comment]
That works for me .. both sections should probably linked to each other as well. Just put a PR together with what you think works and improves what we have and we can discuss more details there. I can also pull in help from others as needed.

**Comment by mosabua** [comment]
cc @bitsondatadev @colebow
