### ISSUE TITLE
Schema filtering for Hive catalogs

### ISSUE THREAD

**Issue by kosinsky** [trinodb/trino#4796]
Currently Hive connector allows to specify uri for Hive Metastore and makes all schemas form default catalog visible.
In case, some schemas need to be skipped for security or convenience reasons (for example, we have two hive catalogs with different properties that use the same Hive Metastore)

Hive Metastore Thrift API supports filtering schemas (databases) with `get_databases(String pattern)` method.
Pattern allows to select only few databases in the default catalog: `schema1|schema2` or 'schema*` or select schemas from different Hive metastore catalog `@catalog#schema1`

Hive connector could support new property:
`hive.metastore.thrift.client.database-pattern=<pattern>` (Default `*` that means everything from default catalog)

That property should be passed to `get_databases` instead of using `get_all_databases`

Known limitation. We can't ask for databases from different catalogs `@cat1#|@cat2#` will ignore databases from `cat2`

**Comment by electrum** [comment]
This is actually a security feature which is already supported. Simply filtering in the `get_databases()` metastore call is not sufficient, as that would not help with other calls like `get_table()`, alternate metastore implementations, etc. It could lead to strange situations such as a user creating a new schema that does not matched by the filtering pattern.

If you're using [file based authorization](https://prestosql.io/docs/current/connector/hive-security.html#file-based-authorization) for Hive, you can add schema rules to restrict the available schemas.

You can also use the [file based system access control](https://prestosql.io/docs/current/security/file-system-access-control.html) to limit schemas in any catalog.

**Comment by kosinsky** [comment]
File based system access control solves problem only partially:
* It denies access to the tables, but they are still visible it causes confusion for end-users
* `@cat1#` pattern allows to access non default catalogs from Hive Metastore

That is a problem tho - "It could lead to strange situations such as a user creating a new schema that is not matched by the filtering pattern."

**Comment by kokosing** [comment]
> File based system access control solves problem only partially:

@kosinsky Can you please try to check https://github.com/prestosql/presto/pull/5039 and see if it helps to you?

**Comment by kosinsky** [comment]
Looks like `testSchemaRulesForCheckCanShowSchemas` in #5039 tests that schemas that people don't have access will be hidden. That should cover my scenario.

**Comment by kokosing** [comment]
@kosinsky Can we close the issue then?
