### ISSUE TITLE
Document docker requirement for presto-docs to README

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#4807]
Also, we may want to add the command to skip it.
```bash
./mvnw -pl '!presto-docs' clean install -DskipTests
```

**Comment by mosabua** [comment]
Can you take care of that and also review the rest of the readme .. some of the FAQ items and such do not apply anymore

**Comment by dprophet** [comment]
I suspect at most large corporations and finance companies, they are not allowed to use external docker containers (sometimes even 3rd party binaries like an RPM). Making various parts of Presto build depend on external docker containers breaks the capability to build presto within large corporations.

**Comment by mosabua** [comment]
You just skip the presto-docs module if that is an issue .. as documented above. I will send a PR to update the readme.

**Comment by mosabua** [comment]
@Ordinant is doing an update at the moment. Please ensure this is added and updated for Trino.

**Comment by ebyhr** [comment]
Closing because README already has docker requirement.
