### ISSUE TITLE
Yugabyte compatibility in the Cassandra connector with DATE types

### ISSUE THREAD

**Issue by awishnick** [trinodb/trino#4836]
It appears that Cassandra supports DATE literals either as an integer number of days since the epoch, or as an ISO-format string, while Yugabyte only supports an ISO-format string. As a result, a query like this gives incorrect results:

select * from table where foo = 'bar' and date > date('2020-02-01') order by date;

Debugging shows the following output:

io.prestosql.plugin.cassandra.CassandraSession Execute cql: SELECT "date" FROM "aaron"."table" WHERE "foo" in ('bar') AND "date" > 18293

One solution would be a connector option for Yugabyte compatibility that formats dates as ISO-format strings. Another would be to unconditionally do this.

cc @ebyhr since @martint suggested that he's more familiar with this connector too.

**Comment by findepi** [comment]
I would consider that we add a dedicated connector for Yugabyte. @awishnick would you mind filing an issue to plan this work?

**Comment by ebyhr** [comment]
This is actually Cassandra connector's bug. Relates to #3763
