### ISSUE TITLE
Cassandra connector doesn't discover new keyspaces/tables with Yugabyte

### ISSUE THREAD

**Issue by awishnick** [trinodb/trino#4838]
I'm using the Cassandra connector to talk to Yugabyte's YCQL endpoint. I notice that if I add new keyspaces/tables through Yugabyte, I can't see them in Presto unless I restart Presto. This means "SHOW SCHEMAS" and "SHOW TABLES" don't reflect the new keyspaces/tables, but also I can't "SELECT" or otherwise query from the new tables.

**Comment by ebyhr** [comment]
Have you already tried PostgreSQL connector instead of Cassandra? I'm experimenting YugabyteDB JDBC based connector now.

**Comment by ebyhr** [comment]
We need a dedicated connector for Yugabyte. Let me close as there's another issue #5352
