### ISSUE TITLE
Enhance access control to `system.jdbc`

### ISSUE THREAD

**Issue by archongum** [trinodb/trino#4865]
For example, if user `ext_ba` only have access to schema  `ext_ba`, so user `ext_ba` should disallow to see the other schemas.
Discuss on: https://prestosql.slack.com/archives/CGB0QHWSW/p1597651093446200
![image](https://user-images.githubusercontent.com/20929338/90461545-1fbbac80-e139-11ea-98e5-3180e3067769.png)

**Comment by huberty89** [comment]
Cannot reproduce it, tested on 399
