### ISSUE TITLE
[hotfix] Code compilation error on pom.xml

### ISSUE THREAD

**Issue by XuQianJin-Stars** [trinodb/trino#4883]
`spotbugs` is error on `pom.xml` 
The error is as follows:
1. spotbugs is error
![image](https://user-images.githubusercontent.com/10494131/90602764-d6e52000-e22c-11ea-9d16-7dccf1a372a8.png)

**Comment by ebyhr** [comment]
Going to close this as an accidental issue during downloading dependencies.
