### ISSUE TITLE
Account memory for collected local dynamic filters

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#4896]
Currently, memory for local dynamic filters (that are stored in `io.prestosql.sql.planner.LocalDynamicFiltersCollector`) is not accounted for. While filter size is limited at the moment, they might become larger eventually.

**Comment by hashhar** [comment]
Seems to have been added in https://github.com/trinodb/trino/commit/67656139e8a292bb9251e8706bf497600595291d?

Do I read that correctly @sopel39? Feel free to re-open if I misunderstood.

**Comment by sopel39** [comment]
Retained mem is still not accounted for, but I guess nobody complaied, so we are probably good

**Comment by hashhar** [comment]
Oh, should be easy to add though since we have the instance size stuff already implemented. Can you let me know how to let engine know of this memory?

For queries we use a call to `MemoryPool#reserve` in `QueryContext`. I don't where the DFs would be plugged in?

**Comment by sopel39** [comment]
I think they should probably be plugged into task mem directly, probably under new `io.trino.memory.context.MemoryTrackingContext#newUserMemoryContext`
