### ISSUE TITLE
Remove StandardColumnMappings#jdbcTypeToPrestoType

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#4914]
We should deprecate and remove `StandardColumnMappings#jdbcTypeToPrestoType`.
Every connector should provide their own mapping, just like they provide their tests.
This way we can know what we support and what we do not.
This also removes the desire/need to compose column mapping objects, which
is proven to be error prone in practice. 

Let's make `io.prestosql.plugin.jdbc.BaseJdbcClient#toPrestoType` abstract:

* [ ] hide a call to `StandardColumnMappings#jdbcTypeToPrestoType`  behind a fallback toggle (https://github.com/prestosql/presto/pull/4940)
* [ ] implement mappings in all connectors explictly
* [ ] remove the fallback after a few releases.

**Comment by ebyhr** [comment]
Let me close this issue because those methods were already removed.
