### ISSUE TITLE
Add tests for Redshift connector

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#497]
We need following tests for Redshift connector:

- derived from `AbstractTestDistributedQueries` (see `TestPostgreSqlDistributedQueries` for example)
- type mapping tests (see `TestPostgreSqlTypeMapping` for example)
- predicate pushdown tests (see also https://github.com/prestosql/presto/issues/496)

The tests will depend on external infrastructure (AWS account).
- it should be possible to run the tests providing minimal setup (see Glue and S3 tests)
- after https://github.com/prestosql/presto/issues/274 we will ru these tests as part of CI

**Comment by kokosing** [comment]
Dump question, is it possible to have a docker image for redshift?

**Comment by dain** [comment]
Test were added but are not automatically run in the CI

**Comment by ebyhr** [comment]
Closing as we have Redshift CI environment now.
