### ISSUE TITLE
Add support for ZetaSQL dialect

### ISSUE THREAD

**Issue by medb** [trinodb/trino#4993]
If Presto has a pluggable SQL language dialects support it could be nice to add support for [ZetaSQL](https://github.com/google/zetasql) to improve interoperability with other query engines that adopting ZetaSQL.

**Comment by findepi** [comment]
@medb thank you for the suggestion.
While we have extension model for connectors (data access), security, monitoring, etc
Presto currently does not provide pluggable language and we have no plans do so.
Presto follows SQL standard. Can you possibly outline the potential benefits we could
realize by adopting ZetaSQL? Both engineering and end-user perspective?
Perhaps, even if we decide not to adopt ZetaSQL, we may draw inspiration or benefit
from parts of it.

**Comment by medb** [comment]
Adding support for ZetaSQL per se will provide compatibility only with query engines that already supports it (Google BigQuery, Google Cloud Dataflow, etc).

But if Presto adopts [Apache Calcite](https://calcite.apache.org) to make SQL language pluggable in Presto then it will allow to support ZetaSQL and other SQL dialects and will make Presto a query engine of choice for migrations from other query engines and will increase Presto adoption.

**Comment by hashhar** [comment]
We have no plans to add pluggable SQL dialects.

Please re-open if still relevant.
