### ISSUE TITLE
Add hidden $partition column to Hive connector

### ISSUE THREAD

**Issue by martint** [trinodb/trino#5]
It can help for computing or filtering the raw partition names that are provided by other Hive-related tools. E.g., ` ds=2017-05-23/type=abc/ts=2017-05-23+21%3A45%3A99`.

It should support pushdown for partition pruning.

- [x] Add initial $partition column (#3582)
- [ ] Support pushdown for partition pruning

**Comment by mosabua** [comment]
I think this is done. Right @martint @ebyhr ?

**Comment by ebyhr** [comment]
Pushdown isn't yet supported if I remember correctly, but let's file a new issue if necessary.
