### ISSUE TITLE
Access control for materalized views

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#5041]
We need to verify if user is eligible to `CREATE`, `DROP`, `SHOW CREATE VIEW`, `DESCRIBE`, list (`SHOW TABLES`) or `SELECT` from a `MATERIALIZED VIEW`

**Comment by sopel39** [comment]
I don't think `SELECT from a MATERIALIZED VIEW` is actual privilege. We don't have such check for normal views, do we?

**Comment by martint** [comment]
It should be. Materialized views are separate entities and it makes sense to be able to limit acces to them.

It should also be possible to limit access to views (if we’re not doing that already), just like tables. At least, that’s how the standard SQL security model works.

**Comment by sopel39** [comment]
@martint https://github.com/trinodb/trino/pull/7618 adds `SELECT` checks for MV

**Comment by raunaqmorarka** [comment]
Fixed with 
https://github.com/trinodb/trino/pull/7618
https://github.com/trinodb/trino/pull/7707
https://github.com/trinodb/trino/pull/7645
