### ISSUE TITLE
SHOW CREATE TABLE output uses unicode escapes instead of showing unicode characters

### ISSUE THREAD

**Issue by wangfeigithub** [trinodb/trino#5061]
show create table  Chinese display exception. The following.
```sql
CREATE TABLE real_mysql.monitor.tableau_report_summary_info (
   workbook_datasource_name varchar(255) COMMENT U&'\5DE5\4F5C\7C3F\6570\636E\6E90\540D\79F0',
   workbook_name varchar(255) COMMENT U&'\5DE5\4F5C\7C3F\540D\79F0',
   project_name varchar(255) COMMENT U&'\9879\76EE\540D\79F0',
   datasource_name varchar(255) COMMENT U&'\6570\636E\6E90\540D\79F0',
   datasource_account varchar(255) COMMENT U&'\6570\636E\6E90\8D26\53F7',
   datasource_create_time timestamp(3) COMMENT U&'\6570\636E\6E90\521B\5EFA\65F6\95F4',
   datasource_update_time timestamp(3) COMMENT U&'\6570\636E\6E90\66F4\65B0\65F6\95F4',
   datasource_project_name varchar(255) COMMENT U&'\6570\636E\6E90\9879\76EE',
   datasource_server varchar(255) COMMENT U&'\6570\636E\6E90\6765\6E90\4E3B\673A',
   datasource_dbclass varchar(255) COMMENT U&'\6570\636E\6E90\9A71\52A8\7C7B',
   datasource_port varchar(255) COMMENT U&'\6570\636E\6E90\7AEF\53E3\53F7',
   datasource_username varchar(255) COMMENT U&'\6570\636E\6E90\7528\6237',
   datasource_nviews integer COMMENT U&'\6570\636E\6E90\6D4F\89C8\91CF',
   dm_tableau_report varchar(255) COMMENT U&'tableau\62A5\8868\540D\79F0',
   dm_hive_dm_table varchar(255) COMMENT 'dm',
   dm_condition_column varchar(100) COMMENT U&'\6761\4EF6\5217\FF0C\7528\4E8E\5B58\50A8tableau\62A5\8868\7684\5224\65AD\5B57\6BB5\5217',
   dm_condition_sql varchar(2048) COMMENT U&'\6761\4EF6sql\8BED\53E5\FF0C\7528\4E8E\5B58\50A8tableau\62A5\8868\66F4\65B0\65F6\95F4\7684\76D1\63A7\8BED\53E5',
   dm_max_report_time timestamp(3) COMMENT U&'tableau\62A5\8868\7684\76D1\63A7\65F6\95F4',
   dm_memo varchar(65535) COMMENT U&'\5907\6CE8\FF0C\7528\4E8E\5B58\50A8\4E00\4E9B\4E8B\9879\8BF4\660E',
   dm_update_time timestamp(3) COMMENT U&'tableau\62A5\8868\66F4\65B0\65F6\95F4',
   dm_create_time timestamp(3) COMMENT U&'tableau\62A5\8868\521B\5EFA\65F6\95F4',
   rsi_update_time timestamp(3) NOT NULL COMMENT U&'\66F4\65B0\65F6\95F4',
   rsi_create_time timestamp(3) NOT NULL COMMENT U&'\521B\5EFA\65F6\95F4'
)
```

How was it modified or what caused it !
thinks

**Comment by ebyhr** [comment]
Do you mean `SHOW CREAT TABLE` doesn't show the column comment even though you can execute `CREATE TABLE`?

**Comment by wangfeigithub** [comment]
> Do you mean `SHOW CREAT TABLE` doesn't show the column comment even though you can execute `CREATE TABLE`?

I mean the annotation is unicode. Not display Chinese.  
How can I display it in Chinese? 
thinks!!

**Comment by dain** [comment]
I think this is the issue: https://github.com/prestosql/presto/blob/07ab946fcbcc33d1aacb96e478330f58bfe228d8/presto-parser/src/main/java/io/prestosql/sql/ExpressionFormatter.java#L810

The code is checking of the comment is ASCII and does not contain control characters, etc.  I think we need a better rule.

**Comment by wangfeigithub** [comment]
> I think this is the issue:
> 
> https://github.com/prestosql/presto/blob/07ab946fcbcc33d1aacb96e478330f58bfe228d8/presto-parser/src/main/java/io/prestosql/sql/ExpressionFormatter.java#L810
> 
> The code is checking of the comment is ASCII and does not contain control characters, etc. I think we need a better rule.

https://github.com/prestosql/presto/blob/07ab946fcbcc33d1aacb96e478330f58bfe228d8/presto-parser/src/main/java/io/prestosql/sql/ExpressionFormatter.java#L823 
-

**Comment by wangfeigithub** [comment]
https://github.com/prestosql/presto/blob/07ab946fcbcc33d1aacb96e478330f58bfe228d8/presto-parser/src/main/java/io/prestosql/sql/ExpressionFormatter.java#L823
There will be one more \ for Chinese Unicode, so the conversion fails. How to deal with it

**Comment by changqing** [comment]
any progress? We can see this issue with trino 390
