### ISSUE TITLE
Support statistics when using AWS Glue

### ISSUE THREAD

**Issue by dongwoo1005** [trinodb/trino#5072]
AWS glue began supporting statistics recently. See this Glue API documentation: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/glue/get-column-statistics-for-partition.html

Presto should be able to support statistics when using Glue now

**Comment by kenjihiraoka** [comment]
Yep, this would be a great feature to Presto

**Comment by amommendes** [comment]
It would be great to have support for statistics for glue

**Comment by Lewuathe** [comment]
I have looked into the codebase to see how to get the Glue partition statistics and found `DisabledGlueColumnStatisticsProvider` which was added in https://github.com/prestosql/presto/commit/7fe264725dd20c551637f4d5a4803b7414382722. It looks that was added to extend `GlueColumnStatisticsProvider` to support Glue column statistics when it's available. Is this assumption correct?

**Comment by sopel39** [comment]
> Is this assumption correct?

Yes. Please use `GlueColumnStatisticsProvider`. Later we can remove that extension altogether.

**Comment by ckdarby** [comment]
Also noticed PrestoDB had a PR to support this:
https://github.com/prestodb/presto/pull/14947

**Comment by GaruGaru** [comment]
The pull request that @ckdarby linked looks pretty complete (even if it hasn't been reviewed yet), are there any major  implementation differences between prestosql and prestodb that we should be aware of before using it as reference ?

**Comment by findepi** [comment]
@hsuchenc (the author of that PR) is from Amazon and I would be surprised if they didn't want to contribute Glue stats support here to Presto. 

@hsuchenc, apparently here is much more interest in your PR than elsewhere 😉
Are you planning on making a contribution?

**Comment by hsuchenc** [comment]
My hands are pretty tied, so feel free to port it from PrestoDB to PrestoSQL.
Thank you.

**Comment by GaruGaru** [comment]
On behalf of my company I'm working on the implementation of this feature following the @hsuchenc pull request as reference

**Comment by GaruGaru** [comment]
I've submitted the pull request #6178 with some changes / performance improvements, big thank you to @hsuchenc for his work

**Comment by wordhardqi** [comment]
how to create stats for glue table?
