### ISSUE TITLE
Document hive.query-partition-filter-required

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#5235]
`hive.query-partition-filter-required` is mentioned in 331 RNs.
let's have this documented too

cc @JamesRTaylor @mosabua

**Comment by mosabua** [comment]
Should it just be added in https://prestosql.io/docs/current/connector/hive.html#hive-configuration-properties ?

Code has description as

```
Require filter on at least one partition column
```

Release notes item says

```
* Add option to enforce that a filter on a partition key be present in the query. This can be enabled by setting the
  ``hive.query-partition-filter-required`` configuration property or the ``query_partition_filter_required`` session property
  to ``true``. (:issue:`2334`)
```

Not sure if there is a specific order on that table or a better place to put it

**Comment by mosabua** [comment]
I can take care of sending a PR once I get info if that table is fine to start

**Comment by mosabua** [comment]
Lets add it to that table.

**Comment by Ankan0011** [comment]
This is already in the docs, can be closed.
[Link](https://trino.io/docs/current/connector/hive.html#hive-general-configuration-properties)
