### ISSUE TITLE
Migrate Tempto to GitHub Actions

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#5256]
Migrate Tempto (https://github.com/prestosql/tempto/) from Travis to GHA.

**Comment by RohanMenon** [comment]
Hi! I'm looking forward to working on this. Wanted to ask this: any restriction for using plugins like Okta here?

**Comment by findepi** [comment]
@RohanMenon nice! let's only make sure @Praveen2112 is not working on it (Praveen had some questions about this offline)

> any restriction for using plugins like Okta here?

what would Okta be for here?

**Comment by RohanMenon** [comment]
This is my first time working on such a migration. So to gain some background, one of my search results led to using Okta plugin for this. Hence the question 😄

**Comment by findepi** [comment]
@Praveen2112 would you be able to provide guidance here?

**Comment by Praveen2112** [comment]
Yes !! I would love to.

**Comment by RohanMenon** [comment]
@Praveen2112 Is this https://fbernutz.github.io/posts/github-actions/ an appropriate resource for this?

**Comment by Praveen2112** [comment]
@RohanMenon Yes we can check that too. We can also check on how we migrate for projects like Slice
Ref : https://github.com/airlift/slice/pull/123

**Comment by RohanMenon** [comment]
Got it. Will go through that too. Thanks!

**Comment by hashhar** [comment]
Was implemented in https://github.com/trinodb/tempto/pull/84
