### ISSUE TITLE
Update documentation for parametric TIME WITH TIME ZONE

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#5316]
https://prestosql.io/docs/current/language/types.html#time-with-time-zone

**Comment by mosabua** [comment]
Now at https://trino.io/docs/current/language/types.html#time-with-time-zone

**Comment by mosabua** [comment]
Not sure what is specifically missing..

But the current example is wrong. It doesnt actually work

TIME '01:02:03.456 America/Los_Angeles'

Instead this works 

select TIME '01:02:03.456 -07:00';

We should update the example at least and specify that the numeric format should be used. And if a text format is used we should say which one and have an example as well.

**Comment by mosabua** [comment]
E.g this format doesnt work either

```
SELECT TIME '01:02:03.456 US/Pacific';
```

**Comment by mosabua** [comment]
cc @martint if you have any insights on this...

**Comment by meggpie** [comment]
@mosabua I can work on this one!

**Comment by martint** [comment]
@mosabua , the reason is that political time zones are no longer supported with the time type since they have undefined semantics - you need to know the date to be able to tell what the actual offset is.

**Comment by anubhav823** [comment]
Hi! Is this issue still open?

**Comment by hashhar** [comment]
I think not since it was addressed with combination of https://github.com/trinodb/trino/pull/7912 and https://github.com/trinodb/trino/pull/13927

**Comment by anubhav823** [comment]
Ok thanks!
