### ISSUE TITLE
Implement COMMENT ON COLUMN in JDBC based connector

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#5333]
- [x] ClickHouse https://github.com/trinodb/trino/pull/10641
- [x] Druid (not supported)
- [ ] MemSQL (@shandeep00)
https://docs.memsql.com/v7.1/reference/sql-reference/data-definition-language-ddl/alter-table/
- [ ] MySQL (#5383)
https://dev.mysql.com/doc/refman/8.0/en/alter-table.html
- [x] Oracle (#5399)
https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_4009.htm
- [x] Phoenix (not supported)
- [x] PostgreSQL (#5307)
- [x] Redshift (#5397)
https://docs.aws.amazon.com/redshift/latest/dg/r_COMMENT.html
- [ ] SQL Server 
https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-addextendedproperty-transact-sql?view=sql-server-ver15
reminder: SQL Server JDBC driver isn't exposing a comment via REMARKS column

**Comment by agrawalreetika** [comment]
@ebyhr, I would like to work on this. Could you please let me know if the issue is different from #5334?

**Comment by ebyhr** [comment]
@agrawalreetika While #5334 is for CREATE TABLE, this ticket's objective is supporting COMMENT ON TABLE. I think this ticket is easier than #5334.

**Comment by shandeep00** [comment]
@ebyhr @agrawalreetika anyone working on support for Mysql?

**Comment by agrawalreetika** [comment]
@shandeep00 I have started looking into changes for implementing comment on a column in MySQL, will raise PR soon

**Comment by shandeep00** [comment]
cool, maybe this can help u started, https://www.tutorialspoint.com/How-can-we-use-MySQL-ALTER-TABLE-command-for-adding-comments-on-columns

**Comment by Riddle4045** [comment]
@ebyhr  is the work for SQL server done? if not i'd be happy to take it!

**Comment by ebyhr** [comment]
@Riddle4045 Not yet. You can take it freely, but please note that:
* SQL Server doesn't expose column comment via REMARKS result set. We will need to introduce a flag not to decrease the performance for metadata fetching.
* You need to find how to create `CREATE TABLE` with column comments in SQL Server

**Comment by Riddle4045** [comment]
@ebyhr  Thanks, I browsed through https://github.com/microsoft/mssql-jdbc/issues/646, Looks like Microsoft does not intend to add support for  `REMARKS` in the jdbc driver. This would mean we use extended properties for retrieving comments and multiple calls ( again through extended properties ) to support `CREATE TABLE`. I doubt this feature mandates the complexity budget for the connector,  what do you think?
