### ISSUE TITLE
Document field quote example for MongoDB _schema collection

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#5353]
We sometimes get question about MongoDB field case sensitivity in `_schema` collection. It would be better to document it explicitly. While auto generated schema will be quoted automatically, some people miss the rule when they are fixing the collection manually.
```
row("UpperCase" varchar,"lowercase" varchar)
```

**Comment by Kalpanat** [comment]
is this still open ? Im new here, let me know if I can work on this.

**Comment by ebyhr** [comment]
@Kalpanat Yes, it's still opened and you can work. The file path is https://github.com/trinodb/trino/blob/master/docs/src/main/sphinx/connector/mongodb.rst
