### ISSUE TITLE
Implement variable precision timestamp handling for optimized Parquet writer

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#5357]
https://github.com/prestosql/presto/pull/5283 implements the write path for variable precision timestamps, but not for the optimized Parquet writer.

tests to be added

- Enable nanosecond timestamp unit tests to run against Optimized Parquet Writer
- Update `TestHiveStorageFormats.storageFormatsWithNanosecondPrecision` to not filter out optimized storage formats.

**Comment by findepi** [comment]
> Enable nanosecond timestamp unit tests to run against Optimized Parquet Writer

i copied this from https://github.com/trinodb/trino/issues/8715
@Justin-Kwan can you mention exact test classes to be updated?

**Comment by Justin-Kwan** [comment]
After nanosecond timestamps types are supported by the optimizer Parquet writer, only `TestHiveStorageFormats.storageFormatsWithNanosecondPrecision` needs to be updated to test against any `PARQUET` storage formats that have the property `hive.experimental_parquet_optimized_writer_enabled` enabled.
