### ISSUE TITLE
Use local limit instead of local Top N if stream is sorted on ordering column

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#5372]
When stream is sorted on ordering column, it is possible to use partial `Limit` operator instead of partial `TopNOperator`. This allows to quickly skip splits in source stage.

**Comment by abhishek8gupta** [comment]
I am a beginner and would like to contribute to presto. Let me know if I can pickup this issue. Also, please share some more details.

**Comment by sopel39** [comment]
Generally, there should be a rule (see `io.prestosql.sql.planner.iterative.Rule`) that recognizes that data is sorted (using `PropertyDerivations` and `io.prestosql.spi.connector.SortingProperty`) and replaces `TopN` with `Limit` operator. Something similar has been done for: https://github.com/prestodb/presto/pull/10731 (albeit much more complicated).

When I think about this issue more, it's not as easy as I though. Feel free to think about it and let me know if you would like to work on it.
