### ISSUE TITLE
Add support for MySQL datetime data type

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#5449]
See TODO comment in
https://github.com/prestosql/presto/blob/50a87c711f7967772cab0d6fb70f9e2810ff5587/presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlTypeMapping.java#L437-L442

> ```
> // TODO MySQL datetime is not correctly read (see comment in StandardColumnMappings.timestampColumnMappingUsingSqlTimestamp)
> // testing this is hard because of https://github.com/prestosql/presto/issues/37
> ```

(the referenced issue (https://github.com/prestosql/presto/issues/37) is generally done)

rel https://github.com/trinodb/trino/issues/6910

**Comment by findepi** [comment]
See also TODO in the code (being added in https://github.com/prestosql/presto/pull/5455)

**Comment by hashhar** [comment]
Fixed by merging https://github.com/trinodb/trino/pull/8060. MySQL connector now uses `java.time` API avoiding the DST related issues.
