### ISSUE TITLE
Add Iceberg tests for Hive tables in the same metastore

### ISSUE THREAD

**Issue by electrum** [trinodb/trino#5459]
Create a mix of Hive and Iceberg tables in the same metastore schema.

Listing tables in a schema:
```sql
SHOW TABLES;
```

Listing columns in a schema:
```sql
SELECT *
FROM information_schema.columns
WHERE table_schema = '...';
```

Run twice, once where `xxx` is an Iceberg table and once where `xxx` is not an Iceberg table:
```sql
SELECT 
FROM information_schema.columns
WHERE table_schema = '...' AND table_name = 'xxx';

DESCRIBE xxx;
```

Selecting from a table:
```sql
SELECT * FROM non_iceberg_table;
```

**Comment by findepi** [comment]
This is now mostly covered by existing `TestIcebergHiveMetadataListing`, with SELECT scenario being added in https://github.com/trinodb/trino/pull/8692
