### ISSUE TITLE
Better k8s/helm experience

### ISSUE THREAD

**Issue by ckdarby** [trinodb/trino#5480]
At the moment there isn't' an "official PrestoSQL" helm chart nor does the community offer a repo.

The Helm default repo does come with a stable PrestoSQL chart seen [here](https://github.com/helm/charts/tree/master/stable/presto), which only a couple of months ago switched from PrestoDB to PrestoSQL and prior to that hadn't been maintained for years.

There are a lot of issues with this chart:
- Getting changes into the default chart takes multiple of months. [Example](https://github.com/helm/charts/pull/23646), [another](https://github.com/helm/charts/pull/23539).
- Isn't very extendable 
- Tons of configuration is missing and can't be easily overridden (Hive cache ttl, query.max-memory-per-node)
- There is no toggle configuration for opting into best practices (Such as security, TLS, etc)

The hope is the Presto community provides a more friendly experience for operators of Kubernetes such as the expansive [Pulsar's helm charts](https://github.com/apache/pulsar-helm-chart/).

**Comment by mosabua** [comment]
it would be great to get some community run Helm charts off the ground.

**Comment by ckdarby** [comment]
@findepi Any internal progress at Starburst to open up a generic chart for both Starburst's edition & community edition? I'm asking as helm is [deprecating their chart repo](https://helm.sh/blog/charts-repo-deprecation/) and this includes the [PrestoSQL stable repo](https://github.com/helm/charts/tree/master/stable/presto).

**Comment by ebyhr** [comment]
We have https://github.com/trinodb/charts repository now.

**Comment by ashishjullia** [comment]
Hi, @findepi @ebyhr @hashhar @Epicsteve2 why there isn't an option to create an issue on the [official GitHub chart page](https://github.com/trinodb/charts)?

How we're are supposed to ask questions?

**Comment by findepi** [comment]
Issues will sometimes cross repo boundaries. E.g. docker image (definition, health checks, mount paths, entry point) is maintained in the main Trino repo. Let's use Trino main repo's issues for **issues**.

@ashishjullia  For **questions** please use the `#kubernetes` slack channel.

**Comment by mosabua** [comment]
How about we add a Issue section with a link to the main repos issue section and the slack reference to the readme file in the repo? @colebow could send a PR

**Comment by ashishjullia** [comment]
@findepi @mosabua You do have a point but it really becomes confusing to add all the issues (even related to k8s specifically helm chart - which was originally I posted for).

There are surely scenarios where people (I'm one of them) might not want to join the slack channel at all, although it is really great that you guys do provide support/help on issues on a slack channel.

But again having a dedicated "issues section" in repository is truely beneficial, in that way it is easier to create a separation line.

I hope it makes sense and understandable.
