### ISSUE TITLE
Support distributed cache for hive metastore

### ISSUE THREAD

**Issue by xumingming** [trinodb/trino#549]
The distributed cache will help in two scenario: 

1. multiple clusters(multiple Presto, or Prest & Hive) want to keep consistency for HiveMetaStore. 
2. When someday presto support more than one coordinator, distributed cache will also help.

**Comment by dain** [comment]
Isn't this something better put inside of the Hive Metastore, so every engine doesn't have to reimplement it.

**Comment by raunaqmorarka** [comment]
Hive Metastore Service does support a server side cache https://cwiki.apache.org/confluence/display/Hive/Hive+Metadata+Caching+Proposal
In cloud deployments a common setup is to have HMS running on master node along with Presto coordinator and making the HMS use an off-cluster RDS instance. Similar setup is common with Hive and Spark as well. That's where the approach of a caching metastore client that uses a distributed cache could be useful.
Also, if we have multiple coordinators in Presto after the work on dispatcher what would be done with the current guava based metastore cache ? Will it be restricted only to per-transaction caching ?

**Comment by dain** [comment]
> Also, if we have multiple coordinators in Presto after the work on dispatcher what would be done with the current guava based metastore cache ? Will it be restricted only to per-transaction caching ?

Yes only a per-transaction cache can be used when there are multiple coordinators.

**Comment by electrum** [comment]
The metastore cache in Presto never worked well. Users were often confused when a partition was added by Hive but it didn't show up instantly in Presto. This is why it's been disabled by default for several years.

I agree with @dain that this is better handled by the metastore. To meet the goals of working with other systems like Hive and Spark, we can't just implement the cache in Presto -- it needs to be added to Hive and Spark as well. You need a central cache service that they can all talk to, like memcached, and they all need to agree on exactly how the cache protocol should work. 

Implementing such a cache across Presto, Hive and Spark seems like much more work than implementing it once in the metastore. It would also be more difficult for users, as they would need to configure caching across all the services, in addition to how to talk to the metastore service.

Let me read the metastore cache proposal in detail. Maybe there are details I'm missing.
