### ISSUE TITLE
Change Iceberg time travel syntax and add tests

### ISSUE THREAD

**Issue by electrum** [trinodb/trino#5500]
We should change the time travel syntax for tables to distinguish between snapshot IDs and timestamps:

* `table@123` -- snapshot ID
* `table@t123` -- as-of timestamp in UNIX milliseconds

As part of this change, we need integration tests for both of these types of table queries.

**Comment by electrum** [comment]
@manishmalhotrawork is going to work on this

**Comment by pPanda-beta** [comment]
The existing syntax is also not working.
Prestosql-348/iceberg 0.10.0

When I queried with a snapshot id, it is returning the value of latest data.
I queried on march 12, 2021, and seen data till march 20, 2021

**Comment by lirui-apache** [comment]
Found this issue while I was searching for iceberg time travel syntax (seems missing in the official doc [1]).

I think snapshot ID and UNIX milliseconds can be user unfriendly in some scenarios. Could we also support specifying a timestamp string?  To do that, the temporal table feature defined in SQL:2011 [2] might be a candidate for the new syntax.

[1] https://trino.io/docs/current/connector/iceberg.html#
[2] https://en.wikipedia.org/wiki/SQL:2011

**Comment by ebyhr** [comment]
Let me close as the connector supports `VERSION AS OF` syntax now.
