### ISSUE TITLE
The cluster is stuck due to major gc

### ISSUE THREAD

**Issue by gaojun2048** [trinodb/trino#5505]
presto version: 322
cluster config: 32C 64G node * 3
jdk: openjdk-11
Today I am doing a concurrent test, the number of concurrent queries is 10. After running several tests, the cluster is stuck and all queries are stuck. I checked the logs of presto and found the following:

![image](https://user-images.githubusercontent.com/32193458/95652020-b8aaea80-0b20-11eb-8a00-983cce86ccb5.png)

config.properties files:
```
query.max-memory=122880MB
experimental.spill-window-operator=true
task.level-time-multiplier=0
estimated-memory-resource-factor=1.0
colocated-joins-enabled=True
http-server.http.port=8285
experimental.spiller-spill-path=/data1/presto/spill-path
node-scheduler.include-coordinator=true
optimizer.optimize-hash-generation=true
concurrent-lifespans-per-task=3
experimental.spiller-threads=4
enable-estimated-cpu-resource-execution=false
exchange.min-error-duration=30m
node-scheduler.network-topology=flat
join-distribution-type=BROADCAST
mysql-password-encryption-enable=False
query.max-memory-per-node=8192MB
experimental.spill-enabled=true
experimental.spill-order-by=true
node-scheduler.max-splits-per-node=100
http-server.threads.max=1500
query.max-total-memory-per-node=8192MB
http-server.https.enabled=false
exchange.http-client.request-timeout=30m
dynamic-schedule-for-grouped-execution=True
task.concurrency=16
http-server.https.port=4285
grouped-execution-enabled=True
experimental.work-processor-pipelines=true
experimental.max-spill-per-node=300GB
discovery.uri=http://node2:8285
node-scheduler.max-pending-splits-per-task=10
exchange.max-error-duration=150m
http-server.http.enabled=true
task.http-response-threads=100
experimental.spill-compression-enabled=true
experimental.reserved-pool-enabled=false
coordinator=false
```

**Comment by sopel39** [comment]
Hey. Please use https://prestosql.slack.com/archives/CGB0QHWSW (troubleshooting) slack channel for discussing such issues.

**Comment by findepi** [comment]
@gaojun2048 if you're not on slack yet, please see https://prestosql.io/slack.html for getting started.

**Comment by gaojun2048** [comment]
Ok, I am on slack

**Comment by tooptoop4** [comment]
did u solve @gaojun2048 ?

**Comment by gaojun2048** [comment]
> did u solve @gaojun2048 ?

No, now we still have this problem occasionally.

**Comment by gaojun2048** [comment]
![image](https://user-images.githubusercontent.com/32193458/120762707-15906080-c549-11eb-85a4-c0e6adb3b4b2.png)

As long as the general pool is full, it will be stuck and the cpu usage rate will drop to 0.

**Comment by hashhar** [comment]
> As long as the general pool is full, it will be stuck and the cpu usage rate will drop to 0.

This seems like the Trino OOM killer came into effect. You can reduce the amount of time it waits to kill a query by `query.low-memory-killer.delay` (default is 5mins).

But since the cluster is running into OOM condition it means that you are overcomitting memory. If you want queries to succeed without failure either limit the concurrency via resource groups or add more memory. 16GB is a very small heap. It's more economical to run smaller number of larger machines (to reduce memory overhead per JVM).

**Comment by gaojun2048** [comment]
> > As long as the general pool is full, it will be stuck and the cpu usage rate will drop to 0.
> 
> This seems like the Trino OOM killer came into effect. You can reduce the amount of time it waits to kill a query by `query.low-memory-killer.delay` (default is 5mins).
> 
> But since the cluster is running into OOM condition it means that you are overcomitting memory. If you want queries to succeed without failure either limit the concurrency via resource groups or add more memory. 16GB is a very small heap. It's more economical to run smaller number of larger machines (to reduce memory overhead per JVM).
> 
> Also if you have 64GB nodes why not provide 70% of the memory to the heap? Are there other processes running on the nodes?

Yes, there are some other processes running on the nodes. So only 16G memory can use by presto.

**Comment by gaojun2048** [comment]
> > As long as the general pool is full, it will be stuck and the cpu usage rate will drop to 0.
> 
> This seems like the Trino OOM killer came into effect. You can reduce the amount of time it waits to kill a query by `query.low-memory-killer.delay` (default is 5mins).
> 
> But since the cluster is running into OOM condition it means that you are overcomitting memory. If you want queries to succeed without failure either limit the concurrency via resource groups or add more memory. 16GB is a very small heap. It's more economical to run smaller number of larger machines (to reduce memory overhead per JVM).
> 
> Also if you have 64GB nodes why not provide 70% of the memory to the heap? Are there other processes running on the nodes?

Yes, Your are right. It is ok now.
