### ISSUE TITLE
When does the community support Presto  on Spark ?

### ISSUE THREAD

**Issue by wjf989** [trinodb/trino#5514]
presto on spark is currently  supported in PrestoDB. When does the prestosql community support Presto  on Spark???

**Comment by martint** [comment]
What would be the use case for this? Presto is a self-contained query engine, so it's not clear to me what's the benefit of running on spark.

**Comment by jerryleooo** [comment]
@martint I guess the points mentioned in https://prestodb.io/blog/2021/10/26/Scaling-with-Presto-on-Spark make sense

Trino/Presto may not be very fit for some ETL jobs, if we can use the same SQL syntax but more suitable engine, I think it would be better?

**Comment by raunaqmorarka** [comment]
https://trino.io/blog/2022/05/05/tardigrade-launch.html will address the ETL use cases that are targeted by "Presto on Spark".
