### ISSUE TITLE
CREATE TABLE docs should have an example of creating a partitioned table

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#5537]
if i google for 'create partitioned table in presto' it is not very helpful, looking at specific https://prestosql.io/docs/current/sql/create-table.html does not help either. Need to query SELECT * FROM system.metadata.table_properties then find partitioned_by then look for example of how to specify it when creating a table

**Comment by tooptoop4** [comment]
similar to https://github.com/prestosql/presto/issues/5581

**Comment by bitsondatadev** [comment]
For now see this episode
https://trino.io/episodes/5.html

**Comment by hashhar** [comment]
There are now examples in the connectors which support partitioned tables. e.g. see https://trino.io/docs/current/connector/hive.html#basic-usage-examples for Hive or https://trino.io/docs/current/connector/iceberg.html#basic-usage-examples for Iceberg for example.
