### ISSUE TITLE
Support partition_by in CREATE TABLE when avro_schema_url is set in Hive connector

### ISSUE THREAD

**Issue by shawnzhu** [trinodb/trino#5572]
Today, this is documented [limitation](https://prestosql.io/docs/current/connector/hive.html#limitations) when using `avro_schema_url`:

> Using `partitioning(partitioned_by)` or `bucketing(bucketed_by)` columns are not supported in `CREATE TABLE`.

Here's the code:
https://github.com/prestosql/presto/blob/0d1b31d2a0e7d25956719ddd2533ec763fb6ed94/presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java#L832-L834

However, when creating an external table via Hive (v2.3.5), it supports both `avro.schema.url` and `partition by`, and it can query this table via prestosql very well.

I learned from [this](https://prestosql.slack.com/archives/CFLB9AMBN/p1602794547294100) Slack thread:

> We added a check to be on the safe side when adding support for avro schema. avro schema could change behind the scenes and conflict with partition columns. someone would need to test what Hive does in such a situation.

## Expected result

Support `partition_by` in `CREATE TABLE` statement when `avro_schema_url` is set. but also explore problems like :point_up: design.

**Comment by findepi** [comment]
cc @lxynov

**Comment by ajklili** [comment]
This is supported now as in https://github.com/trinodb/trino/blob/371/plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java#L851-853

**Comment by ebyhr** [comment]
@ajklili Thanks for finding that. Closing as #9370
