### ISSUE TITLE
Implement QuestDB connector

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#5578]

**Comment by ebyhr** [comment]
It seems QuestDB supports PostgreSQL wire protocol. Have you already tried PostgreSQL connector? There are some unsupported features though.
https://questdb.io/docs/reference/api/postgres/

**Comment by maxstreese** [comment]
Hi @ebyhr, I am a bit late to the party but I have been trying to get things to work for a bit now and I cannot make it work with the PostreSQL connector.
