### ISSUE TITLE
Document partitioned_by, bucketed_by, bucket_count, sorted_by Hive table property

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#5581]
cc @mosabua

**Comment by findepi** [comment]
Actually, `bucketed_by`, `bucket_count` and `partitioned_by` seem to be "documented" by examples only (https://prestosql.io/docs/current/connector/hive.html#examples), so worth adding proper docs for these too.

**Comment by mosabua** [comment]
I assume there properties are Hive connector specific. Correct @findepi ? Any suggestions where specifically we should add them? Also @electrum any progress on breaking up the Hive docs more?

**Comment by findepi** [comment]
@mosabua correct

**Comment by rosewms** [comment]
PR: https://github.com/trinodb/trino/pull/10817

**Comment by mosabua** [comment]
Fixed by the linked PR
