### ISSUE TITLE
Implement TestExtract for INTERVAL types

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#5627]
See `io.prestosql.operator.scalar.timestamptz.TestExtract` for a starting point.

**Comment by RaymondWaterlooLi** [comment]
I am a new developer in this community. May I help solve this issue?

**Comment by findepi** [comment]
@RaymondWaterlooLi welcome! sure, go ahead!

please ask on the `#dev` channel on [our slack](https://prestosql.io/slack.html), should you need any directions.

**Comment by attilakreiner** [comment]
Hello Team,
I am looking for my first contribution and I was checking this task.
I see there was a PR for this some time back which was never merged and it looks like this task is currently unassigned.
I'd like to work on this, actually I have gone ahead and created a [draft PR](https://github.com/trinodb/trino/pull/22750).
I'd appreciate any feedback.
