### ISSUE TITLE
Continuous Integration for BigQuery connector

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#5664]

**Comment by findepi** [comment]
cc @davidrabinowitz

**Comment by findepi** [comment]
Not strictly related, but --
@ebyhr do we have instructions for running existing tests?
for example if i were to run `TestBigQueryIntegrationSmokeTest`, what should i do?

**Comment by ebyhr** [comment]
@findepi Currently, the test expects `bigquery.credentials-key` as credential. So, we need to set `-Dbigquery.credentials-key=xxx` to VM options on IntelliJ. 

The entire steps are:
1. Create a service account on GCP
2. Create a key for the account. It generates a json file
3. Get base64 encoded characters e.g. `cat xxx.json | base64`
4. Set the generated characters to the above `xxx`

**Comment by ebyhr** [comment]
Let's me close this issue since CI has been running on master and PR from non-forked branch thanks to @hashhar
