### ISSUE TITLE
Improve INSERT performance for JDBC based connector

### ISSUE THREAD

**Issue by walter-weinmann** [trinodb/trino#5681]
[GitHub repository db_seeder](https://github.com/KonnexionsGmbH/db_seeder/tree/wwe_2.6.0)

The task for all databases is the following: Add a total of 8011 rows to 5 different database tables. For the databases and Presto the official Docker images are used. The tests have been run exclusively in one go on a Windows 10 notebook. The performance of the Presto JDBC driver is extremely poor. Details can be found [here](https://github.com/KonnexionsGmbH/db_seeder/blob/wwe_2.6.0/resources/statistics/db_seeder_cmd_complete_company_2.6.0.tsv).

![image](https://user-images.githubusercontent.com/1956149/97082778-831bfc00-160c-11eb-88a5-51986b9a79e4.png)

**Comment by walter-weinmann** [comment]
## The problem with MySQL can be reproduced with the following steps (Windows 10):

- All scripts are also available for Ubuntu and bash.
- Similar scripts are available for Oracle, PostgreSQL and SQL Server.
- The number of rows to be inserted is limited to 500, but can easily be changed using the variable `rowMaxSize`.
- For 500 rows MySQL needs 1 second and Presto 87 seconds.
- A sample protocol can be found in the attachment.
[mysql_sample.log](https://github.com/prestosql/presto/files/5434054/mysql_sample.log)
[mysql_sample.log](https://github.com/prestosql/presto/files/5434055/mysql_sample.log)



### 1.  Clone the repository

```
git clone https://github.com/KonnexionsGmbH/db_seeder
cd db_seeder
git checkout wwe_2.6.0
```

### 2.  Compile

```
gradle copyJarToLib
```

### 3.  Create the Presto container

```
scripts\run_db_seeder_setup_presto.bat
```

### 4.  Create the MySQL container

```
scripts\run_db_seeder_setup_mysql.bat
```

### 5.  Run the MySQL tests

```
scripts\samples\presto\run_sample_mysql.bat
```

**Comment by walter-weinmann** [comment]
Unfortunately even with version 347 and the addition of the two batch operations still no improvement - interesting is the extremely high CPU consumption:

![image](https://user-images.githubusercontent.com/1956149/100414014-0ea80300-3079-11eb-844d-8c96fece010c.png)

**Comment by ebyhr** [comment]
@walter-weinmann It's expected behavior for now. Please follow this issue. https://github.com/prestosql/presto/issues/5913
