### ISSUE TITLE
Kudu connector bug: kudu insert operation timeout,bug result is success

### ISSUE THREAD

**Issue by leoChaoGlut** [trinodb/trino#5687]
presto version: 330 
kudu version: 1.10.0

When using presto-cli to insert data into kudu table, query result is FINISHED, but no data was inserted into that table.
After that, i use kudu-client to insert data into that table too, i found kudu server is unreachable, exception as below:

`Timed out: cannot complete before timeout: Batch...`

step:

1. 
 ```
presto:default> desc o3;

Column  |  Type   |                      Extra                      | Comment
----------+---------+-------------------------------------------------+---------
 order_id | bigint  | primary_key, encoding=auto, compression=default |
 test     | varchar | encoding=auto, compression=default              |
(2 rows)
Query 20201026_004152_00019_4j8ri, FINISHED, 2 nodes
Splits: 36 total, 36 done (100.00%)
0:00 [2 rows, 202B] [9 rows/s, 944B/s]
```
2.
```
presto:default> select * from o3;
 order_id | test
----------+------
        2 | b
        3 | d
        1 | a
(3 rows)

Query 20201026_004405_00020_4j8ri, FINISHED, 2 nodes
Splits: 18 total, 18 done (100.00%)
0:00 [3 rows, 6B] [13 rows/s, 27B/s]

``` 

3. attention, this query takes 28 sec
```
presto:default> insert into o3 values(4,'d');
INSERT: 1 row

Query 20201026_004431_00021_4j8ri, FINISHED, 2 nodes
Splits: 68 total, 68 done (100.00%)
0:28 [0 rows, 0B] [0 rows/s, 0B/s]

```

4. there's no (4,'d') record exists.
```
presto:default> select * from o3;
 order_id | test
----------+------
        2 | b
        3 | d
        1 | a
(3 rows)

Query 20201026_004539_00022_4j8ri, FINISHED, 2 nodes
Splits: 18 total, 18 done (100.00%)
0:00 [3 rows, 6B] [14 rows/s, 29B/s]

```

**Comment by findepi** [comment]
cc @Crossoverrr

**Comment by ebyhr** [comment]
@leoChaoGlut Are you setting `range_partitions`? Could you share `SHOW CREATE TABLE o3` result?

**Comment by leoChaoGlut** [comment]
> @leoChaoGlut Are you setting `range_partitions`? Could you share `SHOW CREATE TABLE o3` result?

```
presto:default> show create table o3;
                     Create Table
-------------------------------------------------------
 CREATE TABLE kudu.default.o3 (
    order_id bigint WITH ( primary_key = true ),
    test varchar
 )
 WITH (
    number_of_replicas = 3,
    partition_by_hash_buckets = 2,
    partition_by_hash_columns = ARRAY['order_id'],
    partition_by_range_columns = ARRAY['order_id'],
    range_partitions = '[{"lower":null,"upper":null}]'
 )
(1 row)

Query 20201026_141330_01346_4j8ri, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

```

**Comment by Crossoverrr** [comment]
I think we can abort the insert operation once there are errors reported. No matter one or more pages are failed. Will that be OK?

**Comment by grantatspothero** [comment]
I can reproduce a similar issue with deletes timing out to kudu servers but trino reporting the query was a success. 

The root cause is usage of `FlushMode.AUTO_FLUSH_BACKGROUND` which flushes operations in the background to kudu without confirming the operations were successful. Either reverting to the default of `AUTO_FLUSH_SYNC` or explicitly checking results of the flush are needed.

https://github.com/trinodb/trino/blob/master/plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduPageSink.java#L106
https://github.com/trinodb/trino/blob/master/plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduUpdatablePageSource.java#L53

I'll open PRs to fix the above.
