### ISSUE TITLE
Update guava version to 30.0

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#5718]

**Comment by kokosing** [comment]
This relates to https://github.com/prestosql/presto/pull/5712

**Comment by kokosing** [comment]
That requires:
 - changing https://github.com/airlift/airbase to guava 30
 - then changing https://github.com/airlift/airlift to update it to new airbase
 - and then updating Presto

For reference, please see:
 - https://github.com/airlift/airbase/commit/88e4e3ae3454d137549cce960793cc56af80cb7d
 - https://github.com/airlift/airlift/commit/b2d021261dca74f242ee96a431db582d3d7f71d8 (which updated guava)
 - https://github.com/prestosql/presto/commit/1166b5a7dbf0c58bac643460e7c673eba99d3e4e (which updated guava)

**Comment by RaymondWaterlooLi** [comment]
May I work on this issue?

**Comment by electrum** [comment]
@RaymondWaterlooLi please do

**Comment by wendigo** [comment]
Airbase was updated to version 106 containing guava 30.1
