### ISSUE TITLE
Extract abstract dynamic filtering tests for connectors

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#5776]
Extract `AbstractDynamicFilteringTests` class, so that connectors that implement DF could use tests from that class to validate functionality. Each connector should not implement it's own test suite.

**Comment by findepi** [comment]
> Extract AbstractDynamicFilteringTests class

Extract from ..? Where are these defined today?

Can we put those tests in `AbstractTestIntegrationSmokeTest`?
Perhaps using a feature switch like https://github.com/prestosql/presto/blob/cfadfe534d4f35859e4690eebfa5a411177b69a0/presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java#L90-L113 ?

**Comment by sopel39** [comment]
> Extract from ..? Where are these defined today?

Various flavors of these tests are implemented by different connectors. Some are required to test DF e2e integration, but not every connector needs to test everything DF related (like broadcast vs replicated joins)

**Comment by manupatteri** [comment]
Hi! Newbie to presto here.  Can I work on this ? 

I would like some guidance on some sample connectors from where we  would like to extract DynamicFiltering tests. Thanks.

**Comment by sopel39** [comment]
Currently dynamic filtering e2e integration with connectors is tested in different places:
`TestMemorySmoke` some tests there are used to test node-local dynamic filters
`TestHiveDynamicPartitionPruning` is used to test coordinator dynamic filters
`TestKuduIntegrationDynamicFilter` are kudu specific tests

Some of the tests could be made engine only tests (if TPCH had support for dynamic filters).

What I think we could do initially, we could create
```
AbstractDynamicFilteringIntegrationSmokeTest
```
that has tests cases from `TestMemorySmoke`, `TestHiveDynamicPartitionPruning`, and `TestKuduIntegrationDynamicFilter`.
`AbstractDynamicFilteringIntegrationSmotTest` should define:
```
 protected boolean supportsNodeLocalDynamicFiltering() 
 { 
     return true; 
 } 
  
 protected boolean supportsCoordinatorDynamicFiltering() 
 { 
     return true; 
 } 
```
based on that selected tests could be executed for connector.
