### ISSUE TITLE
Supported software versions for Connectors and testing

### ISSUE THREAD

**Issue by adamjshook** [trinodb/trino#5804]
The goal of this project is provide stability and confidence in a Presto connector where software versions to add additional test classes to connectors to expand the breadth of testing across multiple versions of software.  Today, with few exceptions, connectors are tested against an older software version and rely on backwards compatibility to remain current. We'd like to close the gap to ensure connectors are tested against a minimum supported version, as they are today, as well as stay up to date with software releases to ensure compatibility and get ahead of any potential issues users may see when using Presto against the latest software version.

The general goals for each connector are to:
- Establish (and document) a minimum supported version for the connector
  - Not sure if we need a formal definition for "supported", in the context here it is the minimum software version the connector is tested against
- Ensure the connector has smoke tests, distributed query tests, and product tests for the minimum supported version
- Ensure the connector has distributed query tests against the latest version

In practice, the minimum version is already established today for all connectors based on what the current tests are running against.  The latest version is always a moving target -- for now let's lay the foundation and we can determine how/when to keep track of and/or update the latest version.

The following list of connectors are those that are tested today using Docker. The existing version(s) of the unit and product tests are listed, and the proposed minimum support version and latest versions are listed along with the tasks that are required to bring this up to the above goals.  These connectors are not tested against any specific software version and omitted from the list: BigQuery, Google Sheets, Kinesis, MemSQL, Redshift, and Thrift.  Accumulo 2.0.0 introduces breaking client changes and will need a separate version. Out of scope for this effort.  Hive is intentionally left out as this connector is particularly special and well-tested.

| Presto Connector | Existing Unit Test(s) | Existing Product Test | Minimum Supported Version | Latest Version   | Tasks                                                                                                                                                        |
|------------------|-----------------------|-----------------------|---------------------------|------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Accumulo         | 1.7.4                 | None                  | 1.7.4                     | 1.10.0, 2.0.0    | <ul><li>- [ ] Add unit test class for 1.10.0</li><li>- [ ] Add product test for 1.7.4</li></ul>                                                              |
| Cassandra        | 2.2.x                 | 3.9.x                 | 2.2.x                     | 2.2.18, 3.11.9   | <ul><li>- [X] Add unit test class for 3.11.9 https://github.com/prestosql/presto/pull/5906</li></ul>                                                                                                       |
| Druid            | 0.18.0                | None                  | 0.18.0                    | 0.20.0           | <ul><li>- [X] Add unit test for 0.20.0 https://github.com/prestosql/presto/pull/5919</li><li>- [ ] Add product test for 0.18.0</li></ul>                                                                   |
| Elasticsearch    | 6.0.0, 7.0.0          | None                  | 6.0.0                     | 7.9.3            | <ul><li>- [ ] Add unit test for 6.8.13 and 7.9.3 https://github.com/prestosql/presto/pull/6142</li><li>- [ ] Add product test for 6.0.0</li></ul>                                                                     |
| Kafka            | Confluent 5.4.1       | Confluent 5.2.1       | Confluent 5.2.1           | 5.5.2            | <ul><li>- [X] Downgrade existing unit test to 5.2.1 and add unit test for 5.5.2 https://github.com/prestosql/presto/pull/6143</li></ul>                                                          |
| Kudu             | 1.10.0                | None                  | 1.10.0                    | 1.12.0           | <ul><li>- [ ] Add unit test class for 1.14.0 https://github.com/trinodb/trino/pull/7127</li><li>- [ ] Add product test for 1.10.0</li></ul>                                                             |
| MongoDB          | 3.4.0                 | None                  | 3.4.0                     | 3.6.19, 4.4.0    | <ul><li>- [X] Add unit test class for 3.6.20, 4.4.1 https://github.com/prestosql/presto/pull/5925</li><li>- [ ] Add product test for 3.4.0</li></ul>                  |
| MySQL            | 8.0.12                | 5.7                   | 5.7                       | 8.0.20           | <ul><li>- [ ] Add unit test for 5.7</li><li>- [ ] Update existing unit test to 8.0.20</li></ul>                                                              |
| Oracle           | Express Edition 11g   | None                  | Express 11g               | Express 18c      | <ul><li>- [ ] Add product test for 11g</li><li>- [ ] Add unit test for 18c</li></ul>                                                                         |
| Phoenix          | 4.14.1-HBase-1.4      | None                  | 4.14.1-HBase-1.4          | 4.14.1-HBase-1.4 | <ul><li>- [ ] Add product test for 4.14.1-HBase-1.4</li></ul>                                                                                                |
| Pinot            | 0.4.0-SNAPSHOT        | None                  | 0.4.0                     | 0.5.0            | <ul><li>- [ ] Change unit test to use official 0.4.0 release</li><li>- [ ] Add unit test for latest 0.5.0</li><li>- [ ] Add product test for 0.4.0</li></ul> |
| PostgresSQL      | 9.5                   | 9.5                   | 9.5                       | 13               | <ul><li>- [ ] Add unit test for 13</li></ul>                                                                                                                 |
| Prometheus       | 2.15.1                | None                  | 2.15.1                    | 2.19.1           | <ul><li>- [ ] Add unit test for 2.19.1</li><li>- [ ] Add product test for 2.15.1</li></ul>                                                                   |
| Redis            | 2.8.9                 | None                  | 2.8.9                     | 6.0.5            | <ul><li>- [ ] Add unit test for 6.0.5</li><li>- [ ] Add product test for 2.8.9</li></ul>                                                                     |
| SQL Server       | 14.0.3048.4           | 2017-CU13             | 14.0.3048.4               | 15.0.2000.5      | <ul><li>- [ ] Add unit test for 15.0.2000.5</li></ul>                                                                                                        |

**Comment by martint** [comment]
For Elasticsearch, there are already tests against 6.0.0 and 7.0.0

**Comment by adamjshook** [comment]
> For Elasticsearch, there are already tests against 6.0.0 and 7.0.0

Yes, I have that noted above. I figure for Elasticsearch we'd add another test class for the latest 7.9.3 in addition to 6.0.0 and 7.0.0.

**Comment by mosabua** [comment]
We should standardize on how we document this and make sure each connector doc page has that info. Currently there is no standard and its hit and miss if there is any info

**Comment by adamjshook** [comment]
> We should standardize on how we document this and make sure each connector doc page has that info. Currently there is no standard and its hit and miss if there is any info

@mosabua Agreed, let me know what you're thinking -- or if you want to draft some template for us to use then we can use it to update the docs as we go.

**Comment by mosabua** [comment]
I suggest something like

```
Requirements

* Connectivity to the 
* MongoDB version x to y 
* Atlas
* whatever else
````

**Comment by mosabua** [comment]
If we want to specify more details we can have separate lines for more info. E.g. not sure we want to mention what we test with, also in some cases the version could be `x or higher`

**Comment by mosabua** [comment]
And we should avoid any wording around "supported" versions.

**Comment by electrum** [comment]
For connectivity, I'd like to phrase this as

> The Presto coordinator and workers must be able to connect to the database on the configured port.

We already have the default port number in the example configuration.

**Comment by electrum** [comment]
For versions, how about something like

> The connector is tested against PostgreSQL 9.x and 12.x, but any intermediate or newer versions are expected to work.

This gives specifics about tested versions and sets expectations, without making a concrete statement about other versions working or not working.

**Comment by mosabua** [comment]
This is unmanaged and out of date. Closing.
