### ISSUE TITLE
Sort the functions and operators by alphabetical order

### ISSUE THREAD

**Issue by ArvinZheng** [trinodb/trino#5864]
Function and operator categories under the `Functions and Operators` section are not arranged in a specific order for better or easier to read and search, we should sort them by alphabetical order as we've done to other sections like `Connectors` and `SQL Statement Syntax`

**Comment by mosabua** [comment]
The order might be on purpose in terms of common usage vs not. Maybe we could even use multiple toctree to have a Basic and Special cases section or something like that. wdyt @electrum ?

**Comment by ArvinZheng** [comment]
closing this issue since Functions and operators are now sorted alphabetically - https://trino.io/docs/current/functions.html

**Comment by mosabua** [comment]
Thanks for closing this @ArvinZheng  ... I initiated the change but forgot about the issue here
