### ISSUE TITLE
Sql become cross join even it should't be

### ISSUE THREAD

**Issue by photogamerun** [trinodb/trino#5932]
Hello everyone

I have meet a issue  in presto 332, it report cross join althrought is shouldn't be, it's so strange, query pattern likes
with x(v) as (values 1,2,3), y(z) as (values 1,3,4) select x.v from x left join y on (x.v=y.z)

shot screen is this
![image](https://user-images.githubusercontent.com/16651123/98911177-26bb4680-24ff-11eb-8708-bca227dcc25a.png)

execute plan
is 
![image](https://user-images.githubusercontent.com/16651123/98911327-641fd400-24ff-11eb-9531-939e3edb90c9.png)

it shouldn't be cross join because the tables around join operater both 'CTE table'  they have already filtered before.

is there any one help?

**Comment by sopel39** [comment]
Could you reproduce it with simpler query? Presto often can simplify parts of query and in certain situations could insert cross join. Is the query result correct?

In your explain both branches of join don't produce any rows.

**Comment by findepi** [comment]
@photogamerun can I close this?

**Comment by photogamerun** [comment]
yes please
