### ISSUE TITLE
Use builders in PlanMatchPattern

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#5976]
Currently there is a lot of overloaded methods in `PlanMatchPattern`. At this point, it seems reasonable to use builders in that class to construct matchers for dedicated node types.

**Comment by kokosing** [comment]
How about leverage more the approach that we have in `io.prestosql.sql.planner.TestTpcdsCostBasedPlan`? That would require a way for developer express in what is interested, then string would be automatically generated. And we could simply assert if strings are equals. WDYT?

Then I would deprecate  `PlanMatchPattern`, it is hard to write a test with it and hard to maintain these tests.

**Comment by kokosing** [comment]
@kasiafi I guess you use `PlanMatchPattern` quite frequently, what are your thoughts here?

**Comment by kasiafi** [comment]
`PlanMatchPattern` in its current form allows the developer to specify certain PlanNode properties and skip other. It also allows to skip bigger parts of the plan that are not relevant for the test by using `any()` / `anyTree()`.
Using builders would make it even more flexible. I think it is a good idea to add builders for all nodes or at least for some e.g. join, semiJoin, values. 

On the other hand, using plan printer for comparison would force the developer to define the whole expected plan in detail they not necessarily care about. Or we'd need to have a "selective" printer.

I suggest that we keep the matchers and try migrate matchers construction to builders.
One thing that would be really helpful is some kind of feedback on mismatch to help locate it. It could report the mismatch that ended the longest matching path (in term of PlanMatchPatterns).

**Comment by findepi** [comment]
> One thing that would be really helpful is some kind of feedback on mismatch to help locate it. It could report the mismatch that ended the longest matching path (in term of PlanMatchPatterns).

@kasiafi  let's have a dedicated issue about that
