### ISSUE TITLE
Update code not to use QueryAssert.containsExactly and use containsExactlyInOrder instead

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6052]
https://github.com/prestosql/tempto/pull/67 deprecated `io.prestosql.tempto.assertions.QueryAssert#containsExactly` in favor of a new method: `containsExactlyInOrder`

Once tempto version is released and updated, we should update Presto codebase not to use the deprecated method.

**Comment by findepi** [comment]
> Once tempto version is released and updated

Note: it hasn't been released yet, but i can do the tempto release if anyone wants to work on this.

**Comment by somayaj** [comment]
Hi, can this be worked? thx

**Comment by findepi** [comment]
Yes, but we need to have tempto release first. I will update here when the release is done

**Comment by albericgenius** [comment]
Hey @findepi, I am interested to work on this if no one work on this, could you please assign it to me?

**Comment by albericgenius** [comment]
#8775

**Comment by albericgenius** [comment]
The commit #8775  have already merged, so close this issue.
