### ISSUE TITLE
Remove use of test priorities and dependsOnMethods from Prometheus tests

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6060]
Remove things like `@Test(dependsOnMethods ...)` or `@Test(priority ...)`

**Comment by luis-valdez** [comment]
Hi! Can I work on this?

**Comment by findepi** [comment]
@luis-valdez sure, go for it!

**Comment by m2yi** [comment]
Hi @findepi, I saw there was no progress with this issue, so I would like to take it. Also @luis-valdez if you already made some progress with it, we can work together.
btw, it's my first issue here, so pls let me know if I need to update/add something
