### ISSUE TITLE
Improve shading of org.apache.iceberg:iceberg-core

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#6092]
Currently it doesn't shade some dependencies, like `com.github.ben-manes.caffeine:caffeine:2.7.0`.
This causes conflicts when dependencies versions are updated in presto root POM (e.g: https://github.com/prestosql/presto/pull/6089).

**Comment by electrum** [comment]
`iceberg-core` is a normal artifact and doesn't shade any dependencies, which is fine. This is a more general Maven issue that you have to deal with due to how Maven does dependency resolution.
