### ISSUE TITLE
Support creation of csv data files with header

### ISSUE THREAD

**Issue by guyco33** [trinodb/trino#6132]
Currently it's possible to skip headers while reading `csv` table, but it's not possible to write data files with header.
CSV table with `skip_header_line_count=1` should write `csv` files with header.

**Comment by nandvard** [comment]
did you mean with skip_header_line_count=**0** ?

cos I have same issue. I tried creating:
```
create table test
with (format = 'TEXTFILE', skip_header_line_count=0)
as
select 1 as x
```
But the file in hdfs has no header column x, just a 1 inside it

**Comment by findepi** [comment]
Still reproducible on current master

```
trino:default> create table test
            -> with (format = 'TEXTFILE', skip_header_line_count=1)
            -> as
            -> select 1 as x;
CREATE TABLE: 1 row


trino:default> select * from test;
 x
---
(0 rows)
```

**Comment by findepi** [comment]
inserts get rejected


```
trino:default> insert into test values (42);
Query 20210622_135334_00003_ivwse failed: Inserting into Hive table with skip.header.line.count property not supported
```
