### ISSUE TITLE
Fix aggregation function alias pushdown

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#6189]
Today if the given aggregation function is pushed down into the connector both name and alias (if declared for function) are pushed down to the `applyAggregation()`. Alias should be resolved to name instead.

relates to https://github.com/trinodb/trino/issues/6736

**Comment by brandboat** [comment]
Hello, I would like to take over this issue. Could you provide a SQL statement that reproduce this issue ? Many thanks. 😃

**Comment by wendigo** [comment]
@brandboat

I.e. when  `variance()` (alias) or `var_samp()` aggregation functions (implemented in `VarianceAggregation`) are pushed down to the connector, `AggregateFunction.functionName` will contain either `variance` or `var_samp` but only canonical name should be used (`variance` as `var_samp` is an alias of `variance`)

**Comment by brandboat** [comment]
Thanks for your comments ! I will try to fix it.  🙇
