### ISSUE TITLE
Include full stacktraces from LogTestDurationListener test hang monitor

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6202]
See https://github.com/prestosql/presto/runs/1497472672

- tests apparently hanged
- one test thread is here:

```
2020-12-04T07:53:43.1535741Z "pool-2-thread-2" prio=5 Id=16 BLOCKED on org.testng.TestClass@2a78dd6a owned by "pool-2-thread-1" Id=15
2020-12-04T07:53:43.1537790Z 	at app//org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:158)
2020-12-04T07:53:43.1539747Z 	-  blocked on org.testng.TestClass@2a78dd6a
2020-12-04T07:53:43.1540972Z 	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
2020-12-04T07:53:43.1542880Z 	at java.base@11.0.9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-12-04T07:53:43.1545474Z 	at java.base@11.0.9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-12-04T07:53:43.1547540Z 	at java.base@11.0.9/java.lang.Thread.run(Thread.java:834)
2020-12-04T07:53:43.1548037Z 
2020-12-04T07:53:43.1548486Z 	Number of locked synchronizers = 1
2020-12-04T07:53:43.1549747Z 	- java.util.concurrent.ThreadPoolExecutor$Worker@7cedfa63
```

- the information who owns `TestClass@2a78dd6a` is not present, probably because every stacktrace is limited to 8 frames.

see full thread dump -- https://github.com/prestosql/presto/runs/1497472672  or  https://gist.github.com/findepi/2f87bad4047976bee6af9223f5d3ff6c

**Comment by findepi** [comment]
The relevant code is here:
https://github.com/prestosql/presto/blob/e7c36e313809310f94ee94491937a663aa037365/presto-testng-services/src/main/java/io/prestosql/testng/services/LogTestDurationListener.java#L149

**Comment by CoachLuck** [comment]
@findepi A solution could be to copy the existing [ThreadInfo.toString() method](http://www.howsoftworks.net/j/ThreadInfo) since all it needs is to override the default Max Frame limit.

Taking this method, we can suit it to our needs and call it some new method for example `getFullStackTrace`
The final method would look something like this:

```Java
private static String getFullStackTrace(ThreadInfo threadInfo) {
        StringBuilder sb = new StringBuilder("\"" + threadInfo.getThreadName() + "\"" +
                " Id=" + threadInfo.getThreadId() + " " +
                threadInfo.getThreadState());
        if (threadInfo.getLockName() != null) {
            sb.append(" on " + threadInfo.getLockName());
        }
        if (threadInfo.getLockOwnerName() != null) {
            sb.append(" owned by \"" + threadInfo.getLockOwnerName() +
                    "\" Id=" + threadInfo.getLockOwnerId());
        }
        if (threadInfo.isSuspended()) {
            sb.append(" (suspended)");
        }
        if (threadInfo.isInNative()) {
            sb.append(" (in native)");
        }
        sb.append('\n');

        StackTraceElement[] stackTrace = threadInfo.getStackTrace();
        int i = 0;
        final int MAX_FRAMES = 50;
        for (; i < stackTrace.length & i < MAX_FRAMES; i++) {
            StackTraceElement ste = stackTrace[i];
            sb.append("\tat " + ste.toString());
            sb.append('\n');
            if (i == 0 && threadInfo.getLockInfo() != null) {
                Thread.State ts = threadInfo.getThreadState();
                switch (ts) {
                    case BLOCKED:
                        sb.append("\t-  blocked on " + threadInfo.getLockInfo());
                        sb.append('\n');
                        break;
                    case WAITING:
                    case TIMED_WAITING:
                        sb.append("\t-  waiting on " + threadInfo.getLockInfo());
                        sb.append('\n');
                        break;
                    default:
                }
            }

            for (MonitorInfo mi : threadInfo.getLockedMonitors()) {
                if (mi.getLockedStackDepth() == i) {
                    sb.append("\t-  locked " + mi);
                    sb.append('\n');
                }
            }
        }

        if (i < stackTrace.length) {
            sb.append("\t...");
            sb.append('\n');
        }

        LockInfo[] locks = threadInfo.getLockedSynchronizers();
        if (locks.length > 0) {
            sb.append("\n\tNumber of locked synchronizers = " + locks.length);
            sb.append('\n');
            for (LockInfo li : locks) {
                sb.append("\t- " + li);
                sb.append('\n');
            }
        }
        sb.append('\n');
        return sb.toString();
    }

```

* This allows us to continue reading up to 50 frames rather than the default. This could easily be configured by changing the value of **MAX_FRAMES** to a higher or lower number, or be accessible by making this a public statically available constant within the **LogTestDurationListener** class itself.

**Comment by findepi** [comment]
> A solution could be to copy the existing [ThreadInfo.toString() method](http://www.howsoftworks.net/j/ThreadInfo) since all it needs is to override the default Max Frame limit.

That would be good from technical perspective, but unfortunately it is not possible due to licensing reason.
The JDK is distributed under GPL (with classpath exception) license, and so the code from JDK cannot be copied into Apache License-licensed project.

We want to have the exact same behavior though, so the code needs to be written anew, taking at most inspiration only from the JDK code.

**Comment by CoachLuck** [comment]
> We want to have the exact same behavior though, so the code needs to be written anew, taking at most inspiration only from the JDK code.

Sounds like this is something I could work on implementing. Mind if I give it a shot?

A couple of questions for moving forward:
* Do we need to even set a limit of max lines? As if we want **all** of the information we might as well let it work to through every single stack trace element.
* Should we display information regarding the number of blocks/waits that occur? (Using getBlockedCount() & getWaitedCount(), etc) as the current toString() method does not display this information. 
* Should we display how long the blocks/waits take?

**Comment by findepi** [comment]
> Mind if I give it a shot?

go for it, thanks!

> Do we need to even set a limit of max lines?

no need for a limit

> Should we display information regarding the number of blocks/waits that occur? (Using getBlockedCount() & getWaitedCount(), etc)

My personal opinion is that we do not need this. 

> Should we display how long the blocks/waits take?

If a thread is currently blocked, having information how long it is blocked could be useful

You didn't ask for this, but to be sure we're on the same page, the pretty important part of the output is

- owned locks  ("locked" & "locked synchronizers")
- locks being attempted

as the most common thing to look for is potential deadlock or livelock (as eg it was recently the case around https://github.com/square/okio/pull/818)

**Comment by CoachLuck** [comment]
@findepi I went with creating a new class called `StackTraceUtil` that has a singular public method to retrieve full stack trace information as this could be used anywhere that `ThreadInfo` would like to be inspected. This goes a little more in-depth than the normal toString() function on `ThreadInfo`, by adding the following information:
* DAEMON status
* Time spent on blocked/waiting threads
* Locked Synchronizer class name/hash code
* Unlimited stack trace frames (rather than the default of 8)

As well as using an easier to read format:
* Header section showing Thread ID, State, Suspension Status, In Native, Is Daemon, and any lock that was incurred with the associated owner tagged along with it, only if they are accessible.
* Sections with headers for ThreadState information, locked monitors per stack trace element.
* Locked Synchronizers section displaying all locked synchronizers

See the mentioned PR here #6236
