### ISSUE TITLE
Presto UI does not show details when I configure SSL and Ranger

### ISSUE THREAD

**Issue by wangfeigithub** [trinodb/trino#6217]
Hello, when I configured SSL and Ranger, the UI could not see the SQL details of someone else running

**Comment by wangfeigithub** [comment]
![image](https://user-images.githubusercontent.com/29723968/101313537-4c830380-3891-11eb-959b-900086773c45.png)
![image](https://user-images.githubusercontent.com/29723968/101313554-53aa1180-3891-11eb-975a-b42e5f7d3453.png)
How do I configure all access rights for my primary account?

**Comment by kokosing** [comment]
What kind of Presto Ranger integration are you using?

**Comment by wangfeigithub** [comment]
hi ,apache ranger2.1  presto338.

**Comment by wangfeigithub** [comment]
> What kind of Presto Ranger integration are you using?

How do I configure a super administrator to see all query Details?

**Comment by kokosing** [comment]
But what Presto plugin for Ranger are you using?

**Comment by wangfeigithub** [comment]
apache ranger presto2.1  Presto plugin

**Comment by kokosing** [comment]
I suspect you wanted to open this issue here: https://issues.apache.org/jira/browse/RANGER We don't control this plugin and so we are unable to help you here. If you open an issue there, please link it back here for future reference for others.

>  when I configured SSL and Ranger

Just a shoot. Does it work without SSL?

**Comment by changge458** [comment]
you should set prestouser * access and give impersonate permissions
![image](https://user-images.githubusercontent.com/11388220/105959085-6c2af100-60b6-11eb-98de-c9b6f3cf9c5a.png)

**Comment by findepi** [comment]
Trino has no Ranger plugin yet, so let me close this issue as not pertaining Trino
