### ISSUE TITLE
Hive requests for ORC data contain a race condition on file size

### ISSUE THREAD

**Issue by ddrinka** [trinodb/trino#626]
I'm querying ORC data from a file in S3 that is overwritten throughout the day.  S3 guarantees atomic replace, so a request for a file's data will always return either the old copy or the new copy.  However, no guarantee is made that a range request for one block of data at the start of a file, and another block at the end of the file, will both return data from the same copy.

With these guarantees in mind, Presto should be able to work with files that are changing in S3, as long as the entire file can be read in a single request.  `orc_tiny_stripe_threshold` determines the file size for which this should hold.

However, a race condition is encountered where a file listing is requested, and the file size returned in the listing is used as the assumed length of the files when they're requested.

```
GET /?prefix=my/s3/prefix/&delimiter=/&encoding-type=url HTTP/1.1
<?xml>
<Contents>
  <Key>my/s3/prefix/data</Key>
  <Size>52279</Size>
</Contents>
```

```
GET /my/s3/prefix/data HTTP/1.1
RANGE: bytes=0-52278

HTTP/1.1 206 Partial Content
Content-Range: bytes 0-52278/52299
```

#### I can see three approaches to avoiding this race condition:
- If a file's size from a listing is returned as less than `orc_tiny_stripe_threshold`, don't perform a range request on the file's data at all. Request the entire file.
- If a range request comes back with a longer length available than anticipated, send a new request for the new complete length.
- Provide a configuration variable that disables range requests completely for a session.

Files that change like the one I'm describing are useful for state-keeping or other data-grooming tasks.  While these files could be stored in JSON rather than ORC, ORC provides self-documentation benefits beyond just query efficiency.

**Comment by oneonestar** [comment]
Coordinator separate a file into splits(chunks to read) and allocate the splits to different workers. It is not safe for a worker to extend the range to read without coordination, because that could potentially overlap with other split.

I think you may try:
* Kafka Connector
* Write into a new file instead of append to existing file

**Comment by findepi** [comment]
> Write into a new file instead of append to existing file

To be precise, you cannot atomically create a new file and delete an existing file, so the new file would need to be in a different location (create new file → change table location → delete the old file).

Another workaround given by @electrum on Slack was to use text format for this particular table (assuming the file size is below the split size).
This is probably the simplest approach. Since the data in question is very small (here it is below megabyte), there is no performance penalty incurred from not using columnar format.

**Comment by ddrinka** [comment]
I totally agree with the responses here.  This is an uncommon use case and there are a number of viable workarounds.  However, I think the fix could be trivial as well, and would remove the dependence on the race condition, for at least some scenarios.

Presto already knows that a file is small and to handle that scenario specially.  Presto also knows if it will be requesting the entire content length.  This race condition would be eliminated for small files if the following check were added:
```
if(request_end_position - request_start_position < orc_tiny_stripe_threshold
    && request_end_position - request_start_position == content_length)
  dontSendRangeRequest = true;
```

The risk of this check is that a small file is replaced with a huge file, right between the coordinator collecting the file size and the worker making the range-less request.  This is, seemingly, an unsupported operation anyway, as the expectation is that the query would fail.  With this change, the query would likely succeed, but would have transferred the entire huge file to a single worker rather than splitting it.  From my perspective, if that's a serious concern, that's the reason to not behave as described above.  If that's not a serious concern, adding this check would allow the race condition to be avoided in these narrow circumstances.

**Comment by findepi** [comment]
@ddrinka I understand your case is rather easy to fix.
However, this requires special casing and is not "generally useful" (we still do not support in-place replacements of ORC files).
My personal preference is to not introduce a change here. Others may have different opinion though.

**Comment by ddrinka** [comment]
@findepi yep, and I totally agree, it's not generally useful.  I guess to me it's not new special casing, it's using the existing special casing for small files.  No new configuration required.  And it's a partial, though not complete, fix to a (debatable terminology) bug.

No offense for a won't fix close.  I just wanted to document the conversation here rather than on Slack.

**Comment by oneonestar** [comment]
S3FileSystem in wrapped inside the Hadoop FileSystem. On top there are ORC file reader, CachingOrcDataSource and PageSource layer. All these classes involved the fileSize and offset calculation. Implement this "fix" will break a lot of the abstractions and make the logic very difficult to understand. I'd prefer a won't fix here.
