### ISSUE TITLE
 The partition information does not exist, and the error prompt table does not exist, which is unreasonable

### ISSUE THREAD

**Issue by allendang001** [trinodb/trino#6362]
This can lead to misleading troubleshooting, and actually the table is exist
Optional<List<String>> partitionNameResult = delegate.getPartitionNamesByFilter(identity, databaseName, tableName, columnNames, partitionKeysFilter);
                if (partitionNameResult.isEmpty()) {
                    throw new PrestoException(TRANSACTION_CONFLICT, format("Table '%s.%s' was dropped by another transaction", databaseName, tableName));
                }

**Comment by hashhar** [comment]
Unable to infer the steps to reproduce this.

If you can still reproduce this on current versions please feel free to reopen.
