### ISSUE TITLE
Convert TestMySqlTypeMapping to use SqlDataTypeTest

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6392]
Migrate the tests from `DataTypeTest` to `SqlDataTypeTest`.

- `DataTypeTestToSqlDataTypeTestConverter` (being added in https://github.com/prestosql/presto/pull/6391) may aid the migration.
- ideally the work should be done incrementally (in small steps) to facilitate the review process

See https://github.com/prestosql/presto/pull/6391 for example approach.

**Comment by dratler** [comment]
Hi @findepi ,
is this still open for the grab ?

**Comment by findepi** [comment]
@dratler absolutely!
However, we're in the process of reorganizing the codebase, so I'd suggest waiting about a week before starting work on this, to avoid conflicts.
You can read more at https://trino.io/blog/2020/12/27/announcing-trino.html

**Comment by findepi** [comment]
Hi @dratler,
if you're still interested -- this is still up for grabs and the repo reorganization has been completed.

**Comment by OmkarNeogi** [comment]
Hi @findepi I would like to work on this if it is available.

**Comment by findepi** [comment]
@dratler are you already working on this?

**Comment by 90lantran** [comment]
@findepi I can try to work on it if no one actively work on it

**Comment by findepi** [comment]
@90lantran awesome!
per your request, i assign you in #6395. Let's do one at a time. Please let me know which one you would prefer first.
