### ISSUE TITLE
Convert TestMemSqlTypeMapping to use SqlDataTypeTest

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6393]
Migrate the tests from `DataTypeTest` to `SqlDataTypeTest`.

- `DataTypeTestToSqlDataTypeTestConverter` (being added in https://github.com/prestosql/presto/pull/6391) may aid the migration.
- ideally the work should be done incrementally (in small steps) to facilitate the review process
- see also https://github.com/prestosql/presto/issues/6392, as MySQL and MemSQL tests are similar

See https://github.com/prestosql/presto/pull/6391 for example approach.

**Comment by yuokada** [comment]
The title of the pull request is same as https://github.com/prestosql/presto/issues/6392.
duplicate?

**Comment by albericgenius** [comment]
@findepi Could I take over this issue as my first task?

**Comment by findepi** [comment]
@albericgenius this is already being worked on by @Atema in https://github.com/trinodb/trino/pull/7202. It seems the primary obstacle was the CLA cc @martint 

cc @hashhar

**Comment by albericgenius** [comment]
got you and thanks
