### ISSUE TITLE
Convert TestOracleTypeMapping to use SqlDataTypeTest

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6394]
Migrate the tests from `DataTypeTest` to `SqlDataTypeTest`.

- `DataTypeTestToSqlDataTypeTestConverter` (being added in https://github.com/prestosql/presto/pull/6391) may aid the migration.
- ideally the work should be done incrementally (in small steps) to facilitate the review process

See https://github.com/prestosql/presto/pull/6391 for example approach.

**Comment by brandboat** [comment]
@findepi Could I take over this issue ?

**Comment by findepi** [comment]
@brandboat sure, go for it!

if you have any questions, don't hesitate to reach out! 
@hashhar or myself can help

**Comment by brandboat** [comment]
After #7261 and #6680 merged, the remaining type tests need to be converted to SqlDataTypeTest are as follows:
- testLegacyDateMapping
- testLegacyDateReadMapping
- testDateMapping
- testDateReadMapping
- testTimestamp
- testTimestampWithTimeZone

**Comment by hashhar** [comment]
Addressed by merging https://github.com/trinodb/trino/pull/7552.

Some specific tests remain which are tracked by https://github.com/trinodb/trino/issues/7739
