### ISSUE TITLE
Convert TestPhoenixTypeMapping to use SqlDataTypeTest

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6395]
Migrate the tests from `DataTypeTest` to `SqlDataTypeTest`.

- `DataTypeTestToSqlDataTypeTestConverter` (being added in https://github.com/prestosql/presto/pull/6391) may aid the migration.
- ideally the work should be done incrementally (in small steps) to facilitate the review process

See https://github.com/prestosql/presto/pull/6391 for example approach.

**Comment by 90lantran** [comment]
@findepi if this one is available, I can take a look on it. FYI: this is my first issue.

**Comment by findepi** [comment]
@90lantran awesome!

it is available, will assign to you.
note that there are two `TestPhoenixTypeMapping` classes since we have `phoenix` and `phoenix5` modules.
you can do both at the same time, should be identical.

should you need any advice, @hashhar is the best person to ask.

**Comment by 90lantran** [comment]
@findepi  I will work on this one first, please ignore my request for the other issue
