### ISSUE TITLE
Efficient Adaptive Partial Aggregations

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#64]
Extracted from: https://github.com/prestodb/presto/issues/10305 (see discussion there)

## Problems
1) High cardinality group by can result in one row per partial which can make query significantly more expensive than no partial at all.
2) No partial for distinct aggregations can cause slow queries since all distinct calculations happen on a few machines.
3) Flush of partial is all or nothing which removes the benefit of skewed groups (high row reduction for big groups).

## Proposal
Change partial aggregation to detect ineffective partial aggregations and switch to a mode where the raw input is output instead of intermediate results.  In addition, the partial should be able to make this decision on a per-group basis so groups with a high row count can still get the benefits of partial aggregations.  

For distinct aggregations in groups that performing partial aggregation, the operator would determine if a row is distinct for any of the aggregates, and if so, the raw input is output, along with flag columns that mark which aggregates the row is distinct for.

The net result is the aggregate may output rows for three distinct cases:
1) intermediate results for an enabled group
2) raw input for a disabled group
3) distinct raw input for distinct aggregates (in an enabled group)

The output descriptor for a partial aggregation would look something like this:
1) `row_type` either intermediate, raw, distinct partial 
2) intermediates outputs for non-distinct aggregations. `null` if row type is not intermediate
3) raw input columns. `null` if `row_type` is intermediate; for distinct `row_type` only inputs to distinct aggregations may be present.
4) distinct flags; if set the input row should be processed in the related aggregation. `null` if `row_type` is not distinct

**Comment by frankobe** [comment]
Any taker for this issue? Discussion on https://github.com/prestodb/presto/issues/10305 mentions there are some initial implementation with good performance gain however the branch https://github.com/starburstdata/presto/tree/ks/dynamic_partial_aggregation_simple is unavailable

**Comment by sopel39** [comment]
I don't have cycles to work on this at this moment unfortunately.

**Comment by frankobe** [comment]
@sopel39 I am happy to implement this however wonder any benchmark is available

**Comment by sopel39** [comment]
@frankobe I think you can use `BenchmarkHashAndStreamingAggregationOperators` as a base for benchmarks.

**Comment by sopel39** [comment]
https://github.com/trinodb/trino/pull/11011 seems like good enough implementations of this
