### ISSUE TITLE
Array with double null stored as array with 0 in Phoenix

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6421]
See TODO in the code for more details.

**Comment by findepi** [comment]
@phd3 observed this applies to other array types, eg `array(BIGINT)` as well

**Comment by ebyhr** [comment]
It looks Phoenix driver's bug. `getJdbcObjectArray` passes array with null, but  `PhoenixConnection#createArrayOf` rewrites the element with 0. 
https://github.com/trinodb/trino/blob/98b794a9f7228619f4f8feb2c9bbb4d75d70b8f5/plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java#L769-L775

cc: @vincentpoon @lhofhansl
