### ISSUE TITLE
Document assume canonical hive partition key

### ISSUE THREAD

**Issue by allendang001** [trinodb/trino#6437]
When the partition key of the partition table is an integer type, no data can be found and an exception is thrown like follow：
`PrestoException：Table ‘aa.bb' was dropped by another transaction`
But in fact the table exists, and the partition also exists.
By reading the code, it is found that there is a parameter in the configuration of thrift metastore.
In order to remove this obstacle for future users, we hereby use documents to record.

**Comment by hashhar** [comment]
`hive.metastore.thrift.assume-canonical-partition-keys` is now documented at https://trino.io/docs/current/connector/metastores.html#thrift-metastore-configuration-properties
