### ISSUE TITLE
upgrade Iceberg to 0.10

### ISSUE THREAD

**Issue by bowenli86** [trinodb/trino#6443]
upgrade Iceberg to 0.10 from 0.9

**Comment by bowenli86** [comment]
Hi I wonder why Iceberg dependency is not upgraded to 0.10? is there any blockers, or just the devs don't have time yet?

**Comment by electrum** [comment]
The main question is why upgrade? Since the Iceberg library is primarily used to read and write the Iceberg metadata files, it is not clear there would be any user visible benefit from upgrading. If there is a benefit, or it fixes a bug, it’s likely someone would have upgraded it already.

**Comment by lxynov** [comment]
@bowenli86 We haven't had a real need to upgrade to Iceberg 0.10 yet as @electrum pointed out. But FYI Iceberg 0.10 will be needed to fix a test failure in https://github.com/trinodb/trino/pull/4776. I will include the version upgrade in that PR when rebasing it to Trino master.

**Comment by jirassimok** [comment]
[We're on 0.11 now](https://github.com/trinodb/trino/blob/39b0af8655ac39e24b35d724e88a559e18bdc59e/plugin/trino-iceberg/pom.xml#L18).
