### ISSUE TITLE
Avoid loading table properties during query analysis

### ISSUE THREAD

**Issue by Praveen2112** [trinodb/trino#6477]
Here
https://github.com/trinodb/trino/blob/d2484fbe800747321480d909f369eca5e43e81e7/presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java#L1231

We would be building the `ConnectorMetadata` which requires table properties to be populated which is unnecessary. Can we have a lite version of `ConnectorMetadata` like object which captures only basic table details (tableName, columnName)

**Comment by Praveen2112** [comment]
These are the possible solutions I could enumerate. 

1. To introduce a new API in ConnectorMetadata to fetch only the column details i.e List<ColumnMetadata> - But this doesn't fully solve this problem (It fixes for SELECT) but for INSERTS we still need to fetch the ConnectorTableMetadata

2. Modify ConnectorMetadata to have Supplier<Map<String, Object>> - Maybe we could have a new constructor and handle it (So we typically load the properties on demand)

3. Implement a LazyMap which is loaded only when we are going to use it.


For 2 && 3 we might have to make sure that connector's classloader is being used

**Comment by kokosing** [comment]
I like 1 the most. I would prefer to introduce a new dedicated method targeted semantic analyzer so it could fit needs of SELECT and INSERT.

>  INSERTS we still need to fetch the ConnectorTableMetadata

Why?

**Comment by Praveen2112** [comment]
`ConnectorMetadata#getStatisticsCollectionMetadataForWrite` is invoked during `INSERT` and we need to pass `ConnectorMetadata` as an argument

**Comment by kokosing** [comment]
Two another idesas:
 - we could move out table and column properties of out Metadata classes and have dedicated SPI method for them.
 - we could use `TableHandle` in `getStatisticsCollectionMetadataForWrite`. Hive connector is able to find table properties on his own.

**Comment by Praveen2112** [comment]
> we could move out table and column properties of out Metadata classes and have dedicated SPI method for them.

Ideally Metadata classes should have these properties.

>we could use TableHandle in getStatisticsCollectionMetadataForWrite. Hive connector is able to find table properties on his own.

This looks good to me... I guess only HiveConnector uses this API for now

**Comment by findepi** [comment]
The INSERT case is by far less important than the SELECT case.
If solving the problem for INSERT would require new API methods, I wouldn't be sure this is a fair trade off.

**Comment by Praveen2112** [comment]
What if we could modify the existing API for stats collection during writes/analyze to use ConnectorTableHandle instead of ConnectorTableMetadata ?

**Comment by Praveen2112** [comment]
It might affect when we create a new tables like we don't have a table handle and we can use only ConnectorTableMetadata. 
> we could move out table and column properties of out Metadata classes and have dedicated SPI method for them.

We can have this but it might work only for `SELECT`

**Comment by findepi** [comment]
> We can have this but it might work only for `SELECT`

I am not as much concerned about such limitation. Do we have an alternative proposal which would work for SELECT and INSERT as well?

**Comment by findepi** [comment]
@kokosing should this be closed?

**Comment by kokosing** [comment]
Fixed with https://github.com/trinodb/trino/pull/6975
