### ISSUE TITLE
presto how to get the comment of hive table and column？

### ISSUE THREAD

**Issue by melin** [trinodb/trino#6492]
presto how to get the comment of hive tables and columns? Application needs to display comment information

**Comment by ebyhr** [comment]
You can get those information by:
* Table: system.metadata.table_comments
* Column: $catalog.information_schema.columns (hidden `column` comment)

If you are using JDBC driver, column comments will be exposed via DatabaseMetaData REMARKS.

By the way, I would invite you to join the community Slack for questions https://trino.io/slack.html
Also, we renamed to Trino from Presto recently https://trino.io/blog/2020/12/27/announcing-trino.html

**Comment by melin** [comment]
system.metadata.table_comments table query is very slow and has been
executing

[image: image.png]

Yuya Ebihara <notifications@github.com> 于2021年1月4日周一 上午11:20写道：

**Comment by ebyhr** [comment]
@melin I can't see the attached image `[image: image.png]`. Could you past it again?

**Comment by melin** [comment]
[image: image.png]

Yuya Ebihara <notifications@github.com> 于2021年1月6日周三 下午4:05写道：
