### ISSUE TITLE
Analyze all sub-partitions for a higher-level partition

### ISSUE THREAD

**Issue by nandvard** [trinodb/trino#6493]
If a HIVE table is partitioned by DAY & HOUR (in that order), I would like to ANALYZE (compute statistics) for an entire day (say Dec 8) by doing:
`ANALYZE HIVE.DATA.EVENTS WITH (partitions = ARRAY[ARRAY['2020-12-08'])`

instead of having to specify each of the 24 hours within that day like so:
`ANALYZE HIVE.DATA.EVENTS WITH (partitions = ARRAY[ARRAY['2020-12-08','00'], ARRAY['2020-12-08','01'], ARRAY['2020-12-08','02'],...)`

i.e. I want to be able to specify only the higher-level partition, and maybe an optional keyword like ALL, to analyze all sub partitions within that partitions

**Comment by ebyhr** [comment]
This issue is similar to (or duplicate of) #962

**Comment by nandvard** [comment]
closing, dupe of #962
