### ISSUE TITLE
Presto don't support select item’s alias Chinese?

### ISSUE THREAD

**Issue by ghfengg** [trinodb/trino#6496]
version:0.244.1

![image](https://user-images.githubusercontent.com/3355129/103529519-c8885f80-4ec0-11eb-83a7-5595bdc65676.png)

**Comment by ghfengg** [comment]
xxx

**Comment by ebyhr** [comment]
Please surround by double-quotation as
```
trino> select 1 as "从";
 从
----
  1
```

By the way, you can ask questions in the community Slack https://trino.io/slack.html.

**Comment by ghfengg** [comment]
> Please surround by double-quotation as
> 
> ```
> trino> select 1 as "从";
>  从
> ----
>   1
> ```
> 
> By the way, you can ask questions in the community Slack https://trino.io/slack.html.

thanks~
