### ISSUE TITLE
Flakey CI tests

### ISSUE THREAD

**Issue by erichwang** [trinodb/trino#6506]
In PR #6472, we saw that some of the CI tests were failing with the following error in the error-prone-checks:

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project presto-spi: Resolution of annotationProcessorPath dependencies failed: Unable to get dependency information for com.google.protobuf:protobuf-java:jar:3.4.0: Failed to retrieve POM for com.google.protobuf:protobuf-java:jar:3.4.0: Could not transfer artifact com.google.protobuf:protobuf-java:pom:3.4.0 from/to central (https://repo.maven.apache.org/maven2): /home/runner/.m2/repository/com/google/protobuf/protobuf-java/3.4.0/protobuf-java-3.4.0.pom.part (No such file or directory)

This is unrelated to the PR and seems like something that could be retried if it is an intermittent connectivity issue.

**Comment by findepi** [comment]
is it different from https://github.com/trinodb/trino/issues/5816?

**Comment by erichwang** [comment]
Yea, looks similar to #5816
