### ISSUE TITLE
Support for WINDOW clause

### ISSUE THREAD

**Issue by martint** [trinodb/trino#651]
The syntax and semantics are described in section 7.15 of the SQL specification.

```
<table expression> ::=
  <from clause>
      [ <where clause> ]
      [ <group by clause> ]
      [ <having clause> ]
      [ <window clause> ]
```

```
<window clause> ::=
  WINDOW <window definition list>
<window definition list> ::=
  <window definition> [ { <comma> <window definition> }... ]
<window definition> ::=
  <new window name> AS <window specification>
<new window name> ::=
  <window name>
<window specification> ::=
  <left paren> <window specification details> <right paren>
<window specification details> ::=
  [ <existing window name> ]
      [ <window partition clause> ]
      [ <window order clause> ]
      [ <window frame clause> ]
<existing window name> ::=
  <window name>
```

```
<window function> ::=
  <window function type> OVER <window name or specification>
<window name or specification> ::=
    <window name>
  | <in-line window specification>
<in-line window specification> ::=
  <window specification>
```

This feature allows declaring a named window specification, which can then be used when calling window functions. It is useful to eliminate duplication when multiple window function invocations use the same window specification. The window specification can refer to other window specifications, allowing partial reuse.

Implementing this feature will require changing the parser, analyzer, and planner, but will not require any execution engine changes.

**Comment by JamesRTaylor** [comment]
@Praveen2112 - is this still on your radar? FWIW, we'd love to see it implemented.

**Comment by Praveen2112** [comment]
@JamesRTaylor Yes !! I'm working on it !! Parser part is completed , need to change the analyzer and planner for it

**Comment by JamesRTaylor** [comment]
Any update on this issue, @Praveen2112?
