### ISSUE TITLE
Presto on yarn Is achieved through the slider, but The Slider podling retired on 2018-05-24, Excuse me, is there an alternative??

### ISSUE THREAD

**Issue by tanggaomeng3069** [trinodb/trino#6532]
The currently used Hadoop version is 3.1, thank you

**Comment by tanggaomeng3069** [comment]
The currently used Hadoop version is 3.1, thank you

**Comment by ebyhr** [comment]
Could you file an issue to https://github.com/trinodb/trino-yarn instead?

**Comment by findepi** [comment]
https://github.com/trinodb/trino-yarn is not actively maintained and the last real change was in 2018.
I strongly recommend you do not use it. Please join our slack https://trino.io/slack.html to learn how other community members solve such problems.

**Comment by tanggaomeng3069** [comment]
> 您可以改为将问题提交到https://github.com/trinodb/trino-yarn吗？

ok，thanks

**Comment by tanggaomeng3069** [comment]
> https://github.com/trinodb/trino-yarn is not actively maintained and the last real change was in 2018.
> I strongly recommend you do not use it. Please join our slack https://trino.io/slack.html to learn how other community members solve such problems.

Thank you for answering my question and giving directions, thank you very much
