### ISSUE TITLE
Iceberg table created by spark is not visible by presto when using "show tables" under specified schema of iceberg catalog

### ISSUE THREAD

**Issue by Xiangakun** [trinodb/trino#6542]
Iceberg table created by spark (with spark sql 3.1) is not visible by presto (tested with presto version 348) when using "show tables" under specified schema of iceberg catalog, however, you can still use `select * from ` the specified spark iceberg table to get the correct results with presto. After checked the metadata of the iceberg table created by spark, the  TBLPROPERTIES of table_type shows : 'table_type'='ICEBERG' , the value `ICEBERG` is all upper case，instead of lower case like `iceberg`. 
Checked presto code, the called stack is as follows:
    IcebergMetadata.listTables --> metastore.getTablesWithParameter(schema, TABLE_TYPE_PROP, 
    ICEBERG_TABLE_TYPE_VALUE) -->  ThriftHiveMetastore.getTablesWithParameter --> 
    doGetTablesWithParameter(databaseName, parameterKey, parameterValue)
the ICEBERG_TABLE_TYPE_VALUE is `iceberg`, I think it should be the reason why the unexpected result occurs.
Anyway, I am not sure it should be the bug of trino, or the bug of iceberg spark!

**Comment by lxynov** [comment]
Hi @Xiangakun, thanks for reporting this! This is actually a known issue. You can refer https://github.com/trinodb/trino/issues/1592 for discussion on this. Feel free to create a PR to fix this if you're interested.

**Comment by findepi** [comment]
closing in favor of https://github.com/trinodb/trino/issues/1592
