### ISSUE TITLE
Error running command: Authentication failed: Unauthorized

### ISSUE THREAD

**Issue by dyhyao6** [trinodb/trino#6624]
配置kerberos和https，客户端出现这样的错误。
<img width="679" alt="企业微信截图_20210118104543" src="https://user-images.githubusercontent.com/49445844/104866877-8f4cf680-597a-11eb-827b-d3cca15c37d8.png">
日志信息：
<img width="829" alt="企业微信截图_20210118104856" src="https://user-images.githubusercontent.com/49445844/104866991-c9b69380-597a-11eb-9d2e-16fb5068505b.png">
我的配置：
<img width="490" alt="企业微信截图_20210118105001" src="https://user-images.githubusercontent.com/49445844/104867053-eeab0680-597a-11eb-8ff3-3edd9354ea32.png">
请问哪里出现问题了？ @joshk @electrum @jvanzyl @oggy @andykram

**Comment by hashhar** [comment]
Kerberos debug logs from server would be useful.

Closing since this is very old and not actionable. Please reopen if still relevant or reply with what the solution was for future readers.
