### ISSUE TITLE
coalesce function causes wrong results

### ISSUE THREAD

**Issue by enoughwell** [trinodb/trino#6649]
presto version: 350
description:
When I left join the t1 table and the t2 table, if the fields of the t2 table are not related, I will use the coalesce function to give the value 0, and then add and subtract the value of the t1 field, but I always get an error in doing so. The result. When I use the coalesce function to give the default value of the null value of the t2 table, and then use the cast function to act, the result becomes better. What is the reason? The example is as follows:
select
t1.money+cast(coalesce(t1.money,0) as decimal(16,2))
from t1
left join t2 on t1.id=t2.id
;

**Comment by findepi** [comment]
I don't think `coalesce` could be wrong (as the title suggests). I would assume there is some other problem.
you can reach out for help on the `#troubleshooting` channel  on [our slack](https://prestosql.io/slack.html)

i'd suggest closing the issue here and moving the discussion over there
