### ISSUE TITLE
Make Iceberg maxOpenWriters configurable

### ISSUE THREAD

**Issue by guyco33** [trinodb/trino#6650]
Creating more than 100 partitions fails with the following error:
```
[84148226] Query failed (#20210118_061400_09812_m328m): Exceeded limit of 100 open writers for partitions
```

https://github.com/trinodb/trino/blob/690d9663e76efdb5bbdc10beb8aa461cf86cbdc6/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java#L85

Possible solution is to take advantage of `hive.max-partitions-per-writers` configuration that can be set also in iceberg

**Comment by phd3** [comment]
I think it might be better to just add a new config in the `IcebergConfig` class, independent of the hive config.

**Comment by akshayrai** [comment]
Taking a look! I will raise a PR for this!

**Comment by findepi** [comment]
@phd3 has this been covered in 352?

**Comment by phd3** [comment]
yes, closing.
