### ISSUE TITLE
Raise minimum Java version to 11.0.10 to account for tzinfo changes

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#6662]
Joda time updated its internal tzinfo database to version 2020d and tzinfo 2020b dropped "US/Pacific-New" timezone.

According to https://www.oracle.com/java/technologies/tzdata-versions.html current, minimal java version 11.0.7 has pre tzinfo 2020b.

Java 11.0.10 is updated to tzinfo 2020d which matches Joda time internal tzinfo.

Adding this task to remove exclusions from code when Java version is raised.

**Comment by findepi** [comment]
I don't think we should raise the minimum JVM version for this

- if someone runs older version and try to use this zone -- query will fail cleanly (once we update Joda)
- majority of users do not care (it's not "UTC" or some very common zone like "Europe/Warsaw")

**Comment by wendigo** [comment]
@findepi I've created this task to remove the unnecessary if condition in the test - when if and only Java version is raised to 11.0.10 (and I agree that raising it for this issue only is not necessary as it's not a bug of any kind and it's easily mitigated on our side).

**Comment by alec-heif** [comment]
please do not raise the minimum java version without communicating some warning at least a couple of releases in advance - those of us running Trino in on-prem environments need quite a bit of lead time for java upgrades!

**Comment by findepi** [comment]
@alec-heif thanks for the feedback.

As expressed above, i would prefer to wontfix this unless @trinodb/maintainers speak otherwise.
