### ISSUE TITLE
SQL Server varchar predicate pushdown leads to incorrect results in default configuration

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6671]
Apparently, SQL Server uses case insensitive collation by default (like MySQL), so we should not declare a varchar predicate as enforced upon pushdown.

see TODO in the code, added in https://github.com/trinodb/trino/pull/6672

**Comment by kokosing** [comment]
How about char types? I see mysql fully pushes down the predicate for them. Is this correct?

**Comment by findepi** [comment]
Perhaps it is not. We should have a generic test for that.
