### ISSUE TITLE
Remove reserved pool

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#6677]
Discussion link: https://trinodb.slack.com/archives/CP1MUNEUX/p1610630362006000

**Comment by arhimondr** [comment]
I assume after this refactor there should always be a single memory pool and it should be reflected at the code level. More specifically it would result in replacing `Map<MemoryPoolId, ClusterMemoryPool> pools` with simply `ClusterMemoryPool memoryPool` in multiple places in the codebase. 

Is my understanding correct?

CC: @sopel39 @findepi @losipiuk @martint @dain

**Comment by findepi** [comment]
@arhimondr i am not entirely sure about this.
i am sure removing the reserved pool without this simplification is a good change.
i don't see any future use of >1 memory pools, but that doesn't mean there won't be.

i am personally ok either way, but please wait for opinion from others

**Comment by sopel39** [comment]
Can multiple memory pools be used with resource groups potentially in the future?

**Comment by martint** [comment]
I don't think there's currently any use case for multiple pools, so if we're going to have just one, we should get rid of the infrastructure for managing multiple ones. We can always add that back if it ever becomes necessary.

**Comment by dain** [comment]
I think we should get rid of supporting multiple pools, unless there is some reason someone to keep it right now.  We can always add a new system if some comes up with a reason to segment usage in the future.
