### ISSUE TITLE
[Hive Connector] Support for regional AWS STS endpoint for role assumption.

### ISSUE THREAD

**Issue by twiechert** [trinodb/trino#6693]
Hi,

we are currently migrating our trino setup. (Rel. 346) to an AWS EKS cluster located inside a private VPC where connection to S3 and STS is routed through regional VPC endpoints. To obtain credentials via STS, we can only connect to the regional STS endpoint (sts.eu-central-1.amazonaws.com) since the connection to the global default sts.amazonaws.com is blocked.

We could enforce the use of the regional endpoint for the hive metastore installation by setting two environment variables, which would have been picked up and considered accordingly by the AWS SDK:
 
```
 - name: AWS_DEFAULT_REGION
    value: "{{.awsRegion}}"
 - name: AWS_STS_REGIONAL_ENDPOINTS
    value: "regional"
```
This does not work for trino. Is there a way to force trino to use the regional STS endpoint similarly?

Our ultimate goal is to use trino with an IAM role provisioned through its assigned service account (https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).

From the AWS SDK perspective, this should be possible.

**Comment by twiechert** [comment]
This is only relevant if the IAM role to assume is explicitly set through `hive.s3.iam-role`.

Otherwise, the DefaultAWSCredentialsProviderChain (if recent enough) will pick the right credential provider up and will also respect the environment variables set to point it to the regional endpoints.

However, in our specific case, the containers were not run as root which led to `/var/run/secrets/eks.amazonaws.com/serviceaccount/token` not being accessible to the credential provider. 

I can conclude that trino works just fine with IAM roles for service accounts on EKS.

**Comment by fabioaraujopt** [comment]
How did you solve this?
