### ISSUE TITLE
java.lang.ClassNotFoundException: erver

### ISSUE THREAD

**Issue by huzef** [trinodb/trino#6704]
错误: 找不到或无法加载主类 erver
原因: java.lang.ClassNotFoundException: erver

**Comment by ebyhr** [comment]
Please share your operation and the entire. Also, I would recommend asking in `#troubleshooting`  channel of community Slack. 
https://trino.io/slack.html

**Comment by huzef** [comment]
[root@DGH-IDC-222 trino]# ./bin/launcher run
openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment Zulu11.45+27-CA (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.45+27-CA (build 11.0.10+9-LTS, mixed mode)
Error: cannot find or unable to load the main class erver
The reason:: java.lang.ClassNotFoundException: erver

**Comment by ebyhr** [comment]
Replied in https://trinodb.slack.com/archives/CGB0QHWSW/p1611477116044100

**Comment by findepi** [comment]
discussion moved to slack, let me close it here
