### ISSUE TITLE
Reduce number of connections made to RDBMS during planning with a JDBC connector

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6719]
For example, `io.trino.plugin.jdbc.JdbcMetadata#applyAggregation` calls `io.trino.plugin.jdbc.JdbcClient#prepareQuery` which opens a `Connection`, which subsequently is passed to `io.trino.plugin.jdbc.JdbcClient#toColumnMapping`.
In most cases, this connection is not used though.

### proposed solution

Use a lazy connection object 

### proposed solution (alternative)

Introduce a holder for a lazy connection and use it in these APIs.

### testing

We should be able to count number of connection open calls per query execution (conceptually similar to how we count metadata calls in `io.trino.tests.TestInformationSchemaConnector#assertMetadataCalls`).

**Comment by findepi** [comment]
@losipiuk @kokosing @electrum thoughts?

**Comment by kokosing** [comment]
This seems to be a bit related: https://github.com/trinodb/trino/issues/6477

**Comment by kokosing** [comment]
CC: @ssheikin

**Comment by kokosing** [comment]
We open and close transaction in a connector. Maybe we could associate a JDBC connection with Presto transaction so it could be reused along the way. Do we change JDBC connection properties, if we are using same JDBC properties that could work.

**Comment by findepi** [comment]
> Maybe we could associate a JDBC connection with Trino transaction so it could be reused along the way.

That could work. It has the benefit of reducing new connection count very effectively.
The downside is that it introduces new state, which may be a source of some bugs in the future.
Since there is some downside, it is not a clear win.

>  Do we change JDBC connection properties?

Probably not.

**Comment by kokosing** [comment]
Lazy object contains state too.

> Do we change JDBC connection properties?

We do or at least we want to. Notice that for INSERT or DELETE we might want to use `autocommit=true`, while for select we might prefer to use `autocommit=false`.

**Comment by losipiuk** [comment]
> Reduce number of connections ...

I would first want to understand what are we trying to fix here. Is the fact that we are opening too many of those actually noticable problem? Is connection pool not enough?

**Comment by findepi** [comment]
> Is connection pool not enough?

it's enough, but we don't use pooling except for Oracle

**Comment by kokosing** [comment]
> Is the fact that we are opening too many of those actually noticable problem?

It could be a problem. It could stress the authentication systems as each time connection could need go through authentication process entirely and could require dealing with external services like LDAP, Kerberos or IdP. Causing longer wall time for query or reliability issues.

**Comment by losipiuk** [comment]
I see - thanks for clarification. My personal preference goes towards @kokosing proposal, where we attach Connection object to transaction. Seems like a natural place, and more explicit than lazy wrapper. But I would not say that other apprach is total no-go.

**Comment by findepi** [comment]
When I filed the issue i had 'easy win' in mind -- a change provides and improvement, and without any significant drawback.
Attaching connection changes connection lifecycle significantly, and this on its own is a drawback (can be just good thing, or can have some side-effects). Of course, it promises better performance characteristics as well.
Thus, before we go into this probably better, but not "just a refactor" option, I would want ti understand benefits more and see when they outweigh additional lifecycle complexity.

**Comment by kokosing** [comment]
I am not sure I understand the "lazy connection" approach. Can you please share some details? 

Also I think both approaches are more or less a way of implementing connection pooling. Hence we need to think about all the problems that connection pooling has to address. Like how long we can hold the connection opened (long lasting INSERT INTO)?

**Comment by losipiuk** [comment]
My understanding of "lazy connection" is that in place when we normally pass open,established connection, we pass a wrapper which will only open real connection internally when someone wants to use it (e.g. grap a stament from it).  Close lifecycle remains the same as we have now. The lazy connection gets closed it the same place when non-lazy connection is closed now. If lazy connection was not used, the close does nothing.

Is that what you meant @findepi ?

**Comment by findepi** [comment]
Exactly, thanks @losipiuk

**Comment by kokosing** [comment]
Ok, so the point of lazy connection is to optimize no-op connections. Do you think it will make a difference? I am fine with that as it is obvious improvement.

> testing

We provide JMX metrics for opened connections count, but these are hard to be used in unit tests.

**Comment by kokosing** [comment]
There is another point for https://github.com/trinodb/trino/issues/6719#issuecomment-767419000, if you have a JDBC driver that does not support handling of `InterruptedException` then we will be able abort all in progress queries against remote data source when Trino query is cancelled.
