### ISSUE TITLE
Database cannot be created with a location set

### ISSUE THREAD

**Issue by milnomada** [trinodb/trino#6729]
Using Trino CLI 351,
`trino --user some --catalog hive`

The following sentence:
```
> CREATE SCHEMA cdn AUTHORIZATION USER some WITH ( location = 's3://metastore/place' );

Gives: 
Query 20210126_143319_00009_e8xz6 failed: Database cannot be created with a location set
```

The documentation points out the possibility of schema creation using a location:
https://trino.io/docs/current/sql/create-schema.html

Please let me know any way to solve this.

**Comment by findepi** [comment]
You did not include the full stacktrace, but in current code the only place where this exception can be thrown is in the `file` metastore.
The file metastore implementation is not meant to be used. It is intentionally not documented, and limited to exact the set of features we need internally for testing.
Therefore I am closing this.

Also note that, even if wanted to add a feature like this in file metastore, it would go against its simplistic design. I would strongly recommend using either `thrift` or `glue` metastore.

**Comment by milnomada** [comment]
Thanks for the reply,

It would be very good for the users of this project, that an explicit mention to what you comment visibli appears in your documentation:
> The file metastore implementation is not meant to be used. It is intentionally not documented, and limited to exact the set of features we need internally for testing.

**Comment by findepi** [comment]
@milnomada see https://github.com/trinodb/trino/issues/5714#issuecomment-727101635
