### ISSUE TITLE
Test optimized Parquet writer in TestHiveStorageFormats

### ISSUE THREAD

**Issue by jirassimok** [trinodb/trino#6738]
Currently, we test Parquet with default config, but not with the optimized writer.

See #6382.

**Comment by fredlacis** [comment]
Hey @jirassimok, can I work on this? This would be my first issue.
If so, do you have any tips on where to start from?

**Comment by jirassimok** [comment]
@fredlacis Go ahead!

Take a look at [`TestHiveStorageFormats.storageFormats`](https://github.com/trinodb/trino/blob/a35080a8e3076f60aa567e87febd9ff690a034c4/testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java#L212-L225) and the related logic in the same class. As a starting point, maybe just add the format and session property to the list there, and see what fails (I expect some timestamp tests to fail because of #5357, and there might already be a way to exclude a format from some of the timestamp tests).

**Comment by fredlacis** [comment]
@jirassimok Before I even start modifying the file, I tried to run the TestHiveStorageFormats test and I keep getting the same error on every test:
`Catalog does not exist: hive`
I'm running the test server, but I don't know if there is any extra configuration that should be made.
Do you know what could be going on?

**Comment by jirassimok** [comment]
If you're running the server from `testing/trino-server-dev`, it should have a pre-configured Hive catalog (`testing/trino-server-dev/etc/catalog/hive.properties`).

You'll also need the product test environment, which you can run like `./bin/ptl env up --environment=singlenode --config=config-default --without-trino`. You can leave out `--without-trino` to also run the server with the appropriate catalogs, but then you'll have to restart the whole environment to use any changes you make.

**Comment by Justin-Kwan** [comment]
@jirassimok completed in https://github.com/trinodb/trino/pull/8699
