### ISSUE TITLE
MySQL, MemSQL varchar and char predicate pushdown leads to incorrect results

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#6746]
MySql uses case insensitive collation by default for char and varchars.

Currently MySQL do restore predicate in Presto for varchar. This is almost correct, because in case it looks like it also pushes down `!=` predicate to data source which is incorrect.

Char is fully pushed down currently, which is incorrect for `=` and `!=`.

**Comment by kokosing** [comment]
Same might be applicable to MemSql.

**Comment by hashhar** [comment]
MemSQL also does PushdownAndKeep so it might be incorrect for `!=` as you've pointed out.

ref: https://github.com/trinodb/trino/pull/5495/files#diff-d72a75b2494965c69929a13daf8a872fd2cbca16534c29f7a77a31156645a0a8R152
