### ISSUE TITLE
SystemAccessControl  not support  View Definer Security

### ISSUE THREAD

**Issue by carl-zero** [trinodb/trino#6755]
#### describe
When we used SystemAccessControl to check view authentication, we found that when the view's definer mode was turned on, but the trino used the invoker to authenticate the entity table

SQL Exmaple：
```
CREATE table stu(id int,name varchar);
CREATE VIEW stuviewdefiner SECURITY DEFINER AS SELECT * FROM stu;
SELECT * FROM stuviewdefiner
```

I think follow the documentation（https://trino.io/docs/current/sql/create-view.html）
When execute “SELECT * FROM stuviewdefiner”, Trino will check view stuviewdefiner authentication use  current User, and check table stu authentication use definer，but the result was not.

When I check Trino Code,I find code in  AccessControlManager class 
```
    @Override
    public void checkCanSelectFromColumns(TransactionId transactionId, Identity identity, QualifiedObjectName tableName, Set<String> columnNames)
    {
        requireNonNull(identity, "identity is null");
        requireNonNull(tableName, "tableName is null");
        requireNonNull(columnNames, "columnNames is null");

        authenticationCheck(() -> checkCanAccessCatalog(identity, tableName.getCatalogName()));

        authorizationCheck(() -> systemAccessControl.get().checkCanSelectFromColumns(identity, tableName.asCatalogSchemaTableName(), columnNames));

        CatalogAccessControlEntry entry = getConnectorAccessControl(transactionId, tableName.getCatalogName());
        if (entry != null) {
            authorizationCheck(() -> entry.getAccessControl().checkCanSelectFromColumns(entry.getTransactionHandle(transactionId), identity.toConnectorIdentity(tableName.getCatalogName()), tableName.asSchemaTableName(), columnNames));
        }
    }
```

Trino use Identity User  to  check authenticate , When  I turned on view's definer, this code still use invoker to check authenticate

Please help look at this problem，I use the version is 316

**Comment by findepi** [comment]
> I use the version is 316

Thanks for providing this information. Note that 316 is 1.5 year old and has some well known problems, including CVE-reported security issues.
I am not sure i understand what the problem is, but could you please verify it's still applicable in latest version (351 right now)?
You can get it from https://trino.io/download.html .

**Comment by findepi** [comment]
if you have any problem upgrading, please reach out for help on the `#troubleshooting` channel  on [our slack](https://trino.io/slack.html)

**Comment by kokosing** [comment]
See usages of `io.trino.security.ViewAccessControl`. This is dedicated access control for views where we use different `Identity` depending if it is `INVOKER` or `DEFINER`

**Comment by carl-zero** [comment]
But it is difficult to upgrade due to business reasons，So I try adjust code in 316

I adjust visitTable method in StatementAnalyzer Class
```
        @Override
        protected Scope visitTable(Table table, Optional<Scope> scope)
        {
          .....
            QualifiedObjectName name = createQualifiedObjectName(session, table, table.getName());
            analysis.addEmptyColumnReferencesForTable(accessControl, session.getIdentity(), name);
            Optional<ConnectorViewDefinition> optionalView = metadata.getView(session, name);
           
            // Add my logic here
            // if optionalView  is definer, add owner of current view to Identity
            //  and when check view authentication in SystemAccessControl, authenticate by obtaining the value
```

thinks Piotr Findeisen  and Grzegorz Kokosiński !
