### ISSUE TITLE
Array docs don't show how to convert a non-array column to array

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#6777]
Some docs like:
SELECT ARRAY[state] FROM system.runtime.nodes;

would be helpful to show varchar column to array conversion

**Comment by mosabua** [comment]
Good first issue if writer has SQL knowledge.

**Comment by findepi** [comment]
The `ARRAY[ ... ]` constructor form is mentioned in the docs here https://trino.io/docs/current/language/types.html#array and here https://trino.io/docs/current/functions/array.html

I don't think this needs improvement, does it?

**Comment by tooptoop4** [comment]
it only shows on literals not a column

**Comment by findepi** [comment]
but the syntax is the same, right?

**Comment by mosabua** [comment]
I tend to agree.. literals are just easier to document and for users to follow and test locally themselves. Columns of the same data type can always stand in place of the literal.

**Comment by tooptoop4** [comment]
>  Columns of the same data type can always stand in place of the literal.

not true, below doesn't work:

```
with t as (select 5 mycol)
select *, current_timestamp + interval mycol minute from t
```

**Comment by findepi** [comment]
@tooptoop4 
`interval '1' minute` is a _literal form for interval day to second type_. 
Just like `1` is a literal form for integer type, or `DECIMAL '11.1'` is a literal form for decimal(3,1) type.
