### ISSUE TITLE
sorting postgresql data 

### ISSUE THREAD

**Issue by catalina-ch** [trinodb/trino#6787]
hi everyone, 

i want to sort huge postgresql table and write back to postgresql.
It takes too much time, executing directly postgresql
`insert into table_2 
select * from table_1 
order by column_1`

i give a try from trino;
`insert into postgresql_catalog.table_2 
select * from postgresql_catalog.table_1 
order by column_1`

And selected from postgresql 
`select * from table_2`

Table_2 data was not truly sorted, is there a way to achieve using trino ?

Presto version: 312

**Comment by raunaqmorarka** [comment]
Please try this with `set session skip_redundant_sort=false`

**Comment by findepi** [comment]
in SQL tables are not collections of rows, without a specific order.
Trino does not provide any guarantees on the order of data, except for explicitly ordered SELECT queries.

Some databases may provide order guarantees. I think in PostgreSQL case it's rather a side effect of the implementation though -- the order may be guaranteed until you UPDATE or DELETE data in your table.

When Trino writes data to PostgreSQL, it does so in multiple threads, so it would be hard to ensure final ordering _implicitly_.
This would need to be an explicit feature of the PostgreSQL Trino connector. I don't think there has been much interest about feature like that, so i am not convinced we would add it.

I would suggest applying explicit ORDER BY when you _read_ from your tables. This will help you stay within ANSI SQL guarantees and thus help keep portability.

**Comment by catalina-ch** [comment]
ok thanks
