### ISSUE TITLE
"Show create view" not showing SECURITY INVOKER section

### ISSUE THREAD

**Issue by tnatssb** [trinodb/trino#6792]
Creating View:
create view <catalog_a>.<schema_c>.test1 SECURITY INVOKER
as
select *
  from <catalog_x>.<schema_y>.test_orig to
 where to.year > '2020';

View definition:
show create view <catalog_a>.<schema_c>.test1;

Result of the above ‘show’ command:

create view <catalog_a>.<schema_c>.test1
as
select *
  from <catalog_x>.<schema_y>.test_orig to
 where to.year > '2020';

Notice the SECURITY INVOKER not showing up. 

From Dain:
Looks like a bug.  It don’t see anything in the formatter:
https://github.com/trinodb/trino/blob/03d8e5abc686c5c4a9f96ca14db07e2aed880174/core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java#L809

**Comment by kokosing** [comment]
I assigned this to myself as I know about somehow who would be trilled to implement this.

**Comment by ksobolew** [comment]
Not sure if I'll be thrilled, but I can take a look :)

**Comment by ksobolew** [comment]
`SqlFormatter` is not the right place to look - besides, the method linked in the description formats the `SHOW CREATE VIEW` command, not `CREATE VIEW` (if you look [at `visitCreateView`](https://github.com/trinodb/trino/blob/03d8e5abc686c5c4a9f96ca14db07e2aed880174/core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java#L619), you'll see all the relevant clauses there). The fix should be in `ShowQueriesRewrite`, but we won't be able to reconstruct the exact `CREATE VIEW` there - specifically we don't have enough information to say if the command contained `SECURITY DEFINER` or not. But we can definitely show `SECURITY INVOKER` just fine.

**Comment by kokosing** [comment]
> but we won't be able to reconstruct the exact CREATE VIEW there - specifically we don't have enough information to say if the command contained SECURITY DEFINER or not. But we can definitely show SECURITY INVOKER just fine.

👍 I see. That is inline with `io.trino.execution.CreateViewTask#execute`. We loose the information about if `SECURITY` clause was there. So restore that we would need to change the SPI and the engine. I think in this case it is ok to display `SECURITY DEFINER` in case of missing `SECURITY` clause.

**Comment by ksobolew** [comment]
I was more inclined to skip the DEFINER as it's the default, but making it always explicit works too.
