### ISSUE TITLE
trino-druid plugin: Unable to query tables having any upper case characters

### ISSUE THREAD

**Issue by hugabora** [trinodb/trino#6850]
We have tables in druid with mixed case, such as CamelCase.

Selecting via trino-druid connector does not work in this case:
`SELECT * FROM druid.druid.CamelCase`
Fails with: 
`java.sql.SQLException: Query failed (#20210208_120105_00017_f765z): line 1:15: Table 'druid.druid.camelcase' does not exist` 
Version: 351
  `trino-351` , `trino-druid-351`, `trino-jdbc-351`, etc.

What works:
- accessing CamelCase table **directly from druid**, using druid JDBC driver, druid performs **case-sensitive match**
- accessing lowercase named tables **via trino** using **case-insensitive match**
  - the table names must be lowercase in druid
  - the query in trino can be any case.

Note:
- There is a stackoverflow question that is likely the same or related: [Presto connector for druid fails to identify tables with uppercase names](https://stackoverflow.com/questions/65594896/presto-connector-for-druid-fails-to-identify-tables-with-uppercase-names)
- I am adding a comment there to connect to this issue

Hypothesis:
It looks like trino always converts the table name to lowercase before accessing. As a result a lowercase table trino can be queried written in any case, resulting in case-insensitive matching.
However when the original name has any uppercase letter, it cannot be queried at all.

**Comment by findepi** [comment]
@hugabora thanks for the report!

I think the reason is that `io.trino.plugin.druid.DruidJdbcClient#getTableHandle` (an override) does not do `toRemoteSchemaName` / `toRemoteTableName` conversion as the super method `BaseJdbcClient#getTableHandle`. **If it did**, you would able to access the tables is non-lowercase once you enable `case-insensitive-name-matching`.
cc @samarthjain

**Comment by dheerajkulakarni** [comment]
Hey @findepi, I am interested to work on this, can you please assign it to me?

**Comment by findepi** [comment]
@dheerajkulakarni that's awesome!
if you need any guidance around hwo to test this, see `TestMySqlCaseInsensitiveMapping`. Also @hashhar will be able to help more, if needed.

**Comment by dheerajkulakarni** [comment]
Sure, thanks @findepi, I will try to add some test cases around this.

**Comment by ronnuriel** [comment]
Hi , 
This is my first issue can i join ? 
i will be more than happy to get guidance  for my first time !
Ron

**Comment by ebyhr** [comment]
@dheerajkulakarni Are you still working on #7197?

**Comment by dheerajkulakarni** [comment]
Hey @ebyhr , I am really sorry not getting time to work on this, If someone is interested please do assign it to them!

**Comment by renatocron** [comment]
Any workaround available? All my data sources on the druid side are uppercase, I tried using the json, but the descrption is correct, the search is only insensitive at trino but not on the sent query to druid

https://github.com/trinodb/trino/pull/7197

**Comment by renatocron** [comment]
@Giwrgosyea I was able to run the query with Table functions but it was too slow so I gave up onto this strategy 

If you can upgrade the druid to 24.0.0 (or to 25.0.0), you can try the new query runner, that can run complex query (still not perfect, but can run, so it's better than before)

**Comment by Giwrgosyea** [comment]
@renatocron Thanks for reply. Are you able to query tables like that `SomeTableInDruid` ? If yes can please share the druid configuration file in trino? or the mapping.json ? I am using the containerised version of druid 25.0.0 and the latest trino version.

**Comment by renatocron** [comment]
I don't have the SQL/history anymore. I think the map was not needed, because the table-func bypasses the map entirely 

```
connector.name=druid
connection-url=jdbc:avatica:remote:url=https://user:pass@domain.druid.com/druid/v2/sql/avatica/?caseSensitive=true
case-insensitive-name-matching=true
case-insensitive-name-matching.config-file=/etc/trino/catalog/map.json
```

```
{
    "schemas": [
        {
            "remoteSchema": "druid",
            "mapping": "druid"
        }
    ],
    "tables": [
        {
            "remoteSchema": "druid",
            "remoteTable": "FOO_GENERIC_LOG",
            "mapping": "generic_log"
        }
    ]
}
```
