### ISSUE TITLE
BigQuery tables names with "_"

### ISSUE THREAD

**Issue by dbalabka** [trinodb/trino#6855]
It seems that BigQuery tables or schemas which named with underscore lead to an issue that Trino can not find the table.

**Comment by hashhar** [comment]
I am unable to reproduce this with either a schema or a table with underscore in the name.

Can you share more details:

1. What's the table and schema name which are you having an issue with?
2. How do you identify that Trino cannot find the table? `SHOW TABLES`? `information_schema`? or simply trying to `SELECT` from the table?
3. Try running the Trino CLI with `--debug` and share the stack-trace when you try to perform the query which fails - that should give a good idea of where the failure is.

**Comment by findepi** [comment]
Adding to the above -- please also verify your tables are all lowercase (or see https://github.com/trinodb/trino/pull/6748 if they are not).

**Comment by dbalabka** [comment]
@findepi, @hashhar  I'm using all lower case now and I can not reproduce the problem, so it seems the initial problem has been related to #6748.

Thanks for your quick response.  I think we can close this.
