### ISSUE TITLE
we had support most hive sql syntax, is it possible to commit to trino?

### ISSUE THREAD

**Issue by ImTangYun** [trinodb/trino#6857]
for example：
select ‘data’ equals select “data” and select \`data\` equls select data in hive
but select “data” equals select data in presto
![syntax](https://user-images.githubusercontent.com/5945486/109782628-0cd77800-7c44-11eb-9ad0-0fb39d068270.png)
![syntax1](https://user-images.githubusercontent.com/5945486/109782822-47411500-7c44-11eb-895b-a712c3863114.png)

**Comment by findepi** [comment]
I am not sure what the question is about?

**Comment by ImTangYun** [comment]
> I am not sure what the question is about?

As known that presto only support ansi sql syantax，which is quite different from
hive sql syntax，so we devlop a hive sql parser to support hivesql to run on presto

**Comment by mosabua** [comment]
Trino has multiple ways to support Hive view. Please see more at 

https://github.com/trinodb/trino/blob/master/docs/src/main/sphinx/connector/hive.rst#hive-views

**Comment by ImTangYun** [comment]
> Trino has multiple ways to support Hive view. Please see more at
> 
> https://github.com/trinodb/trino/blob/master/docs/src/main/sphinx/connector/hive.rst#hive-views
> 
> it uses Coral from LinkedIn

The hive view is so simple that not enough to support our complex bussiness in our company，we have surpport most hive sql syntax for example insert overwrite、explode lateral view、rlike、semi join、with cube、with rollup and many other syntax， we just want to contribute to open source

**Comment by findepi** [comment]
cc @martint @electrum

**Comment by ImTangYun** [comment]
any ideas? is it ok?

**Comment by my-byte-2021** [comment]
Sounds interesting. Could you share your code through a pull requests?

**Comment by ImTangYun** [comment]
> Sounds interesting. Could you share your code through a pull requests?

to do this, we have some work todo, so wo have to make sure commitee will receive this feature

**Comment by zhanglistar** [comment]
Really great feature, please contribute, thanks!

**Comment by mosabua** [comment]
Trino uses Coral for supporting Hive views.. so I think it might be best to contribute to that project and then Trino can absorb the features automatically. https://github.com/linkedin/coral

**Comment by findepi** [comment]
For Trino Coral integration, this is the tracker: https://github.com/trinodb/trino/issues/5606

**Comment by findepi** [comment]
@mosabua note that it seems here we're talking about client-facing support for HiveQL, not views-related.

**Comment by mosabua** [comment]
Yeah ... but from my understanding Coral could theoretically also do that translation as well. Right? It might mean that Coral is added as a front of Trino that translates HiveQL to SQL, as understood by Trino, and then Trino processes as usual. That would however be a separate and new integration.

**Comment by ImTangYun** [comment]
@mosabua We support hive syntax not just about hive view，may be somthing further than support sql parser. For example 1.implicit cast in hive ：
    select '123'=123
2.column start with number:
     select '123_cc' from tbl
3.create table like:
      create table tbl1 like tbl2
And many other features that hive support but trino not support, With ability to swith by just a session property

**Comment by kokosing** [comment]
Conceptually Trino SQL and Hive SQL are way different. For example notice that Hive does not have a concept of catalogs.

I think you it would be better to have a proxy/gateway that would take care of SQL translation for you. So instead of going to Trino, user would connect to something else which would translate SQL and then query Trino. So this would be a different layer and so different project I guess.

**Comment by ImTangYun** [comment]
> 

Thanks for your suggestion. If just translate sql, it is difficult to implement many features, for example:
1.implicit type conversion 
(select 123='123')
2.view created by hive/spark engine
3.hive type result of show create table
4.lateral view explode()

**Comment by kokosing** [comment]
Yes, it is difficult. You could have a parser like in #10381, and surely some semantic analyzer, then from AST you can generate Trino SQL.

**Comment by ImTangYun** [comment]
> Yes, it is difficult. You could have a parser like in #10381, and surely some semantic analyzer, then from AST you can generate Trino SQL.

Most of populate engine like spark/flink/hive support hive syntax, and many big company like Tencent had support hive syntax in their internal presto.It really a pity that trino community reject this feature.

**Comment by ImTangYun** [comment]
@findepi @electrum @dain @martint  Any other suggestion？

**Comment by bitsondatadev** [comment]
👋 @ImTangYun - this issue has drawbacks that don’t align with our preferred approach, so we’re not going to proceed with this implementation. If you'd like to continue the discussion on this at any point in the future, feel free to re-open and chime in.

See: https://github.com/trinodb/trino/pull/10379#issuecomment-1301060587
