### ISSUE TITLE
Migrate ORC protobuf from Travis to GitHub Actions

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6860]
Migrate https://github.com/trinodb/orc-protobuf 

see https://github.com/trinodb/trino/issues/6859 for more info

**Comment by choiwaiyiu** [comment]
@findepi
May I work on this issue?

**Comment by findepi** [comment]
That would be great, thanks!

**Comment by hashhar** [comment]
Implemented in https://github.com/trinodb/orc-protobuf/pull/9
