### ISSUE TITLE
Remove usages of deprecated Files.createTempDir

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6908]
`com.google.common.io.Files#createTempDir` is deprecated.
`java.nio.file.Files#createTempDirectory` should be used instead.

- [ ] core module #7818
- [ ] plugin module
- [ ] testing module
- [ ] .mvn/modernizer/violations.xml

**Comment by vaibhavkhanduja** [comment]
@findepi as a newbie .. can I take a tab at this?

**Comment by findepi** [comment]
@vaibhavkhanduja absolutely, go for it!

since i think there are multiple occurrences of the deprecated function, i recommend to do this in steps.
Fix a couple, do a PR. Then fix another couple. Small PRs are best to work with.

**Comment by hguercan** [comment]
Started also working on this issue since its open since 19 Feb. Hope this is fine.

**Comment by ebyhr** [comment]
@findepi Do we update modernizer configuration in this issue?

**Comment by mohitsaxenaknoldus** [comment]
Can I be assigned to it? I can do it.
