### ISSUE TITLE
No predicate pushdown when using `WHERE boolean_column` condition

### ISSUE THREAD

**Issue by 2DKot** [trinodb/trino#6953]
Hello Everyone!
I am using Trino with PostgreSQL connector. I found that the method of boolean checking in the `WHERE` clause affects the query plan dramatically.

I have Django auth_user table, where is_staff is a boolean, NOT NULL column.
Checking with `= true`:

```
EXPLAIN
select id
FROM pd.public.auth_user
where is_staff = true
```

```
Fragment 0 [SINGLE]
Output layout: [id]
Output partitioning: SINGLE []
Stage Execution Strategy: UNGROUPED_EXECUTION
Output[id]
│ Layout: [id:integer]
│ Estimates: {rows: ? (?), cpu: ?, memory: 0B, network: ?}
└─ RemoteSource[1]
Layout: [id:integer]

Fragment 1 [SOURCE]
Output layout: [id]
Output partitioning: SINGLE []
Stage Execution Strategy: UNGROUPED_EXECUTION
TableScan[pd:public.auth_user public.auth_user columns=[id:integer:serial], grouped = false]
Layout: [id:integer]
Estimates: {rows: ? (?), cpu: ?, memory: 0B, network: 0B}
id := id:integer:serial
```

Without EXPLAIN this query executes for 0.09 seconds.

Checking without `= true`:

```
EXPLAIN
select id
FROM pd.public.auth_user
where is_staff
```

```
Query Plan
Fragment 0 [SINGLE]
Output layout: [id]
Output partitioning: SINGLE []
Stage Execution Strategy: UNGROUPED_EXECUTION
Output[id]
│ Layout: [id:integer]
│ Estimates: {rows: ? (?), cpu: ?, memory: 0B, network: ?}
└─ RemoteSource[1]
Layout: [id:integer]

Fragment 1 [SOURCE]
Output layout: [id]
Output partitioning: SINGLE []
Stage Execution Strategy: UNGROUPED_EXECUTION
ScanFilterProject[table = pd:public.auth_user public.auth_user columns=[id:integer:serial, is_staff:boolean:bool], grouped = false, filterPredicate = "is_staff"]
Layout: [id:integer]
Estimates: {rows: ? (?), cpu: ?, memory: 0B, network: 0B}/{rows: ? (?), cpu: ?, memory: 0B, network: 0B}/{rows: ? (?), cpu: ?, memory: 0B, network: 0B}
is_staff := is_staff:boolean:bool
id := id:integer:serial
```

Now ScanFilterProject is used.
Without EXPLAIN this query executes for 11 seconds. This is 150 times longer.

The version of Trino is 352.

PS: I'm sorry for the title of the issue. I'm not sure if it is correct.

**Comment by sopel39** [comment]
it seems we miss basic boolean column reference in `io.trino.sql.planner.DomainTranslator.Visitor`

**Comment by MariyaR** [comment]
Hello @sopel39! 
I would like to work on this, could you please provide a bit more information on what should be done?

**Comment by findepi** [comment]
@MariyaR see `io.trino.sql.planner.TestDomainTranslator` and usages of `io.trino.sql.planner.TestDomainTranslator#fromPredicate` in particular -- those are the tests which exercise conversion from an Expression to a Domain, which we believe is the problem here

**Comment by MariyaR** [comment]
Hello @findepi, 
do I understand correct that I can override visitSymbolReference method in the TestDomainTranslator.Visitor ?

**Comment by findepi** [comment]
I guess you mean `DomainTranslator.Visitor`. Yes, this is where I'd start working on this.

**Comment by MariyaR** [comment]
#7263
