### ISSUE TITLE
QueryCompletedEvent results with empty columns list when table alias is used

### ISSUE THREAD

**Issue by guyco33** [trinodb/trino#6960]
#### Without table alias:
```javascript
SELECT * FROM tab

queryCompletedEvent.getMetadata().getTables().get(0).getColumns()  => ["col1", "col2"]
```

#### With table alias:
```javascript
SELECT * FROM tab a

queryCompletedEvent.getMetadata().getTables().get(0).getColumns() => []
```

**Comment by Praveen2112** [comment]
Did we try with `QueryIOMetadata` ?

**Comment by kasiafi** [comment]
@guyco33 please check https://github.com/trinodb/trino/pull/6972. It might solve the issue.

**Comment by guyco33** [comment]
> Did we try with `QueryIOMetadata`

Issue doesn't happen with `QueryIOMetadata`

**Comment by guyco33** [comment]
@Praveen2112 
There are some cases where `QueryIOMetadata` results with empty column list while `QueryMetadata` results with a list.
```javascript
SELECT count(*) FROM (SELECT * FROM tab)
```
`QueryIOMetadata` - column = []
`QueryMetadata` - columns = ["col1", "col2"]

@kasiafi 
I will test #6972 to verify it fixes the issue

**Comment by Praveen2112** [comment]
I guess #6972 should fix the issue

**Comment by guyco33** [comment]
I approve that #6972 fixes the issue. Wonder what's the possible impact of this change on other use cases.

**Comment by kasiafi** [comment]
fixed by https://github.com/trinodb/trino/pull/6972
