### ISSUE TITLE
Remove usage of @Test(expectedExceptions) on non-oneliner test methods

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6974]
Usage of `@Test(expectedExceptions = ...)` is discouraged and we prefer to use `org.assertj.core.api.Assertions#assertThatThrownBy`.

While it's arguably acceptable to use `@Test(expectedExceptions = ...)`  on one liner test methods, it should be avoided in test methods comprising of multiple statements. 

Since there are still a few occurrences of `@Test(expectedExceptions = ...)`  in the codebase, anyone working on this is encourage to do incremental PRs, with relatively small portions of code being changed at once.

**Comment by leadermags** [comment]
Hi, this is my first time, can I try working on this? Thank you.

**Comment by findepi** [comment]
@leadermags thank you, go for it!

If i were to recommend something, please do the work in small chunks. 
Small PRs are easier to get reviewed and merged, so the work can progress smoothly.

**Comment by mohitsaxenaknoldus** [comment]
Can I be assigned to it? I can do it.
