### ISSUE TITLE
Iceberg show tables nothing list

### ISSUE THREAD

**Issue by rlcyf** [trinodb/trino#6982]
trino:351
iceberg:0.11
spark:3.0.1

create table from spark/flink/java api!

```
 trino:ods> show tables;
 Table
 -------
 (0 rows)


trino:ods> select * from sample;
    id | data
    ----+------
    1 | a
    (1 row)


trino:ods> desc sample;
    Column |  Type   | Extra | Comment
    --------+---------+-------+---------
    id     | bigint  |       |
    data   | varchar |       |
    (2 rows)
```

**Comment by hashhar** [comment]
Can you check once if your problem matches the one described in https://github.com/trinodb/trino/issues/1592?

What was your Iceberg table created using? Spark? Flink? Or something else?

**Comment by rlcyf** [comment]
> Can you check once if your problem matches the one described in #1592?
> 
> There is a PR in progress to solve this. #6617

Yes,it's the same
