### ISSUE TITLE
Add syntax to support time travel in Trino

### ISSUE THREAD

**Issue by jacob-stein** [trinodb/trino#6988]
Currently Trino does not support time travel. This document describes a series of syntax and engine changes that will enable connectors to implement solutions for users to submit queries that return results as if the queries had been sent at a specified time.

https://docs.google.com/document/d/11Ps3FQlfbHqUG_O_UtN1j_orF-B-PO6c7UJfEodD854/edit?usp=sharing

**Comment by martint** [comment]
> We need to update the SQL parser so it is able to construct a tree from a query that includes a for clause. This includes changes to the QuerySpecification as well as the creation of a few new nodes.

The `<query system time period specification>` clause is associated with a table name in the FROM clause, not to the whole FROM clause. Therefore, the change should be in `relationPrimary` in the grammar, and will require either changes to the `Table` syntax tree node or a new node similar to `AliasedRelation`.

**Comment by jacob-stein** [comment]
> > We need to update the SQL parser so it is able to construct a tree from a query that includes a for clause. This includes changes to the QuerySpecification as well as the creation of a few new nodes.
> 
> The `<query system time period specification>` clause is associated with a table name in the FROM clause, not to the whole FROM clause. Therefore, the change should be in `relationPrimary` in the grammar, and will require either changes to the `Table` syntax tree node or a new node similar to `AliasedRelation`.

Thanks! I needed to update that - we will be adding the change to relationPrimary. The document has been updated with the correct syntax.
