### ISSUE TITLE
Notes in documentation use too small font size

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6996]
IMO notes box, as used eg @ https://trino.io/docs/current/functions/json.html#json_parse, uses too small a font, and this can lead to it being less readable.

Sadly the screenshot from Mac shows up much larger than it was originally, so it doesn't convey the problem.

![image](https://user-images.githubusercontent.com/144328/108815276-786e7500-75b4-11eb-870f-a5a644485e34.png)

**Comment by mosabua** [comment]
This is done via the linked PR.
