### ISSUE TITLE
Remember best known statistics for TableHandle on engine side

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6998]
As described in https://github.com/trinodb/trino/pull/844, predicate pushdown may degrade the quality of statistics provided by a connector.
If the connector is not able to consider Filter in the returned response, and engine no longer has a Filter, the statistics will not reflect the effect of filtering.

This can become a bigger issue, as we progress  with https://github.com/trinodb/trino/issues/18 and https://github.com/trinodb/trino/pull/4249, https://github.com/trinodb/trino/issues/6613 https://github.com/trinodb/trino/issues/6620 in particular.

Here, a solution is proposed where Engine keeps track of pre-pushdown statistics on TableHandle / TableScanNode and uses them when connector can no longer produce statistics.
By "pre-pushdown" i mean statistics derived from the TableScan + the operation being pushed down (e.g. Filter, Aggregation, Join, TopN, etc.), calculated on the engine side.

cc @rzeyde-varada @losipiuk @sopel39 @martint @kokosing

**Comment by findepi** [comment]
The computation would need to happen (eagerly, or lazily - to be defined), after successful pushdown, based on the plan nodes before the pushdown.

**Comment by sopel39** [comment]
This does not exactly solve https://github.com/trinodb/trino/pull/844 as connector might support filter pushdown but might not support predicate pushdown when computing stats.
For https://github.com/trinodb/trino/pull/844 I think engine should first try to compute stats with predicate applied and if it returns `empty`, then engine should try to compute stats without any predicate and apply predicate with stats calculator.
