### ISSUE TITLE
Elasticsearch fields with a single value should be handled alongside with fields that have multiple values (Array)

### ISSUE THREAD

**Issue by MusKaya** [trinodb/trino#7012]
**Introduction**
From [Trino docs](https://trino.io/docs/current/connector/elasticsearch.html#array-types): 

> Fields in Elasticsearch can contain [zero or more values](https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html) , but there is no dedicated array type.

In order for Trino to handle a field that contains an array, that field [**has** to be inserted](https://trino.io/docs/current/connector/elasticsearch.html#array-types) under a Trino-specific structure in the `_meta` section of the index mapping.

**Problem Statement**
In cases where the same field both contains single and multiple values (such as `"score": "97"` and `"score": ["97", "90"]`, then Trino throws out the following error since we have (and we must) specify that this field is an array under the `"_meta"` section of the index mapping.
`io.trino.spi.TrinoException: Expected list of elements for field 'score' of type ARRAY: 97 [String]`

If we don't add this field under the `"_meta"` section of the index mapping, then we receive the following error:
`Expected a string or numeric value for field 'score' of type VARCHAR: [97, 90] [ArrayList]`

**Additional Info**
@martint from the slack `#troubleshooting` channel

>:
martin  1 day ago
oh, actually… this is a bug, I think. Elasticsearch doesn’t have a proper concept of array types. That’s why we had to add the mechanism for explicit mappings. In the case where a document contains a single element, it should be interpreted as a single-element array.
The case that would be hard support is when the elements have mixed types across documents, but that’s no different than documents having mixed scalar types.

**Comment by MusKaya** [comment]
Tagging @martint @findepi @bitsondatadev

**Comment by findepi** [comment]
cc @aalbu
