### ISSUE TITLE
Can't rename partitioned hive table

### ISSUE THREAD

**Issue by rmgpinto** [trinodb/trino#7013]
There’s an issue altering a hive table name with partitions on S3.

```
create table "data_lake"."data_warehouse"."f_table__dbt_tmp" with (partitioned_by = ARRAY['column'])  as (SELECT ...);
alter table "data_lake"."data_warehouse"."f_table__dbt_tmp" rename to "data_lake"."data_warehouse"."f_table";
```

alter table statement fails with `New location for this table hive.data_warehouse.f_table already exists : s3a://.../data_warehouse/f_table`

S3 shows both directories: `f_table__dbt_tmp` and `f_table`  with the correct files.

**Comment by sopel39** [comment]
Does it work with Hive? It does look like a bug?

**Comment by sopel39** [comment]
Are you sure `f_table` dir did not exist before?

**Comment by rmgpinto** [comment]
I'm sure, just replicated this on a new and clean enviroment.

**Comment by rmgpinto** [comment]
I have more information.
The table is successfully renamed on trino, the files on s3 are copied to the new directory, but the old directory remains on s3.

**Comment by rmgpinto** [comment]
I have more information.
The table is successfully renamed on trino and the files are copied on s3 to the new location.
However, I still have the error on the `alter table`.

**Comment by yuanyuan1und1** [comment]
I encountered the same issue.  since the ticket is closed, is there already a solution?

**Comment by nguyenann13** [comment]
Also having this issue using dbt

**Comment by codyfrisby** [comment]
I'm seeing this as well using versions of Trino > 405 but not with 405. For hive tables using S3 for the storage layer. These are not partitioned tables. I have been unable to find a solution to this other than use Trino version <= 405.
