### ISSUE TITLE
Planning time too long when query involves IN predicate over Hive partitioning column

### ISSUE THREAD

**Issue by lzeiming** [trinodb/trino#7015]
We have a hive table with partitioned by columns $part_event, $part_date. And We found the planning time of the following SQL took more than two minutes

```
SELECT ta_date_trunc('day', "#event_time", 1) date_time, COUNT(DISTINCT "#user_id") amount_0
FROM ta_event_116 
where (
        "$part_event" IN
         ('save_role', 'import_project_member', 'get_event_alert_detail', 'edit_condition_cluster', 'fe_explore_enter',
          'fe_explore_search', 'update_dashboard_folder', 'delete_condition_cluster', 'create_user_group',
          'del_dashboard_folder', 'id_cluster_modify', 'edit_result_cluster', 'edit_alert_task', 'time_zone_config',
          'del_user_from_company', 'user_group_search', 'edit_data_power', 'verify_and_binding', 'report_batch_del',
          'search_meta_event', 'create_virtual_event', 'create_dashboard_folder', 'save_event_catalog',
          'create_virtual_dict', 'system_role_manager_func_search', 'share_dashboard', 'edit_project',
          'dashboard_folder_search', 'edit_role', 'report_search', 'edit_member', 'unbinding', 'id_cluster_delete',
          'delete_project', 'down_seq_event_list', 'save_data_power', 'create_dashboard_in_folder', 'del_data_power',
          'delete_member', 'edit_dashboard_report', 'update_user_group', 'bury_manage_info_count',
          'edit_system_alert_contact', 'report_edit', 'prop_analyze_download', 'move_boards_in_folders',
          'eventSearch_download', 'copy_dashboard', 'system_role_manager_member_search', 'save_dashboard',
          'refresh_cluster', 'create_result_cluster', 'fetch_verify_code', 'save_dashboard_reports',
          'create_virtual_prop', 'edit_meta_event', 'manage_reports', 'create_condition_cluster', 'del_event_catalog',
          'model_search', 'member_info_search', 'data_power_detail', 'download_virtual_dict', 'report_del',
          'get_open_query_and_sql', 'data_integration', 'user_search_download', 'delete_result_cluster',
          'upload_virtual_dict', 'delay_set', 'use_event_catalog', 'del_alert_task', 'generate_appkey',
          'dashboard_folder_export', 'del_role', 'project_collect_method', 'id_cluster_add', 'save_member',
          'query_v_event', 'del_virtual_prop', 'del_system_alert_contact', 'save_system_alert_contact',
          'system_alert_contact_detail', 'user_items_save', 'dashbord_search', 'distr_download', 'edit_meta_prop',
          'down_meta_display_name', 'one_alert_task', 'del_virtual_dict', 'up_meta_display_name', 'report_save',
          'id_cluster_down', 'creat_alert_task', 'delete_user_group', 'handover_work_del_member', 'project_info',
          'del_virtual_event', 'dashbord_report_search', 'system_alert_contact_search', 'list_alert_task',
          'data_power_search')
        OR ("$part_event" = 'metric_interface' AND "track_interface_path" = '/dashboard/space-members')
    )
  and ("$part_date" BETWEEN '2020-12-05' AND '2021-02-03')
GROUP BY ta_date_trunc('day', "#event_time", 1);
```

[fg.zip](https://github.com/trinodb/trino/files/6032950/fg.zip)

From the flame graph, I found pushing predicate to table scan took a lot time.

**Comment by findepi** [comment]
Looks like we're spending time in `io/prestosql/sql/planner/iterative/rule/PushPredicateIntoTableScan$LayoutConstraintEvaluator.isCandidate`, in the IN predicate in particular.
@lzeiming you may want to check whether partition list was first filtered by `"$part_date" BETWEEN '2020-12-05' AND '2021-02-03'`.
Then the question is how many partitions match this predicate.

@martint would it be reasonable to consider compiling expressions in `LayoutConstraintEvaluator`? Perhaps not eagerly, maybe after some threshold.

**Comment by martint** [comment]
Maybe, but I think we just need to make the ExpressionInterpreter faster. It's slow for no good reason (something regressed years ago), and there are many opportunities to speed that up. For context, in the beginning, the interpreter was *all* we had, and performance was not horrible.

**Comment by findepi** [comment]
The low hanging fruit is resolve operator once for the IN predicate. Let me screen capture the relevant part of the flame below.

@lzeiming do you want to give it a try?
Ideally we should have a `Benchmark*` class for `ExpressionInterpreter`. 

![image](https://user-images.githubusercontent.com/144328/109027123-bfe22780-76c0-11eb-8b17-703fb6ddd94b.png)

**Comment by lzeiming** [comment]
> Looks like we're spending time in `io/prestosql/sql/planner/iterative/rule/PushPredicateIntoTableScan$LayoutConstraintEvaluator.isCandidate`, in the IN predicate in particular.
> @lzeiming you may want to check whether partition list was first filtered by `"$part_date" BETWEEN '2020-12-05' AND '2021-02-03'`.
> Then the question is how many partitions match this predicate.
> 
> @martint would it be reasonable to consider compiling expressions in `LayoutConstraintEvaluator`? Perhaps not eagerly, maybe after some threshold.

**Comment by lzeiming** [comment]
> Looks like we're spending time in `io/prestosql/sql/planner/iterative/rule/PushPredicateIntoTableScan$LayoutConstraintEvaluator.isCandidate`, in the IN predicate in particular.
> @lzeiming you may want to check whether partition list was first filtered by `"$part_date" BETWEEN '2020-12-05' AND '2021-02-03'`.
> Then the question is how many partitions match this predicate.
> 
The Partition list was first filtered by "$part_date" BETWEEN '2020-12-05' AND '2021-02-03'.
Because when I widen the range, the planning time increases, when I narrow the range, the planning time decreases.

There are About 6000 partitions in the example.

**Comment by lzeiming** [comment]
> The low hanging fruit is resolve operator once for the IN predicate. Let me screen capture the relevant part of the flame below.
> 
> @lzeiming do you want to give it a try?
> Ideally we should have a `Benchmark*` class for `ExpressionInterpreter`.
> 
> ![image](https://user-images.githubusercontent.com/144328/109027123-bfe22780-76c0-11eb-8b17-703fb6ddd94b.png)

@findepi 
MetadataManager.resolveOperator is invoked with same arguments for a large number of times.
How about caching the its return value?

**Comment by findepi** [comment]
> MetadataManager.resolveOperator is invoked with same arguments for a large number of times.
How about caching its return value?

"Caching" may mean different things to different people.

We should change the code here https://github.com/trinodb/trino/blob/8fb4a95ab491d91dc82f9a566eaa519ddbc2097a/core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java#L621
so that the operator is resolved once.
Plus, add a benchmark class.
