### ISSUE TITLE
log config max-history of http client not work

### ISSUE THREAD

**Issue by gjhkael** [trinodb/trino#7018]
My config is below, max history set to exchange http client log.
```
#exchange
exchange.http-client.log.enabled=true
exchange.http-client.log.max-size=100MB
exchange.http-client.log.max-history=2
exchange.http-client.log.compression.enabled=false
```
But the old log file is not deleted.
![image](https://user-images.githubusercontent.com/10809317/108977014-15b7cf00-76c3-11eb-8e39-df30a4ceda16.png)

**Comment by findepi** [comment]
Thanks for reporting this.
The HTTP Client code is in Airlift, the logging is configured here:
https://github.com/airlift/airlift/blob/ceff7c002aa0ffd548432718f09e0a90f618cbdd/http-client/src/main/java/io/airlift/http/client/jetty/DefaultHttpClientLogger.java#L61-L72

i think we need to apply a similar change there as in the HTTP Server logging
https://github.com/airlift/airlift/commit/b6ce4e490a76c6d230d414cf410baabd18c541e7

@gjhkael do you want to make a PR?

**Comment by gjhkael** [comment]
@findepi Ok.

**Comment by findepi** [comment]
Fixed by https://github.com/airlift/airlift/pull/896
Will be fixed here when we update to airbase 203, but let me close the ticket now, as no work to be done.
