### ISSUE TITLE
Use smoke test for TestGlobalTransactionMySqlConnectorTest

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#7019]

**Comment by findepi** [comment]
The original title was: "Define smoke test classes for connectors" and it's worth keeping.
I wouldn't want to manage this just for MySQL connector. 

Perhaps, we could make `BaseConnectorTest` work in a smoke fashion, where it skips certain methods, or finishes certain tests early when in "smoke mode".

cc @kokosing

**Comment by losipiuk** [comment]
> The original title was: "Define smoke test classes for connectors" and it's worth keeping.
> I wouldn't want to manage this just for MySQL connector.

Yeah possibly. But having more granular issues allows for having more targetted `TODO(issue)` comments. Do we want to have both?

**Comment by findepi** [comment]
Done in https://github.com/trinodb/trino/pull/7155
