### ISSUE TITLE
Disable char/varchar TopN pushdown for case insensitive databases and PostgreSQL

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#7031]
- Do not push TopN where `CASE_INSENSITIVE_CHARACTER_PUSHDOWN` is used.
  - Also, do not push TopN for char/varchar in PostgreSQL due to different default collation (see `io.trino.plugin.postgresql.TestPostgreSqlConnectorTest#testCaseSensitiveDataMapping`).

- `supportsTopN` should  be required when `topNFunction` is present

Once done, we should enable TopN by default

**Comment by hashhar** [comment]
Should this be kept open since we haven't enabled it by default and aren't forcing connectors to define `supportsTopN` if `topNFunction` is defined?

**Comment by findepi** [comment]
I worded the issue more boradly, but we haven't added support for topN elsewhere, so nothing remaining here.... maybe except making the TopN test reusable.
