### ISSUE TITLE
Integration with zeppelin-jdbc error

### ISSUE THREAD

**Issue by PChou** [trinodb/trino#7070]
I tried to use trino as the sql engine, integrated into Zeppelin, Zeppelin supports jdbc. After trino-jdbc-352 is integrated into Zeppelin, query error:

```
INFO [2021-02-27 17:24:05,947] ({ParallelScheduler-Worker-2} JDBCInterpreter.java[createConnectionPool]:449) - Creating connection pool for url: jdbc:trino://192.168.31.54:28081, user: anonymous, dbPrefix: default, properties: {statementPrecode=, precode=, user=test, url=jdbc:trino://192.168.31.54:28081, password=, completer.ttlInSeconds=120, driver=io.trino.jdbc.TrinoDriver, completer.schemaFilters=}
ERROR [2021-02-27 17:24:05,950] ({ParallelScheduler-Worker-2} JDBCInterpreter.java[executeSql]:700) - Fail to getConnection
java.sql.SQLException: Unrecognized connection property 'url'
        at io.trino.jdbc.TrinoDriverUri.validateConnectionProperties(TrinoDriverUri.java:460)
        at io.trino.jdbc.TrinoDriverUri.<init>(TrinoDriverUri.java:128)
        at io.trino.jdbc.TrinoDriverUri.<init>(TrinoDriverUri.java:118)
        at io.trino.jdbc.TrinoDriverUri.create(TrinoDriverUri.java:139)
        at io.trino.jdbc.TrinoDriver.connect(TrinoDriver.java:81)
...
```

Through the trino code, it can be found that the properties of `url` are not in the legal properties, so the verification went wrong. I tried to comment out the following lines, and it works:

io.trino.jdbc.TrinoDriverUri
```java
// for (String propertyName: connectionProperties.stringPropertyNames()) {
// if (ConnectionProperties.forKey(propertyName) == null) {
// throw new SQLException(format("Unrecognized connection property'%s'", propertyName));
//}
//}
```

Is it necessary to check the unknown parameters?

**Comment by findepi** [comment]
This is the same as https://issues.apache.org/jira/browse/ZEPPELIN-2891 but for Trino.
I don't know how that issue was solved, but can you please file a new issue for Zeppelin project and link it here?

**Comment by PChou** [comment]
@findepi When Zeppelin created the jdbc connection,  it use the whitelist to filter the properties that Presto did not recognize as soon as it encountered the Presto driver class:

org.apache.zeppelin.jdbc.JDBCInterpreter

```
private static final Set<String> PRESTO_PROPERTIES = new HashSet<>(Arrays.asList(
          "user", "password",
          "socksProxy", "httpProxy", "clientTags", "applicationNamePrefix", "accessToken",
          "SSL", "SSLKeyStorePath", "SSLKeyStorePassword", "SSLTrustStorePath",
          "SSLTrustStorePassword", "KerberosRemoteServiceName", "KerberosPrincipal",
          "KerberosUseCanonicalHostname", "KerberosServicePrincipalPattern",
          "KerberosConfigPath", "KerberosKeytabPath", "KerberosCredentialCachePath",
          "extraCredentials", "roles", "sessionProperties"));


String driverClass = properties.getProperty(DRIVER_KEY);
if (driverClass != null && (driverClass.equals("com.facebook.presto.jdbc.PrestoDriver")
        || driverClass.equals("io.prestosql.jdbc.PrestoDriver"))) {
  // Only add valid properties otherwise presto won't work.
  for (String key : properties.stringPropertyNames()) {
    if (!PRESTO_PROPERTIES.contains(key)) {
      properties.remove(key);
    }
  }
}
```

To be honest, I don't think it is necessary to verify the legality of the properties. Compatibility may be more important than preventing typos. This is more conducive to trino popularization.

WDYT?

**Comment by findepi** [comment]
> To be honest, I don't think it is necessary to verify the legality of the properties.

In this project we take quite strict approach to configuration properties and so far it served as well, with Zeppelin integration being about the only place where end user has a problem.

To be honest, I do not see a reason why Zeppelin would want to send "random" properties to the JDBC Driver.
For example, they could be ignored today and gain some new meaning in the future, leading to problems for users.

The fact that I do not understand the design, does not mean it is unsound or wrong. I am not familiar enough with Zeppelin to judge that.
However this just is not yet a compelling argument to change on our side.

Let me close the issue, as there is nothing we can (or plan to) do on our side.
Fortunately in Zeppelin it should be easy to apply same logic for the Trino Driver as they determined necessary to Presto SQL or old Presto drivers.
We can continue conversation here, or on `#troubleshooting` channel on [our slack](https://trino.io/slack.html).
