### ISSUE TITLE
Exclude "default" and CDH5 product tests from PR builds

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#7076]
Run them on branch `push`, and also when a `tests:all` or `tests:hive` label is present.

This is to keep build queue shorter.

**Comment by findepi** [comment]
While it's natural to exclude HDP3 instead of default, the HDP3 builds give coverage for transactional tables and may still run faster due to Tez.

Let's run HDP3 in PRs.

**Comment by kokosing** [comment]
CDH5 is going to die soon. HDP3 is also going to die but a bit later. See https://www.cloudera.com/legal/policies/support-lifecycle-policy.html

**Comment by findepi** [comment]
> CDH5 is going to die soon. HDP3 is also going to die but a bit later. See https://www.cloudera.com/legal/policies/support-lifecycle-policy.html

Let's consider this orthogonal.

**Comment by findinpath** [comment]
@findepi is this issue still relevant?

**Comment by findepi** [comment]
probably done in https://github.com/trinodb/trino/pull/7221
