### ISSUE TITLE
Migrate Iceberg tests to use BaseConnectorTest

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#7107]
https://github.com/trinodb/trino/pull/6989 introduced new `BaseConnectorTest` test class which replaces `AbstractTestDistributedQueries` and `AbstractTestIntegrationSmokeTest`.

Scope of this ticket is to restructure Iceberg test code to follow new pattern.
`AbstractTestIcebergSmoke` should be merged with `TestIcebergDistributed` to form `BaseTestIcebergConnectorTest`
Then on top of that we should create  `TestIcebergOrcConnectorTest` `TestIcebergParquetConnectorTest` (removing `TestIcebergOrcSmoke` and `TestIcebergParquetSmoke`)

Please ensure that `BaseTestIcebergTest` is created as a rename of `AbstractTestIcebergSmoke` so we keep as much Git history as possible.

A PR which restructures MySQL tests is a good reference:  https://github.com/trinodb/trino/pull/7011

**Comment by xuboqing** [comment]
Interesting issue, I wanna have a try. Could you please assign me to solve it?

**Comment by losipiuk** [comment]
Thanks @xuboqing . Assigned.

**Comment by xuboqing** [comment]
Still working on it. Please give me some time.

**Comment by losipiuk** [comment]
Fixed via https://github.com/trinodb/trino/pull/8065

**Comment by losipiuk** [comment]
@wendigo please reopen if there is remaining work here
