### ISSUE TITLE
Migrate Kudu tests to use BaseConnectorTest

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#7108]
https://github.com/trinodb/trino/pull/6989 introduced new `BaseConnectorTest` test class which replaces `AbstractTestDistributedQueries` and `AbstractTestIntegrationSmokeTest`.

Scope of this ticket is to restructure Kudu test code to follow new pattern.
`AbstractKuduIntegrationSmokeTest` should be merged with `TestKuduDistributedQueries` to form `BaseKuduConnectorTest`
Then on top of that we should create  `TestKuduWithDisabledInferSchemaConnectorTest`, `TestKuduWithEmptyInferSchemaConnectorTest`, `TestKuduWithStandardInferSchemaConnectorTest` (removing `TestKuduSmoke*`)

Please ensure that `BaseKuduConnectorTest` is created as a rename of `AbstractKuduIntegrationSmokeTest` so we keep as much Git history as possible.

A PR which restructures MySQL tests is a good reference:  https://github.com/trinodb/trino/pull/7011

**Comment by KimHyoJin** [comment]
Hi, I am interested in this issue. May I try to work on this?

**Comment by losipiuk** [comment]
Thanks @KimHyoJin . Go for it.
