### ISSUE TITLE
Migrate BigQuery tests to use BaseConnectorTest

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#7110]
https://github.com/trinodb/trino/pull/6989 introduced new `BaseConnectorTest` test class which replaces `AbstractTestDistributedQueries` and `AbstractTestIntegrationSmokeTest`.

Scope of this ticket is to restructure BigQuery test code to follow new pattern.
`TestBigQueryIntegrationSmokeTest` should be renamed to `TestBigQueryConnectorTest` and extend `BaseConnectorTest` instead of `AbstractTestIntegrationSmokeTest`

A PR which restructures MySQL tests is a good reference:  https://github.com/trinodb/trino/pull/7011

**Comment by xiangzK** [comment]
Hi, I'm interested in this issue, could you please assign me to solve this problem?

**Comment by losipiuk** [comment]
Thanks @xiangzK

**Comment by ebyhr** [comment]
This issue might not be `good first issue` at this time. The current BigQuery connector supports CREATE TABLE, but it doesn't support `CREATE TABLE AS SELECT` & `INSERT`. Some of the skipping logic in `AbstractTestDistributedQueries` seem wrong, so we can't migrate it unless fixing those tests. 

```java
    @Test
    public void testRenameTable()
    {
        skipTestUnless(supportsCreateTable());
        String tableName = "test_rename_" + randomTableSuffix();
        assertUpdate("CREATE TABLE " + tableName + " AS SELECT 123 x", 1); // CTAS (not CREATE TABLE)
```
