### ISSUE TITLE
Migrate Cassandra tests to use BaseConnectorTest

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#7111]
https://github.com/trinodb/trino/pull/6989 introduced new `BaseConnectorTest` test class which replaces `AbstractTestDistributedQueries` and `AbstractTestIntegrationSmokeTest`.

Scope of this ticket is to restructure Cassandra test code to follow new pattern.
`TestCassandraIntegrationSmokeTest` should be merged with `BaseCassandraDistributedQueries` to form `BaseTestCassandraConnectorTest`
Then on top of that we should create  `TestCassandraConnectorTest` and `TestCassandraLatestConnectorTest` (removing `TestCassandraDistributedQueries` and `TestCassandraDistributedQueriesLatest`)

Please ensure that `BaseTestCassandraConnectorTest` is created as a rename of `TestCassandraIntegrationSmokeTest` so we keep as much Git history as possible.

A PR which restructures MySQL tests is a good reference:  https://github.com/trinodb/trino/pull/7011

**Comment by manan9299** [comment]
@losipiuk Can I work on this issue? I am new here and would love to give this a try. Could you please assign this issue to me?

**Comment by findepi** [comment]
@manan9299 sure, go for it!

**Comment by findinpath** [comment]
I have already experience with refactoring to `BaseConnectorTest` and I'm also familiar with Cassandra. I think I could provide in a day or two a working PR for this issue. Can I be assigned on this one?

**Comment by findepi** [comment]
@findinpath  let's ask @manan9299 whether they are actually working on this

@manan9299 ?

**Comment by manan9299** [comment]
@findinpath sure, go ahead. I got caught up in something else and couldn't find the time to work on this issue.
