### ISSUE TITLE
Migrate Hive tests to use BaseConnectorTest

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#7113]
https://github.com/trinodb/trino/pull/6989 introduced new `BaseConnectorTest` test class which replaces `AbstractTestDistributedQueries` and `AbstractTestIntegrationSmokeTest`.

Scope of this ticket is to restructure Hive test code to follow new pattern.
`TestHiveIntegrationSmokeTest` should be merged  with  `TestHiveDistributedQueries` to form `TestHiveConnectorTest`

Please ensure that `TestHiveConnectorTest` is created as a rename of `TestHiveIntegrationSmokeTest` so we keep as much Git history as possible.

A PR which restructures MySQL tests is a good reference:  https://github.com/trinodb/trino/pull/7011

**Comment by MariyaR** [comment]
Hi, 
may I try to work on this?

**Comment by findepi** [comment]
sure, go for it!

**Comment by xuboqing** [comment]
I wanna have a try and maybe finish it in two days, could you please assign this to me?

**Comment by losipiuk** [comment]
@MariyaR are you still working on this one?

**Comment by MariyaR** [comment]
@losipiuk no, I am sorry, I am very limited in time these days

**Comment by losipiuk** [comment]
> @losipiuk no, I am sorry, I am very limited in time these days

No worries :) @xuboqing feel free to give it a try :)
