### ISSUE TITLE
Migrate Kafka tests to use BaseConnectorTest

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#7114]
https://github.com/trinodb/trino/pull/6989 introduced new `BaseConnectorTest` test class which replaces `AbstractTestDistributedQueries` and `AbstractTestIntegrationSmokeTest`.

Scope of this ticket is to restructure Kafka test code to follow new pattern.
`TestKafkaIntegrationSmokeTest` should be renamed to `TestKafkaConnectorTest` and extend `BaseConnectorTest` instead of `AbstractTestIntegrationSmokeTest`

A PR which restructures MySQL tests is a good reference:  https://github.com/trinodb/trino/pull/7011

**Comment by Alicewillbe** [comment]
I'm tracking this issue for a while and it is still assigned to no one. May I take this issue?

**Comment by losipiuk** [comment]
Sure, thankw !

**Comment by findepi** [comment]
@Alicewillbe sure, go for it, thanks!

See https://github.com/trinodb/trino/pull/7182 as it changes something around Kafka tests, but hopefully shouldn't conflict

**Comment by Alicewillbe** [comment]
@findepi @losipiuk Thanks for supporting!
I agree that no conflict should happen between #7182 and this one, from the perspective of simple refactoring.
Just in case, should I wait until #7182 merged?

**Comment by losipiuk** [comment]
> @findepi @losipiuk Thanks for supporting!
> I agree that no conflict should happen between #7182 and this one, from the perspective of simple refactoring.
> Just in case, should I wait until #7182 merged?

No need IMO. Feel free to attack it already.

**Comment by losipiuk** [comment]
Dropped good-first-issue as the problem here is not that easy to solve due to the fact that Kafka is currently not covered with tests based on `AbstractDistributedTestQueries`. See #7185 for more info.
