### ISSUE TITLE
Migrate Raptor tests to use BaseConnectorTest

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#7116]
https://github.com/trinodb/trino/pull/6989 introduced new `BaseConnectorTest` test class which replaces `AbstractTestDistributedQueries` and `AbstractTestIntegrationSmokeTest`.

Scope of this ticket is to restructure Raptor test code to follow new pattern.
`TestRaptorIntegrationSmokeTest` should be merged with `TestRaptorDistributedQueries` as `BaseRaptorConnectorTest` and extend `BaseConnectorTest`.
On top of that we should create:
* `TestRaptorConnectorTest` (setup like `TestRaptorDistributedQueries`+ `TestRaptorIntegrationSmokeTest`)
* `TestRaptorBucketedConnectorTest`) (setup like `TestRaptorDistributedQueriesBucketed` + `TestRaptorIntegrationSmokeTestBucketed`)
* `TestRaptorMysqlConnectorTest`) (setup like `TestRaptorIntegrationSmokeTestMySql`)

Please ensure that `BaseRaptorConnectorTest` is created as a rename of `TestRaptorIntegrationSmokeTest` so we keep as much Git history as possible.

A PR which restructures MySQL tests is a good reference:  https://github.com/trinodb/trino/pull/7011

**Comment by MirrorChu** [comment]
Hi there!I'm willing to take this issue,may I be the assignee of it?

**Comment by losipiuk** [comment]
Thanks @MirrorChu . Assigned.

**Comment by MirrorChu** [comment]
Sorry for being absent, I am going to work on this issue now.
