### ISSUE TITLE
Migrate Thrift connector tests to use BaseConnectorTest

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#7117]
https://github.com/trinodb/trino/pull/6989 introduced new `BaseConnectorTest` test class which replaces `AbstractTestDistributedQueries` and `AbstractTestIntegrationSmokeTest`.

Scope of this ticket is to restructure Thrift connector test code to follow new pattern.
`TestThriftIntegrationSmokeTest` should be merged  with  `TestThriftDistributedQueries` to form `TestThriftConnectorTest`

A PR which restructures MySQL tests is a good reference:  https://github.com/trinodb/trino/pull/7011

**Comment by maheshsv** [comment]
I can take this issue please assign to me

**Comment by xuboqing** [comment]
Can I have a try? I am willing to fix it in two days maybe, could you please assign it to me?

**Comment by hashhar** [comment]
@maheshsv Are you still working on this? If not, is it okay for @xubo245 to pick this up?

**Comment by xubo245** [comment]
@hashhar  Why is me？ are there any mistakes？

**Comment by hashhar** [comment]
Thanks @xubo245 . I meant to tag @xuboqing instead.

**Comment by HiLany** [comment]
Why isn't this PR merged? [7975](https://github.com/trinodb/trino/pull/7975). 

Can I go ahead and do it?
