### ISSUE TITLE
trino-cli add prompt color option

### ISSUE THREAD

**Issue by wgzhao** [trinodb/trino#7147]
Currently the prompt of `trinio-cli` is dark style, which appears transparent or even unreadable in a dark-themed terminal:

![image](https://user-images.githubusercontent.com/1001616/109931674-16281980-7d04-11eb-954d-65f6f7172054.png)

![image](https://user-images.githubusercontent.com/1001616/109931917-761ec000-7d04-11eb-9853-397188638181.png)

two methods:
1. Add `--no--color` toggle, when it enabled, the trino-cli prompt turned off highlighting
2. Add `--color <color>` option, allow user specify custom prompt color.

**Comment by hashhar** [comment]
Can this be considered a duplicate of https://github.com/trinodb/trino/issues/6190 and https://github.com/trinodb/trino/issues/2187?

**Comment by wgzhao** [comment]
@hashhar Yes, I had the same problem with #6190

**Comment by hashhar** [comment]
Closing as duplicate of #6190.
