### ISSUE TITLE
Document CREATE VIEW is not supported in connectors

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#7150]
For example https://trino.io/docs/current/connector/mysql.html#limitations lists a number of limitations, but CREATE VIEW is not on the list.

**Comment by mosabua** [comment]
This should go in the new SQL support - DDL section we plan to add to all connectors.

**Comment by heroygt** [comment]
> This should go in the new SQL support - DDL section we plan to add to all connectors.

+1

**Comment by mosabua** [comment]
This is done at this stage. Are you missing that info anywhere @heroygt ?
