### ISSUE TITLE
Add Timezone parameter in JDBC URI

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#7158]
JDBC driver connection string should accept parameter such as ```?timeZoneId=<TIMEZONE> ie ?timeZoneId=<UTC> or ?timeZoneId=<America/Chicago>``` so that queries return timestamps according to the timezone of the parameter. This should override java -D system property (if that is supplied).

original ask from slack: "Is there a way to set the timezone in the JDBC driver in the URI (i.e. not programmatically)? I know setTimeZoneId exists, but don’t see a way to do it from the URI (since it’s not a session property)"

**Comment by findepi** [comment]
@tooptoop4 would you mind rephrasing the issue description?
it's currently a copy-paste from slack and it's unclear what's being requested.

thanks

**Comment by findepi** [comment]
cc @martint @electrum @losipiuk

**Comment by Shashikant-Jaiswal** [comment]
Submitted a pull request https://github.com/trinodb/trino/pull/7252 for this issue.

**Comment by hashhar** [comment]
was implemented in https://github.com/trinodb/trino/pull/19102
