### ISSUE TITLE
We had support most hive sql syntax, is it possible to commit to trino? 

### ISSUE THREAD

**Issue by ImTangYun** [trinodb/trino#7167]
see [https://github.com/trinodb/trino/issues/6857](https://github.com/trinodb/trino/issues/6857)

**Comment by ebyhr** [comment]
Hi, please don't create duplicated tickets. Let me close this one.

**Comment by ImTangYun** [comment]
> Hi, please don't create duplicated tickets. Let me close this one.
> Also, I would invite you join the community Slack. https://trino.io/slack.html

ok thanks
