### ISSUE TITLE
Allow connectors to control TopN pushdown based on data-type of the sort keys

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#7177]
Some databases' default sort order differs from that of Trino due to collation differences.
For such databases TopN pushdown causes incorrect results when the sort keys include a column which has a collation-aware data-type (e.g. most textual types).

Some databases allow specifying custom collations for functions and operators (e.g. [Postgres](https://www.postgresql.org/docs/13/collation.html)).

We should make enough information available to the connector so that it can decide to use non-default collations when pushing down TopN for a textual datatype. Currently `topNFunction` received a `List<SortItem>` and `limit` which is missing the data types of the columns so this cannot be implemented yet.

Note that in the case of Postgres it only allows `COLLATE` to be used with types that support collation (`text`, `varchar`, `char`) so knowing the Trino `Type` is not enough to make this decision because e.g. `enum` from Postgres also looks like `VarcharType` to Trino.

**Comment by hashhar** [comment]
A possible solution is to also send `JbdcColumnHandle` for the sort items to `topNFunction` at https://github.com/trinodb/trino/blob/master/plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java#L504 (`applyQueryTransformations`).
The challenge is that by the time that function is called the `tableHandle` refers to the transformed result.

This means that for queries of the form `SELECT a_bigint FROM table ORDER BY a_string LIMIT 100` the `tableHandle` has only `a_bigint` present as the column handle while `sortItems` has `a_string` so we cannot find the data-type of `a_string`.

A possible cause is the check at https://github.com/trinodb/trino/blob/master/plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadata.java#L354-L356. The `handle` at this point includes all the information about the base table.
It seems that `flushAttributesAsQuery` is never called from there which would eventually reach `applyQueryTransformations` allowing us to inspect the data-type of all columns.

This was discovered while implementing https://github.com/trinodb/trino/pull/7170.

**Comment by findepi** [comment]
We should replace `SortItem` with a "`JdbcSortItem`" that will capture the column handle.
This will simplify handling today, and also make sure the column handle information isn't removed by subsequent `applyProjection`.

**Comment by hashhar** [comment]
Fixed via https://github.com/trinodb/trino/pull/7436.
