### ISSUE TITLE
select count(1) is so slowly

### ISSUE THREAD

**Issue by yangyongyongyong** [trinodb/trino#7188]
```
select count(sn) from bps.tmp;
```

900000 rows
6000 columns

need 3.53m
data 13.5G

**Comment by ebyhr** [comment]
@yangyongyongyong  Could you share more detailed information (connector, file format, number of workers and so on)?

**Comment by ebyhr** [comment]
Going to close this issue since there is no response for a while. Please feel free to ask in the community Slack. https://trino.io/community.html
