### ISSUE TITLE
Support views in Pinot Connector

### ISSUE THREAD

**Issue by huukhuongnguyen** [trinodb/trino#7203]
Caused by: io.trino.spi.TrinoException: This connector does not support creating views **with pinot**

**Comment by kokosing** [comment]
Do you mean to support Pinot views in Trino, so you can read from them using Trino?
Or do you mean to support Trino views stored in Pinot, so you can create a view in Trino that can access other Trino catalogs? I am not sure if it is doable.

**Comment by huukhuongnguyen** [comment]
> Do you mean to support Pinot views in Trino, so you can read from them using Trino?
> Or do you mean to support Trino views stored in Pinot, so you can create a view in Trino that can access other Trino catalogs? I am not sure if it is doable.

i'm using SQL statement syntax https://trino.io/docs/current/sql/create-view.html and it's not support for Pinot connector

**Comment by ebyhr** [comment]
@huukhuongnguyen Let me close this issue as Pinot doesn't support views and I don't think we can support the statement in the connector. Please feel free to join Trino community Slack. https://trino.io/slack.html
