### ISSUE TITLE
Iceberg: Apply row-level delete when reading

### ISSUE THREAD

**Issue by jshmchenxi** [trinodb/trino#7226]
Iceberg now supports row-level delete, but Trino does not apply row-level delete when read iceberg tables.
#7049 is required for this feature.

Some issues in Iceberg for reference:
apache/iceberg#1352 Data: Support row-level deletes with IcebergGenerics
apache/iceberg#1444 Spark: Apply row-level delete files when reading
apache/iceberg#1497 MR: Apply row-level delete files when reading
apache/iceberg#1517 Flink: Apply row-level deletes when reading

**Comment by jshmchenxi** [comment]
Spark/Flink support this row-level delete reading feature by invoking DeleteFilter.filter() to record rows. This requires the engine to support dealing with data by row. However, Trino reads Iceberg data and converts to a Block[]. So I found it difficult to apply the DeleteFilter to Trino to support this feature.

**Comment by jshmchenxi** [comment]
@electrum @phd3  Hello! What do you think of this issue? I wonder if there is a way to achieve this feature?

**Comment by electrum** [comment]
@jshmchenxi We definitely want to support this, along with performing row-level deletes via `DELETE`, `UPDATE`, and `MERGE` as well. The Iceberg specification says v2 is incomplete, so we haven't prioritized working this.

**Comment by jshmchenxi** [comment]
@electrum Thanks for the reply and look forward to the feature!

**Comment by velctor** [comment]
I am more interested in this. Based on this PR - https://github.com/trinodb/trino/pull/8534, some bugs have been fixed and optimized. Trino read row level delete function has been basically implemented. But when reading a large table, an error will be reported _Failed to open Parquet file_ or _stream is closed_.

**Comment by hankfanchiu** [comment]
@electrum, could we consider prioritizing this feature, now that Iceberg's v2 spec is in?

**Comment by alexjo2144** [comment]
Released in 376: https://github.com/trinodb/trino/pull/11642
