### ISSUE TITLE
Support HIVE VIEW with LATERAL VIEW json_tuple AS ...

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#7242]
Currently Coral lacks support of the `LATERAL VIEW json_tuple` which is a Hive syntax leveraging `json_tuple` UDTF.

The main difference between `json_tuple` and other UDTFs like `explode` is that `json_tuple` is column generating function (in contrast to `explode` which is a row generating function).

`json_tuple` has following signature in Hive:

```
json_tuple(string jsonStr,string k1,...,string kn)
```

Where `jsonStr` is a string or column reference (of string type) holding serialized JSON object. `k1, ..., kn` are field names that are being extracted from `jsonStr` JSON object. So having `jsonStr`:

```
{"user_id": 1000, "name": "Mateusz", "surname": "Gajewski"}
```

`SELECT json_tuple(jsonStr, "name", "surname", "user_id")`

will return a tuple (this Hive concept is weird tbh):

```
"1000", "Mateusz", "Gajewski"
```

and by default, those columns are having automatically generated names (`c0`, `c1`,...).

Hive allows to name those columns which Coral doesn't handle as well:

```
SELECT json_tuple(jsonStr, "name", "surname", "user_id") as (name, surname, user_id)
```

And finally:

Hive's:

```
SELECT v.col, v.col2 FROM json_test t 
  LATERAL VIEW json_tuple(t.col, 'field', 'field2') v as col, col2
```

should be translated to Trino's/Presto's query (or similar shape):

```
SELECT v.field AS col, v.field2 AS col2 from json_test t 
  CROSS JOIN LATERAL (
    SELECT cast(json_parse(t.col) as ROW(field varchar, field2 varchar)) as v
  );
```

Please note that due to Hive's `AS` clause it's possible to extract `field` from JSON as column `col`.

Also reported in Coral: https://github.com/linkedin/coral/issues/53

**Comment by findepi** [comment]
Let me take some notes about the `json_tuple` behavior.
All Hive queries run on HDP3 environment, with the following setup

```
CREATE TABLE t(jsonstr string);
INSERT INTO t VALUES ('{"user_id": 1000, "name": "Mateusz", "surname": "Gajewski"}');
```


## Unalias case

```
SELECT * FROM t AS t LATERAL VIEW json_tuple(jsonstr, "name", "surname", "user_id") x;

+----------------------------------------------------+----------+-----------+-------+
|                     t.jsonstr                      |   x.c0   |   x.c1    | x.c2  |
+----------------------------------------------------+----------+-----------+-------+
| {"user_id": 1000, "name": "Mateusz", "surname": "Gajewski"} | Mateusz  | Gajewski  | 1000  |
+----------------------------------------------------+----------+-----------+-------+
```

This introduces a relation `x` with fields `c0`, `c1` and `c2`.
As with any relation, the fields can be accssed using qualified or unqualified
names:

```
SELECT c0, x.c1 FROM t AS t LATERAL VIEW json_tuple(jsonstr, "name", "surname", "user_id") x;

+----------+-----------+
|    c0    |   x.c1    |
+----------+-----------+
| Mateusz  | Gajewski  |
+----------+-----------+
```

The unaliased case is easy to support -- we know number of columns statically,
so we can enumerate `c0, c1, ...` and fold that into the aliased case below.
This is not needed to be covered in the first iteration, from my perspective.

## Aliased case

```
SELECT * FROM t AS t LATERAL VIEW json_tuple(jsonstr, "name", "surname", "user_id") x AS a, b, c;

+----------------------------------------------------+----------+-----------+-------+
|                     t.jsonstr                      |   x.a    |    x.b    |  x.c  |
+----------------------------------------------------+----------+-----------+-------+
| {"user_id": 1000, "name": "Mateusz", "surname": "Gajewski"} | Mateusz  | Gajewski  | 1000  |
+----------------------------------------------------+----------+-----------+-------+
```

This introduces a relation `x` with fields `a`, `b` and `c`.

## Types

`json_tuple` takes JSON as a `string`, and field names as `string` values. It
returns `string` values as a result, regardless of JSON type.

## Edge cases

### Missing

`NULL` is returned for a missing entry

```
SELECT * FROM t AS t LATERAL VIEW json_tuple(jsonstr, "name", "xxx") x AS a, b;

+----------------------------------------------------+----------+-------+
|                     t.jsonstr                      |   x.a    |  x.b  |
+----------------------------------------------------+----------+-------+
| {"user_id": 1000, "name": "Mateusz", "surname": "Gajewski"} | Mateusz  | NULL  |
+----------------------------------------------------+----------+-------+
```

### Array or Struct

```
INSERT INTO t VALUES ('{"name": ["an array"]}');
INSERT INTO t VALUES ('{"name": {"some": "json object"]}');
SELECT * FROM t AS t LATERAL VIEW json_tuple(jsonstr, "name", "user_id") x AS a, b;

+----------------------------------------------------+---------------+-------+
|                     t.jsonstr                      |      x.a      |  x.b  |
+----------------------------------------------------+---------------+-------+
...
| {"name": ["an array"]}                             | ["an array"]  | NULL  |
| {"name": {"some": "json object"]}                  | NULL          | NULL  |
+----------------------------------------------------+---------------+-------+
```

An array was converted into a string representation.
An object was ignored.

### Key case sensitivity.

JSON keys are treated case sensitively. 

### Nested fields

Nested keys like `"name.some"` or `"$.name.some"` are ignored and return
`NULL` values. 


## Mapping

In Trino, the aliased case can be mapped as below.

```
hive> SELECT * FROM t AS t LATERAL VIEW json_tuple(jsonstr, "name", "user_id") x AS a, b;

+----------------------------------------------------+---------------+-------+
|                     t.jsonstr                      |      x.a      |  x.b  |
+----------------------------------------------------+---------------+-------+
| {"user_id": 1000, "name": "Mateusz", "surname": "Gajewski"} | Mateusz       | 1000  |
+----------------------------------------------------+---------------+-------+
```

```
trino> SELECT * FROM t CROSS JOIN UNNEST(ARRAY[ROW(json_extract_scalar(jsonstr, '$.name'), json_extract_scalar(jsonstr, '$.user_id'))]) x(a, b);
                           jsonstr                           |    a    |  b
-------------------------------------------------------------+---------+------
 {"user_id": 1000, "name": "Mateusz", "surname": "Gajewski"} | Mateusz | 1000

```

Note that this has the following limitations:

- does not work with arrays (incorrectly ignores arrays, where Hive returns
  them using some "toString" representation)
- does not discern between top-level and nested fields, so nested fields are
  not getting correctly ignored

The limitations are, from my perspective, acceptable for the initial support.

**Comment by Hemantratera** [comment]
I was trying to use LATERAL VIEW json_tuple in pyspark , but i got a problem , I have key (Header_list) and its value as string which is of length 3004 character, but when I am reading it through JSON tuple and printing the value in dataframe it only gives 2913 length string , last few characters are truncated by default, So i wanted to know whether there is some default limit on length of string value in json using json_tuple, and if we can change that default.
