### ISSUE TITLE
Looking for Snowflake & Druid Connector

### ISSUE THREAD

**Issue by kalyansworld** [trinodb/trino#7247]
I understand druid connector already there, which doesn't support case sensitivity. Also looking for snowflake connector.

**Comment by hashhar** [comment]
For Druid case-sensitivity issues take a look at the ongoing work in https://github.com/trinodb/trino/pull/7197

**Comment by findepi** [comment]
For Snowflake connector, see https://github.com/trinodb/trino/pull/2551

**Comment by findepi** [comment]
I will close this as answered.
We can continue conversation here, or on [our slack](https://trino.io/slack.html).
See you there!
