### ISSUE TITLE
Trino architecture and use of Spark

### ISSUE THREAD

**Issue by ppKrauss** [trinodb/trino#7267]
Trino is a kind of  [Federated Database Systems](https://en.wikipedia.org/wiki/Federated_database_system), which transparently maps multiple autonomous database systems  into a single "federated database" (and an alternative SQL language to query it)... This old article (of 2016), "[Virtual Integration of Hadoop with External Systems](https://community.cloudera.com/t5/Community-Articles/Virtual-Integration-of-Hadoop-with-External-Systems/ta-p/245890)",  outlines the **three  patterns** to address the challenge of Data Federation with Hadoop databases. I am using the article as foundation for this question.

I am supposing that Trino is related to **pattern-3**, is it? 

----
**Notes**. Here a summary of the 3 patterns described in the article, in the perspective of the question. 

![](https://community.cloudera.com/t5/image/serverpage/image-id/12316iC6ADF7FFC0F52EC7/image-size/medium?v=1.0&px=600)
It is like a *syntax sugar* to express (in a kind of SQL language) JDBC-like connections. Bad performance. <br/>PS: the worst performance is on remote connections... Think of it as some kind of JDBC connection, abtracted in the SQL language (of the Federated Database) as a kind of [dblink](https://www.postgresql.org/docs/current/contrib-dblink-function.html) or [foreign data wrapper](https://www.postgresql.org/docs/current/contrib-dblink-function.html).

![](https://community.cloudera.com/t5/image/serverpage/image-id/12317iB595A2BC652E020D/image-size/medium?v=1.0&px=600)<br/> It is like a *syntax sugar* to express (in the SQL language of system-A) JDBC connections to non-A systems. Good performance for A and bad performance non-A.

![](https://community.cloudera.com/t5/image/serverpage/image-id/12318iC921F26E8CE43185/image-size/medium?v=1.0&px=600)<br/> It is not only a *syntax sugar*, it is possible to express, in the [Spark SQL](https://spark.apache.org/docs/3.1.1/sql-programming-guide.html) language, queries to all same-cluster-Hadoop systems with good performance, and use a kind of "JDBC connection with optimized cache" to non-Hadoop systems (with not so bad performance).

**Comment by findepi** [comment]
The first two are described as "syntax sugar", and Trino is an _execution engine_, so hardly a "syntax sugar".
So i guess if i have to choose between these, I'd choose 3, but I am not sure I have the same understanding of it when it comes to details.

Does this answer your question? Let me close the issue as "nothing to change in the project".

We can continue conversation here, or on `#general` channel on [our slack](https://trino.io/slack.html).
See you there!

**Comment by martint** [comment]
Also, please take a look at https://trino.io/paper
