### ISSUE TITLE
Join cross database with Trino

### ISSUE THREAD

**Issue by hli191** [trinodb/trino#7269]
How can i  use  join cross database  with multiple catalogs  in Trino?  or not support?

for example : 
One connector is Mysql ,catalog as mysql
Second connector is PostgreSql, catalog as postgresql

I want join cross database use sql as below :

select 
          a.user_name,
         b.order 
from 
        mysql.user as a  
join postgresql.order as b 
 on a.user_id=b.user_id

**Comment by findepi** [comment]
This is absolutely possible. 
I think you may hit a problem because `order` is a keyword, so try replacing `b.order` with `b."order"`.

**Comment by phd3** [comment]
Also, another minor thing: tables are referenced as `<catalog_name>.<schema_name>.<table_name>` in Trino, so please make sure to include the schema name too. https://trino.io/docs/current/overview/concepts.html#schema

Feel free to join Trino community [slack](https://trino.io/slack.html) to discuss any further questions you might have.

**Comment by hli191** [comment]
Thanks for the explain , but how to config JDBC URL for client ?
assume i have two catalogs as above.

jdbc:trino://host:port/ ????
jdbc:trino://host:port/mysql
jdbc:trino://host:port/postgresql

**Comment by findepi** [comment]
Use `jdbc:trino://host:port/` url and then query like:

```
select * from one_catalog.some_schema.my_table a
join second_catalog.a_schema.some_other_table b ON a.id = b.id
```

I will close this as not-an-issue in Trino.
We can continue conversation here, or on `#troubleshooting` channel on [our slack](https://trino.io/slack.html).
See you there!
