### ISSUE TITLE
trino table column is case Insensetive for elasticsearch connector

### ISSUE THREAD

**Issue by waitingF** [trinodb/trino#7276]
While using trino to perform sql base on Elasticsearch cluster, I found presto is NOT case sensetive for columns. For Example, I have an Index in elasticsearch with mapping like(with fields[age, Age, name, Name]): 
```json
{
  "myindex" : {
    "mappings" : {
      "properties" : {
        "Age" : {
          "type" : "long"
        },
        "Name" : {
          "type" : "keyword"
        },
        "age" : {
          "type" : "long"
        },
        "name" : {
          "type" : "keyword"
        }
      }
    }
  }
}
```

When use "DESC myindex" in trino-cli, it shows nothing:
![image](https://user-images.githubusercontent.com/19326824/110954053-069f7500-8383-11eb-9f25-48a2cd4c49c4.png)

Then, I dive into elasticsearch connector plugin, I found the following code which cause "DESC myindex" shows no rows.
![image](https://user-images.githubusercontent.com/19326824/110954305-4f572e00-8383-11eb-9bc0-b6285dfe7189.png)

Then, I remove the toLowCase function with the thought trino might show the correct columns:
![image](https://user-images.githubusercontent.com/19326824/110954602-a65d0300-8383-11eb-9d53-9ed50d05f617.png)

But I was wrong. This time, trino show below. All column are lower case:
![image](https://user-images.githubusercontent.com/19326824/110954724-cbea0c80-8383-11eb-9dad-1604c74397ed.png)
And, I could not select any data from elasticsearch.
![image](https://user-images.githubusercontent.com/19326824/110955330-73673f00-8384-11eb-9581-d818dceb6410.png)
below is the Exeption stack:
![image](https://user-images.githubusercontent.com/19326824/110955445-94c82b00-8384-11eb-813f-36ddc4d8c204.png)

In my case, I need trino to treat columns like age & Age. Could anyone tell me how to make trino case sensetive? THANKS~

**Comment by hashhar** [comment]
Requires https://github.com/trinodb/trino/issues/17 to fix correctly. The optimizer normalizes every input to lowercase today. We do support case-insensitive name matching as long as there are no collisions - which is not true in your case.

You can try once using the query passthrough feature of the ElasticSearch connector (but I don't think it would work since the query is embedded in the table name which itself would be lowercased). See https://trino.io/docs/current/connector/elasticsearch.html#pass-through-queries.

**Comment by findepi** [comment]
> You can try once using the query passthrough feature of the ElasticSearch connector (but I don't think it would work since the query is embedded in the table name which itself would be lowercased). See https://trino.io/docs/current/connector/elasticsearch.html#pass-through-queries.

Note that (from the docs):

_The Elasticsearch query string es-query is base32-encoded to avoid having to deal with escaping quotes and case sensitivity issues in table identifiers._
