### ISSUE TITLE
How to make trino table name case sensetive?

### ISSUE THREAD

**Issue by cxydevelop** [trinodb/trino#7286]
I have created a custom connector plugin.
When I executed "select name,id from http.cluster_list.TEST", I always got the lowercase SchemaTableName in "ConnectorMetadata.getTableHandle(..)"
![image](https://user-images.githubusercontent.com/25632323/111108855-9ff1a580-8594-11eb-8824-f94fbc0a8162.png)
I found that when Trino SqlParser create statement, it will make my table name lowercase.
![image](https://user-images.githubusercontent.com/25632323/111108491-f5798280-8593-11eb-9376-1a92745cf1b9.png)
So I want to know how to control the SqlParser do not make lowercase

**Comment by findepi** [comment]
Please have a look here: https://github.com/trinodb/trino/issues/17
I will close this one as the duplicate.

We can continue conversation here, or on `#dev` channel on [our slack](https://trino.io/slack.html).
See you there!
