### ISSUE TITLE
trino kafka connector dynamic table names

### ISSUE THREAD

**Issue by giggsodevops** [trinodb/trino#7289]
hello
in trino kafka.properties files we are giving tables names as per below config
```
connector.name=kafka
kafka.nodes=localhost:9092
kafka.table-names=tpch.customer,tpch.orders,tpch.lineitem,tpch.part,tpch.partsupp,tpch.supplier,tpch.nation,tpch.region
kafka.hide-internal-columns=false
```

so instead of my expectation is how to get all tables dynamic without mention in `kafka.table-names` list.
because my source code automatic creating date base topic names on kafka. so i am not able to retrieve those topics names here without adding in above files.
so how i can do that dynamic ?

thanks

**Comment by Praveen2112** [comment]
Hi !! Kafka connector also supports schema registry tables. We just need to add the following config 

```
kafka.table-description-supplier=CONFLUENT
kafka.confluent-schema-registry-url=schemaRegistry-url
```

Reference : https://trino.io/docs/current/connector/kafka.html#confluent-table-description-supplier. 

Now we could add new subject to SchemaRegistry and it is accessible by Trino.

**Comment by Praveen2112** [comment]
Feel free to join our community : https://trino.io/slack.html

**Comment by Praveen2112** [comment]
Feel free to open this issue if it doesn't answer your question.
