### ISSUE TITLE
How to package the custom plugin

### ISSUE THREAD

**Issue by cxydevelop** [trinodb/trino#7353]
I want to package a custom plugin and put it in trino directory "/usr/lib/trino/plugin"
![image](https://user-images.githubusercontent.com/25632323/111732519-9c219400-88b0-11eb-812a-89903232e411.png)

My plugin is a maven project, and I have to use  the maven plugin "maven-dependency-plugin" to package its dependency jar.
pom.xml
`<build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <meminitial>128m</meminitial>
                    <maxmem>512m</maxmem>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.1.2</version>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/lib</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>`
after run maven plugin, I should move my plugin jar and all dependency jar to trino plugin folder. And it can work.
But I found that some jar in trino plugin folder also in "/usr/lib/trino/lib/". like "trino-array-352.jar" 
![image](https://user-images.githubusercontent.com/25632323/111734604-67fca200-88b5-11eb-9230-789565985af3.png)
I suppose that some jar don't need to package with my custom plugin, so I want to know usually how can we package our custom plugin

**Comment by yuokada** [comment]
Hi, maven-shade-plugin may be useful to package a custom plugin.

`maven-shade-plugin` packs class files depended on a custom plugin to a jar for that project.

Just in my case.

e.g: Here is my example repository.
- https://github.com/yuokada/presto-sample-udf/blob/5ee5193233bbfbb981696f3fdd8fc9ded8db8399/pom.xml#L158-L191

**Comment by findepi** [comment]
The recommended way is to use
```xml
<packaging>trino-plugin</packaging>
```

and 
```xml
<plugin>
    <groupId>io.trino</groupId>
    <artifactId>trino-maven-plugin</artifactId>
    <version>10</version>
    <extensions>true</extensions>
</plugin>
```

the dedicated packaging runs some additional checks, ensuring your plugin declares dependencies correctly.
For example, it should not bundle SPI classes.

**Comment by findepi** [comment]
I will close this as answered, and not-an-issue in Trino.
We can continue conversation here, or on `#dev` channel on [our slack](https://trino.io/slack.html).
See you there!
