### ISSUE TITLE
jdbc driver rise "The datetime zone id 'GMT+08:00' is not recognised" error

### ISSUE THREAD

**Issue by sinlang** [trinodb/trino#7403]
The datetime zone id 'GMT+08:00' is not recognised

**Comment by findepi** [comment]
`GMT+08:00` is accepted as a zone identifier by Java Time, but is not accepted by Joda Time, which we use internally for performance reasons.

Please use `+08:00` instead.

**Comment by sinlang** [comment]
> `GMT+08:00` is accepted as a zone identifier by Java Time, but is not accepted by Joda Time, which we use internally for performance reasons.
> 
> Please use `+08:00` instead.

is there any method to gracefully set GMT+08:00 correctly;

**Comment by sinlang** [comment]
> `GMT+08:00` is accepted as a zone identifier by Java Time, but is not accepted by Joda Time, which we use internally for performance reasons.
> 
> Please use `+08:00` instead.
if used jdbc driver, i cant set  it manually;  but if use dbeaver client , has method to config it ?
![image](https://user-images.githubusercontent.com/4089994/113077256-627f5000-9203-11eb-9f7a-797ece67ef0c.png)

**Comment by findepi** [comment]
You'll need something like https://github.com/trinodb/trino/issues/7158 / https://github.com/trinodb/trino/pull/7252.

For now, please run Dbeaver with `-Duser.timezone=....`

**Comment by sinlang** [comment]
> You'll need something like #7158 / #7252.
> 
> For now, please run Dbeaver with `-Duser.timezone=....`

it doesn't work ,maybe has a jdbc properties to set timezone is a good idea

**Comment by xwzpp** [comment]
Can presto-jdbc connection can set timezone?

**Comment by auntyellow** [comment]
> Please use `+08:00` instead.

@findepi this doesn't work (in jdk1.8)

```
TimeZone.setDefault(TimeZone.getTimeZone("+08:00"))
```

This will set Java's default timezone to GMT but not expected GMT+8.
