### ISSUE TITLE
Dependency site cannot be reachable 

### ISSUE THREAD

**Issue by maranmani978** [trinodb/trino#7428]
While installing dependency for prestosql (tag-350) using ./mvnw clean install -DskipTest
Got stuck in this line
Downloading from confluent: http://packages.confluent.io/maven/com/google/cloud/google-cloud-phishingprotection-bom/0.29.2/google-cloud-phishingprotection-bom-0.29.2.pom

looks like packages.confluent.io is not reachable...

Can someone help on this??

**Comment by findepi** [comment]
I can reach http://packages.confluent.io/maven/com/ but it shows only "linkedin" sub-directory, no "google" there.
Interestingly the build on master passed today https://github.com/trinodb/trino/runs/2198787107.
Maybe we don't depend on that repository anymore?

@maranmani978 can you please try building from `master` branch? Please make sure your local copy is up to date.

**Comment by hashhar** [comment]
possibly you were behind a firewall @maranmani978.

Maven consults all repos for all dependencies in order so even if something won't be found at packages.confluent.io it still gets queried.

This is improving now for example with https://github.com/trinodb/trino/commit/f133a42e4e1df7c7dc8777edf45df71b3fa0d1b6 and eventually with Maven 4.

However, yes, confluent repo is a requirement to build the project. You can exclude `trino-kafka` module if you want to build project without connectivity to confluent repo.
