### ISSUE TITLE
class io.prestosql.$gen.VarbinaryBigintLongToBmAccumulator_20210328_072354_3

### ISSUE THREAD

**Issue by maijh** [trinodb/trino#7440]
i deploy a new trino plugin ,but when i implement my method ,it rise "class io.prestosql.$gen.VarbinaryBigintLongToBmAccumulator_20210328_072354_3" error，i don't know how to solve it，can someone help me，thanks.  Below is the code

import io.prestosql.operator.aggregation.state.StateCompiler;
import io.prestosql.spi.block.BlockBuilder;
import io.prestosql.spi.function.*;
import io.prestosql.spi.type.StandardTypes;
import org.hao.aggregation.state.BitmapState;
import org.roaringbitmap.buffer.MutableRoaringBitmap;
import io.prestosql.spi.function.AccumulatorStateSerializer;

@AggregationFunction("long_to_bm")
public final class LongBitmapAggregation {
	private static final AccumulatorStateSerializer<BitmapState> SERIALIZER = StateCompiler.generateStateSerializer(BitmapState.class);

    private LongBitmapAggregation() {}
	
	@InputFunction
    public static void input(@AggregationState BitmapState state, @SqlType(StandardTypes.BIGINT) long inputNum)
    {
		MutableRoaringBitmap bm = getOrCreateBitmap(state);
		state.addMemoryUsage(-bm.getSizeInBytes());
		bm.add(Integer.parseInt(String.valueOf(inputNum)));
		state.addMemoryUsage(bm.getSizeInBytes());
    }

    @CombineFunction
    public static void combineState(@AggregationState BitmapState state, @AggregationState BitmapState otherState)
    {
        MutableRoaringBitmap input = otherState.getBitmap();

        MutableRoaringBitmap previous  = state.getBitmap();
        if (previous == null) {
            state.setBitmap(input);
            state.addMemoryUsage(input.getSizeInBytes());
        }
        else {
            state.addMemoryUsage(-previous.getSizeInBytes());
            previous.or(input);
            state.addMemoryUsage(previous.getSizeInBytes());
        }
    }

    private static MutableRoaringBitmap getOrCreateBitmap(@AggregationState BitmapState state)
    {
        MutableRoaringBitmap bm = state.getBitmap();
        if (bm == null) {
            bm = new MutableRoaringBitmap();
            state.setBitmap(bm);
            state.addMemoryUsage(bm.getSizeInBytes());
        }
        return bm;
    }

    @OutputFunction(StandardTypes.VARBINARY)
    public static void evaluateFinal(@AggregationState BitmapState state, BlockBuilder out)
    {
        SERIALIZER.serialize(state, out);
    }
}

**Comment by zz0614** [comment]
how did you solve this problem?
