### ISSUE TITLE
Trino Thrift Metastore client not support multiple catalogs

### ISSUE THREAD

**Issue by sshkvar** [trinodb/trino#7486]
Hi, we would like to use 2 different iceberg/hive catalogs (prod and sandbox) with same hive metastore.
Hive metastore support different catalogs, but I can’t find a way to configure which catalog should iceberg use . As a result we have exactly same list of schemas/tables in both iceberg catalogs. 

[Discussion in slack ](https://trinodb.slack.com/archives/CJ6UC075E/p1617007674003600)

**Comment by dmitryfill** [comment]
Any recent developments on this?

**Comment by ateam131** [comment]
Has anything ever come of this? We have to deploy multiple HMS in order to get around this which makes scalability very limited.

**Comment by dain** [comment]
This was implemented in may in #21502
