### ISSUE TITLE
hive with specific pattern partition

### ISSUE THREAD

**Issue by antoinevokleber** [trinodb/trino#7514]
For the Hive connector, i  have need to mapping a partitionned blob azure with sub-directory  with form yyyy/mm/dd and not year=yyyy/month=mm/day=dd
i can't use a specific patten in the msck repair or procedure sync_partition_metadata 

how doing ?

thanks

**Comment by findepi** [comment]
Please use `register_partition` procedure for that, see https://trino.io/docs/current/connector/hive.html#procedures

I will close this as not-an-issue in Trino.
We can continue conversation here, or on `#troubleshooting` channel on [our slack](https://trino.io/slack.html).
See you there!
