### ISSUE TITLE
Document SetDigest type and functions

### ISSUE THREAD

**Issue by martint** [trinodb/trino#7517]
https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/type/setdigest/SetDigestType.java
https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/type/setdigest/SetDigestFunctions.java

**Comment by mosabua** [comment]
Example usage can be found in the slack conversation. 

https://trinodb.slack.com/archives/CFLB9AMBN/p1617829538494100

**Comment by mosabua** [comment]
Should be added to list https://trino.io/docs/current/functions/list.html

But also documented .. any suggestion where @martint 

Also should include jaccard_index function.

**Comment by mosabua** [comment]
SetDigest should be in data types doc somewhere

**Comment by mosabua** [comment]
Also include make_set_digest function

**Comment by findinpath** [comment]
This issue is being handled by the https://github.com/trinodb/trino/pull/8269 PR

**Comment by hashhar** [comment]
https://github.com/trinodb/trino/pull/8269 was merged.
