### ISSUE TITLE
Push topN to Phoenix unconditionally when Phoenix 5.1.2 is released

### ISSUE THREAD

**Issue by lhofhansl** [trinodb/trino#7521]
Currently Phoenix overestimated the memory required to perform a topN query, so in #7490 the maximum limit in topN queries to be pushed down to Phoenix had to be limited (and thus Trino had a ensure the topN on its side again, even though Phoenix performed all the work already.)

When Phoenix 5.1.2 (4.16.1) is released, we can remove that limitation.

**Comment by lhofhansl** [comment]
Tried with the pre-version of Phoenix 5.1.2. It turns out that `isTopNLimitGuaranteed` still has return false, since for `ORDER BY .. LIMIT N`, each split could return up to `N` results.

@findepi Is there a way around this? If not, we can still push topN down unconditionally, but Trino has to topN the result again.

**Comment by lhofhansl** [comment]
In fact I wonder how this relates to #6634

Even when topN is pushed to the connector and the connector does the sorting, we cannot assume a single ordered set, as each split can at best provide a partial order. I'm probably missing something.

**Comment by lhofhansl** [comment]
Example: 
```
trino> explain select count(*) from (SELECT v1 FROM phoenix.default.test ORDER BY "V1" ASC NULLS FIRST LIMIT 5);
Query Plan                                                               
----------------------------------------------------------------------------------------------------------------------------------------
Fragment 0 [SINGLE]
Output layout: [count]
Output partitioning: SINGLE []
Stage Execution Strategy: UNGROUPED_EXECUTION
Output[_col0]
│   Layout: [count:bigint]
│   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
│   _col0 := count
└─ Aggregate(FINAL)
│   Layout: [count:bigint]
│   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
│   count := count("count_0")
└─ LocalExchange[SINGLE] ()
│   Layout: [count_0:bigint]
│   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
└─ RemoteSource[1]
Layout: [count_0:bigint]

Fragment 1 [SOURCE]
Output layout: [count_0]
Output partitioning: SINGLE []
Stage Execution Strategy: UNGROUPED_EXECUTION
Aggregate(PARTIAL)
│   Layout: [count_0:bigint]
│   count_0 := count(*)
└─ TableScan[phoenix:default.test TEST sortOrder=[io.trino.plugin.jdbc.JdbcSortItem@6ce7ed0f] limit=5 columns=[], grouped = false]
Layout: []
Estimates: {rows: ? (0B), cpu: 0, memory: 0B, network: 0B}


(1 row)
```

```
trino> select count(*) from (SELECT v1 FROM phoenix.default.test ORDER BY "V1" ASC NULLS FIRST LIMIT 5);
_col0
-------
50
(1 row)

Query 20210409_003514_00005_bvmz2, FINISHED, 1 node
Splits: 27 total, 27 done (100.00%)
0.48 [50 rows, 0B] [105 rows/s, 0B/s]
```

**Comment by sopel39** [comment]
> In fact I wonder how this relates to #6634

Split level order is sufficient for #6634 to work
