### ISSUE TITLE
Iceberg : Delete Or Update is not support when read 

### ISSUE THREAD

**Issue by zhangwcoder** [trinodb/trino#7522]
In Iceberg 0.11，the row-based delete and  update operation is supported .  
Spark and flink has apply this feature , but trino is not support now .

**Comment by SananGuliyev** [comment]
is there any plan regarding to that?

**Comment by bitsondatadev** [comment]
@SananGuliyev and @zhangwcoder see: https://github.com/trinodb/trino/pull/10075.
