### ISSUE TITLE
Web UI ignores the 'http-server.authentication.oauth2.principal-field' config property

### ISSUE THREAD

**Issue by cccs-tom** [trinodb/trino#7526]
When using OAuth2 to log in to the the UI, it creates its principal based on the 'sub' claim and ignores the claim identified in the 'http-server.authentication.oauth2.principal-field' property. 

Steps to reproduce:
1. Configure Trino and the UI for OAuth2, set 'http-server.authentication.oauth2.principal-field' to something other than 'sub' and start the server. Set query permissions so that your user can only view and kill their own queries.
2. Log in to the CLI using an Access Token and execute any query.
3. Log in to the Web UI using the same user as in step 2. The user will not see their query.

It would seem pretty trivial to capture the value of `oauth2Config.getPrincipalField()` in the `OAuth2WebUiAuthenticationFilter` constructor and make use of it here:
https://github.com/trinodb/trino/blob/ec5daf8aaae8e9d467b2859aec53b8909c2dd6f1/core/trino-main/src/main/java/io/trino/server/ui/OAuth2WebUiAuthenticationFilter.java#L100

**Comment by lukasz-walkiewicz** [comment]
Hi, thanks for reporting this.

I'm afraid we forgot about the UI when this option was added.

I agree, it should be trivial, for reference, please take a look at:  https://github.com/trinodb/trino/commit/7b83702fcc1c04d49abee6a60f784653979f6325.

**Comment by kokosing** [comment]
@cccs-tom Would you like to contribute this fix?

**Comment by cccs-tom** [comment]
> 
> 
> @cccs-tom Would you like to contribute this fix?

I would. I'm just not sure how quickly I can get it done. It would be my first Trino contribution, so I need to set up my IDE, sign the CLA, etc.

**Comment by kokosing** [comment]
Please take your time. We will be happy to help.

**Comment by cccs-tom** [comment]
Resolved by #7639
