### ISSUE TITLE
MongoDB implicit schema inferred from data is not refreshed after data changes

### ISSUE THREAD

**Issue by Ognian** [trinodb/trino#7538]
`select * from xempty`where xempty is an empty collection results in
`SQL-Fehler [47]: Query failed (#20210409_143001_00009_3jyks): line 1:8: SELECT * not allowed from relation that has no columns`

After that I decided to add an entry in the xempty collection. And got the error again although there was now an entry with _id and name properties. After some debugging I found that the _schema collection was populated, and that xempty is there without any properties (columns). After deleting the xentry entry in the _schema and refreshing the query succeeds...

So it looks like there are 2 errors here:
1. empty collection should not error, but return OK and 0 rows
2. writing at a certain point in time to the _schema collection could go terrible wrong since data structure in mongodb is quite dynamic... Maybe there should be some some config option to prevent "caching" in _schema

**Comment by ebyhr** [comment]
1. The behavior is not specific to MongoDB connector. You can see the error comes from `StatementAnalyzer` class. 
2. Let me label as enhancement.

**Comment by findepi** [comment]
> empty collection should not error, but return OK and 0 rows

In SQL, a relation cannot have zero columns. cc @martint 
In connectors based on base-jdbc, we filter this out early 
https://github.com/trinodb/trino/blob/d2751de016155305719abf989abf99301935d00a/plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java#L315-L318

> writing at a certain point in time to the _schema collection could go terrible wrong since data structure in mongodb is quite dynamic... Maybe there should be some some config option to prevent "caching" in _schema

can we rephrase this issue to focus on this point only for now?

**Comment by Ognian** [comment]
@findepi I agree. The first is indeed very specific and can be only solved by manually providing a schema, or by knowing that a certain column always exists, which in case of mongodb is the _id column (see [here](https://docs.mongodb.com/manual/core/document/)):
```
In MongoDB, each document stored in a collection requires a unique _id field that acts as a primary key. If an inserted document omits the _id field, the MongoDB driver automatically generates an ObjectId for the _id field. 
```
So I'll try to rephrase the second issue (correct me if I'm wrong):

SQL requires a fixed schema. MongoDB does not have a fixed schema. So the first step is to either use a predefined one (_schema collection) or to generate a schema from the actual data . Then this schema is used to perform the query.
The problem is that when the schema is generated from the data, it is saved in the same place (_schema collection) like it is when the schema is predefined.
But when the schema is predefined the user guarantees that this schema is not changing or if it changes the user would update this place (_schema collection).
When generating the schema from the data it should be updated (generated) on every query, since a simple insert can change the schema.

**Comment by ebyhr** [comment]
I don't think this is bug. How can we detect the inserted data efficiently? Another question is how can we decide the expected schema from several documents? We can insert unrelated documents into one collection (likes USER document and ORDER document).

**Comment by findepi** [comment]
Is the schema inferred from the first document only?

**Comment by ebyhr** [comment]
@findepi Yes, the first document only. `...find().first()`. 
https://github.com/trinodb/trino/blob/b23fa2dba1db024fa603aa99d94c8e66fe19d791/plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java#L518-L521

**Comment by miniway** [comment]
Yes, it's not easy to detect schema change without a callbak or polling.

So initial design was detect schema from the first record as best guess then the update it manually if it's not correct. 

I think some possible ideas are
* Utilizing ALTER TABLE ADD COLUMN
* Adding a procedure, refresh_mongodb_schema(collection, strategy) 

Thanks
Min

**Comment by Ognian** [comment]
Some more input on how "detecting" can be done:
mongodb calls it [sampling](https://docs.mongodb.com/compass/current/sampling/#std-label-sampling) and beside the `$sample`operator in the aggregation pipeline there is also an implementation in [compass](https://docs.mongodb.com/compass/current/schema/export/) which is now free. [Sourcecode of compass](https://github.com/mongodb-js/compass) can be also be of help...

**Comment by ebyhr** [comment]
We are going to support `json` type for MongoDB connector in version 360 (not yet released). I know it's little different from this request, but I hope it helps you in some situation. Please feel free to provide feedback.

**Comment by Ognian** [comment]
@ebyhr Thanks! I'll test when it is released and see how this helps...

**Comment by ebyhr** [comment]
Let me close as the connector supports `SET DATA TYPE` syntax now.
