### ISSUE TITLE
Iceberg: should add caching mechanism for IcebergMetadata

### ISSUE THREAD

**Issue by dixingxing0** [trinodb/trino#7551]
I think trino should add caching mechanism for IcebergMetadata for at least two reasons :
1. to prevent the client from using the same table multiple times in the same query and getting different results, for now iceberg connector accesses hive metastore for multiple times in a single query.
2. improve query performance, For example,when trino query a small iceberg table, we found a simple count query will cost about 4 seconds, and analyze phase cost more than 2 seconds.

**Comment by findepi** [comment]
> * to prevent the client from using the same table multiple times in the same query and getting different results, for now iceberg connector accesses hive metastore for multiple times in a single query.

There should be query- (actually: transaction-) -level "cache".
For reference, in Hive this is done in `TransactionalMetadataFactory`.
(utilising `CachingHiveMetastore` under the hood).
Such "cache" should be always used, does not need to be configurable.

Furthermore, there could be additionally an opt-in longer-lived
(not transaction-scoped) metadata cache. For reference, in Hive this is
done in `CachingHiveMetastoreModule` (also using `CachingHiveMetastore`,
but with different configuration, this is a cache in a typical sense of the 
word).

**Comment by phd3** [comment]
this is in progress under #7367. (not long-lived though).

**Comment by dixingxing0** [comment]
> this is in progress under #7367. (not long-lived though).
Thanks @phd3, that's greate, i'm closing this issue.
