### ISSUE TITLE
Support offset after limit in queries

### ISSUE THREAD

**Issue by reugn** [trinodb/trino#7553]
The following query
```sql
select * from schema limit 1 offset 1;
```
fails with
`Query failed: line 1:32: mismatched input 'offset'. Expecting: <EOF>`
while
```sql
select * from schema offset 1 limit 1;
```
works as expected using the Trino CLI client.

**Comment by findepi** [comment]
This was discussed at https://github.com/trinodb/trino/issues/4335
Let's continue there or on [our slack](https://trino.io/slack.html).
