### ISSUE TITLE
Support prepared statements for `SHOW...` statements

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#7560]
It is due the fact pattern and escape are `string` in `SqlBase.g4`

```
    | SHOW TABLES ((FROM | IN) qualifiedName)?
        (LIKE pattern=string (ESCAPE escape=string)?)?                 #showTables
    | SHOW SCHEMAS ((FROM | IN) identifier)?
        (LIKE pattern=string (ESCAPE escape=string)?)?                 #showSchemas
```

To support prepared statement one should be able to use `PARAMETER` there.

The change requires much work than simply changing the grammar.

**Comment by findepi** [comment]
`SHOW ...` statements are by design for humans only, as their output layout can change without notice.
What would be the usecase to support `SHOW` queries with prepared statements?

**Comment by kokosing** [comment]
> SHOW ... statements are by design for humans only, as their output layout can change without notice.

That is fine.

> What would be the usecase to support SHOW queries with prepared statements?

To call such statements using client tools, like JDBI. Which use prepare statements for handling parameters.

**Comment by findepi** [comment]
When humans interact with Trino, they rarely use JDBI directly. 
People will use CLI or graphical tools like DBeaver, and then they don't need (and cannot leverage) support for parameters.

For programmatic use, one should be able to access necessary information without need to use a `SHOW` query.
Is there a use-case where today this is not possible?

**Comment by kokosing** [comment]
Let me close it then. I see your point.
