### ISSUE TITLE
trinodb 338 memory not freed

### ISSUE THREAD

**Issue by wangfeigithub** [trinodb/trino#7561]

**Comment by wangfeigithub** [comment]
When I run Trinodb for a few days, it takes up so much memory that the server has no memory to use, but I have no SQL tasks running in the background.
But when I restarted Trinodb, the server's memory returned to normal. I suspected that the SQL task was finished, but the memory was not freed. Is there any way to solve this problem?

**Comment by findepi** [comment]
This has been explained on [our slack](https://trino.io/slack.html)
let me quote https://trinodb.slack.com/archives/CGB0QHWSW/p1584297218397400?thread_ts=1584284178.390000&cid=CGB0QHWSW

> this is normal Java behavior.
> JVM usually does not return memory back to OS even after full GC (this is subject to some configuration toggles, JVM version and GC algorithm used).
> 
> to monitor memory usage, you need to check JVM metrics exposed over JMX. Monitoring OS-level memory usage is much less useful.

We can continue conversation here, or on `#troubleshooting` channel on [our slack](https://trino.io/slack.html).
See you there!
