### ISSUE TITLE
Document unsupported-type-handling for all connectors that support it

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#7570]
Current `unsupported-type-handling` is documented for Oracle connector:

> If an Oracle table uses a type not listed in the above table, then you can use the
> ``unsupported-type-handling`` configuration property to specify Trino behavior.
> For example:
> 
...
> - If ``unsupported-type-handling`` is set to ``IGNORE``,
>   then you can't see the unsupported types in Trino.
> - If ``unsupported-type-handling`` is set to ``CONVERT_TO_VARCHAR``,
>   then the column is exposed as unbounded ``VARCHAR``.

however it applies to a bunch of other connectors (extending from base-jdbc).

cc @mosabua

**Comment by findepi** [comment]
see however https://github.com/trinodb/trino/pull/7573 before oracle.rst gets copied.

**Comment by mosabua** [comment]
Should go into a base connector doc and just be linked from the standard Type mapping section in each connector that supports it.

**Comment by findepi** [comment]
> Should go into a base connector doc a

Provided such doc exists. Today it doesn't AFAIK.
(if indeed doesn't, the creation of this is not part of the task)

**Comment by mosabua** [comment]
Will address this for SQL Server and can then be used for all other connectors that implement this https://github.com/trinodb/trino/pull/7531

**Comment by mosabua** [comment]
Fixed in https://github.com/trinodb/trino/pull/7834
