### ISSUE TITLE
Hive example for drop_stats needs quoting on arguments

### ISSUE THREAD

**Issue by electrum** [trinodb/trino#7572]
The examples in [this section](https://trino.io/docs/current/connector/hive.html#updating-table-and-partition-statistics) be updated:

```sql
CALL system.drop_stats('schema_name', 'table_name')
```

```sql
CALL system.drop_stats(
    schema_name => 'schema',
    table_name => 'table',
    partition_values => ARRAY[ARRAY['p2_value1', 'p2_value2']])
```

**Comment by yashhd** [comment]
Hi @electrum . This will be my first ever open source contribution. Can you please tell me which file is it?

**Comment by findepi** [comment]
@yashhd this is in `docs/src/main/sphinx/connector/hive.rst`.

**Comment by yashhd** [comment]
@findepi @electrum  I have made a pull request. Could you please review it?
github.com/trinodb/trino/pull/7640
