### ISSUE TITLE
Add support for partition evolution in Iceberg.

### ISSUE THREAD

**Issue by bitsondatadev** [trinodb/trino#7580]
Now that we've [updated to 0.11.0 ](https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/pom.xml#L18) for Iceberg, we should consider adding support for partition evolution. I spoke with @phd3 and he said there may be some support for reading partition evolved tables but currently we don't support the DDL for updating the table properties after creation.

Docs: https://iceberg.apache.org/evolution/#partition-evolution

**Comment by bitsondatadev** [comment]
One thing we'll need to discuss is adding syntax for [ALTER TABLE](https://trino.io/docs/current/sql/alter-table.html). 

Looking at the postgresql syntax for [CREATE TABLE](https://www.postgresql.org/docs/current/sql-createtable.html) and [ALTER TABLE](https://www.postgresql.org/docs/current/sql-altertable.html), we would want to add  `SET ( storage_parameter [= value] [, ... ] )` and `RESET ( storage_parameter [, ... ] )`.

For this table creation

```
CREATE TABLE distributors (
    did     integer,
    name    varchar(40),
    UNIQUE(name) WITH (fillfactor=70)
)
WITH (
 location='s3a://a/b/c/d',
 partitioning = ARRAY['identity(name)'']
);
```

We could update with

```
ALTER TABLE distributors SET ( partitioning = ARRAY['day(event_time)', 'bucket(did, 64)']);
ALTER TABLE distributors RESET (location);
```

**Comment by tuppimax** [comment]
@bitsondatadev @phd3 when you say "there may be some support for reading partition evolved tables" are there any known issues with reading partition evolved tables ? I would be happy help out.

We use Trino only reads while all the writes happen through Spark. Trying to understand the gaps which affect our use case. 

Thanks in advance

**Comment by phd3** [comment]
@tuppimax Currently, there isn’t test coverage around tables with partition spec evolution, so adding them would give us confidence on the read support. However, Trino uses iceberg library itself to generate splits based on provided filters, so it should already be partition spec aware. In addition, partition pruning optimization and delete operation requires that the filters match entire partitions. This code is also aware of partition spec evolution currently. But need to have tests to make sure everything works.

**Comment by phd3** [comment]
The tests would need to use Spark to evolve the spec (See `io.trino.tests.iceberg.TestSparkCompatibility`), since Trino doesn’t have support right now. IIRC the spec evolution syntax requires iceberg-spark3-runtime version 0.11.0, if so we need another release of [trinodb/docker-images](https://github.com/trinodb/docker-images) to have that.

**Comment by Kyo91** [comment]
@tuppimax See #8284 for an example of an issue with reading partition evolved tables.

**Comment by alexjo2144** [comment]
Sorry, didn't see this older thread so I made a duplicate https://github.com/trinodb/trino/issues/12174 but updating the partitioning on a table using `ALTER TABLE ... SET PROPERTIES` is in this PR: https://github.com/trinodb/trino/pull/12259
