### ISSUE TITLE
Pass User Identity to Hive Metastore

### ISSUE THREAD

**Issue by chrlso** [trinodb/trino#7581]
When using Hive and Glue Metastores we would like to pass some user information from the ConnectorIdentity to the Metastore Client in order to allow for different users to connect to their respective Metastores and allow for different IAM roles. 
This is similar to this request which is still open: https://github.com/trinodb/trino/issues/966 

We were thinking to leverage the HiveIdentity parameter which is currently passed through the majority of calls which get table, view, and database information. 

Would it be feasible to include the HiveIdentity on the remaining methods i.e getDatabase, getAllDatabases, getAllTables, etc?

**Comment by kokosing** [comment]
>  to allow for different users to connect to their respective Metastores and allow for different IAM roles.

Can you please explain me how this mapping works? I don't see currently anything in `GlueHiveMetastore` that could use `HiveIdentity`.  It looks like Glue client is created once with credentials from `hive.metastore.glue.*` properties. Do you use different metastore implementation or are you will to change `GlueHiveMetastore` in the next step?

If you a parameter that is not currently used, then I am afraid that someone will notice this and try to clean the code by removing "unused"  parameters.

**Comment by chrlso** [comment]
We use a custom metastore implementation which acts similar to the ThriftHiveMetastore and the ThrifthiveMetastoreClient which will create the client during a call to the metastore. We keep a cached client so that we can reuse it when we see the same HiveIdentity. This allows us to pass in the proper credentials for the new Identity.

I see that Trino currently passes the HiveIdentity to the metastore methods in order to enable impersonation in the Hive calls but these were missing for getting databases and getting all tables/views. Adding these properties can allow for impersonation on these functions as well. Do you know if there is a reason impersonation was not added to these calls?

**Comment by kokosing** [comment]
> Do you know if there is a reason impersonation was not added to these calls?

IIRC that was a deliberate choice. If we don't pass identity here can cache same information between users, so other users don't need to call these if caching is enabled. Also as far I remember we were thinking that it is ok as we can filter schemas and tables with sql-access control later.

CC: @findepi @electrum @losipiuk Do you recall more reasons?

At them moment I am no longer convinced that the current implementation is ok. For example HMS could use other authorization mechanism and values returned for listing tables or databases could be different between users. And sql-standard access control is not always used or applicable.

So I would not only add identity parameter but also use it for thrift HMS client implementation.

**Comment by findepi** [comment]
Impersonation is not used not only for listing databases. (BTW do we know of a case where HMS returns different responses for different users?)

Impersonation is _also_ skipped when managing roles and grants. 
While I can imagine a situation when impersonation is desired for managing roles and grants,
i can also imagine situation when it's not desired (as currently implemented).

In any case, any behavior change here can may or may not have consequences that are hard to foresee.
The primary obstacle is that we're debating HMS behavior including when HMS has some auxiliary
authentication plugins, which are not necessarily known to us. Thus, any change needs to be introduced
consciously and defensively.

**Comment by kokosing** [comment]
> Impersonation is also skipped when managing roles and grants.

I would prefer not to change this at the moment.

**Comment by kokosing** [comment]
Fixed by https://github.com/trinodb/trino/pull/12002
