### ISSUE TITLE
Saturated floor cast from varchar to char may contain illegal characters

### ISSUE THREAD

**Issue by skrzypo987** [trinodb/trino#7597]
In `CharactedStringCasts::varcharToCharSaturatedFloorCast` there is an operation of decrementing the value of a code point. The decremented value in rare cases may end up being an index that is not a valid Unicode code point (surrogate for example).
This in turn may end up as an incorrect/illegal character string.

**Comment by JoJoBizarreAdventure** [comment]
@findepi Could you please give me some examples of inputs that lead to incorrect character string?
It's a bit confusing. I want to have a try fixing it.

**Comment by skrzypo987** [comment]
Put
```
        assertEquals(varcharToCharSaturatedFloorCast(
                5L,
                utf8Slice("123" + new String(Character.toChars(0xE000)))),
                utf8Slice("123" + 0xDFFF));
```
into `CharacterStringCasts::testVarcharToCharSaturatedFloorCast` and you will get an `InvalidCodePointException`
`0xDFFF` is the last of the surrogate codepoints which are illegal and should not exists. There may be other ranger of chars like that in Unicode, however `SliceUtf8::setCodePointAt` knows only this one.

**Comment by JoJoBizarreAdventure** [comment]
I need some help for this https://github.com/trinodb/trino/issues/7597.
I found that for this testcase
```
assertEquals(varcharToCharSaturatedFloorCast(
                5L,
                utf8Slice("123" + new String(Character.toChars(0xE000)))),
                utf8Slice("123" + 0xDFFF));
```
The actual result of utf8Slice("123"+0xDFFF) will be [49, 50, 51, 53, 55, 51, 52, 51]. 49, 50 and 51 comes from "123" but the rest all come from 0xDFFF( in decimal 57343 for this number ). The length of it is larger than 5 and it should be truncated.
So I wonder for this issue, if I should handle the InvalidCodePointException and truncate the result? (In this case the result would be 12357, the rest part 343 will be removed).
Please give me some advice.

**Comment by JoJoBizarreAdventure** [comment]
@hashhar Could you please give me some advice for this ?

**Comment by skrzypo987** [comment]
I believe you are confusing length of UTF8 representation with the actual length. The `y` parameter is a number of **code **points****, not bytes. Actually you should not even care about charsets like UTF8.
The example `utf8Slice("123" + new String(Character.toChars(0xE000))))` consists actually of 4 code points: 49, 50, 51, 0xE000.
All of them are ints, not bytes.
And this is a valid unicode string, as `0xE000` is a valid (not specified yet, but valid) code point. However code point in the range of `Character.MIN_SURROGATE` to `Character.MAX_SURROGATE` are not valid as they are sort of helper numbers for UTF-16 encoding.
So after decrementing the `0xE000` we end up with `Character.MAX_SURROGATE` which is invalid. The reasonable solution would be to keep decrementing the code point until it is legal which will always end up with `Character.MIN_SURROGATE - 1`

**Comment by JoJoBizarreAdventure** [comment]
Thanks @skrzypo987 , I will try to submit a pr that keep decrementing the code point.
