### ISSUE TITLE
trino can not Configure hive permissions   Doesn't work

### ISSUE THREAD

**Issue by thiningsun** [trinodb/trino#7598]
trino version ：347
I want to control the permissions of the hive table through trino -server, but I went through the official documents and found that it failed

![image](https://user-images.githubusercontent.com/45502167/114852443-5c998980-9e15-11eb-9087-a5d0d25e1879.png)

![image](https://user-images.githubusercontent.com/45502167/114852745-a4201580-9e15-11eb-8ffd-09ade580e8c8.png)
![image](https://user-images.githubusercontent.com/45502167/114861848-65438d00-9e20-11eb-9f56-a207a1c883ec.png)

Sorry to bother you, hope you can help me！Because there is too little information on the Internet  on trino .
thx

**Comment by hashhar** [comment]
Web UI disables password if accessed over HTTP. Trino only allows authentication to happen over HTTPS to prevent leaking credentials in plaintext over the network.

Make sure you enable HTTPS and access the Web UI (and other client tools) over HTTPS for the password to be available.

**Comment by hashhar** [comment]
Feel free to re-open if you still need additional help.
