### ISSUE TITLE
Standard code path in BackgroundHiveSplitLoader should not reference AcidInfo.Builder

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#7603]
Currently we are calling out to `AcidInfo.Builder.build()` method also for code path in `BackgroundHiveSplitLoader.loadPartition` when we are not reading from ORC ACID table. 
This should be changed to make the code flow in the method more obvious.

**Comment by tooptoop4** [comment]
related to https://github.com/trinodb/trino/issues/2913
