### ISSUE TITLE
Pass Constraint with functional predicate to ConnectorSplitManager

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#7608]
`Constraint#predicate` represents a Filter that cannot be converted to a `TupleDomain`.
Today the `Constraint#predicate` is passed to `io.trino.spi.connector.ConnectorMetadata#applyFilter` (but only sometimes, i.e. within `AddExchanges`)
Connector may be unable to derived all the possible information out of that at this stage.
We should pass the same information second time, to `ConnectorSplitManager`.

**Comment by sopel39** [comment]
Should we fix planner and connectors instead so that pushdown of predicate via `applyFilter` is more reliable?

**Comment by findepi** [comment]
`Constraint#predicate` is not always present for performance reasons.

**Comment by martint** [comment]
Are the performance reasons that it can be expensive to evaluate? Then we should improve that, instead. There’s no reason why it should be as slow as it is today — Trino used to evaluate expressions exclusively by interpreting them on the early days, and it was not horrible.

**Comment by findepi** [comment]
> Are the performance reasons that it can be expensive to evaluate? Then we should improve that

Let's track this as a separate issue

> instead. 

Improving performance wouldn't alleviate the underlying problem that split manager doesn't have access to full information.
For example, `HiveTableHandle` keeps list of partitions to scan. (It uses memory, so we have a safety limit for 100K partitions).
Now imagine you want to change hive connector not to track partition list explicitly, or you simply delay this computing this
information until the time of split generation. Today it's not possible, as `ConnectorSplitManager` gets `TupleDomain` only,
and not `Constraint`.

**Comment by sopel39** [comment]
> or you simply delay this computing this
information until the time of split generation

We use partition information to generate table predicates.

We could maybe keep `Optional<Predicate<Map<ColumnHandle, NullableValue>>> predicate` within `HiveTableHandle` (since it's used only on coordinator)?

**Comment by findepi** [comment]
> We could maybe keep `Optional<Predicate<Map<ColumnHandle, NullableValue>>> predicate` within `HiveTableHandle` (since it's used only on coordinator)?

I wanted to start a separate thread about ... https://github.com/trinodb/trino/issues/7620

**Comment by losipiuk** [comment]
cc: @losipiuk
