### ISSUE TITLE
Hive ORC ACID INSERT/UPDATE/DELETE/MERGE support

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#7611]
This is umbrella issue to track work regarding DML for Hive ORC ACID tables:

Core features:
 * [x] DELETE Support (https://github.com/trinodb/trino/issues/5049, https://github.com/trinodb/trino/pull/5402)
 * [x] INSERT Support (https://github.com/trinodb/trino/issues/5049, https://github.com/trinodb/trino/pull/5402)
 * [x] UPDATE Support (https://github.com/trinodb/trino/pull/5861)
 * [x] MERGE Support (https://github.com/trinodb/trino/pull/7386)

Outstanding issues:
 * [x] Support UPDATE when original files are present (https://github.com/trinodb/trino/issues/7298)
 * [x] Do not use non-transactional delete to drop whole partition of ORC ACID table (https://github.com/trinodb/trino/issues/7291)

**Comment by losipiuk** [comment]
cc: @findepi @electrum @djsstarburst

**Comment by divyanshidm** [comment]
Is this available in Trino? (I am using Trino CLI 376, Hive Metastore 3.1.2, Both on dataproc gcp.)
But it still complains on update/delete - **Invalid method name: 'alter_table_req'**
Can somebody help?

**Comment by bitsondatadev** [comment]
@losipiuk now that MERGE support is in, can we close this?

**Comment by losipiuk** [comment]
> @losipiuk now that MERGE support is in, can we close this?

Yes, I thnk
