### ISSUE TITLE
Document bing_tile_quadkey function

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#7653]
Already in list.rst .. needs to be added to other bing_tile functions docs.

**Comment by Damans227** [comment]
I have assigned this isseue to myself. Thanks!

**Comment by Damans227** [comment]
@mosabua ` bing_tile_quadkey()`function already exists in this file: `Trino/master/docs/src/main/sphinx/functions/geospatial.rst`

Where else does it needs to be added ?

**Comment by mosabua** [comment]
then you probably just need to ensure that the entry in list.rst links to the function in geospatial.rst

**Comment by Damans227** [comment]
> then you probably just need to ensure that the entry in list.rst links to the function in geospatial.rst

I see, Idk why I was under an impression that sphinx would tc of it automatically. I will take a second look at list.rst to figure out why it's not working. Thanks for replying.
