### ISSUE TITLE
Document functions for bitwise shifting

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#7654]
* bitwise_left_shift
* bitwise_right_shift
* bitwise_right_shift_arithmetic

Add to functions/bitwise.rst and update list

**Comment by mkDoku** [comment]
Hi, it's Sascha. I would like to work on this issue.

**Comment by mosabua** [comment]
Functions are already documented, list.,rst needs the links update to be using func and @mkDoku is going to add some examples!

**Comment by mosabua** [comment]
This is all done now in terms of documenting. More examples in linked PR are mostly a nice to have.

**Comment by mkDoku** [comment]
Thank you for reviewing my changes, @mosabua .
