### ISSUE TITLE
Link format_datetime function in list.rst to actual docs

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#7656]
and probably expand that documentation. Probably needs an anchor set to allow linking. Maybe even a separate section.

To be found in functions/datetime.rst

**Comment by shivampapat** [comment]
Hi there. From what I understood I need to add format_datetime in list.rst ( :func:`format_datetime` add this line in list.rst)
Please let me know if that's correct
PS : I am a beginner.

**Comment by shivampapat** [comment]
I have made changes in the branch
https://github.com/trinodb/trino/compare/master...shivampapat:patch-1
Please check

**Comment by ebyhr** [comment]
@shivampapat Additionally, please update `list-by-topic.rst`. Feel free to send the PR. Thanks in advance.

**Comment by shivampapat** [comment]
Pull requested. PLease check and let me know if any changes are needed. Thank you.
https://github.com/trinodb/trino/pull/10973

**Comment by shivampapat** [comment]
Hi @ebyhr. I have raised PR. I have mailed the terms and conditions agreement Signed to the respective mail ID mentioned.
But I see that it is UNCHECKED yet and that's why the PR is on hold.
Is there anything I can do or anyone I should reach out ?

**Comment by ebyhr** [comment]
@martint Could you confirm CLA from @shivampapat?

**Comment by ebyhr** [comment]
Closing as #10973
