### ISSUE TITLE
Document from_geojson_geometry and to_geojson_geometry functions

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#7657]
in geospatial docs and update links in list.rst

**Comment by mosabua** [comment]
from_geojson_geometry is already done. So the other one should be easy.

**Comment by tanya654** [comment]
Hi, may i ask is this issue still open? can i work on this?

**Comment by mosabua** [comment]
Sorry .. I just checked.. both are done.

**Comment by mosabua** [comment]
However @tanya654 .. there are probably lots of other places in the docs that can be improved. And the functions lists might still have functions that dont link because there is no docs.
