### ISSUE TITLE
Document nanos time functions

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#7658]
* from_iso8601_timestamp_nanos
* from_unixtime_nanos

Currently only in list and release notes. Need to add to datetime.rst and link

**Comment by zhangchunyang1024** [comment]
@mosabua can i take it

**Comment by mosabua** [comment]
Sure .. go for it.

**Comment by mosabua** [comment]
Sorry... I found a bug with the docs there and needed to fix that.

**Comment by zhangchunyang1024** [comment]
It's OK. I'll continue to pick another issue
