### ISSUE TITLE
Document murmur3 hash function

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#7664]
With other hash functions, update list, add example

**Comment by gaojun2048** [comment]
Can I work for this issue?

**Comment by martint** [comment]
Go for it!

**Comment by mosabua** [comment]
Then we just need to update the link to it in list.rst. Want to send a PR for that @gaojun2048 ?

**Comment by gaojun2048** [comment]
> Then we just need to update the link to it in list.rst. Want to send a PR for that @gaojun2048 ? And it might be worth adding some more info about that hash (or a link to a useful external site?). Maybe an example use case might help?

Ok, I will do this.

**Comment by mosabua** [comment]
PR merged. Great work @gaojun2048
