### ISSUE TITLE
Document soundex function

### ISSUE THREAD

**Issue by martint** [trinodb/trino#7668]
Function added here: https://github.com/trinodb/trino/pull/4022

**Comment by mosabua** [comment]
Needs to be in list.rst and string function docs page

**Comment by Damans227** [comment]
@mosabua Hi! I would like to work on this issue. Can it please be assigned to me ? I have signed the CLA as per the steps given here: https://github.com/trinodb/cla

**Comment by mosabua** [comment]
The PR is merged now. Thank you @Damans227
