### ISSUE TITLE
Move CLI usage with Kerberos

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#7681]
From https://trino.io/docs/current/security/ldap.html#trino-cli to the actual CLI docs https://trino.io/docs/current/installation/cli.html

**Comment by mosabua** [comment]
Wasn't this on your plate at some stage @Jessie212  ..

**Comment by Jessie212** [comment]
> Wasn't this on your plate at some stage @Jessie212 ..

Yes. https://github.com/trinodb/trino/pull/12159.
