### ISSUE TITLE
Create RPM install page

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#7684]
We can use the content from https://docs.starburst.io/latest/installation/rpm.html mostly but adapt it to the Trino RPM package

**Comment by asantoz** [comment]
Hi @mosabua 
I can take it!
It should be added on this [file](https://github.com/trinodb/trino/blob/f6422d04663ab011d3ddb831ed16dec02659c47e/docs/src/main/sphinx/installation.rst)?
And for the other installation types(Docker,Tarbal...) already exits other issues to tackle it?

**Comment by mosabua** [comment]
I think we should create a separate rpm.rst file in the installation directory .. you can literally take a lot of the content from the Starburst docs .. we wrote them with this in mind..

**Comment by asantoz** [comment]
PR opened :) #7775

**Comment by mosabua** [comment]
Done now - https://trino.io/docs/current/installation/rpm.html
