### ISSUE TITLE
Document tdigest_agg function

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#7692]
Exists in list but is missing anchor and therefore link to https://trino.io/docs/current/functions/tdigest.html

**Comment by SivaTharun** [comment]
@mosabua i am a newbie to open source contribution, can i start working on this issue.

**Comment by mosabua** [comment]
Yes. Please check out the readme in the docs folder for next steps. If you end up working on this please assign the ticket to yourself and submit a PR.

**Comment by SivaTharun** [comment]
Thanks @mosabua

**Comment by jhlodin** [comment]
It doesn't look like there's movement on this issue right now, and I'm looking for a docs ticket to resolve. Assigning to myself, PR incoming soon.

**Comment by kokosing** [comment]
Fixed with https://github.com/trinodb/trino/pull/7902
