### ISSUE TITLE
Document url_extract_protocol function

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#7694]
and ensure its linked in the list

**Comment by chenjian2664** [comment]
@mosabua Hi @mosabua , I am interested in this, but do not know how to start, can you give me some suggestions?

**Comment by chenjian2664** [comment]
I think i can add some examples to this functions in file 'docs/src/main/sphinx/functions/url.rst', what's your suggestions? @mosabua

**Comment by mosabua** [comment]
That works. Mostly we need to add the missing function. You can find more info on how to write docs and such at https://github.com/trinodb/trino/tree/master/docs#readme

**Comment by mosabua** [comment]
Link from the list fixed in https://github.com/trinodb/trino/pull/7740

**Comment by mosabua** [comment]
Fixed in linked PR
