### ISSUE TITLE
jdbc connector does not support deletes and updates

### ISSUE THREAD

**Issue by 13250709979** [trinodb/trino#7699]
jdbc connector does not support deletes and updates.So far, there is no version of this function on the Internet.

What should I do if I want to support this feature?

If someone already supports this function, is it convenient to provide a code reference?

**Comment by hashhar** [comment]
See https://github.com/trinodb/trino/issues/6993.

I'm closing this because it's essentially a duplicate.
Feel free to continue the discussion on the Trino slack at https://trino.io/slack.html.
