### ISSUE TITLE
Database names with a capital letter. Clickhouse 21.1.2.15.

### ISSUE THREAD

**Issue by Saamuel** [trinodb/trino#7702]
Trino does not see databases and tables that start with a capital letter when connected to clickhouse.

direct connection to clickhouse
![image](https://user-images.githubusercontent.com/19970895/115699867-c0203b80-a36e-11eb-8c04-ce7b4912ab08.png)

trino connection
![image](https://user-images.githubusercontent.com/19970895/115700073-fcec3280-a36e-11eb-9e4c-13b9759f41d0.png)

if I create a database with lowercase letters and a table in it with lowercase letters, then trino sees everything perfectly

**Comment by ebyhr** [comment]
Could you add below config to clickhouse properties?
```
case-insensitive-name-matching=true
```

**Comment by ebyhr** [comment]
Please feel free to reopen if the above config property doesn't work.
