### ISSUE TITLE
Use a single metastore call to get tables with multiple parameters

### ISSUE THREAD

**Issue by phd3** [trinodb/trino#7710]
With https://github.com/trinodb/trino/pull/7642, table listing in iceberg connector performs two metastore calls for every schema. Looking at the documentation [here](https://github.com/apache/hive/blob/68a759a9925efe5f04d6dfe8f4a9ccc3d7a068e6/standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java#L380), we need to see the feasibility of adding a new API in `HiveMetastore` and `ThriftMetastore`, thad'd allow passing a more complex filter in one call.

**Comment by ebyhr** [comment]
Closing as the code no longer exists. Relates to #11617
