### ISSUE TITLE
Use latest version of DataStax Java Driver For Apache Cassandra instead of trino-cassandra-driver

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#7729]
**Context** 

The project trino-cassandra is currently using the trino-cassandra-driver which is a shaded version of cassandra-driver-core 3.1.4 (which dates from 2017).
The reasoning behind the choice of using a shaded version of the cassandra driver is to make it compatible with the newer version of Guava library.

**Datastax cassandra driver**

In the meantime, the Cassandra driver evolved (with minor releases being published on the maven repository every month), having the latest version 4.11.0

https://mvnrepository.com/artifact/com.datastax.oss/java-driver-core/4.11.0

**Task requirements**

Modify the trino-cassandra project to be based on the latest Datastax Cassandra driver and drop the dependency towards trino-cassandra-driver.

**Comment by hashhar** [comment]
Once the driver is updated can you please check if the workaround in https://github.com/trinodb/trino/pull/7544 (https://github.com/trinodb/trino/pull/7544/files#diff-1d4d18de4bd6e8b689f31339b09319cbbc46bc224bb4927ecf4ad96b21ef5a29R152-R154) can be removed?

The older driver doesn't implement `isNull` correctly for Timestamp types.

**Comment by findinpath** [comment]
Datastax Java Driver for Apache Cassandra® 4.11 documentation page:

https://docs.datastax.com/en/developer/java-driver/4.11/

**Comment by findinpath** [comment]
I just noticed that the cassandra driver

https://trino.io/docs/current/connector/cassandra.html

via cassandra.protocol-version supports `V2` , `V3` and `V4`


On the other hand, cassandra java driver v4 supports the protocol version `V3`, `V4` , `V5` .

https://github.com/datastax/java-driver/tree/4.x/manual/core/native_protocol


Doing these changes would involve dropping the support for protocol version `V2`

**Comment by hashhar** [comment]
From https://docs.datastax.com/en/developer/java-driver/3.5/manual/native_protocol/:

It looks only versions lower than `2.1.x` don't support protocol version 3. The first 2.1 release was in 2014 and versions older than 2.1 are no longer supported anyway.

I think it should be safe. cc: @ebyhr

**Comment by findinpath** [comment]
> Once the driver is updated can you please check if the workaround in #7544 (https://github.com/trinodb/trino/pull/7544/files#diff-1d4d18de4bd6e8b689f31339b09319cbbc46bc224bb4927ecf4ad96b21ef5a29R152-R154) can be removed?
> 
> The older driver doesn't implement `isNull` correctly for Timestamp types.

Unfortunatelly it seems that also with the new java driver v4 version the problem persists

Deleting from `io.trino.plugin.cassandra.CassandraRecordCursor#isNull` the lines:

``` 
        if (getCassandraType(i) == TIMESTAMP) {
            return currentRow.getInstant(i) == null;
        }
```

is causing the following tests to fail:

- io.trino.plugin.cassandra.TestCassandraConnectorTest#testNullAndEmptyTimestamp
- io.trino.plugin.cassandra.TestCassandraConnectorTest#testEmptyTimestampClusteringKey

both with NPE

**Comment by findinpath** [comment]
While testing the updated cassandra connector on a local trino installation CLI I noticed the following exception:

```
trino> select avg(age) from cassandra.trino.student;
Query 20210504_124046_00002_ub6qn failed: Since you provided explicit contact points, the local DC must be explicitly set (see basic.load-balancing-policy.local-datacenter in the config, or set it programmatically with SessionBuilder.withLocalDatacenter). Current contact points are: Node(endPoint=/127.0.0.1:9042, hostId=686498b0-97c2-4481-a58b-4c43124841ca, hashCode=34947c50)=datacenter1. Current DCs in this cluster are: datacenter1
```

The reference towards `basic.load-balancing-policy.local-datacenter` can be misleading for a trino user, because the user actually has only `cassandra.properties` catalog at hand for performing configuration modifcations.

Any idea how to deal with this issue?

**Comment by findinpath** [comment]
While testing the updated cassandra connector on a local trino installation CLI I noticed the following exception:

```
trino> select avg(age) from cassandra.trino.student;
Query 20210504_124046_00002_ub6qn failed: Since you provided explicit contact points, the local DC must be explicitly set (see basic.load-balancing-policy.local-datacenter in the config, or set it programmatically with SessionBuilder.withLocalDatacenter). Current contact points are: Node(endPoint=/127.0.0.1:9042, hostId=686498b0-97c2-4481-a58b-4c43124841ca, hashCode=34947c50)=datacenter1. Current DCs in this cluster are: datacenter1
```

The reference towards `basic.load-balancing-policy.local-datacenter` can be misleading for a trino user, because the user actually has only `cassandra.properties` catalog at hand for performing configuration modifcations.

Any idea how to deal with this issue?

**Comment by hashhar** [comment]
cc: @ebyhr 

I am not knowledgeable enough about Cassandra but as a user I'd like to see a default configuration that works out of the box? Is there a load balancing config that works without explicit configuration?
