### ISSUE TITLE
Presto writing to S3 with Java11, fails with java.lang.ClassNotFoundException: javax.activation.DataSource. As java 11 does not have javax.activation as part of sdk.tools anymore.

### ISSUE THREAD

**Issue by SinghAsDev** [trinodb/trino#775]
Adding this dependency would solve this issue. 

```
<dependency>
      <groupId>com.sun.activation</groupId>
      <artifactId>javax.activation</artifactId>
      <version>1.2.0</version>
</dependency>
```

**Comment by dain** [comment]
I believe this will be fixed by this PR, which is in the next release: https://github.com/prestosql/presto/pull/707

**Comment by electrum** [comment]
I'm not able to reproduce this error. Can you provide the full stack trace? You can find this from the web UI, or by running the CLI with `--debug`.

**Comment by electrum** [comment]
Also, what version of Presto are you running?

**Comment by electrum** [comment]
@SinghAsDev Can you still reproduce this? If so, please provide the stack trace

**Comment by tooptoop4** [comment]
u there @SinghAsDev ?
