### ISSUE TITLE
Add details about specifying Mbeans in JMX connector

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#7782]
From https://trinodb.slack.com/archives/CFLB9AMBN/p1619569057404100

This does not work 

```
jmx.dump-tables="java.lang:type=GarbageCollector,name=g1 old Generation"
```

You need to escape the commas, which are used to separate multiple table names. Try with:

```
jmx.dump-tables=java.lang:type=GarbageCollector\,name=g1 old Generation
```

**Comment by mosabua** [comment]
Needs to be added in https://github.com/trinodb/trino/blob/master/docs/src/main/sphinx/connector/jmx.rst in the configuration section. Arguably this is already there. Wdyt @martint

**Comment by JerryngtonD** [comment]
@mosabua it seems to be already escaped, for ex. 
`
jmx.dump-tables=trino.memory:name=general\\,type=memorypool,\
   trino.memory:name=reserved\\,type=memorypool
`

**Comment by hashhar** [comment]
@mosabua I don't think anything needs changing here.

Current example:

```properties
jmx.dump-tables=trino.memory:name=general\\,type=memorypool,\
    trino.memory:name=reserved\\,type=memorypool
```

gets read as two tables `trino.memory:name=general,type=memorypool` and `trino.memory:name=reserved,type=memorypool` which is correct and expected.

The suggested change:

```properties
jmx.dump-tables=trino.memory:name=general\\,type=memorypool\\,trino.memory:name=reserved\\,type=memorypool
```

gets read as a single table `trino.memory:name=general,type=memorypool,trino.memory:name=reserved,type=memorypool`.

However it might be useful to change the example to remove the newline being escaped which causes confusion IMO.
Or there should be two examples - one about escaping `,` - the other about other escaping that's needed in a Java `properties` file.

**Comment by hashhar** [comment]
@mosabua Is there anything to do here? Apart from maybe:

> However it might be useful to change the example to remove the newline being escaped which causes confusion IMO.
> Or there should be two examples - one about escaping , - the other about other escaping that's needed in a Java properties file.
