### ISSUE TITLE
BigQuery connector does not modify single quote escape characters

### ISSUE THREAD

**Issue by patmagee** [trinodb/trino#7784]
BigQuery and Trino do not share the same single quote escape semantics leading to a situation where it is impossible to query a Datasets in BigQuery when there is a single quote in your query criteria. The canonical way of escaping a single quote character within a string in ANSI SQL is to use two single quotes, `''`, a feature which Trino supports. Unfortunately,  BigQuery requires a double backslash escape character `\\'`. When a query containing an escaped string is pushed down to the BigQuery connector, these strings are not re-written  according to the BigQuery escape semantics

For example, say I have the following table: `foo.bar.users` in BigQuery, and i would like  to filter all users  who live on the street 'Looney's Lane'. There does not appear to be any valid way of actually performing this action without somehow turning off predicate pushdown for a part of the query and loading the entirety of the dataset (I have not actually be able to do this). I have tried many different variations of the following queries (even trying to use `CONCAT(...,CHR(39),...)` all to no avail.

**Trino SQL:**
```sql
SELECT 
  *
FROM foo.bar.users
WHERE
  address = 'Looney''s Lane'
LIMIT 10
```

One would think this should work properly, however running this would result in the following error code:
```
Query 20210428_143644_00004_yegf9 failed: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: request failed: Row filter for table my_project.bar.users is invalid. Filter is '(`address` = 'Looney's Lane')'
```

**Expected BigQuery SQL**
```sql
SELECT 
  *
FROM foo.bar.users
WHERE
  address = 'Looney\\'s Lane''
LIMIT 10
```

Conversely if you try to make BigQuery happy and run the above query you receive a parse error from Trino:
```
Query 20210428_144620_00007_yegf9 failed: line 1:22: mismatched input 's'. Expecting: '%', '*', '+', '-', '.', '/', 'AND', 'AT', 'EXCEPT', 'FETCH', 'GROUP', 'HAVING', 'INTERSECT', 'LIMIT', 'OFFSET', 'OR', 'ORDER', 'UNION', 'WINDOW', '[', '||', <EOF>
```

### Expected Behaviour

What one would expect is for the BigQuery connector to properly rewrite filter values containing the ANSI SQL single quote Escape sequence (or any other special sequences) into one that BigQuery is happy with. 

```
'Looney''s Lane' ->  'Looney\\'s Lane'
```

**Comment by patmagee** [comment]
A potential ugly workaround we found seems to be casting the column name and the value to a varbinary using `to_utf8`.

```sql
SELECT 
  *
FROM foo.bar.users
WHERE
  to_utf8(address) = to_utf8('Looney''s Lane')
LIMIT 10
```

**Comment by ayushbilala** [comment]
I was able to replicate the issue and would like to work on adding a fix.
@ebyhr Is it fine if I pick it up?

**Comment by ebyhr** [comment]
@ayushbilala Sure, go for it!

**Comment by hashhar** [comment]
@ayushbilala you might find this conversation on the Trino slack helpful while working on the fix.

https://trinodb.slack.com/archives/CGB0QHWSW/p1619726125358600?thread_ts=1619723632.356200&cid=CGB0QHWSW

**Comment by ayushbilala** [comment]
@hashhar Sure, I'll take a look.
