### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by seven7777777** [trinodb/trino#7800]
trino: tag 355
java: openjdk version "11.0.11" 2021-04-20 LTS

Failed info:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project trino-spi: Fatal error compiling: error: release version 11 not supported

**Comment by hashhar** [comment]
Please verify what version of Java is Maven trying to use.
You can check that via `./mvnw --version`. Also note that the version of Java used must be >= 11.0.7. Older versions have some JVM bugs which can cause the build to fail.

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/hashhar/.m2/wrapper/dists/apache-maven-3.6.3-bin/lm9vem38rfmjij3jj0mk5bvnt/apache-maven-3.6.3
Java version: 11.0.11, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
Default locale: en_IN, platform encoding: UTF-8
OS name: "mac os x", version: "11.3", arch: "x86_64", family: "mac"
```

It is generally faster to get help on such issues on the Trino slack. Feel free to join the slack and continue this discussion there.

**Comment by seven7777777** [comment]
well , moving to zulu open jdk 11, it works.
