### ISSUE TITLE
Remove table layouts from all connectors

### ISSUE THREAD

**Issue by electrum** [trinodb/trino#781]
Add a comment about which one you are working on. Each one should be done as a separate commit and PR, since they are unrelated, and some will be non-trivial or will require additional features like column projection pushdown.

- [x] Accumulo (#823)
- [x] Atop (#885)
- [x] Cassandra (#1004)
- [x] Elasticsearch (#883)
- [x] Hive (#689)
- [x] Jmx (#511)
- [x] Kafka (#881)
- [x] Kudu (#1721)
- [x] LocalFile (#880)
- [x] Mongo (#884)
- [x] Phoenix (#3383)
- [x] Raptor (#1015)
- [x] Redis (#882)
- [x] Thrift (#2009)
- [ ] Tpcds (#9628)
- [x] Tpch (#787)

**Comment by Praveen2112** [comment]
@electrum Can I take up this issue ?

**Comment by electrum** [comment]
@Praveen2112 Yes, but work on one at a time, and comment here first about which one you are doing. Some of these will be non-trivial or may require additional features (like column projection pushdown which is not yet implemented in the new model).

**Comment by Praveen2112** [comment]
@electrum I will be starting with the Tpch and Tpcds connector

**Comment by Praveen2112** [comment]
I am working on removing table layouts from Accumulo connector.

**Comment by Praveen2112** [comment]
Next I am trying to remove for Atop connector.

**Comment by Praveen2112** [comment]
Next I'm planning to take cassandra and raptor connector.

**Comment by Praveen2112** [comment]
Once #676 is merged we can remove TableLayout for Kudu and Thrift connector

**Comment by findepi** [comment]
In the project i see `TpchTableLayoutHandle` and `TpcdsTableLayoutHandle` classes, so we're almost migrated.

Do we have a plan to do something with `io.trino.spi.connector.ConnectorMetadata#usesLegacyTableLayouts`?
It currently returns false.

Removing support for layouts would simplify things in the engine.

**Comment by martint** [comment]
There was some issue with the TPC-DS connector due to limitations of the optimizer. @Praveen2112, do you remember?

Once those are migrated, we can just go ahead and remove the old API. It’s been almost two years since we deprecated it.
