### ISSUE TITLE
Doc for sessionUser in JDBC driver

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#7822]
See https://trinodb.slack.com/archives/CFLB9AMBN/p1620012644008500

https://github.com/trinodb/trino/pull/6549

Setting connection parameter properties.setProperty("sessionUser", sessionUser);

**Comment by SivaTharun** [comment]
@mosabua @findepi can i work on this issue, for adding the  document related to JDBC driver connection parameters.

**Comment by mosabua** [comment]
Definitely. Should be added in https://trino.io/docs/current/installation/jdbc.html#parameter-reference

**Comment by ebyhr** [comment]
@electrum added in #8799
