### ISSUE TITLE
Upgrade Postgres connector incompatible with newer drivers

### ISSUE THREAD

**Issue by dain** [trinodb/trino#7823]
PostgreSQL connector does not work with newer drivers due to fixes to handle of

- [ ] multidimensional arrays (>= 42.2.14)
- [x]  numeric types (>= 42.2.11) (https://github.com/trinodb/trino/pull/9517)

To reproduce simply update to latest driver and run `TestPostgreSqlTypeMapping`

**Comment by wendigo** [comment]
Solved by https://github.com/trinodb/trino/pull/9847
