### ISSUE TITLE
CREATE TABLE AS does not work with timestamp(9) columns when transferring between hive catalogs

### ISSUE THREAD

**Issue by alec-heif** [trinodb/trino#7849]
The following seems to be a bug with the way the `hive.timestamp_precision` property is forwarded when a CREATE TABLE AS is run from one hive catalog to a different hive catalog.

Steps to reproduce (on Trino 354):

1. Have two hive catalogs, `hive` and `hive2`. Do not override the `hive.timestamp-precision` property in either catalog config so that both use `MILLISECONDS`.
2. Create a table `hive.default.foo` with a `TIMESTAMP(9)` datatype using an inline session property of `hive.timestamp_precision=NANOSECONDS` and a format of `ORC`.
3. Confirm using `DESCRIBE hive.default.foo` that the type is `TIMESTAMP(9)`, again making sure to use an inline session property of `hive.timestamp_precision=NANOSECONDS`
4. Do a `CREATE TABLE hive2.default.bar AS (SELECT * FROM hive.default.foo)` once again using `hive.timestamp_precision=NANOSECONDS`
5. Observe the following stack trace:

```
io.trino.spi.TrinoException: Incorrect timestamp precision for timestamp(9); the configured precision is MILLISECONDS 	at io.trino.plugin.hive.HiveMetadata.validateTimestampTypes(HiveMetadata.java:2883) 	at io.trino.plugin.hive.HiveMetadata.validateTimestampColumns(HiveMetadata.java:2875) 	at io.trino.plugin.hive.HiveMetadata.getNewTableLayout(HiveMetadata.java:2587) 	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getNewTableLayout(ClassLoaderSafeConnectorMetadata.java:137) 	at io.trino.metadata.MetadataManager.getNewTableLayout(MetadataManager.java:807) 	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitCreateTableAsSelect(StatementAnalyzer.java:757) 	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitCreateTableAsSelect(StatementAnalyzer.java:343) 	at io.trino.sql.tree.CreateTableAsSelect.accept(CreateTableAsSelect.java:96) 	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27) 	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:360) 	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:323) 	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:91) 	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:83) 	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:263) 	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:186) 	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:768) 	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:129) 	at io.trino.$gen.Trino_354____20210504_165846_2.call(Unknown Source) 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125) 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69) 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78) 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 	at java.base/java.lang.Thread.run(Thread.java:834)
```

Note that I confirmed in the Trino UI that this query did receive the desired `hive.timestamp_precision=NANOSECONDS` parameter (see image) so I'm not sure why it's thinking that the configured precision is still `MILLISECONDS` - are session properties that affect a specific catalog type not supported when transferring data between two catalogs?

<img width="581" alt="Screen Shot 2021-05-06 at 2 50 50 PM" src="https://user-images.githubusercontent.com/5010391/117351125-58dcae00-ae7b-11eb-8950-dfa9d2c23057.png">

**Comment by alec-heif** [comment]
edit: I did some experimenting and I realized that I was misunderstanding session properties.

setting `hive2.timestamp_precision=NANOSECONDS` as an additional session property to the query did the right thing!

We can close this out, although it might be worth clarifying in the docs that the `hive.<session_property>` inline setting only actually works if the connector is named `hive`.

**Comment by hashhar** [comment]
It's documented but not within each connector's docs. https://trino.io/docs/current/sql/set-session.html

cc: @mosabua Any ideas how we could improve this? Would making use of non-default catalog names in examples clarify it? Similar to the notes we add about replacing the catalog name in the example queries if your catalog properties file is named differently?

**Comment by mosabua** [comment]
We have been moving to changing the catalog names in the connector docs to be different from the connector.name .. this has been a common problem. And we should move that out more and more to all connectors. PRs for that are welcome.
