### ISSUE TITLE
Use username/password authentication in MongoDB docker tests

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#7854]
Currently, there is no authentication in our MongoDB tests. 
Setting `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD` environment variables enable auth in MongoDB docker. https://hub.docker.com/_/mongo

**Comment by sachindavra** [comment]
Hi @ebyhr, Thanks for explaining this.
I think coding is in other than python. I am not familiar with this syntax. Apology for this.

**Comment by amyma1** [comment]
Hi @ebyhr,
I'm completely new to open-source and would like to contribute to this please! :)

**Comment by ebyhr** [comment]
@sachindavra Do you mind if @amyma1 takes over this?

**Comment by sachindavra** [comment]
@ebyhr, Please go ahead.

**Comment by amyma1** [comment]
Thanks!  @ebyhr can I begin working on this or should I wait for it to be assigned to me?

**Comment by hashhar** [comment]
@amyma1 go for it. Thanks for picking this up.

**Comment by AshwinC137** [comment]
@ebyhr , @hashhar can I look into this issue? I am a newbie but I think I can help.

**Comment by ebyhr** [comment]
Closed as #14988
