### ISSUE TITLE
Migrate CaseInsensitiveMapping tests to BaseCaseInsensitiveMappingTest

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#7864]
`BaseCaseInsensitiveMappingTest` was added in #7909 and some connectors' tests (PostgreSQL, MySQL and SQL Server) are already migrated to use it.

The following must also be migrated to use `BaseCaseInsensitiveMappingTest`:

- [x] TestOracleCaseInsensitiveMapping
- [ ] TestBigQueryCaseInsensitiveMapping
- [x] TestMemSqlCaseInsensitiveMapping

**Comment by hashhar** [comment]
`BaseCaseInsensitiveMappingTest` was added in https://github.com/trinodb/trino/pull/7909.

Re-purposing this issue to track migrating remaining connectors to this base test.

**Comment by hashhar** [comment]
- [ ] TestOracleCaseInsensitiveMapping
- [ ] TestBigQueryCaseInsensitiveMapping
- [ ] TestMemSqlCaseInsensitiveMapping

**Comment by findepi** [comment]
@hashhar please move the checklist to the issue description.

**Comment by OLMS99** [comment]
Howdy, any problem with me helping with this issue?

**Comment by kokosing** [comment]
We would be delighted.

**Comment by hashhar** [comment]
Oracle and MemSQL done in https://github.com/trinodb/trino/pull/11250.

BigQuery is out of scope since it doesn't use / support file-based mappings.
