### ISSUE TITLE
Document metadata.cache-ttl properties to JDBC based connector

### ISSUE THREAD

**Issue by xwzpp** [trinodb/trino#7873]
According to the slow SQL query of Druid, the query frequency of metadata is high. We want to know whether the metadata is cached and how often the query frequency is.

SELECT
  TABLE_CATALOG AS TABLE_CAT,
  TABLE_SCHEMA AS TABLE_SCHEM,
  TABLE_NAME AS TABLE_NAME,
  COLUMN_NAME AS COLUMN_NAME,
  CAST(JDBC_TYPE AS INTEGER) AS DATA_TYPE,
  DATA_TYPE AS TYPE_NAME,
  -1 AS COLUMN_SIZE,
  -1 AS BUFFER_LENGTH,
  -1 AS DECIMAL_DIGITS,
  -1 AS NUM_PREC_RADIX,
  CASE IS_NULLABLE WHEN 'YES' THEN 1 ELSE 0 END AS NULLABLE,
  CAST(NULL AS VARCHAR) AS REMARKS,
  COLUMN_DEFAULT AS COLUMN_DEF,
  -1 AS SQL_DATA_TYPE,
  -1 AS SQL_DATETIME_SUB,
  -1 AS CHAR_OCTET_LENGTH,
  CAST(ORDINAL_POSITION AS INTEGER) AS ORDINAL_POSITION,
  IS_NULLABLE AS IS_NULLABLE,
  CAST(NULL AS VARCHAR) AS SCOPE_CATALOG,
  CAST(NULL AS VARCHAR) AS SCOPE_SCHEMA,
  CAST(NULL AS VARCHAR) AS SCOPE_TABLE,
  -1 AS SOURCE_DATA_TYPE,
  'NO' AS IS_AUTOINCREMENT,
  'NO' AS IS_GENERATEDCOLUMN
FROM
  INFORMATION_SCHEMA.COLUMNS
WHERE COLUMNS.TABLE_CATALOG = 'druid' AND COLUMNS.TABLE_SCHEMA LIKE 'druid' ESCAPE '\' AND COLUMNS.TABLE_NAME LIKE U&'mnet\002Dnetstream\002Dtop' ESCAPE '\'
ORDER BY
  TABLE_CAT, TABLE_SCHEM, TABLE_NAME, ORDINAL_POSITION

**Comment by ebyhr** [comment]
Metadata cache is disabled by default in JDBC based connectors. There is `metadata.cache-ttl` (duration) properties.

**Comment by mosabua** [comment]
This is documented now. This PR added it to all connectors it applies to.

https://github.com/trinodb/trino/pull/7834
