### ISSUE TITLE
Trino select query slow

### ISSUE THREAD

**Issue by Hubert-Tiket** [trinodb/trino#7958]
Query stuck when using subquery on trino on large database (around 100m data), but it works fine on mysql or on smaller database.

Trino can't finish the query, stuck at 40-60% when executing the query

```sql
SELECT *
FROM table1
WHERE id1 = (SELECT id1 FROM table1 WHERE id2 IN ('123456') AND id1 != '' LIMIT 1)
   OR id2 IN ('123456');
```

However, executing this query in mysql returns the result in 2-3 seconds and it also works on smaller database.

Another interesting problem was even if the `id1` was hardcoded like this

```sql
SELECT *
FROM table1
WHERE id1 = 'asd123'
   OR id2 IN ('123456');
```

Trino will still run so slow, on the console it runs at around 500-600 rows/sec which will be done in around 5 hours for 100m data
<img width="716" alt="Screen Shot 2021-05-18 at 16 29 19" src="https://user-images.githubusercontent.com/79558182/118627981-5c1a5700-b7f6-11eb-8c95-ae35f3bde46c.png">

Environtment:
- MySql 5.7.24
- Trino v356

Config.properties:
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery-server.enabled=true
discovery.uri=http://localhost:8080
query.low-memory-killer.policy=total-reservation
optimizer.dictionary-aggregation=false
optimizer.optimize-hash-generation=false
optimizer.optimize-metadata-queries=false
optimizer.push-aggregation-through-outer-join=false
optimizer.push-table-write-through-union=true
optimizer.join-reordering-strategy=NONE
optimizer.optimize-duplicate-insensitive-joins=false
optimizer.use-table-scan-node-partitioning=false

Even if we use **other config** (like default config), the result is the same.

**Comment by hashhar** [comment]
@Hubert-Tiket `OR` predicate pushdown isn't implemented in the engine yet. Can you try with a query that doesn't use an `OR` predicate?

Feel free to continue the conversation on our [Slack](https://trino.io/slack.html) or re-open the issue if you prefer here.
