### ISSUE TITLE
README.txt is pointing to prestosql.io where as it should be trino.io

### ISSUE THREAD

**Issue by prabhacloud** [trinodb/trino#8024]
Latest Trino version downloaded from here https://www.starburst.io/platform/starburst-enterprise/download/ has old website instead of trino.io
Version presto-server-350-e.7

**Comment by findepi** [comment]
Thanks @prabhacloud for letting us know.
Since this seems to be Starburst's issue, and not really Trino project's let me close this.

@mosabua @joshthoward can you please take care of fixing this?

@prabhacloud thanks again!

**Comment by mosabua** [comment]
We are working on a fix. Thank you for reporting.
