### ISSUE TITLE
Document updated Postgres requirements

### ISSUE THREAD

**Issue by m57lyra** [trinodb/trino#8035]
Discontinue support for PostgreSQL 9.5, which has reached end of life. (#7676)

**Comment by findinpath** [comment]
I think this one can be closed as it has been done already by @mosabua  in https://github.com/trinodb/trino/blob/master/docs/src/main/sphinx/connector/postgresql.rst#requirements

**Comment by mosabua** [comment]
Yes... correct. Thanks for noticing @findinpath
