### ISSUE TITLE
Document ConnectorMaterializedViewDefinition

### ISSUE THREAD

**Issue by m57lyra** [trinodb/trino#8038]
355: Engine now uses ConnectorMaterializedViewDefinition#storageTable to determine materialized view storage table. (#7319)
356: Require that ConnectorMaterializedViewDefinition provides a view owner. (#7489)

**Comment by sopel39** [comment]
Do we want to document SPI methods?

**Comment by findepi** [comment]
@sopel39 https://trino.io/docs/current/develop.html

**Comment by raunaqmorarka** [comment]
https://trino.io/docs/current/develop/connectors.html#connectormetadata
```
This interface is too big to list in this documentation
```
To document ConnectorMaterializedViewDefinition, we would need to start documenting ConnectorMetadata to provide the relevant context.

**Comment by mosabua** [comment]
Lets close this
