### ISSUE TITLE
Support multilingual encoding in property files

### ISSUE THREAD

**Issue by songgane** [trinodb/trino#8096]
Trino supports LDAP by external password authentication method.

However if ldap.user-bind-pattern value of the LDAP configuration file is not an English value, there is a bug that can not be read properly.

Trino is used in various countries and support external authentications. So multilingual encoding support is required.

ex)
configuration value : ldap.user-bind-pattern=OU=사용자,DC=example,DC=com
compiled value : OU=ì�¬ì�©ì��,DC=example,DC=com

**Comment by songgane** [comment]
I posted a Trino PR on this issue. At the request of @kokosing , I re-posted a PR(https://github.com/airlift/airlift/pull/921) to airlift.

**Comment by findepi** [comment]
@songgane did you try using Properties file unicode escapes for your value?
see eg https://stackoverflow.com/questions/6230190/convert-international-string-to-u-codes-in-java

**Comment by songgane** [comment]
@findepi Thank you. After converting values using native2ascii, I confirmed that the multilingual value in the property file was correctly read.
But I also think it is a good alternative to help reading multilingual encoding values in properties files without a separate conversion process.

**Comment by songgane** [comment]
This PR will close because there is an alternative to native2ascii and a backward compatibility issue may occur.
