### ISSUE TITLE
Add Apache Ignite connector

### ISSUE THREAD

**Issue by yangliang9004** [trinodb/trino#8098]
Apache Ignite is a distributed database for high-performance computing with in-memory speed.

Ignite play an important role in our platform, it is powerful.

Do you consider developing trino-ignite ?

website:   https://ignite.apache.org/

**Comment by kokosing** [comment]
> Do you consider developing trino-ignite ?

I am not aware of anyone working on this. However, we are open for any contributions like this and I would be happy to give it a review.

**Comment by yangliang9004** [comment]
Good ! I am glad to hava a try.

**Comment by tooptoop4** [comment]
@yangliang9004 ignite connector is mentioned on https://github.com/trinodb/trino/issues/3472
