### ISSUE TITLE
Support setting Kafka consumer group ID

### ISSUE THREAD

**Issue by afilimonov** [trinodb/trino#8110]
It appears there is no way to set Kafka consumer group ID in the Kafka Connector. Seems like the group.id is set to null.

```
...
fetch.min.bytes = 1
group.id = null
group.instance.id = null
heartbeat.interval.ms = 3000
...
```

**Comment by afilimonov** [comment]
Am I missing something here? I would be surprised that such a basic feature like defining consumer group id is not supported by the Kafka plugin.

**Comment by hashhar** [comment]
The Kafka connector doesn't need to commit offsets and handles the distribution of messages across workers itself (by splitting each topic-partition into a groups of offset ranges). So there's no reason to use a consumer group.

In case you want this for setting quotas or tracking usage on Kafka there is an issue open for setting `client.id` which is what's recommended. See #7633.

**Comment by afilimonov** [comment]
Our Kafka environment uses ACLs with prefixed group ids therefore we need to set consumer group. In this case perhaps Trino is not a right tool for us at least not for querying Kafka data.

**Comment by afilimonov** [comment]
Unfortunately this is a fully managed Kafka environment we don't have much control over ACL policies. We are not giving up yet thanks for the suggestion.

**Comment by afilimonov** [comment]
Is it possible to generate  a unique prefixed consumer group for each query execution?
