### ISSUE TITLE
trino spi moudle mvn install error

### ISSUE THREAD

**Issue by lucasaytt** [trinodb/trino#8114]
![image](https://user-images.githubusercontent.com/42641861/119924309-ebb5c780-bfa5-11eb-9c78-60fa750a79f7.png)
****

**Comment by findepi** [comment]
i recommend to always run `clean install`, as the incremental compilation may have issues:

```
./mvnw clean install -DskipTests
```

If this doesn't help, we can continue here, or on project slack. see you there!
