### ISSUE TITLE
druid LATEST function cannot support by druid connector

### ISSUE THREAD

**Issue by xwzpp** [trinodb/trino#8140]
druid LATEST function cannot support by druid connector

**Comment by findinpath** [comment]
I assume that you imply 

```

LATEST(expr) | Returns the latest value of&nbsp;expr, which must be numeric. If&nbsp;expr&nbsp;comes from a relation with a timestamp column (like a Druid datasource) then "latest" is the value last encountered with the maximum overall timestamp of all values being aggregated. If&nbsp;expr&nbsp;does not come from a relation with a timestamp, then it is simply the last value encountered.
````

taken from https://druid.apache.org/docs/0.21.0/querying/sql.html


However Trino supports only the following functions at the moment: 

https://trino.io/docs/current/functions/list.html

**Comment by hashhar** [comment]
This requires supporting function pushdown and expression pushdown. Some work on those fronts is ongoing in https://github.com/trinodb/trino/pull/7994.

Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there on #dev to learn about the plans and how you can contribute.

**Comment by jerryleooo** [comment]
@hashhar glad to see the function/expression pushdown is considered, may I know if there is an overall roadmap for this? So we can see what progress it is right now. I guess some work still needs to do after #7994 merged?
