### ISSUE TITLE
CI's setup-java sometimes fails with: Unexpected EOF in archive

### ISSUE THREAD

**Issue by ssheikin** [trinodb/trino#8146]
Extracted from https://github.com/trinodb/trino/issues/5033

```
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/temp_1541730422 -f /home/runner/work/_temp/5d973049-8f2c-43f8-88f5-50f1667239af

gzip: stdin: unexpected end of file
/usr/bin/tar: Unexpected EOF in archive
/usr/bin/tar: Unexpected EOF in archive
/usr/bin/tar: Error is not recoverable: exiting now
Error: The process '/usr/bin/tar' failed with exit code 2
```
noticed here: https://github.com/trinodb/trino/pull/8108/checks?check_run_id=2709868896

**Comment by hashhar** [comment]
https://github.com/trinodb/trino/runs/2710240871?check_suite_focus=true

**Comment by findepi** [comment]
@ssheikin  Is this some archive downloaded over the network, or created locally?
if the latter, did we run out of disk space?

**Comment by ssheikin** [comment]
@findepi I've force pushed branch and now `No check run found with ID 2709868896 for this pull request.`

**Comment by Praveen2112** [comment]
I guess we can update the setup java action to the latest version 2.0 .. which supports retries in case of failure due to network

**Comment by findepi** [comment]
> noticed here: https://github.com/trinodb/trino/pull/8108/checks?check_run_id=2709868896

@ssheikin i guess the correct link would be https://github.com/trinodb/trino/runs/2709868896

@Praveen2112 thanks, i didn't know we're talking about java setup step

**Comment by findepi** [comment]
@Praveen2112 can you make a PR?

**Comment by Praveen2112** [comment]
Working on it.
