### ISSUE TITLE
system.metadata.catalogs returns catalog name as the connector_id

### ISSUE THREAD

**Issue by raunaqmorarka** [trinodb/trino#8150]
After setting up a `hive-hadoop2` connector with catalog name `hive_abd` I got

```
trino> select * from system.metadata.catalogs;
 catalog_name | connector_id
--------------+--------------
 blackhole    | blackhole
 druid        | druid
 example      | example
 hive_abd     | hive_abd
```

**Comment by kokosing** [comment]
That is ok. I guess connector id column is legacy and I think we could try to remove it. 

The idea behind it was to have unique connector instance id. So if connector would be unregistered and registered under the same catalog name it could get different connector id. However the idea of dynamically unregistering catalogs died as it is very difficult to achieve.

**Comment by raunaqmorarka** [comment]
I see, I got the impression that connector id would give the connector's name like `hive-hadoop2` and we might be able to get all `hive-hadoop2` connector's catalog names using this table.
Would it make sense to repurpose connector id to give connector name ?
cc: @sopel39

**Comment by kokosing** [comment]
I think we could add another column `connector_name` as independent to `connector_id`.

**Comment by electrum** [comment]
@dain thoughts here? Probably we should just drop that column?

We could add a `connector_name` field if that is useful, though let's file a separate issue for that.

**Comment by ebyhr** [comment]
Closing as #9691
