### ISSUE TITLE
elasticsearch query bug

### ISSUE THREAD

**Issue by zhangfangkai** [trinodb/trino#8158]
when I query elasticsearch use trino, there is  a bug
my query is :
`SELECT table_schema FROM columns WHERE elasticsearch.information_schema.table_schema = 'default'`
then i meet the bug: Multiple entries with same key
In my elasticsearch, there are many indexes alias one name, eg:
index |  alias_name
aa-000000 -->aa
aa-000001 -->aa
i think  there is some bug in io.trino.plugin.elasticsearch.ElasticsearchMetadata.listTable method

**Comment by sumannewton** [comment]
Please be more specific about what the bug is.
Also refer [issue-2748](https://github.com/trinodb/trino/issues/2748). You might be facing the same issue.

**Comment by sumannewton** [comment]
> Please be more specific about what the bug is.
> Also refer [issue-2748](https://github.com/trinodb/trino/issues/2748). You might be facing the same issue.

This issue is different from [issue-2748](https://github.com/trinodb/trino/issues/2748). Able to reproduce this issue with the fixes for [issue-2748](https://github.com/trinodb/trino/issues/2748). Will try to debug more and fix this in my free time.

**Comment by sumannewton** [comment]
I have fixed this in my local.
**Issue:**
Many indices aliased to single alias is causing this problem.
**RCA:**
Both`ElasticsearchClient.getAliases()` and `ElasticsearchMetadata.listTables()` have got flaws.
https://github.com/trinodb/trino/blob/f4cc1fb6a8fde26e2cd4e7d460f6661e566d170d/plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/ElasticsearchClient.java#L497-L519

`getAliases()` computes and returns Map(Index, List(Alias)). This results in many indices having the same alias.

https://github.com/trinodb/trino/blob/f4cc1fb6a8fde26e2cd4e7d460f6661e566d170d/plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java#L337-L357

But in `listTables()` we map to every Map's entry to `SchemaTableName`. That's resulted in duplicate tables.

**FIX**:
Return a Map(Alias, List(Indices)) from `getAliases()`.
Map each entry to `SchemaTableName`.

@bitsondatadev @findepi @aalbu Thoughts?
