### ISSUE TITLE
Trino/Presto UI does not respect show limit when query state filter is changed 

### ISSUE THREAD

**Issue by cpsnowden** [trinodb/trino#8185]
When you change a query state filter e.g. showing 'Finished' queries or 'User Error' queries, the Show Limit is not respected immediately resulting in all queries being rendered. If a re-order interval is set then Show Limit is applied on the next query refresh. If there are a large number of queries in the history this can result in the browser crashing on the first render.

The following two calls to sortAndLimitQueries looks like they are missing a last parameter of this.state.maxQueries resulting in no limit being applied

https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/resources/webapp/src/components/QueryList.jsx#L512
https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/resources/webapp/src/components/QueryList.jsx#L544

**Comment by hashhar** [comment]
Thanks for reporting this @cpsnowden. Would you like to submit a pull-request yourself - we can guide you through the process.

**Comment by cpsnowden** [comment]
Yep - can contribute a PR for this
