### ISSUE TITLE
List of functions per topic

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#8189]
It might be useful to have a page that lists all functions similar to list.rst

But instead of alphabetical order it should use the topics from the different groups we already have defined like datetime, array and so on (see https://trino.io/docs/current/functions.html) and under each group list the functions covered in that specific document.

We could play around and check how that works out and how useful it is. I will organize a session for this. Ping me if you are interested to hack on this together with me and @jessie212

**Comment by mosabua** [comment]
We are working on this together next week. If anyone is interested to join the hacking session at 10am PST on Wed (2021-06-09) reach out to me on slack and I can add you to the invite.

**Comment by Jessie212** [comment]
> 
> 
> It might be useful to have a page that lists all functions similar to list.rst
> 
> But instead of alphabetical order it should use the topics from the different groups we already have defined like datetime, array and so on (see https://trino.io/docs/current/functions.html) and under each group list the functions covered in that specific document.
> 
> We could play around and check how that works out and how useful it is. I will organize a session for this. Ping me if you are interested to hack on this together with me and @Jessie212

Absolutely.

**Comment by ebyhr** [comment]
Going to close because we already have https://trino.io/docs/current/functions/list-by-topic.html
