### ISSUE TITLE
SASL_SSL and additional Kakfka property support

### ISSUE THREAD

**Issue by ashishmgofficial** [trinodb/trino#8197]
Support for SASL_SSL secure properties for kafka connector. Some of the properties of interest are : 
```
kafka.sasl.jaas.config
kafka.security.protocol=SASL_SSL
kafka.sasl.mechanism=PLAIN
kafka.sasl.username
kafka.sasl.password
kafka.group.id
basic.auth.credentials.source
basic.auth.user.info
```
I think these are all basic configs supported by kafka driver.

**Comment by klDen** [comment]
This is now supported with the linked merged PR.

**Comment by subbareddydagumati** [comment]
@klDen Does it support SASL SSL GSSPAI. If so, Can you please provide the list of properties we need to pass in the external config file

**Comment by subbareddydagumati** [comment]
nm. Found the sample. It's working. Thanks alot for working on this. It's an amazing feature.
```
security.protocol=SASL_SSL
sasl.mechanism=GSSAPI
ssl.truststore.type=JKS
ssl.truststore.location=/etc/trino/kafka_config/truststore.jks
ssl.truststore.password=
sasl.kerberos.service.name=kafka
```
Added jaas file to jvm.config
```
-Djava.security.krb5.conf=/etc/trino/krb5.conf
-Djava.security.auth.login.config=/etc/trino/kafka_config/jaas.conf
```

**Comment by subbareddydagumati** [comment]
@klDen 
Is there a way to pass the jaas file in kafka.config.resources

**Comment by klDen** [comment]
Seems like you can (first option): https://docs.confluent.io/platform/current/kafka/authentication_sasl/index.html#jaas-configurations.
