### ISSUE TITLE
Support views (CREATE VIEW) in Iceberg connector

### ISSUE THREAD

**Issue by esemeniuc** [trinodb/trino#8216]
Hi all, when using iceberg catalog and creating a view, I see this:

```
presto:partition_demo_iceberg> create OR REPLACE view sfms_cpustats as (SELECT * FROM sfms_cpustats_daily);
Query 20210607_203635_03250_hfqhn failed: This connector does not support creating views
```

I noticed this line about view support: https://github.com/trinodb/trino/blob/e4cae791c0b56509af281ceb7b91bc7c62dce6e5/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java#L1035
Can view support be added, or is there a fundamental issue with views and iceberg?

**Comment by raunaqmorarka** [comment]
You can simply use MATERIALIZED VIEW. It behaves like a VIEW if you don't run REFRESH MATERIALIZED VIEW query on it.
@electrum might have more thoughts about explicit support of VIEW in iceberg.

**Comment by findepi** [comment]
> You can simply use MATERIALIZED VIEW. It behaves like a VIEW if you don't run REFRESH MATERIALIZED VIEW query on it.

nice workaround, thanks @raunaqmorarka for sharing.

Another workaround is to define a view via Hive connector, but reference Iceberg catalog in the view body. Not as useful, but may be helpful in some cases.

We should just add support for views ("trino views") in Iceberg. This is pretty straightforward, and Hive connector can be used as an example.

**Comment by jetsasank** [comment]
@findepi : Its been a while since I contributed, may I help with adding the support for views ?

**Comment by jetsasank** [comment]
Great, I will assign this issue to myself and start working on a solution.

**Comment by losipiuk** [comment]
Hi @jetsasank are you still working on this issue? I wanted to dig into that, but if you have in flight it would be great to not duplicate work.

**Comment by ebyhr** [comment]
Closing as #8540
