### ISSUE TITLE
trino-358 build failed

### ISSUE THREAD

**Issue by AllenWod** [trinodb/trino#8249]
env:
jdk 11.0.11
maven 3.8.1

follow by readme.md
![image](https://user-images.githubusercontent.com/22765507/121460846-44428700-c9e0-11eb-9c3d-b9a7dbe94544.png)

**Comment by hashhar** [comment]
It looks like you are checking out the project in some way that the `.git` directory is missing. Are you using git worktree? Did you clone the project or download the tarball/zip of the code?

Please join our [Slack](https://trino.io/slack.html) and continue the conversation there on the #dev or #troubleshooting channels. There are more people there and you would get help quicker.

**Comment by AllenWod** [comment]
yeal ,I have just download the zip code and import into InteliJ Idea to build.thanks for you answer

**Comment by hashhar** [comment]
Please try using `git clone` instead of a zip download and it should work.
Closing the issue - but feel free to continue the discussion if you still run into issues.

Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there.

**Comment by AllenWod** [comment]
> Please try using `git clone` instead of a zip download and it should work.
> Closing the issue - but feel free to continue the discussion if you still run into issues.
> 
> Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there.

ok thanks very much

**Comment by AllenWod** [comment]
> Please try using `git clone` instead of a zip download and it should work.
> Closing the issue - but feel free to continue the discussion if you still run into issues.
> 
> Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there.

Can i execute git init in trino-358 directory to make it effective?

**Comment by hashhar** [comment]
I don't think so. You'll need to perform a fresh clone. `git clone https://github.com/trinodb/trino`

**Comment by AllenWod** [comment]
> I don't think so. You'll need to perform a fresh clone. `git clone https://github.com/trinodb/trino`

thanks for your guide，I have successfully build，but i don't know how to execute next step，can you help me
![image](https://user-images.githubusercontent.com/22765507/121499392-eaf24c00-ca0f-11eb-87de-353f71fa0637.png)

**Comment by AllenWod** [comment]
> I don't think so. You'll need to perform a fresh clone. `git clone https://github.com/trinodb/trino`

thanks for your guide，I have successfully build，but i don't know how to execute next step，can you tell how to config the running full server in IntelliJ IDEA,thanks

**Comment by hashhar** [comment]
I think you already got the answer to that on Slack at https://trinodb.slack.com/archives/CFLB9AMBN/p1623316919422800?

**Comment by AllenWod** [comment]
> I think you already got the answer to that on Slack at https://trinodb.slack.com/archives/CFLB9AMBN/p1623316919422800?

yes , i have solved the problem ,thank you
