### ISSUE TITLE
How could we use ConnectorIndex in mysql connector to improve query performance?

### ISSUE THREAD

**Issue by Crossoverrr** [trinodb/trino#8252]
Dear community,
I'm Investigating ConnectorIndexProvider, and using tpch as a simple example.
I found method `io.trino.testing.tpch.TpchConnectorIndex#lookup` will do a filter job according to the keys in param `RecordSet rawInputRecordSet`.
After some code tracing, I find tpch will read all data in table `orders`, and build a `ImmutableListMultimap` to cache all the key->record mapping,
and tpch connector will finished this key->record filter using this `ImmutableListMultimap`.
Is that true, I'm not very sure about that. The presto version I am using is 357.
Well, I mean in our scenarios we cannot cache all data in memory, so what could we do to make a good use of mysql index using `ConnectorIndexProvider`?

**Comment by Crossoverrr** [comment]
Any help will be appreciated!     :)

**Comment by Crossoverrr** [comment]
Got answer on slack so close this one.   :)

**Comment by kokosing** [comment]
Can you please link the slack conversation for future reference?

**Comment by Crossoverrr** [comment]
Conversation link is below:
https://trinodb.slack.com/archives/CP1MUNEUX/p1623318575296500
