### ISSUE TITLE
DST ambiguity does not raise an error

### ISSUE THREAD

**Issue by giladmaya** [trinodb/trino#8256]
Hi,

When applying `with_timezone` on dates that "overlap" between daylight saving modes, the function chooses a mode automatically without raising any error or allowing the user to choose how to treat such cases

For example:
Israel's DST ends on October 31st at 02:00 
So, the local time 2021-10-31 01:30:00 has two UTC possibilities 

`select with_timezone(TIMESTAMP '2021-10-31 01:30:00', 'Asia/Jerusalem')` results in `2021-10-30 22:30:00` 

Converting ambiguous dates without explicitly choosing a resolution (raise error/return null/fallback to "first" mode), can create unexpected discrepancies for the user. 

Can you please add the missing argument?
Thank you

**Comment by findepi** [comment]
@giladmaya thanks for reporting this.
it seems it's being tracked in https://github.com/trinodb/trino/issues/5781. let me close this one
