### ISSUE TITLE
Mongo connector creating index for every new collection

### ISSUE THREAD

**Issue by academy-codex** [trinodb/trino#8264]
The Mongo connector creates a new index on the _schema (meta-info default table) everytime that a new collection is encountered.

This is not so useful in scenario where an organisation has a seperate DBO (database admin) who can create indexes, read/write, etc. while there are different users with read/write access but not admin accesses like create indexes.
For example, here presto system user running the presto JVM would not be given DBO privilidges in an ideal scenerio but rather only R/W access.

In such situations, organisation policies may prefer for DBO to create a collection _schema and create an index on it and then the presto system user can just R/W on the collections.

Hence, several different teams in organisations are having to patch the code.

Proposed Solution: **Try to Create Index only if it is absent**

Redacting database names due to privacy concerns.
Error: **Command failed with error 13 (Unauthorized): 'not authorized on <<mongo database>> to execute command { createIndexes: "_schema", indexes: [ { key: { table: 1 }, name: "table_1", ns: "<<mongo database>>._schema", unique: true } ], $db: "<<mongo database>>", ... }'** 

We face this error even though the DBO has already created an index on the collection. Hence, we had to patch the connector code to make it run. However, looks like a functional use case to be handled in code for others out there as well.

**Comment by academy-codex** [comment]
I would like to take this up!

**Comment by academy-codex** [comment]
@martint @electrum

**Comment by ebyhr** [comment]
I assume the current logic is already " Create Index only if it is absent". Could you share the code you are mentioning? 
https://github.com/trinodb/trino/blob/master/plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java#L444-L470

**Comment by academy-codex** [comment]
@ebyhr The code you are referencing to is the correct place. However, it is creating once per new collection, how ever we should ideally be creating only once per database, due to the reason of DBO vs R/W access restrictions in organisations.

`
**Document doc = schema.find(new Document(TABLE_NAME_KEY, tableName)).first();**

**if (doc == null)** {       
 if (!collectionExists(db, tableName)) {               
 throw new TableNotFoundException(new SchemaTableName(schemaName, tableName), format("Table '%s.%s' not found", schemaName, tableName), null);           
 }           
 else {                
Document metadata = new Document(TABLE_NAME_KEY, tableName);                
metadata.append(FIELDS_KEY, guessTableFields(schemaName, tableName));
schema.createIndex(new Document(TABLE_NAME_KEY, 1), new IndexOptions().unique(true));                schema.insertOne(metadata);
                return metadata;            
}       
 }
`

If you see the above highlighted sections you will see that same create index is fired for every new collection. This means it checks if collection is absent or not, rather we should check if index is absent or not on the _schema collection.

**Comment by ebyhr** [comment]
Understand your requirement now, thanks.

**Comment by academy-codex** [comment]
@ebyhr 
According to this doc:https://docs.mongodb.com/manual/reference/method/db.collection.createIndex/#recreating-an-existing-index

Mongo doesn't create indexes again if it already exists. However, from the presto side, we are still firing the command but the createIndex is actually a DBO operation v/s R/W operation and can cause several organisations issue while delegating access to presto user as the presto deploys with a system user and such system users can't be granted DBO accesses in a compliance based project.

**Comment by academy-codex** [comment]
On a personal note, I know of 2 major orgs running this on patched versions.

**Comment by academy-codex** [comment]
On another note, createIndex(..) creates an exclusive lock and escalates it during index creation. It can be tricky and impactful if sufficient processes/calls happen to createIndex(..). For example, a big MongoDB cluster with says 1000's of collections is on-boarded to presto and high frequency calls start happening to this mongo via presto, now different people querying different collections will require so many exclusive locks because each collection will call createIndex(..).

Secondly, if user defined schema is updated in MongoDB via CREATE TABLE. We need to check there as well if we are calling createIndex(..) there as well.
