### ISSUE TITLE
How to access /v1/node API endpoint when the password-file-authentication is enabled

### ISSUE THREAD

**Issue by fxulusoy** [trinodb/trino#8289]
I am using the following this [helm-chart](https://github.com/valeriano-manassero/helm-charts) to deploy Trino on Kubernetes. 

When I enable the [password-file-authentication](https://trino.io/docs/current/security/password-file.html), `/v1/node` API, which is used for [the health check](https://github.com/valeriano-manassero/helm-charts/blob/main/valeriano-manassero/trino/templates/configmap-worker.yaml#L49), is not accessible without authentication. 

How can I authenticate to `/v1/node` API endpoint?

**Comment by fxulusoy** [comment]
or is there any other API endpoint to check the nodes?

**Comment by hashhar** [comment]
Take a look at `/v1/info`. That's what we use in https://github.com/trinodb/charts/blob/7f0562edb723e3556cb7075128391bddc6df6715/charts/trino/templates/deployment-coordinator.yaml

**Comment by ebyhr** [comment]
Going to close this issue as it's already answered.
