### ISSUE TITLE
clickhouse  filter pushdown 

### ISSUE THREAD

**Issue by quanleiqwe** [trinodb/trino#8312]
clickhouse connector filter pushdown not effect 

select count(*) from  clickhouse.test01.person_info ;
 _col0
--------
 269140
(1 row)

select person_id from clickhouse.test01.person_info where person_id = '1234';
 person_id
-----------
 1234
 1234
 1234
 1234
 1234
(5 rows)

Query 20210618_121625_03302_j9w2a, FINISHED, 2 nodes
Splits: 33 total, 33 done (100.00%)
0.21 [269K rows, 0B] [1.27M rows/s, 0B/s]

this sql clieckhouse excute   shoud return  five record , but return 269K rows

**Comment by hashhar** [comment]
This is known and predicate pushdown for VARCHAR/VARBINARY is not yet implemented. cc: @wgzhao 

See https://github.com/trinodb/trino/issues/7103 for current state.

Should I consider this a duplicate?

**Comment by quanleiqwe** [comment]
ok, thanks

**Comment by findepi** [comment]
Covered by https://github.com/trinodb/trino/issues/7100
