### ISSUE TITLE
columnValueAndRowIdChannels order inconsistencies in the UpdatablePageSource.updateRows method

### ISSUE THREAD

**Issue by reugn** [trinodb/trino#8330]
I'm trying to implement the row-level SQL DELETE and UPDATE for a custom plugin. DELETE works fine, but there are issues with the UPDATE.

* I return an IdColumnHandler in the `ConnectorMetadata.getUpdateRowIdColumnHandle` method, but it's not being added to the `updatedColumns` in `ConnectorMetadata.beginUpdate` (I understood that it shouldn't be there). 
* I pass the updated columns via a `TableHandler`.
* The order in `columnValueAndRowIdChannels` is not reflecting the actual state. I do have all of the values on a Page in `UpdatablePageSource.updateRows`, but the ID handler is missing, and the order of the columnValueAndRowIdChannels looks not correct.

According to the [official documentation](https://trino.io/docs/current/develop/delete-and-update.html#updatablepagesource-api):

> void updateRows(Page page, List<Integer> columnValueAndRowIdChannels).

> The Trino engine calls the updateRows() method of the same UpdatablePageSource instance that supplied the original page, passing a page of projected columns, one for each updated column and the last one for the rowId column. The order of projected columns is defined by the Trino engine, and that order is reflected in the columnValueAndRowIdChannels argument.

This indeed works for statements where I set a single column value, this way I do receive the raw id value as a last element in the Page, and the order in columnValueAndRowIdChannels is correct if I push the ID handler manually to the end of the list (by the docs). But when I try to set multiple values, the columnValueAndRowIdChannels order doesn't make any sense. For example:

```sql
update table1 set int1=111, int2=5, str='abcd' where int1>200;
```

**Comment by findepi** [comment]
Moved to https://trinodb.slack.com/archives/CP1MUNEUX/p1623946311409900
