### ISSUE TITLE
Avoid lenient Number cast in writeNativeValue

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#8332]
In the past a conversion through `Number` "interface" has proven to be able to mask bugs in the code.
We should remove these conversions from `io.trino.spi.type.TypeUtils#writeNativeValue`.

**Comment by swetharnaik** [comment]
@findepi Can I work on this issue?

**Comment by hashhar** [comment]
@pvliborio is already working on this in https://github.com/trinodb/trino/pull/8343 so this isn't free to take.

However feel free to take a look at other good first issues (or others) at https://github.com/trinodb/trino/labels/good%20first%20issue
