### ISSUE TITLE
query exceeded per-node user memory after killed,resource not freed and service crashed 

### ISSUE THREAD

**Issue by ic4y** [trinodb/trino#8341]
If a query’s resource occupation exceeds the resource of the node (Query exceeded per-node user memory limit of XXGB) , the query will be killed.

![image](https://user-images.githubusercontent.com/83933160/122857095-86f25080-d34a-11eb-9530-dd4831f4f384.png)

At this time, if you continue to submit the query that takes up a lot of resources (but it can be successfully executed normally). There will be insufficient resources, leading to continuous Major GC until the node hangs.

![image](https://user-images.githubusercontent.com/83933160/122857146-9a9db700-d34a-11eb-9479-d24366f3b78c.png)

I suspect this is caused by the fact that the resource was not released after the query was killed.

The screenshot is a single machine test environment, and we also encountered such a problem in our production cluster.

**Comment by ic4y** [comment]
I need your help. Why is that

**Comment by sopel39** [comment]
Which Trino version is this? There have been some improvements for releasing memory in operators recently.

**Comment by ic4y** [comment]
Hi @sopel39  thanks for the reply.

I found this problem in both prestoSQl-322 and trino-353 versions.  
Which version of the improvements you mentioned was done? I can do the corresponding test.

**Comment by sopel39** [comment]
Actually it will be in 359, see https://github.com/trinodb/trino/issues/8170#issuecomment-855744518

**Comment by ic4y** [comment]
@sopel39 Thanks . this solves the problem
