### ISSUE TITLE
approx_set returns NULL for empty or only-nulls imput

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#8347]
approx_set currently returns NULL if executed against empty input or input which contains just NULL values.
It feels like more reasonable approach would be to return empty HLL like `empty_approx_set`.

@martint, @findepi ?

**Comment by findepi** [comment]
Most aggregations return NULL for empty input.
Also, it seems most aggregations ignore NULL values on input, so it might be typical for them to return NULL result for all-NULL input as well.

Now, i don't know whether this is just an incidental pattern, or a design principle. 
I don't see why `approx_set` over empty input, or over all-NULL input, wouldn't return `empty_approx_set()`.

cc @martint @kasiafi

**Comment by kasiafi** [comment]
If we change the result returned by `approx_set` for empty input or all nulls, we need to make sure that no other code depends on the assumption that the result is `null`. I recall that we used to have some transformation in the Optimizer which special-handled the few aggregations which don't follow this pattern. That is now removed, but there might be left-overs of this approach elsewhere.

**Comment by kasiafi** [comment]
> NOTE 238 — Any \<set function specification\>s will be evaluated with an empty argument source; thus COUNT is 0 (zero) and other aggregates produce a null value. 

This is from the spec. The context of this note is row pattern recognition, but is seems to reflect a general rule.

**Comment by electrum** [comment]
That users can workaround this in their query if they want the empty set behavior
```sql
SELECT coalesce(approx_set(x), empty_approx_set())

**Comment by losipiuk** [comment]
Thanks for comments. Seems like current semantics is reasonable. Closing as a wont-fix
