### ISSUE TITLE
mongodb: how to describe a json field which can have different types in _schema 

### ISSUE THREAD

**Issue by Ognian** [trinodb/trino#8352]
I'm using trino with mongodb. I'm trying to write a _schema entry for a mongodb collection. The entries in this collection are described with json schema:
```
...
  "delta": {
    "＄schema": "http://json-schema.org/draft-04/schema#",
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "op": { "type": "string" },
        "path": { "type": "string" },
        "value": {
          "anyOf": [
            { "type": "string" },
            { "type": "number" },
            { "type": "integer" },
            { "type": "boolean" },
            { "type": "object" },
            { "type": "array" }
          ],
        }
      },
      "additionalProperties": false
    }
  }
...
```
the entry would look like
```
          {
            "name": "delta",
            "type": "array(row(\"op\" varchar,\"path\" varchar,\"value\" json))",
            "hidden": false
          }
```
So the interesting point here is that the field `value` can have on of the types listed below.
The only way to express this was to use the json type, BUT this is the error I got:

```
[65536] Query failed (#20210621_212459_01468_5jhjw): Unhandled type for Slice: json io.trino.spi.TrinoException: Unhandled type for Slice: json
```

The question is how to define a field which can have more than one type?
Funny enough if I change from `json` to `varchar` it looks like it works, but it makes no sense to me... 

Thanks
Ognian

**Comment by ebyhr** [comment]
As far as I know, there is no simple solution except for your `varchar` workaround. Let me label as `enhancement`.

**Comment by Ognian** [comment]
@ebyhr it gets even funnier:
when using superset as the frontend and having an address field with subfields street, zip, city, country.
If I define it in _schema of type: `row("street" varchar,"zip" varchar,"city" varchar,"country" varchar)`
the it is displayed as an array:
<img width="216" alt="image" src="https://user-images.githubusercontent.com/1231174/123274963-3b83a200-d504-11eb-8904-ea0f31d054ad.png">
BUT If I define it in _schema of type: `varchar`
<img width="380" alt="image" src="https://user-images.githubusercontent.com/1231174/123275043-4b9b8180-d504-11eb-942e-93afce71c015.png">
which display's it correct
BUT of course this is a superset error since if I try to select address.zip it errors...

**Comment by academy-codex** [comment]
Looks interesting. @ebyhr If you're not taking it up I can have a look.

**Comment by ebyhr** [comment]
@academy-codex I implemented half of this enhancement locally, but please feel free to take it. The point is json generated by `Document.toJson()` is little different from Trino json response.
