### ISSUE TITLE
Fix flaky test `testAlias()` in BaseElasticsearchConnectorTest

### ISSUE THREAD

**Issue by sumannewton** [trinodb/trino#8380]
Test `testSelectInformationSchemaColumns()` asserts query
https://github.com/trinodb/trino/blob/ea5d9889b0844e83ca90673fff529632931e2561/testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java#L664-L666.

But another test `testAlias()` creates alias by name `orders_alias` which runs always after the latter test. If `testAlias()` runs before the latter then the above assert fails.

So to ensure that tests remain independent of each other, aliasName in `testAlias()` should be renamed.

**Comment by hashhar** [comment]
Thanks @sumannewton . Do you want to send in a PR for this? Fixing flaky tests is a very welcome improvement.

**Comment by sumannewton** [comment]
> Thanks @sumannewton . Do you want to send in a PR for this? Fixing flaky tests is a very welcome improvement.

In few mins I am requesting a PR.

**Comment by sumannewton** [comment]
Fixed by #8379

**Comment by sumannewton** [comment]
Fixed by #8379
