### ISSUE TITLE
Verify ClickHouse clusters can be queried as well in addition to singlenode setups

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#8391]
ClickHouse can be deployed a single-node server or as a cluster of servers.

See https://clickhouse.tech/docs/en/getting-started/tutorial/#cluster-deployment.

We should have tests (maybe product tests) to verify it works with cluster based deployments as well.

Most likely the JDBC driver is already handling this for us but it's not tested.

**Comment by tangjiangling** [comment]
@hashhar Is anyone doing this? If not, I'd like to do this.

From the above description, we want to add tests for ClickHouse deployment in a clustered manner and such tests are placed under `trino-product-tests`, do I understand correctly?

**Comment by hashhar** [comment]
Yes, your understanding is correct.
For reference see any of the existing product tests for JDBC based connectors like SQL Server etc.

You need to define an Environment, a new TestGroup and then implement tests (simple read + write) in a class annotated with the new test group you have created.
