### ISSUE TITLE
Added Support for WKB in trino

### ISSUE THREAD

**Issue by lerenah** [trinodb/trino#8393]
Hello and thanks for all the hard work!

I recently configured our postgres connector to return varchar for geography objects in trino.  Initially, it would not resolve the column as trino doesn't map geography(Point, 4236) types into it's own Geospatial types. Once I added the unsupported-type-handling to the connector, it returned the binary representation in string format.  Naturally, I thought to use the ST_GeomFromBinary function to read it in, but kept getting "invalid shape object".  It looks like the function doesn't directly support the type without a bit of massaging.

**Comment by hashhar** [comment]
Duplicates https://github.com/trinodb/trino/issues/5580.

Closing in favour of https://github.com/trinodb/trino/issues/5580.
