### ISSUE TITLE
Support for time zone conversions based on values inside columns

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#8409]
In below example, f could be an actual table containing 3 string columns.

```
with f (select 'America/Chicago' z1, 'America/Los_Angeles' z2, '2012-10-31 01:00' t
union all 
select 'Africa/Cairo' z1, 'Asia/Tokyo' z2, '2016-12-27 04:00' t
)
SELECT timestamp t||' '||z1 AT TIME ZONE z2
```

**Comment by findepi** [comment]
Please see https://trino.io/docs/current/functions/datetime.html#at_timezone and https://trino.io/docs/current/functions/datetime.html#with_timezone
