### ISSUE TITLE
Slack invite link no longer active

### ISSUE THREAD

**Issue by hankfanchiu** [trinodb/trino#8415]
I would like to join Trino's Slack to ask questions and discuss possible changes!

The [URL](https://join.slack.com/t/trinodb/shared_invite/zt-h88upx5f-gVb8XUu16W_jo4I2Cw8ijA) to join the Slack workspace -- hyperlinked on https://trino.io/slack.html and https://trino.io/community.html -- does not seem to be active anymore:

![image](https://user-images.githubusercontent.com/13294681/123719476-7bb19000-d836-11eb-8e64-777aa76586d1.png)

Is there an updated link?

**Comment by martint** [comment]
Thanks for the report. We've updated the link on the website and it should show up there shortly. In the meantime, here's the link: https://join.slack.com/t/trinodb/shared_invite/zt-sbw8lqer-DL3zksjpm6fyIsSQz74MBA
