### ISSUE TITLE
io.trino.spi.TrinoException: Database cannot be created with a location set

### ISSUE THREAD

**Issue by rudolfdobias** [trinodb/trino#8435]
I'm trying to get the Hive connector with Azure Storage working and this error I get when I follow the tutorial:

```sql
CREATE SCHEMA hive.export
WITH (location = 'abfs://test@xxx.dfs.core.windows.net/export'); 
```
```java
io.trino.spi.TrinoException: Database cannot be created with a location set
```

`CREATE TABLE hive.export with external_location` works, but not for writing (TrinoException: Cannot write to non-managed Hive table)

This is my configuration:
```yaml
  hive.properties: |
    connector.name=hive-hadoop2
    hive.metastore=file
    hive.metastore.catalog.dir=file:///tmp/hive_catalog
    hive.metastore.user=xxx
    hive.azure.abfs-storage-account=xxx
    hive.azure.abfs-access-key=xxx
```

Using Trino 358.

Quoting the docs:

> Create a write schema
If the Hive metastore contains schema(s) mapped to Azure storage filesystems, you can use them to write data to Azure storage.

> If you don’t want to use existing schemas, or there are no appropriate schemas in the Hive metastore, you need to create a new one:

> ```
> CREATE SCHEMA hive.abfs_export
> WITH (location = 'abfs[s]://file_system@account_name.dfs.core.windows.net/<path>');
> ```

**Comment by ebyhr** [comment]
File Hive metastore has some limitation and is for testing purpose. You can see more context in #5715
