### ISSUE TITLE
Should doc-only PRs trigger a full suite of product tests?

### ISSUE THREAD

**Issue by Ordinant** [trinodb/trino#8439]
Investigate whether a PR submission with changes **only** in trino/docs can be set with a lower CI profile that does not require a full suite of product test runs.

This would have to be set up with careful automated validation of all files changed in the PR to make sure a nefarious change cannot be sneaked in disguised as a doc-only PR.

**Comment by kokosing** [comment]
I think docs PR should not trigger tests at all. It could be done by using `labels`. For example when label `docs` is set then we could skip tests.

Potentially we could try to use https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths

**Comment by hashhar** [comment]
I've been looking at this for some time. Doc PRs should build only the `docs` module. There are ways to apply labels based on file-paths that have changed. See https://github.com/actions/labeler.

This will also allow to hopefully automatically apply the `hive` etc. tags and maybe even categorise the PRs so that maintainers can filter notifications easily.

**Comment by findepi** [comment]
> There are ways to apply labels based on file-paths that have changed. See https://github.com/actions/labeler.

Won't it be too late?

Anyway, great idea to improve this. thanks @Ordinant for bringing this up!

**Comment by findepi** [comment]
> Potentially we could try to use https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths

I like the idea.
see example usage https://github.com/apache/iceberg/blob/1884beeec2e4d48c8627c320a4612320f716af7f/.github/workflows/java-ci.yml#L20-L31

@Ordinant would you be able to propose a code change for this?

**Comment by hashhar** [comment]
Some baby steps - https://github.com/trinodb/trino/pull/9121

This only adds the labels - no action is being taken on those labels yet.

**Comment by ebyhr** [comment]
Closing as docs-only PRs don't trigger full PTs now.
