### ISSUE TITLE
No page sink provider for catalog 'di_hive' error detected when INSERT query on Presto

### ISSUE THREAD

**Issue by JacobJSShin** [trinodb/trino#8440]
![스크린샷 2021-06-30 오후 2 02 35](https://user-images.githubusercontent.com/86750950/124044117-94dd5b00-da47-11eb-90b0-7cf81d56254c.png)

As a beginner using Presto, working on developing ELT job on Presto across Oracle DB and Hive. 
SELECT query works well, but trying to INSERT INTO HIVE table on Presto, it doesn't work and "No page sink provider for catalog 'di_hive' error" detected as attached. 

What is "page sink" on Presto and how can I fix it?

**Comment by hashhar** [comment]
This suggests that the catalog properties file is not present on all nodes most probably and/or Trino wasn't restarted after updating the catalog properties files.

Please re-open if this doesn't help.
