### ISSUE TITLE
Support insert overwrite dir

### ISSUE THREAD

**Issue by allendang001** [trinodb/trino#8458]
For now, trino only support insert into table, but can not write a file into a dir with the result of select

**Comment by raunaqmorarka** [comment]
INSERT INTO DIRECTORY is not ANSI SQL, so we would probably add support for something like `CREATE TABLE foo WITH (location='...', skip_creating_table=true) AS  ...` rather than that.

**Comment by hashhar** [comment]
This has some challenges keeping the process atomic (although this will surely be nice to have). See previous discussion on Slack at https://trinodb.slack.com/archives/CFLB9AMBN/p1622846497295000?thread_ts=1622756052.235000&cid=CFLB9AMBN for some context.

**Comment by allendang001** [comment]
> INSERT INTO DIRECTORY is not ANSI SQL, so we would probably add support for something like `CREATE TABLE foo WITH (location='...', skip_creating_table=true) AS ...` rather than that.

Is there plan or date to make it?

**Comment by ebyhr** [comment]
I would recommend reading #11603.
