### ISSUE TITLE
NoClassDefFoundError: Could not initialize class HdfsEnvironment

### ISSUE THREAD

**Issue by dev-lpq** [trinodb/trino#8491]
we tried to deploy trino to connect hive/iceberge on  trino-server-358 and  trino-server-359 version, but has the same error  "NoClassDefFoundError: Could not initialize class HdfsEnvironment". We have checked that the HdfsEnvironment class can be added when trino is running. What causes the trino to fail to startup?

**Comment by ebyhr** [comment]
Going to close since you resolved in https://trinodb.slack.com/archives/CGB0QHWSW/p1625723953246400

**Comment by user-GitHub-user** [comment]
can't see the resolve
