### ISSUE TITLE
Autocomplete using tab key is not working in Trino CLI

### ISSUE THREAD

**Issue by aakashnand** [trinodb/trino#8495]
When using trino CLI for version 358, I tried hitting the `TAB` key after typing queries like `Show ca<TAB>` but I am not getting any autosuggestions. According to the following code, I should at least get autocomplete for commands written in the following code.

Slack Reference:  https://trinodb.slack.com/archives/CGB0QHWSW/p1625537890190300

https://github.com/trinodb/trino/blob/6bbe9f1092db394c45a005040c1a03af7e765520/client/trino-cli/src/main/java/io/trino/cli/Completion.java#L25-L54

**Comment by lucasdlemos** [comment]
@aakashnand @hashhar I'm fixing this as part of #8481. Can you please assign it to me? Thanks.

**Comment by hashhar** [comment]
Fixed in https://github.com/trinodb/trino/issues/8481.
