### ISSUE TITLE
How can I get access token in trino plugins using oauth2

### ISSUE THREAD

**Issue by kaojunsong** [trinodb/trino#8508]
Hi all,

Our system originally implement PasswordAuthenticator to get the user and password in plugins.

But recently, we are switching to oauth2 (keycloak), then how can I get the access token in plugins?

I saw there is an endpoint "/oauth2/token/{authId}" in class OAuth2TokenExchangeResource, can I use this endpoint to get the access token in plugins? If so, where can I get the "authId"?

Or there are other ways that I can get the access token in plugins? 

Thank you very much if you have any ideas about this.

**Comment by kokosing** [comment]
What do you mean by plugins? Connector? PasswordAuthenticator?

`OAuth2TokenExchangeResource` is a part of the engine so it is not accessible to plugins in general.

**Comment by kaojunsong** [comment]
Thank you very much for your reply.

The "plugins" I mean is the custom classes we have implements "io.trino.spi.Plugin" interface. 

We got user and password from PasswordAuthenticator  in our current code, and I want to know if we can get the access token to implement a class like "TokenAuthenticator", or other methods, thanks

**Comment by kaojunsong** [comment]
Thank you very much for your help.
Yes, I have followed https://trino.io/docs/current/security/oauth2.html, and the UI works well.
But for our business, I need to get tokens in the plugins to invoke another system which needs the tokens.
Anyhow, thanks a lot. :)
