### ISSUE TITLE
The added methods in  class MysqlConfig have not taken effect

### ISSUE THREAD

**Issue by Bryanquan** [trinodb/trino#8509]
I add some public methods in class MysqlConfig and compile the project again,but it seems the methods has not taken effect
What should I do?

**Comment by ebyhr** [comment]
@Bryanquan I couldn't understand the actual issue. Could you post in the community Slack? 
https://trino.io/community.html

**Comment by ebyhr** [comment]
Let me close this issue because there is no reply for a while. Please feel free to ask in Slack. We have `#troubleshooting` channel.
