### ISSUE TITLE
How can I login to trino using JDBC with oauth2

### ISSUE THREAD

**Issue by kaojunsong** [trinodb/trino#8517]
Hi,

I am switching trino from PASSWORD to oauth2, then I can not login to trino using JDBC using DBVisutalizer.

Does JDBC support oauth2? How can I login to trino using JDBC with oauth2

**Comment by kokosing** [comment]
Yes, please see https://trino.io/docs/current/installation/jdbc.html#parameter-reference, you need to use `externalAuthentication` property.

**Comment by kaojunsong** [comment]
Thank you very much.

**Comment by 1503-firmansyah-indra** [comment]
@kaojunsong how did you solve your issue? I have set `externalAuthentication` as `true` but web browser to authenticate externally does not get authenticated, could you share your code snippet please?
