### ISSUE TITLE
Query failures with Expected Limit input to be sorted by: [...], but was []

### ISSUE THREAD

**Issue by utk-spartan** [trinodb/trino#8526]
Queries which have a 'ORDER BY col1 LIMIT n '  with a filter  `WHERE col1 = abcd` fail with the  error
"Expected Limit input to be sorted by: [field_0], but was []" 

Sharing some examples to provide clarity.

following queries fail with the above mentioned error
 ```
select * FROM (VALUES (1, 'a'),(1, 'b')) AS t (id, name) where id = 1 order by 1 limit 1;

select * FROM (VALUES (1, 'a'),(1, 'b'), (2, 'c')) AS t (id, name) where name = 'a' order by 2 limit 2
```
 removing the ORDERing or increasing the limit allows them to run.

following will run successfully

```
select * FROM (VALUES (1, 'a'),(1, 'b')) AS t (id, name) where id = 1 order by 1 limit 2;

select * FROM (VALUES (1, 'a'),(1, 'b'), (2, 'c')) AS t (id, name) where name = 'a' order by 2 limit 3;
```

**Comment by utk-spartan** [comment]
This started happening since version 359, 
this change seems to be the cause to me - https://github.com/trinodb/trino/pull/8184

**Comment by hashhar** [comment]
cc: @raunaqmorarka 

Are you by any chance on version older than 359? This seems similar to what was addressed in https://github.com/trinodb/trino/pull/8184 (which is available in 359).

**Comment by utk-spartan** [comment]
I upgraded to 359 from 357
and started observing this for a small subset of queries.

**Comment by utk-spartan** [comment]
Looking at the source code snippet  from current master
```if (sortedColumns.size() < node.getPreSortedInputs().size() ||
                    !sortedColumns.subList(0, node.getPreSortedInputs().size()).equals(node.getPreSortedInputs())) {
                throw new VerifyException(format("Expected Limit input to be sorted by: %s, but was %s", node.getPreSortedInputs(), sortedColumns));
```
and the error msg.
"Expected Limit input to be sorted by: [field_0], but was []"

looks like the first condition does get satisfied here, hence the error

**Comment by raunaqmorarka** [comment]
I'll look into it, probably a regression from https://github.com/trinodb/trino/pull/6634
