### ISSUE TITLE
Remove workaround dummy test after updating testng to 7.4.0+

### ISSUE THREAD

**Issue by brandboat** [trinodb/trino#8571]
According to https://github.com/cbeust/testng/issues/2361, there is no way to enforce `@Test(singleThreaded = true)` when test defined in base class. This issue has been fixed in 7.4.0+.

Workdaround: https://github.com/cbeust/testng/issues/2361#issuecomment-688393166, add a dummy test method.

Rel https://github.com/trinodb/trino/issues/8575

**Comment by raunaqmorarka** [comment]
After merging https://github.com/trinodb/trino/pull/20267 we no longer have such dummy tests since we've migrated to junit5
