### ISSUE TITLE
Add a test analyzer to ensure single-threaded base test classes are extended correctly

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#8575]
Until we upgrade to TestNG 7.4 we should add a test analyzer to catch cases where a test class extends a base class with `singleThreaded = true`.

TestNG has a bug where the tests don't run single threaded unless the extending class has at-least 1 `@Test` method.
See https://github.com/trinodb/trino/pull/8568 for context.

Rel https://github.com/trinodb/trino/issues/8571

**Comment by martint** [comment]
Why not just update to testng 7.4?

**Comment by hashhar** [comment]
@martint That is a large upgrade while the test analyzer will be helpful now. There was one in progress at https://github.com/trinodb/trino/pull/4727. I'll try and pick it up.

**Comment by martint** [comment]
Why would that be a large upgrade? Isn’t bumping the version dependency enough?

**Comment by findepi** [comment]
> Isn’t bumping the version dependency enough?

It's not. 

Of course, we can work in parallel on these things.
I do not expect TestNG 7.4 to be "issue-free", so we will still have our test analyzers.

And, adding this one here should be really straightforward.

**Comment by hashhar** [comment]
now since we are using JUnit we don't have this specific problem. So closing. Other problems of similar nature might reappear and we'll tackle separately.
