### ISSUE TITLE
Alias not support in Having predicate

### ISSUE THREAD

**Issue by DoubleDue** [trinodb/trino#8582]
For example SQL statement in MySQL: 
`select  odr.createDate, count(orderid) as total from szsd.orders as odr group by odr.createDate having total >1 ;`

return
`Query 20210717_043219_00000_nmtxv failed: line 1:104: Column 'total' cannot be resolved
select  odr.createDate, count(orderid) as total from szsd.orders as odr group by odr.createDate having total >1
`
<img width="993" alt="image-20210717123304528" src="https://user-images.githubusercontent.com/22554046/126026154-7d4db900-4c56-41bc-98cc-c9714d9987ae.png">

**Comment by findepi** [comment]
I commented in the PR that this is intentional. https://github.com/trinodb/trino/pull/8583#pullrequestreview-708948901
Let's close the issue here so that the conversation can be captured there, in one place.

cc @martint @kasiafi
