### ISSUE TITLE
[ MongoDB Connector ] Support for PLAIN authentication mechanism

### ISSUE THREAD

**Issue by ChandrasekharPo-Kore** [trinodb/trino#8591]
We have a MongoDB setup with ldap authentication configured.Did not find a way to explicitly specify the "auth" mechanism 'PLAIN'. Is there a way to specify it.

**Comment by ebyhr** [comment]
Currently, only no-auth and username&password auth are supported. We need to add support for that.

**Comment by academy-codex** [comment]
This actually brings up a need for flexible auth mechanisms for mongodb. We should support Kerberos and Sasl and Ldap more generically. Instead of fixing one by on le with separate config why not have a auth provider and config ? @ebyhr

**Comment by ChandrasekharPo-Kore** [comment]
Mongodb Driver might already be supporting it.

**Comment by academy-codex** [comment]
Driver might support, but i am thinking why not generalise from trino config side.. like you can provide auth mechanishm property and give respective config and internally we resolve it at connector factory level.

**Comment by ChandrasekharPo-Kore** [comment]
@academy-codex 
Appreciate if you can provide an update on when this will be available ?
Thanks again.

**Comment by academy-codex** [comment]
Hmm.. let me check and come back, we already have implemented kerberos based in my org.
