### ISSUE TITLE
What are the bottlenecks of coordinator or worker when there is a large amount of sql execution?

### ISSUE THREAD

**Issue by manbuyun** [trinodb/trino#8592]
When there are only a few sql running, the average time is about 20 seconds. 
However, when executing 50 or even 100 + sql tasks in parallel, a single sql takes more than 3 minutes. 
What are the bottlenecks of trino coordinator and worker, or which parameters need to be considered and optimized?

**Comment by ebyhr** [comment]
Continues in https://trinodb.slack.com/archives/CGB0QHWSW/p1626681768490700

**Comment by silent-lad** [comment]
Please do not close threads on the basis of slack threads. The Trino slack is not the paid one and the above thread is now lost on slack. Makes it very very hard to find stuff on trino
