### ISSUE TITLE
Certain partition range in where clause causes error

### ISSUE THREAD

**Issue by yjin0510** [trinodb/trino#8604]
We observed the same date range (partition column) specified with OR and BETWEEN worked:
select * from db.table where dt='2021-02-12' or dt = '2021-02-13' limit 10;
select * from db.table where dt between '2021-02-12' and '2021-02-13' limit 10;

However, it failed when using inequality signs:
select dt,count(*) from db.table where dt>='2020-02-12' or dt<='2020-02-13' group by dt;
Query 20210719_184142_01722_cvmzu failed: Query over table 'pin.r_events_daily' can potentially read more than 100000 partitions

We are using Trino 350 and Glue. The same problem happened for Hive metastore as well.

**Comment by hashhar** [comment]
The conditions don't seem to be equivalent, specifically:

`dt>='2020-02-12' or dt<='2020-02-13'` evaluated to include all values, did you mean to use `dt>='2020-02-12' AND dt<='2020-02-13'`?

**Comment by yjin0510** [comment]
Sorry, my bad. This can be closed.
