### ISSUE TITLE
Pinot Connector not working with secured pinot.controller-urls (https)

### ISSUE THREAD

**Issue by vedangparasnis** [trinodb/trino#8617]
I noticed that trino's pinot connector adds a prefix a as http to pinot-controller-urls when we try to connect trino with pinot. 
But In our Case we have attached a loadbalancer  over our zookeeper cluster for our dev apache pinot and added a secure connection .  Hence we require https prefix over http when connecting with  trino pinot connector 

   connector.name=pinot
   pinot.controller-urls=pinot-dev..cloud:443 

We have the following configuration 
A Cloud load balancer balancing zookeeper worker nodes 
3 zookeeper Nodes
2 Brokers 
2 Servers

We are using secured kafka for ingestion in pinot with realtime table and also some offline tables queried from trino using pinot connector 

Someone please help because if we add https in pinot.controller-urls it doesn't give the url we want to connect to pinot controller 
Are there any more security configuration to be done with trino like keystore or truststore when connecting to secured pinot cluster 
Thanks in advance

**Comment by ebyhr** [comment]
@vedangparasnis Can you make sure whether #8836 is sufficient in your environment?
