### ISSUE TITLE
DROP SCHEMA .. [RESTRICT] drops MySQL, MemSQL, ClickHouse schema even if there are relations inside

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#8634]
per https://github.com/trinodb/trino/discussions/8613, `DROP SCHEMA ..` and `DROP SCHEMA .. RESTRICT` should fail when schema contains tables.

This is not the case for MySQL connector.
This may lead to an inadvertent data loss.

cc @wendigo @hashhar @kokosing

**Comment by kokosing** [comment]
I think we should check in `DropSchemaTask` if there are tables in the schema before dropping it.

**Comment by haldes** [comment]
@findepi @kokosing I can take a look. Can you please assign this to me.

**Comment by findepi** [comment]
same applies to MemSQL. Clickhouse

**Comment by findepi** [comment]
I did not verify Kudu

**Comment by wendigo** [comment]
Closed by https://github.com/trinodb/trino/pull/8660
