### ISSUE TITLE
Add apache doris connector

### ISSUE THREAD

**Issue by caneGuy** [trinodb/trino#8653]
Apache doris(https://doris.apache.org/master/en/) is a fast MPP database for all modern analytics on big data.Like Clickhouse, it is widely used in China. We have implemented a Doris connector in our production and we would like to contribute it to the community.

**Comment by zcdJason** [comment]
when to submit？

**Comment by caodaoxi** [comment]
有trino doris connector的代码吗

**Comment by myfjdthink** [comment]
We have modified the Mysql Connector to support  Doris, for a complete example you can see this [repository](https://github.com/myfjdthink/trino-doris-demo)

**Comment by Yiutto** [comment]
> We have modified the Mysql Connector to support Doris, for a complete example you can see this [repository](https://github.com/myfjdthink/trino-doris-demo)

![image](https://github.com/trinodb/trino/assets/12077317/7fc4e2e0-463d-405a-8fee-6b68ae9f5763)

Query 20230719_101134_00044_r6m84, FAILED, 2 nodes
Splits: 383 total, 254 done (66.32%)
1:02 [44.7M rows, 440MB] [716K rows/s, 7.05MB/s]

Query 20230719_101134_00044_r6m84 failed: errCode = 2, detailMessage = query timeout

One problem is that I used trino to associate hive with kudu and doris tests, and I found that the query always timed out

doris> show variables like 'query_timeout';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| query_timeout | 60 |
+---------------+-------+
1 row in set (0.00 sec)

doris's timeout is 60 seconds
trino's query.client.timeout=5m,

trino itself does not support doris, so it is difficult to set the query timeout time of doris from trino. What should I do?

**Comment by hackeryang** [comment]
Our community is trying to support `StarRocks` connector, which is similar and originated from `Apache Doris`: https://github.com/trinodb/trino/issues/17329
