### ISSUE TITLE
Presto Client Query Results Pagination limits

### ISSUE THREAD

**Issue by nigurr** [trinodb/trino#8673]
Presto/Trino Client documentation describes the behavior of paginated results - https://trino.io/docs/current/develop/client-protocol.html#

I couldn't find information/documentation regarding the default limit per page (nextURI).
Can this be set by Client or Server? If so, which properties/configuration defines the same.

Any help is appreciated!

**Comment by wendigo** [comment]
It's controlled by `targetResultSize` query param. Default is to fetch up to 1 MB of data, please see comment here: https://github.com/trinodb/trino/blob/4492277f15c090cd8edcf690ef4bac1eb6ea02cc/core/trino-main/src/main/java/io/trino/server/protocol/Query.java#L503

**Comment by nigurr** [comment]
> It's controlled by `targetResultSize` query param. Default is to fetch up to 1 MB of data (maximum is 128 MB), please see comment here:
> 
> https://github.com/trinodb/trino/blob/4492277f15c090cd8edcf690ef4bac1eb6ea02cc/core/trino-main/src/main/java/io/trino/server/protocol/Query.java#L503

Awesome. Thank you! Can I raise PR to embed this info in documentation? Would be great which section should I target? HTTP Client section?

**Comment by hashhar** [comment]
Note that larger values increase CPU and memory usage on both client and co-ordinator since the payload is JSON and parsing larger payloads takes longer wall-clock times.

@nigurr are you writing a new client? Generally nobody should have to use the client API directly.

**Comment by nigurr** [comment]
> @nigurr are you writing a new client? Generally nobody should have to use the client API directly.

I am planning to extend the `go-client`. From the current implementation https://github.com/trinodb/trino-go-client/blob/master/trino/trino.go#L885 we keep on fetching data until we completed loading full data set and return all rows (if I try to fetch million rows, the memory foot print shoots up to 30 GB in go client).

It can be extended to expose `reader channel` where we can stream the results into channel while querying is still happening in client. This is more efficient in my opinion.

**Comment by hashhar** [comment]
Agreed. The JDBC client works in a similar manner by using a thread to fetch results and another to parse and return results returned in previous fetch IIRC.

I think it'll be helpful if you join along on [Slack](https://trino.io/slack.html) we can discuss in detail at #dev about possible ways to improve the trino-go-client.

**Comment by nigurr** [comment]
Will take this offline.
