### ISSUE TITLE
Excessive metastore invocations when querying Iceberg table

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#8675]
There was a concern about second call to getTable here https://github.com/trinodb/trino/pull/8151#discussion_r643707727  because these can be expensive.

as  https://github.com/trinodb/trino/blob/30f2ecce1dd1fe787b075ecf21d30fe89d38e315/plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java#L106-L108 shows, we currently do 12 such calls per table when querying Iceberg.

We need to understand _why_ we're doing those additional accesses to metastore.
If caching is found to be desired, https://github.com/trinodb/trino/pull/8659 is a WIP adding it.

**Comment by findepi** [comment]
Out of these 12:

- 4x `io.trino.plugin.iceberg.IcebergMetadata#getSystemTable`
- 1x `io.trino.plugin.iceberg.IcebergMetadata#getMaterializedView` and 1x `io.trino.plugin.iceberg.IcebergMetadata#getView`
- 2x `IcebergMetadata.getTableHandle` (apparently within one call)
- 4x `IcebergMetadata.getTableMetadata` (these seem plain redundant)


cc @homar @joshthoward @clemensvonschwerin

**Comment by findepi** [comment]
> * 4x `IcebergMetadata.getTableMetadata` (these seem plain redundant)

https://github.com/trinodb/trino/pull/8676

**Comment by electrum** [comment]
Nice analysis. It looks like we will need to change the connector, since it seems hard to avoid all of these.

**Comment by findepi** [comment]
> * 4x `io.trino.plugin.iceberg.IcebergMetadata#getSystemTable`

https://github.com/trinodb/trino/pull/8689

**Comment by findepi** [comment]
When selecting from a system table, we currently do even more accesses:

```
    // select from $history
    assertMetastoreInvocations("SELECT * FROM \"test_select_snapshots$history\"",
            ImmutableMultiset.builder()
                    .addCopies(GET_TABLE, 17)
                    .build());

    // select from $snapshots
    assertMetastoreInvocations("SELECT * FROM \"test_select_snapshots$snapshots\"",
            ImmutableMultiset.builder()
                    .addCopies(GET_TABLE, 19)
                    .build());

    // select from $manifests
    assertMetastoreInvocations("SELECT * FROM \"test_select_snapshots$manifests\"",
            ImmutableMultiset.builder()
                    .addCopies(GET_TABLE, 21)
                    .build());

    // select from $partitions
    assertMetastoreInvocations("SELECT * FROM \"test_select_snapshots$partitions\"",
            ImmutableMultiset.builder()
                    .addCopies(GET_TABLE, 17)
                    .build());

    // select from $files
    assertMetastoreInvocations("SELECT * FROM \"test_select_snapshots$files\"",
            ImmutableMultiset.builder()
                    .addCopies(GET_TABLE, 24)
                    .build());
```

**Comment by findepi** [comment]
> When selecting from a system table, we currently do even more accesses 

https://github.com/trinodb/trino/pull/8692
