### ISSUE TITLE
Support use-preferred-write-partitioning for the Iceberg connector

### ISSUE THREAD

**Issue by epogash** [trinodb/trino#8682]
When trying to utilize use-preferred-write-partitioning for Iceberg, there is no effect.

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/9834 adds repartitioning support for Iceberg.

per https://github.com/trinodb/trino/blob/36ff8b5a3d69e244ac7eb7d17f63a12458f41f83/core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java#L542-L553
to fully leverage cost-based write partitioning selection, for identity-based partitions, we need not to return partitioning handle, and set only `ConnectorNewTableLayout#partitionColumns`
