### ISSUE TITLE
Test Nanosecond Timestamp Handling for Optimized Parquet Writer

### ISSUE THREAD

**Issue by Justin-Kwan** [trinodb/trino#8715]
**Description**

- Enable nanosecond timestamp unit tests to run against Optimized Parquet Writer, once https://github.com/trinodb/trino/issues/5357 is completed
- Update `TestHiveStorageFormats.storageFormatsWithNanosecondPrecision` to not filter out optimized storage formats.

https://github.com/trinodb/trino/pull/8699

cc: @findepi

**Comment by findepi** [comment]
I merged this into https://github.com/trinodb/trino/issues/5357.
