### ISSUE TITLE
Total number of rows in index does not match number of rows in partitions within that index

### ISSUE THREAD

**Issue by ic4y** [trinodb/trino#8721]
I encountered this error in the query, but the problem disappeared when the cluster was restarted.

![image](https://user-images.githubusercontent.com/83933160/127634406-0d6b299c-943a-43ea-8970-004d05694558.png)
![image](https://user-images.githubusercontent.com/83933160/127634471-a9ed8b2c-a807-4d76-b3e1-1d19df02cd43.png)

What causes this problem, and why does the restart problem disappear ？

**Comment by findepi** [comment]
Duplicates https://github.com/trinodb/trino/issues/7419.
