### ISSUE TITLE
Transaction should not be allowed to be used when connector does NOT support them

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#8725]
Tested on memory connector:
```
trino:default> start transaction;
START TRANSACTION
trino:default> create table x(i int);
CREATE TABLE
trino:default> rollback;
ROLLBACK
trino:default> show tables like 'x';
 Table
-------
 x
(1 row)
```

Disregarding the fact that statements like `START TRANSACTION` and `ROLLBACK` succeeded the "transaction" left side effects. I don't think transaction are commonly used in Trino, so possibly nobody hit this issue (as it was not yet reported) but pretending that they are supported is not good anyway.

**Comment by kokosing** [comment]
See: https://github.com/trinodb/trino/pull/8694#issuecomment-889847490

>  I think we should disallow calling `START TRANSACTION` for connectors that do not support transaction (most of the connectors).

**Comment by electrum** [comment]
As I mentioned on https://github.com/trinodb/trino/pull/8694#pullrequestreview-729153982 this is a bug in the connector implementation, but we should fix it by changing the default method. `START TRANSACTION` is not linked to a specific connector, so it is not possible to fail at that time. If the connector returned `true` from `isSingleStatementWritesOnly()`, then the `CREATE TABLE` would fail with *Catalog memory only supports writes using autocommit*.
