### ISSUE TITLE
Trino LDAP setup fails with HTTP ERROR 403 Forbidden

### ISSUE THREAD

**Issue by nnandula** [trinodb/trino#8744]
Hi,
We are trying to set up Trino server 359 with LDAP authentication.
We are using a proxy server (load balancer) and the Trino coordinator is running with HTTP configuration on the default port, 8080.

Added `http-server.process-forwarded=true ` to the `config.properties` file.

We are able to connect to trino using the proxy server HTTPS URL and query data.

Now, to configure LDAP authentication added `http-server.authentication.type=PASSWORD` to `config.properties` file.
And `password-authenticator.properties` with below content:

```
password-authenticator.name=ldap
ldap.allow-insecure=true
ldap.url=ldap://ldap.example.com:389
ldap.user-bind-pattern=${USER}@example.com
```

When we try to connect to Trino CLI using the below command:
`./trino --server https://trino-dev.example.com --catalog hive --schema db --user nnandula --password`

it fails with the below error:

```
trino:db> Aug 02, 2021 2:18:39 AM com.google.common.cache.LocalCache$Segment$1 run
WARNING: Exception thrown during refresh
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error starting query at https://trino-dev.example.com/v1/statement returned an invalid response: JsonResponse{statusCode=403, statusMessage=Forbidden, headers={cache-control=[must-revalidate,no-cache,no-store], content-length=[417], content-type=[text/html;charset=iso-8859-1]}, hasValue=false} [Error: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 403 Forbidden</title>
</head>
<body><h2>HTTP ERROR 403 Forbidden</h2>
<table>
<tr><th>URI:</th><td>/v1/statement</td></tr>
<tr><th>STATUS:</th><td>403</td></tr>
<tr><th>MESSAGE:</th><td>Forbidden</td></tr>
<tr><th>SERVLET:</th><td>org.glassfish.jersey.servlet.ServletContainer-49de1505</td></tr>
</table>

</body>
</html>

```

Please advise.

**Comment by hashhar** [comment]
Can you add `io.trino.plugin.password=DEBUG` to `log.properties` and share the entries from `server.log` (or the stdout/stderr of the container if you are using Docker)?

That will have additional information to see the root cause.

Also, do you have any system access controls configured?
Does your setup work with PASSWORD file authentication? That will help ensure the issue is in the LDAP authentication itself instead of password authentication in general.

**Comment by nnandula** [comment]
Hello @hashhar - Thank you for your response.

I tried to add `io.trino.plugin.password=DEBUG` to `log.properties` but no new entries in `server.log` when we try to connect via CLI.

The same error with PASSWORD file authentication as well. 

Trying to access Web UI after enabling PASSWORD authentication in `config.properties` file says
**_Web Interface is Disabled_**


Please advise.

**Comment by nnandula** [comment]
@hashhar - Thanks, we are able to solve the issue after correcting the `Forwarded` header issue from the proxy server. We are able to authenticate via LDAP

**Comment by hashhar** [comment]
@nnandula Can you briefly describe what was wrong so that other people who run into this issue have an idea of what to correct?

**Comment by ashishjullia** [comment]
@hashhar correct, I can see that @nnandula also posted same thing in slack channel as well, said the same thing that solved it but replied again how "solved it" after correcting the `Forwarded` header issue.

I'm also facing the same thing and looking for a solution but always ending up with @nnandula 's mentions but not the solution.
