### ISSUE TITLE
Enable HTTPS automatically for CLI if using port 443

### ISSUE THREAD

**Issue by electrum** [trinodb/trino#8798]
If the `--server` option is used without a protocol, then it should use `https` when on port 443. For example, these invocations would be equivalent, with the first one having the new behavior:

```
trino --server example.net:443
trino --server https://example.net:443
trino --server https://example.net
```

This will make the CLI consistent with the JDBC driver in this regard. While it's technically a backwards incompatible change, it seems unlikely that anyone is using HTTP over port 443. If they are, they can specify `http://` explicitly.

**Comment by andrewdibiasio6** [comment]
Can you assign this to me? I am taking a look now.

**Comment by andrewdibiasio6** [comment]
I cut a PR here: https://github.com/trinodb/trino/pull/8806
