### ISSUE TITLE
Expose lastddltime of hive views

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#8805]
Using trino there doesn't seem to be way to see the last time a Hive view was modified. Hive tables show transient_lastddltime in $properties. Perhaps Hive views should also have their own $properties ? Or alternatively add this value in information_schema.views

Having this would allow to answer the Q: what views were changed in the last 24hrs

**Comment by ebyhr** [comment]
Though I'm not sure about the context, the view support is disabled at

https://github.com/trinodb/trino/blob/c235522a56c894560789972de1656be423b865f1/plugin/trino-hive/src/main/java/io/trino/plugin/hive/PropertiesSystemTableProvider.java#L61

We can get `transient_lastddltime` once we remove the 2nd condition. 

```bash
trino> SELECT * FROM hive.default."v8805$properties";
 bucketing_version | transient_lastddltime
-------------------+-----------------------
 2                 | 1628177271
```

Relates to #268

cc: @kokosing @electrum
