### ISSUE TITLE
iceberg connector not support hadoop_catalog

### ISSUE THREAD

**Issue by dongdong-2016** [trinodb/trino#8813]
there are two type of  iceberg catalog : hive   and hadoop.
hadoop  catalog-type ,metadata is stored in hdfs; hive   catalog-type metadata is stored in HMS.
now trino iceberg connector only support catalog-type hive.
hope  trino iceberg connector support catalog-type hadoop

**Comment by hashhar** [comment]
See https://github.com/trinodb/trino/pull/6977. Work is already in progress.

I'm closing the issue since it's already tracked but feel free to reopen or join our [Slack](https://trino.io/slack.html) and continue the conversation there.
