### ISSUE TITLE
Iceberg: Exceptions swallowed when metadata file cannot be read

### ISSUE THREAD

**Issue by RussellSpitzer** [trinodb/trino#8841]
When Iceberg fails to be able to read the metadata file location the exception is swallowed. This leads to a complicated exception unrelated to file reading when a null AtomicReference is dereferenced

```Cannot invoke "org.apache.iceberg.TableMetadata.uuid()" because the return value of "java.util.concurrent.atomic.AtomicReference.get()" is null```

I think we should probably be returning the actual exception if the metadata read fails or have better handling around the AtomicReference dereference.

https://github.com/trinodb/trino/blob/b8bcec23f407e8e6fa7504e3c76f8df3f311d355/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/HiveTableOperations.java#L291-L299

**Comment by manishmalhotrawork** [comment]
@RussellSpitzer 
Looks like this is fixed here (suppressFailureWhenFinished() is removed now) https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractMetastoreTableOperations.java#L279

**Comment by findepi** [comment]
Fixed by https://github.com/trinodb/trino/pull/8951

**Comment by RussellSpitzer** [comment]
Excellent! Thanks!

**Comment by osscm** [comment]
thanks, @findepi for fixing and closing!
