### ISSUE TITLE
Support for querying iceberg tables with "as of timestamp" semantics

### ISSUE THREAD

**Issue by skandasa23** [trinodb/trino#8847]
Today, Trino supports querying a particular snapshot of Iceberg with the convention table@snapshot-id. It would also be beneficial to provide table@as-of-timestamp. 
This will help the data-users who doesn't know about snapshots but wanted to do time based reads.

**Comment by skandasa23** [comment]
@findepi FYI

**Comment by hashhar** [comment]
I think this is already supported. See https://github.com/trinodb/trino/issues/8663#issuecomment-895980852.

e.g. `SELECT * FROM "table_xyz@1628659697000";` will query the snapshot corresponding to `1628659697000` in epoch milliseconds i.e. `11-08-2021 05:28:17Z`

cc: @homar @losipiuk

**Comment by tooptoop4** [comment]
maybe related to https://github.com/trinodb/trino/pull/8773

**Comment by electrum** [comment]
Note that the existing syntax will likely be deprecated or changed, since it has the problem that the value is ambiguous: it is either a timestamp or a snapshot ID. The standard-ish time travel syntax that @tooptoop4 mentioned will solve this.

**Comment by skandasa23** [comment]
Makes sense, thank you everyone for sharing the details!

**Comment by skandasa23** [comment]
Duplicate of #8773 , closing this!
