### ISSUE TITLE
希望支持excel

### ISSUE THREAD

**Issue by yangyongyongyong** [trinodb/trino#8849]
I want to support Excel.
目前市面上还没有专门针对excel的sql工具. 希望trino的connector能够支持本地或者hdfs上的excel文件.

**Comment by tooptoop4** [comment]
https://github.com/ebyhr/trino-storage/blob/master/src/main/java/org/ebyhr/trino/storage/operator/ExcelPlugin.java

**Comment by yangyongyongyong** [comment]
> https://github.com/ebyhr/trino-storage/blob/master/src/main/java/org/ebyhr/trino/storage/operator/ExcelPlugin.java

多谢大哥.
