### ISSUE TITLE
Unicode characters in query plan explain (\000A \2502 etc.)

### ISSUE THREAD

**Issue by leniartek** [trinodb/trino#8852]
Steps to reproduce:

1. Open trino-cli
3. Run query `explain explain select count(*) from tpch.tiny.orders;`

Expected: well-formatted query plan
Actual: query plan with special characters (\000A, \2502)
<img width="1020" alt="Screenshot 2021-08-11 at 10 54 54" src="https://user-images.githubusercontent.com/10237525/129009509-4563a594-b82a-4387-b6c7-f854e85d53b6.png">

**Comment by hashhar** [comment]
Are you on MacOS by any chance? I am unable to reproduce on a Linux machine but can reproduce on MacOS machines.

Seems something wrong with either the JDK or MacOS because even older clients that used to work (e.g. even as old as 352) are showing this behaviour now. I have tried on older Trino server versions as well with the same observations.
<img width="762" alt="Screenshot 2021-08-11 at 5 26 56 PM" src="https://user-images.githubusercontent.com/10473142/129024628-a45f9b7b-c466-4118-9ea4-5a216dff4f4e.png">

**Comment by hashhar** [comment]
@martint @kasiafi Should Trino be accepting `EXPLAIN EXPLAIN` in the first place? It seems like it's doing the wrong thing here (rewrapping explain output as a literal string).

Every other database considers `EXPLAIN EXPLAIN` a syntax error.

**Comment by leniartek** [comment]
Yes this is from Mac.

**Comment by findepi** [comment]
> Actual: query plan with special characters (\000A, \2502)

this is actually correct, and as designed

```
trino> EXPLAIN SELECT chr(10);
                               Query Plan
------------------------------------------------------------------------
 Fragment 0 [SINGLE]
     Output layout: [chr]
     Output partitioning: SINGLE []
     Stage Execution Strategy: UNGROUPED_EXECUTION
     Output[_col0]
     │   Layout: [chr:varchar(1)]
     │   Estimates: {rows: 1 (55B), cpu: 0, memory: 0B, network: 0B}
     │   _col0 := chr
     └─ Values
            Layout: [chr:varchar(1)]
            Estimates: {rows: 1 (55B), cpu: 0, memory: 0B, network: 0B}
            (U&'\000A')
```

> Should Trino be accepting EXPLAIN EXPLAIN in the first place?

I don't see any value in accepting these. Let's have a separate issue on this.

**Comment by arunkumaralagesan** [comment]
Do we have any pretty print mechanisms for the explain output?
It's hard for the users to go over the output and gain insights.

Any solution for a "pretty" rendering in javascript/React would be very much helpful

**Comment by findepi** [comment]
> It's hard for the users to go over the output and gain insights.

No doubt about that. EXPLAIN plans are not supposed to be read by a typical user. They are meant for expert and contain information that only experts can make sense of.
