### ISSUE TITLE
Support path override in Iceberg table creation

### ISSUE THREAD

**Issue by jackye1995** [trinodb/trino#8861]
Trino should support creating Iceberg tables with path override to leverage Iceberg features around `ObjectStorageLocationProvider`. The work for reading Spark Iceberg table with the feature is in #8573, I will create a follow up for this feature once it is merged.

**Comment by jackye1995** [comment]
@losipiuk FYI, this feature is better added with https://github.com/apache/iceberg/pull/2845, which is not in Iceberg 0.12.0 release. It will be in the next release in September, and then I will implement this feature.

**Comment by Cerebus** [comment]
@jackye1995  This looks complete on the Iceberg end.

**Comment by jakelong95** [comment]
I've put up a PR addressing this - https://github.com/trinodb/trino/pull/20516
