### ISSUE TITLE
Trino function url_extract_path failing

### ISSUE THREAD

**Issue by hylas-dev** [trinodb/trino#8862]
The URL `https://bingus.io/quote?a=fetch&content=<php>die(@md5(HelloThinkCMF))</php>` ended up returning NULL for `url_extract_path()`. 

Strange URL, I know, but it ended up in my application.

**Comment by ebyhr** [comment]
If I understand [RFC 2396](https://datatracker.ietf.org/doc/html/rfc2396.html) correctly, angle brackets are excluded and you need to escape it.
```sql
trino> SELECT url_extract_path('https://bingus.io/quote?a=fetch&content=%3Cphp%3Edie(@md5(HelloThinkCMF))%3C/php%3E');
 _col0
--------
 /quote
```

**Comment by ebyhr** [comment]
Let me close this issue as the expected behavior. Please feel free to reopen or ask in the community Slack if you want to continue. 
https://trino.io/community.html
