### ISSUE TITLE
I'd like to support Excel by default, rather than having me compile the plugin myself

### ISSUE THREAD

**Issue by yangyongyongyong** [trinodb/trino#8879]
![image](https://user-images.githubusercontent.com/46118358/129420806-f8a0ca80-3692-4c50-90aa-3a528ccd08bf.png)

**Comment by yangyongyongyong** [comment]
因为我总是编译失败..............

**Comment by hashhar** [comment]
we don't ship third party plugins as part of our deployment.

Unless a trino-excel plugin is contributed (e.g. https://github.com/snowlift/trino-storage or https://github.com/fortitudetec/presto-plugins/tree/master/spreadsheet-storage-handler) people will need to use the plugins themselves.

There are no plans to add an Excel plugin in near future as part of Trino core.
