### ISSUE TITLE
Druid column missing

### ISSUE THREAD

**Issue by jerryleooo** [trinodb/trino#8886]
If the column data type is `OTHER` in Druid, then it will be missing in Trino's `desc <table name>`

<img width="160" alt="image" src="https://user-images.githubusercontent.com/3231765/129547393-6fbec966-3b02-4dc9-b0d1-d4fbf789103a.png">
<img width="189" alt="image" src="https://user-images.githubusercontent.com/3231765/129547450-91be068b-c133-4b57-b647-457a7999679d.png">

**Comment by jerryleooo** [comment]
I think the solution would be Druid connector has its own explicit type mapping.

@hashhar any ideas?

**Comment by ebyhr** [comment]
We use `jdbc` label for JDBC driver, not JDBC based connector. 

Also, most JDBC based connector doesn't support all remote data types, so basically it's not a bug in my opinion. 

Could you try `jdbc-types-mapped-to-varchar` as workaround? I guess the type will be mapped to varchar even if we add support explicitly. 

https://druid.apache.org/docs/latest/querying/sql.html
> OTHER: May represent various Druid column types such as hyperUnique, approxHistogram, etc

**Comment by jerryleooo** [comment]
Thanks, @ebyhr , just removed the 2 labels.

I have tried using `jdbc-types-mapped-to-varchar` and it works: https://github.com/trinodb/trino/pull/8889

**Comment by jerryleooo** [comment]
As @ebyhr mentioned, this can be solved by adding the `jdbc-types-mapped-to-varchar` configuration, so closing.
