### ISSUE TITLE
Join Pushdown isn't working with functions

### ISSUE THREAD

**Issue by aislinnjeske** [trinodb/trino#8904]
I've noticed that join pushdown does not work correctly when there's a function in the query. 

The query that I was running was to Hive and it contained regexp_like and joined two Hive tables. When the regexp_like was present in the query, the join was not being pushed down to Hive

**Comment by hashhar** [comment]
This is a known limitation with all types of pushdown. There is ongoing work regarding this in https://github.com/trinodb/trino/pull/7994.

**Comment by findepi** [comment]
closing, since this is answered.

BTW, there is no Join pushdown for Hive connector, since there is no other engine we could push things into.
