### ISSUE TITLE
Document Hive connector table properties explicitly

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#8905]
Currently we only have this in code snippets.

Here is what I think is correct without too much digging

```
.. list-table:: Hive connector storage table properties
  :widths: 30, 60, 5
  :header-rows: 1

  * - Property name
    - Description
    - Default
  * - ``format``
    - File format to use in the storage. Valid values include ``ORC``,
      ``PARQUET``, ``CSV``, ``JSON`` and others. The catalog property
      ``hive.storage-format`` sets the default value to ``ORC`` and can be used
      to set a different default.
    - ``ORC``
  * - ``partitioned_by``
    - Partitioning column for the storage table.
    - ``[]``
  * - ``bucketed_by``
    - Bucketing column for the storage table.  Must be used with
      ``bucketed_count``.
    - ``[]``
  * - ``bucket_count``
    - Number of buckets to group data into. Must be used with ``bucketed_by``.
    -
  * - ``sorted_by``
    - Column to sort by to determine bucketing for row.
    - ``[]``

```

There are probably other table properties and I know that we have properties for ORC and Parquet. We should collect them all and have a section/table with anchor so we can link to it from other places like materialized view and such

**Comment by mosabua** [comment]
wdyt @hashhar @electrum ?

**Comment by hashhar** [comment]
Would it be better to link to https://trino.io/docs/current/sql/create-table.html#description from the Hive documentation as a "see this for table properties"?

It's always up to date and exhaustive. There is no confusion regarding some properties not being available because the Hive catalog configuration is different. And it works with every connector.

**Comment by mosabua** [comment]
That does not detail what the possible values for each table property are and it requires the user to run a query to be able to write a query ... while inline documentation like this is great .. its probably not good enough. We can link to that in addition to documenting the properties in the actual docs with possible values, explanations and even example queries..

**Comment by hashhar** [comment]
Good point about possible values and some examples.

**Comment by findepi** [comment]
@mosabua yes, the available table properties should be documented in Hive connector docs.

Currently the coverage is erratic, with e.g. `bucketed_by` being mentioned in examples only and e.g. `skip_header_line_count` being mentioned in release notes only.

btw the `SELECT * FROM system.metadata.table_properties` is a good way to get the docs initialized,
also, if we could test the docs (and we already do in some rare cases!), we could test coherence between `SELECT * FROM system.metadata.table_properties` and documented properties. This would help keep them in sync.

**Comment by mosabua** [comment]
This is done
