### ISSUE TITLE
ctas bug：presto can not write column type except string into csv table 

### ISSUE THREAD

**Issue by allendang001** [trinodb/trino#8940]
CTAS：create table test1 with(external_location='hdfs://aaaa/testaaa', format='CSV') as select * from test 

testjson:
      create table test (a int, b varchar);

exception:
       Query failed (#20210823_101459_00008_3rmb4): org.apache.hadoop.hive.serde2.objectinspector.primitive.WritableIntObjectInspector cannot be cast to org.apache.hadoop.hive.serde2.objectinspector.primitive.StringObjectInspector

**Comment by findepi** [comment]
the limitation is intentional, since CSV serde supports unbounded varchar (string) data type only.

> `Query failed (#20210823_101459_00008_3rmb4): org.apache.hadoop.hive.serde2.objectinspector.primitive.WritableIntObjectInspector cannot be cast to org.apache.hadoop.hive.serde2.objectinspector.primitive.StringObjectInspector`

this should have failed earlier.

**Comment by allendang001** [comment]
is it ok that converting type to string before writing to csv file?

**Comment by findepi** [comment]
it's expected that a user does that explicitly. We made such decision to avoid doing silent data conversions on behalf of the user.

i am closing this as answered, but we can continue talking here.

**Comment by allendang001** [comment]
it will lead to that ctas statement failed in default if there are non string type in the result of query. it it a mislead
