### ISSUE TITLE
Upgrade Avro version to 1.10.1

### ISSUE THREAD

**Issue by phd3** [trinodb/trino#8943]
A [bug](https://github.com/apache/avro/pull/969/files#diff-2812ad83e127ca916e60f60beff26c675cb92eaa7159fb7bc100971d5a1c69f8R61) in the current avro version fails some iceberg queries because it fails to read an avro file. https://github.com/apache/iceberg/issues/1654

We need to bump the avro version to `1.10.1` for the fix. However, we should see if we should only do that when we upgrade Iceberg version to `0.12.0`, since some additional Iceberg side changes may be required. https://github.com/apache/iceberg/pull/1648

cc @electrum @findepi @jackye1995

**Comment by findepi** [comment]
cc @losipiuk @jirassimok

**Comment by jirassimok** [comment]
I'm already looking into the version bump to address a different issue. I'll put up a PR with the minimal change in a moment.

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/9114
