### ISSUE TITLE
com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist while querying AWS s3 via trino

### ISSUE THREAD

**Issue by optimus-kart** [trinodb/trino#8950]
I am using the following catalog config to connect to AWS S3  using trino (`s3bucket.properties`)

```
      connector.name=hive-hadoop2
      hive.metastore.uri=thrift://hive-metastore-trino-example.vcs.svc.cluster.local:9083
      hive.s3.endpoint=https://mybucket.s3.us-east-1.amazonaws.com
      hive.s3.aws-access-key=accessKey 
      hive.s3.aws-secret-key=secretKey
      hive.s3.ssl.enabled=false
      hive.non-managed-table-writes-enabled=true
      hive.s3select-pushdown.enabled=true
      hive.storage-format=ORC
      hive.metastore.thrift.impersonation.enabled=true
```
Similarly, In the hive-metastore (backed by MySQL DB)  I have  updated the hive-site.xml with the relevant config to connect to AWS S3, now when I try to run the below query

```
CREATE TABLE s3bucket.mydb.customer
WITH (
    format = 'ORC',
    external_location = 's3a://mybucket/customer/'
) 
AS SELECT * FROM tpch.tiny.customer;
```
I get the following error:
`The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code`
But if I change the `external_location` to `s3a://mybucket/` the query writes the data in s3 but I see that it is written at `s3a://mybucket/mybucket` instead of `s3a://mybucket`. Also if I don't specify the bucket name in `external_location` (ex: `extermal_location=s3a://customer`) the data gets written to `s3a://mybucket/customer`.

Now the other problem is when I try to read the data that is written using `external_location=s3a://mybucket` (even `s3a://customer`) with the following query

`SELECT * FROM s3bucket.mydb.customer;` 

 I again get ` The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; ` error.

Another thing to note here is that, if I use minio as the object store all these operations work as expected.

Trino Version: 360

**Comment by hashhar** [comment]
> `hive.s3.endpoint=https://mybucket.s3.us-east-1.amazonaws.com`

This is incorrect and causing the issue - the S3 endpoint refers to the S3 service's endpoint not the bucket URL. The default value should work unless you are using some S3-compatible system like Minio.
If you want to use a regional S3 endpoint you should use the ones mentioned at https://docs.aws.amazon.com/general/latest/gr/s3.html.

I'm closing this but feel free to re-open if this doesn't resolve the issue or join our [Slack](https://trino.io/slack.html) and continue the conversation there.

**Comment by optimus-kart** [comment]
@hashhar  thanks for the suggestion, It is working fine after updating the hive.s3.endpoint value.
That said the trino documentation mentions the following

```
The S3 storage endpoint server. This can be used to connect to an S3-compatible storage system instead of AWS. When using v4 signatures, it is recommended to set this to the AWS region-specific endpoint (e.g., http[s]://<bucket>.s3-<AWS-region>.amazonaws.com).
--
```
The example mentioned point to bucket endpoint which lead me to use the bucket endpoint instead of s3 service endpoint, do you think this needs to be updated?

**Comment by hashhar** [comment]
> AWS region-specific endpoint (e.g., http[s]://<bucket>.s3-<AWS-region>.amazonaws.com).

@optimus-kart Thanks for catching that. The example is indeed misleading. It should've been `http[s]://s3.<AWS-region>.amazonaws.com` Would you want to contribute a fix to the docs? If not I can take care of it.

**Comment by optimus-kart** [comment]
@hashhar  I will raise a PR for the same. thanks
