### ISSUE TITLE
Superset queryPrepare and Describe functions are not applicable 

### ISSUE THREAD

**Issue by YY0919** [trinodb/trino#8957]
Hey, I worked on creating dashboards based on Trino + Superset. Both of them are the latest version. I followed the instructions from https://trino.io/docs/current/sql/prepare.html to display the lineage of the query output. I got a syntax error after running the following query: 

```
PREPARE my_select1 FROM
SELECT * FROM df_sample

DESCRIBE OUTPUT my_select1;
```
Below is the syntax error :
![Screen Shot 2021-08-25 at 3 56 54 PM](https://user-images.githubusercontent.com/37122917/130750700-23291cad-3c37-41ce-95b7-db629ce9ccf2.png)

Any idea will be helpful and appreciated!
Thanks,
Yang

**Comment by ebyhr** [comment]
You need to append `;` in the first statement. 
```sql
PREPARE my_select1 FROM
SELECT * FROM df_sample;

DESCRIBE OUTPUT my_select1;
```

Also, I would recommend joining to the community Slack and ask questions there.  
https://trino.io/community.html
