### ISSUE TITLE
hive add column，trino select not found this column。presto is ok

### ISSUE THREAD

**Issue by yaoshouchong** [trinodb/trino#8988]

**Comment by yaoshouchong** [comment]
Hive metastore caching disable

**Comment by hashhar** [comment]
> thrift://bj-gm-prod-cos-datacenter001:9083,thrift://bj-gm-prod-cos-datacenter002:9083

Are these two Hive metastore services backed by the same Hive metastore database?

Also can you share the steps to reproduce. i.e. the actual CREATE TABLE you run and the ALTER TABLE and the exception stack-trace?

**Comment by yaoshouchong** [comment]
yes，  two Hive metastore services backed by the same Hive metastore database。
last time，check stack-trace no error log 。
now ，online environment cut back presto sql version 225。
