### ISSUE TITLE
UNLOAD statement for writing query results to S3

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#9007]
Use case: Trino being used for federated access to join between data in Oracle and SQLServer catalogs. The result of a join query needs to be written to a consuming/downstream team's s3 bucket (ie a regular report extract file).

Currently there are 2 ways to achieve this use case in trino, but neither are optimal.
1. Spool query results to local disk (which is limited, unlike s3) and then upload from local disk to s3.
2. Setup Hive metastore, run CREATE TABLE as (and then either drop the table afterwards or always remember to create a new table name for subsequent exports to s3). Hive has its own set of infra to maintain (db, metastore, security vulnerabilities, configuration) and for no benefit, updating partitions etc slows down the overall export completion

Adding support for UNLOAD statement (https://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html or https://docs.snowflake.com/en/sql-reference/sql/copy-into-location.html#unloading-data-from-a-table-directly-to-files-in-an-external-location or https://cloud.google.com/bigquery/docs/reference/standard-sql/other-statements#exporting_data_to_csv_format) would solve this -->
```
UNLOAD ('select a.foo, b.bar from s1.a join s2.b on a.id = b.id')
TO 's3://object-path/name-prefix'
IAM_ROLE 'arn:aws:iam::<aws-account-id>:role/<role-name>';
```

**Comment by ndrluis** [comment]
I have a use case to use unload to consume the data through batching to generate pre aggregations on [Cube](https://cube.dev/).

Cube already has an [implementation](https://github.com/cube-js/cube.js/pull/4039) to consume unloaded data from Athena and would be nice to Trino have the unload feature to make possible to us moving from Athena to Trino.

**Comment by ebyhr** [comment]
Let me close as duplicate of https://github.com/trinodb/trino/issues/19981
