### ISSUE TITLE
Populate split_offsets in Iceberg metadata

### ISSUE THREAD

**Issue by phd3** [trinodb/trino#9018]
Iceberg allows writers to store split offsets for every data file. These offsets are used by Iceberg during split generation to align splits with file format specific data boundaries (e.g. ORC stripes). Trino's Iceberg writer should also write this field, but it doesn't seem to currently. Trino code change should be in `CommitTaskData` and `IcebergMetadata#finishInsert`.

Relevant links: [split_offset in the spec](https://iceberg.apache.org/spec/#manifests) , [Iceberg's ORC file appender](https://github.com/apache/iceberg/blob/master/orc/src/main/java/org/apache/iceberg/orc/OrcFileAppender.java#L108), [Offset-aware task generator](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/BaseFileScanTask.java#L108)

**Comment by findepi** [comment]
per @alexjo2144 's https://trinodb.slack.com/archives/CJ6UC075E/p1654720714647439?thread_ts=1654706006.485319&cid=CJ6UC075E we probably want to ignore these offsets, so i don't think a need to write them.

(if it matters for some other client applications, a contribution is still to be accepted, I am just commenting on purposefulness from Trino perspective)

**Comment by ebyhr** [comment]
Related issue https://github.com/trinodb/trino/issues/14241

**Comment by findepi** [comment]
Tagged as `performance` as this may improve scheduling overhead (per offline discussion with @sopel39 @dain @alexjo2144 )

**Comment by findepi** [comment]
> These offsets are used by Iceberg during split generation to align splits with file format specific data boundaries (e.g. ORC stripes)

I assume offset are aligned with ORC stripes.
But is every stripe represented in `split_offsets`? or the split_offsets are less frequent than the stripe boundaries?

I like aligning the generated splits with ORC stripes / Parquet row groups, but I don't like the fact that the data writer dictates how the data reader reads the data.
Currently, when split_offsets is present, Iceberg library will create one split per offset:
https://github.com/findepi/iceberg/blob/c07f2aabc0a1d02f068ecf1514d2479c0fbdd3b0/core/src/main/java/org/apache/iceberg/OffsetsAwareSplitScanTaskIterator.java#L75

When split offsets are not present, Iceberg will create splits of 128 MB size 
https://github.com/apache/iceberg/blob/fa9d0dad7d0ae1c32cbf640019fba0182d400490/core/src/main/java/org/apache/iceberg/TableProperties.java#L208
https://github.com/apache/iceberg/blob/b8db3f00424c2cc2910a760b9068d38916e8c27a/core/src/main/java/org/apache/iceberg/BaseContentScanTask.java#L104-L105

I don't know how split_offsets are written by Iceberg writers, but if Iceberg library deems 128 MB splits to be optimal, I would expect split_offsets to be aligned with that thinking: no 1-1 mapping with stripes/row groups, and ~128MB apart from each other.

At the same time, the Trino Hive connector creates 32 MB splits for first ~6GB of the table, and then 64 MB.
The small initial splits are there to automatically get more parallelism from a table scan, without users needing to tune anything.

I think that Trino Iceberg connector should follow similar logic, to avoid being inherently slower (less parallel) than the Hive connector on similar data.

Therefore I think in IcebergSplitSource we should have a concept of "initial split size" and "max split size".
We can use split_offsets if present to further align splits, but that may not matter a lot in practice.

cc @raunaqmorarka @alexjo2144 @sopel39 @dain @losipiuk

**Comment by findepi** [comment]
@raunaqmorarka suggested that Hive's smaller split size generally may help with textual files, but is not necessarily helpful with Iceberg/Parquet.

@dain @electrum please chime in here too.

cc @alexjo2144

**Comment by findepi** [comment]
> At the same time, the Trino Hive connector creates 32 MB splits for first ~6GB of the table, and then 64 MB. The small initial splits are there to automatically get more parallelism from a table scan, without users needing to tune anything.
> 
> I think that Trino Iceberg connector should follow similar logic, to avoid being inherently slower (less parallel) than the Hive connector on similar data.

@electrum shared offline the smaller initial splits in Hive are only useful for text files.
cc @sopel39 @raunaqmorarka
