### ISSUE TITLE
Docker Documentation and Tutorials

### ISSUE THREAD

**Issue by omgsauce** [trinodb/trino#903]
Hello,

I open this issue to understand what It is needed for Docker Documentation and how to add tutorials and where.

I understand Docker Docs in this way: 
1)Basic Configuration start It.
2)Complex Configuration run presto cli and presto admin, etc.

What kind of workflow is better?
For example: I can update Docker Readme with basic instructions and add complex tutorials somewhere else, in my GitHub Page or in your GitHub Blog.

You can review my GitHub in repository worldwide-tech-travel/sketch/PrestoSQL md file. There is a docker compose for PrestoSQL plus Superset.
There is only one more thing to do presto-admin hands on and practise.

**Comment by findepi** [comment]
@OliverMorenoGonzalez thank you for your initiative!
We already have one tutorial in the documentation -- https://prestosql.io/docs/current/connector/hive-gcs-tutorial.html
I think we should have Docker documentation, usage instructions and recipes also in our docs.
cc @electrum

**Comment by OliverMorenoGonzalez** [comment]
Perfect.

I am going to read about the cla, and later fork the presto/prestosql.io and continue with process.

English It is not my first language so I will expect from reviewers some changes/help to make It more readable, of course I will review and review before send a pull request.

You can close this issue if It is all clear.

**Comment by findepi** [comment]
@OliverMorenoGonzalez cool.
The docs are hosted @ https://prestosql.io/docs/ and their sources are here, in this repo: https://github.com/prestosql/presto/tree/master/presto-docs

**Comment by findepi** [comment]
BTW docs building instructions:
https://github.com/prestosql/presto/blob/bee2029f41b81408d8db151fa2b30ddcdba46cb6/presto-docs/pom.xml#L19-L28

**Comment by mosabua** [comment]
This exists now in the docs https://trino.io/docs/current/installation/containers.html
