### ISSUE TITLE
Update _schema collection in MongoDB doc

### ISSUE THREAD

**Issue by rosewms** [trinodb/trino#9048]
[See 359 release notes in the MongoDB section](https://trino.io/docs/current/release/release-359.html#mongodb-connector).

> Skip creating an index for the _schema collection if it already exists.

**Comment by academy-codex** [comment]
@rosewms What is this issue pointing to exactly ?

**Comment by rosewms** [comment]
@academy-codex this issue notes that we need to update the existing MongoDB docs to include a new explanation of the `_schema` functionality based on the linked release notes.

**Comment by ebyhr** [comment]
It's the details of internal implementation and I think exposing the information to users isn't helpful. Let me close this issue.
