### ISSUE TITLE
[MariaDB connector] Invalid value of epochMicros

### ISSUE THREAD

**Issue by valeriano-manassero** [trinodb/trino#9054]
Following a discussion on Slack channel, starting with version 359 we have support for higher precision timestamps on MySQL.

One more reference here: https://github.com/trinodb/trino/pull/7198#issuecomment-817321405

In my case, when executing a query involving timestamps on a `10.1.32-MariaDB`, I got:

```
Invalid value of epochMicros for precision 0: 1630324792160396
```

This is preventing an upgrade forcing me to stay on 358.

**Comment by ebyhr** [comment]
Relates to https://trinodb.slack.com/archives/CGB0QHWSW/p1630387787057000

**Comment by findepi** [comment]
We don't have a MariaDB connector. Let's continue under https://github.com/trinodb/trino/pull/10046.

**Comment by willshen** [comment]
For paper trail's sake, this should be fixed by https://github.com/trinodb/trino/pull/12606

**Comment by xiaoyi-ge** [comment]
Hi there, I got the same issue recently from a clickhouse connector 

```
Invalid value of epochMicros for precision 3: 1588336955848084
```

Where I just simply query from a DateTime64(6) column. 

Is it related to this?
