### ISSUE TITLE
DROP TABLE IF EXISTS silently ignores views 

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#9129]
With Hive connector

```
trino:default> CREATE TABLE one (a varchar);
            -> CREATE VIEW two AS SELECT * FROM one;
CREATE TABLE
CREATE VIEW
```

`DROP TABLE` is rejected on a view:
```
trino:default> DROP TABLE two;
Query 20210906_150832_00015_id3y3 failed: line 1:1: Table 'hive.default.two' does not exist, but a view with that name exists. Did you mean DROP VIEW hive.default.two?
```

Now this should fail informing that relation indeed exists, but is not a table -- but succeeds:
```
trino:default> DROP TABLE IF EXISTS two;
DROP TABLE
```

nothing got dropped:
```
trino:default> SELECT * FROM two;
 a
---
(0 rows)
```

**Comment by ronnuriel** [comment]
can you assign me to this issue ?

**Comment by ronnuriel** [comment]
i have installed hadoop and hive  ,
how can i get data for testing hive and configurations ?

**Comment by sopel39** [comment]
> how can i get data for testing hive and configurations ?

You need to create view and then use `DROP TABLE IF EXIST` on that view

**Comment by ronnuriel** [comment]
> > how can i get data for testing hive and configurations ?
> 
> 
> 
> You need to create view and then use `DROP TABLE IF EXIST` on that view

How do i create a view im new

**Comment by sopel39** [comment]
Please refer to Trino documentation: https://trino.io/docs/current/

**Comment by wendigo** [comment]
@ronnuriel are you working on that?

**Comment by kyo-tom** [comment]
@wendigo can I work for this issuse?

**Comment by wendigo** [comment]
@kyo-tom sure, go ahead :)

**Comment by kyo-tom** [comment]
> 

I had see issues #9023. In my opinion, the sql of ‘DROP TABLE IF EXISTS two’ should be success。when the view named two is not exists，this sql will success but why when the view named two is exists，this sql should be fail and return fail information. I only execute drop table,the result should not be change by view

**Comment by kyo-tom** [comment]
> 

I had see issues #9023. In my opinion,

**Comment by dchvn** [comment]
@kyo-tom Are you still working on this? Can I go on it?

**Comment by Riddle4045** [comment]
@sopel39  @dchvn  @kyo-tom I ran into this issue recently and I have a review ready for the fix,  Can I publish it?
Draft request - https://github.com/trinodb/trino/pull/11554

**Comment by sopel39** [comment]
@Riddle4045 please go ahead
