### ISSUE TITLE
`TIMESTAMP` doesn't support function returning string like `SUBSTR`

### ISSUE THREAD

**Issue by ljfgem** [trinodb/trino#9140]
We can query
```
SELECT "date"(TIMESTAMP '2021-08-20');
```
in trino. 

However, if we query
```
SELECT "date"(TIMESTAMP "SUBSTR"('2021-08-20', 1, 10));
```
it will throw exception:
```
mismatched input 'TIMESTAMP'. Expecting: ')', '*', 'ALL', 'DISTINCT', 'ORDER', <expression>
```
Looks like `TIMESTAMP` only supports pure string at present.

**Comment by martint** [comment]
`TIMESTAMP <string value>` is a special construct in SQL to represent timestamp literals, so it is by design that it doesn't take anything other than a literal string as a value.

You can achieve that by using a `CAST`, instead:

```
SELECT CAST(substr('2021-08-20', 1, 10) AS timestamp)
```
