### ISSUE TITLE
Convert To UTC Timestamp

### ISSUE THREAD

**Issue by krisfyler** [trinodb/trino#9196]
How can you convert to UTC in Presto?

cast(replace(replace(replace(cast(to_utc_timestamp(to_timestamp(cast(`timestamp` as STRING), 'yyyyMMddHHmmss'), 'Los Angeles/America') AS STRING), '-', ''), ' ',''), ':','') AS BIGINT) as timestamp

**Comment by ebyhr** [comment]
There is [at_timezone](https://trino.io/docs/current/functions/datetime.html#at_timezone) function. 

By the way, I would recommend asking questions in Slack instead of GitHub issue. 
https://trino.io/community.html
