### ISSUE TITLE
359 Hive connector doc updates

### ISSUE THREAD

**Issue by rosewms** [trinodb/trino#9210]
[Update to reflect 359 release functionality](https://trino.io/docs/current/release/release-359.html#hive-connector):

~Add support for Hive views which use GROUP BY over a subquery that also uses GROUP BY on matching columns. (#7635)~
Add support for granting UPDATE privileges when hive.security=sql-standard is used. (#8279)
~Add support for inserting data into CSV and TEXT tables with skip_header_line_count table property set to 1. The same applies to creating tables with data using CREATE TABLE ... AS SELECT syntax. (#8390)~
~Disallow creating CSV and TEXT tables with data if skip_header_line_count is set to a value greater than 0. (#8373)~

**Comment by findepi** [comment]
> Add support for Hive views which use GROUP BY over a subquery that also uses GROUP BY on matching columns. (#7635)

> Add support for inserting data into CSV and TEXT tables with skip_header_line_count table property set to 1. The same applies to creating tables with data using CREATE TABLE ... AS SELECT syntax. (#8390)

> Disallow creating CSV and TEXT tables with data if skip_header_line_count is set to a value greater than 0. (#8373)

These are bugfixes and don't need to be documented beyond release note entries.

> Add support for granting UPDATE privileges when hive.security=sql-standard is used. (#8279)

cc @raunaqmorarka

**Comment by raunaqmorarka** [comment]
I had updated docs in #8279 itself to mention UPDATE in GRANT docs https://trino.io/docs/current/sql/grant.html?highlight=update
