### ISSUE TITLE
Implement type mapping tests for Druid connector

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#9215]
The Druid connector doesn't support writes. And we cannot directly write to Druid. So this makes type mapping tests (and others difficult to implement).

Data ingestion into Druid needs to be done via external mechanisms like files, Kafka etc.

We can follow the same approach as in Pinot tests - https://github.com/trinodb/trino/blob/master/plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotIntegrationSmokeTest.java#L86.

We can use `TestingKafka` and push records to it and configure an ingest into Druid via Kafka.
This will allow us to prepare test data of our choice using Kafka and then test the Druid connector against it.

**Comment by ebyhr** [comment]
Druid type mapping test was implemented in #13335
