### ISSUE TITLE
Possibility to store distant past or distant future dates in nanosecond precision in Hive connector with new Parquet writer

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#9244]
Per https://github.com/apache/parquet-format/blob/master/LogicalTypes.md, nanosecond precision timestamp should be stored as INT64
even though it can only hold values within 1677-09-21 00:12:43 and 2262-04-11 23:47:16 range.

This can be problematic in practice, as Trino users have been witnessed using dates such as `9999-12-31` and `0001-01-01`.
Obviously, these dates do not represent actual date of some event, but rather are used for technical reasons.

Note that this doesn't apply to:

- Spark: in spark timestamps have microsecond precision. This gives timestamp range `-290308-12-21T19:59:05` to `+294247-01-10T04:00:54`
- Iceberg and Iceberg connector: the Iceberg spec mandates that timestamp values have microsecond precision
- Hive: latest Hive version we have available for testing (HDP's Hive 3.1.0) uses INT96 for encoding values, which allows it to store timestamps beyond `9999-12-31`.
- Hive connector unless nanosecond precision is enabled and experimental writer is enabled (old writer uses INT96 too)
  - note however that it would be good to be able to enable the new writer by default
  - Hive connector would use nanosecond precision if it wasn't for performance difference between short and long timestamps. If we could figure out performance, we wouldn't need hive `timestamp_precision` toggle at all.

cc @martint @phd3 @losipiuk

**Comment by findepi** [comment]
@raunaqmorarka is this solved for Hive by https://github.com/trinodb/trino/pull/12857 ?

**Comment by raunaqmorarka** [comment]
Indeed, I checked that for nano precision in hive we are now able to store and read big values like '294247-01-10 04:00:54.123456789' and '-290307-12-31 19:58:05.123456789' with the int96 encoding in the optimized writer. Earlier this used to fail with `long overflow` exception due to lower capacity in in64 encoding.

**Comment by findepi** [comment]
Thanks for checking @raunaqmorarka 
And in Delta and Iceberg we should be OK. Both these formats define timestamps to have microsecond precision, and then int64 is well enough.
