### ISSUE TITLE
Optimizer infinite loop with OR partition clause

### ISSUE THREAD

**Issue by JamesRTaylor** [trinodb/trino#9250]
The optimizer gets in an infinite loop when planning a query with an OR on the partition column. For example:

    SELECT 'foo'
    FROM my_table
    WHERE a IS NULL OR a = ''
    AND ds='2021-08-01'

This did not occur in the 346 release. For a repro, see this PR: https://github.com/trinodb/trino/pull/9246

**Comment by JamesRTaylor** [comment]
cc. @martint @phd3

**Comment by martint** [comment]
It's caused by 39ebb43839c554469ee7dcde82199fa1db9352f6. cc @findepi

**Comment by martint** [comment]
It's ping-ponging between SimplifyExpressions and RemoveRedundantTableScanPredicate

**Comment by martint** [comment]
SimplifyExpressions is changing the filter from:

```
((("a" = VARCHAR '') OR ("a" IS NULL)) AND (("a" IS NULL) OR ("ds" = VARCHAR '2021-08-01')))
```

to 

```
((("a" IS NULL) OR ("a" = VARCHAR '')) AND (("a" IS NULL) OR ("ds" = VARCHAR '2021-08-01')))
```

RemoveRedundantTableScanPredicate is rewriting the filter from 

```
((("a" IS NULL) OR ("a" = VARCHAR '')) AND (("a" IS NULL) OR ("ds" = VARCHAR '2021-08-01')))
```

to 

```
((("a" = VARCHAR '') OR ("a" IS NULL)) AND (("a" IS NULL) OR ("ds" = VARCHAR '2021-08-01')))
```
