### ISSUE TITLE
How to setup a embedded server to test local connector

### ISSUE THREAD

**Issue by chgxtony** [trinodb/trino#9261]
Hi , I just want a lightweight embedded server to develop and test local connector, how to setup? I cannot find any documents in trino doc websites

**Comment by hashhar** [comment]
https://github.com/trinodb/trino#running-trino-in-your-ide

If you want to add a connector to Trino itself then you can follow the document above.
You can add more catalogs e.g. one using your custom connector by modifying the config files at https://github.com/trinodb/trino/blob/7e44c84098d391f3cffd2166c708556251a09695/testing/trino-server-dev/etc (`testing/trino-server-dev/etc`).

If you want to test an existing connector with Trino you can take a look at testcontainer's Trino container - https://www.testcontainers.org/modules/databases/trino/.
You can mount files into the container and run integration tests against it.

Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation on #dev. There are a lot more people there including people who most likely maintain a few of their own connectors.

**Comment by ebyhr** [comment]
Also, you can use DistributedQueryRunner class. MySQL connector's example is 
https://github.com/trinodb/trino/blob/master/plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/MySqlQueryRunner.java
