### ISSUE TITLE
Grouped execution on partition keys

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#930]
Today, grouped ("bucketed") execution is supported on bucketed tables.
Add support for grouped execution for partitioned unbucketed tables.

For example, joining partitioned tables on partition key can be handled the same way as joining bucketed tables on bucketing key.

Ref https://github.com/prestodb/presto/issues/11876

**Comment by jacobbaskin** [comment]
I have a PR in the works for this for the Hive connector, but I am wondering what the right way is to configure this setting. We are mainly interested in enabling this to lower RAM usage, but I want to be mindful of potential tail-latency issues. So in particular:

- Should this be just on/off as it is for bucketing, or should there be a (configurable) minimum number of partitions required in order for this to be enabled (or, alternatively, a max % of a table that's in a single partition, to account for skew when partition statistics are present?)
- If a table is partitioned and bucketed, should the groups for grouped execution be (partition * bucket) or should we choose one or the other?

I know this is an old issue -- @findepi have you thought about these questions / do you have preferences?

**Comment by jacobbaskin** [comment]
What does this do for colocated_join though?

**Comment by jacobbaskin** [comment]
I will also try to get on the Slack to ask some more questions, but generally the idea that in order for Trino to run your query you have to store the full shuffle state somewhere (in memory or on disk) all at once seems problematic to me so I hope that even with grouped execution deprecated there will be some way to avoid this.
