### ISSUE TITLE
Iceberg partition pruning does not work for predicates not expressible by tuple domain

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#9309]
Partition pruning in Iceberg does not work for filters that are passed via `Constraint.predicate` (as opposed to `Constraint.summary`).

Repro:
```
CREATE TABLE nation_partitioned WITH (partitioning = ARRAY['regionkey']) AS SELECT * FROM nation;
SELECT * FROM nation_partitioned WHERE regionkey % 5 = 3;
-- whole table is read
```

cc: @findepi

**Comment by findepi** [comment]
May require https://github.com/trinodb/trino/issues/7608
