### ISSUE TITLE
[360] Add ``write.batch-size`` to Clickhouse connector config properties

### ISSUE THREAD

**Issue by rosewms** [trinodb/trino#9313]
[360 release note info](https://trino.io/docs/current/release/release-360.html#clickhouse-connector) that should be documented in the ClickHouse connector:

- Add write.batch-size connector configuration property to control JDBC batch size used during writes. It can also be controlled using the write_batch_size session property. (#8434)

**Comment by hashhar** [comment]
See https://github.com/trinodb/trino/pull/9251. I think it's already present now.

Closing, please re-open if you think anything more needs to be done.

**Comment by rosewms** [comment]
@hashhar good catch, I searched for it within the issues and it didn't come up and apparently I forgot to look at the recent PRs. Thanks.
