### ISSUE TITLE
Document how to deploy a custom plugin

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#9315]
Could be a connector, or UDF or whatever ..

Basically just extract zip archive of plugin build output into `plugin` folder as a separate directory.

Either document in developer guide or somewhere in deployment.rst (or break that document up since its mostly about the tarball.

**Comment by RCHowell** [comment]
There is information about deploying a custom plugin here - https://trino.io/docs/current/develop/spi-overview.html

Is there something more you would like to see, or how could this be improved?

**Comment by ebyhr** [comment]
@mosabua Could you confirm @RCHowell's comment?

**Comment by mosabua** [comment]
I think that is probably good. Overall our installation docs are not that great and need improvement and could then link to that section.. but for now I think w can close this.
