### ISSUE TITLE
Iceberg: parquet written by spark causes queries to run for hours

### ISSUE THREAD

**Issue by clemensvonschwerin** [trinodb/trino#9320]
Trino version in use: 361
Spark version in use: 3.1.2 / 3.1.1 (observed with both)
Issue: We are writing to trino tables (created in trino) in an iceberg catalog using spark in the overwritePartitions mode. The format for the table data is PARQUET. Writing is possible without an issue and simple select queries like "SELECT * FROM test_table" are executed with normal speed. However if we add a WHERE, GROUP BY clause or any aggregation or JOIN the query takes hours (no exaggeration here) in stage 1 (sometimes also in stage 2 if there are 4 or 5 stages in total). 

Not that if we run "INSERT INTO test_table_2 SLECT * FROM test_table" on trino itself without spark being involved and try our problematic queries on test_table_2 they finish within seconds. The parquet files show some differences examining their metadata: 

**Written by spark:**

```
file:                                   file:/path/to/file.parquet
creator:                                parquet-mr version 1.11.1 (build 765bd5cd7fdef2af1cecd0755000694b992bfadd)
extra:                                  iceberg.schema = {"type":"struct","fields":[...]}

file schema:                            table
--------------------------------------------------------------------------------
col_1:                               OPTIONAL BINARY L:STRING R:0 D:1
col_2:                               OPTIONAL INT32 L:DATE R:0 D:1
col_3:                               OPTIONAL FLOAT R:0 D:1

row group 1:                            RC:224132 TS:35272347 OFFSET:4
--------------------------------------------------------------------------------
col_1:                                BINARY GZIP DO:0 FPO:4 SZ:864149/9194073/10.64 VC:224132 ENC:PLAIN,BIT_PACKED,RLE ST:[min: abc, max: zxy, num_nulls: 0]
col_2:                                INT32 GZIP DO:0 FPO:864153 SZ:870/680/0.78 VC:224132 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE ST:[min: 2016-01-01, max: 2016-01-31, num_nulls: 0]
col_3:                                FLOAT GZIP DO:0 FPO:2921553 SZ:700399/896969/1.28 VC:224132 ENC:PLAIN,BIT_PACKED,RLE ST:[min: -683004.1, max: 555002.2, num_nulls: 0]
```

**Written by trino:**

```
file:                                   file:/path/to/file2.parquet
creator:                                null

file schema:                            table
--------------------------------------------------------------------------------
dim_invoice_position:                   OPTIONAL BINARY L:STRING R:0 D:1
dim_date:                               OPTIONAL INT32 L:DATE R:0 D:1
mes_spend_curr_1:                       OPTIONAL FLOAT R:0 D:1

row group 1:                            RC:96295 TS:5292160 OFFSET:4
--------------------------------------------------------------------------------
dim_invoice_position:                    BINARY GZIP DO:0 FPO:4 SZ:301393/2382725/7.91 VC:96295 ENC:DELTA_BYTE_ARRAY ST:[min: abc, max: zxy, num_nulls: 0]
dim_date:                                INT32 GZIP DO:0 FPO:301397 SZ:317/348/1.10 VC:96295 ENC:RLE_DICTIONARY ST:[min: 2016-01-01, max: 2016-01-31, num_nulls: 0]
mes_spend_curr_1:                        FLOAT GZIP DO:0 FPO:1338947 SZ:296582/385216/1.30 VC:96295 ENC:PLAIN ST:[min: -683004.1, max: 555002.2, num_nulls: 0]
```

Has anyone encountered this behaviour already? Can anybody share any pointers or ideas regarding why this problematic query behaviour could happen and how to avoid while still writing the parquet files using spark ?

**Comment by hashhar** [comment]
This was fixed in 362 and I believe https://github.com/trinodb/trino/pull/9161 is the issue/PR.

You can try to see if the Iceberg catalog exposes a session property `parquet_use_column_index`. If so, you can set it to false to workaround this.

**Comment by clemensvonschwerin** [comment]
@hashhar awesome, thank you for the quick answer. I will try it out and keep you posted.

**Comment by findepi** [comment]
> You can try to see if the Iceberg catalog exposes a session property `parquet_use_column_index`. If so, you can set it to false to workaround this.

It does not (https://github.com/trinodb/trino/issues/9097#issuecomment-913460609)

Closing per https://github.com/trinodb/trino/pull/9161
