### ISSUE TITLE
Why is the performance difference so big?

### ISSUE THREAD

**Issue by Stevenchooo** [trinodb/trino#9343]
SELECT xx FROM xxx WHERE "$part_event" IN ('user_login' ,'play_game')
VS
SELECT xx FROM xxx WHERE "$part_event" IN ('user_login') UNION ALL SELECT xx FROM xxx WHERE "$part_event" IN ('play_game')

The first one consumes ten times more time than the second one.
Does anyone know why.

![image](https://user-images.githubusercontent.com/20969863/134480408-a35f4f2b-dad8-4f48-8ea1-838941456c4d.png)
![image](https://user-images.githubusercontent.com/20969863/134480429-ba8736fa-adba-40fe-a2d9-935596c5dddf.png)

**Comment by hashhar** [comment]
You can run EXPLAIN to see the difference in the query plan. The non-union all version would only have a single TableScan operation.

UNION ALL requires the table to be scanned twice (i.e. each side of union all needs to run separately) so it would take longer time.

Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there on #troubleshooting. There are more people there and it helps keep GitHub limited to issues.
