### ISSUE TITLE
date column name not parsing properly in passthrough query from trino to pinot

### ISSUE THREAD

**Issue by lokipatel** [trinodb/trino#9373]
Hello all,
I have connected trino with pinot. Its working fine but the only problem that i am facing in tables whose columns have “date” as the column name for datefield.

I am getting the error 

> Error = org.apache.calcite.sql.parser.SqlParseException: Encountered "date ," at line 1, column 8.

PFA the file for reference.  I humbly request you to please suggest some solutions on this

[pinot_trino_error.txt](https://github.com/trinodb/trino/files/7225421/pinot_trino_error.txt)

**Comment by ebyhr** [comment]
Relates to https://trinodb.slack.com/archives/CGB0QHWSW/p1632476513364000

**Comment by hashhar** [comment]
cc: @elonazoulay Does the Pinot require a different form of quoting in the passthrough part?

**Comment by ebyhr** [comment]
Let's fix normal query builder first because the attached log uses doesn't dynamic tables.  
https://github.com/trinodb/trino/blob/master/plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotQueryBuilder.java
