### ISSUE TITLE
Use isAdjustedToUTC=false when writing timestamps with the native Parquet writer

### ISSUE THREAD

**Issue by jirassimok** [trinodb/trino#9438]
In Parquet, a `TIMESTAMP` with `isAdjustedToUTC=false` is the proper representation for a SQL timestamp, [representing a collection of date and time fields](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#local-semantics-timestamps-not-normalized-to-utc) rather than an instant in time. This is very similar to Trino's own internal representation of timestamps.

With `isAdjustedToUTC=true`, it represents an instant in time, similar to `TIMESTAMP WITH TIME ZONE`, but with UTC as the implicit time zone for all values.

This is already referenced in a few places in the native writer's code:
- https://github.com/trinodb/trino/blob/2be4a3ebe39e29f7700a4e4dfea323bb8a5dafe3/lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetSchemaConverter.java#L138
- https://github.com/trinodb/trino/blob/4558f9db479b4dbc9cb0e32dd5db617cc14ff09e/lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriters.java#L193

**Comment by jirassimok** [comment]
It might also be appropriate to read timestamps with `isAdjustedToUTC=true` as timestamps with time zone, but this might cause issues with data previously written by Trino.

(On the other hand, reading such data as plain timestamps could cause issues for anyone expecting instant semantics.)

**Comment by findepi** [comment]
I had the same conclusion when working on #9188. I should have followed up on that. #9465
