### ISSUE TITLE
Unable to Query Iceberg $partitions if table contains columns called row_count, file_count or total_size

### ISSUE THREAD

**Issue by SamWheating** [trinodb/trino#9519]
The Iceberg `table$partition` system table includes columns called `row_count`, `file_count` and `total_size` as well as a column with column stats for each partition. 

If an iceberg table happens to have a column which uses any of these names, it will create a duplicate key and make the partition spec un-queryable for these tables. 

To replicate:

```sql
CREATE TABLE IF NOT EXISTS iceberg.testdb.test_orders (
    order_id BIGINT,
    order_date DATE,
    row_count BIGINT,
    customer VARCHAR,
    country VARCHAR)
WITH (
    format = 'Parquet',
    partitioning = ARRAY['order_date']
)
```

```
> show columns from iceberg.testdb."test_orders$partitions"

order_date	date
row_count	bigint												-> row_count column #1
file_count	bigint
total_size	bigint
order_id	row(min bigint, max bigint, null_count bigint)
row_count	row(min bigint, max bigint, null_count bigint)		-> row_count column #2
customer	row(min varchar, max varchar, null_count bigint)
country	    row(min varchar, max varchar, null_count bigint)
```

```
> select * from iceberg.testdb."test_orders$partitions"

Query failed (#20211005_182639_00387_29hec): Multiple entries with same key: row_count=row_count and row_count=row_count java.lang.IllegalArgumentException: Multiple entries with same key: row_count=row_count and row_count=row_count
```

I understand why this happens, but I'm wondering if there would be a better way to handle this case (for example, renaming the row_count, file_count or total_size columns in the event of an overlap with table columns)

Also - I'd be happy to contribute a fix for this if a maintainer is able to provide some guidance.

**Comment by SamWheating** [comment]
This seems like a reasonable solution which ensures there aren't any collisions. 

Would it be alright if I try to make these changes? I think I will have some time next week.

Feel free to assign the issue to me 👍

**Comment by findepi** [comment]
i agree with https://github.com/trinodb/trino/issues/9519#issuecomment-938191139.

cc @losipiuk @phd3
