### ISSUE TITLE
Add Hive table property to for arbitrary properties

### ISSUE THREAD

**Issue by dain** [trinodb/trino#954]
Currently only table properties explicitly listed [HiveTableProperties](https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/HiveTableProperties.java) are supported in Presto, but many Hive environments use extended properties for administration.  

Add a property named `extra_properties` of type `MAP(VARCHAR, VARCHAR)`.  

On read (e.g. `SHOW CREATE TABLE`) will show only the properties not mapped to existing table properties, and properties created by presto such as `presto_version` and `presto_query_id`.

On write, these properties are merged with the other properties, and if there are duplicates and error is thrown.

This is equivalent of Hive's `TBLPROPERTIES`.

**Comment by ankitdixit** [comment]
@dain Can i work on this.

**Comment by ankitdixit** [comment]
@dain Can you please help me understand why we do not want to show properties mapped to existing table properties?

**Comment by dain** [comment]
> @dain Can you please help me understand why we do not want to show properties mapped to existing table properties?

I believe it would be confusing to users if the a property was presented in two different ways.  I expect this would raise a lot of questions about which one is supposed to be used, and what happens on conflicts.  Also, things like "I only set X and now I see X and Y".

In general, I see this feature as an "escape hatch" for cases when we don't directly support a standard property, or there the user has a custom property in their environment, but I want to encourage the use of the Presto property system because it is safer for end users to use due to the type safety of the syntax and the property specific validation code we have in some cases.

**Comment by ankitdixit** [comment]
@dain Please have a look at the initial WIP pr, i am able to take input and store map but while visiting in `ShowCreateTable `, we have to convert map into an expression, which it seems is not supported as of yet.
One workaround could be to create a String out of map and then convert that to expression.
@Praveen2112 pointed out https://github.com/prestodb/presto/issues/5065, adding literal type for map would inherently solve this problem.
Need your inputs on which way to approach.

**Comment by findepi** [comment]
@posulliv has https://github.com/trinodb/trino/pull/9475 open for this
and @dain  has https://github.com/trinodb/trino/pull/9523

should we have discussion about way forward?
if it was for me to decide, i would just go with adding `extra_properties` property, so i personally don't need a discussion :)

**Comment by Chaho12** [comment]
Any plans on developing this? For iceberg, we need to set properties to clean data files
