### ISSUE TITLE
can't select or describe elasticsearch indices in Trino because of NullPointerException

### ISSUE THREAD

**Issue by GeksterOne** [trinodb/trino#9545]
I am trying to use Trino (official docker version) with existing elasticsearch cluster. What I already achieved I can get list of indices using command "SHOW tables from elasticsearch.default;" But when I try to DESCRIBE OR SELECT one in indices I get internal error "Query 20211007_084419_00016_73piy failed: Internal error" in cli and in server I get this:

> 2021-10-07T08:39:45.250Z WARN I/O dispatcher 3
> org.elasticsearch.client.RestClient request [GET https://data-elasticsearch.server.com:443/dr_index_2021.04.01_999/_mappings] returned 1 warnings: [299 Elasticsearch-6.8.16-1f62092 "[types removal] The parameter include_type_name should be explicitly specified in get mapping requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', which means responses will omit the type name in mapping definitions."] 2021-10-07T08:39:45.255Z DEBUG dispatcher-query-22 io.trino.execution.QueryStateMachine
> Query 20211007_083944_00013_73piy is FAILED 2021-10-07T08:39:45.254Z
> DEBUG dispatcher-query-19 io.trino.execution.QueryStateMachine
> Query 20211007_083944_00013_73piy failed java.lang.NullPointerException at io.trino.plugin.elasticsearch.decoders.DecoderType.of(DecoderType.java:41) at io.trino.plugin.elasticsearch.DecoderDescriptor.primitiveDecoderDescriptor(DecoderDescriptor.java:48) at io.trino.plugin.elasticsearch.ElasticsearchMetadata.getDecoderDescriptor(ElasticsearchMetadata.java:142) at com.google.common.collect.CollectCollectors.lambda$toImmutableMap$6(CollectCollectors.java:182) at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) at io.trino.plugin.elasticsearch.ElasticsearchMetadata.getDecoderDescriptor(ElasticsearchMetadata.java:138) at io.trino.plugin.elasticsearch.ElasticsearchMetadata.makeColumnHandles(ElasticsearchMetadata.java:275) at io.trino.plugin.elasticsearch.ElasticsearchMetadata.makeInternalTableMetadata(ElasticsearchMetadata.java:226) at io.trino.plugin.elasticsearch.ElasticsearchMetadata.getTableMetadata(ElasticsearchMetadata.java:212) at io.trino.plugin.elasticsearch.ElasticsearchMetadata.getTableMetadata(ElasticsearchMetadata.java:207) at io.trino.spi.connector.ConnectorMetadata.getTableSchema(ConnectorMetadata.java:180) at io.trino.metadata.MetadataManager.getTableSchema(MetadataManager.java:566) at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1344) at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:360) at io.trino.sql.tree.Table.accept(Table.java:53) at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27) at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:377) at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitAliasedRelation(StatementAnalyzer.java:1861) at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitAliasedRelation(StatementAnalyzer.java:360) at io.trino.sql.tree.AliasedRelation.accept(AliasedRelation.java:71) at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27) at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:377) at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:3185) at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1955) at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:360) at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155) at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27) at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:377) at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:387) at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1169) at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:360) at io.trino.sql.tree.Query.accept(Query.java:107) at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27) at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:377) at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:340) at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:91) at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:83) at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:269) at io.trino.execution.SqlQueryExecution.(SqlQueryExecution.java:190) at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:806) at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:132) at io.trino.$gen.Trino_362____20211007_082343_2.call(Unknown Source) at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125) at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69) at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829)
I checked the latest code from github and didn't find there io.trino.plugin.elasticsearch.decoders.DecoderType class. Is it a bug?

**Comment by phd3** [comment]
After https://github.com/trinodb/trino/pull/9358, [this](https://github.com/trinodb/trino/blob/master/plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java#L223) code invokes `getType` on `toTrino` output, which may be null. 

However, the issue with null type handling is reproducible before this change too, as seen in the first stacktrace.

**Comment by GeksterOne** [comment]
@phd3 when I do select columns from table I get the same NullPointerException with the same StackTrace as in case 2. 
I think this fix can help in this case (method  toTrino(String prefix, IndexMetadata.Field field) can return null on line 374 but there is no null check after): 
Index: plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java b/plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java
--- a/plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java	(revision 357102116d2eed5865482994bd5a33f8e82d4205)
+++ b/plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java	(date 1633614926429)
@@ -220,7 +220,11 @@
                 .collect(Collectors.groupingBy(f -> f.getName().toLowerCase(ENGLISH), Collectors.counting()));
 
         for (IndexMetadata.Field field : metadata.getSchema().getFields()) {
-            Type type = toTrino(field).getType();
+            TypeAndDecoder typeAndDecoder = toTrino(field);
+            Type type = null;
+            if (typeAndDecoder != null){
+                type = typeAndDecoder.getType();
+            }
             if (type == null || counts.get(field.getName().toLowerCase(ENGLISH)) > 1) {
                 continue;
             }
