### ISSUE TITLE
Using cross join with unnest on JSON element the cross join drops records

### ISSUE THREAD

**Issue by wix-ilyaf** [trinodb/trino#9677]
when doing cross join with record that contains JSON column that we try to unnest the cross join drops records that has empty element in the JSON path, the workaround is to use left join with condition on true

example:
```
item_data, is a JSON column

cross join 
    unnest (cast(json_extract(item_data, '$') as 
            array (row (id varchar,
                        description varchar, 
                        name varchar, 
                        priceamount double, 
                        quantity double
                        )
                    )
                ) 
            ) as t(id,description, name,priceamount,quantity)   
```

**Comment by martint** [comment]
The way to think about this is as UNNEST just being a table-producing-function. For example, in:

```
SELECT * 
FROM UNNEST(ARRAY[1, 2, 3])
```

the function converts the provided array into a table. Then, the table is used in a context where any table could be referenced.

A query involving JOIN is no different. The result of UNNEST (a table) is used in the JOIN in the same way any other table would be used, taking into account the semantics of each type of JOIN (LEFT/RIGHT/INNER/CROSS).

**Comment by wix-ilyaf** [comment]
Thanks for the explanation!
