### ISSUE TITLE
Scan of Hive partitions

### ISSUE THREAD

**Issue by z-arosio** [trinodb/trino#9713]
I've a Hive catalog connected with S3, and an external table referring to parquet files in a S3 folder.
The Hive table is partitioned, accorting with the S3 subfolder structure.

If I run the following query:
```sql
select * from mycatalog.myschema.mytable
where partition_column = 'partition_value'
```
Trino scans only the data in the `partition_value` subfolder.

While, if I run the following query:
```sql
select * from mycatalog.myschema.mytable
where partition_column = (select max(partition_column) from mycatalog.myschema."mytable$partitions"
```
to have data only from the last partition, Trino scans all the partitions.

What's wrong with the second query?
How to force Trino to scan only the last partition?

Thanks

**Comment by findepi** [comment]
Closing as answered.
