### ISSUE TITLE
Trino client REST API  QueryResults pagination

### ISSUE THREAD

**Issue by ashoksri0** [trinodb/trino#9724]
I'm using TRINO rest client to get results as  JSON documents  TRINO giving me with batch results with nextUri, how I will control the result size in a batch like pagination

**Comment by ashoksri0** [comment]
any help please

**Comment by findinpath** [comment]
@ashoksri0   I think that the feature you are requesting is not yet implemented in Trino.

See https://github.com/trinodb/trino/pull/4347 and https://github.com/trinodb/trino/issues/2210

**Comment by hashhar** [comment]
Note that none of them will allow you to implement pagination if you want fixed size pages since the targetResultSize is based on amount of data in bytes rather than number of records to be returned.

**Comment by findepi** [comment]
Closing as answered
