### ISSUE TITLE
IcebergSplitSource: Support large `IN` predicates

### ISSUE THREAD

**Issue by alexjo2144** [trinodb/trino#9743]
TODO from the code:

Remove TupleDomain#simplify once Iceberg supports IN expression. Currently this is required for IN predicates on non-partition columns with large value list. Such predicates on partition columns are not supported. (See AbstractTestIcebergSmoke#testLargeInFailureOnPartitionedColumns)

@findepi : I think the TODO wording is overly optimistic, especially in context of DF, which can produce larger domains than usually.
https://github.com/trinodb/trino/pull/9193#discussion_r734572924

**Comment by findepi** [comment]
> once Iceberg supports IN expression.

Iceberg supports them (https://github.com/trinodb/trino/pull/10032 uses them)

> TODO from the code: Remove TupleDomain#simplify [...]

it apparently got removed in https://github.com/trinodb/trino/pull/9193
( https://github.com/trinodb/trino/pull/9193/files#diff-5f16ce85422fcac65b098c620431d97805cf6ca538d8166a35526004591abf8eL65 )


> I think the TODO wording is overly optimistic, especially in context of DF,

@alexjo2144 that's possible.
Maybe we should close this issue?

cc @raunaqmorarka
