### ISSUE TITLE
SQL with filter condition "or" can not be pushed down to Iceberg metadata when do sql plan 

### ISSUE THREAD

**Issue by Xiangakun** [trinodb/trino#9786]
SQL with filter condition "or" (e.g. ' select * from iceberg.iceberg_schema.tableA where id = 1 or data = 'test' ') can not be pushed down to Iceberg metadata when doing sql plan stage, which lead to such scenario can not make full use of iceberg’s MIN/MAX index. As far as I know, Iceberg itself supports filter with 'or' condition. I am wondering if it's the limit by current framework of trino ？Does anyone has good idea on this？ Thanks in advance

**Comment by findepi** [comment]
This is going to be covered by https://github.com/trinodb/trino/pull/7994.
See #18 for more info.
