### ISSUE TITLE
trino-opa-plugin

### ISSUE THREAD

**Issue by rodolfototaro** [trinodb/trino#9787]
Developing a plugin that provides a SystemAccessControl implementation that delegates authorization decisions to OPA (Open Policy Access) technology

**Comment by vagaerg** [comment]
We've been in touch with the developers of https://github.com/stackabletech/trino-opa-authorizerhttps://github.com/stackabletech/trino-opa-authorizer and created a fork of their code to be mainlined and with some tweaks.

This is a WIP, but see #17940

**Comment by YuriyGavrilov** [comment]
+1

**Comment by ebyhr** [comment]
Closing as https://github.com/trinodb/trino/pull/19532
