### ISSUE TITLE
ORC bloom filter in Trino working?

### ISSUE THREAD

**Issue by sangkeon** [trinodb/trino#9792]
I created a transactional table in ORC Format with a bloom filter for some columns in Hive, and inserted some rows in Trino.

But the bloom filter is not created in the ORC file.

Inspecting some code, I found some problems in the following.

https://github.com/trinodb/trino/blob/8f5aa1cbca7393eadfbbf3d81b57587b9a933793/plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java#L1017-L1037

1) The schema parameter does not contains keys ORC_BLOOM_FILTER_COLUMNS("orc_bloom_filter_columns") and ORC_BLOOM_FILTER_FPP("orc_bloom_filter_fpp"), but contains ORC_BLOOM_FILTER_COLUMNS_KEY("orc.bloom.filter.columns") and ORC_BLOOM_FILTER_FPP_KEY("orc.bloom.filter.fpp")

2) Keys of Properties is checked using contains() not containsKey()

3) Throw exception when fpp value is in valid range(>0.0 and <1.0)

               if (fpp > 0.0 && fpp < 1.0) {
                    throw new TrinoException(HIVE_UNSUPPORTED_FORMAT, format("Invalid value for bloom filter: %f", fpp));
                }

According to code, bloom filter options in ORCWriteOptions are never set when creating an OrcFileWriter object.

**Comment by findepi** [comment]
reopening for https://github.com/trinodb/trino/pull/10343
