### ISSUE TITLE
Pinot fails or returns incorrect results in case of IS NULL, IS NOT NULL predicates

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#9885]
1. the assumption at https://github.com/trinodb/trino/blob/dfd38e12061c0d992eaf47c56d2826f3510a6cf9/plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotQueryBuilder.java#L127
   is incorrect, as this is exactly how `Domain.notNull(type)` is represented (i.e. result of `x IS NOT NULL`)
2. the whole `io.trino.plugin.pinot.query.PinotQueryBuilder#toPredicate` method is incorrect, since it doesn't consult `domain.isNullAllowed()`, so `x IS NULL OR x > 5` is going to return incorrect results

**Comment by findepi** [comment]
cc @elonazoulay @wendigo @hashhar

**Comment by findepi** [comment]
cc @elonazoulay

**Comment by elonazoulay** [comment]
Note:
Pinot does not yet handle null values, ex. 
```
select col from table where col is null
```
will return a non-null default value.

The is not null predicate should not be pushed down. 

Will test, may have to disable pushdown of both IS NULL and IS NOT NULL since they will return different results, updating and will push a pr.
