### ISSUE TITLE
Fix raw types in TemptoPlugin

### ISSUE THREAD

**Issue by ksobolew** [trinodb/trino#9904]
The `PrestoTemptoPlugin` class implements `TemptoPlugin`, which is from the Tempto library; it declares `TemptoPlugin#getTableManagers` as returning `List<Class<? extends TableManager>>`, where `TableManager` is a raw type. Until this is fixed in Tempto, we can't get rid of raw types entirely.

**Comment by hashhar** [comment]
Closing the issue since the IDE warning / suppression comment should be sufficient reminder of this?

The issue hasn't helped in the issue being addressed anyway. 😢
