### ISSUE TITLE
package trino failed！

### ISSUE THREAD

**Issue by ImTangYun** [trinodb/trino#9911]
my command is
./mvnw  install -DskipTests
errors
[ERROR] Failed to execute goal ca.vanzyl.provisio.maven.plugins:provisio-maven-plugin:1.0.18:provision (unpack) on project trino-server-rpm: Error provisioning assembly.: java.nio.file.NoSuchFileException: /home/candy/work/gitlab/trino/core/trino-server-rpm/target/classes/trino-server-363/lib/asm-6.2.1.jar -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :trino-server-rpm

more info
candy@ubuntu:trino$ ls /home/candy/work/gitlab/trino/core/trino-server-rpm/target/classes/trino-server-363/lib/asm-6.2.1.jar -l
lrwxrwxrwx 3 candy candy 26 Nov  9 15:57 /home/candy/work/gitlab/trino/core/trino-server-rpm/target/classes/trino-server-363/lib/asm-6.2.1.jar -> ../../shared/asm-6.2.1.jar

it seems link a file that not exists，what happened？

 ls /home/candy/work/gitlab/trino/core/trino-server-rpm/target/classes/trino-server-363/
bin  lib  NOTICE  plugin  README.txt  shared

**Comment by ebyhr** [comment]
Could you share the error message? Also, I would recommend to ask in the community Slack > `#dev` channel. 
https://trino.io/slack.html

**Comment by ImTangYun** [comment]
> Could you share the error message? Also, I would recommend to ask in the community Slack > `#dev` channel. https://trino.io/slack.html

add more info，could you check again？

**Comment by ebyhr** [comment]
How about `./mvnw --version`?

**Comment by ImTangYun** [comment]
candy@ubuntu:trino$ ./mvnw --version
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: /home/candy/.m2/wrapper/dists/apache-maven-3.8.2-bin/1ku64710m9f46eultd2idql0o3/apache-maven-3.8.2
Java version: 11.0.11, vendor: Oracle Corporation, runtime: /home/candy/work/program/jdk-11.0.11
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-148-generic", arch: "amd64", family: "unix"


> How about `./mvnw --version`?

**Comment by ebyhr** [comment]
Let's continue in Slack so that we can talk interactively.
