### ISSUE TITLE
Feature Request: support for Iceberg Dynamodb catalogues 

### ISSUE THREAD

**Issue by josephDunne** [trinodb/trino#9953]
It would be great if we could setup the iceberg connecter to use a dynamodb catalogue

**Comment by ebyhr** [comment]
Let me close this issue as DynamoDB catalog is deprecated. https://lists.apache.org/thread/b92zwcvy7917bhr5t00b07f7r8qqwxqj

**Comment by nabaskes** [comment]
The above link suggests support for DDB is not deprecated.  Are we operating under the assumption that it will be?
