### ISSUE TITLE
io.airlift.discovery.client.DiscoveryException: Announcement failed for http://presto-coordinator-service:8099

### ISSUE THREAD

**Issue by zhenyangdong** [trinodb/trino#9964]
hi,
I used the latest version 363/364 and successed deploy trino stand alone
Then I try to create image to deploy trino using over docker，and start it on a physical single node ，it also runs well.
Then I need to run trino on kubernetes, it cause a error

**io.airlift.discovery.client.DiscoveryException: Announcement failed for http://presto-coordinator-service:8099**

it seems can not start the discovery server, can someone give me advice？

**### configmap**

> apiVersion: v1
kind: ConfigMap
metadata:
  name: presto-config-cm
  labels:
    app: presto-coordinator
data:
  node.properties: |-
    node.environment=staging
    node.data-dir=/opt/presto/data
  jvm.config: |-
    -server
    -Xmx16G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
  config.properties: |-
    coordinator=${COORDINATOR_NODE}
    node-scheduler.include-coordinator=true
    http-server.http.port=8099
    query.max-memory=80GB
    query.max-memory-per-node=4.8GB
    query.max-total-memory-per-node=4.8GB
    #discovery-server.enabled=true
    discovery.uri=http://presto-coordinator-service:8099

### **deployment coordinator**

> apiVersion: apps/v1
kind: Deployment
metadata:
  name: presto-coordinator
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: presto-coordinator
  template:
    metadata:
      labels:
        app: presto-coordinator
    spec:
      #nodeSelector:
        #type: lab1
      containers:
        - name: presto-coordinator
          imagePullPolicy: Always
          image: 10.38.199.203:8090/library/trino:v.ssl
          ports:
            - name: http-coord
              containerPort: 8099
              protocol: TCP
          env:
            - name: COORDINATOR_NODE
              value: "true"
          volumeMounts:
            - name: presto-config-volume
              mountPath: /opt/bootstrap
              readOnly: false
            - name: presto-data-volume
              mountPath: /opt/presto/data
              readOnly: false
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /v1/cluster
              port: http-coord
      volumes:
        - name: presto-config-volume
          configMap:
            name: presto-config-cm

 

**### service**

> kind: Service
apiVersion: v1
metadata:
  labels:
    app: presto-coordinator
  name: presto-coordinator-service
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - port: 8099
      targetPort: http-coord
      name: http-coord
      protocol: TCP
      nodePort: 30012
  selector:
    app: presto-coordinator

![image](https://user-images.githubusercontent.com/60861212/141922040-f8b168cd-6452-4bb1-92e0-d27afd6ce664.png)

**Comment by ebyhr** [comment]
Could you ask questions in the community Slack so that we can debug interactively? There are `#troubleshooting` and `#kubernetes` channel. Please post in either one. 
https://trino.io/slack.html
