### ISSUE TITLE
interval literal support number?

### ISSUE THREAD

**Issue by waitingF** [trinodb/trino#9975]
currently interval literal only support string, 
`
interval
    : INTERVAL sign=(PLUS | MINUS)? string from=intervalField (TO to=intervalField)?
    ;
`

is there any plan to support number  too? 
maybe like this:
`
interval
    : INTERVAL sign=(PLUS | MINUS)? (string | number) from=intervalField (TO to=intervalField)?
    ;
`

**Comment by ebyhr** [comment]
If I understand ANSI specification correctly, it should be quoted. 

```
<interval literal> ::=
  INTERVAL [ <sign>  ] <interval string>  <interval qualifier> 

<interval string> ::=
  <quote>  <unquoted interval string>  <quote> 
```

cc: @martint @kasiafi
