### ISSUE TITLE
Use 'show columns' can't get Comment from oracle,which DBever shows it has comment.But Can get Comment from MySQL,PostgreSQL

### ISSUE THREAD

**Issue by dawsongzhao** [trinodb/trino#9977]
## From MySQL
`SHOW COLUMNS from mysqldevtms.tms_test.base_address `
![image](https://user-images.githubusercontent.com/7078308/142175452-9080c0be-ffee-4150-8530-53773271b696.png)
## From PG
`SHOW COLUMNS from pgdevbiz.biz.comm_change_header `
![image](https://user-images.githubusercontent.com/7078308/142175575-349a4b36-ffe1-47f3-9548-9db579657bb8.png)
## From Oracle
`SHOW COLUMN from oracledevcrm.cidp_crm.oms_exp_lines `
![image](https://user-images.githubusercontent.com/7078308/142176304-ee66b2fb-b76e-427d-81ad-6c79b31dd4f3.png)

In DBeaver
![image](https://user-images.githubusercontent.com/7078308/142176018-eb930528-c682-4b13-9d27-0576b4b75322.png)

**Comment by ebyhr** [comment]
Please enable `oracle.remarks-reporting.enabled`. 
https://trino.io/docs/current/connector/oracle.html#configuration
