### ISSUE TITLE
Predicates pushdown to REAL type in MySQL and MemSQL return incorrect result

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#9998]
```
trino> create table tpch.test_real (c1 real);
trino> insert into tpch.test_real values (real '3.14');

trino> desc tpch.test_real;
 Column | Type | Extra | Comment 
--------+------+-------+---------
 c1     | real |       |      

trino> select * from tpch.test_real;
  c1  
------
 3.14 

trino> select * from tpch.test_real where c1 = real '3.14';
 c1 
----
(0 rows)
```

I haven't confirmed all connectors, but PostgreSQL works fine.

**Comment by findepi** [comment]
Any clue why this wasn't found by `AbstractTestDistributedQueries#testDataMappingSmokeTest`?

**Comment by ebyhr** [comment]
@findepi Because these connectors were overriding `filterDataMappingSmokeTestData` method even though the type is supported:
```java
        if (typeName.equals("real")
                || typeName.equals("timestamp")) {
            // TODO this should either work or fail cleanly
            return Optional.empty();
        }
```

**Comment by ebyhr** [comment]
@ssheikin Sorry, I don't remember the details. I think the implementation in both JDBC drivers and servers has been changed. It worth checking the latest behavior.

**Comment by ssheikin** [comment]
With `3.14` it's still reproducible for `float`, but not for `double`.
